-- Ekwo OS — Belgium: the rules of this country's corporate income tax.
--
-- Generated from packs/be/corporate_tax.json at version 1.17.1, do not edit.
-- Change the pack and run `ekwo pack build be`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the corporate income tax module.
--
-- Reference data: read where it stands, never copied into a company. A figure
-- that changes is a new row with a new valid_from, so a past year keeps its answer.

insert into tax.country_rules
  (country, tax_code, name, name_i18n, result_statement_code, result_line_code, result_legal_reference, result_source_key, expense_account_code, payable_account_code, receivable_account_code, accounts_legal_reference, accounts_source_key, legal_reference, source_key)
values
  ('BE', 'BE-ISOC', 'Impôt des sociétés', '{"de":"Gesellschaftssteuer","en":"Corporate income tax","nl":"Vennootschapsbelasting"}'::jsonb, 'BE-BNB-ABBR-IS', '9903', 'Arrêté royal du 29 avril 2019, annexe — compte de résultats abrégé, rubrique 9903 « Bénéfice (Perte) de l''exercice avant impôts » ; Code des impôts sur les revenus 1992, art. 198, § 1er, 1° — l''impôt des sociétés et les sommes versées à valoir sur celui-ci ne sont pas des frais professionnels, de sorte que le calcul part du résultat avant impôts', 'comptes-annuels', '670000', '450000', '412000', 'Arrêté royal du 21 octobre 2018, annexe 1 — comptes 670 « Impôts belges sur le résultat de l''exercice », 450 « Dettes fiscales estimées » et 412 « Impôts et versements fiscaux à récupérer »', 'pcmn', 'Code des impôts sur les revenus 1992, titre III — impôt des sociétés', 'cir-92')
on conflict (country) do update set
  tax_code                 = excluded.tax_code,
  name                     = excluded.name,
  name_i18n                = excluded.name_i18n,
  result_statement_code    = excluded.result_statement_code,
  result_line_code         = excluded.result_line_code,
  result_legal_reference   = excluded.result_legal_reference,
  result_source_key        = excluded.result_source_key,
  expense_account_code     = excluded.expense_account_code,
  payable_account_code     = excluded.payable_account_code,
  receivable_account_code  = excluded.receivable_account_code,
  accounts_legal_reference = excluded.accounts_legal_reference,
  accounts_source_key      = excluded.accounts_source_key,
  legal_reference          = excluded.legal_reference,
  source_key               = excluded.source_key;

insert into tax.parameter_templates
  (country, code, name, name_i18n, value_type, legal_reference, source_key, sequence)
values
  ('BE', 'small_company', 'La société est une petite société au sens de l''article 1:24, §§ 1er à 6, du Code des sociétés et des associations', '{"de":"Die Gesellschaft ist eine kleine Gesellschaft im Sinne von Artikel 1:24 §§ 1 bis 6 des Gesetzbuches der Gesellschaften und Vereinigungen","en":"The company is a small company within the meaning of article 1:24, §§ 1 to 6, of the Code of companies and associations","nl":"De vennootschap is een kleine vennootschap in de zin van artikel 1:24, §§ 1 tot 6, van het Wetboek van vennootschappen en verenigingen"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 2 — le taux réduit est réservé aux sociétés considérées comme petites sociétés sur la base de l''article 1:24, §§ 1er à 6, du Code des sociétés et des associations', 'cir-92-ex-2026', 10),
  ('BE', 'approved_cooperative', 'La société est une société coopérative agréée conformément à l''article 8:4 du Code des sociétés et des associations', '{"de":"Die Gesellschaft ist eine gemäß Artikel 8:4 des Gesetzbuches der Gesellschaften und Vereinigungen zugelassene Genossenschaft","en":"The company is a cooperative company approved under article 8:4 of the Code of companies and associations","nl":"De vennootschap is een coöperatieve vennootschap erkend overeenkomstig artikel 8:4 van het Wetboek van vennootschappen en verenigingen"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 1°, 2° et 4° — ces exclusions ne visent pas les sociétés coopératives agréées', 'cir-92-ex-2026', 20),
  ('BE', 'holds_participations_above_half', 'La société détient des actions ou parts dont la valeur d''investissement excède 50 % de la valeur réévaluée du capital libéré, ou du capital libéré augmenté des réserves taxées et des plus-values comptabilisées', '{"de":"Die Gesellschaft hält Aktien oder Anteile, deren Investitionswert 50 % des neu bewerteten eingezahlten Kapitals oder des eingezahlten Kapitals zuzüglich der besteuerten Rücklagen und der gebuchten Mehrwerte übersteigt","en":"The company holds shares whose investment value exceeds 50 % of the revalued paid-up capital, or of the paid-up capital plus taxed reserves and recorded capital gains","nl":"De vennootschap bezit aandelen waarvan de beleggingswaarde meer bedraagt dan 50 % van de gerevaloriseerde waarde van het gestorte kapitaal, of van het gestorte kapitaal verhoogd met de belaste reserves en de geboekte meerwaarden"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 1° — il n''est pas tenu compte des actions ou parts qui représentent au moins 75 % du capital libéré de la société qui les a émises', 'cir-92-ex-2026', 30),
  ('BE', 'held_half_by_companies', 'Les actions ou parts de la société sont détenues à concurrence d''au moins la moitié par une ou plusieurs autres sociétés', '{"de":"Die Aktien oder Anteile der Gesellschaft werden mindestens zur Hälfte von einer oder mehreren anderen Gesellschaften gehalten","en":"At least half of the shares of the company are held by one or more other companies","nl":"De aandelen van de vennootschap zijn voor ten minste de helft in het bezit van een of meer andere vennootschappen"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 2°', 'cir-92-ex-2026', 40),
  ('BE', 'director_remuneration', 'Rémunération la plus élevée allouée à un dirigeant d''entreprise à charge du résultat de la période imposable', '{"de":"Höchste Entlohnung, die einem Unternehmensleiter zu Lasten des Ergebnisses des Besteuerungszeitraums gewährt wurde","en":"Highest remuneration granted to a company director and charged to the result of the taxable period","nl":"Hoogste bezoldiging toegekend aan een bedrijfsleider ten laste van het resultaat van het belastbare tijdperk"}'::jsonb, 'amount'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 4°, tel qu''applicable à l''exercice d''imposition 2026', 'cir-92-ex-2026', 50),
  ('BE', 'within_first_four_periods', 'La période imposable est l''une des quatre premières depuis la constitution de la société', '{"de":"Der Besteuerungszeitraum ist einer der ersten vier seit der Gründung der Gesellschaft","en":"The taxable period is one of the first four since the company was incorporated","nl":"Het belastbare tijdperk is een van de eerste vier sinds de oprichting van de vennootschap"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 4° — la condition de rémunération s''applique à partir de la cinquième période imposable depuis la constitution', 'cir-92-ex-2026', 60),
  ('BE', 'investment_company', 'La société est une société d''investissement, une société immobilière réglementée ou un organisme de financement de pensions visés à l''article 215, alinéa 3, 6°', '{"de":"Die Gesellschaft ist eine Investmentgesellschaft, eine beaufsichtigte Immobiliengesellschaft oder ein Organismus für die Finanzierung von Pensionen im Sinne von Artikel 215 Absatz 3 Nr. 6","en":"The company is an investment company, a regulated real estate company or an organisation for financing pensions covered by article 215, third paragraph, 6°","nl":"De vennootschap is een beleggingsvennootschap, een gereglementeerde vastgoedvennootschap of een organisme voor de financiering van pensioenen bedoeld in artikel 215, derde lid, 6°"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 6°', 'cir-92-ex-2026', 70),
  ('BE', 'director_remuneration_condition_met', 'La société n''est pas exclue du taux réduit par la condition de rémunération minimale d''un dirigeant d''entreprise, telle qu''elle s''applique à partir de l''exercice d''imposition 2027', '{"de":"Die Gesellschaft ist nicht durch die Bedingung der Mindestentlohnung eines Unternehmensleiters, wie sie ab dem Steuerjahr 2027 gilt, vom ermäßigten Satz ausgeschlossen","en":"The company is not excluded from the reduced rate by the minimum director remuneration condition, as it applies from assessment year 2027","nl":"De vennootschap is niet uitgesloten van het verlaagd tarief door de voorwaarde van de minimumbezoldiging van een bedrijfsleider, zoals die geldt vanaf aanslagjaar 2027"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 4°, remplacé par la loi du 15 juillet 2026, art. 80 et 88 — rémunération au moins égale à un montant indexé chaque année, ou au moins égale au revenu imposable de la société. Le montant indexé n''est pas repris dans ce pack : la société déclare si la condition est remplie.', 'loi-2026-07-15', 80),
  ('BE', 'excessive_benefits_in_kind', 'La société alloue à ses dirigeants d''entreprise une part excessive d''avantages de toute nature au sens de l''article 2, § 1er, 25°', '{"de":"Die Gesellschaft gewährt ihren Unternehmensleitern einen übermäßigen Anteil an Vorteilen jeglicher Art im Sinne von Artikel 2 § 1 Nr. 25","en":"The company grants its directors an excessive share of benefits in kind within the meaning of article 2, § 1, 25°","nl":"De vennootschap kent haar bedrijfsleiders een overdreven deel voordelen van alle aard toe in de zin van artikel 2, § 1, 25°"}'::jsonb, 'boolean'::tax.parameter_type, 'Code des impôts sur les revenus 1992, art. 215, al. 3, 5°, rétabli par la loi du 15 juillet 2026, art. 80 et 88 — applicable à partir de l''exercice d''imposition 2027', 'loi-2026-07-15', 90)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  value_type      = excluded.value_type,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key,
  sequence        = excluded.sequence;

insert into tax.adjustment_rule_templates
  (country, code, valid_from, valid_to, valid_on, name, name_i18n, direction, percent, formula, account_rules, legal_reference, source_key, sequence)
values
  ('BE', 'restaurant', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Frais de restaurant — quotité non déductible', '{"de":"Restaurantkosten — nicht abzugsfähiger Anteil","en":"Restaurant costs — non-deductible share","nl":"Restaurantkosten — niet-aftrekbaar gedeelte"}'::jsonb, 'add_back'::tax.adjustment_direction, 31, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 53, 8°bis — 31 % de la quotité professionnelle des frais de restaurant ; art. 53/1 — sauf les frais refacturés à des tiers de manière explicite et séparée', 'cir-92-ex-2026', 10),
  ('BE', 'reception-gifts', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Frais de réception et cadeaux d''affaires — quotité non déductible', '{"de":"Empfangskosten und Geschäftsgeschenke — nicht abzugsfähiger Anteil","en":"Reception costs and business gifts — non-deductible share","nl":"Receptiekosten en relatiegeschenken — niet-aftrekbaar gedeelte"}'::jsonb, 'add_back'::tax.adjustment_direction, 50, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 53, 8° — 50 % de la quotité professionnelle des frais de réception et de cadeaux d''affaires, à l''exclusion des articles publicitaires portant la dénomination de l''entreprise', 'cir-92-ex-2026', 20),
  ('BE', 'fines', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Amendes, confiscations et pénalités de toute nature', '{"de":"Geldbußen, Einziehungen und Strafen jeglicher Art","en":"Fines, confiscations and penalties of any kind","nl":"Geldboeten, verbeurdverklaringen en straffen van alle aard"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 53, 6° — les amendes, y compris transactionnelles et administratives, les confiscations et les pénalités de toute nature', 'cir-92-ex-2026', 30),
  ('BE', 'clothing', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Vêtements non spécifiques', '{"de":"Nicht spezifische Kleidung","en":"Non-specific clothing","nl":"Niet-specifieke kledij"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 53, 7° — les frais de vêtements, sauf s''il s''agit de vêtements professionnels spécifiques', 'cir-92-ex-2026', 40),
  ('BE', 'car-benefit-with-fuel', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Véhicule mis à disposition à des fins personnelles, carburant pris en charge — 40 % de l''avantage de toute nature', '{"de":"Zur persönlichen Nutzung überlassenes Fahrzeug, Kraftstoff übernommen — 40 % des Vorteils jeglicher Art","en":"Vehicle made available for private use, fuel paid by the company — 40 % of the benefit in kind","nl":"Voertuig ter beschikking gesteld voor persoonlijk gebruik, brandstof ten laste genomen — 40 % van het voordeel van alle aard"}'::jsonb, 'add_back'::tax.adjustment_direction, 40, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 198, § 1er, 9° et 9°bis — frais de véhicules à concurrence de 40 % du montant de l''avantage de toute nature lorsque les frais de carburant liés à l''utilisation personnelle sont pris en charge par la société', 'isoc-275-1-2026', 50),
  ('BE', 'car-benefit-without-fuel', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Véhicule mis à disposition à des fins personnelles, sans carburant — 17 % de l''avantage de toute nature', '{"de":"Zur persönlichen Nutzung überlassenes Fahrzeug, ohne Kraftstoff — 17 % des Vorteils jeglicher Art","en":"Vehicle made available for private use, no fuel paid — 17 % of the benefit in kind","nl":"Voertuig ter beschikking gesteld voor persoonlijk gebruik, zonder brandstof — 17 % van het voordeel van alle aard"}'::jsonb, 'add_back'::tax.adjustment_direction, 17, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 198, § 1er, 9° et 9°bis — frais de véhicules à concurrence de 17 % du montant de l''avantage de toute nature lorsque la société ne prend pas le carburant en charge', 'isoc-275-1-2026', 60),
  ('BE', 'car-costs-before-2023-07', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Frais de voiture — véhicules achetés, pris en leasing ou en location avant le 1er juillet 2023', '{"de":"Fahrzeugkosten — vor dem 1. Juli 2023 gekaufte, geleaste oder gemietete Fahrzeuge","en":"Car costs — vehicles bought, leased or rented before 1 July 2023","nl":"Autokosten — voertuigen aangekocht, geleased of gehuurd vóór 1 juli 2023"}'::jsonb, 'add_back'::tax.adjustment_direction, null, '{"coefficient":{"parameter":"fuel","values":{"diesel":1,"natural_gas_under_12_hp":0.9,"other":0.95}},"decimals":1,"intercept":120,"max":100,"min":50,"slope":-0.5,"steps":[{"from":200,"percent":40}],"variable":"co2_g_km","yields":"deductible_percent"}'::jsonb, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 66, § 1er — 120 % − (0,5 % × coefficient × grammes de CO2 par kilomètre), coefficient 1 pour le diesel, 0,95 pour les autres véhicules et 0,90 pour le gaz naturel sous 12 chevaux fiscaux, taux arrondi au dixième, au moins 50 % et au plus 100 %, et 40 % à partir de 200 grammes. Un véhicule commandé avant le 1er juillet 2023 est réputé acheté. Le carburant suit le taux du véhicule ; les hybrides rechargeables dont l''émission est recalculée (art. 66, § 1er, al. 4) déclarent l''émission recalculée.', 'cir-92-ex-2026', 70),
  ('BE', 'car-costs-2023-07-to-2025', date '2025-12-31', date '2026-12-30', 'period_end'::tax.validity_basis, 'Frais de voiture — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025', '{"de":"Fahrzeugkosten — vom 1. Juli 2023 bis zum 31. Dezember 2025 gekaufte, geleaste oder gemietete Fahrzeuge mit CO2-Ausstoß","en":"Car costs — vehicles emitting CO2 bought, leased or rented from 1 July 2023 to 31 December 2025","nl":"Autokosten — voertuigen met CO2-uitstoot aangekocht, geleased of gehuurd van 1 juli 2023 tot 31 december 2025"}'::jsonb, 'add_back'::tax.adjustment_direction, null, '{"coefficient":{"parameter":"fuel","values":{"diesel":1,"natural_gas_under_12_hp":0.9,"other":0.95}},"decimals":1,"intercept":120,"max":75,"min":0,"slope":-0.5,"variable":"co2_g_km","yields":"deductible_percent"}'::jsonb, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 66, § 1er, et art. 550 — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025 : la formule 120 % − (0,5 % × coefficient × grammes de CO2 par kilomètre) s''applique sans minimum, y compris à partir de 200 grammes, et le taux est plafonné à 75 % pour l''exercice d''imposition 2026', 'cir-92-ex-2026', 80),
  ('BE', 'car-costs-2023-07-to-2025', date '2026-12-31', date '2027-12-30', 'period_end'::tax.validity_basis, 'Frais de voiture — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025', '{"de":"Fahrzeugkosten — vom 1. Juli 2023 bis zum 31. Dezember 2025 gekaufte, geleaste oder gemietete Fahrzeuge mit CO2-Ausstoß","en":"Car costs — vehicles emitting CO2 bought, leased or rented from 1 July 2023 to 31 December 2025","nl":"Autokosten — voertuigen met CO2-uitstoot aangekocht, geleased of gehuurd van 1 juli 2023 tot 31 december 2025"}'::jsonb, 'add_back'::tax.adjustment_direction, null, '{"coefficient":{"parameter":"fuel","values":{"diesel":1,"natural_gas_under_12_hp":0.9,"other":0.95}},"decimals":1,"intercept":120,"max":50,"min":0,"slope":-0.5,"variable":"co2_g_km","yields":"deductible_percent"}'::jsonb, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 66, § 1er, et art. 550 — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025 : la formule 120 % − (0,5 % × coefficient × grammes de CO2 par kilomètre) s''applique sans minimum, y compris à partir de 200 grammes, et le taux est plafonné à 50 % pour l''exercice d''imposition 2027 (loi du 18 décembre 2025, art. 26)', 'loi-2025-12-18', 80),
  ('BE', 'car-costs-2023-07-to-2025', date '2027-12-31', date '2028-12-30', 'period_end'::tax.validity_basis, 'Frais de voiture — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025', '{"de":"Fahrzeugkosten — vom 1. Juli 2023 bis zum 31. Dezember 2025 gekaufte, geleaste oder gemietete Fahrzeuge mit CO2-Ausstoß","en":"Car costs — vehicles emitting CO2 bought, leased or rented from 1 July 2023 to 31 December 2025","nl":"Autokosten — voertuigen met CO2-uitstoot aangekocht, geleased of gehuurd van 1 juli 2023 tot 31 december 2025"}'::jsonb, 'add_back'::tax.adjustment_direction, null, '{"coefficient":{"parameter":"fuel","values":{"diesel":1,"natural_gas_under_12_hp":0.9,"other":0.95}},"decimals":1,"intercept":120,"max":25,"min":0,"slope":-0.5,"variable":"co2_g_km","yields":"deductible_percent"}'::jsonb, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 66, § 1er, et art. 550 — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025 : la formule 120 % − (0,5 % × coefficient × grammes de CO2 par kilomètre) s''applique sans minimum, y compris à partir de 200 grammes, et le taux est plafonné à 25 % pour l''exercice d''imposition 2028 (circulaire relative au verdissement fiscal de la mobilité)', 'verdissement-mobilite', 80),
  ('BE', 'car-costs-2023-07-to-2025', date '2028-12-31', null, 'period_end'::tax.validity_basis, 'Frais de voiture — véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025', '{"de":"Fahrzeugkosten — vom 1. Juli 2023 bis zum 31. Dezember 2025 gekaufte, geleaste oder gemietete Fahrzeuge mit CO2-Ausstoß","en":"Car costs — vehicles emitting CO2 bought, leased or rented from 1 July 2023 to 31 December 2025","nl":"Autokosten — voertuigen met CO2-uitstoot aangekocht, geleased of gehuurd van 1 juli 2023 tot 31 december 2025"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Circulaire relative au verdissement fiscal de la mobilité — à partir de l''exercice d''imposition 2029, les frais des véhicules émettant du CO2 achetés, pris en leasing ou en location du 1er juillet 2023 au 31 décembre 2025 ne sont plus déductibles', 'verdissement-mobilite', 80),
  ('BE', 'car-costs-from-2026', date '2025-12-31', null, 'period_end'::tax.validity_basis, 'Frais de voiture — véhicules émettant du CO2 achetés, pris en leasing ou en location à partir du 1er janvier 2026', '{"de":"Fahrzeugkosten — ab dem 1. Januar 2026 gekaufte, geleaste oder gemietete Fahrzeuge mit CO2-Ausstoß","en":"Car costs — vehicles emitting CO2 bought, leased or rented from 1 January 2026","nl":"Autokosten — voertuigen met CO2-uitstoot aangekocht, geleased of gehuurd vanaf 1 januari 2026"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 66, § 1er, et art. 198bis ; circulaire relative au verdissement fiscal de la mobilité — les frais des véhicules dont l''émission de CO2 est supérieure à zéro achetés, pris en leasing ou en location à partir du 1er janvier 2026 ne sont plus déductibles. Dans le chef des sociétés, le régime transitoire des hybrides rechargeables (art. 66, § 1er/1) ne s''applique pas.', 'verdissement-mobilite', 90)
on conflict (country, code, valid_from) do update set
  valid_to        = excluded.valid_to,
  valid_on        = excluded.valid_on,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  direction       = excluded.direction,
  percent         = excluded.percent,
  formula         = excluded.formula,
  account_rules   = excluded.account_rules,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key,
  sequence        = excluded.sequence;

insert into tax.rate_templates
  (country, code, valid_from, valid_to, valid_on, name, name_i18n, rate, up_to, up_to_prorata, conditions, legal_reference, source_key, sequence)
values
  ('BE', 'reduced-small', date '2025-12-31', date '2026-12-30', 'period_end'::tax.validity_basis, 'Taux réduit des petites sociétés sur la première tranche', '{"de":"Ermäßigter Satz für kleine Gesellschaften auf die erste Teilbetragsstufe","en":"Reduced rate for small companies on the first bracket","nl":"Verlaagd tarief voor kleine vennootschappen op de eerste schijf"}'::jsonb, 20, 100000, 'none', '[{"parameter":"small_company","test":"is_true"},{"parameter":"holds_participations_above_half","test":"is_false","waived_by":["approved_cooperative"]},{"parameter":"held_half_by_companies","test":"is_false","waived_by":["approved_cooperative"]},{"amount":45000,"or_at_least":"taxable_base","parameter":"director_remuneration","test":"at_least","waived_by":["within_first_four_periods","approved_cooperative"]},{"parameter":"investment_company","test":"is_false"}]'::jsonb, 'Code des impôts sur les revenus 1992, art. 215, al. 2 et 3, exercice d''imposition 2026 — 20 % sur la première tranche de 0 à 100 000 EUR pour les petites sociétés, sauf les exclusions de l''alinéa 3 : participations (1°), détention par d''autres sociétés (2°), rémunération d''un dirigeant inférieure à 45 000 EUR et au revenu imposable à partir de la cinquième période imposable (4°), sociétés d''investissement (6°)', 'cir-92-ex-2026', 10),
  ('BE', 'reduced-small', date '2026-12-31', null, 'period_end'::tax.validity_basis, 'Taux réduit des petites sociétés sur la première tranche', '{"de":"Ermäßigter Satz für kleine Gesellschaften auf die erste Teilbetragsstufe","en":"Reduced rate for small companies on the first bracket","nl":"Verlaagd tarief voor kleine vennootschappen op de eerste schijf"}'::jsonb, 20, 100000, 'none', '[{"parameter":"small_company","test":"is_true"},{"parameter":"holds_participations_above_half","test":"is_false","waived_by":["approved_cooperative"]},{"parameter":"held_half_by_companies","test":"is_false","waived_by":["approved_cooperative"]},{"parameter":"director_remuneration_condition_met","test":"is_true","waived_by":["within_first_four_periods","approved_cooperative"]},{"parameter":"excessive_benefits_in_kind","test":"is_false"},{"parameter":"investment_company","test":"is_false"}]'::jsonb, 'Code des impôts sur les revenus 1992, art. 215, al. 2 et 3, tel que modifié par la loi du 15 juillet 2026, art. 80 et 88, à partir de l''exercice d''imposition 2027 — 20 % sur la première tranche de 0 à 100 000 EUR ; la condition de rémunération du 4° porte sur un montant indexé chaque année et le 5° exclut les sociétés qui allouent une part excessive d''avantages de toute nature à leurs dirigeants', 'loi-2026-07-15', 10),
  ('BE', 'standard', date '2020-01-01', null, 'period_start'::tax.validity_basis, 'Taux ordinaire', '{"de":"Normaler Satz","en":"Standard rate","nl":"Gewoon tarief"}'::jsonb, 25, null, 'none', '[]'::jsonb, 'Code des impôts sur les revenus 1992, art. 215, al. 1er — 25 %, à partir de l''exercice d''imposition 2021 et pour les périodes imposables débutant au plus tôt le 1er janvier 2020', 'cir-92-ex-2026', 20)
on conflict (country, code, valid_from) do update set
  valid_to        = excluded.valid_to,
  valid_on        = excluded.valid_on,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  rate            = excluded.rate,
  up_to           = excluded.up_to,
  up_to_prorata   = excluded.up_to_prorata,
  conditions      = excluded.conditions,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key,
  sequence        = excluded.sequence;

insert into tax.loss_rule_templates
  (country, valid_from, valid_to, valid_on, floor_amount, percent_above, carry_forward_years, legal_reference, source_key)
values
  ('BE', date '2025-12-31', null, 'period_end'::tax.validity_basis, 1000000, 70, null, 'Code des impôts sur les revenus 1992, art. 206, § 1er — les pertes professionnelles antérieures sont déduites successivement des revenus de chacune des périodes imposables suivantes ; art. 207, al. 3 et 5 — le total des déductions de la « corbeille », dont les pertes antérieures, est limité à 1 000 000 EUR majoré de 70 % de la quotité du bénéfice qui excède ce montant. Les autres déductions de la corbeille et l''exception des petites sociétés pendant leurs quatre premières périodes imposables (al. 6) ne sont pas calculées ici.', 'cir-92-ex-2026')
on conflict (country, valid_from) do update set
  valid_to            = excluded.valid_to,
  valid_on            = excluded.valid_on,
  floor_amount        = excluded.floor_amount,
  percent_above       = excluded.percent_above,
  carry_forward_years = excluded.carry_forward_years,
  legal_reference     = excluded.legal_reference,
  source_key          = excluded.source_key;

insert into tax.prepayment_templates
  (country, valid_from, valid_to, valid_on, method, month_basis, instalments, surcharge_percent, exempt_up_to, legal_reference, source_key)
values
  ('BE', date '2026-12-31', date '2027-12-30', 'period_end'::tax.validity_basis, 'surcharge_on_shortfall', 'calendar', '[{"credit_percent":9,"day":10,"month":4,"sequence":1},{"credit_percent":7.5,"day":10,"month":7,"sequence":2},{"credit_percent":6,"day":10,"month":10,"sequence":3},{"credit_percent":4.5,"day":20,"month":12,"sequence":4}]'::jsonb, 6.75, null, 'Code des impôts sur les revenus 1992, art. 159, 161 et 218 — majoration pour absence ou insuffisance de versements anticipés ; taux de l''exercice d''imposition 2027 (revenus 2026) publiés par le SPF Finances : majoration de 6,75 %, avantages de 9 %, 7,5 %, 6 % et 4,5 %. Échéances légales d''une société dont l''exercice coïncide avec l''année civile : 10 avril, 10 juillet, 10 octobre et 20 décembre ; une échéance qui tombe un jour non ouvrable est reportée. Aucune majoration n''est due par une petite société pour ses trois premiers exercices comptables (art. 218, § 2).', 'versements-anticipes')
on conflict (country, valid_from) do update set
  valid_to          = excluded.valid_to,
  valid_on          = excluded.valid_on,
  method            = excluded.method,
  month_basis       = excluded.month_basis,
  instalments       = excluded.instalments,
  surcharge_percent = excluded.surcharge_percent,
  exempt_up_to      = excluded.exempt_up_to,
  legal_reference   = excluded.legal_reference,
  source_key        = excluded.source_key;
