-- Ekwo OS — España: the rules of this country's corporate income tax.
--
-- Generated from packs/es/corporate_tax.json at version 0.5.0, do not edit.
-- Change the pack and run `ekwo pack build es`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the corporate income tax module.
--
-- Reference data: read where it stands, never copied into a company. A figure
-- that changes is a new row with a new valid_from, so a past year keeps its answer.

insert into tax.country_rules
  (country, tax_code, name, name_i18n, result_statement_code, result_line_code, result_legal_reference, result_source_key, expense_account_code, payable_account_code, receivable_account_code, accounts_legal_reference, accounts_source_key, legal_reference, source_key)
values
  ('ES', 'ES-IS', 'Impuesto sobre Sociedades', '{"en":"Corporate income tax"}'::jsonb, 'ES-PGC-PGA', 'C', 'Real Decreto 1514/2007, Plan General de Contabilidad, tercera parte — modelo de cuenta de pérdidas y ganancias abreviada, línea C) «Resultado antes de impuestos»; Ley 27/2014, art. 15.b) — los gastos derivados de la contabilización del Impuesto sobre Sociedades no son deducibles, de modo que el cálculo parte del resultado antes de impuestos y la cuenta 630 no entra', 'pgc', '6300', '4752', '4709', 'Real Decreto 1514/2007, Plan General de Contabilidad, cuarta parte — cuadro de cuentas: 6300 «Impuesto corriente» (grupo 63, «Impuesto sobre beneficios»), 4752 «Hacienda Pública, acreedora por impuesto sobre sociedades» y 4709 «Hacienda Pública, deudora por devolución de impuestos»', 'pgc', 'Ley 27/2014, de 27 de noviembre, del Impuesto sobre Sociedades', 'lis')
on conflict (country) do update set
  tax_code                 = excluded.tax_code,
  name                     = excluded.name,
  name_i18n                = excluded.name_i18n,
  result_statement_code    = excluded.result_statement_code,
  result_line_code         = excluded.result_line_code,
  result_legal_reference   = excluded.result_legal_reference,
  result_source_key        = excluded.result_source_key,
  expense_account_code     = excluded.expense_account_code,
  payable_account_code     = excluded.payable_account_code,
  receivable_account_code  = excluded.receivable_account_code,
  accounts_legal_reference = excluded.accounts_legal_reference,
  accounts_source_key      = excluded.accounts_source_key,
  legal_reference          = excluded.legal_reference,
  source_key               = excluded.source_key;

insert into tax.parameter_templates
  (country, code, name, name_i18n, value_type, legal_reference, source_key, sequence)
values
  ('ES', 'turnover_prior_period', 'Importe neto de la cifra de negocios del período impositivo inmediato anterior, determinado según el artículo 101, apartados 2 y 3, de la Ley 27/2014 (elevado al año y, en un grupo, el del conjunto)', '{"en":"Net turnover of the immediately preceding tax period, determined under article 101, paragraphs 2 and 3, of Law 27/2014 (restated to a year and, in a group, that of the whole group)"}'::jsonb, 'amount'::tax.parameter_type, 'Ley 27/2014, art. 29.1 — escala de las entidades cuyo importe neto de la cifra de negocios del período impositivo inmediato anterior sea inferior a 1 millón de euros, determinado con arreglo al art. 101, apartados 2 y 3', 'lis', 10),
  ('ES', 'reduced_size', 'La entidad cumple las condiciones del artículo 101 de la Ley 27/2014 (entidad de reducida dimensión: cifra de negocios del período inmediato anterior inferior a 10 millones de euros, con las reglas de grupo, de nueva creación y de permanencia de ese artículo)', '{"en":"The entity meets the conditions of article 101 of Law 27/2014 (reduced-size entity: turnover of the preceding period under 10 million euros, with that article''s rules on groups, new entities and the three further periods)"}'::jsonb, 'boolean'::tax.parameter_type, 'Ley 27/2014, art. 101, apartados 1 a 4 — la cifra de 10 millones de euros se refiere al conjunto de un grupo (art. 42 del Código de Comercio) y se mantiene tres períodos más cuando se supera, si se cumplieron las condiciones en el período y en los dos anteriores a ese', 'lis', 20),
  ('ES', 'asset_holding_entity', 'La entidad es una entidad patrimonial en los términos del artículo 5.2 de la Ley 27/2014', '{"en":"The entity is an asset-holding entity within the meaning of article 5.2 of Law 27/2014"}'::jsonb, 'boolean'::tax.parameter_type, 'Ley 27/2014, art. 29.1 — los tipos reducidos no se aplican a las entidades patrimoniales (art. 5.2); art. 101.1 — los incentivos del capítulo de las entidades de reducida dimensión tampoco', 'lis', 30),
  ('ES', 'new_entity', 'La entidad es de nueva creación y realiza actividades económicas, y este es el primer período impositivo en que su base imponible resulta positiva o el siguiente (artículo 29.1 de la Ley 27/2014)', '{"en":"The entity is newly created and carries on an economic activity, and this is the first tax period in which its taxable base is positive, or the next one (article 29.1 of Law 27/2014)"}'::jsonb, 'boolean'::tax.parameter_type, 'Ley 27/2014, art. 29.1 — 15 por ciento en el primer período impositivo en que la base imponible resulte positiva y en el siguiente; no se entiende iniciada una actividad económica cuando la ejerció antes una persona o entidad vinculada o una persona física con más del 50 por ciento de la entidad, y una entidad de un grupo del art. 42 del Código de Comercio no es de nueva creación', 'lis', 40)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  value_type      = excluded.value_type,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key,
  sequence        = excluded.sequence;

insert into tax.adjustment_rule_templates
  (country, code, valid_from, valid_to, valid_on, name, name_i18n, direction, percent, formula, account_rules, legal_reference, source_key, sequence)
values
  ('ES', 'fines-penalties', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'Multas y sanciones penales y administrativas, recargos del período ejecutivo y recargo por declaración extemporánea', '{"en":"Criminal and administrative fines and penalties, enforcement surcharges and the surcharge for late filing"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Ley 27/2014, art. 15.c) — no tienen la consideración de gastos fiscalmente deducibles las multas y sanciones penales y administrativas, los recargos del período ejecutivo y el recargo por declaración extemporánea sin requerimiento previo. El plan de cuentas no tiene cuenta propia para ellas: la sociedad declara el importe', 'lis', 10),
  ('ES', 'gambling-losses', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'Pérdidas del juego', '{"en":"Gambling losses"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Ley 27/2014, art. 15.d) — no tienen la consideración de gastos fiscalmente deducibles las pérdidas del juego', 'lis', 20),
  ('ES', 'donations', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'Donativos y liberalidades', '{"en":"Donations and acts of generosity"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Ley 27/2014, art. 15.e) — no son gastos fiscalmente deducibles los donativos y liberalidades; la misma letra deja fuera de ellos los gastos por atenciones a clientes o proveedores (deducibles hasta el 1 por ciento del importe neto de la cifra de negocios), los usos y costumbres con el personal, los de promoción de ventas y servicios y los correlacionados con los ingresos. La sociedad declara solo el importe que es donativo o liberalidad', 'lis', 30),
  ('ES', 'unlawful-expenses', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'Gastos de actuaciones contrarias al ordenamiento jurídico', '{"en":"Expenses of acts contrary to the legal order"}'::jsonb, 'add_back'::tax.adjustment_direction, 100, null, '[]'::jsonb, 'Ley 27/2014, art. 15.f) — no tienen la consideración de gastos fiscalmente deducibles los gastos de actuaciones contrarias al ordenamiento jurídico', 'lis', 40)
on conflict (country, code, valid_from) do update set
  valid_to        = excluded.valid_to,
  valid_on        = excluded.valid_on,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  direction       = excluded.direction,
  percent         = excluded.percent,
  formula         = excluded.formula,
  account_rules   = excluded.account_rules,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key,
  sequence        = excluded.sequence;

insert into tax.rate_templates
  (country, code, valid_from, valid_to, valid_on, name, name_i18n, rate, up_to, up_to_prorata, conditions, legal_reference, source_key, sequence)
values
  ('ES', 'micro-first-slice', date '2025-01-01', date '2025-12-31', 'period_start'::tax.validity_basis, 'Microempresas: tipo sobre la parte de la base hasta 50.000 euros', '{"en":"Micro-enterprises: rate on the part of the base up to 50,000 euros"}'::jsonb, 21, 50000, 'months', '[{"amount":1000000,"parameter":"turnover_prior_period","test":"below"},{"parameter":"asset_holding_entity","test":"is_false"},{"parameter":"new_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 1.a) — períodos impositivos que se inicien dentro del año 2025: 21 por ciento hasta 50.000 euros de base imponible y 22 por ciento por el resto — importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 1 millón de euros, determinado según el art. 101, apartados 2 y 3; cuando el período sea inferior al año, el tramo es 50.000 euros por la proporción de días entre 365 (el pack lo reparte por meses); no se aplica a las entidades patrimoniales ni a las de nueva creación, que tributan al 15 por ciento', 'lis', 10),
  ('ES', 'micro-first-slice', date '2026-01-01', date '2026-12-31', 'period_start'::tax.validity_basis, 'Microempresas: tipo sobre la parte de la base hasta 50.000 euros', '{"en":"Micro-enterprises: rate on the part of the base up to 50,000 euros"}'::jsonb, 19, 50000, 'months', '[{"amount":1000000,"parameter":"turnover_prior_period","test":"below"},{"parameter":"asset_holding_entity","test":"is_false"},{"parameter":"new_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 2.a) — períodos impositivos que se inicien dentro del año 2026: 19 por ciento hasta 50.000 euros de base imponible y 21 por ciento por el resto — importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 1 millón de euros, determinado según el art. 101, apartados 2 y 3; cuando el período sea inferior al año, el tramo es 50.000 euros por la proporción de días entre 365 (el pack lo reparte por meses); no se aplica a las entidades patrimoniales ni a las de nueva creación, que tributan al 15 por ciento', 'lis', 10),
  ('ES', 'micro-first-slice', date '2027-01-01', null, 'period_start'::tax.validity_basis, 'Microempresas: tipo sobre la parte de la base hasta 50.000 euros', '{"en":"Micro-enterprises: rate on the part of the base up to 50,000 euros"}'::jsonb, 17, 50000, 'months', '[{"amount":1000000,"parameter":"turnover_prior_period","test":"below"},{"parameter":"asset_holding_entity","test":"is_false"},{"parameter":"new_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, art. 29.1, letras a) y b) — escala de las entidades con cifra de negocios inferior a 1 millón de euros: 17 por ciento hasta 50.000 euros y 20 por ciento por el resto; la disposición transitoria cuadragésima cuarta no prevé escala propia para los períodos que se inicien desde 2027, y el manual de la AEAT (Sociedades 2025, tipos de gravamen) da 17 y 20 por ciento para 2027 y 2028 — importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 1 millón de euros, determinado según el art. 101, apartados 2 y 3; cuando el período sea inferior al año, el tramo es 50.000 euros por la proporción de días entre 365 (el pack lo reparte por meses); no se aplica a las entidades patrimoniales ni a las de nueva creación, que tributan al 15 por ciento', 'lis', 10),
  ('ES', 'new-entity', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'Entidades de nueva creación: tipo del 15 %', '{"en":"Newly created entities: 15 % rate"}'::jsonb, 15, null, 'none', '[{"parameter":"new_entity","test":"is_true"},{"parameter":"asset_holding_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, art. 29.1 — las entidades de nueva creación que realicen actividades económicas tributan al 15 por ciento en el primer período impositivo en que la base imponible resulte positiva y en el siguiente, salvo que deban tributar a un tipo inferior; no se entiende iniciada una actividad económica cuando fue realizada antes por personas o entidades vinculadas o por una persona física que posea más del 50 por ciento de la entidad, y las entidades que forman parte de un grupo del art. 42 del Código de Comercio no son de nueva creación; el tipo no se aplica a las entidades patrimoniales (art. 5.2). AEAT, Tipos de gravamen 2025: 15 %', 'lis', 10),
  ('ES', 'micro-remainder', date '2025-01-01', date '2025-12-31', 'period_start'::tax.validity_basis, 'Microempresas: tipo sobre la parte de la base que excede de 50.000 euros', '{"en":"Micro-enterprises: rate on the part of the base above 50,000 euros"}'::jsonb, 22, null, 'none', '[{"amount":1000000,"parameter":"turnover_prior_period","test":"below"},{"parameter":"asset_holding_entity","test":"is_false"},{"parameter":"new_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 1.a) — períodos impositivos que se inicien dentro del año 2025: 21 por ciento hasta 50.000 euros de base imponible y 22 por ciento por el resto — importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 1 millón de euros, determinado según el art. 101, apartados 2 y 3; cuando el período sea inferior al año, el tramo es 50.000 euros por la proporción de días entre 365 (el pack lo reparte por meses); no se aplica a las entidades patrimoniales ni a las de nueva creación, que tributan al 15 por ciento', 'lis', 20),
  ('ES', 'micro-remainder', date '2026-01-01', date '2026-12-31', 'period_start'::tax.validity_basis, 'Microempresas: tipo sobre la parte de la base que excede de 50.000 euros', '{"en":"Micro-enterprises: rate on the part of the base above 50,000 euros"}'::jsonb, 21, null, 'none', '[{"amount":1000000,"parameter":"turnover_prior_period","test":"below"},{"parameter":"asset_holding_entity","test":"is_false"},{"parameter":"new_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 2.a) — períodos impositivos que se inicien dentro del año 2026: 19 por ciento hasta 50.000 euros de base imponible y 21 por ciento por el resto — importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 1 millón de euros, determinado según el art. 101, apartados 2 y 3; cuando el período sea inferior al año, el tramo es 50.000 euros por la proporción de días entre 365 (el pack lo reparte por meses); no se aplica a las entidades patrimoniales ni a las de nueva creación, que tributan al 15 por ciento', 'lis', 20),
  ('ES', 'micro-remainder', date '2027-01-01', null, 'period_start'::tax.validity_basis, 'Microempresas: tipo sobre la parte de la base que excede de 50.000 euros', '{"en":"Micro-enterprises: rate on the part of the base above 50,000 euros"}'::jsonb, 20, null, 'none', '[{"amount":1000000,"parameter":"turnover_prior_period","test":"below"},{"parameter":"asset_holding_entity","test":"is_false"},{"parameter":"new_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, art. 29.1, letras a) y b) — escala de las entidades con cifra de negocios inferior a 1 millón de euros: 17 por ciento hasta 50.000 euros y 20 por ciento por el resto; la disposición transitoria cuadragésima cuarta no prevé escala propia para los períodos que se inicien desde 2027, y el manual de la AEAT (Sociedades 2025, tipos de gravamen) da 17 y 20 por ciento para 2027 y 2028 — importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 1 millón de euros, determinado según el art. 101, apartados 2 y 3; cuando el período sea inferior al año, el tramo es 50.000 euros por la proporción de días entre 365 (el pack lo reparte por meses); no se aplica a las entidades patrimoniales ni a las de nueva creación, que tributan al 15 por ciento', 'lis', 20),
  ('ES', 'reduced-size', date '2025-01-01', date '2025-12-31', 'period_start'::tax.validity_basis, 'Entidades de reducida dimensión: tipo sobre toda la base', '{"en":"Reduced-size entities: rate on the whole base"}'::jsonb, 24, null, 'none', '[{"parameter":"reduced_size","test":"is_true"},{"parameter":"asset_holding_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 1.b) — períodos impositivos que se inicien dentro del año 2025: 24 por ciento — entidades que cumplen el art. 101 (importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 10 millones de euros, con las reglas de grupo, nueva creación y permanencia de los apartados 2 a 4 del mismo artículo); el art. 101.1 excluye a las entidades patrimoniales (art. 5.2) y el manual de la AEAT (Sociedades 2025) las mantiene al 25 por ciento', 'lis', 30),
  ('ES', 'reduced-size', date '2026-01-01', date '2026-12-31', 'period_start'::tax.validity_basis, 'Entidades de reducida dimensión: tipo sobre toda la base', '{"en":"Reduced-size entities: rate on the whole base"}'::jsonb, 23, null, 'none', '[{"parameter":"reduced_size","test":"is_true"},{"parameter":"asset_holding_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 2.b) — períodos impositivos que se inicien dentro del año 2026: 23 por ciento — entidades que cumplen el art. 101 (importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 10 millones de euros, con las reglas de grupo, nueva creación y permanencia de los apartados 2 a 4 del mismo artículo); el art. 101.1 excluye a las entidades patrimoniales (art. 5.2) y el manual de la AEAT (Sociedades 2025) las mantiene al 25 por ciento', 'lis', 30),
  ('ES', 'reduced-size', date '2027-01-01', date '2027-12-31', 'period_start'::tax.validity_basis, 'Entidades de reducida dimensión: tipo sobre toda la base', '{"en":"Reduced-size entities: rate on the whole base"}'::jsonb, 22, null, 'none', '[{"parameter":"reduced_size","test":"is_true"},{"parameter":"asset_holding_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 3 — períodos impositivos que se inicien dentro del año 2027: 22 por ciento — entidades que cumplen el art. 101 (importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 10 millones de euros, con las reglas de grupo, nueva creación y permanencia de los apartados 2 a 4 del mismo artículo); el art. 101.1 excluye a las entidades patrimoniales (art. 5.2) y el manual de la AEAT (Sociedades 2025) las mantiene al 25 por ciento', 'lis', 30),
  ('ES', 'reduced-size', date '2028-01-01', date '2028-12-31', 'period_start'::tax.validity_basis, 'Entidades de reducida dimensión: tipo sobre toda la base', '{"en":"Reduced-size entities: rate on the whole base"}'::jsonb, 21, null, 'none', '[{"parameter":"reduced_size","test":"is_true"},{"parameter":"asset_holding_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, disposición transitoria cuadragésima cuarta, apartado 4 — períodos impositivos que se inicien dentro del año 2028: 21 por ciento — entidades que cumplen el art. 101 (importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 10 millones de euros, con las reglas de grupo, nueva creación y permanencia de los apartados 2 a 4 del mismo artículo); el art. 101.1 excluye a las entidades patrimoniales (art. 5.2) y el manual de la AEAT (Sociedades 2025) las mantiene al 25 por ciento', 'lis', 30),
  ('ES', 'reduced-size', date '2029-01-01', null, 'period_start'::tax.validity_basis, 'Entidades de reducida dimensión: tipo sobre toda la base', '{"en":"Reduced-size entities: rate on the whole base"}'::jsonb, 20, null, 'none', '[{"parameter":"reduced_size","test":"is_true"},{"parameter":"asset_holding_entity","test":"is_false"}]'::jsonb, 'Ley 27/2014, art. 29.1 — las entidades que cumplan las previsiones del art. 101 tributan al 20 por ciento; la disposición transitoria cuadragésima cuarta no prevé tipo propio para los períodos que se inicien desde 2029 — entidades que cumplen el art. 101 (importe neto de la cifra de negocios del período impositivo inmediato anterior inferior a 10 millones de euros, con las reglas de grupo, nueva creación y permanencia de los apartados 2 a 4 del mismo artículo); el art. 101.1 excluye a las entidades patrimoniales (art. 5.2) y el manual de la AEAT (Sociedades 2025) las mantiene al 25 por ciento', 'lis', 30),
  ('ES', 'standard', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'Tipo general', '{"en":"Standard rate"}'::jsonb, 25, null, 'none', '[]'::jsonb, 'Ley 27/2014, art. 29.1 — el tipo general de gravamen de los contribuyentes del Impuesto es el 25 por ciento, salvo que deban tributar a un tipo diferente; AEAT, Tipos de gravamen 2025: 25 %', 'lis', 40)
on conflict (country, code, valid_from) do update set
  valid_to        = excluded.valid_to,
  valid_on        = excluded.valid_on,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  rate            = excluded.rate,
  up_to           = excluded.up_to,
  up_to_prorata   = excluded.up_to_prorata,
  conditions      = excluded.conditions,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key,
  sequence        = excluded.sequence;

insert into tax.prepayment_templates
  (country, valid_from, valid_to, valid_on, method, month_basis, instalments, surcharge_percent, exempt_up_to, legal_reference, source_key)
values
  ('ES', date '2025-01-01', null, 'period_start'::tax.validity_basis, 'share_of_reference_tax', 'calendar', '[{"day":20,"month":4,"sequence":1,"share_percent":18},{"day":20,"month":10,"sequence":2,"share_percent":18},{"day":20,"month":12,"sequence":3,"share_percent":18}]'::jsonb, null, null, 'Ley 27/2014, art. 40.1 y 40.2 — pago fraccionado en los primeros 20 días naturales de abril, octubre y diciembre, a cuenta del período impositivo en curso el día 1 de cada uno de esos meses; su base es la cuota íntegra del último período cuyo plazo de declaración estuviese vencido, minorada en las deducciones y bonificaciones y en las retenciones e ingresos a cuenta de aquel, y la cuantía es el 18 por ciento de esa base; no lo efectúan las entidades del art. 29, apartados 4 y 5. La modalidad del art. 40.3 y el art. 40.4 (porcentajes modificables por la Ley de Presupuestos) no se calculan', 'lis')
on conflict (country, valid_from) do update set
  valid_to          = excluded.valid_to,
  valid_on          = excluded.valid_on,
  method            = excluded.method,
  month_basis       = excluded.month_basis,
  instalments       = excluded.instalments,
  surcharge_percent = excluded.surcharge_percent,
  exempt_up_to      = excluded.exempt_up_to,
  legal_reference   = excluded.legal_reference,
  source_key        = excluded.source_key;
