-- Ekwo OS — United States: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/us/assets.json at version 0.6.0, do not edit.
-- Change the pack and run `ekwo pack build us`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the `assets` module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('US', 'months', 'months', 'actual', null, true, 'net_result', 'FASB Accounting Standards Codification topic 360 — depreciation begins when an asset is ready for its intended use, so the charge runs from the month the asset is placed in service and not for the whole of the first year. The Codification prescribes no method and names the straight line, the units of production and the declining balance among those an entity may select, so nothing here caps a declining rate. What this section is **not** is the Modified Accelerated Cost Recovery System: the Internal Revenue Service''s conventions — the half-year convention, the mid-quarter convention, the mid-month convention for real property — belong to a tax return and never to the books. A company that keeps both keeps two sets of figures for one asset, and the module carries one; the gap is written up in docs/international.md.')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('US', 'goodwill', 'Goodwill', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 10, 'A public business entity does not amortise goodwill at all under the Codification: it tests it for impairment. A private company that has elected the accounting alternative of topic 350 amortises it over ten years or less, and this category is that election.   There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'intangibles', 'Other intangible assets, patents and licences', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 20, 'An intangible asset with a finite useful life is amortised over that life under topic 350; one with an indefinite life is not amortised and is tested for impairment instead, and no category of this section can express that.   There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'buildings', 'Buildings', '{}'::jsonb, 'straight_line', 468, null, null, 'asset_fixed', 30, 'Land is not depreciated and the building on it is, so a property is split before this category reaches the part that has a life. Thirty-nine years is the figure American practice reaches for most commercial buildings, and it is worth saying out loud that it is also the recovery period MACRS gives to non-residential real property: the two agree by habit and not by rule, and nothing makes the accounting life follow the tax one.   There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'building-improvements', 'Building improvements', '{}'::jsonb, 'straight_line', 180, null, null, 'asset_fixed', 40, 'There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'leasehold-improvements', 'Leasehold improvements', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 50, 'Practice amortises a leasehold improvement over the shorter of its own life and the remaining term of the lease, which is a fact about the lease and not about the category.   There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'machinery-and-equipment', 'Machinery and equipment', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 60, 'There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'furniture-and-fixtures', 'Furniture and fixtures', '{}'::jsonb, 'straight_line', 84, null, null, 'asset_fixed', 70, 'There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'computer-equipment', 'Computer equipment', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 80, 'There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'computer-software', 'Computer software', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 90, 'There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'vehicles', 'Vehicles, straight line', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 100, 'There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'vehicles-declining', 'Vehicles, declining balance at 40 per cent', '{}'::jsonb, 'declining_balance', 60, 2, null, 'asset_fixed', 110, 'Twice the straight-line rate of a five-year life is forty per cent a year, which is the double-declining balance American practice applies to a vehicle most often, with a switch to the straight line when that gives the larger charge.   There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.'),
    ('US', 'right-of-use-assets', 'Right-of-use assets', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 120, 'A right-of-use asset arising from a lease is amortised over the lease term under topic 842, and the term is a fact about the contract rather than about a class of asset.   There is no legal or fiscal table of useful lives in the United States. FASB Accounting Standards Codification topic 360, Property, Plant, and Equipment, requires the depreciable amount of a long-lived asset to be allocated over its useful life on a systematic and rational basis, and leaves that life to the entity to estimate and to review. What the Internal Revenue Service publishes — the Modified Accelerated Cost Recovery System of Publication 946, with its three, five, seven, ten, fifteen, twenty, twenty-seven-and-a-half and thirty-nine year recovery periods, its half-year and mid-quarter conventions and its two declining-balance rates — is a tax computation and is never the accounting charge. **This category is not MACRS.** The duration below is common American practice, and an asset that depreciates differently says so in its own columns.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

