-- Ekwo OS — currencies. ISO 4217, the handful a European ledger meets, and the
-- five the seventeen member States of OHADA keep their books in.
--
-- The code and the decimals are those of ISO 4217 list one, as SIX
-- Financial Information publishes it on behalf of the maintenance agency
-- (https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml,
-- edition of 17 September 2026). Both CFA francs, the Comorian franc and the
-- Guinean franc have no minor unit there; the Congolese franc has two.

insert into currencies (code, name, symbol, decimal_places) values
  ('EUR', 'Euro',                 E'€', 2),
  ('USD', 'US dollar',            '$',       2),
  ('GBP', 'Pound sterling',       E'£', 2),
  ('CHF', 'Swiss franc',          'CHF',     2),
  ('SEK', 'Swedish krona',        'kr',      2),
  ('DKK', 'Danish krone',         'kr',      2),
  ('NOK', 'Norwegian krone',      'kr',      2),
  ('PLN', 'Polish zloty',         E'z\u0142', 2),
  ('CZK', 'Czech koruna',         E'Kč', 2),
  ('RON', 'Romanian leu',         'lei',     2),
  ('CAD', 'Canadian dollar',      '$',       2),
  ('JPY', 'Japanese yen',         E'¥', 0),
  ('XOF', 'CFA franc BCEAO',      'F CFA',   0),
  ('MXN', 'Mexican peso',         '$',       2),
  ('COP', 'Colombian peso',       '$',       2),
  ('XAF', 'CFA franc BEAC',       'F CFA',   0),
  ('KMF', 'Comorian franc',       'CF',      0),
  ('GNF', 'Guinean franc',        'FG',      0),
  ('CDF', 'Congolese franc',      'FC',      2),
  ('AUD', 'Australian dollar',    '$',       2),
  ('SGD', 'Singapore dollar',     '$',       2),
  ('NZD', 'New Zealand dollar',   '$',       2),
  ('HKD', 'Hong Kong dollar',     E'HK$',    2),
  ('TWD', 'New Taiwan dollar',    E'NT$',    2),
  ('KRW', 'South Korean won',     E'₩',      0),
  ('AED', 'UAE dirham',           E'د.إ', 2),
  ('THB', 'Thai baht',            E'฿', 2),
  ('VND', 'Vietnamese dong',      E'₫', 0),
  ('SAR', 'Saudi riyal',          E'ر.س', 2),
  ('HUF', 'Hungarian forint',     'Ft',      2),
  ('ISK', 'Icelandic krona',      'kr',      0),
  ('TRY', 'Turkish lira',         E'₺', 2),
  ('EGP', 'Egyptian pound',       E'ج.م', 2),
  ('TND', 'Tunisian dinar',       E'د.ت', 3),
  ('DZD', 'Algerian dinar',       E'د.ج', 2),
  ('MAD', 'Moroccan dirham',      E'د.م.', 2),
  ('ZAR', 'South African rand',   'R',       2),
  ('KES', 'Kenyan shilling',      E'KSh',    2),
  ('IDR', 'Indonesian rupiah',    'Rp',      0),
  ('MYR', 'Malaysian ringgit',    'RM',      2),
  ('ILS', 'Israeli new shekel',   E'₪', 2),
  ('PHP', 'Philippine peso',      E'₱', 2),
  ('ARS', 'Argentine peso',       '$',       2),
  ('NGN', 'Nigerian naira',       E'₦', 2),
  ('CLP', 'Chilean peso',         '$',       0),
  ('PEN', 'Peruvian sol',         'S/',      2),
  ('UAH', 'Ukrainian hryvnia',    E'₴', 2),
  ('UYU', 'Uruguayan peso',       E'$U', 2),
  ('BOB', 'Bolivian boliviano',   'Bs',      2)
on conflict (code) do nothing;
