-- Ekwo OS — Uruguay: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/uy at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build uy`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Texto Ordenado 2023 (Decreto N° 101/024, de 4 de abril de 2024), Título 10 — Impuesto al Valor Agregado (IVA), actualizado a diciembre de 2025 (Dirección General Impositiva — Centro de Información Oficial (IMPO))
--     https://www.impo.com.uy/bases/todgi-2023/10-2024
--   Decreto N° 220/998, de 12 de agosto de 1998 — reglamentario del Impuesto al Valor Agregado (Capítulo III, Exportaciones, arts. 29 a 35; Capítulo IV, Exoneraciones) (Dirección General Impositiva — Centro de Información Oficial (IMPO))
--     https://www.impo.com.uy/bases/decretos/220-1998
--   Ley N° 16.060, de Sociedades Comerciales, de 4 de setiembre de 1989 (arts. 87 y 90, sobre el balance general y el estado de resultados) (Centro de Información Oficial (IMPO))
--     https://www.impo.com.uy/bases/leyes/16060-1989
--   Decreto N° 36/012, de 8 de febrero de 2012 — fíjase el régimen de documentación fiscal electrónica (Comprobantes Fiscales Electrónicos, CFE) (Dirección General Impositiva — Centro de Información Oficial (IMPO))
--     https://www.impo.com.uy/bases/decretos/36-2012
--   ¿Quiénes están obligados a ser emisores electrónicos? (Dirección General Impositiva)
--     https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/estan-obligados-emisores-electronicos
--   Facturación Electrónica: incorporación de restantes contribuyentes de IVA (Dirección General Impositiva)
--     https://www.gub.uy/direccion-general-impositiva/comunicacion/noticias/facturacion-electronica-incorporacion-restantes-contribuyentes-iva
--   Sujetos obligados y plazos de presentación del Formulario 1376 (Dirección General Impositiva)
--     https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/sujetos-obligados-plazos-presentacion-del-formulario-1376
--   Panel 1 — IVA Ventas e IVA Compras, Formulario 1376 (Dirección General Impositiva)
--     https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/panel-1-iva-ventas-iva-compras-formulario-1376
--   Vencimientos 2026. Calendario general actualizado (Dirección General Impositiva)
--     https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/vencimientos-2026-calendario-general-actualizado
--   e-Factura — portal de Comprobantes Fiscales Electrónicos (Dirección General Impositiva)
--     https://www.efactura.dgi.gub.uy/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('UY', 'Uruguay', '0.1.0', date '2026-09-26', '20260923110000', 'community', null, null, '8ec32b09fc2d3e8485b17969afffeb87bfafe93e761b349a4f7d754cda1ac22f', '[{"key":"to2023-t10","title":"Texto Ordenado 2023 (Decreto N° 101/024, de 4 de abril de 2024), Título 10 — Impuesto al Valor Agregado (IVA), actualizado a diciembre de 2025","publisher":"Dirección General Impositiva — Centro de Información Oficial (IMPO)","url":"https://www.impo.com.uy/bases/todgi-2023/10-2024","consulted_on":"2026-09-26","kind":"law"},{"key":"decreto220-998","title":"Decreto N° 220/998, de 12 de agosto de 1998 — reglamentario del Impuesto al Valor Agregado (Capítulo III, Exportaciones, arts. 29 a 35; Capítulo IV, Exoneraciones)","publisher":"Dirección General Impositiva — Centro de Información Oficial (IMPO)","url":"https://www.impo.com.uy/bases/decretos/220-1998","consulted_on":"2026-09-26","kind":"regulation"},{"key":"ley16060","title":"Ley N° 16.060, de Sociedades Comerciales, de 4 de setiembre de 1989 (arts. 87 y 90, sobre el balance general y el estado de resultados)","publisher":"Centro de Información Oficial (IMPO)","url":"https://www.impo.com.uy/bases/leyes/16060-1989","consulted_on":"2026-09-26","kind":"law"},{"key":"decreto36-012","title":"Decreto N° 36/012, de 8 de febrero de 2012 — fíjase el régimen de documentación fiscal electrónica (Comprobantes Fiscales Electrónicos, CFE)","publisher":"Dirección General Impositiva — Centro de Información Oficial (IMPO)","url":"https://www.impo.com.uy/bases/decretos/36-2012","consulted_on":"2026-09-26","kind":"regulation"},{"key":"efactura-obligados","title":"¿Quiénes están obligados a ser emisores electrónicos?","publisher":"Dirección General Impositiva","url":"https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/estan-obligados-emisores-electronicos","consulted_on":"2026-09-26","kind":"guidance"},{"key":"efactura-restantes","title":"Facturación Electrónica: incorporación de restantes contribuyentes de IVA","publisher":"Dirección General Impositiva","url":"https://www.gub.uy/direccion-general-impositiva/comunicacion/noticias/facturacion-electronica-incorporacion-restantes-contribuyentes-iva","consulted_on":"2026-09-26","kind":"guidance"},{"key":"form1376-sujetos","title":"Sujetos obligados y plazos de presentación del Formulario 1376","publisher":"Dirección General Impositiva","url":"https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/sujetos-obligados-plazos-presentacion-del-formulario-1376","consulted_on":"2026-09-26","kind":"form"},{"key":"form1376-panel1","title":"Panel 1 — IVA Ventas e IVA Compras, Formulario 1376","publisher":"Dirección General Impositiva","url":"https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/panel-1-iva-ventas-iva-compras-formulario-1376","consulted_on":"2026-09-26","kind":"form"},{"key":"vencimientos2026","title":"Vencimientos 2026. Calendario general actualizado","publisher":"Dirección General Impositiva","url":"https://www.gub.uy/direccion-general-impositiva/comunicacion/publicaciones/vencimientos-2026-calendario-general-actualizado","consulted_on":"2026-09-26","kind":"guidance"},{"key":"efactura-portal","title":"e-Factura — portal de Comprobantes Fiscales Electrónicos","publisher":"Dirección General Impositiva","url":"https://www.efactura.dgi.gub.uy/","consulted_on":"2026-09-26","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('UY', 'default', 'Plan de cuentas Ekwo para Uruguay (sin catálogo oficial)', '{}'::jsonb, true, 'companies', array['UY-BAL', 'UY-RES']::text[], null, 'Uruguay no fija por ley un plan de cuentas con códigos obligatorios: la Ley N° 16.060, de Sociedades Comerciales, art. 87, sólo exige que los administradores formulen, dentro de los cuatro meses del cierre del ejercicio, el inventario y el balance general, y el art. 89 remite a las normas contables adecuadas (hoy las Normas Internacionales de Información Financiera, adoptadas por el Decreto N° 291/014, o el régimen simplificado que ese decreto habilita a las empresas de menor dimensión), sin imponer una numeración de cuentas — a diferencia del código agrupador que el Anexo 24 de la RMF mexicana publica. Este plan es una numeración propia de Ekwo (clases 1 a 5, sin correlato oficial), pensada para que cada cuenta alcance una línea del Estado de Situación Patrimonial y del Estado de Resultados de los arts. 87 y 90 de la Ley N° 16.060', 'ley16060')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('UY', 'default', '1101', 'Caja', '{}'::jsonb, 'asset_cash', false, null, 10),
  ('UY', 'default', '1102', 'Banco', '{}'::jsonb, 'asset_cash', false, null, 20),
  ('UY', 'default', '1103', 'Clientes', '{}'::jsonb, 'asset_receivable', true, null, 30),
  ('UY', 'default', '1104', 'Documentos por Cobrar', '{}'::jsonb, 'asset_current', false, null, 40),
  ('UY', 'default', '1105', 'IVA Compras - Crédito Fiscal', '{}'::jsonb, 'asset_current', false, null, 50),
  ('UY', 'default', '1106', 'Anticipos a Proveedores', '{}'::jsonb, 'asset_current', false, null, 60),
  ('UY', 'default', '1107', 'Otras Cuentas por Cobrar', '{}'::jsonb, 'asset_current', false, null, 70),
  ('UY', 'default', '1108', 'IVA a Favor - Remanente', '{}'::jsonb, 'asset_current', true, null, 80),
  ('UY', 'default', '1109', 'Anticipo de IRAE', '{}'::jsonb, 'asset_current', false, null, 90),
  ('UY', 'default', '1110', 'Cuentas por Cobrar a Empresas Vinculadas', '{}'::jsonb, 'asset_current', false, null, 100),
  ('UY', 'default', '1111', 'Préstamos al Personal', '{}'::jsonb, 'asset_current', false, null, 110),
  ('UY', 'default', '1112', 'Provisión para Deudores Incobrables', '{}'::jsonb, 'asset_current', false, null, 120),
  ('UY', 'default', '1120', 'Mercaderías', '{}'::jsonb, 'asset_current', false, null, 130),
  ('UY', 'default', '1121', 'Materias Primas', '{}'::jsonb, 'asset_current', false, null, 140),
  ('UY', 'default', '1122', 'Productos en Proceso', '{}'::jsonb, 'asset_current', false, null, 150),
  ('UY', 'default', '1123', 'Productos Terminados', '{}'::jsonb, 'asset_current', false, null, 160),
  ('UY', 'default', '1124', 'Materiales y Repuestos', '{}'::jsonb, 'asset_current', false, null, 170),
  ('UY', 'default', '1125', 'Provisión por Obsolescencia de Existencias', '{}'::jsonb, 'asset_current', false, null, 180),
  ('UY', 'default', '1130', 'Gastos Pagados por Anticipado', '{}'::jsonb, 'asset_prepayments', false, null, 190),
  ('UY', 'default', '1131', 'Seguros Pagados por Anticipado', '{}'::jsonb, 'asset_prepayments', false, null, 200),
  ('UY', 'default', '1132', 'Alquileres Pagados por Anticipado', '{}'::jsonb, 'asset_prepayments', false, null, 210),
  ('UY', 'default', '1150', 'Partidas Pendientes de Identificación', '{}'::jsonb, 'asset_current', false, null, 220),
  ('UY', 'default', '1201', 'Terrenos', '{}'::jsonb, 'asset_fixed', false, null, 230),
  ('UY', 'default', '1202', 'Construcciones y Edificios', '{}'::jsonb, 'asset_fixed', false, null, 240),
  ('UY', 'default', '1203', 'Maquinaria y Equipos', '{}'::jsonb, 'asset_fixed', false, null, 250),
  ('UY', 'default', '1204', 'Muebles y Útiles', '{}'::jsonb, 'asset_fixed', false, null, 260),
  ('UY', 'default', '1205', 'Equipos de Computación', '{}'::jsonb, 'asset_fixed', false, null, 270),
  ('UY', 'default', '1206', 'Vehículos', '{}'::jsonb, 'asset_fixed', false, null, 280),
  ('UY', 'default', '1207', 'Instalaciones', '{}'::jsonb, 'asset_fixed', false, null, 290),
  ('UY', 'default', '1208', 'Mejoras en Bienes Arrendados', '{}'::jsonb, 'asset_fixed', false, null, 300),
  ('UY', 'default', '1210', 'Depreciación Acumulada Construcciones y Edificios', '{}'::jsonb, 'asset_fixed', false, null, 310),
  ('UY', 'default', '1211', 'Depreciación Acumulada Maquinaria y Equipos', '{}'::jsonb, 'asset_fixed', false, null, 320),
  ('UY', 'default', '1212', 'Depreciación Acumulada Muebles y Útiles', '{}'::jsonb, 'asset_fixed', false, null, 330),
  ('UY', 'default', '1213', 'Depreciación Acumulada Equipos de Computación', '{}'::jsonb, 'asset_fixed', false, null, 340),
  ('UY', 'default', '1214', 'Depreciación Acumulada Vehículos', '{}'::jsonb, 'asset_fixed', false, null, 350),
  ('UY', 'default', '1215', 'Depreciación Acumulada Instalaciones', '{}'::jsonb, 'asset_fixed', false, null, 360),
  ('UY', 'default', '1216', 'Depreciación Acumulada Mejoras en Bienes Arrendados', '{}'::jsonb, 'asset_fixed', false, null, 370),
  ('UY', 'default', '1220', 'Obras en Construcción', '{}'::jsonb, 'asset_fixed', false, null, 380),
  ('UY', 'default', '1301', 'Activos Intangibles', '{}'::jsonb, 'asset_non_current', false, null, 390),
  ('UY', 'default', '1302', 'Amortización Acumulada de Intangibles', '{}'::jsonb, 'asset_non_current', false, null, 400),
  ('UY', 'default', '1303', 'Inversiones en Empresas Vinculadas', '{}'::jsonb, 'asset_non_current', false, null, 410),
  ('UY', 'default', '1304', 'Depósitos en Garantía', '{}'::jsonb, 'asset_non_current', false, null, 420),
  ('UY', 'default', '2101', 'Proveedores', '{}'::jsonb, 'liability_payable', true, null, 430),
  ('UY', 'default', '2102', 'Documentos por Pagar', '{}'::jsonb, 'liability_current', false, null, 440),
  ('UY', 'default', '2103', 'IVA Ventas - Débito Fiscal', '{}'::jsonb, 'liability_current', false, null, 450),
  ('UY', 'default', '2104', 'Anticipos de Clientes', '{}'::jsonb, 'liability_current', false, null, 460),
  ('UY', 'default', '2105', 'Otras Cuentas por Pagar', '{}'::jsonb, 'liability_current', false, null, 470),
  ('UY', 'default', '2106', 'IVA por Pagar', '{}'::jsonb, 'liability_current', true, null, 480),
  ('UY', 'default', '2107', 'Cuentas por Pagar a Empresas Vinculadas', '{}'::jsonb, 'liability_current', false, null, 490),
  ('UY', 'default', '2108', 'Remuneraciones por Pagar', '{}'::jsonb, 'liability_current', false, null, 500),
  ('UY', 'default', '2109', 'BPS - Aportes Personales por Pagar', '{}'::jsonb, 'liability_current', false, null, 510),
  ('UY', 'default', '2110', 'BPS - Aportes Patronales por Pagar', '{}'::jsonb, 'liability_current', false, null, 520),
  ('UY', 'default', '2111', 'Fondo de Reconversión Laboral por Pagar', '{}'::jsonb, 'liability_current', false, null, 530),
  ('UY', 'default', '2112', 'IRPF Retenido por Pagar', '{}'::jsonb, 'liability_current', false, null, 540),
  ('UY', 'default', '2113', 'Provisión de Aguinaldo', '{}'::jsonb, 'liability_current', false, null, 550),
  ('UY', 'default', '2114', 'Provisión de Licencias y Salario Vacacional', '{}'::jsonb, 'liability_current', false, null, 560),
  ('UY', 'default', '2115', 'Provisión de Despidos', '{}'::jsonb, 'liability_current', false, null, 570),
  ('UY', 'default', '2116', 'IRAE por Pagar', '{}'::jsonb, 'liability_current', false, null, 580),
  ('UY', 'default', '2117', 'Impuesto al Patrimonio por Pagar', '{}'::jsonb, 'liability_current', false, null, 590),
  ('UY', 'default', '2201', 'Préstamos Bancarios a Largo Plazo', '{}'::jsonb, 'liability_non_current', false, null, 600),
  ('UY', 'default', '2202', 'Leasing por Pagar Largo Plazo', '{}'::jsonb, 'liability_non_current', false, null, 610),
  ('UY', 'default', '2203', 'Provisiones Largo Plazo', '{}'::jsonb, 'liability_non_current', false, null, 620),
  ('UY', 'default', '3101', 'Capital Integrado', '{}'::jsonb, 'equity', false, null, 630),
  ('UY', 'default', '3102', 'Capital a Integrar', '{}'::jsonb, 'equity', false, null, 640),
  ('UY', 'default', '3103', 'Resultados Acumulados', '{}'::jsonb, 'equity_retained', false, null, 650),
  ('UY', 'default', '3104', 'Pérdidas Acumuladas', '{}'::jsonb, 'equity_retained', false, null, 660),
  ('UY', 'default', '3105', 'Resultado del Ejercicio - Ganancia', '{}'::jsonb, 'equity_retained', false, null, 670),
  ('UY', 'default', '3106', 'Resultado del Ejercicio - Pérdida', '{}'::jsonb, 'equity_retained', false, null, 680),
  ('UY', 'default', '3107', 'Reserva Legal', '{}'::jsonb, 'equity', false, null, 690),
  ('UY', 'default', '3108', 'Otras Reservas', '{}'::jsonb, 'equity', false, null, 700),
  ('UY', 'default', '3109', 'Ajustes al Patrimonio', '{}'::jsonb, 'equity', false, null, 710),
  ('UY', 'default', '4101', 'Ventas Nacionales', '{}'::jsonb, 'income', false, null, 720),
  ('UY', 'default', '4102', 'Ventas de Exportación', '{}'::jsonb, 'income', false, null, 730),
  ('UY', 'default', '4103', 'Servicios Prestados', '{}'::jsonb, 'income', false, null, 740),
  ('UY', 'default', '4104', 'Arrendamientos Ganados', '{}'::jsonb, 'income', false, null, 750),
  ('UY', 'default', '4105', 'Devoluciones y Bonificaciones en Ventas', '{}'::jsonb, 'income', false, null, 760),
  ('UY', 'default', '4106', 'Descuentos Obtenidos por Pronto Pago', '{}'::jsonb, 'income', false, null, 770),
  ('UY', 'default', '4107', 'Ingresos Financieros', '{}'::jsonb, 'income_other', false, null, 780),
  ('UY', 'default', '4108', 'Diferencia de Cambio - Ganancia', '{}'::jsonb, 'income_other', false, null, 790),
  ('UY', 'default', '4109', 'Otros Ingresos de Explotación', '{}'::jsonb, 'income', false, null, 800),
  ('UY', 'default', '4110', 'Ingresos Extraordinarios', '{}'::jsonb, 'income_other', false, null, 810),
  ('UY', 'default', '5101', 'Costo de Mercaderías Vendidas', '{}'::jsonb, 'expense_direct_cost', false, null, 820),
  ('UY', 'default', '5102', 'Compras', '{}'::jsonb, 'expense_direct_cost', false, null, 830),
  ('UY', 'default', '5103', 'Mano de Obra Directa', '{}'::jsonb, 'expense_direct_cost', false, null, 840),
  ('UY', 'default', '5104', 'Gastos Indirectos de Fabricación', '{}'::jsonb, 'expense_direct_cost', false, null, 850),
  ('UY', 'default', '5110', 'Sueldos y Jornales', '{}'::jsonb, 'expense', false, null, 860),
  ('UY', 'default', '5111', 'Cargas Sociales - BPS Patronal', '{}'::jsonb, 'expense', false, null, 870),
  ('UY', 'default', '5112', 'Aguinaldo', '{}'::jsonb, 'expense', false, null, 880),
  ('UY', 'default', '5113', 'Salario Vacacional', '{}'::jsonb, 'expense', false, null, 890),
  ('UY', 'default', '5114', 'Seguro de Accidentes de Trabajo (BSE)', '{}'::jsonb, 'expense', false, null, 900),
  ('UY', 'default', '5115', 'Honorarios Profesionales', '{}'::jsonb, 'expense', false, null, 910),
  ('UY', 'default', '5116', 'Arrendamientos', '{}'::jsonb, 'expense', false, null, 920),
  ('UY', 'default', '5117', 'Servicios Contratados en el Exterior', '{}'::jsonb, 'expense', false, null, 930),
  ('UY', 'default', '5118', 'Seguros Generales', '{}'::jsonb, 'expense', false, null, 940),
  ('UY', 'default', '5119', 'Servicios Básicos (UTE, OSE, Antel)', '{}'::jsonb, 'expense', false, null, 950),
  ('UY', 'default', '5120', 'Mantenimiento y Reparaciones', '{}'::jsonb, 'expense', false, null, 960),
  ('UY', 'default', '5121', 'Materiales de Oficina', '{}'::jsonb, 'expense', false, null, 970),
  ('UY', 'default', '5122', 'Publicidad y Marketing', '{}'::jsonb, 'expense', false, null, 980),
  ('UY', 'default', '5123', 'Gastos de Representación', '{}'::jsonb, 'expense', false, null, 990),
  ('UY', 'default', '5124', 'Viáticos y Gastos de Viaje', '{}'::jsonb, 'expense', false, null, 1000),
  ('UY', 'default', '5125', 'Fletes y Transportes', '{}'::jsonb, 'expense', false, null, 1010),
  ('UY', 'default', '5126', 'Comunicaciones', '{}'::jsonb, 'expense', false, null, 1020),
  ('UY', 'default', '5127', 'Depreciación del Ejercicio', '{}'::jsonb, 'expense_depreciation', false, null, 1030),
  ('UY', 'default', '5128', 'Amortización de Intangibles', '{}'::jsonb, 'expense_depreciation', false, null, 1040),
  ('UY', 'default', '5129', 'Deudores Incobrables', '{}'::jsonb, 'expense', false, null, 1050),
  ('UY', 'default', '5130', 'Donaciones', '{}'::jsonb, 'expense', false, null, 1060),
  ('UY', 'default', '5131', 'Patente Única de Rodados', '{}'::jsonb, 'expense', false, null, 1070),
  ('UY', 'default', '5132', 'Capacitación del Personal', '{}'::jsonb, 'expense', false, null, 1080),
  ('UY', 'default', '5133', 'Diferencia de Cambio - Pérdida', '{}'::jsonb, 'expense', false, null, 1090),
  ('UY', 'default', '5134', 'Gastos Bancarios', '{}'::jsonb, 'expense', false, null, 1100),
  ('UY', 'default', '5135', 'Intereses por Préstamos', '{}'::jsonb, 'expense', false, null, 1110),
  ('UY', 'default', '5136', 'Impuesto a la Renta (IRAE)', '{}'::jsonb, 'expense', false, null, 1120),
  ('UY', 'default', '5137', 'Impuesto al Patrimonio', '{}'::jsonb, 'expense', false, null, 1130),
  ('UY', 'default', '5138', 'Multas y Recargos Fiscales', '{}'::jsonb, 'expense', false, null, 1140),
  ('UY', 'default', '5139', 'Gastos Extraordinarios', '{}'::jsonb, 'expense', false, null, 1150),
  ('UY', 'default', '5140', 'Diferencias de Redondeo', '{}'::jsonb, 'expense', false, null, 1160)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('UY', 'APE', 'Asiento de Apertura', '{}'::jsonb, 'opening', 60),
  ('UY', 'BAN', 'Banco', '{}'::jsonb, 'bank', 30),
  ('UY', 'CAJ', 'Caja', '{}'::jsonb, 'cash', 40),
  ('UY', 'COM', 'Libro de Compras', '{}'::jsonb, 'purchase', 20),
  ('UY', 'DIA', 'Libro Diario', '{}'::jsonb, 'general', 50),
  ('UY', 'VEN', 'Libro de Ventas', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('UY', 'UY-P-10', 'Compras y servicios, tasa mínima 10 %', '{}'::jsonb, 'Adquisición de bienes de primera necesidad gravada a la tasa mínima, con derecho a crédito fiscal', 'percent', 10, 'purchase', 'domestic', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 34, literal B), y art. 36, literal A) — tasa mínima 10% sobre, entre otros, arroz y harina de cereales; art. 14 — derecho a crédito fiscal sobre las compras del giro. Formulario 1376, panel «IVA Ventas e IVA Compras», línea 19', 'S', null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'to2023-t10', null, null, null, null),
  ('UY', 'UY-P-22', 'Compras y servicios, tasa básica 22 %', '{}'::jsonb, 'Adquisición de bienes o servicios del giro, gravada a la tasa básica, con derecho a crédito fiscal', 'percent', 22, 'purchase', 'domestic', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 34, literal A) — tasa básica 22%; art. 14 — el impuesto correspondiente a las compras de bienes y servicios adquiridos por el sujeto pasivo, documentado en la forma del art. 13, se deduce del impuesto a pagar, en tanto integre directa o indirectamente el costo de bienes y servicios destinados a las operaciones gravadas. Formulario 1376, panel «IVA Ventas e IVA Compras», línea 19 «IVA COMPRAS deducible por operaciones gravadas»', 'S', null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'to2023-t10', null, null, null, null),
  ('UY', 'UY-S-0-EXP-BIENES', 'Exportación de bienes', '{}'::jsonb, 'Enajenación de bienes exportados, no gravada por el Impuesto al Valor Agregado', 'percent', 0, 'sale', 'export', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 5° — «Estarán gravadas las entregas de bienes y las prestaciones de servicios realizadas en el territorio nacional … y no lo estarán aquellas exportaciones de bienes». El exportador no traslada IVA en la exportación y, en cambio, conserva el derecho a deducir el impuesto que integre directa o indirectamente el costo del producto exportado (art. 14, inciso quinto) — véase UY-P-22 y UY-P-10, que dan ese crédito, y el Formulario 1376, panel «Determinación de IVA», línea 27, que declara el crédito de compras atribuible a la exportación, no transcrita por este paquete (véase el README)', 'G', null, 30, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'to2023-t10', null, null, null, null),
  ('UY', 'UY-S-0-EXP-SERVICIOS', 'Exportación de servicios', '{}'::jsonb, 'Servicios de diseño, desarrollo o implementación de soportes lógicos (software) prestados a un usuario del exterior y aprovechados exclusivamente allí, calificados como exportación de servicios', 'percent', 0, 'sale', 'export', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 5°, inciso primero — «no lo estarán aquellas exportaciones de servicios que determine el Poder Ejecutivo»; Decreto N° 220/998, art. 34, numeral 11, literal b) — se consideran exportación «los servicios prestados para el diseño, desarrollo o implementación de soportes lógicos específicos», siempre que sean aprovechados exclusivamente en el exterior', 'G', null, 40, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'decreto220-998', null, null, null, null),
  ('UY', 'UY-S-10', 'Ventas y servicios, tasa mínima 10 %', '{}'::jsonb, 'Circulación de bienes o prestación de servicios de primera necesidad gravada a la tasa mínima (p. ej. arroz, harina, servicios de hotelería)', 'percent', 10, 'sale', 'domestic', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 34, literal B) — tasa mínima del 10% (fuente: Ley N° 18.083, de 27 de diciembre de 2006, art. 25); art. 36, literal A) — están sujetos a esta tasa, entre otros bienes, «arroz; harina de cereales y subproductos de su molienda»', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'to2023-t10', null, null, null, null),
  ('UY', 'UY-S-22', 'Ventas y servicios, tasa básica 22 %', '{}'::jsonb, 'Circulación de bienes o prestación de servicios gravada a la tasa básica', 'percent', 22, 'sale', 'domestic', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 34, literal A) — «Fíjanse las siguientes tasas: A) Básica del 22% (veintidós por ciento)» (fuente: Ley N° 18.083, de 27 de diciembre de 2006, art. 25); art. 1° — hecho gravado (circulación de bienes, prestación de servicios); art. 3° — el hecho generador se presume configurado en la fecha de la factura', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'to2023-t10', null, null, null, null),
  ('UY', 'UY-S-EXE-INMUEBLE', 'Arrendamiento de inmuebles', '{}'::jsonb, 'Prestación de servicios de arrendamiento de bienes inmuebles, exonerada del Impuesto al Valor Agregado', 'percent', 0, 'sale', 'exempt', date '2007-07-01', null, 'Texto Ordenado 2023, Título 10, art. 38, numeral 2), literal C) — «Exonéranse … 2) Las siguientes prestaciones de servicios: … C) Arrendamientos de inmuebles»', 'E', null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'to2023-t10', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('UY-P-10', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('UY-P-10', 'invoice', 'tax', 100, '1105', '19', array['19']::text[], 100, 'UY-F1376-IVA', 20),
    ('UY-P-10', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('UY-P-10', 'credit_note', 'tax', 100, '1105', '19', array['19']::text[], -100, 'UY-F1376-IVA', 20),
    ('UY-P-22', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('UY-P-22', 'invoice', 'tax', 100, '1105', '19', array['19']::text[], 100, 'UY-F1376-IVA', 20),
    ('UY-P-22', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('UY-P-22', 'credit_note', 'tax', 100, '1105', '19', array['19']::text[], -100, 'UY-F1376-IVA', 20),
    ('UY-S-0-EXP-BIENES', 'invoice', 'base', 100, null, '9', array['9']::text[], 100, 'UY-F1376-IVA', 10),
    ('UY-S-0-EXP-BIENES', 'credit_note', 'base', 100, null, '9', array['9']::text[], -100, 'UY-F1376-IVA', 10),
    ('UY-S-0-EXP-SERVICIOS', 'invoice', 'base', 100, null, '9', array['9']::text[], 100, 'UY-F1376-IVA', 10),
    ('UY-S-0-EXP-SERVICIOS', 'credit_note', 'base', 100, null, '9', array['9']::text[], -100, 'UY-F1376-IVA', 10),
    ('UY-S-10', 'invoice', 'base', 100, null, '11', array['11']::text[], 100, 'UY-F1376-IVA', 10),
    ('UY-S-10', 'invoice', 'tax', 100, '2103', '15', array['15']::text[], 100, 'UY-F1376-IVA', 20),
    ('UY-S-10', 'credit_note', 'base', 100, null, '11', array['11']::text[], -100, 'UY-F1376-IVA', 10),
    ('UY-S-10', 'credit_note', 'tax', 100, '2103', '15', array['15']::text[], -100, 'UY-F1376-IVA', 20),
    ('UY-S-22', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'UY-F1376-IVA', 10),
    ('UY-S-22', 'invoice', 'tax', 100, '2103', '16', array['16']::text[], 100, 'UY-F1376-IVA', 20),
    ('UY-S-22', 'credit_note', 'base', 100, null, '12', array['12']::text[], -100, 'UY-F1376-IVA', 10),
    ('UY-S-22', 'credit_note', 'tax', 100, '2103', '16', array['16']::text[], -100, 'UY-F1376-IVA', 20),
    ('UY-S-EXE-INMUEBLE', 'invoice', 'base', 100, null, '8', array['8']::text[], 100, 'UY-F1376-IVA', 10),
    ('UY-S-EXE-INMUEBLE', 'credit_note', 'base', 100, null, '8', array['8']::text[], -100, 'UY-F1376-IVA', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'UY' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('UY', 'UY-F1376-IVA', 'Formulario 1376 — Declaración Mensual de IVA (grupo CEDE y División Grandes Contribuyentes), sección Impuesto al Valor Agregado', array['month']::declaration_period[], 'month'::declaration_period, date '2021-10-01', null, 'El Formulario 1376 sustituyó al Formulario 2176 para las declaraciones de períodos iguales o posteriores a octubre de 2021, y comprende la declaración de IVA y los anticipos de IRAE, Impuesto al Patrimonio (IPAT) e ICOSA de los contribuyentes del grupo CEDE y de la División Grandes Contribuyentes. Este paquete transcribe únicamente los campos que alimentan la determinación del Impuesto al Valor Agregado del panel «IVA Ventas e IVA Compras» y del panel «Determinación de IVA», con los números de línea que expone la aplicación PADI de la Dirección General Impositiva; omite los anticipos de IRAE, IPAT e ICOSA, que no son Impuesto al Valor Agregado — véase «Lo que este paquete no transcribe» en el README', true,'depends_on_taxpayer'::filing_deadline_rule, null, null, 'La Dirección General Impositiva fija cada año, mediante resolución (para 2026, la que fija el calendario de vencimientos publicado como «Vencimientos 2026»), un día de vencimiento distinto según el grupo del contribuyente y la terminación de su Registro Único Tributario (RUT): los contribuyentes CEDE y de la División Grandes Contribuyentes vencen entre los días 22 y 24 de cada mes, según esa terminación', 'vencimientos2026', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('UY', 'UY-F1376-IVA', '8', 'base', 'Ventas e ingresos no gravados o exentos (monto neto)', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «Ventas e IVA Ventas», línea 8: «No gravadas»', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '9', 'base', 'Ventas de exportación y asimiladas (monto neto)', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «Ventas e IVA Ventas», línea 9: «De exportación y asimiladas»', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '11', 'base', 'Ventas gravadas a la tasa mínima (monto neto)', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «Ventas e IVA Ventas», línea 11: «Gravadas tasa mínima»', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '12', 'base', 'Ventas gravadas a la tasa básica (monto neto)', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «Ventas e IVA Ventas», línea 12: «Gravadas tasa básica»', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '14', 'total', 'Total de ventas e ingresos del período', '{}'::jsonb, 50, null, array['8', '9', '11', '12']::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «Ventas e IVA Ventas», línea 14 «TOTAL» — este paquete suma únicamente las líneas que sus impuestos alimentan', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '15', 'tax', 'IVA ventas — tasa mínima', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «IVA ventas», línea 15: «Tasa mínima»', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '16', 'tax', 'IVA ventas — tasa básica', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «IVA ventas», línea 16: «Tasa básica»', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '18', 'total', 'Total IVA ventas (débito fiscal)', '{}'::jsonb, 80, null, array['15', '16']::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «IVA Ventas e IVA Compras», cuadro «IVA ventas», línea 18 «TOTAL»; retomado como primera línea del panel «Determinación de IVA» («IVA VENTAS»)', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '19', 'tax', 'IVA compras deducible por operaciones gravadas', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 1376, panel «Determinación de IVA», línea 19: «IVA COMPRAS deducible por operaciones gravadas». El formulario oficial reparte el crédito fiscal del período entre esta línea y la línea 27 (compras atribuibles a la exportación) mediante un cuadro de prorrateo sobre la composición de las ventas del ejercicio; este paquete no reproduce ese prorrateo — un contribuyente que también exporta declara aquí, de forma simplificada, la totalidad del crédito fiscal del período — véase «Lo que este paquete no transcribe» en el README', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '43', 'total', 'Saldo a pagar', '{}'::jsonb, 100, null, array['18']::text[], array['19']::text[], null, null, true, false, null, 'Formulario 1376, panel «Determinación de IVA», línea 43: «Saldo a pagar» — la diferencia positiva entre el IVA Ventas (línea 18) y el IVA Compras deducible (línea 19). El formulario oficial encadena antes de esta línea los excedentes de crédito fiscal de meses anteriores y otros créditos que este paquete no transcribe — véase el README', 'form1376-panel1'),
  ('UY', 'UY-F1376-IVA', '22', 'total', 'Crédito fiscal que pasa al próximo mes', '{}'::jsonb, 110, null, array['19']::text[], array['18']::text[], null, null, true, false, null, 'Formulario 1376, panel «Determinación de IVA», línea 22: «IVA COMPRAS excedente que pasa al próximo mes» — el remanente de crédito fiscal cuando el IVA Compras deducible (línea 19) excede el IVA Ventas (línea 18)', 'form1376-panel1')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('UY-BAL', 'UY', 'default', 'Estado de Situación Patrimonial', 'balance_sheet', 'UY-Ekwo', date '1970-01-01', null, 'Ley N° 16.060, de Sociedades Comerciales, art. 87 — dentro de los cuatro meses de la fecha de cierre del ejercicio los administradores deben formular, cuando menos, el inventario y el balance general (estado de situación patrimonial y de resultados). Uruguay no fija una estructura de líneas obligatoria para ese balance fuera de las Normas Internacionales de Información Financiera que adopta el Decreto N° 291/014 para las empresas obligadas a aplicarlas (cuyo texto no se transcribe aquí): esta es la estructura mínima que Ekwo instala por defecto, agrupada por naturaleza (activo corriente, activo fijo, pasivo corriente, pasivo no corriente, patrimonio), sobre el plan de cuentas propio del paquete', 'ley16060'),
  ('UY-RES', 'UY', 'default', 'Estado de Resultados', 'income_statement', 'UY-Ekwo', date '1970-01-01', null, 'Ley N° 16.060, de Sociedades Comerciales, art. 90 — el estado de resultados del ejercicio debe indicar separadamente los resultantes de la actividad ordinaria de la sociedad y los provenientes de operaciones extraordinarias, discriminando los rubros positivos y negativos en la medida necesaria para permitir formarse un juicio claro sobre la magnitud y el contenido de cada uno de ellos. Estructura mínima propia de Ekwo, con los subtotales de utilidad bruta, operativa, antes de impuesto y neta', 'ley16060')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('UY-BAL', 'ACT', null, 'Total Activo', '{}'::jsonb, 10, 1, true, array['AC', 'AF', 'AO']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'AC', 'ACT', 'Activo Corriente', '{}'::jsonb, 20, 1, true, array['1101', '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109', '1110', '1111', '1112', '1120', '1121', '1122', '1123', '1124', '1125', '1130', '1131', '1132', '1150D']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1101', 'AC', 'Caja', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1102', 'AC', 'Banco', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1103', 'AC', 'Clientes', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1104', 'AC', 'Documentos por Cobrar', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1105', 'AC', 'IVA Compras - Crédito Fiscal', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1106', 'AC', 'Anticipos a Proveedores', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1107', 'AC', 'Otras Cuentas por Cobrar', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1108', 'AC', 'IVA a Favor - Remanente', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1109', 'AC', 'Anticipo de IRAE', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1110', 'AC', 'Cuentas por Cobrar a Empresas Vinculadas', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1111', 'AC', 'Préstamos al Personal', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1112', 'AC', 'Provisión para Deudores Incobrables', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1120', 'AC', 'Mercaderías', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1121', 'AC', 'Materias Primas', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1122', 'AC', 'Productos en Proceso', '{}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1123', 'AC', 'Productos Terminados', '{}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1124', 'AC', 'Materiales y Repuestos', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1125', 'AC', 'Provisión por Obsolescencia de Existencias', '{}'::jsonb, 210, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1130', 'AC', 'Gastos Pagados por Anticipado', '{}'::jsonb, 220, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1131', 'AC', 'Seguros Pagados por Anticipado', '{}'::jsonb, 230, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1132', 'AC', 'Alquileres Pagados por Anticipado', '{}'::jsonb, 240, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1150D', 'AC', 'Partidas Pendientes de Identificación (saldo deudor)', '{}'::jsonb, 250, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'AF', 'ACT', 'Activo Fijo', '{}'::jsonb, 250, 1, true, array['1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208', '1210', '1211', '1212', '1213', '1214', '1215', '1216', '1220']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1201', 'AF', 'Terrenos', '{}'::jsonb, 270, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1202', 'AF', 'Construcciones y Edificios', '{}'::jsonb, 280, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1203', 'AF', 'Maquinaria y Equipos', '{}'::jsonb, 290, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1204', 'AF', 'Muebles y Útiles', '{}'::jsonb, 300, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1205', 'AF', 'Equipos de Computación', '{}'::jsonb, 310, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1206', 'AF', 'Vehículos', '{}'::jsonb, 320, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1207', 'AF', 'Instalaciones', '{}'::jsonb, 330, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1208', 'AF', 'Mejoras en Bienes Arrendados', '{}'::jsonb, 340, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1210', 'AF', 'Depreciación Acumulada Construcciones y Edificios', '{}'::jsonb, 350, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1211', 'AF', 'Depreciación Acumulada Maquinaria y Equipos', '{}'::jsonb, 360, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1212', 'AF', 'Depreciación Acumulada Muebles y Útiles', '{}'::jsonb, 370, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1213', 'AF', 'Depreciación Acumulada Equipos de Computación', '{}'::jsonb, 380, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1214', 'AF', 'Depreciación Acumulada Vehículos', '{}'::jsonb, 390, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1215', 'AF', 'Depreciación Acumulada Instalaciones', '{}'::jsonb, 400, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1216', 'AF', 'Depreciación Acumulada Mejoras en Bienes Arrendados', '{}'::jsonb, 410, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1220', 'AF', 'Obras en Construcción', '{}'::jsonb, 420, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'AO', 'ACT', 'Otros Activos', '{}'::jsonb, 420, 1, true, array['1301', '1302', '1303', '1304']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1301', 'AO', 'Activos Intangibles', '{}'::jsonb, 440, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1302', 'AO', 'Amortización Acumulada de Intangibles', '{}'::jsonb, 450, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1303', 'AO', 'Inversiones en Empresas Vinculadas', '{}'::jsonb, 460, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1304', 'AO', 'Depósitos en Garantía', '{}'::jsonb, 470, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'PYP', null, 'Total Pasivo y Patrimonio', '{}'::jsonb, 470, 1, true, array['PAS', 'PAT']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'PAS', 'PYP', 'Total Pasivo', '{}'::jsonb, 480, 1, true, array['PC', 'PNC']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'PC', 'PAS', 'Pasivo Corriente', '{}'::jsonb, 490, 1, true, array['2101', '2102', '2103', '2104', '2105', '2106', '2107', '2108', '2109', '2110', '2111', '2112', '2113', '2114', '2115', '2116', '2117', '1150C']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2101', 'PC', 'Proveedores', '{}'::jsonb, 510, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2102', 'PC', 'Documentos por Pagar', '{}'::jsonb, 520, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2103', 'PC', 'IVA Ventas - Débito Fiscal', '{}'::jsonb, 530, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2104', 'PC', 'Anticipos de Clientes', '{}'::jsonb, 540, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2105', 'PC', 'Otras Cuentas por Pagar', '{}'::jsonb, 550, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2106', 'PC', 'IVA por Pagar', '{}'::jsonb, 560, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2107', 'PC', 'Cuentas por Pagar a Empresas Vinculadas', '{}'::jsonb, 570, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2108', 'PC', 'Remuneraciones por Pagar', '{}'::jsonb, 580, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2109', 'PC', 'BPS - Aportes Personales por Pagar', '{}'::jsonb, 590, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2110', 'PC', 'BPS - Aportes Patronales por Pagar', '{}'::jsonb, 600, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2111', 'PC', 'Fondo de Reconversión Laboral por Pagar', '{}'::jsonb, 610, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2112', 'PC', 'IRPF Retenido por Pagar', '{}'::jsonb, 620, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2113', 'PC', 'Provisión de Aguinaldo', '{}'::jsonb, 630, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2114', 'PC', 'Provisión de Licencias y Salario Vacacional', '{}'::jsonb, 640, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2115', 'PC', 'Provisión de Despidos', '{}'::jsonb, 650, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2116', 'PC', 'IRAE por Pagar', '{}'::jsonb, 660, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2117', 'PC', 'Impuesto al Patrimonio por Pagar', '{}'::jsonb, 670, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '1150C', 'PC', 'Partidas Pendientes de Identificación (saldo acreedor)', '{}'::jsonb, 680, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'PNC', 'PAS', 'Pasivo No Corriente', '{}'::jsonb, 680, 1, true, array['2201', '2202', '2203']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2201', 'PNC', 'Préstamos Bancarios a Largo Plazo', '{}'::jsonb, 700, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2202', 'PNC', 'Leasing por Pagar Largo Plazo', '{}'::jsonb, 710, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '2203', 'PNC', 'Provisiones Largo Plazo', '{}'::jsonb, 720, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', 'PAT', 'PYP', 'Patrimonio', '{}'::jsonb, 720, 1, true, array['3101', '3102', '3103', '3104', '3105', '3106', '3107', '3108', '3109']::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3101', 'PAT', 'Capital Integrado', '{}'::jsonb, 740, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3102', 'PAT', 'Capital a Integrar', '{}'::jsonb, 750, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3103', 'PAT', 'Resultados Acumulados', '{}'::jsonb, 760, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3104', 'PAT', 'Pérdidas Acumuladas', '{}'::jsonb, 770, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3105', 'PAT', 'Resultado del Ejercicio - Ganancia', '{}'::jsonb, 780, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3106', 'PAT', 'Resultado del Ejercicio - Pérdida', '{}'::jsonb, 790, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3107', 'PAT', 'Reserva Legal', '{}'::jsonb, 800, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3108', 'PAT', 'Otras Reservas', '{}'::jsonb, 810, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-BAL', '3109', 'PAT', 'Ajustes al Patrimonio', '{}'::jsonb, 820, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', 'ING', null, 'Ingresos', '{}'::jsonb, 10, 1, true, array['4101', '4102', '4103', '4104', '4105', '4106', '4107', '4108', '4109', '4110']::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4101', 'ING', 'Ventas Nacionales', '{}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4102', 'ING', 'Ventas de Exportación', '{}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4103', 'ING', 'Servicios Prestados', '{}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4104', 'ING', 'Arrendamientos Ganados', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4105', 'ING', 'Devoluciones y Bonificaciones en Ventas', '{}'::jsonb, 70, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4106', 'ING', 'Descuentos Obtenidos por Pronto Pago', '{}'::jsonb, 80, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4107', 'ING', 'Ingresos Financieros', '{}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4108', 'ING', 'Diferencia de Cambio - Ganancia', '{}'::jsonb, 100, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4109', 'ING', 'Otros Ingresos de Explotación', '{}'::jsonb, 110, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '4110', 'ING', 'Ingresos Extraordinarios', '{}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', 'CV', null, 'Costo de Ventas', '{}'::jsonb, 120, 1, true, array['5101', '5102', '5103', '5104']::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5101', 'CV', 'Costo de Mercaderías Vendidas', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5102', 'CV', 'Compras', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5103', 'CV', 'Mano de Obra Directa', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5104', 'CV', 'Gastos Indirectos de Fabricación', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', 'UB', null, 'Utilidad (Pérdida) Bruta', '{}'::jsonb, 170, 1, true, array['ING']::text[], array['CV']::text[], null, null, null),
  ('UY-RES', 'GO', null, 'Gastos de Operación', '{}'::jsonb, 180, 1, true, array['5110', '5111', '5112', '5113', '5114', '5115', '5116', '5117', '5118', '5119', '5120', '5121', '5122', '5123', '5124', '5125', '5126', '5127', '5128', '5129', '5130', '5131', '5132']::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5110', 'GO', 'Sueldos y Jornales', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5111', 'GO', 'Cargas Sociales - BPS Patronal', '{}'::jsonb, 210, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5112', 'GO', 'Aguinaldo', '{}'::jsonb, 220, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5113', 'GO', 'Salario Vacacional', '{}'::jsonb, 230, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5114', 'GO', 'Seguro de Accidentes de Trabajo (BSE)', '{}'::jsonb, 240, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5115', 'GO', 'Honorarios Profesionales', '{}'::jsonb, 250, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5116', 'GO', 'Arrendamientos', '{}'::jsonb, 260, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5117', 'GO', 'Servicios Contratados en el Exterior', '{}'::jsonb, 270, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5118', 'GO', 'Seguros Generales', '{}'::jsonb, 280, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5119', 'GO', 'Servicios Básicos (UTE, OSE, Antel)', '{}'::jsonb, 290, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5120', 'GO', 'Mantenimiento y Reparaciones', '{}'::jsonb, 300, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5121', 'GO', 'Materiales de Oficina', '{}'::jsonb, 310, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5122', 'GO', 'Publicidad y Marketing', '{}'::jsonb, 320, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5123', 'GO', 'Gastos de Representación', '{}'::jsonb, 330, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5124', 'GO', 'Viáticos y Gastos de Viaje', '{}'::jsonb, 340, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5125', 'GO', 'Fletes y Transportes', '{}'::jsonb, 350, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5126', 'GO', 'Comunicaciones', '{}'::jsonb, 360, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5127', 'GO', 'Depreciación del Ejercicio', '{}'::jsonb, 370, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5128', 'GO', 'Amortización de Intangibles', '{}'::jsonb, 380, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5129', 'GO', 'Deudores Incobrables', '{}'::jsonb, 390, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5130', 'GO', 'Donaciones', '{}'::jsonb, 400, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5131', 'GO', 'Patente Única de Rodados', '{}'::jsonb, 410, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5132', 'GO', 'Capacitación del Personal', '{}'::jsonb, 420, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', 'UO', null, 'Utilidad (Pérdida) Operativa', '{}'::jsonb, 420, 1, true, array['UB']::text[], array['GO']::text[], null, null, null),
  ('UY-RES', 'RNO', null, 'Resultado No Operativo', '{}'::jsonb, 430, 1, true, array['5133', '5134', '5135', '5138', '5139', '5140']::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5133', 'RNO', 'Diferencia de Cambio - Pérdida', '{}'::jsonb, 450, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5134', 'RNO', 'Gastos Bancarios', '{}'::jsonb, 460, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5135', 'RNO', 'Intereses por Préstamos', '{}'::jsonb, 470, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5138', 'RNO', 'Multas y Recargos Fiscales', '{}'::jsonb, 480, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5139', 'RNO', 'Gastos Extraordinarios', '{}'::jsonb, 490, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5140', 'RNO', 'Diferencias de Redondeo', '{}'::jsonb, 500, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', 'UAI', null, 'Utilidad (Pérdida) Antes de Impuesto', '{}'::jsonb, 500, 1, true, array['UO']::text[], array['RNO']::text[], null, null, null),
  ('UY-RES', 'IMP', null, 'Impuestos a la Renta y al Patrimonio', '{}'::jsonb, 510, 1, true, array['5136', '5137']::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5136', 'IMP', 'Impuesto a la Renta (IRAE)', '{}'::jsonb, 530, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', '5137', 'IMP', 'Impuesto al Patrimonio', '{}'::jsonb, 540, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UY-RES', 'UN', null, 'Utilidad (Pérdida) Neta', '{}'::jsonb, 540, 1, true, array['UAI']::text[], array['IMP']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('UY-BAL', '1101', 10, 'account_code', '1101', null, null, 'any'),
    ('UY-BAL', '1102', 10, 'account_code', '1102', null, null, 'any'),
    ('UY-BAL', '1103', 10, 'account_code', '1103', null, null, 'any'),
    ('UY-BAL', '1104', 10, 'account_code', '1104', null, null, 'any'),
    ('UY-BAL', '1105', 10, 'account_code', '1105', null, null, 'any'),
    ('UY-BAL', '1106', 10, 'account_code', '1106', null, null, 'any'),
    ('UY-BAL', '1107', 10, 'account_code', '1107', null, null, 'any'),
    ('UY-BAL', '1108', 10, 'account_code', '1108', null, null, 'any'),
    ('UY-BAL', '1109', 10, 'account_code', '1109', null, null, 'any'),
    ('UY-BAL', '1110', 10, 'account_code', '1110', null, null, 'any'),
    ('UY-BAL', '1111', 10, 'account_code', '1111', null, null, 'any'),
    ('UY-BAL', '1112', 10, 'account_code', '1112', null, null, 'any'),
    ('UY-BAL', '1120', 10, 'account_code', '1120', null, null, 'any'),
    ('UY-BAL', '1121', 10, 'account_code', '1121', null, null, 'any'),
    ('UY-BAL', '1122', 10, 'account_code', '1122', null, null, 'any'),
    ('UY-BAL', '1123', 10, 'account_code', '1123', null, null, 'any'),
    ('UY-BAL', '1124', 10, 'account_code', '1124', null, null, 'any'),
    ('UY-BAL', '1125', 10, 'account_code', '1125', null, null, 'any'),
    ('UY-BAL', '1130', 10, 'account_code', '1130', null, null, 'any'),
    ('UY-BAL', '1131', 10, 'account_code', '1131', null, null, 'any'),
    ('UY-BAL', '1132', 10, 'account_code', '1132', null, null, 'any'),
    ('UY-BAL', '1150D', 10, 'account_code', '1150', null, null, 'debit'),
    ('UY-BAL', '1201', 10, 'account_code', '1201', null, null, 'any'),
    ('UY-BAL', '1202', 10, 'account_code', '1202', null, null, 'any'),
    ('UY-BAL', '1203', 10, 'account_code', '1203', null, null, 'any'),
    ('UY-BAL', '1204', 10, 'account_code', '1204', null, null, 'any'),
    ('UY-BAL', '1205', 10, 'account_code', '1205', null, null, 'any'),
    ('UY-BAL', '1206', 10, 'account_code', '1206', null, null, 'any'),
    ('UY-BAL', '1207', 10, 'account_code', '1207', null, null, 'any'),
    ('UY-BAL', '1208', 10, 'account_code', '1208', null, null, 'any'),
    ('UY-BAL', '1210', 10, 'account_code', '1210', null, null, 'any'),
    ('UY-BAL', '1211', 10, 'account_code', '1211', null, null, 'any'),
    ('UY-BAL', '1212', 10, 'account_code', '1212', null, null, 'any'),
    ('UY-BAL', '1213', 10, 'account_code', '1213', null, null, 'any'),
    ('UY-BAL', '1214', 10, 'account_code', '1214', null, null, 'any'),
    ('UY-BAL', '1215', 10, 'account_code', '1215', null, null, 'any'),
    ('UY-BAL', '1216', 10, 'account_code', '1216', null, null, 'any'),
    ('UY-BAL', '1220', 10, 'account_code', '1220', null, null, 'any'),
    ('UY-BAL', '1301', 10, 'account_code', '1301', null, null, 'any'),
    ('UY-BAL', '1302', 10, 'account_code', '1302', null, null, 'any'),
    ('UY-BAL', '1303', 10, 'account_code', '1303', null, null, 'any'),
    ('UY-BAL', '1304', 10, 'account_code', '1304', null, null, 'any'),
    ('UY-BAL', '2101', 10, 'account_code', '2101', null, null, 'any'),
    ('UY-BAL', '2102', 10, 'account_code', '2102', null, null, 'any'),
    ('UY-BAL', '2103', 10, 'account_code', '2103', null, null, 'any'),
    ('UY-BAL', '2104', 10, 'account_code', '2104', null, null, 'any'),
    ('UY-BAL', '2105', 10, 'account_code', '2105', null, null, 'any'),
    ('UY-BAL', '2106', 10, 'account_code', '2106', null, null, 'any'),
    ('UY-BAL', '2107', 10, 'account_code', '2107', null, null, 'any'),
    ('UY-BAL', '2108', 10, 'account_code', '2108', null, null, 'any'),
    ('UY-BAL', '2109', 10, 'account_code', '2109', null, null, 'any'),
    ('UY-BAL', '2110', 10, 'account_code', '2110', null, null, 'any'),
    ('UY-BAL', '2111', 10, 'account_code', '2111', null, null, 'any'),
    ('UY-BAL', '2112', 10, 'account_code', '2112', null, null, 'any'),
    ('UY-BAL', '2113', 10, 'account_code', '2113', null, null, 'any'),
    ('UY-BAL', '2114', 10, 'account_code', '2114', null, null, 'any'),
    ('UY-BAL', '2115', 10, 'account_code', '2115', null, null, 'any'),
    ('UY-BAL', '2116', 10, 'account_code', '2116', null, null, 'any'),
    ('UY-BAL', '2117', 10, 'account_code', '2117', null, null, 'any'),
    ('UY-BAL', '1150C', 10, 'account_code', '1150', null, null, 'credit'),
    ('UY-BAL', '2201', 10, 'account_code', '2201', null, null, 'any'),
    ('UY-BAL', '2202', 10, 'account_code', '2202', null, null, 'any'),
    ('UY-BAL', '2203', 10, 'account_code', '2203', null, null, 'any'),
    ('UY-BAL', '3101', 10, 'account_code', '3101', null, null, 'any'),
    ('UY-BAL', '3102', 10, 'account_code', '3102', null, null, 'any'),
    ('UY-BAL', '3103', 10, 'account_code', '3103', null, null, 'any'),
    ('UY-BAL', '3104', 10, 'account_code', '3104', null, null, 'any'),
    ('UY-BAL', '3105', 10, 'account_code', '3105', null, null, 'any'),
    ('UY-BAL', '3106', 10, 'account_code', '3106', null, null, 'any'),
    ('UY-BAL', '3107', 10, 'account_code', '3107', null, null, 'any'),
    ('UY-BAL', '3108', 10, 'account_code', '3108', null, null, 'any'),
    ('UY-BAL', '3109', 10, 'account_code', '3109', null, null, 'any'),
    ('UY-RES', '4101', 10, 'account_code', '4101', null, null, 'any'),
    ('UY-RES', '4102', 10, 'account_code', '4102', null, null, 'any'),
    ('UY-RES', '4103', 10, 'account_code', '4103', null, null, 'any'),
    ('UY-RES', '4104', 10, 'account_code', '4104', null, null, 'any'),
    ('UY-RES', '4105', 10, 'account_code', '4105', null, null, 'any'),
    ('UY-RES', '4106', 10, 'account_code', '4106', null, null, 'any'),
    ('UY-RES', '4107', 10, 'account_code', '4107', null, null, 'any'),
    ('UY-RES', '4108', 10, 'account_code', '4108', null, null, 'any'),
    ('UY-RES', '4109', 10, 'account_code', '4109', null, null, 'any'),
    ('UY-RES', '4110', 10, 'account_code', '4110', null, null, 'any'),
    ('UY-RES', '5101', 10, 'account_code', '5101', null, null, 'any'),
    ('UY-RES', '5102', 10, 'account_code', '5102', null, null, 'any'),
    ('UY-RES', '5103', 10, 'account_code', '5103', null, null, 'any'),
    ('UY-RES', '5104', 10, 'account_code', '5104', null, null, 'any'),
    ('UY-RES', '5110', 10, 'account_code', '5110', null, null, 'any'),
    ('UY-RES', '5111', 10, 'account_code', '5111', null, null, 'any'),
    ('UY-RES', '5112', 10, 'account_code', '5112', null, null, 'any'),
    ('UY-RES', '5113', 10, 'account_code', '5113', null, null, 'any'),
    ('UY-RES', '5114', 10, 'account_code', '5114', null, null, 'any'),
    ('UY-RES', '5115', 10, 'account_code', '5115', null, null, 'any'),
    ('UY-RES', '5116', 10, 'account_code', '5116', null, null, 'any'),
    ('UY-RES', '5117', 10, 'account_code', '5117', null, null, 'any'),
    ('UY-RES', '5118', 10, 'account_code', '5118', null, null, 'any'),
    ('UY-RES', '5119', 10, 'account_code', '5119', null, null, 'any'),
    ('UY-RES', '5120', 10, 'account_code', '5120', null, null, 'any'),
    ('UY-RES', '5121', 10, 'account_code', '5121', null, null, 'any'),
    ('UY-RES', '5122', 10, 'account_code', '5122', null, null, 'any'),
    ('UY-RES', '5123', 10, 'account_code', '5123', null, null, 'any'),
    ('UY-RES', '5124', 10, 'account_code', '5124', null, null, 'any'),
    ('UY-RES', '5125', 10, 'account_code', '5125', null, null, 'any'),
    ('UY-RES', '5126', 10, 'account_code', '5126', null, null, 'any'),
    ('UY-RES', '5127', 10, 'account_code', '5127', null, null, 'any'),
    ('UY-RES', '5128', 10, 'account_code', '5128', null, null, 'any'),
    ('UY-RES', '5129', 10, 'account_code', '5129', null, null, 'any'),
    ('UY-RES', '5130', 10, 'account_code', '5130', null, null, 'any'),
    ('UY-RES', '5131', 10, 'account_code', '5131', null, null, 'any'),
    ('UY-RES', '5132', 10, 'account_code', '5132', null, null, 'any'),
    ('UY-RES', '5133', 10, 'account_code', '5133', null, null, 'any'),
    ('UY-RES', '5134', 10, 'account_code', '5134', null, null, 'any'),
    ('UY-RES', '5135', 10, 'account_code', '5135', null, null, 'any'),
    ('UY-RES', '5138', 10, 'account_code', '5138', null, null, 'any'),
    ('UY-RES', '5139', 10, 'account_code', '5139', null, null, 'any'),
    ('UY-RES', '5140', 10, 'account_code', '5140', null, null, 'any'),
    ('UY-RES', '5136', 10, 'account_code', '5136', null, null, 'any'),
    ('UY-RES', '5137', 10, 'account_code', '5137', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('UY', 'Uruguay', '{}'::jsonb, array['es']::text[], 'UYU', '1103', '2101', '1150', '5140', '3103', '4101', '5102', '1102', '1101', 'VEN', 'COM', 'DIA', 'es', 'result_accounts', '3105', '3106', '3104', 'APE', 'half_up', default, '4108', '5133', null, null, null, null, '2106', '1108', 'Asiento de apertura', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{NNNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Decreto N° 36/012, de 8 de febrero de 2012, y Resolución de la Dirección General Impositiva N° 798/012 — el Comprobante Fiscal Electrónico (CFE) se identifica por un tipo de comprobante, una serie y un número correlativo que el propio emisor electrónico asigna dentro del régimen que la Dirección General Impositiva autoriza, y que ésta valida mediante un Código de Autorización de Emisión (CAE) previamente otorgado por rangos — un mecanismo de autorización previa de numeración y reporte posterior, no la certificación documento a documento de un tercero como el PAC mexicano. El número que declara este paquete es el de la pieza contable, correlativo por diario, y no un número de un CAE que Ekwo no solicita: véase «Ekwo no emite un CFE uruguayo» en el README',
  numbering_source_key          = 'decreto36-012',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Texto Ordenado 2023, Título 10, art. 3° — el hecho gravado se considera configurado cuando el contrato o acto equivalente tenga ejecución mediante la entrega o la introducción de los bienes o la prestación de los servicios, pero «las entregas de bienes y prestaciones de servicios se presumirán realizadas en la fecha de la factura respectiva, sin perjuicio de las facultades de la Administración de fijar la misma, cuando existiera omisión, anticipación o retardo en la facturación». Este paquete declara invoice_if_issued por esa presunción legal, que hace coincidir en la generalidad de los casos la fecha del hecho gravado con la de la factura',
  tax_point_source_key          = 'to2023-t10',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Texto Ordenado 2023, Título 10, art. 3°, inciso quinto — el contribuyente tiene derecho a la deducción del impuesto facturado cuando la contraprestación no se hace efectiva por devolución de mercadería, bonificación, descuento o ajuste posterior de precio, entre otras causas, deducción que en la práctica documental del CFE y de todo comprobante fiscal se instrumenta mediante una nota de crédito que individualiza el comprobante que corrige. Un documento contabilizado se corrige con una nota de crédito que lo nombra, nunca con la edición del documento original',
  posted_edit_policy_source_key = 'to2023-t10',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Decreto N° 36/012, de 8 de febrero de 2012, que fija el régimen de documentación fiscal electrónica, y Resolución de la Dirección General Impositiva de Interés General N° 798/012, que lo implementa; la incorporación se extendió de forma escalonada desde 2012 según el volumen de ingresos del contribuyente hasta alcanzar, a partir del 1° de enero de 2025, a todos los contribuyentes del Impuesto al Valor Agregado, incluso los del IVA mínimo, con excepciones puntuales (actividad agropecuaria de reducida dimensión, agregación de valor en la construcción, contribuyentes del Impuesto a las Rentas de los No Residentes, Monotributo y Monotributo Social MIDES). El Comprobante Fiscal Electrónico (CFE) — e-Factura para operaciones entre contribuyentes, e-Ticket para el consumo final — se emite firmado electrónicamente por el emisor y validado mediante un Código de Autorización de Emisión (CAE) que la Dirección General Impositiva otorga por rangos, un régimen de autorización previa y reporte posterior más próximo al de Chile que a la certificación documento a documento de un tercero. La obligación es real y universal desde el 1° de enero de 2025 (con las excepciones puntuales arriba dichas), pero este paquete no puede escribirla en `mandatory_from`: ese campo exige un `profile` no nulo — un perfil construido sobre EN 16931 que una pieza de packages/formats escribe — y el CFE no lo es, por lo que `obligation: mandatory` tampoco puede declararse sin `mandatory_from`; véase «From Uruguay» en docs/international.md. EKWO NO SOLICITA CAE, NO FIRMA NI TRANSMITE CFE: ningún componente de packages/formats emite el XML del CFE uruguayo ni se comunica con la Dirección General Impositiva, y un documento emitido desde Ekwo no es un comprobante tributario uruguayo. El Registro Único Tributario (RUT) identifica a emisor y receptor y no tiene código ISO 6523 de la lista que el formato usa para party_scheme y vat_scheme',
  einvoice_source_key           = 'decreto36-012',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = array['csv']::text[],
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'UY';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('UY', 'cfe_not_issued', 'always', 'Este documento no es un Comprobante Fiscal Electrónico (CFE): no lleva Código de Autorización de Emisión (CAE) de la Dirección General Impositiva ni su representación validada. Sólo el CFE con CAE ampara la operación para efectos tributarios en Uruguay.', '{}'::jsonb, 10, date '1970-01-01', null, 'Decreto N° 36/012, de 8 de febrero de 2012, y Resolución de la Dirección General Impositiva N° 798/012, que fijan el régimen de documentación fiscal electrónica; desde el 1° de enero de 2025 todos los contribuyentes del Impuesto al Valor Agregado, incluidos los del IVA mínimo, revisten la calidad de emisores electrónicos desde su inscripción, salvo excepciones puntuales. Ekwo no solicita CAE, no firma ni transmite CFE: la frase evita que el documento que Ekwo produce se tome por el comprobante fiscal uruguayo'),
  ('UY', 'export', 'export', 'Exportación — operación no gravada por el Impuesto al Valor Agregado (artículo 5° del Título 10 del Texto Ordenado 2023).', '{}'::jsonb, 20, date '1970-01-01', null, 'Texto Ordenado 2023, Título 10, art. 5° — «Tampoco estarán gravadas aquellas exportaciones de bienes … y no lo estarán aquellas exportaciones de servicios que determine el Poder Ejecutivo», enumeradas por el Decreto N° 220/998, art. 34'),
  ('UY', 'exempt', 'exempt', 'Operación exonerada del Impuesto al Valor Agregado (artículo 38 del Título 10 del Texto Ordenado 2023).', '{}'::jsonb, 30, date '1970-01-01', null, 'Texto Ordenado 2023, Título 10, art. 38 — exoneraciones de determinados bienes, prestaciones de servicios e importaciones')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
