-- Ekwo OS — 中国: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/cn at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build cn`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   中华人民共和国增值税法（2024年12月25日第十四届全国人民代表大会常务委员会第十三次会议通过，自2026年1月1日起施行）— Value-Added Tax Law of the People's Republic of China (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c100009/c5237365/content.html
--   中华人民共和国增值税法实施条例（国务院令第826号，自2026年1月1日起施行）— Implementing Regulations of the VAT Law (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c100010/c5246349/content.html
--   财政部 税务总局关于增值税法施行后增值税优惠政策衔接事项的公告（财政部 税务总局公告2026年第10号）— the preferential VAT policies continued after the VAT Law took effect (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c102416/c5247434/content.html
--   国家税务总局关于起征点标准等增值税征管事项的公告（国家税务总局公告2026年第4号）— thresholds and the 1% small-scale rate, administration (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c100012/c5247426/content.html
--   增值税及附加税费申报表（一般纳税人适用）— VAT and surcharges return, general taxpayer: the form, its schedules and filling instructions (国家税务总局 12366纳税服务平台 State Taxation Administration, 12366 taxpayer service platform)
--     https://12366.chinatax.gov.cn/bzds/009/009.html
--   国家税务总局关于增值税消费税与附加税费申报表整合有关事项的公告（国家税务总局公告2021年第20号）— the notice that issued the combined VAT and surcharges return (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c100012/c5194981/content.html
--   国家税务总局关于调整增值税纳税申报有关事项的公告（国家税务总局公告2026年第6号）— the filling instructions adjusted for the VAT Law (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c100012/c5247507/content.html
--   全国统一规范电子税务局 — the national electronic tax bureau, where the return is filed and the digital invoices are issued (linked from the home page of www.chinatax.gov.cn) (国家税务总局 State Taxation Administration)
--     https://etax.chinatax.gov.cn/
--   国家税务总局关于推广应用全面数字化电子发票的公告（国家税务总局公告2024年第11号）— the fully digitalised electronic invoice, nationwide from 1 December 2024 (中国政府网 国务院部门文件 — www.gov.cn)
--     https://www.gov.cn/zhengce/zhengceku/202411/content_6989164.htm
--   财政部关于印发《企业会计准则——应用指南》的通知（财会〔2006〕18号），附录：会计科目和主要账务处理 — Accounting Standards for Business Enterprises, Application Guidance, appendix: the accounts and their main entries (商务部 全球法规网 Ministry of Commerce, legal database (reproducing the Ministry of Finance notice))
--     https://policy.mofcom.gov.cn/claw/clawContent.shtml?id=13655
--   财政部关于印发《增值税会计处理规定》的通知（财会〔2016〕22号）— VAT accounting rules (中华人民共和国财政部 Ministry of Finance)
--     https://www.mof.gov.cn/gp/xxgkml/hjs/201612/t20161214_2512803.htm
--   财政部关于修订印发2019年度一般企业财务报表格式的通知（财会〔2019〕6号）— financial statement formats for general enterprises (中华人民共和国财政部会计司 Ministry of Finance, Accounting Regulatory Department)
--     https://kjs.mof.gov.cn/zhengcefabu/201905/t20190510_3254992.htm
--   中华人民共和国城市维护建设税法 — Urban Maintenance and Construction Tax Law (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c100009/c5193055/content.html
--   征收教育费附加的暂行规定 — Interim Provisions on the Collection of the Education Surcharge (司法部 国家行政法规库 Ministry of Justice, national database of administrative regulations)
--     https://xzfg.moj.gov.cn/front/law/detail?LawID=762
--   财政部关于统一地方教育附加政策有关问题的通知（财综〔2010〕98号）— the local education surcharge (国家税务总局 State Taxation Administration — 税收政策库)
--     https://fgk.chinatax.gov.cn/zcfgk/c102416/c5194201/content.html
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('CN', '中国', '0.1.0', date '2026-09-26', '20260917170000', 'community', null, null, '4fe4e1ab732221f147b75e182c36ac35a90c5449b7186f03e0b30230b7fac197', '[{"key":"vat-law","title":"中华人民共和国增值税法（2024年12月25日第十四届全国人民代表大会常务委员会第十三次会议通过，自2026年1月1日起施行）— Value-Added Tax Law of the People''s Republic of China","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c100009/c5237365/content.html","consulted_on":"2026-09-26","kind":"law"},{"key":"vat-regs","title":"中华人民共和国增值税法实施条例（国务院令第826号，自2026年1月1日起施行）— Implementing Regulations of the VAT Law","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c100010/c5246349/content.html","consulted_on":"2026-09-26","kind":"regulation"},{"key":"vat-bridge","title":"财政部 税务总局关于增值税法施行后增值税优惠政策衔接事项的公告（财政部 税务总局公告2026年第10号）— the preferential VAT policies continued after the VAT Law took effect","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c102416/c5247434/content.html","consulted_on":"2026-09-26","kind":"regulation"},{"key":"sta-2026-4","title":"国家税务总局关于起征点标准等增值税征管事项的公告（国家税务总局公告2026年第4号）— thresholds and the 1% small-scale rate, administration","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c100012/c5247426/content.html","consulted_on":"2026-09-26","kind":"guidance"},{"key":"form-general","title":"增值税及附加税费申报表（一般纳税人适用）— VAT and surcharges return, general taxpayer: the form, its schedules and filling instructions","publisher":"国家税务总局 12366纳税服务平台 State Taxation Administration, 12366 taxpayer service platform","url":"https://12366.chinatax.gov.cn/bzds/009/009.html","consulted_on":"2026-09-26","kind":"form"},{"key":"form-2021-20","title":"国家税务总局关于增值税消费税与附加税费申报表整合有关事项的公告（国家税务总局公告2021年第20号）— the notice that issued the combined VAT and surcharges return","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c100012/c5194981/content.html","consulted_on":"2026-09-26","kind":"form"},{"key":"form-2026-6","title":"国家税务总局关于调整增值税纳税申报有关事项的公告（国家税务总局公告2026年第6号）— the filling instructions adjusted for the VAT Law","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c100012/c5247507/content.html","consulted_on":"2026-09-26","kind":"form"},{"key":"etax-portal","title":"全国统一规范电子税务局 — the national electronic tax bureau, where the return is filed and the digital invoices are issued (linked from the home page of www.chinatax.gov.cn)","publisher":"国家税务总局 State Taxation Administration","url":"https://etax.chinatax.gov.cn/","consulted_on":"2026-09-26","kind":"portal"},{"key":"einvoice-2024-11","title":"国家税务总局关于推广应用全面数字化电子发票的公告（国家税务总局公告2024年第11号）— the fully digitalised electronic invoice, nationwide from 1 December 2024","publisher":"中国政府网 国务院部门文件 — www.gov.cn","url":"https://www.gov.cn/zhengce/zhengceku/202411/content_6989164.htm","consulted_on":"2026-09-26","kind":"regulation"},{"key":"asbe-guide","title":"财政部关于印发《企业会计准则——应用指南》的通知（财会〔2006〕18号），附录：会计科目和主要账务处理 — Accounting Standards for Business Enterprises, Application Guidance, appendix: the accounts and their main entries","publisher":"商务部 全球法规网 Ministry of Commerce, legal database (reproducing the Ministry of Finance notice)","url":"https://policy.mofcom.gov.cn/claw/clawContent.shtml?id=13655","consulted_on":"2026-09-26","kind":"regulation"},{"key":"vat-accounting","title":"财政部关于印发《增值税会计处理规定》的通知（财会〔2016〕22号）— VAT accounting rules","publisher":"中华人民共和国财政部 Ministry of Finance","url":"https://www.mof.gov.cn/gp/xxgkml/hjs/201612/t20161214_2512803.htm","consulted_on":"2026-09-26","kind":"regulation"},{"key":"fs-format","title":"财政部关于修订印发2019年度一般企业财务报表格式的通知（财会〔2019〕6号）— financial statement formats for general enterprises","publisher":"中华人民共和国财政部会计司 Ministry of Finance, Accounting Regulatory Department","url":"https://kjs.mof.gov.cn/zhengcefabu/201905/t20190510_3254992.htm","consulted_on":"2026-09-26","kind":"regulation"},{"key":"umct-law","title":"中华人民共和国城市维护建设税法 — Urban Maintenance and Construction Tax Law","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c100009/c5193055/content.html","consulted_on":"2026-09-26","kind":"law"},{"key":"edu-surcharge","title":"征收教育费附加的暂行规定 — Interim Provisions on the Collection of the Education Surcharge","publisher":"司法部 国家行政法规库 Ministry of Justice, national database of administrative regulations","url":"https://xzfg.moj.gov.cn/front/law/detail?LawID=762","consulted_on":"2026-09-26","kind":"regulation"},{"key":"local-edu","title":"财政部关于统一地方教育附加政策有关问题的通知（财综〔2010〕98号）— the local education surcharge","publisher":"国家税务总局 State Taxation Administration — 税收政策库","url":"https://fgk.chinatax.gov.cn/zcfgk/c102416/c5194201/content.html","consulted_on":"2026-09-26","kind":"regulation"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('CN', 'default', '企业会计准则 会计科目（节选）— Accounts of the Accounting Standards for Business Enterprises, abridged', '{"en":"Accounts of the Accounting Standards for Business Enterprises (abridged)"}'::jsonb, true, 'companies', array['CN-ASBE-BS', 'CN-ASBE-IS']::text[], null, '《企业会计准则——应用指南》（财会〔2006〕18号）附录《会计科目和主要账务处理》 — the first-level accounts and their four-digit codes are transcribed from the appendix, leaving out those of banks, insurers and securities firms, and 6403 carries the name 税金及附加 that 财会〔2016〕22号 gave 营业税金及附加. The appendix lets an enterprise add, split or merge accounts and set its own detail accounts and numbers ("对于明细科目，企业可以比照本附录中的规定自行设置。会计科目编号供企业…参考，企业可结合实际情况自行确定会计科目编号"): the detail accounts of 应付职工薪酬, 盈余公积, 利润分配 and 所得税费用 are the ones the appendix names for them; those of 应交税费 are the ones 财会〔2016〕22号 prescribes; the columns (专栏) of 应交增值税 are carried as accounts 22210101 to 22210110 beside 222101, which the same rule gives a small-scale taxpayer as its one VAT account. Four codes are this pack''s own, for accounts later standards introduced and the 2006 appendix does not number: 6115 资产处置损益, 6117 其他收益, 6702 信用减值损失, and the six-digit expense details of 销售费用, 管理费用 and 财务费用. See the README.', 'asbe-guide')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('CN', 'default', '1001', '库存现金', '{"en":"Cash on hand"}'::jsonb, 'asset_cash', false, null, 10),
  ('CN', 'default', '1002', '银行存款', '{"en":"Bank deposits"}'::jsonb, 'asset_cash', false, null, 20),
  ('CN', 'default', '1012', '其他货币资金', '{"en":"Other monetary funds"}'::jsonb, 'asset_cash', false, null, 30),
  ('CN', 'default', '1101', '交易性金融资产', '{"en":"Financial assets held for trading"}'::jsonb, 'asset_current', false, null, 40),
  ('CN', 'default', '1121', '应收票据', '{"en":"Notes receivable"}'::jsonb, 'asset_current', false, null, 50),
  ('CN', 'default', '1122', '应收账款', '{"en":"Accounts receivable"}'::jsonb, 'asset_receivable', true, null, 60),
  ('CN', 'default', '1123', '预付账款', '{"en":"Prepayments"}'::jsonb, 'asset_prepayments', false, null, 70),
  ('CN', 'default', '1131', '应收股利', '{"en":"Dividends receivable"}'::jsonb, 'asset_current', false, null, 80),
  ('CN', 'default', '1132', '应收利息', '{"en":"Interest receivable"}'::jsonb, 'asset_current', false, null, 90),
  ('CN', 'default', '1221', '其他应收款', '{"en":"Other receivables"}'::jsonb, 'asset_current', false, null, 100),
  ('CN', 'default', '1231', '坏账准备', '{"en":"Allowance for bad debts"}'::jsonb, 'asset_current', false, null, 110),
  ('CN', 'default', '1401', '材料采购', '{"en":"Materials procurement"}'::jsonb, 'asset_current', false, null, 120),
  ('CN', 'default', '1402', '在途物资', '{"en":"Goods in transit"}'::jsonb, 'asset_current', false, null, 130),
  ('CN', 'default', '1403', '原材料', '{"en":"Raw materials"}'::jsonb, 'asset_current', false, null, 140),
  ('CN', 'default', '1404', '材料成本差异', '{"en":"Materials cost variance"}'::jsonb, 'asset_current', false, null, 150),
  ('CN', 'default', '1405', '库存商品', '{"en":"Merchandise inventory"}'::jsonb, 'asset_current', false, null, 160),
  ('CN', 'default', '1406', '发出商品', '{"en":"Goods dispatched"}'::jsonb, 'asset_current', false, null, 170),
  ('CN', 'default', '1407', '商品进销差价', '{"en":"Merchandise price differences"}'::jsonb, 'asset_current', false, null, 180),
  ('CN', 'default', '1408', '委托加工物资', '{"en":"Materials sent for processing"}'::jsonb, 'asset_current', false, null, 190),
  ('CN', 'default', '1411', '周转材料', '{"en":"Revolving materials"}'::jsonb, 'asset_current', false, null, 200),
  ('CN', 'default', '1421', '消耗性生物资产', '{"en":"Consumable biological assets"}'::jsonb, 'asset_current', false, null, 210),
  ('CN', 'default', '1471', '存货跌价准备', '{"en":"Inventory write-down allowance"}'::jsonb, 'asset_current', false, null, 220),
  ('CN', 'default', '1511', '长期股权投资', '{"en":"Long-term equity investments"}'::jsonb, 'asset_non_current', false, null, 230),
  ('CN', 'default', '1512', '长期股权投资减值准备', '{"en":"Impairment allowance, long-term equity investments"}'::jsonb, 'asset_non_current', false, null, 240),
  ('CN', 'default', '1521', '投资性房地产', '{"en":"Investment property"}'::jsonb, 'asset_non_current', false, null, 250),
  ('CN', 'default', '1531', '长期应收款', '{"en":"Long-term receivables"}'::jsonb, 'asset_non_current', false, null, 260),
  ('CN', 'default', '1532', '未实现融资收益', '{"en":"Unrealised financing income"}'::jsonb, 'asset_non_current', false, null, 270),
  ('CN', 'default', '1601', '固定资产', '{"en":"Fixed assets"}'::jsonb, 'asset_fixed', false, null, 280),
  ('CN', 'default', '1602', '累计折旧', '{"en":"Accumulated depreciation"}'::jsonb, 'asset_fixed', false, null, 290),
  ('CN', 'default', '1603', '固定资产减值准备', '{"en":"Impairment allowance, fixed assets"}'::jsonb, 'asset_fixed', false, null, 300),
  ('CN', 'default', '1604', '在建工程', '{"en":"Construction in progress"}'::jsonb, 'asset_fixed', false, null, 310),
  ('CN', 'default', '1605', '工程物资', '{"en":"Construction materials"}'::jsonb, 'asset_fixed', false, null, 320),
  ('CN', 'default', '1606', '固定资产清理', '{"en":"Fixed assets in liquidation"}'::jsonb, 'asset_fixed', false, null, 330),
  ('CN', 'default', '1621', '生产性生物资产', '{"en":"Productive biological assets"}'::jsonb, 'asset_fixed', false, null, 340),
  ('CN', 'default', '1622', '生产性生物资产累计折旧', '{"en":"Accumulated depreciation, productive biological assets"}'::jsonb, 'asset_fixed', false, null, 350),
  ('CN', 'default', '1701', '无形资产', '{"en":"Intangible assets"}'::jsonb, 'asset_non_current', false, null, 360),
  ('CN', 'default', '1702', '累计摊销', '{"en":"Accumulated amortisation"}'::jsonb, 'asset_non_current', false, null, 370),
  ('CN', 'default', '1703', '无形资产减值准备', '{"en":"Impairment allowance, intangible assets"}'::jsonb, 'asset_non_current', false, null, 380),
  ('CN', 'default', '1711', '商誉', '{"en":"Goodwill"}'::jsonb, 'asset_non_current', false, null, 390),
  ('CN', 'default', '1801', '长期待摊费用', '{"en":"Long-term deferred expenses"}'::jsonb, 'asset_non_current', false, null, 400),
  ('CN', 'default', '1811', '递延所得税资产', '{"en":"Deferred tax assets"}'::jsonb, 'asset_non_current', false, null, 410),
  ('CN', 'default', '1901', '待处理财产损溢', '{"en":"Property losses and gains pending treatment"}'::jsonb, 'asset_current', false, null, 420),
  ('CN', 'default', '2001', '短期借款', '{"en":"Short-term borrowings"}'::jsonb, 'liability_current', false, null, 430),
  ('CN', 'default', '2101', '交易性金融负债', '{"en":"Financial liabilities held for trading"}'::jsonb, 'liability_current', false, null, 440),
  ('CN', 'default', '2201', '应付票据', '{"en":"Notes payable"}'::jsonb, 'liability_current', false, null, 450),
  ('CN', 'default', '2202', '应付账款', '{"en":"Accounts payable"}'::jsonb, 'liability_payable', true, null, 460),
  ('CN', 'default', '2203', '预收账款', '{"en":"Advances from customers"}'::jsonb, 'liability_current', false, null, 470),
  ('CN', 'default', '2211', '应付职工薪酬', '{"en":"Employee benefits payable"}'::jsonb, 'liability_current', false, null, 480),
  ('CN', 'default', '221101', '工资', '{"en":"Wages and salaries"}'::jsonb, 'liability_current', false, '2211', 490),
  ('CN', 'default', '221102', '职工福利', '{"en":"Staff welfare"}'::jsonb, 'liability_current', false, '2211', 500),
  ('CN', 'default', '221103', '社会保险费', '{"en":"Social insurance contributions"}'::jsonb, 'liability_current', false, '2211', 510),
  ('CN', 'default', '221104', '住房公积金', '{"en":"Housing provident fund"}'::jsonb, 'liability_current', false, '2211', 520),
  ('CN', 'default', '221105', '工会经费', '{"en":"Trade union funds"}'::jsonb, 'liability_current', false, '2211', 530),
  ('CN', 'default', '221106', '职工教育经费', '{"en":"Staff education funds"}'::jsonb, 'liability_current', false, '2211', 540),
  ('CN', 'default', '221107', '非货币性福利', '{"en":"Non-monetary benefits"}'::jsonb, 'liability_current', false, '2211', 550),
  ('CN', 'default', '221108', '辞退福利', '{"en":"Termination benefits"}'::jsonb, 'liability_current', false, '2211', 560),
  ('CN', 'default', '221109', '股份支付', '{"en":"Share-based payments"}'::jsonb, 'liability_current', false, '2211', 570),
  ('CN', 'default', '2221', '应交税费', '{"en":"Taxes payable"}'::jsonb, 'liability_current', false, null, 580),
  ('CN', 'default', '222101', '应交增值税', '{"en":"VAT payable"}'::jsonb, 'liability_current', false, '2221', 590),
  ('CN', 'default', '22210101', '应交增值税（进项税额）', '{"en":"VAT payable (input VAT)"}'::jsonb, 'liability_current', false, '2221', 600),
  ('CN', 'default', '22210102', '应交增值税（销项税额抵减）', '{"en":"VAT payable (output VAT offset)"}'::jsonb, 'liability_current', false, '2221', 610),
  ('CN', 'default', '22210103', '应交增值税（已交税金）', '{"en":"VAT payable (VAT paid)"}'::jsonb, 'liability_current', false, '2221', 620),
  ('CN', 'default', '22210104', '应交增值税（转出未交增值税）', '{"en":"VAT payable (transfer of unpaid VAT)"}'::jsonb, 'liability_current', false, '2221', 630),
  ('CN', 'default', '22210105', '应交增值税（减免税款）', '{"en":"VAT payable (VAT relief)"}'::jsonb, 'liability_current', false, '2221', 640),
  ('CN', 'default', '22210106', '应交增值税（出口抵减内销产品应纳税额）', '{"en":"VAT payable (export credit against domestic VAT)"}'::jsonb, 'liability_current', false, '2221', 650),
  ('CN', 'default', '22210107', '应交增值税（销项税额）', '{"en":"VAT payable (output VAT)"}'::jsonb, 'liability_current', false, '2221', 660),
  ('CN', 'default', '22210108', '应交增值税（出口退税）', '{"en":"VAT payable (export refund)"}'::jsonb, 'liability_current', false, '2221', 670),
  ('CN', 'default', '22210109', '应交增值税（进项税额转出）', '{"en":"VAT payable (input VAT transferred out)"}'::jsonb, 'liability_current', false, '2221', 680),
  ('CN', 'default', '22210110', '应交增值税（转出多交增值税）', '{"en":"VAT payable (transfer of overpaid VAT)"}'::jsonb, 'liability_current', false, '2221', 690),
  ('CN', 'default', '222102', '未交增值税', '{"en":"Unpaid VAT"}'::jsonb, 'liability_current', true, '2221', 700),
  ('CN', 'default', '222103', '预交增值税', '{"en":"Prepaid VAT"}'::jsonb, 'liability_current', false, '2221', 710),
  ('CN', 'default', '222104', '待抵扣进项税额', '{"en":"Input VAT pending deduction"}'::jsonb, 'liability_current', false, '2221', 720),
  ('CN', 'default', '222105', '待认证进项税额', '{"en":"Input VAT pending verification"}'::jsonb, 'liability_current', false, '2221', 730),
  ('CN', 'default', '222106', '待转销项税额', '{"en":"Output VAT pending recognition"}'::jsonb, 'liability_current', false, '2221', 740),
  ('CN', 'default', '222107', '增值税留抵税额', '{"en":"Retained VAT credit"}'::jsonb, 'liability_current', false, '2221', 750),
  ('CN', 'default', '222108', '简易计税', '{"en":"VAT under the simplified method"}'::jsonb, 'liability_current', false, '2221', 760),
  ('CN', 'default', '222109', '转让金融商品应交增值税', '{"en":"VAT payable on transfers of financial products"}'::jsonb, 'liability_current', false, '2221', 770),
  ('CN', 'default', '222110', '代扣代交增值税', '{"en":"VAT withheld"}'::jsonb, 'liability_current', false, '2221', 780),
  ('CN', 'default', '222111', '应交消费税', '{"en":"Consumption tax payable"}'::jsonb, 'liability_current', false, '2221', 790),
  ('CN', 'default', '222112', '应交城市维护建设税', '{"en":"Urban maintenance and construction tax payable"}'::jsonb, 'liability_current', false, '2221', 800),
  ('CN', 'default', '222113', '应交教育费附加', '{"en":"Education surcharge payable"}'::jsonb, 'liability_current', false, '2221', 810),
  ('CN', 'default', '222114', '应交地方教育附加', '{"en":"Local education surcharge payable"}'::jsonb, 'liability_current', false, '2221', 820),
  ('CN', 'default', '222115', '应交企业所得税', '{"en":"Enterprise income tax payable"}'::jsonb, 'liability_current', false, '2221', 830),
  ('CN', 'default', '222116', '应交个人所得税', '{"en":"Individual income tax withheld"}'::jsonb, 'liability_current', false, '2221', 840),
  ('CN', 'default', '222117', '应交房产税', '{"en":"Property tax payable"}'::jsonb, 'liability_current', false, '2221', 850),
  ('CN', 'default', '222118', '应交城镇土地使用税', '{"en":"Urban land use tax payable"}'::jsonb, 'liability_current', false, '2221', 860),
  ('CN', 'default', '222119', '应交车船税', '{"en":"Vehicle and vessel tax payable"}'::jsonb, 'liability_current', false, '2221', 870),
  ('CN', 'default', '222120', '应交印花税', '{"en":"Stamp tax payable"}'::jsonb, 'liability_current', false, '2221', 880),
  ('CN', 'default', '2231', '应付利息', '{"en":"Interest payable"}'::jsonb, 'liability_current', false, null, 890),
  ('CN', 'default', '2232', '应付股利', '{"en":"Dividends payable"}'::jsonb, 'liability_current', false, null, 900),
  ('CN', 'default', '2241', '其他应付款', '{"en":"Other payables"}'::jsonb, 'liability_current', false, null, 910),
  ('CN', 'default', '2401', '递延收益', '{"en":"Deferred income"}'::jsonb, 'liability_non_current', false, null, 920),
  ('CN', 'default', '2501', '长期借款', '{"en":"Long-term borrowings"}'::jsonb, 'liability_non_current', false, null, 930),
  ('CN', 'default', '2502', '应付债券', '{"en":"Bonds payable"}'::jsonb, 'liability_non_current', false, null, 940),
  ('CN', 'default', '2701', '长期应付款', '{"en":"Long-term payables"}'::jsonb, 'liability_non_current', false, null, 950),
  ('CN', 'default', '2702', '未确认融资费用', '{"en":"Unrecognised financing charges"}'::jsonb, 'liability_non_current', false, null, 960),
  ('CN', 'default', '2711', '专项应付款', '{"en":"Special-purpose payables"}'::jsonb, 'liability_non_current', false, null, 970),
  ('CN', 'default', '2801', '预计负债', '{"en":"Provisions"}'::jsonb, 'liability_non_current', false, null, 980),
  ('CN', 'default', '2901', '递延所得税负债', '{"en":"Deferred tax liabilities"}'::jsonb, 'liability_non_current', false, null, 990),
  ('CN', 'default', '4001', '实收资本', '{"en":"Paid-in capital"}'::jsonb, 'equity', false, null, 1000),
  ('CN', 'default', '4002', '资本公积', '{"en":"Capital reserve"}'::jsonb, 'equity', false, null, 1010),
  ('CN', 'default', '4101', '盈余公积', '{"en":"Surplus reserve"}'::jsonb, 'equity', false, null, 1020),
  ('CN', 'default', '410101', '法定盈余公积', '{"en":"Statutory surplus reserve"}'::jsonb, 'equity', false, '4101', 1030),
  ('CN', 'default', '410102', '任意盈余公积', '{"en":"Discretionary surplus reserve"}'::jsonb, 'equity', false, '4101', 1040),
  ('CN', 'default', '4103', '本年利润', '{"en":"Profit for the year"}'::jsonb, 'equity', false, null, 1050),
  ('CN', 'default', '4104', '利润分配', '{"en":"Profit distribution"}'::jsonb, 'equity', false, null, 1060),
  ('CN', 'default', '410401', '提取法定盈余公积', '{"en":"Appropriation to statutory surplus reserve"}'::jsonb, 'equity', false, '4104', 1070),
  ('CN', 'default', '410402', '提取任意盈余公积', '{"en":"Appropriation to discretionary surplus reserve"}'::jsonb, 'equity', false, '4104', 1080),
  ('CN', 'default', '410403', '应付现金股利或利润', '{"en":"Cash dividends or profits payable"}'::jsonb, 'equity', false, '4104', 1090),
  ('CN', 'default', '410404', '转作股本的股利', '{"en":"Dividends converted into share capital"}'::jsonb, 'equity', false, '4104', 1100),
  ('CN', 'default', '410405', '盈余公积补亏', '{"en":"Losses made up from surplus reserve"}'::jsonb, 'equity', false, '4104', 1110),
  ('CN', 'default', '410406', '未分配利润', '{"en":"Undistributed profits"}'::jsonb, 'equity_retained', false, '4104', 1120),
  ('CN', 'default', '4201', '库存股', '{"en":"Treasury shares"}'::jsonb, 'equity', false, null, 1130),
  ('CN', 'default', '5001', '生产成本', '{"en":"Production costs"}'::jsonb, 'asset_current', false, null, 1140),
  ('CN', 'default', '5101', '制造费用', '{"en":"Manufacturing overheads"}'::jsonb, 'asset_current', false, null, 1150),
  ('CN', 'default', '5201', '劳务成本', '{"en":"Service costs"}'::jsonb, 'asset_current', false, null, 1160),
  ('CN', 'default', '5301', '研发支出', '{"en":"Research and development expenditure"}'::jsonb, 'asset_non_current', false, null, 1170),
  ('CN', 'default', '6001', '主营业务收入', '{"en":"Revenue from principal operations"}'::jsonb, 'income', false, null, 1180),
  ('CN', 'default', '6051', '其他业务收入', '{"en":"Revenue from other operations"}'::jsonb, 'income', false, null, 1190),
  ('CN', 'default', '6101', '公允价值变动损益', '{"en":"Gains and losses from changes in fair value"}'::jsonb, 'income_other', false, null, 1200),
  ('CN', 'default', '6111', '投资收益', '{"en":"Investment income"}'::jsonb, 'income_other', false, null, 1210),
  ('CN', 'default', '6115', '资产处置损益', '{"en":"Gains and losses on disposal of assets"}'::jsonb, 'income_other', false, null, 1220),
  ('CN', 'default', '6117', '其他收益', '{"en":"Other income"}'::jsonb, 'income_other', false, null, 1230),
  ('CN', 'default', '6301', '营业外收入', '{"en":"Non-operating income"}'::jsonb, 'income_other', false, null, 1240),
  ('CN', 'default', '6401', '主营业务成本', '{"en":"Cost of principal operations"}'::jsonb, 'expense_direct_cost', false, null, 1250),
  ('CN', 'default', '6402', '其他业务成本', '{"en":"Cost of other operations"}'::jsonb, 'expense_direct_cost', false, null, 1260),
  ('CN', 'default', '6403', '税金及附加', '{"en":"Taxes and surcharges"}'::jsonb, 'expense', false, null, 1270),
  ('CN', 'default', '6601', '销售费用', '{"en":"Selling expenses"}'::jsonb, 'expense', false, null, 1280),
  ('CN', 'default', '660101', '职工薪酬', '{"en":"Employee benefits"}'::jsonb, 'expense', false, '6601', 1290),
  ('CN', 'default', '660102', '广告费和业务宣传费', '{"en":"Advertising and promotion"}'::jsonb, 'expense', false, '6601', 1300),
  ('CN', 'default', '660103', '运输费', '{"en":"Transport"}'::jsonb, 'expense', false, '6601', 1310),
  ('CN', 'default', '660104', '折旧费', '{"en":"Depreciation"}'::jsonb, 'expense_depreciation', false, '6601', 1320),
  ('CN', 'default', '660199', '其他', '{"en":"Other selling expenses"}'::jsonb, 'expense', false, '6601', 1330),
  ('CN', 'default', '6602', '管理费用', '{"en":"Administrative expenses"}'::jsonb, 'expense', false, null, 1340),
  ('CN', 'default', '660201', '研究费用', '{"en":"Research expenses"}'::jsonb, 'expense', false, '6602', 1350),
  ('CN', 'default', '660202', '无形资产摊销', '{"en":"Amortisation of intangible assets"}'::jsonb, 'expense_depreciation', false, '6602', 1360),
  ('CN', 'default', '660203', '职工薪酬', '{"en":"Employee benefits"}'::jsonb, 'expense', false, '6602', 1370),
  ('CN', 'default', '660204', '办公费', '{"en":"Office expenses"}'::jsonb, 'expense', false, '6602', 1380),
  ('CN', 'default', '660205', '差旅费', '{"en":"Travel expenses"}'::jsonb, 'expense', false, '6602', 1390),
  ('CN', 'default', '660206', '业务招待费', '{"en":"Business entertainment"}'::jsonb, 'expense', false, '6602', 1400),
  ('CN', 'default', '660207', '折旧费', '{"en":"Depreciation"}'::jsonb, 'expense_depreciation', false, '6602', 1410),
  ('CN', 'default', '660208', '租赁费', '{"en":"Rent"}'::jsonb, 'expense', false, '6602', 1420),
  ('CN', 'default', '660209', '中介机构费', '{"en":"Professional fees"}'::jsonb, 'expense', false, '6602', 1430),
  ('CN', 'default', '660299', '其他', '{"en":"Other administrative expenses"}'::jsonb, 'expense', false, '6602', 1450),
  ('CN', 'default', '6603', '财务费用', '{"en":"Finance expenses"}'::jsonb, 'expense', false, null, 1460),
  ('CN', 'default', '660301', '利息费用', '{"en":"Interest expense"}'::jsonb, 'expense', false, '6603', 1470),
  ('CN', 'default', '660302', '利息收入', '{"en":"Interest income"}'::jsonb, 'expense', false, '6603', 1480),
  ('CN', 'default', '660303', '汇兑损益', '{"en":"Exchange gains and losses"}'::jsonb, 'expense', false, '6603', 1490),
  ('CN', 'default', '660304', '手续费', '{"en":"Bank charges"}'::jsonb, 'expense', false, '6603', 1500),
  ('CN', 'default', '660399', '其他', '{"en":"Other finance expenses"}'::jsonb, 'expense', false, '6603', 1510),
  ('CN', 'default', '6701', '资产减值损失', '{"en":"Asset impairment losses"}'::jsonb, 'expense', false, null, 1520),
  ('CN', 'default', '6702', '信用减值损失', '{"en":"Credit impairment losses"}'::jsonb, 'expense', false, null, 1530),
  ('CN', 'default', '6711', '营业外支出', '{"en":"Non-operating expenses"}'::jsonb, 'expense', false, null, 1540),
  ('CN', 'default', '6801', '所得税费用', '{"en":"Income tax expense"}'::jsonb, 'expense', false, null, 1550),
  ('CN', 'default', '680101', '当期所得税费用', '{"en":"Current income tax expense"}'::jsonb, 'expense', false, '6801', 1560),
  ('CN', 'default', '680102', '递延所得税费用', '{"en":"Deferred income tax expense"}'::jsonb, 'expense', false, '6801', 1570)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('CN', 'BNK', '银行存款日记账', '{"en":"Bank deposits journal"}'::jsonb, 'bank', 30),
  ('CN', 'CSH', '现金日记账', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('CN', 'GEN', '转账凭证', '{"en":"Transfer vouchers"}'::jsonb, 'general', 50),
  ('CN', 'OPN', '期初余额', '{"en":"Opening balances"}'::jsonb, 'opening', 60),
  ('CN', 'PUR', '采购日记账', '{"en":"Purchases journal"}'::jsonb, 'purchase', 20),
  ('CN', 'SAL', '销售日记账', '{"en":"Sales journal"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('CN', 'CN-P-1', '取得小规模纳税人1%专用发票（可抵扣）', '{"en":"Special invoice from a small-scale taxpayer at 1% (deductible)"}'::jsonb, '凭增值税专用发票等扣税凭证抵扣的进项税额', 'percent', 1, 'purchase', 'domestic', date '2026-01-01', date '2027-12-31', '中华人民共和国增值税法第十一条 and 财政部 税务总局公告2026年第10号 第三条第（三）项第6点 (the rate or levy rate the supplier charges) and 第十六条 — input tax is deducted on the strength of a VAT deduction voucher (增值税扣税凭证); 增值税法实施条例第十一条 names them, the special VAT invoice (增值税专用发票) first among them, and 第十二条第一项 deducts the tax stated on it. Reported on line 12 (进项税额) of the general-taxpayer return; booked on 应交税费—应交增值税（进项税额）. An ordinary invoice (普通发票) carries no deductible tax and is booked with a non-deductible code instead.', 'S', null, 240, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-13', '购进货物、加工修理修配、有形动产租赁 13%（可抵扣）', '{"en":"Purchase at 13% (deductible)"}'::jsonb, '凭增值税专用发票等扣税凭证抵扣的进项税额', 'percent', 13, 'purchase', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第一项 (the rate or levy rate the supplier charges) and 第十六条 — input tax is deducted on the strength of a VAT deduction voucher (增值税扣税凭证); 增值税法实施条例第十一条 names them, the special VAT invoice (增值税专用发票) first among them, and 第十二条第一项 deducts the tax stated on it. Reported on line 12 (进项税额) of the general-taxpayer return; booked on 应交税费—应交增值税（进项税额）. An ordinary invoice (普通发票) carries no deductible tax and is booked with a non-deductible code instead.', 'S', null, 200, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-13-ND', '购进用于集体福利或个人消费 13%（不得抵扣）', '{"en":"Purchase for collective welfare or personal consumption, 13% (not deductible)"}'::jsonb, '购进并用于集体福利或者个人消费的货物', 'percent', 13, 'purchase', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第二十二条第四项 — the input tax on goods, services, intangible assets and immovable property bought and used for collective welfare or personal consumption may not be deducted. The tax is part of the cost of the line (tax_on_base) and reaches no line of the return.', 'S', null, 260, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-3', '取得小规模纳税人3%专用发票（可抵扣）', '{"en":"Special invoice from a small-scale taxpayer at 3% (deductible)"}'::jsonb, '凭增值税专用发票等扣税凭证抵扣的进项税额', 'percent', 3, 'purchase', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十一条 (the rate or levy rate the supplier charges) and 第十六条 — input tax is deducted on the strength of a VAT deduction voucher (增值税扣税凭证); 增值税法实施条例第十一条 names them, the special VAT invoice (增值税专用发票) first among them, and 第十二条第一项 deducts the tax stated on it. Reported on line 12 (进项税额) of the general-taxpayer return; booked on 应交税费—应交增值税（进项税额）. An ordinary invoice (普通发票) carries no deductible tax and is booked with a non-deductible code instead.', 'S', null, 230, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-6', '购进服务、无形资产 6%（可抵扣）', '{"en":"Purchase of services and intangibles at 6% (deductible)"}'::jsonb, '凭增值税专用发票等扣税凭证抵扣的进项税额', 'percent', 6, 'purchase', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第三项 (the rate or levy rate the supplier charges) and 第十六条 — input tax is deducted on the strength of a VAT deduction voucher (增值税扣税凭证); 增值税法实施条例第十一条 names them, the special VAT invoice (增值税专用发票) first among them, and 第十二条第一项 deducts the tax stated on it. Reported on line 12 (进项税额) of the general-taxpayer return; booked on 应交税费—应交增值税（进项税额）. An ordinary invoice (普通发票) carries no deductible tax and is booked with a non-deductible code instead.', 'S', null, 220, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-6-ND', '购进餐饮、居民日常服务、娱乐服务 6%（不得抵扣）', '{"en":"Catering, everyday and entertainment services, 6% (not deductible)"}'::jsonb, '购进并直接用于消费的餐饮服务、居民日常服务和娱乐服务', 'percent', 6, 'purchase', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第二十二条第五项 — the input tax on catering, everyday residential and entertainment services bought and directly consumed may not be deducted. The tax is part of the cost of the line (tax_on_base) and reaches no line of the return.', 'S', null, 250, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-9', '购进 9% 税率项目（可抵扣）', '{"en":"Purchase at 9% (deductible)"}'::jsonb, '凭增值税专用发票等扣税凭证抵扣的进项税额', 'percent', 9, 'purchase', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第二项 (the rate or levy rate the supplier charges) and 第十六条 — input tax is deducted on the strength of a VAT deduction voucher (增值税扣税凭证); 增值税法实施条例第十一条 names them, the special VAT invoice (增值税专用发票) first among them, and 第十二条第一项 deducts the tax stated on it. Reported on line 12 (进项税额) of the general-taxpayer return; booked on 应交税费—应交增值税（进项税额）. An ordinary invoice (普通发票) carries no deductible tax and is booked with a non-deductible code instead.', 'S', null, 210, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-EXO', '购进免税项目', '{"en":"Exempt purchase"}'::jsonb, '取得免税发票的购进，或从小规模纳税人取得未注明税额的普通发票', 'percent', 0, 'purchase', 'exempt', date '2026-01-01', null, '中华人民共和国增值税法第二十三条、第二十四条 — the supplier''s sale is exempt, or below the small-scale threshold, so the invoice states no tax the buyer could deduct. Reported on no line of the general-taxpayer return.', 'E', null, 280, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-FS-6', '境外单位提供服务 代扣代缴 6%', '{"en":"Service from a foreign supplier, VAT withheld, 6%"}'::jsonb, '境外单位和个人在境内发生应税交易，购买方为扣缴义务人', 'percent', 6, 'purchase', 'foreign_services_received', date '2026-01-01', null, '中华人民共和国增值税法第十五条 — where a foreign entity or individual makes a taxable transaction within China, the buyer is the withholding agent, and withholds the sales amount multiplied by the rate; 增值税法实施条例第十二条第三项 lets the buyer deduct the tax stated on the tax payment certificate (完税凭证) of a service or intangible asset bought from abroad. One posting books the deductible input tax (line 12); the other books the tax withheld on 应交税费—代扣代交增值税, which the withholding agent pays under article 30 paragraph 3 and which reaches no line of the buyer''s own return. The supplier is owed the price net of nothing: the two postings cancel on the document total.', null, null, 270, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-P-NA', '不征收增值税的支出', '{"en":"Expense not subject to VAT"}'::jsonb, '不属于应税交易的支出，如工资、行政事业性收费', 'percent', 0, 'purchase', 'not_subject', date '2026-01-01', null, '中华人民共和国增值税法第六条 — wages, administrative fees and government funds, compensation for expropriation and deposit interest are not taxable transactions. Reported on no line of the return.', 'O', null, 290, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-0-EXP-G', '出口货物 零税率', '{"en":"Export of goods, zero rate"}'::jsonb, '出口货物，适用免、抵、退税办法', 'percent', 0, 'sale', 'export', date '2026-01-01', null, '中华人民共和国增值税法第十条第四项 — 纳税人出口货物，税率为零；国务院另有规定的除外; 增值税法实施条例第八条 defines an exported good as one declared to Customs, physically leaving the country and sold to a foreign entity or individual. Article 33 of the Law and article 47 of 增值税法实施条例 make the zero rate a refund procedure: the exporter declares 退（免）税 to the tax office, computed at the export refund rate the State Council sets per product (出口退税率), by the 免抵退 method for a producer or the 免退 method for a trading company. Reported on line 7 (免、抵、退办法出口销售额) of the general-taxpayer return. The refund itself — its rate per product, the 免抵退 computation of line 15 and the separate refund declaration — is not modelled by this pack; see the README.', 'G', null, 60, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-0-EXP-S', '跨境销售服务、无形资产 零税率', '{"en":"Cross-border services and intangible assets, zero rate"}'::jsonb, '境内单位和个人跨境销售国务院规定范围内的服务、无形资产', 'percent', 0, 'sale', 'export', date '2026-01-01', null, '中华人民共和国增值税法第十条第五项 — cross-border sales of the services and intangible assets within the scope the State Council sets are zero-rated; 增值税法实施条例第九条 lists them — R&D, energy performance contracting, design, film and broadcast production, software, circuit design and testing, information systems, business process management and offshore outsourcing services sold to a foreign entity and wholly consumed abroad; technology transferred to a foreign entity and wholly used abroad; international and space transport and repair services for foreign parties. A general-method taxpayer declares them under the 免抵退 method and reports them on line 7, the column the return''s own instructions reserve for zero-rated sales under that method (line 10, as redefined by 国家税务总局公告2026年第6号, carries only the zero-rated services that are not under it). Which services qualify, and whether a given seller is under 免抵退 or 免税, is not a fact of the ledger: to be reviewed case by case.', 'G', null, 70, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-13-G', '销售货物 13%', '{"en":"Sale of goods, 13%"}'::jsonb, '一般计税方法：销售货物、进口货物以外的13%税率应税交易中的货物部分', 'percent', 13, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第一项 — 纳税人销售货物、加工修理修配服务、有形动产租赁服务，进口货物，除第二项、第四项、第五项规定外，税率为百分之十三. The sale base is reported on line 2 (应税货物销售额) of 增值税及附加税费申报表（一般纳税人适用）, inside line 1, and the output tax on line 11 (销项税额). The same 13% rate applied before 2026 under the repealed 增值税暂行条例 as amended; this code starts on the day the VAT Law took effect (article 38) and carries no earlier period.', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-13-S', '加工修理修配、有形动产租赁 13%', '{"en":"Processing, repair and replacement, leasing of tangible movables, 13%"}'::jsonb, '一般计税方法：加工修理修配服务、有形动产租赁服务', 'percent', 13, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第一项 — processing, repair and replacement services and the leasing of tangible movable property are taxed at 13%. Reported on line 3 (应税劳务销售额) of the general-taxpayer return: 国家税务总局公告2026年第6号 附件1 redefines line 3 as the sales of taxable services (including 加工修理修配服务), intangible assets and immovable property taxed at an applicable rate; output tax on line 11.', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-3-SIMPLE', '简易计税 3%（一般纳税人）', '{"en":"Simplified method 3% (general taxpayer)"}'::jsonb, '一般纳税人按规定选择简易计税方法的应税交易', 'percent', 3, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十一条 — the levy rate of the simplified method is 3%; 财政部 税务总局公告2026年第10号 第三条第（三）项 lists the transactions for which a general taxpayer may elect it (public transport, among others). Reported on line 5 (按简易办法计税销售额) and line 21 (简易计税办法计算的应纳税额) of the general-taxpayer return; booked on 应交税费—简易计税 as 财会〔2016〕22号 requires. Article 22 item 1 of the Law denies the deduction of the input tax attributable to it.', 'S', null, 100, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-bridge', null, null, null, null),
  ('CN', 'CN-S-6', '销售服务、无形资产 6%', '{"en":"Services and intangible assets, 6%"}'::jsonb, '一般计税方法：第十条第一项、第二项、第五项以外的服务和无形资产', 'percent', 6, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第三项 — services and intangible assets not covered by items 1, 2 and 5 of the article are taxed at 6%. Line 3 and line 11 of the general-taxpayer return.', 'S', null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-9-G', '销售货物 9%', '{"en":"Sale of goods, 9%"}'::jsonb, '一般计税方法：农产品、食用植物油、食用盐、自来水、暖气、天然气、图书报纸、饲料化肥农药农机农膜等货物', 'percent', 9, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第二项 — the goods listed in its four sub-items (agricultural products, edible vegetable oil and salt; tap water, heating, gas and the other utilities listed; books, newspapers, magazines, audio-visual and electronic publications; feed, fertiliser, pesticides, agricultural machinery and film) are taxed at 9%. 财政部 税务总局公告2026年第9号 附件1 defines their scope; this pack has not transcribed it. Line 2 and line 11 of the general-taxpayer return.', 'S', null, 30, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-9-S', '交通运输、邮政、基础电信、建筑、不动产 9%', '{"en":"Transport, postal, basic telecom, construction, immovable property, 9%"}'::jsonb, '一般计税方法：交通运输、邮政、基础电信、建筑、不动产租赁服务，销售不动产，转让土地使用权', 'percent', 9, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第十条第二项 — transport, postal, basic telecommunications, construction and immovable-property leasing services, the sale of immovable property and the transfer of land use rights are taxed at 9%. Line 3 (as redefined by 国家税务总局公告2026年第6号) and line 11 of the general-taxpayer return.', 'S', null, 40, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-EXO-G', '免税货物', '{"en":"Exempt goods"}'::jsonb, '免征增值税的货物，如农业生产者销售的自产农产品', 'percent', 0, 'sale', 'exempt', date '2026-01-01', null, '中华人民共和国增值税法第二十四条 — the article lists nine items exempt from VAT, among them (item 1) agricultural products sold by the agricultural producer who grew them and (item 3) antique books; 财政部 税务总局公告2026年第10号 adds time-limited exemptions. Article 22 item 2 denies the deduction of the input tax attributable to an exempt item. Reported on line 9 (免税货物销售额), inside line 8. A seller may waive an exemption (article 27), which is a fact about the seller this code does not record.', 'E', null, 80, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-EXO-S', '免税服务', '{"en":"Exempt services"}'::jsonb, '免征增值税的服务，如技术转让、技术开发及相关技术咨询、技术服务', 'percent', 0, 'sale', 'exempt', date '2026-01-01', null, '中华人民共和国增值税法第二十四条 and 财政部 税务总局公告2026年第10号 第二条第（二）项 — among the services exempt from 1 January 2026 to 31 December 2027, item 2: technology transfer, technology development and the technical consultancy and services related to them, provided they are invoiced together with the transfer or development and the written contract has been recognised by the provincial science and technology or industry authority. Reported on line 10 (免税劳务销售额), inside line 8.', 'E', null, 90, 'vat', true, array['supply_nature', 'buyer_certificate']::tax_condition[], null, false, false, null, 'vat-bridge', null, null, null, null),
  ('CN', 'CN-S-NA', '不征收增值税', '{"en":"Not subject to VAT"}'::jsonb, '不属于应税交易，如存款利息、依法被征收征用取得的补偿', 'percent', 0, 'sale', 'not_subject', date '2026-01-01', null, '中华人民共和国增值税法第六条 — four receipts are not taxable transactions and bear no VAT: wages of an employee, administrative fees and government funds collected, compensation for expropriation, and interest on deposits. Reported on no line of the return.', 'O', null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('CN', 'CN-S-SS-1', '小规模纳税人 减按1%', '{"en":"Small-scale taxpayer, reduced to 1%"}'::jsonb, '小规模纳税人3%征收率的应税交易，减按1%征收（2026年1月1日至2027年12月31日）', 'percent', 1, 'sale', 'domestic', date '2026-01-01', date '2027-12-31', '财政部 税务总局公告2026年第10号 第三条第（三）项第6点 — from 1 January 2026 to 31 December 2027, a small-scale taxpayer''s taxable transactions other than the sale or leasing of immovable property and the transfer of land use rights, taxable at the 3% levy rate, are taxed at 1%; 国家税务总局公告2026年第4号 第四条 requires the invoice to be issued at 1%, unless the seller waives the reduction for all or part of its sales and issues a special VAT invoice at 3%. Same account and same form as CN-S-SS-3.', 'S', null, 130, 'vat', true, array['seller_threshold', 'supply_nature']::tax_condition[], null, false, false, null, 'vat-bridge', null, null, null, null),
  ('CN', 'CN-S-SS-3', '小规模纳税人 3%', '{"en":"Small-scale taxpayer, 3%"}'::jsonb, '小规模纳税人简易计税方法，征收率3%', 'percent', 3, 'sale', 'domestic', date '2026-01-01', null, '中华人民共和国增值税法第八条第二款、第九条、第十一条 — a small-scale taxpayer (annual taxable sales not above 5 million yuan) computes VAT on the simplified method at the 3% levy rate, with no deduction of input tax. Booked on 应交税费—应交增值税, the one detail account 财会〔2016〕22号 gives a small-scale taxpayer. It is declared on 增值税及附加税费申报表（小规模纳税人适用）, a different form from the one this pack models, so the code reports on no box here; see the README. Below the threshold of 财政部 税务总局公告2026年第10号 第一条 (100 000 yuan a month, 300 000 a quarter) the sales are exempt, which is a total over a period and not a fact of one invoice.', 'S', null, 120, 'vat', true, array['seller_threshold']::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('CN-P-1', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-1', 'invoice', 'tax', 100, '22210101', '12', array['12']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-P-1', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-1', 'credit_note', 'tax', 100, '22210101', '12', array['12']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-P-13', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-13', 'invoice', 'tax', 100, '22210101', '12', array['12']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-P-13', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-13', 'credit_note', 'tax', 100, '22210101', '12', array['12']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-P-13-ND', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-13-ND', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('CN-P-13-ND', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-13-ND', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('CN-P-3', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-3', 'invoice', 'tax', 100, '22210101', '12', array['12']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-P-3', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-3', 'credit_note', 'tax', 100, '22210101', '12', array['12']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-P-6', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-6', 'invoice', 'tax', 100, '22210101', '12', array['12']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-P-6', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-6', 'credit_note', 'tax', 100, '22210101', '12', array['12']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-P-6-ND', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-6-ND', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('CN-P-6-ND', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-6-ND', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('CN-P-9', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-9', 'invoice', 'tax', 100, '22210101', '12', array['12']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-P-9', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-9', 'credit_note', 'tax', 100, '22210101', '12', array['12']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-P-EXO', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-EXO', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-FS-6', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-FS-6', 'invoice', 'tax', 100, '22210101', '12', array['12']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-P-FS-6', 'invoice', 'tax', -100, '222110', null, null, 100, null, 30),
    ('CN-P-FS-6', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-FS-6', 'credit_note', 'tax', 100, '22210101', '12', array['12']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-P-FS-6', 'credit_note', 'tax', -100, '222110', null, null, 100, null, 30),
    ('CN-P-NA', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-P-NA', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-0-EXP-G', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-0-EXP-G', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-0-EXP-S', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-0-EXP-S', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-13-G', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-13-G', 'invoice', 'tax', 100, '22210107', '11', array['11']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-S-13-G', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-13-G', 'credit_note', 'tax', 100, '22210107', '11', array['11']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-S-13-S', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-13-S', 'invoice', 'tax', 100, '22210107', '11', array['11']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-S-13-S', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-13-S', 'credit_note', 'tax', 100, '22210107', '11', array['11']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-S-3-SIMPLE', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-3-SIMPLE', 'invoice', 'tax', 100, '222108', '21', array['21']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-S-3-SIMPLE', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-3-SIMPLE', 'credit_note', 'tax', 100, '222108', '21', array['21']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-S-6', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-6', 'invoice', 'tax', 100, '22210107', '11', array['11']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-S-6', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-6', 'credit_note', 'tax', 100, '22210107', '11', array['11']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-S-9-G', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-9-G', 'invoice', 'tax', 100, '22210107', '11', array['11']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-S-9-G', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-9-G', 'credit_note', 'tax', 100, '22210107', '11', array['11']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-S-9-S', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-9-S', 'invoice', 'tax', 100, '22210107', '11', array['11']::text[], 100, 'CN-VAT-GENERAL', 20),
    ('CN-S-9-S', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-9-S', 'credit_note', 'tax', 100, '22210107', '11', array['11']::text[], -100, 'CN-VAT-GENERAL', 20),
    ('CN-S-EXO-G', 'invoice', 'base', 100, null, '9', array['9']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-EXO-G', 'credit_note', 'base', 100, null, '9', array['9']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-EXO-S', 'invoice', 'base', 100, null, '10', array['10']::text[], 100, 'CN-VAT-GENERAL', 10),
    ('CN-S-EXO-S', 'credit_note', 'base', 100, null, '10', array['10']::text[], -100, 'CN-VAT-GENERAL', 10),
    ('CN-S-NA', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-NA', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-SS-1', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-SS-1', 'invoice', 'tax', 100, '222101', null, null, 100, null, 20),
    ('CN-S-SS-1', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-SS-1', 'credit_note', 'tax', 100, '222101', null, null, 100, null, 20),
    ('CN-S-SS-3', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-SS-3', 'invoice', 'tax', 100, '222101', null, null, 100, null, 20),
    ('CN-S-SS-3', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('CN-S-SS-3', 'credit_note', 'tax', 100, '222101', null, null, 100, null, 20)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'CN' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('CN', 'CN-VAT-GENERAL', '增值税及附加税费申报表（一般纳税人适用） — VAT and surcharges return, general taxpayer, main table', array['month', 'quarter']::declaration_period[], null, date '2026-01-01', null, '中华人民共和国增值税法第三十条 — the taxable period is ten days, fifteen days, one month or one quarter, fixed for each taxpayer by the competent tax office according to the amount of tax it owes; 增值税法实施条例第四十三条 limits the quarter to small-scale taxpayers, banks, finance companies, trust companies and credit cooperatives among general taxpayers, and whoever the State Council''s tax and finance authorities add. This pack carries the month and the quarter, and proposes neither: the period is assigned by the tax office, not chosen. The form is the main table of 增值税及附加税费申报表（一般纳税人适用）, issued by 国家税务总局公告2021年第20号 and still in use, with the filling instructions 国家税务总局公告2026年第6号 adjusts for the VAT Law ("增值税纳税人暂使用《增值税及附加税费申报表（一般纳税人适用）》及其附列资料…有关栏次按本公告调整后的填报要求填写"). Its four schedules and the surcharge lines 39 to 41 are not modelled; see the README. Amounts are in yuan to the fen ("金额单位：元（列至角分）"), so the form carries no rounding of its own.', true,'day_of_month_after_period'::filing_deadline_rule, 15, null, '中华人民共和国增值税法第三十条第二款 — a taxpayer on a one-month or one-quarter period files and pays within fifteen days of its end ("自期满之日起十五日内申报纳税"). A deadline falling on a public holiday is moved by the State Taxation Administration''s yearly filing calendar, which this rule does not know.', 'vat-law', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('CN', 'CN-VAT-GENERAL', '2', 'base', '其中：应税货物销售额', '{"en":"of which: sales of taxable goods"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第2栏 — the sales of taxable goods at an applicable rate, a part of line 1.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '3', 'base', '应税劳务销售额', '{"en":"sales of taxable services"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第3栏 — as redefined by 国家税务总局公告2026年第6号 附件1: the sales of taxable services (including processing, repair and replacement services), intangible assets and immovable property at an applicable rate, a part of line 1.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '1', 'total', '（一）按适用税率计税销售额', '{"en":"(1) Sales taxed at an applicable rate"}'::jsonb, 30, 5, array['2', '3']::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第1栏 — the sales taxed at an applicable rate. Line 1 is lines 2 and 3 plus line 4 (纳税检查调整的销售额, adjustments found by a tax inspection), which is not a fact of the ledger and is not declared here.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '5', 'base', '（二）按简易办法计税销售额', '{"en":"(2) Sales taxed on the simplified method"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第5栏 — the sales taxed on the simplified method (line 6, the inspection adjustment inside it, is not declared).', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '7', 'base', '（三）免、抵、退办法出口销售额', '{"en":"(3) Export sales under the exemption-credit-refund method"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第7栏 — the export sales declared under the exemption-credit-refund method.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '9', 'base', '其中：免税货物销售额', '{"en":"of which: exempt sales of goods"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第9栏 — the sales of exempt goods, a part of line 8.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '10', 'base', '免税劳务销售额', '{"en":"exempt sales of services"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第10栏 — as redefined by 国家税务总局公告2026年第6号 附件1: the exempt and zero-rated sales of services, intangible assets and immovable property, excluding zero-rated sales under the exemption-credit-refund method.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '8', 'total', '（四）免税销售额', '{"en":"(4) Exempt sales"}'::jsonb, 80, 55, array['9', '10']::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第8栏 — lines 9 and 10, the exempt sales.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '11', 'tax', '销项税额', '{"en":"Output tax"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第11栏 — the output tax of the period.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '12', 'tax', '进项税额', '{"en":"Input tax"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第12栏 — the input tax of the period, from the deduction vouchers the buyer has confirmed for deduction.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '17', 'total', '应抵扣税额合计', '{"en":"Total deductible tax"}'::jsonb, 110, null, array['12']::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第17栏 — printed as 12+13-14-15+16. Line 13 (上期留抵税额, the credit carried in from the previous period) is what the previous return came to and not a fact this period''s ledger holds; line 14 (进项税额转出), line 15 (免、抵、退应退税额) and line 16 (纳税检查应补缴税额) come from procedures this pack does not model. This pack therefore declares line 17 as line 12 alone; see the README.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '19', 'total', '应纳税额', '{"en":"Tax payable"}'::jsonb, 120, null, array['11']::text[], array['17']::text[], null, null, true, false, null, '增值税及附加税费申报表（一般纳税人适用），第19栏 — printed as 11-18. Line 18 is 17 where 17 is below 11 and 11 otherwise, so 11-18 is 11-17 floored at zero, which is how it is computed here.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '18', 'total', '实际抵扣税额', '{"en":"Tax actually deducted"}'::jsonb, 130, 115, array['11']::text[], array['19']::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第18栏 — printed as "如17<11，则为17，否则为11", the smaller of lines 17 and 11. The format has no minimum; 11 less line 19 is that minimum, whichever of the two is smaller.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '20', 'total', '期末留抵税额', '{"en":"Credit carried forward at the end of the period"}'::jsonb, 140, null, array['17']::text[], array['11']::text[], null, null, true, false, null, '增值税及附加税费申报表（一般纳税人适用），第20栏 — printed as 17-18: the input tax left over, carried to the next period''s line 13 (or refunded under article 21 of 中华人民共和国增值税法). Computed as 17-11 floored at zero, which is the same figure.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '21', 'tax', '简易计税办法计算的应纳税额', '{"en":"Tax payable on the simplified method"}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第21栏 — the tax computed on the simplified method.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '24', 'total', '应纳税额合计', '{"en":"Total tax payable"}'::jsonb, 160, null, array['19', '21']::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第24栏 — printed as 19+21-23; line 23 (应纳税额减征额, reductions such as the tax-control equipment credit) is not modelled.', 'form-general'),
  ('CN', 'CN-VAT-GENERAL', '34', 'total', '本期应补(退)税额', '{"en":"Tax to pay (refund) this period"}'::jsonb, 170, null, array['24']::text[], '{}'::text[], null, null, false, false, null, '增值税及附加税费申报表（一般纳税人适用），第34栏 — printed as 24-28-29, the tax to pay this period net of the instalments prepaid during it (line 28, 分次预缴税额) and of the tax prepaid on special export payment books (line 29). Neither is booked by a tax code of this pack, so line 34 comes to line 24.', 'form-general')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('CN-ASBE-BS', 'CN', 'default', '资产负债表（会企01表）— Balance sheet', 'balance_sheet', '企业会计准则', date '1970-01-01', null, '财政部关于修订印发2019年度一般企业财务报表格式的通知（财会〔2019〕6号）附件2 — the balance sheet 会企01表 of a non-financial enterprise that applies the new financial instruments, revenue and leases standards. The notice itself lets an enterprise leave out the items it has no business for ("企业对不存在相应业务的报表项目可结合本企业的实际情况进行必要删减"); this statement leaves out the items this chart carries no account for — 衍生金融资产, 应收款项融资, 合同资产, 持有待售资产, 一年内到期的非流动资产, 债权投资, 其他债权投资, 其他权益工具投资, 其他非流动金融资产, 油气资产, 使用权资产, 其他非流动资产 and their liability and equity counterparts (衍生金融负债, 合同负债, 持有待售负债, 一年内到期的非流动负债, 租赁负债, 其他非流动负债, 其他权益工具, 其他综合收益, 专项储备). Line codes are this pack''s own: the form numbers no line.', 'fs-format'),
  ('CN-ASBE-IS', 'CN', 'default', '利润表（会企02表）— Income statement', 'income_statement', '企业会计准则', date '1970-01-01', null, '财会〔2019〕6号 附件2 — the income statement 会企02表, down to 四、净利润. The 其中 lines under 财务费用 (利息费用, 利息收入) and 投资收益, the split of net profit between continuing and discontinued operations, other comprehensive income (五), total comprehensive income (六) and earnings per share (七) are not carried: this chart has no account for other comprehensive income, and the 其中 lines restate a part of a line already printed.', 'fs-format')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('CN-ASBE-BS', 'A01', null, '货币资金', '{"en":"Cash and cash equivalents"}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A02', null, '交易性金融资产', '{"en":"Financial assets held for trading"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A04', null, '应收票据', '{"en":"Notes receivable"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A05', null, '应收账款', '{"en":"Accounts receivable"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, note 3 — the debit balance of 应收账款 less its allowance in 坏账准备; note 16 of the same attachment reads 应付账款 and 预付账款 from the credit and debit balances of their detail accounts, and the same reading is applied here to 应收账款 and 预收账款. 坏账准备 is carried against this line alone: an allowance booked against notes or other receivables belongs on those lines, and a company that books one should split the account.', null),
  ('CN-ASBE-BS', 'A07', null, '预付款项', '{"en":"Prepayments"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2 — 预付款项 takes the debit balances of 预付账款 and of 应付账款.', null),
  ('CN-ASBE-BS', 'A08', null, '其他应收款', '{"en":"Other receivables"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, note 5 — 应收利息, 应收股利 and 其他应收款 together.', null),
  ('CN-ASBE-BS', 'A09', null, '存货', '{"en":"Inventories"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, 'The inventory accounts 1401 to 1471 of the 应用指南 appendix, less 存货跌价准备, and the production-cost accounts 生产成本, 制造费用 and 劳务成本 whose debit balance is work in progress.', null),
  ('CN-ASBE-BS', 'A13', null, '其他流动资产', '{"en":"Other current assets"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2016〕22号 — the debit balances of 应交增值税, 未交增值税, 待抵扣进项税额, 待认证进项税额, 增值税留抵税额 and the other detail accounts of 应交税费 are presented under 其他流动资产 ("期末借方余额应根据情况，在资产负债表中的''其他流动资产''或''其他非流动资产''项目列示").', null),
  ('CN-ASBE-BS', 'A14', null, '流动资产合计', '{"en":"Total current assets"}'::jsonb, 90, 1, true, array['A01', 'A02', 'A04', 'A05', 'A07', 'A08', 'A09', 'A13']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A21', null, '长期应收款', '{"en":"Long-term receivables"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A22', null, '长期股权投资', '{"en":"Long-term equity investments"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A23', null, '投资性房地产', '{"en":"Investment property"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A24', null, '固定资产', '{"en":"Fixed assets"}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, note 10 — 固定资产 less 累计折旧 and 固定资产减值准备, plus 固定资产清理.', null),
  ('CN-ASBE-BS', 'A25', null, '在建工程', '{"en":"Construction in progress"}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, note 11 — 在建工程 and 工程物资.', null),
  ('CN-ASBE-BS', 'A26', null, '生产性生物资产', '{"en":"Productive biological assets"}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A27', null, '无形资产', '{"en":"Intangible assets"}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A28', null, '开发支出', '{"en":"Development expenditure"}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, 'The capitalised part of 研发支出; the expensed part is closed to 管理费用 each period and never remains on this account.', null),
  ('CN-ASBE-BS', 'A29', null, '商誉', '{"en":"Goodwill"}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A30', null, '长期待摊费用', '{"en":"Long-term deferred expenses"}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A31', null, '递延所得税资产', '{"en":"Deferred tax assets"}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A39', null, '非流动资产合计', '{"en":"Total non-current assets"}'::jsonb, 210, 1, true, array['A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'A40', null, '资产总计', '{"en":"Total assets"}'::jsonb, 220, 1, true, array['A14', 'A39']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L01', null, '短期借款', '{"en":"Short-term borrowings"}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L02', null, '交易性金融负债', '{"en":"Financial liabilities held for trading"}'::jsonb, 310, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L04', null, '应付票据', '{"en":"Notes payable"}'::jsonb, 320, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L05', null, '应付账款', '{"en":"Accounts payable"}'::jsonb, 330, -1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, note 16 — the credit balances of 应付账款 and of 预付账款.', null),
  ('CN-ASBE-BS', 'L06', null, '预收款项', '{"en":"Advances from customers"}'::jsonb, 340, -1, false, '{}'::text[], '{}'::text[], null, 'The credit balances of 预收账款 and of 应收账款. A company under the 2017 revenue standard presents what it has been paid ahead of performance as 合同负债, a line this chart carries no account for.', null),
  ('CN-ASBE-BS', 'L08', null, '应付职工薪酬', '{"en":"Employee benefits payable"}'::jsonb, 350, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L09', null, '应交税费', '{"en":"Taxes payable"}'::jsonb, 360, -1, false, '{}'::text[], '{}'::text[], null, '财会〔2016〕22号 — the credit balances of 未交增值税, 简易计税, 转让金融商品应交增值税, 代扣代交增值税 and of the other taxes payable are presented under 应交税费; 待转销项税额 is presented under 其他流动负债 instead, and the debit balances under 其他流动资产.', null),
  ('CN-ASBE-BS', 'L10', null, '其他应付款', '{"en":"Other payables"}'::jsonb, 370, -1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, note 17 — 应付利息, 应付股利 and 其他应付款 together.', null),
  ('CN-ASBE-BS', 'L13', null, '其他流动负债', '{"en":"Other current liabilities"}'::jsonb, 380, -1, false, '{}'::text[], '{}'::text[], null, '财会〔2016〕22号 — the credit balance of 应交税费—待转销项税额 is presented under 其他流动负债.', null),
  ('CN-ASBE-BS', 'L14', null, '流动负债合计', '{"en":"Total current liabilities"}'::jsonb, 390, 1, true, array['L01', 'L02', 'L04', 'L05', 'L06', 'L08', 'L09', 'L10', 'L13']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L21', null, '长期借款', '{"en":"Long-term borrowings"}'::jsonb, 400, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L22', null, '应付债券', '{"en":"Bonds payable"}'::jsonb, 410, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L24', null, '长期应付款', '{"en":"Long-term payables"}'::jsonb, 420, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L25', null, '预计负债', '{"en":"Provisions"}'::jsonb, 430, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L26', null, '递延收益', '{"en":"Deferred income"}'::jsonb, 440, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L27', null, '递延所得税负债', '{"en":"Deferred tax liabilities"}'::jsonb, 450, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L29', null, '非流动负债合计', '{"en":"Total non-current liabilities"}'::jsonb, 460, 1, true, array['L21', 'L22', 'L24', 'L25', 'L26', 'L27']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'L30', null, '负债合计', '{"en":"Total liabilities"}'::jsonb, 470, 1, true, array['L14', 'L29']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'E01', null, '实收资本（或股本）', '{"en":"Paid-in capital (or share capital)"}'::jsonb, 500, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'E03', null, '资本公积', '{"en":"Capital reserve"}'::jsonb, 510, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'E04', null, '减：库存股', '{"en":"Less: treasury shares"}'::jsonb, 520, 1, false, '{}'::text[], '{}'::text[], null, 'Printed as a positive figure under 减：, and subtracted in the total of equity.', null),
  ('CN-ASBE-BS', 'E07', null, '盈余公积', '{"en":"Surplus reserve"}'::jsonb, 530, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-BS', 'E08', null, '未分配利润', '{"en":"Undistributed profits"}'::jsonb, 540, -1, false, '{}'::text[], '{}'::text[], null, '利润分配 and, until the year is closed into it, 本年利润. The income and expense accounts of an open year reach this line only once close_fiscal_year() has carried them to 本年利润.', null),
  ('CN-ASBE-BS', 'E09', null, '所有者权益（或股东权益）合计', '{"en":"Total owners'' (or shareholders'') equity"}'::jsonb, 550, 1, true, array['E01', 'E03', 'E07', 'E08']::text[], array['E04']::text[], null, null, null),
  ('CN-ASBE-BS', 'E10', null, '负债和所有者权益（或股东权益）总计', '{"en":"Total liabilities and owners'' (or shareholders'') equity"}'::jsonb, 560, 1, true, array['L30', 'E09']::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R01', null, '一、营业收入', '{"en":"1. Operating revenue"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R02', null, '减：营业成本', '{"en":"Less: operating costs"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R03', null, '税金及附加', '{"en":"Taxes and surcharges"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2016〕22号 — consumption tax, urban maintenance and construction tax, resource tax, the education surcharges, property tax, land use tax, vehicle and vessel tax and stamp tax.', null),
  ('CN-ASBE-IS', 'R04', null, '销售费用', '{"en":"Selling expenses"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R05', null, '管理费用', '{"en":"Administrative expenses"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, '管理费用 less its 研究费用 and 无形资产摊销 details, which 财会〔2019〕6号 presents under 研发费用.', null),
  ('CN-ASBE-IS', 'R06', null, '研发费用', '{"en":"Research and development expenses"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, '财会〔2019〕6号 附件2, 利润表 note 1 — the 研究费用 and 无形资产摊销 details of 管理费用. The note reads the amortisation of self-developed intangible assets only; a company amortising a purchased one should book it on another detail of 管理费用.', null),
  ('CN-ASBE-IS', 'R07', null, '财务费用', '{"en":"Finance expenses"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R08', null, '加：其他收益', '{"en":"Add: other income"}'::jsonb, 80, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R09', null, '投资收益（损失以“-”号填列）', '{"en":"Investment income (loss shown with \"-\")"}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R10', null, '公允价值变动收益（损失以“-”号填列）', '{"en":"Gains from changes in fair value (loss shown with \"-\")"}'::jsonb, 100, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R11', null, '信用减值损失（损失以“-”号填列）', '{"en":"Credit impairment losses (loss shown with \"-\")"}'::jsonb, 110, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R12', null, '资产减值损失（损失以“-”号填列）', '{"en":"Asset impairment losses (loss shown with \"-\")"}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R13', null, '资产处置收益（损失以“-”号填列）', '{"en":"Gains on disposal of assets (loss shown with \"-\")"}'::jsonb, 130, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R20', null, '二、营业利润（亏损以“-”号填列）', '{"en":"2. Operating profit (loss shown with \"-\")"}'::jsonb, 140, 1, true, array['R01', 'R08', 'R09', 'R10', 'R11', 'R12', 'R13']::text[], array['R02', 'R03', 'R04', 'R05', 'R06', 'R07']::text[], null, null, null),
  ('CN-ASBE-IS', 'R21', null, '加：营业外收入', '{"en":"Add: non-operating income"}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R22', null, '减：营业外支出', '{"en":"Less: non-operating expenses"}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R30', null, '三、利润总额（亏损总额以“-”号填列）', '{"en":"3. Total profit (loss shown with \"-\")"}'::jsonb, 170, 1, true, array['R20', 'R21']::text[], array['R22']::text[], null, null, null),
  ('CN-ASBE-IS', 'R31', null, '减：所得税费用', '{"en":"Less: income tax expense"}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CN-ASBE-IS', 'R40', null, '四、净利润（净亏损以“-”号填列）', '{"en":"4. Net profit (net loss shown with \"-\")"}'::jsonb, 190, 1, true, array['R30']::text[], array['R31']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('CN-ASBE-BS', 'A01', 10, 'code_prefix', '1001', null, null, 'any'),
    ('CN-ASBE-BS', 'A01', 20, 'code_prefix', '1002', null, null, 'any'),
    ('CN-ASBE-BS', 'A01', 30, 'code_prefix', '1012', null, null, 'any'),
    ('CN-ASBE-BS', 'A02', 10, 'code_prefix', '1101', null, null, 'any'),
    ('CN-ASBE-BS', 'A04', 10, 'code_prefix', '1121', null, null, 'any'),
    ('CN-ASBE-BS', 'A05', 10, 'code_prefix', '1122', null, null, 'debit'),
    ('CN-ASBE-BS', 'A05', 20, 'code_prefix', '2203', null, null, 'debit'),
    ('CN-ASBE-BS', 'A05', 30, 'code_prefix', '1231', null, null, 'any'),
    ('CN-ASBE-BS', 'A07', 10, 'code_prefix', '1123', null, null, 'debit'),
    ('CN-ASBE-BS', 'A07', 20, 'code_prefix', '2202', null, null, 'debit'),
    ('CN-ASBE-BS', 'A08', 10, 'code_prefix', '1131', null, null, 'any'),
    ('CN-ASBE-BS', 'A08', 20, 'code_prefix', '1132', null, null, 'any'),
    ('CN-ASBE-BS', 'A08', 30, 'code_prefix', '1221', null, null, 'any'),
    ('CN-ASBE-BS', 'A09', 10, 'code_prefix', '14', null, null, 'any'),
    ('CN-ASBE-BS', 'A09', 20, 'code_prefix', '5001', null, null, 'any'),
    ('CN-ASBE-BS', 'A09', 30, 'code_prefix', '5101', null, null, 'any'),
    ('CN-ASBE-BS', 'A09', 40, 'code_prefix', '5201', null, null, 'any'),
    ('CN-ASBE-BS', 'A13', 10, 'code_prefix', '1901', null, null, 'any'),
    ('CN-ASBE-BS', 'A13', 20, 'code_prefix', '2221', null, null, 'debit'),
    ('CN-ASBE-BS', 'A21', 10, 'code_prefix', '1531', null, null, 'any'),
    ('CN-ASBE-BS', 'A21', 20, 'code_prefix', '1532', null, null, 'any'),
    ('CN-ASBE-BS', 'A22', 10, 'code_prefix', '1511', null, null, 'any'),
    ('CN-ASBE-BS', 'A22', 20, 'code_prefix', '1512', null, null, 'any'),
    ('CN-ASBE-BS', 'A23', 10, 'code_prefix', '1521', null, null, 'any'),
    ('CN-ASBE-BS', 'A24', 10, 'code_prefix', '1601', null, null, 'any'),
    ('CN-ASBE-BS', 'A24', 20, 'code_prefix', '1602', null, null, 'any'),
    ('CN-ASBE-BS', 'A24', 30, 'code_prefix', '1603', null, null, 'any'),
    ('CN-ASBE-BS', 'A24', 40, 'code_prefix', '1606', null, null, 'any'),
    ('CN-ASBE-BS', 'A25', 10, 'code_prefix', '1604', null, null, 'any'),
    ('CN-ASBE-BS', 'A25', 20, 'code_prefix', '1605', null, null, 'any'),
    ('CN-ASBE-BS', 'A26', 10, 'code_prefix', '1621', null, null, 'any'),
    ('CN-ASBE-BS', 'A26', 20, 'code_prefix', '1622', null, null, 'any'),
    ('CN-ASBE-BS', 'A27', 10, 'code_prefix', '1701', null, null, 'any'),
    ('CN-ASBE-BS', 'A27', 20, 'code_prefix', '1702', null, null, 'any'),
    ('CN-ASBE-BS', 'A27', 30, 'code_prefix', '1703', null, null, 'any'),
    ('CN-ASBE-BS', 'A28', 10, 'code_prefix', '5301', null, null, 'any'),
    ('CN-ASBE-BS', 'A29', 10, 'code_prefix', '1711', null, null, 'any'),
    ('CN-ASBE-BS', 'A30', 10, 'code_prefix', '1801', null, null, 'any'),
    ('CN-ASBE-BS', 'A31', 10, 'code_prefix', '1811', null, null, 'any'),
    ('CN-ASBE-BS', 'L01', 10, 'code_prefix', '2001', null, null, 'any'),
    ('CN-ASBE-BS', 'L02', 10, 'code_prefix', '2101', null, null, 'any'),
    ('CN-ASBE-BS', 'L04', 10, 'code_prefix', '2201', null, null, 'any'),
    ('CN-ASBE-BS', 'L05', 10, 'code_prefix', '2202', null, null, 'credit'),
    ('CN-ASBE-BS', 'L05', 20, 'code_prefix', '1123', null, null, 'credit'),
    ('CN-ASBE-BS', 'L06', 10, 'code_prefix', '2203', null, null, 'credit'),
    ('CN-ASBE-BS', 'L06', 20, 'code_prefix', '1122', null, null, 'credit'),
    ('CN-ASBE-BS', 'L08', 10, 'code_prefix', '2211', null, null, 'any'),
    ('CN-ASBE-BS', 'L09', 10, 'code_prefix', '222101', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 20, 'code_prefix', '222102', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 30, 'code_prefix', '222103', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 40, 'code_prefix', '222104', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 50, 'code_prefix', '222105', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 60, 'code_prefix', '222107', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 70, 'code_prefix', '222108', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 80, 'code_prefix', '222109', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 90, 'code_prefix', '222110', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 100, 'code_prefix', '222111', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 110, 'code_prefix', '222112', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 120, 'code_prefix', '222113', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 130, 'code_prefix', '222114', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 140, 'code_prefix', '222115', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 150, 'code_prefix', '222116', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 160, 'code_prefix', '222117', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 170, 'code_prefix', '222118', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 180, 'code_prefix', '222119', null, null, 'credit'),
    ('CN-ASBE-BS', 'L09', 190, 'code_prefix', '222120', null, null, 'credit'),
    ('CN-ASBE-BS', 'L10', 10, 'code_prefix', '2231', null, null, 'any'),
    ('CN-ASBE-BS', 'L10', 20, 'code_prefix', '2232', null, null, 'any'),
    ('CN-ASBE-BS', 'L10', 30, 'code_prefix', '2241', null, null, 'any'),
    ('CN-ASBE-BS', 'L13', 10, 'code_prefix', '222106', null, null, 'credit'),
    ('CN-ASBE-BS', 'L21', 10, 'code_prefix', '2501', null, null, 'any'),
    ('CN-ASBE-BS', 'L22', 10, 'code_prefix', '2502', null, null, 'any'),
    ('CN-ASBE-BS', 'L24', 10, 'code_prefix', '2701', null, null, 'any'),
    ('CN-ASBE-BS', 'L24', 20, 'code_prefix', '2702', null, null, 'any'),
    ('CN-ASBE-BS', 'L24', 30, 'code_prefix', '2711', null, null, 'any'),
    ('CN-ASBE-BS', 'L25', 10, 'code_prefix', '2801', null, null, 'any'),
    ('CN-ASBE-BS', 'L26', 10, 'code_prefix', '2401', null, null, 'any'),
    ('CN-ASBE-BS', 'L27', 10, 'code_prefix', '2901', null, null, 'any'),
    ('CN-ASBE-BS', 'E01', 10, 'code_prefix', '4001', null, null, 'any'),
    ('CN-ASBE-BS', 'E03', 10, 'code_prefix', '4002', null, null, 'any'),
    ('CN-ASBE-BS', 'E04', 10, 'code_prefix', '4201', null, null, 'any'),
    ('CN-ASBE-BS', 'E07', 10, 'code_prefix', '4101', null, null, 'any'),
    ('CN-ASBE-BS', 'E08', 10, 'code_prefix', '4103', null, null, 'any'),
    ('CN-ASBE-BS', 'E08', 20, 'code_prefix', '4104', null, null, 'any'),
    ('CN-ASBE-IS', 'R01', 10, 'code_prefix', '6001', null, null, 'any'),
    ('CN-ASBE-IS', 'R01', 20, 'code_prefix', '6051', null, null, 'any'),
    ('CN-ASBE-IS', 'R02', 10, 'code_prefix', '6401', null, null, 'any'),
    ('CN-ASBE-IS', 'R02', 20, 'code_prefix', '6402', null, null, 'any'),
    ('CN-ASBE-IS', 'R03', 10, 'code_prefix', '6403', null, null, 'any'),
    ('CN-ASBE-IS', 'R04', 10, 'code_prefix', '6601', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 10, 'code_prefix', '660203', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 20, 'code_prefix', '660204', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 30, 'code_prefix', '660205', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 40, 'code_prefix', '660206', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 50, 'code_prefix', '660207', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 60, 'code_prefix', '660208', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 70, 'code_prefix', '660209', null, null, 'any'),
    ('CN-ASBE-IS', 'R05', 80, 'code_prefix', '660299', null, null, 'any'),
    ('CN-ASBE-IS', 'R06', 10, 'code_prefix', '660201', null, null, 'any'),
    ('CN-ASBE-IS', 'R06', 20, 'code_prefix', '660202', null, null, 'any'),
    ('CN-ASBE-IS', 'R07', 10, 'code_prefix', '6603', null, null, 'any'),
    ('CN-ASBE-IS', 'R08', 10, 'code_prefix', '6117', null, null, 'any'),
    ('CN-ASBE-IS', 'R09', 10, 'code_prefix', '6111', null, null, 'any'),
    ('CN-ASBE-IS', 'R10', 10, 'code_prefix', '6101', null, null, 'any'),
    ('CN-ASBE-IS', 'R11', 10, 'code_prefix', '6702', null, null, 'any'),
    ('CN-ASBE-IS', 'R12', 10, 'code_prefix', '6701', null, null, 'any'),
    ('CN-ASBE-IS', 'R13', 10, 'code_prefix', '6115', null, null, 'any'),
    ('CN-ASBE-IS', 'R21', 10, 'code_prefix', '6301', null, null, 'any'),
    ('CN-ASBE-IS', 'R22', 10, 'code_prefix', '6711', null, null, 'any'),
    ('CN-ASBE-IS', 'R31', 10, 'code_prefix', '6801', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('CN', '中国', '{"en":"China"}'::jsonb, array['zh', 'en']::text[], 'CNY', '1122', '2202', '2241', '660399', '410406', '6001', '1405', '1002', '1001', 'SAL', 'PUR', 'GEN', 'zh', 'result_accounts', '4103', '4103', '410406', 'OPN', 'half_up', default, '660303', '660303', '6115', '6115', null, null, '222102', '222102', null, null)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}/{YYYY}/{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = '国家税务总局公告2024年第11号 第四条 — the number of a fully digitalised invoice is twenty digits, assigned nationwide by the tax authority''s platform ("号码全国统一赋予"): two for the year, two for the provincial tax bureau, one for the issuing channel and fifteen of sequence. The seller does not choose it and Ekwo does not draw it; the number above is the internal reference of the document in the books, and the invoice number the platform returns is a fact to record beside it. See the README.',
  numbering_source_key          = 'einvoice-2024-11',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'earliest_of_delivery_or_payment',
  tax_point_legal_reference     = '中华人民共和国增值税法第二十八条第一款第一项 — the VAT obligation arises on the day the sale proceeds are received or the right to claim them is obtained ("收讫销售款项或者取得销售款项索取凭据的当日"), or on the day the invoice is issued where it is issued first ("先开具发票的，为开具发票的当日"). The first two branches are the earliest of a payment and of the right to payment, which ordinarily arises with the supply; the third, an invoice issued before either, is not a word of this vocabulary and makes the tax due on the invoice date. 增值税法实施条例第四十一条 moves an export to the day of the customs declaration where it comes first.',
  tax_point_source_key          = 'vat-law',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = '国家税务总局公告2024年第11号 第八条 — once issued, a digital invoice is corrected, for a return, an error, an interrupted service or a price allowance, by a red-letter invoice (红字数电发票) and never by editing it; 增值税法实施条例 also bars reducing output tax or sales for a special invoice that has not been voided or reversed in the prescribed way. A posted document is therefore undone by a credit note.',
  posted_edit_policy_source_key = 'einvoice-2024-11',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'No statute obliges a Chinese business to exchange a structured invoice under EN 16931 or a Peppol profile with its trading partner: there is no Peppol Authority for China, and none of peppol-bis-3, factur-x-en16931, xrechnung or a PINT applies. This is a null answer to a European-shaped question and not a statement that China has no electronic invoicing — the opposite is true. 中华人民共和国增值税法第三十四条 requires invoices to be issued according to law and gives the electronic invoice the paper one''s legal force; 国家税务总局公告2024年第11号 generalised the fully digitalised invoice (数电发票) from 1 December 2024: issued on the tax authority''s own platform, numbered by it, capped by a monthly invoicing limit the authority grants, delivered to the buyer''s tax digital account, and confirmed there by the buyer before its tax can be deducted. That is a real-time clearance model the pack format cannot express; see the README and docs/international.md, "From China".',
  einvoice_source_key           = 'einvoice-2024-11',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'CN';
