-- Ekwo OS — Moldova: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/md at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build md`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Codul fiscal al Republicii Moldova nr. 1163-XIII din 24 aprilie 1997, Titlul III — Taxa pe valoarea adăugată, formă consolidată (Parlamentul Republicii Moldova — Serviciul Fiscal de Stat)
--     https://www.legis.md/cautare/getResults?doc_id=79111&lang=ro
--   Baza generalizată a practicii fiscale — cotele TVA aplicabile conform art. 96 din Codul fiscal (Serviciul Fiscal de Stat)
--     https://sfs.md/ro/intrebare-baza-de-date-generalizare/9
--   Începând cu 31 decembrie 2023, se va aplica cota TVA de 8% pentru domeniul HORECA (Serviciul Fiscal de Stat)
--     https://sfs.md/ro/stiri/incepand-cu-31-decembrie-2023-se-va-aplica-cota-tva-de-8-pentru-domeniul-horeca
--   Ordinul Inspectoratului Fiscal Principal de Stat nr. 1164 din 25.10.2012 privind aprobarea formularului Declarației privind TVA (forma TVA12) și a Modului de completare a acesteia (Inspectoratul Fiscal Principal de Stat / Serviciul Fiscal de Stat)
--     https://www.legis.md/cautare/getResults?lang=ro&doc_id=126104
--   Comunicat privind utilizarea obligatorie în cadrul achizițiilor publice a serviciului electronic „e-Factura” — art. 117 alin. (12) din Codul fiscal, Legea nr. 102/2020 (Agenția Achiziții Publice)
--     https://tender.gov.md/ro/content/comunicat-privind-utilizarea-obligatorie-%C3%AEn-cadrul-achizi%C8%9Biilor-publice-serviciului-1
--   SIA „Declarație electronică” — portalul de depunere a declarațiilor fiscale, inclusiv Declarația privind TVA (forma TVA12) și facturile fiscale electronice ale sistemului e-Factura (Serviciul Fiscal de Stat)
--     https://raportare.gov.md/reports-sfs
--   Ordinul Ministerului Finanțelor nr. 119 din 06.08.2013 privind aprobarea Planului general de conturi contabile (Ministerul Finanțelor al Republicii Moldova)
--     https://mf.gov.md/sites/default/files/legislatie/Planul%20general%20de%20conturi%20contabile.pdf
--   Legea contabilității și raportării financiare nr. 287 din 15.12.2017 (Parlamentul Republicii Moldova — Ministerul Finanțelor)
--     https://mf.gov.md/ro/content/legea-contabilit%C4%83%C8%9Bii-%C8%99i-raport%C4%83rii-financiare-nr-287
--   Standardul Național de Contabilitate „Prezentarea situațiilor financiare” (S.N.C. 5), aprobat prin ordinul Ministerului Finanțelor nr. 118 din 29.07.2013, modificat prin ordinul nr. 194 din 2018 — formularele Bilanțul contabil (Forma nr. 1) și Raportul de profit și pierderi (Forma nr. 2) (Ministerul Finanțelor al Republicii Moldova)
--     https://old.mf.gov.md/files/files/Standardele%20Na%C8%9Bionale%20de%20Contabilitate.pdf
--   Codul civil al Republicii Moldova nr. 1107/2002, art. 942 — dobânda de întârziere în executarea obligațiilor pecuniare (Parlamentul Republicii Moldova)
--     https://www.legis.md/cautare/getResults?doc_id=112573&lang=ro
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('MD', 'Moldova', '0.1.0', date '2026-09-26', '20260923110000', 'community', null, null, '8a6e9135ae682ba51df3c13df3ce3ab7809315b1bfc462e0c5bb4c6e951b5fb9', '[{"key":"codul-fiscal","title":"Codul fiscal al Republicii Moldova nr. 1163-XIII din 24 aprilie 1997, Titlul III — Taxa pe valoarea adăugată, formă consolidată","publisher":"Parlamentul Republicii Moldova — Serviciul Fiscal de Stat","url":"https://www.legis.md/cautare/getResults?doc_id=79111&lang=ro","consulted_on":"2026-09-26","kind":"law"},{"key":"sfs-cotele-tva","title":"Baza generalizată a practicii fiscale — cotele TVA aplicabile conform art. 96 din Codul fiscal","publisher":"Serviciul Fiscal de Stat","url":"https://sfs.md/ro/intrebare-baza-de-date-generalizare/9","consulted_on":"2026-09-26","kind":"guidance"},{"key":"sfs-horeca-8","title":"Începând cu 31 decembrie 2023, se va aplica cota TVA de 8% pentru domeniul HORECA","publisher":"Serviciul Fiscal de Stat","url":"https://sfs.md/ro/stiri/incepand-cu-31-decembrie-2023-se-va-aplica-cota-tva-de-8-pentru-domeniul-horeca","consulted_on":"2026-09-26","kind":"guidance"},{"key":"oifps-1164-2012","title":"Ordinul Inspectoratului Fiscal Principal de Stat nr. 1164 din 25.10.2012 privind aprobarea formularului Declarației privind TVA (forma TVA12) și a Modului de completare a acesteia","publisher":"Inspectoratul Fiscal Principal de Stat / Serviciul Fiscal de Stat","url":"https://www.legis.md/cautare/getResults?lang=ro&doc_id=126104","consulted_on":"2026-09-26","kind":"form"},{"key":"efactura-achizitii","title":"Comunicat privind utilizarea obligatorie în cadrul achizițiilor publice a serviciului electronic „e-Factura” — art. 117 alin. (12) din Codul fiscal, Legea nr. 102/2020","publisher":"Agenția Achiziții Publice","url":"https://tender.gov.md/ro/content/comunicat-privind-utilizarea-obligatorie-%C3%AEn-cadrul-achizi%C8%9Biilor-publice-serviciului-1","consulted_on":"2026-09-26","kind":"guidance"},{"key":"sfs-raportare-portal","title":"SIA „Declarație electronică” — portalul de depunere a declarațiilor fiscale, inclusiv Declarația privind TVA (forma TVA12) și facturile fiscale electronice ale sistemului e-Factura","publisher":"Serviciul Fiscal de Stat","url":"https://raportare.gov.md/reports-sfs","consulted_on":"2026-09-26","kind":"portal"},{"key":"omf119-2013","title":"Ordinul Ministerului Finanțelor nr. 119 din 06.08.2013 privind aprobarea Planului general de conturi contabile","publisher":"Ministerul Finanțelor al Republicii Moldova","url":"https://mf.gov.md/sites/default/files/legislatie/Planul%20general%20de%20conturi%20contabile.pdf","consulted_on":"2026-09-26","kind":"regulation"},{"key":"legea-287-2017","title":"Legea contabilității și raportării financiare nr. 287 din 15.12.2017","publisher":"Parlamentul Republicii Moldova — Ministerul Finanțelor","url":"https://mf.gov.md/ro/content/legea-contabilit%C4%83%C8%9Bii-%C8%99i-raport%C4%83rii-financiare-nr-287","consulted_on":"2026-09-26","kind":"law"},{"key":"snc-prezentarea","title":"Standardul Național de Contabilitate „Prezentarea situațiilor financiare” (S.N.C. 5), aprobat prin ordinul Ministerului Finanțelor nr. 118 din 29.07.2013, modificat prin ordinul nr. 194 din 2018 — formularele Bilanțul contabil (Forma nr. 1) și Raportul de profit și pierderi (Forma nr. 2)","publisher":"Ministerul Finanțelor al Republicii Moldova","url":"https://old.mf.gov.md/files/files/Standardele%20Na%C8%9Bionale%20de%20Contabilitate.pdf","consulted_on":"2026-09-26","kind":"regulation"},{"key":"codul-civil-942","title":"Codul civil al Republicii Moldova nr. 1107/2002, art. 942 — dobânda de întârziere în executarea obligațiilor pecuniare","publisher":"Parlamentul Republicii Moldova","url":"https://www.legis.md/cautare/getResults?doc_id=112573&lang=ro","consulted_on":"2026-09-26","kind":"law"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('MD', 'default', 'Planul general de conturi contabile', '{"en":"General chart of accounts"}'::jsonb, true, 'companies', array['MD-SNC-BS', 'MD-SNC-IS']::text[], null, 'Ordinul Ministerului Finanțelor nr. 119 din 06.08.2013, în vigoare de la 01.01.2014, obligatoriu de la 01.01.2015 pentru entitățile care nu aplică Standardele Internaționale de Raportare Financiară și nu sunt instituții publice — Planul general de conturi contabile, cu nouă clase (1-9). Acest pachet transcrie clasele 1-7 (active imobilizate, active circulante, capital propriu, datorii pe termen lung, datorii curente, venituri, cheltuieli), care poartă conturile de bilanț și de rezultate; clasa 8 (conturi de gestiune) și clasa 9 (conturi extrabilanțiere), declarate de recomandare de textul ordinului și fără corespondent în Declarația privind TVA sau în situațiile financiare, nu sunt reluate — a se vedea README.md. Subconturile 53441 și 53442 (TVA colectată/deductibilă) sunt o convenție a acestui pachet pentru a distinge contul de decontare a TVA (5344, reconciliabil) de conturile de postare ale taxelor, absentă din nomenclatorul oficial care nu detaliază contul 5344 la gradul II — semnalată în README.', 'omf119-2013')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('MD', 'default', '11', 'Imobilizări necorporale', '{"en":"Intangible assets"}'::jsonb, 'asset_fixed', false, null, 10),
  ('MD', 'default', '111', 'Imobilizări necorporale în curs de execuție', '{"en":"Intangible assets under construction"}'::jsonb, 'asset_fixed', false, '11', 20),
  ('MD', 'default', '112', 'Imobilizări necorporale în exploatare', '{"en":"Intangible assets in use"}'::jsonb, 'asset_fixed', false, '11', 30),
  ('MD', 'default', '1121', 'Concesiuni, licențe și mărci', '{"en":"Concessions, licences and trademarks"}'::jsonb, 'asset_fixed', false, '112', 40),
  ('MD', 'default', '1122', 'Drepturi de autor și titluri de protecție', '{"en":"Copyrights and titles of protection"}'::jsonb, 'asset_fixed', false, '112', 50),
  ('MD', 'default', '1123', 'Programe informatice', '{"en":"Computer software"}'::jsonb, 'asset_fixed', false, '112', 60),
  ('MD', 'default', '1124', 'Alte imobilizări necorporale', '{"en":"Other intangible assets"}'::jsonb, 'asset_fixed', false, '112', 70),
  ('MD', 'default', '113', 'Amortizarea imobilizărilor necorporale', '{"en":"Amortisation of intangible assets"}'::jsonb, 'asset_fixed', false, '11', 80),
  ('MD', 'default', '114', 'Deprecierea imobilizărilor necorporale', '{"en":"Impairment of intangible assets"}'::jsonb, 'asset_fixed', false, '11', 90),
  ('MD', 'default', '115', 'Fond comercial pozitiv', '{"en":"Positive goodwill"}'::jsonb, 'asset_fixed', false, '11', 100),
  ('MD', 'default', '116', 'Fond comercial negativ', '{"en":"Negative goodwill"}'::jsonb, 'asset_fixed', false, '11', 110),
  ('MD', 'default', '117', 'Deprecierea fondului comercial pozitiv', '{"en":"Impairment of positive goodwill"}'::jsonb, 'asset_fixed', false, '11', 120),
  ('MD', 'default', '12', 'Imobilizări corporale, terenuri, mijloace fixe și resurse minerale', '{"en":"Tangible fixed assets, land, fixed assets and mineral resources"}'::jsonb, 'asset_fixed', false, null, 130),
  ('MD', 'default', '121', 'Imobilizări corporale în curs de execuție', '{"en":"Tangible fixed assets under construction"}'::jsonb, 'asset_fixed', false, '12', 140),
  ('MD', 'default', '122', 'Terenuri', '{"en":"Land"}'::jsonb, 'asset_fixed', false, '12', 150),
  ('MD', 'default', '123', 'Mijloace fixe', '{"en":"Fixed assets"}'::jsonb, 'asset_fixed', false, '12', 160),
  ('MD', 'default', '1231', 'Clădiri', '{"en":"Buildings"}'::jsonb, 'asset_fixed', false, '123', 170),
  ('MD', 'default', '1232', 'Construcții speciale', '{"en":"Special constructions"}'::jsonb, 'asset_fixed', false, '123', 180),
  ('MD', 'default', '1233', 'Mașini, utilaje și instalații tehnice', '{"en":"Machinery, equipment and technical installations"}'::jsonb, 'asset_fixed', false, '123', 190),
  ('MD', 'default', '1234', 'Mijloace de transport', '{"en":"Vehicles"}'::jsonb, 'asset_fixed', false, '123', 200),
  ('MD', 'default', '1235', 'Inventar și mobilier', '{"en":"Fixtures and furniture"}'::jsonb, 'asset_fixed', false, '123', 210),
  ('MD', 'default', '124', 'Amortizarea mijloacelor fixe', '{"en":"Depreciation of fixed assets"}'::jsonb, 'asset_fixed', false, '12', 220),
  ('MD', 'default', '125', 'Resurse minerale', '{"en":"Mineral resources"}'::jsonb, 'asset_fixed', false, '12', 230),
  ('MD', 'default', '126', 'Amortizarea și deprecierea resurselor minerale', '{"en":"Depreciation and impairment of mineral resources"}'::jsonb, 'asset_fixed', false, '12', 240),
  ('MD', 'default', '127', 'Deprecierea imobilizărilor corporale în curs de execuție', '{"en":"Impairment of tangible fixed assets under construction"}'::jsonb, 'asset_fixed', false, '12', 250),
  ('MD', 'default', '128', 'Deprecierea terenurilor', '{"en":"Impairment of land"}'::jsonb, 'asset_fixed', false, '12', 260),
  ('MD', 'default', '129', 'Deprecierea mijloacelor fixe', '{"en":"Impairment of fixed assets"}'::jsonb, 'asset_fixed', false, '12', 270),
  ('MD', 'default', '13', 'Active biologice imobilizate', '{"en":"Non-current biological assets"}'::jsonb, 'asset_fixed', false, null, 280),
  ('MD', 'default', '131', 'Active biologice imobilizate în curs de execuție', '{"en":"Non-current biological assets under construction"}'::jsonb, 'asset_fixed', false, '13', 290),
  ('MD', 'default', '132', 'Active biologice imobilizate în exploatare', '{"en":"Non-current biological assets in use"}'::jsonb, 'asset_fixed', false, '13', 300),
  ('MD', 'default', '133', 'Amortizarea și deprecierea activelor biologice imobilizate', '{"en":"Depreciation and impairment of non-current biological assets"}'::jsonb, 'asset_fixed', false, '13', 310),
  ('MD', 'default', '14', 'Investiții financiare pe termen lung', '{"en":"Long-term financial investments"}'::jsonb, 'asset_non_current', false, null, 320),
  ('MD', 'default', '141', 'Investiții financiare pe termen lung în părți neafiliate', '{"en":"Long-term financial investments in unrelated parties"}'::jsonb, 'asset_non_current', false, '14', 330),
  ('MD', 'default', '1411', 'Valori mobiliare', '{"en":"Securities"}'::jsonb, 'asset_non_current', false, '141', 340),
  ('MD', 'default', '1412', 'Cote de participație', '{"en":"Equity interests"}'::jsonb, 'asset_non_current', false, '141', 350),
  ('MD', 'default', '1413', 'Depozite', '{"en":"Deposits"}'::jsonb, 'asset_non_current', false, '141', 360),
  ('MD', 'default', '1414', 'Împrumuturi acordate', '{"en":"Loans granted"}'::jsonb, 'asset_non_current', false, '141', 370),
  ('MD', 'default', '142', 'Investiții financiare pe termen lung în părți afiliate', '{"en":"Long-term financial investments in related parties"}'::jsonb, 'asset_non_current', false, '14', 380),
  ('MD', 'default', '143', 'Deprecierea investițiilor financiare pe termen lung', '{"en":"Impairment of long-term financial investments"}'::jsonb, 'asset_non_current', false, '14', 390),
  ('MD', 'default', '15', 'Investiții imobiliare', '{"en":"Investment property"}'::jsonb, 'asset_non_current', false, null, 400),
  ('MD', 'default', '151', 'Investiții imobiliare', '{"en":"Investment property"}'::jsonb, 'asset_non_current', false, '15', 410),
  ('MD', 'default', '152', 'Amortizarea și deprecierea investițiilor imobiliare', '{"en":"Depreciation and impairment of investment property"}'::jsonb, 'asset_non_current', false, '15', 420),
  ('MD', 'default', '16', 'Creanțe și avansuri acordate pe termen lung', '{"en":"Long-term receivables and advances granted"}'::jsonb, 'asset_non_current', false, null, 430),
  ('MD', 'default', '161', 'Creanțe pe termen lung', '{"en":"Long-term receivables"}'::jsonb, 'asset_non_current', false, '16', 440),
  ('MD', 'default', '162', 'Creanțe ale părților afiliate pe termen lung', '{"en":"Long-term receivables from related parties"}'::jsonb, 'asset_non_current', false, '16', 450),
  ('MD', 'default', '163', 'Avansuri acordate pe termen lung', '{"en":"Long-term advances granted"}'::jsonb, 'asset_non_current', false, '16', 460),
  ('MD', 'default', '17', 'Alte active imobilizate', '{"en":"Other non-current assets"}'::jsonb, 'asset_non_current', false, null, 470),
  ('MD', 'default', '171', 'Cheltuieli anticipate pe termen lung', '{"en":"Long-term prepaid expenses"}'::jsonb, 'asset_non_current', false, '17', 480),
  ('MD', 'default', '172', 'Alte active imobilizate', '{"en":"Other non-current assets"}'::jsonb, 'asset_non_current', false, '17', 490),
  ('MD', 'default', '21', 'Stocuri', '{"en":"Inventories"}'::jsonb, 'asset_current', false, null, 500),
  ('MD', 'default', '211', 'Materiale', '{"en":"Materials"}'::jsonb, 'asset_current', false, '21', 510),
  ('MD', 'default', '2111', 'Materii prime și materiale de bază', '{"en":"Raw materials and basic materials"}'::jsonb, 'asset_current', false, '211', 520),
  ('MD', 'default', '2112', 'Materiale auxiliare', '{"en":"Auxiliary materials"}'::jsonb, 'asset_current', false, '211', 530),
  ('MD', 'default', '2113', 'Piese de schimb', '{"en":"Spare parts"}'::jsonb, 'asset_current', false, '211', 540),
  ('MD', 'default', '2114', 'Combustibil', '{"en":"Fuel"}'::jsonb, 'asset_current', false, '211', 550),
  ('MD', 'default', '2115', 'Ambalaje', '{"en":"Packaging"}'::jsonb, 'asset_current', false, '211', 560),
  ('MD', 'default', '212', 'Active biologice circulante', '{"en":"Current biological assets"}'::jsonb, 'asset_current', false, '21', 570),
  ('MD', 'default', '213', 'Obiecte de mică valoare și scurtă durată', '{"en":"Low-value and short-lived items"}'::jsonb, 'asset_current', false, '21', 580),
  ('MD', 'default', '214', 'Uzura obiectelor de mică valoare și scurtă durată', '{"en":"Depreciation of low-value and short-lived items"}'::jsonb, 'asset_current', false, '21', 590),
  ('MD', 'default', '215', 'Producția în curs de execuție', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, '21', 600),
  ('MD', 'default', '216', 'Produse', '{"en":"Products"}'::jsonb, 'asset_current', false, '21', 610),
  ('MD', 'default', '2161', 'Produse finite', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, '216', 620),
  ('MD', 'default', '217', 'Mărfuri', '{"en":"Merchandise"}'::jsonb, 'asset_current', false, '21', 630),
  ('MD', 'default', '2171', 'Bunuri procurate în vederea revânzării', '{"en":"Goods purchased for resale"}'::jsonb, 'asset_current', false, '217', 640),
  ('MD', 'default', '218', 'Ajustări pentru deprecierea stocurilor', '{"en":"Allowances for impairment of inventories"}'::jsonb, 'asset_current', false, '21', 650),
  ('MD', 'default', '22', 'Creanțe comerciale și calculate', '{"en":"Trade and calculated receivables"}'::jsonb, 'asset_current', false, null, 660),
  ('MD', 'default', '221', 'Creanțe comerciale', '{"en":"Trade receivables"}'::jsonb, 'asset_receivable', true, '22', 670),
  ('MD', 'default', '2211', 'Creanțe comerciale din țară', '{"en":"Domestic trade receivables"}'::jsonb, 'asset_receivable', true, '221', 680),
  ('MD', 'default', '2212', 'Creanțe comerciale din străinătate', '{"en":"Foreign trade receivables"}'::jsonb, 'asset_receivable', true, '221', 690),
  ('MD', 'default', '222', 'Corecții privind creanțele compromise', '{"en":"Allowances for doubtful receivables"}'::jsonb, 'asset_current', false, '22', 700),
  ('MD', 'default', '223', 'Creanțe ale părților afiliate', '{"en":"Receivables from related parties"}'::jsonb, 'asset_current', false, '22', 710),
  ('MD', 'default', '224', 'Avansuri acordate curente', '{"en":"Current advances granted"}'::jsonb, 'asset_current', false, '22', 720),
  ('MD', 'default', '225', 'Creanțe ale bugetului', '{"en":"Receivables from the budget"}'::jsonb, 'asset_current', false, '22', 730),
  ('MD', 'default', '2251', 'Creanțe privind impozitul pe venit', '{"en":"Income tax receivable"}'::jsonb, 'asset_current', false, '225', 740),
  ('MD', 'default', '2252', 'Creanțe privind taxa pe valoarea adăugată', '{"en":"VAT receivable"}'::jsonb, 'asset_current', true, '225', 750),
  ('MD', 'default', '2253', 'Creanțe privind accizele', '{"en":"Excise duty receivable"}'::jsonb, 'asset_current', false, '225', 760),
  ('MD', 'default', '2254', 'Creanțe privind alte impozite și taxe', '{"en":"Other tax receivables"}'::jsonb, 'asset_current', false, '225', 770),
  ('MD', 'default', '226', 'Creanțe ale personalului', '{"en":"Receivables from personnel"}'::jsonb, 'asset_current', false, '22', 780),
  ('MD', 'default', '23', 'Alte creanțe curente', '{"en":"Other current receivables"}'::jsonb, 'asset_current', false, null, 790),
  ('MD', 'default', '231', 'Creanțe privind veniturile din utilizarea de către terți a activelor entității', '{"en":"Receivables from third-party use of the entity''s assets"}'::jsonb, 'asset_current', false, '23', 800),
  ('MD', 'default', '232', 'Creanțe preliminate', '{"en":"Preliminary receivables"}'::jsonb, 'asset_current', false, '23', 810),
  ('MD', 'default', '233', 'Creanțe curente privind asigurările', '{"en":"Current insurance receivables"}'::jsonb, 'asset_current', false, '23', 820),
  ('MD', 'default', '234', 'Alte creanțe curente', '{"en":"Other current receivables"}'::jsonb, 'asset_current', false, '23', 830),
  ('MD', 'default', '24', 'Numerar', '{"en":"Cash"}'::jsonb, 'asset_cash', false, null, 840),
  ('MD', 'default', '241', 'Casa', '{"en":"Cash on hand"}'::jsonb, 'asset_cash', false, '24', 850),
  ('MD', 'default', '242', 'Conturi curente în monedă națională', '{"en":"Current accounts in national currency"}'::jsonb, 'asset_cash', false, '24', 860),
  ('MD', 'default', '243', 'Conturi curente în valută străină', '{"en":"Current accounts in foreign currency"}'::jsonb, 'asset_cash', false, '24', 870),
  ('MD', 'default', '244', 'Alte conturi bancare', '{"en":"Other bank accounts"}'::jsonb, 'asset_cash', false, '24', 880),
  ('MD', 'default', '245', 'Transferuri de numerar în expediție', '{"en":"Cash in transit"}'::jsonb, 'asset_cash', false, '24', 890),
  ('MD', 'default', '246', 'Documente bănești', '{"en":"Cash documents"}'::jsonb, 'asset_cash', false, '24', 900),
  ('MD', 'default', '25', 'Investiții financiare curente', '{"en":"Current financial investments"}'::jsonb, 'asset_current', false, null, 910),
  ('MD', 'default', '251', 'Investiții financiare curente în părți neafiliate', '{"en":"Current financial investments in unrelated parties"}'::jsonb, 'asset_current', false, '25', 920),
  ('MD', 'default', '252', 'Investiții financiare curente în părți afiliate', '{"en":"Current financial investments in related parties"}'::jsonb, 'asset_current', false, '25', 930),
  ('MD', 'default', '253', 'Provizioane pentru pierderi din împrumuturi neachitate la termen', '{"en":"Provisions for losses on loans not repaid at term"}'::jsonb, 'asset_current', false, '25', 940),
  ('MD', 'default', '254', 'Ajustări pentru deprecierea investițiilor financiare curente', '{"en":"Allowances for impairment of current financial investments"}'::jsonb, 'asset_current', false, '25', 950),
  ('MD', 'default', '26', 'Alte active circulante', '{"en":"Other current assets"}'::jsonb, 'asset_current', false, null, 960),
  ('MD', 'default', '261', 'Cheltuieli anticipate curente', '{"en":"Current prepaid expenses"}'::jsonb, 'asset_prepayments', false, '26', 970),
  ('MD', 'default', '262', 'Alte active circulante', '{"en":"Other current assets"}'::jsonb, 'asset_current', false, '26', 980),
  ('MD', 'default', '31', 'Capital social, neînregistrat și prime de capital', '{"en":"Share capital, unregistered capital and share premium"}'::jsonb, 'equity', false, null, 990),
  ('MD', 'default', '311', 'Capital social', '{"en":"Share capital"}'::jsonb, 'equity', false, '31', 1000),
  ('MD', 'default', '313', 'Capital nevărsat', '{"en":"Uncalled capital"}'::jsonb, 'equity', false, '31', 1010),
  ('MD', 'default', '314', 'Capital neînregistrat', '{"en":"Unregistered capital"}'::jsonb, 'equity', false, '31', 1020),
  ('MD', 'default', '315', 'Capital retras', '{"en":"Withdrawn capital"}'::jsonb, 'equity', false, '31', 1030),
  ('MD', 'default', '316', 'Patrimoniul primit de la stat cu drept de proprietate', '{"en":"Assets received from the state with ownership right"}'::jsonb, 'equity', false, '31', 1040),
  ('MD', 'default', '317', 'Prime de capital', '{"en":"Share premium"}'::jsonb, 'equity', false, '31', 1050),
  ('MD', 'default', '32', 'Rezerve', '{"en":"Reserves"}'::jsonb, 'equity', false, null, 1060),
  ('MD', 'default', '321', 'Capital de rezervă', '{"en":"Legal reserve"}'::jsonb, 'equity', false, '32', 1070),
  ('MD', 'default', '322', 'Rezerve statutare', '{"en":"Statutory reserves"}'::jsonb, 'equity', false, '32', 1080),
  ('MD', 'default', '323', 'Alte rezerve', '{"en":"Other reserves"}'::jsonb, 'equity', false, '32', 1090),
  ('MD', 'default', '33', 'Profit nerepartizat (pierdere neacoperită)', '{"en":"Retained earnings (uncovered loss)"}'::jsonb, 'equity_retained', false, null, 1100),
  ('MD', 'default', '331', 'Corecții ale rezultatelor anilor precedenți', '{"en":"Corrections of prior years'' results"}'::jsonb, 'equity_retained', false, '33', 1110),
  ('MD', 'default', '332', 'Profit nerepartizat (pierdere neacoperită) al anilor precedenți', '{"en":"Retained earnings (uncovered loss) of prior years"}'::jsonb, 'equity_retained', false, '33', 1120),
  ('MD', 'default', '333', 'Profit net (pierdere netă) al perioadei de gestiune', '{"en":"Net profit (net loss) for the period"}'::jsonb, 'equity_retained', false, '33', 1130),
  ('MD', 'default', '334', 'Profit utilizat al perioadei de gestiune', '{"en":"Profit used during the period"}'::jsonb, 'equity_retained', false, '33', 1140),
  ('MD', 'default', '335', 'Rezultat din tranziția la noile reglementări contabile', '{"en":"Result of transition to new accounting regulations"}'::jsonb, 'equity_retained', false, '33', 1150),
  ('MD', 'default', '336', 'Excedent net (deficit net) al perioadei de gestiune', '{"en":"Net surplus (net deficit) for the period"}'::jsonb, 'equity_retained', false, '33', 1160),
  ('MD', 'default', '34', 'Alte elemente de capital propriu', '{"en":"Other equity items"}'::jsonb, 'equity', false, null, 1170),
  ('MD', 'default', '341', 'Fonduri', '{"en":"Funds"}'::jsonb, 'equity', false, '34', 1180),
  ('MD', 'default', '342', 'Subvenții aferente activelor entităților cu proprietate publică', '{"en":"Grants related to assets of publicly owned entities"}'::jsonb, 'equity', false, '34', 1190),
  ('MD', 'default', '343', 'Rezerve din reevaluare', '{"en":"Revaluation reserves"}'::jsonb, 'equity', false, '34', 1200),
  ('MD', 'default', '344', 'Alte elemente de capital propriu', '{"en":"Other equity items"}'::jsonb, 'equity', false, '34', 1210),
  ('MD', 'default', '35', 'Rezultat financiar total', '{"en":"Total financial result"}'::jsonb, 'equity_retained', false, null, 1220),
  ('MD', 'default', '351', 'Rezultat financiar total', '{"en":"Total financial result"}'::jsonb, 'equity_retained', false, '35', 1230),
  ('MD', 'default', '41', 'Datorii financiare pe termen lung', '{"en":"Long-term financial liabilities"}'::jsonb, 'liability_non_current', false, null, 1240),
  ('MD', 'default', '411', 'Credite bancare pe termen lung', '{"en":"Long-term bank loans"}'::jsonb, 'liability_non_current', false, '41', 1250),
  ('MD', 'default', '412', 'Împrumuturi pe termen lung', '{"en":"Long-term borrowings"}'::jsonb, 'liability_non_current', false, '41', 1260),
  ('MD', 'default', '414', 'Datorii privind depunerile de economii pe termen lung ale membrilor asociațiilor de economii și împrumut', '{"en":"Long-term savings deposits of members of savings and loan associations"}'::jsonb, 'liability_non_current', false, '41', 1270),
  ('MD', 'default', '42', 'Alte datorii pe termen lung', '{"en":"Other long-term liabilities"}'::jsonb, 'liability_non_current', false, null, 1280),
  ('MD', 'default', '421', 'Datorii comerciale pe termen lung', '{"en":"Long-term trade payables"}'::jsonb, 'liability_non_current', false, '42', 1290),
  ('MD', 'default', '422', 'Datorii față de părțile afiliate pe termen lung', '{"en":"Long-term payables to related parties"}'::jsonb, 'liability_non_current', false, '42', 1300),
  ('MD', 'default', '423', 'Avansuri primite pe termen lung', '{"en":"Long-term advances received"}'::jsonb, 'liability_non_current', false, '42', 1310),
  ('MD', 'default', '424', 'Venituri anticipate pe termen lung', '{"en":"Long-term deferred income"}'::jsonb, 'liability_non_current', false, '42', 1320),
  ('MD', 'default', '425', 'Finanțări și încasări cu destinație specială pe termen lung', '{"en":"Long-term earmarked financing and receipts"}'::jsonb, 'liability_non_current', false, '42', 1330),
  ('MD', 'default', '426', 'Provizioane pe termen lung', '{"en":"Long-term provisions"}'::jsonb, 'liability_non_current', false, '42', 1340),
  ('MD', 'default', '427', 'Datorii pe termen lung privind bunurile primite în gestiune economică', '{"en":"Long-term payables on assets received in economic management"}'::jsonb, 'liability_non_current', false, '42', 1350),
  ('MD', 'default', '428', 'Alte datorii pe termen lung', '{"en":"Other long-term liabilities"}'::jsonb, 'liability_non_current', false, '42', 1360),
  ('MD', 'default', '51', 'Datorii financiare curente', '{"en":"Current financial liabilities"}'::jsonb, 'liability_current', false, null, 1370),
  ('MD', 'default', '511', 'Credite bancare pe termen scurt', '{"en":"Short-term bank loans"}'::jsonb, 'liability_current', false, '51', 1380),
  ('MD', 'default', '512', 'Împrumuturi pe termen scurt', '{"en":"Short-term borrowings"}'::jsonb, 'liability_current', false, '51', 1390),
  ('MD', 'default', '513', 'Datorii privind depunerile de economii pe termen scurt ale membrilor asociațiilor de economii și împrumut', '{"en":"Short-term savings deposits of members of savings and loan associations"}'::jsonb, 'liability_current', false, '51', 1400),
  ('MD', 'default', '52', 'Datorii comerciale curente', '{"en":"Current trade payables"}'::jsonb, 'liability_current', false, null, 1410),
  ('MD', 'default', '521', 'Datorii comerciale curente', '{"en":"Current trade payables"}'::jsonb, 'liability_payable', true, '52', 1420),
  ('MD', 'default', '522', 'Datorii curente față de părțile afiliate', '{"en":"Current payables to related parties"}'::jsonb, 'liability_current', false, '52', 1430),
  ('MD', 'default', '523', 'Avansuri primite curente', '{"en":"Current advances received"}'::jsonb, 'liability_current', false, '52', 1440),
  ('MD', 'default', '53', 'Datorii calculate curente', '{"en":"Current accrued liabilities"}'::jsonb, 'liability_current', false, null, 1450),
  ('MD', 'default', '531', 'Datorii față de personal privind retribuirea muncii', '{"en":"Payables to personnel regarding remuneration"}'::jsonb, 'liability_current', false, '53', 1460),
  ('MD', 'default', '532', 'Datorii față de personal privind alte operații', '{"en":"Payables to personnel for other operations"}'::jsonb, 'liability_current', false, '53', 1470),
  ('MD', 'default', '533', 'Datorii privind asigurările sociale și medicale', '{"en":"Payables for social and medical insurance"}'::jsonb, 'liability_current', false, '53', 1480),
  ('MD', 'default', '534', 'Datorii față de buget', '{"en":"Payables to the budget"}'::jsonb, 'liability_current', false, '53', 1490),
  ('MD', 'default', '5341', 'Datorii privind impozitul pe venit din activitatea de întreprinzător și profesională', '{"en":"Income tax payable on entrepreneurial and professional activity"}'::jsonb, 'liability_current', false, '534', 1500),
  ('MD', 'default', '5342', 'Datorii privind impozitul pe venit din salariu', '{"en":"Income tax payable on wages"}'::jsonb, 'liability_current', false, '534', 1510),
  ('MD', 'default', '5343', 'Datorii privind impozitul pe venit reținut la sursa de plată', '{"en":"Income tax withheld at source"}'::jsonb, 'liability_current', false, '534', 1520),
  ('MD', 'default', '5344', 'Datorii privind taxa pe valoarea adăugată', '{"en":"VAT payable"}'::jsonb, 'liability_current', true, '534', 1530),
  ('MD', 'default', '53441', 'TVA colectată', '{"en":"VAT collected"}'::jsonb, 'liability_current', false, '5344', 1540),
  ('MD', 'default', '53442', 'TVA deductibilă', '{"en":"VAT deductible"}'::jsonb, 'liability_current', false, '5344', 1550),
  ('MD', 'default', '53443', 'TVA aferentă serviciilor importate', '{"en":"VAT on imported services"}'::jsonb, 'liability_current', false, '5344', 1555),
  ('MD', 'default', '5345', 'Datorii privind accizele', '{"en":"Excise duty payable"}'::jsonb, 'liability_current', false, '534', 1560),
  ('MD', 'default', '5346', 'Datorii privind alte impozite și taxe', '{"en":"Other taxes and duties payable"}'::jsonb, 'liability_current', false, '534', 1570),
  ('MD', 'default', '535', 'Venituri anticipate curente', '{"en":"Current deferred income"}'::jsonb, 'liability_current', false, '53', 1580),
  ('MD', 'default', '536', 'Datorii față de proprietari', '{"en":"Payables to owners"}'::jsonb, 'liability_current', false, '53', 1590),
  ('MD', 'default', '537', 'Finanțări și încasări cu destinație specială curente', '{"en":"Current earmarked financing and receipts"}'::jsonb, 'liability_current', false, '53', 1600),
  ('MD', 'default', '538', 'Provizioane curente', '{"en":"Current provisions"}'::jsonb, 'liability_current', false, '53', 1610),
  ('MD', 'default', '54', 'Alte datorii curente', '{"en":"Other current liabilities"}'::jsonb, 'liability_current', false, null, 1620),
  ('MD', 'default', '541', 'Datorii preliminate', '{"en":"Preliminary payables"}'::jsonb, 'liability_current', false, '54', 1630),
  ('MD', 'default', '542', 'Datorii privind asigurarea bunurilor și a persoanelor', '{"en":"Payables for insurance of goods and persons"}'::jsonb, 'liability_current', false, '54', 1640),
  ('MD', 'default', '543', 'Datorii curente privind bunurile primite în gestiune economică', '{"en":"Current payables on assets received in economic management"}'::jsonb, 'liability_current', false, '54', 1650),
  ('MD', 'default', '544', 'Alte datorii curente', '{"en":"Other current liabilities"}'::jsonb, 'liability_current', false, '54', 1660),
  ('MD', 'default', '61', 'Venituri din activitatea operațională', '{"en":"Income from operating activity"}'::jsonb, 'income', false, null, 1670),
  ('MD', 'default', '611', 'Venituri din vânzări', '{"en":"Revenue from sales"}'::jsonb, 'income', false, '61', 1680),
  ('MD', 'default', '6111', 'Venituri din vânzarea produselor', '{"en":"Revenue from sale of products"}'::jsonb, 'income', false, '611', 1690),
  ('MD', 'default', '6112', 'Venituri din vânzarea mărfurilor', '{"en":"Revenue from sale of merchandise"}'::jsonb, 'income', false, '611', 1700),
  ('MD', 'default', '6113', 'Venituri din prestarea serviciilor', '{"en":"Revenue from services rendered"}'::jsonb, 'income', false, '611', 1710),
  ('MD', 'default', '612', 'Alte venituri din activitatea operațională', '{"en":"Other income from operating activity"}'::jsonb, 'income', false, '61', 1720),
  ('MD', 'default', '613', 'Venituri din dobânzile aferente împrumuturilor acordate', '{"en":"Interest income on loans granted"}'::jsonb, 'income', false, '61', 1730),
  ('MD', 'default', '616', 'Venituri aferente mijloacelor cu destinație specială', '{"en":"Income related to earmarked funds"}'::jsonb, 'income', false, '61', 1740),
  ('MD', 'default', '617', 'Alte venituri (cu excepția veniturilor din activitatea economică)', '{"en":"Other income (excluding income from economic activity)"}'::jsonb, 'income', false, '61', 1750),
  ('MD', 'default', '618', 'Venituri din activitatea economică', '{"en":"Income from economic activity"}'::jsonb, 'income', false, '61', 1760),
  ('MD', 'default', '62', 'Venituri din alte activități', '{"en":"Income from other activities"}'::jsonb, 'income_other', false, null, 1770),
  ('MD', 'default', '621', 'Venituri din operațiuni cu active imobilizate', '{"en":"Income from transactions with non-current assets"}'::jsonb, 'income_other', false, '62', 1780),
  ('MD', 'default', '6211', 'Venituri din ieșirea imobilizărilor necorporale', '{"en":"Income from disposal of intangible assets"}'::jsonb, 'income_other', false, '621', 1790),
  ('MD', 'default', '6212', 'Venituri din ieșirea imobilizărilor corporale', '{"en":"Income from disposal of tangible fixed assets"}'::jsonb, 'income_other', false, '621', 1800),
  ('MD', 'default', '622', 'Venituri financiare', '{"en":"Financial income"}'::jsonb, 'income_other', false, '62', 1810),
  ('MD', 'default', '6221', 'Venituri din interese de participare', '{"en":"Income from equity interests"}'::jsonb, 'income_other', false, '622', 1820),
  ('MD', 'default', '6222', 'Venituri din dobânzi', '{"en":"Interest income"}'::jsonb, 'income_other', false, '622', 1830),
  ('MD', 'default', '6226', 'Venituri din diferențe de curs valutar', '{"en":"Foreign exchange gains"}'::jsonb, 'income_other', false, '622', 1840),
  ('MD', 'default', '6227', 'Venituri din diferențe de sumă', '{"en":"Rounding differences income"}'::jsonb, 'income_other', false, '622', 1850),
  ('MD', 'default', '623', 'Venituri excepționale', '{"en":"Extraordinary income"}'::jsonb, 'income_other', false, '62', 1860),
  ('MD', 'default', '71', 'Cheltuieli ale activității operaționale', '{"en":"Expenses of operating activity"}'::jsonb, 'expense', false, null, 1870),
  ('MD', 'default', '711', 'Costul vânzărilor', '{"en":"Cost of sales"}'::jsonb, 'expense_direct_cost', false, '71', 1880),
  ('MD', 'default', '7111', 'Valoarea contabilă a produselor vândute', '{"en":"Carrying amount of products sold"}'::jsonb, 'expense_direct_cost', false, '711', 1890),
  ('MD', 'default', '7112', 'Valoarea contabilă a mărfurilor vândute', '{"en":"Carrying amount of merchandise sold"}'::jsonb, 'expense_direct_cost', false, '711', 1900),
  ('MD', 'default', '7113', 'Costul serviciilor prestate', '{"en":"Cost of services rendered"}'::jsonb, 'expense_direct_cost', false, '711', 1910),
  ('MD', 'default', '712', 'Cheltuieli de distribuire', '{"en":"Distribution expenses"}'::jsonb, 'expense', false, '71', 1920),
  ('MD', 'default', '713', 'Cheltuieli administrative', '{"en":"Administrative expenses"}'::jsonb, 'expense', false, '71', 1930),
  ('MD', 'default', '714', 'Alte cheltuieli din activitatea operațională', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, '71', 1940),
  ('MD', 'default', '7148', 'Alte cheltuieli operaționale', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, '714', 1950),
  ('MD', 'default', '715', 'Cheltuieli aferente dobânzilor calculate', '{"en":"Interest expense accrued"}'::jsonb, 'expense', false, '71', 1960),
  ('MD', 'default', '716', 'Cheltuieli aferente mijloacelor cu destinație specială', '{"en":"Expenses related to earmarked funds"}'::jsonb, 'expense', false, '71', 1970),
  ('MD', 'default', '717', 'Alte cheltuieli (cu excepția cheltuielilor din activitatea economică)', '{"en":"Other expenses (excluding expenses of economic activity)"}'::jsonb, 'expense', false, '71', 1980),
  ('MD', 'default', '718', 'Cheltuieli din activitatea economică', '{"en":"Expenses of economic activity"}'::jsonb, 'expense', false, '71', 1990),
  ('MD', 'default', '72', 'Cheltuieli ale altor activități', '{"en":"Expenses of other activities"}'::jsonb, 'expense', false, null, 2000),
  ('MD', 'default', '721', 'Cheltuieli cu active imobilizate', '{"en":"Expenses with non-current assets"}'::jsonb, 'expense', false, '72', 2010),
  ('MD', 'default', '7211', 'Valoarea contabilă și cheltuielile aferente imobilizărilor necorporale ieșite', '{"en":"Carrying amount and expenses on disposal of intangible assets"}'::jsonb, 'expense', false, '721', 2020),
  ('MD', 'default', '7212', 'Valoarea contabilă și cheltuielile aferente imobilizărilor corporale ieșite', '{"en":"Carrying amount and expenses on disposal of tangible fixed assets"}'::jsonb, 'expense', false, '721', 2030),
  ('MD', 'default', '722', 'Cheltuieli financiare', '{"en":"Financial expenses"}'::jsonb, 'expense', false, '72', 2040),
  ('MD', 'default', '7221', 'Cheltuieli privind dobânzile', '{"en":"Interest expense"}'::jsonb, 'expense', false, '722', 2050),
  ('MD', 'default', '7224', 'Cheltuieli din diferențe de curs valutar', '{"en":"Foreign exchange losses"}'::jsonb, 'expense', false, '722', 2060),
  ('MD', 'default', '7225', 'Cheltuieli din diferențe de sumă', '{"en":"Rounding differences expense"}'::jsonb, 'expense', false, '722', 2070),
  ('MD', 'default', '723', 'Cheltuieli excepționale', '{"en":"Extraordinary expenses"}'::jsonb, 'expense', false, '72', 2080),
  ('MD', 'default', '73', 'Cheltuieli privind impozitul pe venit', '{"en":"Income tax expense"}'::jsonb, 'expense', false, null, 2090),
  ('MD', 'default', '731', 'Cheltuieli privind impozitul pe venit', '{"en":"Income tax expense"}'::jsonb, 'expense', false, '73', 2100)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('MD', 'BNC', 'Jurnal de bancă', '{"en":"Bank journal"}'::jsonb, 'bank', 30),
  ('MD', 'CAS', 'Jurnal de casă', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('MD', 'CMP', 'Registrul de evidență a procurărilor', '{"en":"Purchase register"}'::jsonb, 'purchase', 20),
  ('MD', 'DES', 'Notă de deschidere', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('MD', 'DIV', 'Operațiuni diverse', '{"en":"Miscellaneous operations"}'::jsonb, 'general', 50),
  ('MD', 'VNZ', 'Registrul de evidență a livrărilor', '{"en":"Sales register"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('MD', 'MD-P-20', 'Procurări pe teritoriul țării — cota standard 20%, deductibilă', '{"en":"Domestic purchases — standard rate 20%, deductible"}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2016-01-01', null, 'Codul fiscal, art. 102 alin. (1) — subiecților impozabili înregistrați li se permite trecerea în cont a sumei TVA achitate sau care urmează a fi achitată furnizorilor plătitori de TVA pe valorile materiale, serviciile procurate pentru efectuarea livrărilor impozabile, dacă dispun de factura fiscală a furnizorului (art. 102 alin. (6) lit. a)).', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('MD', 'MD-P-8', 'Procurări pe teritoriul țării — cota redusă 8%, deductibilă', '{"en":"Domestic purchases — reduced rate 8%, deductible"}'::jsonb, null, 'percent', 8, 'purchase', 'domestic', date '2023-12-31', null, 'Codul fiscal, art. 96 lit. b) pentru cota aplicată de furnizor; art. 102 alin. (1) pentru dreptul de trecere în cont al cumpărătorului, în aceleași condiții ca la MD-P-20.', null, null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('MD', 'MD-P-IMPORT', 'Import de mărfuri — cota standard 20%, deductibilă', '{"en":"Import of goods — standard rate 20%, deductible"}'::jsonb, null, 'percent', 20, 'purchase', 'import', date '2016-01-01', null, 'Codul fiscal, art. 100 — valoarea impozabilă a mărfurilor importate este valoarea lor vamală; art. 101 alin. (7) — TVA se achită pînă la sau la momentul depunerii declarației vamale; art. 102 alin. (6) lit. b) — trecerea în cont este condiționată de documentul eliberat de autoritățile vamale ce confirmă achitarea TVA la mărfurile importate.', null, null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('MD', 'MD-P-IMPORT-SRV', 'Import de servicii — autolichidare, cota standard 20%', '{"en":"Import of services — self-assessment, standard rate 20%"}'::jsonb, null, 'percent', 20, 'purchase', 'foreign_services_received', date '2016-01-01', null, 'Codul fiscal, art. 94 lit. c) — persoana care importă servicii pentru desfășurarea activității de întreprinzător este subiect impozabil; art. 101 alin. (4) — TVA se achită la momentul achitării plății pentru serviciul importat; art. 115 alin. (1) — obligația de a declara TVA aferentă serviciilor importate pentru fiecare perioadă fiscală, chiar și de o persoană neînregistrată ca plătitor de TVA.', null, null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('MD', 'MD-S-0-EXPORT', 'Export de mărfuri, servicii și transport internațional — cota zero', '{"en":"Export of goods, services and international transport — zero rate"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2008-01-01', null, 'Codul fiscal, art. 104 lit. a) — se impozitează la cota zero a TVA mărfurile, serviciile pentru export și toate tipurile de transporturi internaționale de mărfuri (inclusiv de expediție) și pasageri; art. 102 alin. (8) — dreptul la restituirea TVA aferente valorilor materiale, serviciilor procurate pentru o astfel de livrare este condiționat de confirmarea organelor vamale privind livrarea mărfurilor pentru export și de documentele de transport internațional.', null, null, 30, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('MD', 'MD-S-20', 'Livrări — cota standard 20%', '{"en":"Sales — standard rate 20%"}'::jsonb, null, 'percent', 20, 'sale', 'domestic', date '2016-01-01', null, 'Codul fiscal, art. 96 lit. a) — cota standard, în mărime de 20% din valoarea impozabilă a livrărilor efectuate pe teritoriul Republicii Moldova.', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('MD', 'MD-S-8', 'Livrări — cota redusă 8%', '{"en":"Sales — reduced rate 8%"}'::jsonb, null, 'percent', 8, 'sale', 'domestic', date '2023-12-31', null, 'Codul fiscal, art. 96 lit. b) — cotă redusă de 8%, aplicabilă, printre altele: pîinii și produselor de panificație și laptelui și produselor lactate (cu excepția produselor alimentare pentru copii, scutite conform art. 103 alin. (1) pct. 2)); medicamentelor înscrise în Nomenclatorul de stat sau autorizate de Ministerul Sănătății, inclusiv preparate în farmacii conform prescripțiilor magistrale; unor mărfuri și articole cu destinație medicală de la pozițiile tarifare indicate expres de lege; gazelor naturale și gazelor lichefiate; producției din zootehnie și horticultură în formă naturală, livrate de producători; zahărului din sfeclă de zahăr; biocombustibilului solid; produselor de igienă feminină de la poziția tarifară ex. 9619; serviciilor de cazare, indiferent de categoria de confort, și produselor alimentare și/sau băuturilor nealcoolice preparate sau nepreparate, însoțite de servicii ce permit consumul imediat, în cadrul activităților din secțiunea I a Clasificatorului Activităților din Economia Moldovei (domeniul HORECA) — cota de 8% aplicabilă domeniului HORECA este permanentă începînd cu 31 decembrie 2023, dată la care a încetat starea de urgență ce menținea temporar o cotă redusă la 8% din 2022, potrivit modificării aduse prin Legea nr. 212/2023.', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'sfs-horeca-8', null, null, null, null),
  ('MD', 'MD-S-EXE', 'Livrare scutită de TVA fără drept de deducere — locuință, pămînt, arendă', '{"en":"Exempt supply without right of deduction — housing, land, lease"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2016-01-01', null, 'Codul fiscal, art. 103 alin. (1) pct. 1) — T.V.A. nu se aplică livrărilor de mărfuri, servicii ce constituie rezultatul activității de întreprinzător, printre care locuința, pămîntul, arenda acestora, dreptul de livrare și arendare a acestora, cu excepția plăților de comision aferente tranzacțiilor respective.', null, null, 40, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('MD-P-20', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'MD-TVA12', 10),
    ('MD-P-20', 'invoice', 'tax', 100, '53442', '13', array['13']::text[], 100, 'MD-TVA12', 20),
    ('MD-P-20', 'credit_note', 'tax', 100, '53442', '16', array['16']::text[], -100, 'MD-TVA12', 10),
    ('MD-P-8', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'MD-TVA12', 10),
    ('MD-P-8', 'invoice', 'tax', 100, '53442', '13', array['13']::text[], 100, 'MD-TVA12', 20),
    ('MD-P-8', 'credit_note', 'tax', 100, '53442', '16', array['16']::text[], -100, 'MD-TVA12', 10),
    ('MD-P-IMPORT', 'invoice', 'base', 100, null, '14', array['14']::text[], 100, 'MD-TVA12', 10),
    ('MD-P-IMPORT', 'invoice', 'tax', 100, '53442', '15', array['15']::text[], 100, 'MD-TVA12', 20),
    ('MD-P-IMPORT', 'credit_note', 'tax', 100, '53442', '16', array['16']::text[], -100, 'MD-TVA12', 10),
    ('MD-P-IMPORT-SRV', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'MD-TVA12', 10),
    ('MD-P-IMPORT-SRV', 'invoice', 'tax', 100, '53443', '8', array['8']::text[], 100, 'MD-TVA12', 20),
    ('MD-P-IMPORT-SRV', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'MD-TVA12', 10),
    ('MD-P-IMPORT-SRV', 'credit_note', 'tax', 100, '53443', '8', array['8']::text[], -100, 'MD-TVA12', 20),
    ('MD-S-0-EXPORT', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'MD-TVA12', 10),
    ('MD-S-0-EXPORT', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'MD-TVA12', 10),
    ('MD-S-20', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'MD-TVA12', 10),
    ('MD-S-20', 'invoice', 'tax', 100, '53441', '2', array['2']::text[], 100, 'MD-TVA12', 20),
    ('MD-S-20', 'credit_note', 'tax', 100, '53441', '9', array['9']::text[], -100, 'MD-TVA12', 10),
    ('MD-S-8', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'MD-TVA12', 10),
    ('MD-S-8', 'invoice', 'tax', 100, '53441', '4', array['4']::text[], 100, 'MD-TVA12', 20),
    ('MD-S-8', 'credit_note', 'tax', 100, '53441', '9', array['9']::text[], -100, 'MD-TVA12', 10),
    ('MD-S-EXE', 'invoice', 'base', 100, null, '6', array['6']::text[], 100, 'MD-TVA12', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'MD' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('MD', 'MD-TVA12', 'Declarația privind TVA (forma TVA12)', array['month']::declaration_period[], 'month'::declaration_period, date '2012-10-25', null, 'Ordinul Inspectoratului Fiscal Principal de Stat nr. 1164 din 25.10.2012, anexa nr. 1 (formularul TVA12) și anexa nr. 2 (Modul de completare). Acest pachet transcrie boxele pe care taxele sale le declară și cele patru totaluri pe care le poate calcula fără starea din perioada fiscală precedentă; sub-boxele 1.1, 2.1 și 11.1 (informative, nu se completează sau condiționate de un avans încasat în altă perioadă decît livrarea) și boxele 17, 21, 22 (suma trecută în cont din perioada precedentă, suma destinată trecerii în cont în perioada următoare, suma solicitată spre restituire) nu sunt reluate — a se vedea README.md și secțiunea «From Moldova» din docs/international.md.', true,'day_of_month_after_period'::filing_deadline_rule, 25, null, 'Codul fiscal, art. 115 alin. (1) — declarația privind TVA se prezintă Serviciului Fiscal de Stat pentru fiecare perioadă fiscală, în termenul stabilit de acest articol. Cercetarea acestui pachet nu a putut confirma formularea la zi a art. 115 alin. (1) pe un text consolidat deschis fără autentificare (legis.md refuză o cerere fără navigator, ca Légifrance — a se vedea docs/packs.md); practica de raportare curentă (formularul TVA12, prezentat prin SIA „Declarație electronică”) fixează termenul la ziua 25 a lunii următoare încheierii perioadei fiscale, dată reținută aici — de reverificat pe textul oficial de un contabil autorizat.', 'sfs-raportare-portal', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('MD', 'MD-TVA12', '1', 'base', 'Livrări de mărfuri și servicii impozitate la cota standard, efectuate pe teritoriul Republicii Moldova', '{"en":"Supplies of goods and services taxed at the standard rate, made on the territory of the Republic of Moldova"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 1; Modul de completare, pct. 4.2.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '2', 'tax', 'Suma TVA calculată de la valoarea livrărilor de la rd. 1', '{"en":"VAT calculated on the value of supplies from row 1"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 2; Modul de completare, pct. 4.3.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '3', 'base', 'Livrări de mărfuri și servicii la cota redusă', '{"en":"Supplies of goods and services at the reduced rate"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 3; Modul de completare, pct. 4.5.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '4', 'tax', 'Suma TVA calculată de la valoarea livrărilor de la rd. 3', '{"en":"VAT calculated on the value of supplies from row 3"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 4; Modul de completare, pct. 4.6.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '5', 'base', 'Livrări scutite de TVA cu drept de deducere (cota zero)', '{"en":"Supplies exempt from VAT with the right of deduction (zero rate)"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 5; Modul de completare, pct. 4.7.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '6', 'base', 'Livrări scutite de TVA fără drept de deducere', '{"en":"Supplies exempt from VAT without the right of deduction"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 6; Modul de completare, pct. 4.8.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '7', 'base', 'Import de servicii', '{"en":"Import of services"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 7; Modul de completare, pct. 4.9.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '8', 'tax', 'Suma TVA calculată de la valoarea de la rd. 7', '{"en":"VAT calculated on the value from row 7"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 8; Modul de completare, pct. 4.10.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '9', 'tax', 'Ajustarea TVA aferentă livrărilor', '{"en":"Adjustment of VAT related to supplies"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 9; Modul de completare, pct. 4.11 — corectarea erorilor din perioadele precedente, datoriile compromise (art. 116 alin. (1)) și ajustările conform art. 98 pentru livrările efectuate.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '10', 'total', 'Total — volumul livrărilor efectuate în perioada fiscală', '{"en":"Total — volume of supplies made in the fiscal period"}'::jsonb, 100, null, array['1', '3', '5', '6']::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 10; Modul de completare, pct. 4.12.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '11', 'total', 'Total — suma TVA aferentă livrărilor efectuate în perioada fiscală', '{"en":"Total — VAT related to supplies made in the fiscal period"}'::jsonb, 110, null, array['2', '4', '9']::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 11; Modul de completare, pct. 4.13.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '12', 'base', 'Procurări de mărfuri, servicii pe teritoriul Republicii Moldova', '{"en":"Purchases of goods, services on the territory of the Republic of Moldova"}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 12; Modul de completare, pct. 4.15.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '13', 'tax', 'Suma TVA pentru procurările de la rd. 12, spre trecere în cont', '{"en":"VAT for the purchases from row 12, for deduction"}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 13; Modul de completare, pct. 4.16.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '14', 'base', 'Importul de mărfuri, servicii', '{"en":"Import of goods, services"}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 14; Modul de completare, pct. 4.17.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '15', 'tax', 'Suma TVA aferentă mărfurilor, serviciilor de la rd. 14, spre trecere în cont', '{"en":"VAT related to the goods, services from row 14, for deduction"}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 15; Modul de completare, pct. 4.18.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '16', 'tax', 'Ajustarea TVA aferentă procurărilor', '{"en":"Adjustment of VAT related to purchases"}'::jsonb, 160, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 16; Modul de completare, pct. 4.19 — corectarea erorilor, datoriile compromise (art. 116 alin. (3)) și ajustările conform art. 98 și art. 102 alin. (3) pentru procurările efectuate.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '18', 'total', 'Total TVA spre deducere', '{"en":"Total VAT for deduction"}'::jsonb, 170, null, array['13', '15', '16']::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 18 (13+15+16+17); Modul de completare, pct. 4.21. rd. 17 (suma trecută în cont din perioada fiscală precedentă) nu este reluat de acest pachet — a se vedea README.md.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '19', 'total', 'TVA aferentă bugetului', '{"en":"VAT due to the budget"}'::jsonb, 180, null, array['11']::text[], array['18']::text[], null, null, true, false, null, 'Formularul TVA12, rd. 19 (11-18); Modul de completare, pct. 4.22 — se completează numai cînd rd. 11 depășește rd. 18; cazul invers (suma spre trecere în cont sau spre restituire, rd. 21-22) nu este reluat de acest pachet.', 'oifps-1164-2012'),
  ('MD', 'MD-TVA12', '20', 'total', 'TVA aferentă bugetului pentru import de servicii', '{"en":"VAT due to the budget for the import of services"}'::jsonb, 190, null, array['8']::text[], '{}'::text[], null, null, false, false, null, 'Formularul TVA12, rd. 20 (echivalentă cu suma reflectată la rd. 8); Modul de completare, pct. 4.23.', 'oifps-1164-2012')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('MD-SNC-BS', 'MD', 'default', 'Bilanțul contabil', 'balance_sheet', 'MD-SNC-5', date '1970-01-01', null, 'S.N.C. 5 „Prezentarea situațiilor financiare”, aprobat prin ordinul Ministerului Finanțelor nr. 118 din 29.07.2013, anexa nr. 1 — Forma nr. 1, Bilanțul contabil. Acest pachet transcrie liniile de capitol și de secțiune ale formularului, la nivelul grupelor de conturi (cod rd.), fără fiecare cont sintetic de gradul I sau II în parte — forma abreviată, în lipsa unei versiuni oficiale «micro» sau «prescurtate» distincte confirmate de cercetarea acestui pachet. Activele biologice imobilizate (clasa 13), introduse ulterior primei redacții a formularului consultate, sunt reluate împreună cu activele materiale pe termen lung (rd. 090) — a se vedea README.md.', 'snc-prezentarea'),
  ('MD-SNC-IS', 'MD', 'default', 'Raportul de profit și pierderi', 'income_statement', 'MD-SNC-5', date '1970-01-01', null, 'S.N.C. 5 „Prezentarea situațiilor financiare”, anexa nr. 2 — Forma nr. 2, Raportul de profit și pierderi, în varianta pe funcții (cheltuieli clasificate în costul vânzărilor, cheltuieli de distribuire, cheltuieli administrative și alte cheltuieli operaționale). Veniturile și cheltuielile din conturile 613, 616-618 și, respectiv, 715-718, care nu figurau pe un rând distinct al primei redacții a formularului consultate, sunt reluate împreună cu «alte venituri operaționale» (rd. 040) și «alte cheltuieli operaționale» (rd. 070) — a se vedea README.md.', 'snc-prezentarea')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('MD-SNC-BS', '030', null, 'Valoarea de bilanț a activelor nemateriale', '{"en":"Carrying value of intangible assets"}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '090', null, 'Valoarea de bilanț a activelor materiale pe termen lung', '{"en":"Carrying value of non-current tangible assets"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '160', null, 'Total active financiare pe termen lung', '{"en":"Total long-term financial assets"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '170', null, 'Alte active pe termen lung', '{"en":"Other non-current assets"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '180', '470', 'Total capitolul 1 — active pe termen lung', '{"en":"Total chapter 1 — non-current assets"}'::jsonb, 50, 1, true, array['030', '090', '160', '170']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 180 (rd.030+rd.090+rd.160+rd.170).', 'snc-prezentarea'),
  ('MD-SNC-BS', '250', null, 'Total stocuri de mărfuri și materiale', '{"en":"Total inventories of goods and materials"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '350', null, 'Total creanțe pe termen scurt', '{"en":"Total short-term receivables"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '390', null, 'Total investiții pe termen scurt', '{"en":"Total short-term investments"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '440', null, 'Total mijloace bănești', '{"en":"Total cash"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '450', null, 'Alte active curente', '{"en":"Other current assets"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '460', '470', 'Total capitolul 2 — active curente', '{"en":"Total chapter 2 — current assets"}'::jsonb, 110, 1, true, array['250', '350', '390', '440', '450']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 460 (rd.250+rd.350+rd.390+rd.440+rd.450).', 'snc-prezentarea'),
  ('MD-SNC-BS', '470', null, 'TOTAL GENERAL — ACTIV', '{"en":"TOTAL ASSETS"}'::jsonb, 120, 1, true, array['180', '460']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 470 (rd.180+rd.460).', 'snc-prezentarea'),
  ('MD-SNC-BS', '520', null, 'Capital statutar și suplimentar', '{"en":"Share capital and additional capital"}'::jsonb, 130, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '560', null, 'Rezerve', '{"en":"Reserves"}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '610', null, 'Profit nerepartizat (pierdere neacoperită)', '{"en":"Retained earnings (uncovered loss)"}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '640', null, 'Capital secundar', '{"en":"Secondary capital"}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '650', '980', 'Total capitolul 3 — capital propriu', '{"en":"Total chapter 3 — equity"}'::jsonb, 170, 1, true, array['520', '560', '610', '640']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 650 (rd.520+rd.560+rd.610+rd.640).', 'snc-prezentarea'),
  ('MD-SNC-BS', '690', null, 'Datorii financiare pe termen lung', '{"en":"Long-term financial liabilities"}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '760', null, 'Datorii pe termen lung calculate', '{"en":"Long-term accrued liabilities"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '770', '980', 'Total capitolul 4 — datorii pe termen lung', '{"en":"Total chapter 4 — non-current liabilities"}'::jsonb, 200, 1, true, array['690', '760']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 770 (rd.690+rd.760).', 'snc-prezentarea'),
  ('MD-SNC-BS', '820', null, 'Datorii financiare curente', '{"en":"Current financial liabilities"}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '860', null, 'Datorii comerciale curente', '{"en":"Current trade payables"}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '960', null, 'Datorii curente calculate și alte datorii curente', '{"en":"Current accrued and other current liabilities"}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-BS', '970', '980', 'Total capitolul 5 — datorii curente', '{"en":"Total chapter 5 — current liabilities"}'::jsonb, 240, 1, true, array['820', '860', '960']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 970 (rd.820+rd.860+rd.960).', 'snc-prezentarea'),
  ('MD-SNC-BS', '980', null, 'TOTAL GENERAL — PASIV', '{"en":"TOTAL EQUITY AND LIABILITIES"}'::jsonb, 250, 1, true, array['650', '770', '970']::text[], '{}'::text[], null, 'Forma nr. 1, rd. 980 (rd.650+rd.770+rd.970).', 'snc-prezentarea'),
  ('MD-SNC-IS', '010', null, 'Venituri din vînzări', '{"en":"Revenue from sales"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '020', null, 'Costul vînzărilor', '{"en":"Cost of sales"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '030', null, 'Profitul brut (pierdere globală)', '{"en":"Gross profit (overall loss)"}'::jsonb, 30, 1, true, array['010']::text[], array['020']::text[], null, 'Forma nr. 2, rd. 030 (rd.010-rd.020).', 'snc-prezentarea'),
  ('MD-SNC-IS', '040', null, 'Alte venituri operaționale', '{"en":"Other operating income"}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '050', null, 'Cheltuieli comerciale', '{"en":"Distribution expenses"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '060', null, 'Cheltuieli generale și administrative', '{"en":"General and administrative expenses"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '070', null, 'Alte cheltuieli operaționale', '{"en":"Other operating expenses"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '080', null, 'Rezultatul din activitatea operațională: profit (pierdere)', '{"en":"Result of operating activity: profit (loss)"}'::jsonb, 80, 1, true, array['030', '040']::text[], array['050', '060', '070']::text[], null, 'Forma nr. 2, rd. 080 (rd.030+rd.040-rd.050-rd.060-rd.070).', 'snc-prezentarea'),
  ('MD-SNC-IS', '090', null, 'Rezultatul din activitatea de investiții: profit (pierdere)', '{"en":"Result of investing activity: profit (loss)"}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, 'Forma nr. 2, rd. 090 (621-721) — venituri și cheltuieli din operațiuni cu active imobilizate, reunite pe un singur rând al formularului.', 'snc-prezentarea'),
  ('MD-SNC-IS', '100', null, 'Rezultatul din activitatea financiară: profit (pierdere)', '{"en":"Result of financial activity: profit (loss)"}'::jsonb, 100, -1, false, '{}'::text[], '{}'::text[], null, 'Forma nr. 2, rd. 100 (622-722) — venituri și cheltuieli financiare, reunite pe un singur rând al formularului.', 'snc-prezentarea'),
  ('MD-SNC-IS', '110', null, 'Rezultatul din activitatea economico-financiară: profit (pierdere)', '{"en":"Result of economic-financial activity: profit (loss)"}'::jsonb, 110, 1, true, array['080', '090', '100']::text[], '{}'::text[], null, 'Forma nr. 2, rd. 110 (±rd.080±rd.090±rd.100).', 'snc-prezentarea'),
  ('MD-SNC-IS', '120', null, 'Rezultatul excepțional: profit (pierdere)', '{"en":"Extraordinary result: profit (loss)"}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, 'Forma nr. 2, rd. 120 (623-723) — venituri și cheltuieli excepționale, reunite pe un singur rând al formularului.', 'snc-prezentarea'),
  ('MD-SNC-IS', '130', null, 'Profitul (pierderea) perioadei de gestiune pînă la impozitare', '{"en":"Profit (loss) of the period before taxation"}'::jsonb, 130, 1, true, array['110', '120']::text[], '{}'::text[], null, 'Forma nr. 2, rd. 130 (±rd.110±rd.120).', 'snc-prezentarea'),
  ('MD-SNC-IS', '140', null, 'Cheltuieli (economii) privind impozitul pe venit', '{"en":"Income tax expense (saving)"}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MD-SNC-IS', '150', null, 'Profit net (pierdere)', '{"en":"Net profit (loss)"}'::jsonb, 150, 1, true, array['130']::text[], array['140']::text[], null, 'Forma nr. 2, rd. 150 (±rd.130±rd.140).', 'snc-prezentarea')
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('MD-SNC-BS', '030', 10, 'code_prefix', '11', null, null, 'any'),
    ('MD-SNC-BS', '090', 10, 'code_prefix', '12', null, null, 'any'),
    ('MD-SNC-BS', '090', 20, 'code_prefix', '13', null, null, 'any'),
    ('MD-SNC-BS', '160', 10, 'code_prefix', '14', null, null, 'any'),
    ('MD-SNC-BS', '160', 20, 'code_prefix', '15', null, null, 'any'),
    ('MD-SNC-BS', '170', 10, 'code_prefix', '16', null, null, 'any'),
    ('MD-SNC-BS', '170', 20, 'code_prefix', '17', null, null, 'any'),
    ('MD-SNC-BS', '250', 10, 'code_prefix', '21', null, null, 'any'),
    ('MD-SNC-BS', '350', 10, 'code_prefix', '22', null, null, 'any'),
    ('MD-SNC-BS', '350', 20, 'code_prefix', '23', null, null, 'any'),
    ('MD-SNC-BS', '390', 10, 'code_prefix', '25', null, null, 'any'),
    ('MD-SNC-BS', '440', 10, 'code_prefix', '24', null, null, 'any'),
    ('MD-SNC-BS', '450', 10, 'code_prefix', '26', null, null, 'any'),
    ('MD-SNC-BS', '520', 10, 'code_prefix', '31', null, null, 'any'),
    ('MD-SNC-BS', '560', 10, 'code_prefix', '32', null, null, 'any'),
    ('MD-SNC-BS', '610', 10, 'code_prefix', '33', null, null, 'any'),
    ('MD-SNC-BS', '640', 10, 'code_prefix', '34', null, null, 'any'),
    ('MD-SNC-BS', '640', 20, 'code_prefix', '35', null, null, 'any'),
    ('MD-SNC-BS', '690', 10, 'code_prefix', '41', null, null, 'any'),
    ('MD-SNC-BS', '760', 10, 'code_prefix', '42', null, null, 'any'),
    ('MD-SNC-BS', '820', 10, 'code_prefix', '51', null, null, 'any'),
    ('MD-SNC-BS', '860', 10, 'code_prefix', '52', null, null, 'any'),
    ('MD-SNC-BS', '960', 10, 'code_prefix', '53', null, null, 'any'),
    ('MD-SNC-BS', '960', 20, 'code_prefix', '54', null, null, 'any'),
    ('MD-SNC-IS', '010', 10, 'code_prefix', '611', null, null, 'any'),
    ('MD-SNC-IS', '020', 10, 'code_prefix', '711', null, null, 'any'),
    ('MD-SNC-IS', '040', 10, 'code_prefix', '612', null, null, 'any'),
    ('MD-SNC-IS', '040', 20, 'code_prefix', '613', null, null, 'any'),
    ('MD-SNC-IS', '040', 30, 'code_prefix', '616', null, null, 'any'),
    ('MD-SNC-IS', '040', 40, 'code_prefix', '617', null, null, 'any'),
    ('MD-SNC-IS', '040', 50, 'code_prefix', '618', null, null, 'any'),
    ('MD-SNC-IS', '050', 10, 'code_prefix', '712', null, null, 'any'),
    ('MD-SNC-IS', '060', 10, 'code_prefix', '713', null, null, 'any'),
    ('MD-SNC-IS', '070', 10, 'code_prefix', '714', null, null, 'any'),
    ('MD-SNC-IS', '070', 20, 'code_prefix', '715', null, null, 'any'),
    ('MD-SNC-IS', '070', 30, 'code_prefix', '716', null, null, 'any'),
    ('MD-SNC-IS', '070', 40, 'code_prefix', '717', null, null, 'any'),
    ('MD-SNC-IS', '070', 50, 'code_prefix', '718', null, null, 'any'),
    ('MD-SNC-IS', '090', 10, 'code_prefix', '621', null, null, 'any'),
    ('MD-SNC-IS', '090', 20, 'code_prefix', '721', null, null, 'any'),
    ('MD-SNC-IS', '100', 10, 'code_prefix', '622', null, null, 'any'),
    ('MD-SNC-IS', '100', 20, 'code_prefix', '722', null, null, 'any'),
    ('MD-SNC-IS', '120', 10, 'code_prefix', '623', null, null, 'any'),
    ('MD-SNC-IS', '120', 20, 'code_prefix', '723', null, null, 'any'),
    ('MD-SNC-IS', '140', 10, 'code_prefix', '731', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('MD', 'Moldova', '{"en":"Moldova"}'::jsonb, array['ro', 'en']::text[], 'MDL', '221', '521', '544', '7148', '332', '611', '711', '242', '241', 'VNZ', 'CMP', 'DIV', 'ro', 'result_accounts', '333', '333', null, 'DES', 'half_up', default, '6226', '7224', '6212', '7212', null, null, '5344', '2252', 'Notă contabilă de deschidere', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = true,
  number_format                 = '{CODE}{NNNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = 'Codul civil, art. 942 alin. (1)-(2) — dacă o sumă de bani nu este plătită la scadență, creditorul are dreptul la dobânda de întârziere asupra acestei sume din ziua imediat următoare datei scadenței pînă în ziua plății, la rata prevăzută de acest articol (rata de bază stabilită semianual de Banca Națională a Moldovei, majorată cu un număr de puncte procentuale), fie la o altă rată prevăzută de dispoziții legale speciale sau de contract. Dispozițiile art. 942-945, introduse prin Legea nr. 133/2018, se aplică de la 1 martie 2019. Codul fiscal nu fixează un termen de plată implicit între profesioniști, spre deosebire de Directiva europeană 2011/7/UE: termenul rămîne o clauză a contractului.',
  numbering_legal_reference     = 'Codul fiscal, art. 117 alin. (2) pct. 1) — factura fiscală trebuie să includă în mod obligatoriu «numărul curent al facturii». Legea cere doar un număr curent (secvențial), fără să impute o remitere la zero anuală; seria facturii fiscale este fie atribuită de Serviciul Fiscal de Stat pentru un formular imprimat tipografic, fie autoimprimată cu o serie și un număr alocate de acesta, potrivit art. 117 și normelor de completare aprobate prin ordinul Ministerului Finanțelor nr. 118 din 28.08.2017 — formatul indicat aici, cu un cod de serie și un contor, este un exemplu de conformare al acestui pachet și nu forma unică impusă de text.',
  numbering_source_key          = 'codul-fiscal',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Codul fiscal, art. 108 alin. (1) — data obligației fiscale este, ca regulă, data livrării (predarea mărfurilor, prestarea serviciului); alin. (4)-(5) — pentru servicii, sau dacă factura fiscală este eliberată ori plata este primită înainte de livrare, data obligației devine data eliberării facturii sau data plății, oricare intervine mai devreme. Principiul este livrarea, iar factura (sau plata anticipată) devansează data — exact structura pe care valoarea închisă «invoice_if_issued» o descrie; devansarea produsă exclusiv de o plată anticipată fără factură emisă anterior nu este exprimabilă separat de acest cîmp și rămîne nemodelată, ca și în cazul pachetului românesc — a se vedea secțiunea «From Moldova» din docs/international.md.',
  tax_point_source_key          = 'codul-fiscal',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Codul fiscal, art. 117 alin. (12), introdus prin Legea nr. 102 din 18.06.2020 — la efectuarea livrărilor impozabile în cadrul achizițiilor publice pe teritoriul țării (inclusiv achizițiile sectoriale, concesiunile și achizițiile de valoare mică), subiectul impozabil este obligat să prezinte cumpărătorului (beneficiarului) o factură fiscală electronică prin sistemul informațional automatizat SIA „e-Factura”, cu excepția livrărilor de energie electrică, energie termică, gaze naturale, servicii comunale și servicii de comunicații electronice — obligație în vigoare de la 1 ianuarie 2021. Domeniul de aplicare a fost extins de la 1 ianuarie 2025 la livrările către agenții economici care nu au relații fiscale cu sistemul bugetar al Republicii Moldova și la mărfurile/serviciile finanțate din proiecte de asistență tehnică realizate prin granturi și tratate internaționale. `profile` rămîne vid: SIA „e-Factura” este un serviciu al Serviciul Fiscal de Stat prin care factura fiscală electronică este generată și transmisă direct în platforma de stat — cercetarea acestui pachet nu a găsit o confirmare oficială că documentul schimbat urmează un model semantic interoperabil de tipul EN 16931 (Peppol BIS, Factur-X, XRechnung, un PINT); niciun brick din packages/formats/ nu scrie, validează sau transmite azi o asemenea factură. `party_scheme` și `vat_scheme` rămîn de asemenea vide: contribuabilul este identificat prin codul fiscal (IDNO/IDNP) atribuit de Serviciul Fiscal de Stat, fără o schemă ISO 6523 înregistrată — a se vedea secțiunea «From Moldova» din docs/international.md.',
  einvoice_source_key           = 'efactura-achizitii',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'MD';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('MD', 'reverse_charge', 'reverse_charge', 'TVA se calculează și se achită la buget de către beneficiar, în conformitate cu art. 94 lit. c) și art. 115 din Codul fiscal.', '{"en":"VAT is calculated and paid to the budget by the recipient, in accordance with art. 94 letter c) and art. 115 of the Tax Code."}'::jsonb, 10, date '1970-01-01', null, 'Codul fiscal, art. 94 lit. c) — subiect impozabil este și persoana care importă servicii; art. 115 alin. (1) — obligația de declarare a TVA aferente serviciilor importate. Textul menționat pe factură este o formulare a acestui pachet: legea nu impune o mențiune tipizată pentru acest caz.'),
  ('MD', 'export', 'export', 'Livrare impozitată la cota zero a TVA, conform art. 104 lit. a) din Codul fiscal.', '{"en":"Supply taxed at the zero VAT rate, in accordance with art. 104 letter a) of the Tax Code."}'::jsonb, 20, date '1970-01-01', null, 'Codul fiscal, art. 104 lit. a) — mărfurile, serviciile pentru export și toate tipurile de transporturi internaționale de mărfuri și pasageri se impozitează la cota zero a TVA.'),
  ('MD', 'exempt', 'exempt', 'Livrare scutită de TVA fără drept de deducere, conform art. 103 din Codul fiscal.', '{"en":"Supply exempt from VAT without the right of deduction, in accordance with art. 103 of the Tax Code."}'::jsonb, 30, date '1970-01-01', null, 'Codul fiscal, art. 103 alin. (1) — T.V.A. nu se aplică livrărilor enumerate la acest alineat, printre care, la pct. 1), locuința, pămîntul, arenda acestora.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
