-- Ekwo OS — Bosna i Hercegovina: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ba at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build ba`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Zakon o porezu na dodanu vrijednost ("Službeni glasnik BiH", br. 9/05, 35/05, 100/08, 33/17 i 46/23) — Law on Value Added Tax, official English translation (Uprava za indirektno oporezivanje Bosne i Hercegovine (UIO))
--     https://www.uino.gov.ba/portal/wp-content/uploads/95-ENGLESKI-PROPISI/1-VAT-PDV/1-Law_on_VAT_BiH.pdf
--   Zakon o izmjeni Zakona o porezu na dodatu vrijednost, "Službeni glasnik BiH", broj 80/23 od 24.11.2023 (prag za registraciju povećan na 100.000 KM, član 57) (Parlamentarna skupština Bosne i Hercegovine, objavljeno na uino.gov.ba)
--     https://www.uino.gov.ba/portal/wp-content/uploads/PROPISI/2_Porezi/1_PDV/1_Zakon_o_PDV/B/B-H-S-1-5-Z-o-PDV-sl-list-80-23-24-11-23.pdf
--   Obrazac P PDV — Prijava poreza na dodanu vrijednost, uz Pravilnik o primjeni Zakona o porezu na dodatu vrijednost (Uprava za indirektno oporezivanje Bosne i Hercegovine (UIO))
--     https://www.uino.gov.ba/portal/wp-content/uploads/PROPISI/2_Porezi/1_PDV/2_Pravilnici/B/B-1-1-PDV_prijava_240806.pdf
--   e-Porezi / e-VAT — elektronsko podnošenje prijave PDV-a (Uprava za indirektno oporezivanje Bosne i Hercegovine (UIO))
--     https://www.uino.gov.ba/portal/en/e-services/e-vat/
--   Pravilnik o kontnom okviru i sadržaju konta za privredna društva ("Službene novine Federacije BiH", broj 81/21), na snazi od 01.01.2022. (Federalno ministarstvo finansija)
--     https://privrednastampa.ba/pravilnik-o-kontnom-okviru-i-sadrzaju-konta-za-privredna-drustva-sluzbene-novine-fbih-81-21/
--   Pravilnik o kontnom okviru, sadržaju konta i primjeni kontnog okvira za privredna društva ("Službene novine FBiH", broj 82/10), Prilog — kontni okvir za privredna društva (Federalno ministarstvo finansija)
--     https://www.finpol.gov.ba/pdf/pravilnici/Pravilnik_o_kontnom_okviru_za_privredna_drustva.pdf
--   Pravilnik o sadržaju i formi obrazaca finansijskih izvještaja za privredna društva ("Službene novine FBiH", broj 82/10), Prilog 1 (Bilans stanja) i Prilog 2 (Bilans uspjeha) (Federalno ministarstvo finansija)
--     https://finpol.gov.ba/pdf/pravilnici/Pravilnik_o_sadrzini_i_formi_obrazaca_finansijskih_izvjestaja_za_privredna_drustva.pdf
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('BA', 'Bosna i Hercegovina', '0.1.0', date '2026-09-26', '20260917170000', 'community', null, null, '60b2b2d8093715307b2c556b702f697a855123c28e9c731d134f743e75fc73ed', '[{"key":"vat-law","title":"Zakon o porezu na dodanu vrijednost (\"Službeni glasnik BiH\", br. 9/05, 35/05, 100/08, 33/17 i 46/23) — Law on Value Added Tax, official English translation","publisher":"Uprava za indirektno oporezivanje Bosne i Hercegovine (UIO)","url":"https://www.uino.gov.ba/portal/wp-content/uploads/95-ENGLESKI-PROPISI/1-VAT-PDV/1-Law_on_VAT_BiH.pdf","consulted_on":"2026-09-26","kind":"law"},{"key":"vat-law-amendment-2023","title":"Zakon o izmjeni Zakona o porezu na dodatu vrijednost, \"Službeni glasnik BiH\", broj 80/23 od 24.11.2023 (prag za registraciju povećan na 100.000 KM, član 57)","publisher":"Parlamentarna skupština Bosne i Hercegovine, objavljeno na uino.gov.ba","url":"https://www.uino.gov.ba/portal/wp-content/uploads/PROPISI/2_Porezi/1_PDV/1_Zakon_o_PDV/B/B-H-S-1-5-Z-o-PDV-sl-list-80-23-24-11-23.pdf","consulted_on":"2026-09-26","kind":"law"},{"key":"vat-form","title":"Obrazac P PDV — Prijava poreza na dodanu vrijednost, uz Pravilnik o primjeni Zakona o porezu na dodatu vrijednost","publisher":"Uprava za indirektno oporezivanje Bosne i Hercegovine (UIO)","url":"https://www.uino.gov.ba/portal/wp-content/uploads/PROPISI/2_Porezi/1_PDV/2_Pravilnici/B/B-1-1-PDV_prijava_240806.pdf","consulted_on":"2026-09-26","kind":"form"},{"key":"vat-portal","title":"e-Porezi / e-VAT — elektronsko podnošenje prijave PDV-a","publisher":"Uprava za indirektno oporezivanje Bosne i Hercegovine (UIO)","url":"https://www.uino.gov.ba/portal/en/e-services/e-vat/","consulted_on":"2026-09-26","kind":"portal"},{"key":"coa-2021","title":"Pravilnik o kontnom okviru i sadržaju konta za privredna društva (\"Službene novine Federacije BiH\", broj 81/21), na snazi od 01.01.2022.","publisher":"Federalno ministarstvo finansija","url":"https://privrednastampa.ba/pravilnik-o-kontnom-okviru-i-sadrzaju-konta-za-privredna-drustva-sluzbene-novine-fbih-81-21/","consulted_on":"2026-09-26","kind":"regulation"},{"key":"coa-2010","title":"Pravilnik o kontnom okviru, sadržaju konta i primjeni kontnog okvira za privredna društva (\"Službene novine FBiH\", broj 82/10), Prilog — kontni okvir za privredna društva","publisher":"Federalno ministarstvo finansija","url":"https://www.finpol.gov.ba/pdf/pravilnici/Pravilnik_o_kontnom_okviru_za_privredna_drustva.pdf","consulted_on":"2026-09-26","kind":"regulation"},{"key":"fs-2010","title":"Pravilnik o sadržaju i formi obrazaca finansijskih izvještaja za privredna društva (\"Službene novine FBiH\", broj 82/10), Prilog 1 (Bilans stanja) i Prilog 2 (Bilans uspjeha)","publisher":"Federalno ministarstvo finansija","url":"https://finpol.gov.ba/pdf/pravilnici/Pravilnik_o_sadrzini_i_formi_obrazaca_finansijskih_izvjestaja_za_privredna_drustva.pdf","consulted_on":"2026-09-26","kind":"regulation"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('BA', 'default', 'Kontni okvir za privredna društva (Federacija BiH)', '{"en":"Chart of accounts (FBiH Pravilnik o kontnom okviru, \"Official Gazette of FBiH\" No. 81/21)"}'::jsonb, true, 'companies', array['BA-FBIH-BS', 'BA-FBIH-IS']::text[], null, 'Pravilnik o kontnom okviru i sadržaju konta za privredna društva ("Službene novine Federacije BiH", broj 81/21), u primjeni od 01.01.2022.', 'coa-2021')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('BA', 'default', '01', 'Nematerijalna sredstva', '{"en":"Intangible assets"}'::jsonb, 'asset_fixed', false, null, 10),
  ('BA', 'default', '010', 'Kapitalizirana ulaganja u razvoj', '{"en":"Capitalised development costs"}'::jsonb, 'asset_fixed', false, '01', 20),
  ('BA', 'default', '011', 'Koncesije, patenti, licence i druga prava', '{"en":"Concessions, patents, licences and other rights"}'::jsonb, 'asset_fixed', false, '01', 30),
  ('BA', 'default', '012', 'Goodwill', '{"en":"Goodwill"}'::jsonb, 'asset_fixed', false, '01', 40),
  ('BA', 'default', '014', 'Ostala nematerijalna sredstva', '{"en":"Other intangible assets"}'::jsonb, 'asset_fixed', false, '01', 50),
  ('BA', 'default', '015', 'Nematerijalna sredstva u pripremi', '{"en":"Intangible assets under development"}'::jsonb, 'asset_fixed', false, '01', 60),
  ('BA', 'default', '02', 'Nekretnine, postrojenja i oprema', '{"en":"Property, plant and equipment"}'::jsonb, 'asset_fixed', false, null, 70),
  ('BA', 'default', '020', 'Zemljište', '{"en":"Land"}'::jsonb, 'asset_fixed', false, '02', 80),
  ('BA', 'default', '021', 'Građevinski objekti', '{"en":"Buildings"}'::jsonb, 'asset_fixed', false, '02', 90),
  ('BA', 'default', '022', 'Postrojenja i oprema (mašine)', '{"en":"Plant and equipment (machinery)"}'::jsonb, 'asset_fixed', false, '02', 100),
  ('BA', 'default', '023', 'Alati, pogonski i kancelarijski namještaj', '{"en":"Tools, workshop and office fixtures"}'::jsonb, 'asset_fixed', false, '02', 110),
  ('BA', 'default', '024', 'Transportna sredstva', '{"en":"Vehicles"}'::jsonb, 'asset_fixed', false, '02', 120),
  ('BA', 'default', '025', 'Nekretnine, postrojenja i oprema u pripremi', '{"en":"Property, plant and equipment under construction"}'::jsonb, 'asset_fixed', false, '02', 130),
  ('BA', 'default', '03', 'Investicijske nekretnine', '{"en":"Investment property"}'::jsonb, 'asset_non_current', false, null, 140),
  ('BA', 'default', '030', 'Ulaganja u vlastito zemljište', '{"en":"Investment in own land"}'::jsonb, 'asset_non_current', false, '03', 150),
  ('BA', 'default', '032', 'Ulaganja u vlastite građevine', '{"en":"Investment in own buildings"}'::jsonb, 'asset_non_current', false, '03', 160),
  ('BA', 'default', '04', 'Biološka sredstva', '{"en":"Biological assets"}'::jsonb, 'asset_fixed', false, null, 170),
  ('BA', 'default', '040', 'Šume', '{"en":"Forests"}'::jsonb, 'asset_fixed', false, '04', 180),
  ('BA', 'default', '042', 'Osnovno stado', '{"en":"Breeding stock"}'::jsonb, 'asset_fixed', false, '04', 190),
  ('BA', 'default', '05', 'Ostala (specifična) stalna materijalna sredstva', '{"en":"Other (specific) tangible fixed assets"}'::jsonb, 'asset_fixed', false, null, 200),
  ('BA', 'default', '050', 'Ostala stalna materijalna sredstva u upotrebi', '{"en":"Other tangible fixed assets in use"}'::jsonb, 'asset_fixed', false, '05', 210),
  ('BA', 'default', '06', 'Dugoročni finansijski plasmani', '{"en":"Long-term financial investments"}'::jsonb, 'asset_non_current', false, null, 220),
  ('BA', 'default', '060', 'Učešća u kapitalu povezanih pravnih lica', '{"en":"Equity investments in related parties"}'::jsonb, 'asset_non_current', false, '06', 230),
  ('BA', 'default', '061', 'Učešća u kapitalu drugih pravnih lica', '{"en":"Equity investments in other entities"}'::jsonb, 'asset_non_current', false, '06', 240),
  ('BA', 'default', '062', 'Dugoročni krediti dati povezanim pravnim licima', '{"en":"Long-term loans to related parties"}'::jsonb, 'asset_non_current', false, '06', 250),
  ('BA', 'default', '064', 'Dugoročni krediti dati u zemlji', '{"en":"Long-term loans given domestically"}'::jsonb, 'asset_non_current', false, '06', 260),
  ('BA', 'default', '065', 'Finansijska sredstva raspoloživa za prodaju', '{"en":"Financial assets available for sale"}'::jsonb, 'asset_non_current', false, '06', 270),
  ('BA', 'default', '07', 'Druga dugoročna potraživanja', '{"en":"Other long-term receivables"}'::jsonb, 'asset_non_current', false, null, 280),
  ('BA', 'default', '070', 'Potraživanja od povezanih pravnih lica', '{"en":"Receivables from related parties"}'::jsonb, 'asset_non_current', false, '07', 290),
  ('BA', 'default', '071', 'Potraživanja po osnovu prodaje na kredit', '{"en":"Receivables from sales on credit"}'::jsonb, 'asset_non_current', false, '07', 300),
  ('BA', 'default', '09', 'Odložena porezna sredstva i dugoročna razgraničenja', '{"en":"Deferred tax assets and long-term accruals"}'::jsonb, 'asset_non_current', false, null, 310),
  ('BA', 'default', '090', 'Odložena porezna sredstva', '{"en":"Deferred tax assets"}'::jsonb, 'asset_non_current', false, '09', 320),
  ('BA', 'default', '091', 'Unaprijed plaćeni troškovi (za period duži od 12 mjeseci)', '{"en":"Prepaid expenses (period longer than 12 months)"}'::jsonb, 'asset_non_current', false, '09', 330),
  ('BA', 'default', '10', 'Sirovine, materijal, rezervni dijelovi i sitan inventar', '{"en":"Raw materials, supplies, spare parts and low-value items"}'::jsonb, 'asset_current', false, null, 340),
  ('BA', 'default', '100', 'Obračun troška nabavke', '{"en":"Purchase cost clearing"}'::jsonb, 'asset_current', false, '10', 350),
  ('BA', 'default', '101', 'Sirovine i materijal', '{"en":"Raw materials and supplies"}'::jsonb, 'asset_current', false, '10', 360),
  ('BA', 'default', '102', 'Rezervni dijelovi', '{"en":"Spare parts"}'::jsonb, 'asset_current', false, '10', 370),
  ('BA', 'default', '103', 'Auto gume i ambalaža', '{"en":"Tyres and packaging"}'::jsonb, 'asset_current', false, '10', 380),
  ('BA', 'default', '104', 'Alat i sitan inventar', '{"en":"Tools and low-value items"}'::jsonb, 'asset_current', false, '10', 390),
  ('BA', 'default', '11', 'Proizvodnja u toku, poluproizvodi i nedovršene usluge', '{"en":"Work in progress, semi-finished goods and unfinished services"}'::jsonb, 'asset_current', false, null, 400),
  ('BA', 'default', '110', 'Proizvodnja u toku — nedovršeni proizvodi', '{"en":"Work in progress — unfinished products"}'::jsonb, 'asset_current', false, '11', 410),
  ('BA', 'default', '111', 'Poluproizvodi i dijelovi vlastite proizvodnje', '{"en":"Semi-finished goods and own-produced parts"}'::jsonb, 'asset_current', false, '11', 420),
  ('BA', 'default', '12', 'Gotovi proizvodi', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, null, 430),
  ('BA', 'default', '120', 'Proizvodi u skladištu', '{"en":"Finished goods in warehouse"}'::jsonb, 'asset_current', false, '12', 440),
  ('BA', 'default', '121', 'Proizvodi u maloprodajnim objektima', '{"en":"Finished goods in retail outlets"}'::jsonb, 'asset_current', false, '12', 450),
  ('BA', 'default', '13', 'Roba', '{"en":"Goods for resale"}'::jsonb, 'asset_current', false, null, 460),
  ('BA', 'default', '130', 'Obračun troška nabavke robe', '{"en":"Purchase cost of goods clearing"}'::jsonb, 'asset_current', false, '13', 470),
  ('BA', 'default', '131', 'Nekretnine nabavljene radi dalje prodaje', '{"en":"Real estate acquired for resale"}'::jsonb, 'asset_current', false, '13', 480),
  ('BA', 'default', '132', 'Roba u prodaji na veliko', '{"en":"Goods for wholesale"}'::jsonb, 'asset_current', false, '13', 490),
  ('BA', 'default', '133', 'Roba u maloprodajnim objektima', '{"en":"Goods in retail outlets"}'::jsonb, 'asset_current', false, '13', 500),
  ('BA', 'default', '14', 'Stalna sredstva i sredstva obustavljenog poslovanja namijenjena prodaji', '{"en":"Non-current assets and disposal groups held for sale"}'::jsonb, 'asset_current', false, null, 510),
  ('BA', 'default', '141', 'Zemljište namijenjeno prodaji', '{"en":"Land held for sale"}'::jsonb, 'asset_current', false, '14', 520),
  ('BA', 'default', '142', 'Građevinski objekti namijenjeni prodaji', '{"en":"Buildings held for sale"}'::jsonb, 'asset_current', false, '14', 530),
  ('BA', 'default', '15', 'Dati avansi', '{"en":"Advances given"}'::jsonb, 'asset_prepayments', false, null, 540),
  ('BA', 'default', '150', 'Dati avansi za zalihe i usluge povezanim pravnim licima', '{"en":"Advances for inventories and services to related parties"}'::jsonb, 'asset_prepayments', false, '15', 550),
  ('BA', 'default', '151', 'Dati avansi za zalihe i usluge ostalim pravnim licima', '{"en":"Advances for inventories and services to other entities"}'::jsonb, 'asset_prepayments', false, '15', 560),
  ('BA', 'default', '20', 'Gotovina i gotovinski ekvivalenti', '{"en":"Cash and cash equivalents"}'::jsonb, 'asset_cash', false, null, 570),
  ('BA', 'default', '200', 'Transakcijski računi — domaća valuta', '{"en":"Current accounts — domestic currency"}'::jsonb, 'asset_cash', false, '20', 580),
  ('BA', 'default', '201', 'Transakcijski računi — strana valuta', '{"en":"Current accounts — foreign currency"}'::jsonb, 'asset_cash', false, '20', 590),
  ('BA', 'default', '203', 'Akreditivi — domaća valuta', '{"en":"Letters of credit — domestic currency"}'::jsonb, 'asset_cash', false, '20', 600),
  ('BA', 'default', '206', 'Blagajne — domaća valuta', '{"en":"Petty cash — domestic currency"}'::jsonb, 'asset_cash', false, '20', 610),
  ('BA', 'default', '21', 'Potraživanja od prodaje', '{"en":"Trade receivables"}'::jsonb, 'asset_receivable', true, null, 620),
  ('BA', 'default', '210', 'Kupci — povezana pravna lica', '{"en":"Customers — related parties"}'::jsonb, 'asset_receivable', true, '21', 630),
  ('BA', 'default', '211', 'Kupci u zemlji', '{"en":"Customers — domestic"}'::jsonb, 'asset_receivable', true, '21', 640),
  ('BA', 'default', '212', 'Kupci u inostranstvu', '{"en":"Customers — foreign"}'::jsonb, 'asset_receivable', true, '21', 650),
  ('BA', 'default', '219', 'Ispravka vrijednosti potraživanja od prodaje', '{"en":"Allowance for trade receivables"}'::jsonb, 'asset_receivable', true, '21', 660),
  ('BA', 'default', '22', 'Potraživanja iz specifičnih poslova', '{"en":"Receivables from specific transactions"}'::jsonb, 'asset_current', false, null, 670),
  ('BA', 'default', '220', 'Potraživanja od izvoznika', '{"en":"Receivables from exporters"}'::jsonb, 'asset_current', false, '22', 680),
  ('BA', 'default', '221', 'Potraživanja po osnovu uvoza za tuđi račun', '{"en":"Receivables on imports for a third party’s account"}'::jsonb, 'asset_current', false, '22', 690),
  ('BA', 'default', '23', 'Druga kratkoročna potraživanja', '{"en":"Other short-term receivables"}'::jsonb, 'asset_current', false, null, 700),
  ('BA', 'default', '230', 'Potraživanja za kamatu i dividendu', '{"en":"Interest and dividends receivable"}'::jsonb, 'asset_current', false, '23', 710),
  ('BA', 'default', '232', 'Potraživanja od zaposlenika', '{"en":"Receivables from employees"}'::jsonb, 'asset_current', false, '23', 720),
  ('BA', 'default', '233', 'Potraživanja od državnih organa i institucija', '{"en":"Receivables from government bodies and institutions"}'::jsonb, 'asset_current', false, '23', 730),
  ('BA', 'default', '234', 'Potraživanja za više plaćeni porez na dobit', '{"en":"Overpaid corporate income tax"}'::jsonb, 'asset_current', false, '23', 740),
  ('BA', 'default', '24', 'Kratkoročni finansijski plasmani', '{"en":"Short-term financial placements"}'::jsonb, 'asset_current', false, null, 750),
  ('BA', 'default', '240', 'Kratkoročni krediti dati povezanim pravnim licima', '{"en":"Short-term loans to related parties"}'::jsonb, 'asset_current', false, '24', 760),
  ('BA', 'default', '241', 'Kratkoročni krediti dati u zemlji', '{"en":"Short-term loans given domestically"}'::jsonb, 'asset_current', false, '24', 770),
  ('BA', 'default', '245', 'Finansijska sredstva namijenjena trgovanju', '{"en":"Financial assets held for trading"}'::jsonb, 'asset_current', false, '24', 780),
  ('BA', 'default', '27', 'Potraživanja za PDV — odbitni ulazni porez', '{"en":"VAT receivable — deductible input tax"}'::jsonb, 'asset_current', false, null, 790),
  ('BA', 'default', '270', 'PDV u primljenim fakturama', '{"en":"VAT on purchase invoices received"}'::jsonb, 'asset_current', false, '27', 800),
  ('BA', 'default', '271', 'PDV plaćen pri uvozu dobara', '{"en":"VAT paid on imports of goods"}'::jsonb, 'asset_current', false, '27', 810),
  ('BA', 'default', '272', 'PDV sadržan u datim avansima', '{"en":"VAT included in advances given"}'::jsonb, 'asset_current', false, '27', 820),
  ('BA', 'default', '273', 'PDV obračunat na usluge stranih lica', '{"en":"VAT self-assessed on services from foreign suppliers"}'::jsonb, 'asset_current', false, '27', 830),
  ('BA', 'default', '279', 'Potraživanja za razliku ulaznog poreza i obaveza za PDV', '{"en":"Net VAT settlement receivable (credit/refund position)"}'::jsonb, 'asset_current', true, '27', 840),
  ('BA', 'default', '28', 'Aktivna vremenska razgraničenja', '{"en":"Prepayments and accrued income"}'::jsonb, 'asset_prepayments', false, null, 850),
  ('BA', 'default', '280', 'Unaprijed plaćeni rashodi', '{"en":"Prepaid expenses"}'::jsonb, 'asset_prepayments', false, '28', 860),
  ('BA', 'default', '281', 'Potraživanja za nefakturisani prihod', '{"en":"Accrued income not yet invoiced"}'::jsonb, 'asset_prepayments', false, '28', 870),
  ('BA', 'default', '30', 'Osnovni kapital', '{"en":"Share capital"}'::jsonb, 'equity', false, null, 880),
  ('BA', 'default', '300', 'Dionički kapital', '{"en":"Share capital"}'::jsonb, 'equity', false, '30', 890),
  ('BA', 'default', '302', 'Udjeli članova društva sa ograničenom odgovornošću', '{"en":"Members’ interests in a limited liability company"}'::jsonb, 'equity', false, '30', 900),
  ('BA', 'default', '305', 'Državni kapital', '{"en":"State capital"}'::jsonb, 'equity', false, '30', 910),
  ('BA', 'default', '31', 'Upisani neuplaćeni kapital', '{"en":"Subscribed unpaid capital"}'::jsonb, 'equity', false, null, 920),
  ('BA', 'default', '310', 'Upisane neuplaćene dionice', '{"en":"Subscribed unpaid shares"}'::jsonb, 'equity', false, '31', 930),
  ('BA', 'default', '32', 'Rezerve', '{"en":"Reserves"}'::jsonb, 'equity', false, null, 940),
  ('BA', 'default', '321', 'Zakonske rezerve', '{"en":"Legal reserves"}'::jsonb, 'equity', false, '32', 950),
  ('BA', 'default', '322', 'Statutarne i druge rezerve', '{"en":"Statutory and other reserves"}'::jsonb, 'equity', false, '32', 960),
  ('BA', 'default', '33', 'Revalorizacijske rezerve i nerealizovani dobici i gubici', '{"en":"Revaluation reserves and unrealised gains and losses"}'::jsonb, 'equity', false, null, 970),
  ('BA', 'default', '330', 'Revalorizacijske rezerve', '{"en":"Revaluation reserves"}'::jsonb, 'equity', false, '33', 980),
  ('BA', 'default', '34', 'Neraspoređena dobit', '{"en":"Retained earnings"}'::jsonb, 'equity_retained', false, null, 990),
  ('BA', 'default', '340', 'Neraspoređena dobit ranijih godina', '{"en":"Retained earnings from previous years"}'::jsonb, 'equity_retained', false, '34', 1000),
  ('BA', 'default', '341', 'Neraspoređena dobit izvještajne godine', '{"en":"Retained earnings of the reporting year"}'::jsonb, 'equity_retained', false, '34', 1010),
  ('BA', 'default', '35', 'Gubitak do visine kapitala', '{"en":"Accumulated loss up to the amount of capital"}'::jsonb, 'equity_retained', false, null, 1020),
  ('BA', 'default', '350', 'Gubitak ranijih godina', '{"en":"Accumulated loss from previous years"}'::jsonb, 'equity_retained', false, '35', 1030),
  ('BA', 'default', '351', 'Gubitak izvještajne godine', '{"en":"Loss of the reporting year"}'::jsonb, 'equity_retained', false, '35', 1040),
  ('BA', 'default', '36', 'Otkupljene vlastite dionice i udjeli', '{"en":"Treasury shares and interests"}'::jsonb, 'equity', false, null, 1050),
  ('BA', 'default', '360', 'Otkupljene vlastite dionice i udjeli', '{"en":"Treasury shares and interests bought back"}'::jsonb, 'equity', false, '36', 1060),
  ('BA', 'default', '40', 'Dugoročna rezervisanja i odložene porezne obaveze', '{"en":"Long-term provisions and deferred tax liabilities"}'::jsonb, 'liability_non_current', false, null, 1070),
  ('BA', 'default', '400', 'Rezervisanja za troškove u garantnom roku', '{"en":"Provisions for warranty costs"}'::jsonb, 'liability_non_current', false, '40', 1080),
  ('BA', 'default', '404', 'Rezervisanja za naknade i beneficije zaposlenika', '{"en":"Provisions for employee benefits"}'::jsonb, 'liability_non_current', false, '40', 1090),
  ('BA', 'default', '408', 'Odložene porezne obaveze', '{"en":"Deferred tax liabilities"}'::jsonb, 'liability_non_current', false, '40', 1100),
  ('BA', 'default', '41', 'Dugoročne obaveze', '{"en":"Long-term liabilities"}'::jsonb, 'liability_non_current', false, null, 1110),
  ('BA', 'default', '410', 'Obaveze koje se mogu konvertirati u kapital', '{"en":"Liabilities convertible into capital"}'::jsonb, 'liability_non_current', false, '41', 1120),
  ('BA', 'default', '413', 'Dugoročni krediti uzeti u zemlji', '{"en":"Long-term loans taken domestically"}'::jsonb, 'liability_non_current', false, '41', 1130),
  ('BA', 'default', '414', 'Dugoročni krediti uzeti u inostranstvu', '{"en":"Long-term loans taken abroad"}'::jsonb, 'liability_non_current', false, '41', 1140),
  ('BA', 'default', '42', 'Kratkoročne finansijske obaveze', '{"en":"Short-term financial liabilities"}'::jsonb, 'liability_current', false, null, 1150),
  ('BA', 'default', '422', 'Kratkoročni krediti uzeti u zemlji', '{"en":"Short-term loans taken domestically"}'::jsonb, 'liability_current', false, '42', 1160),
  ('BA', 'default', '423', 'Kratkoročni krediti uzeti u inostranstvu', '{"en":"Short-term loans taken abroad"}'::jsonb, 'liability_current', false, '42', 1170),
  ('BA', 'default', '424', 'Kratkoročni dio dugoročnih kredita', '{"en":"Current portion of long-term loans"}'::jsonb, 'liability_current', false, '42', 1180),
  ('BA', 'default', '43', 'Obaveze iz poslovanja', '{"en":"Trade payables"}'::jsonb, 'liability_payable', true, null, 1190),
  ('BA', 'default', '430', 'Primljeni avansi, depoziti i kaucije', '{"en":"Advances, deposits and guarantees received"}'::jsonb, 'liability_payable', true, '43', 1200),
  ('BA', 'default', '431', 'Dobavljači — povezana pravna lica', '{"en":"Suppliers — related parties"}'::jsonb, 'liability_payable', true, '43', 1210),
  ('BA', 'default', '432', 'Dobavljači u zemlji', '{"en":"Suppliers — domestic"}'::jsonb, 'liability_payable', true, '43', 1220),
  ('BA', 'default', '433', 'Dobavljači u inostranstvu', '{"en":"Suppliers — foreign"}'::jsonb, 'liability_payable', true, '43', 1230),
  ('BA', 'default', '44', 'Obaveze iz specifičnih poslova', '{"en":"Liabilities from specific transactions"}'::jsonb, 'liability_current', false, null, 1240),
  ('BA', 'default', '440', 'Obaveze prema uvozniku', '{"en":"Payables to the importer of record"}'::jsonb, 'liability_current', false, '44', 1250),
  ('BA', 'default', '45', 'Obaveze po osnovu plaća, naknada i ostalih primanja zaposlenih', '{"en":"Liabilities for payroll and other employee benefits"}'::jsonb, 'liability_current', false, null, 1260),
  ('BA', 'default', '450', 'Obaveze za neto plaće i naknade plaća', '{"en":"Net salaries and wage compensation payable"}'::jsonb, 'liability_current', false, '45', 1270),
  ('BA', 'default', '451', 'Obaveze za porez i posebne dažbine na plaće', '{"en":"Payroll tax and special charges payable"}'::jsonb, 'liability_current', false, '45', 1280),
  ('BA', 'default', '452', 'Obaveze za doprinose u vezi plaća', '{"en":"Social contributions on payroll payable"}'::jsonb, 'liability_current', false, '45', 1290),
  ('BA', 'default', '46', 'Druge obaveze', '{"en":"Other liabilities"}'::jsonb, 'liability_current', false, null, 1300),
  ('BA', 'default', '460', 'Obaveze po osnovu kamata i troškova finansiranja', '{"en":"Interest and financing costs payable"}'::jsonb, 'liability_current', false, '46', 1310),
  ('BA', 'default', '461', 'Obaveze za dividende', '{"en":"Dividends payable"}'::jsonb, 'liability_current', false, '46', 1320),
  ('BA', 'default', '469', 'Ostale obaveze', '{"en":"Other liabilities"}'::jsonb, 'liability_current', false, '46', 1330),
  ('BA', 'default', '4699', 'Prijelazni račun (sredstva u iščekivanju razjašnjenja)', '{"en":"Suspense clearing account (amounts awaiting clarification)"}'::jsonb, 'liability_current', false, '469', 1340),
  ('BA', 'default', '47', 'Obaveze za PDV', '{"en":"VAT payable"}'::jsonb, 'liability_current', false, null, 1350),
  ('BA', 'default', '470', 'PDV po osnovu isporuka drugim obveznicima PDV-a', '{"en":"VAT on supplies to other VAT payers"}'::jsonb, 'liability_current', false, '47', 1360),
  ('BA', 'default', '471', 'PDV po primljenim avansima', '{"en":"VAT on advances received"}'::jsonb, 'liability_current', false, '47', 1370),
  ('BA', 'default', '474', 'PDV obračunat na usluge stranih lica', '{"en":"VAT self-assessed on services from foreign suppliers"}'::jsonb, 'liability_current', false, '47', 1380),
  ('BA', 'default', '479', 'Obaveze za razliku između obaveza za PDV i ulaznog poreza', '{"en":"Net VAT settlement payable"}'::jsonb, 'liability_current', true, '47', 1390),
  ('BA', 'default', '48', 'Obaveze za ostale poreze, doprinose i druge dažbine', '{"en":"Other taxes, contributions and charges payable"}'::jsonb, 'liability_current', false, null, 1400),
  ('BA', 'default', '480', 'Obaveze za akcize', '{"en":"Excise duties payable"}'::jsonb, 'liability_current', false, '48', 1410),
  ('BA', 'default', '481', 'Obaveze za porez na dobit', '{"en":"Corporate income tax payable"}'::jsonb, 'liability_current', false, '48', 1420),
  ('BA', 'default', '49', 'Pasivna vremenska razgraničenja', '{"en":"Accrued expenses and deferred income"}'::jsonb, 'liability_current', false, null, 1430),
  ('BA', 'default', '490', 'Unaprijed obračunati rashodi perioda', '{"en":"Accrued expenses of the period"}'::jsonb, 'liability_current', false, '49', 1440),
  ('BA', 'default', '491', 'Obračunati prihodi narednog perioda', '{"en":"Deferred income of the following period"}'::jsonb, 'liability_current', false, '49', 1450),
  ('BA', 'default', '50', 'Nabavna vrijednost prodate robe', '{"en":"Cost of goods sold"}'::jsonb, 'expense_direct_cost', false, null, 1460),
  ('BA', 'default', '500', 'Nabavna vrijednost prodate robe', '{"en":"Cost of goods sold"}'::jsonb, 'expense_direct_cost', false, '50', 1470),
  ('BA', 'default', '51', 'Materijalni troškovi', '{"en":"Cost of materials"}'::jsonb, 'expense_direct_cost', false, null, 1480),
  ('BA', 'default', '510', 'Nabavka sirovina, materijala, rezervnih dijelova i inventara', '{"en":"Purchases of raw materials, supplies, spare parts and inventory"}'::jsonb, 'expense_direct_cost', false, '51', 1490),
  ('BA', 'default', '511', 'Utrošene sirovine i materijal', '{"en":"Raw materials and supplies consumed"}'::jsonb, 'expense_direct_cost', false, '51', 1500),
  ('BA', 'default', '512', 'Utrošena energija i gorivo', '{"en":"Energy and fuel consumed"}'::jsonb, 'expense_direct_cost', false, '51', 1510),
  ('BA', 'default', '52', 'Troškovi plaća i ostalih primanja zaposlenih i drugih fizičkih lica', '{"en":"Payroll and other employee benefit costs"}'::jsonb, 'expense', false, null, 1520),
  ('BA', 'default', '520', 'Troškovi plaća', '{"en":"Salary costs"}'::jsonb, 'expense', false, '52', 1530),
  ('BA', 'default', '521', 'Troškovi naknada plaća', '{"en":"Wage compensation costs"}'::jsonb, 'expense', false, '52', 1540),
  ('BA', 'default', '523', 'Troškovi službenih putovanja zaposlenih', '{"en":"Employee business travel costs"}'::jsonb, 'expense', false, '52', 1550),
  ('BA', 'default', '53', 'Troškovi proizvodnih usluga', '{"en":"Cost of production services"}'::jsonb, 'expense', false, null, 1560),
  ('BA', 'default', '530', 'Troškovi usluga izrade i dorade učinaka', '{"en":"Costs of processing and finishing services"}'::jsonb, 'expense', false, '53', 1570),
  ('BA', 'default', '531', 'Troškovi transportnih usluga', '{"en":"Transport service costs"}'::jsonb, 'expense', false, '53', 1580),
  ('BA', 'default', '532', 'Troškovi usluga održavanja', '{"en":"Maintenance service costs"}'::jsonb, 'expense', false, '53', 1590),
  ('BA', 'default', '533', 'Troškovi zakupa', '{"en":"Rent costs"}'::jsonb, 'expense', false, '53', 1600),
  ('BA', 'default', '535', 'Troškovi reklame i sponzorstava', '{"en":"Advertising and sponsorship costs"}'::jsonb, 'expense', false, '53', 1610),
  ('BA', 'default', '54', 'Amortizacija i troškovi rezervisanja', '{"en":"Depreciation and provisioning costs"}'::jsonb, 'expense_depreciation', false, null, 1620),
  ('BA', 'default', '540', 'Amortizacija nematerijalnih i materijalnih stalnih sredstava koja se amortizuju', '{"en":"Depreciation and amortisation of depreciable fixed assets"}'::jsonb, 'expense_depreciation', false, '54', 1630),
  ('BA', 'default', '543', 'Troškovi rezervisanja za troškove u garantnom roku', '{"en":"Costs of provisions for warranty obligations"}'::jsonb, 'expense', false, '54', 1640),
  ('BA', 'default', '55', 'Nematerijalni troškovi', '{"en":"Other intangible costs"}'::jsonb, 'expense', false, null, 1650),
  ('BA', 'default', '550', 'Troškovi neproizvodnih usluga', '{"en":"Non-production service costs"}'::jsonb, 'expense', false, '55', 1660),
  ('BA', 'default', '551', 'Troškovi reprezentacije', '{"en":"Entertainment costs"}'::jsonb, 'expense', false, '55', 1670),
  ('BA', 'default', '552', 'Troškovi premija osiguranja', '{"en":"Insurance premium costs"}'::jsonb, 'expense', false, '55', 1680),
  ('BA', 'default', '553', 'Troškovi platnog prometa', '{"en":"Payment transaction costs"}'::jsonb, 'expense', false, '55', 1690),
  ('BA', 'default', '554', 'Troškovi poštanskih i telekomunikacionih usluga', '{"en":"Postal and telecommunications costs"}'::jsonb, 'expense', false, '55', 1700),
  ('BA', 'default', '555', 'Troškovi poreza, naknada, taksi i drugih dažbina', '{"en":"Taxes, fees and other charges"}'::jsonb, 'expense', false, '55', 1710),
  ('BA', 'default', '556', 'Troškovi članskih doprinosa', '{"en":"Membership contribution costs"}'::jsonb, 'expense', false, '55', 1720),
  ('BA', 'default', '559', 'Ostali nematerijalni troškovi', '{"en":"Other intangible costs"}'::jsonb, 'expense', false, '55', 1730),
  ('BA', 'default', '5599', 'Troškovi zaokruživanja', '{"en":"Rounding costs"}'::jsonb, 'expense', false, '559', 1740),
  ('BA', 'default', '56', 'Finansijski rashodi', '{"en":"Finance costs"}'::jsonb, 'expense', false, null, 1750),
  ('BA', 'default', '560', 'Finansijski rashodi iz odnosa s povezanim pravnim licima', '{"en":"Finance costs on related-party transactions"}'::jsonb, 'expense', false, '56', 1760),
  ('BA', 'default', '561', 'Rashodi kamata', '{"en":"Interest expense"}'::jsonb, 'expense', false, '56', 1770),
  ('BA', 'default', '562', 'Negativne kursne razlike', '{"en":"Negative exchange rate differences"}'::jsonb, 'expense', false, '56', 1780),
  ('BA', 'default', '57', 'Ostali rashodi i gubici', '{"en":"Other expenses and losses"}'::jsonb, 'expense', false, null, 1790),
  ('BA', 'default', '570', 'Gubici od prodaje i rashodovanja stalnih sredstava', '{"en":"Losses on disposal of fixed assets"}'::jsonb, 'expense', false, '57', 1800),
  ('BA', 'default', '576', 'Manjkovi', '{"en":"Shortages"}'::jsonb, 'expense', false, '57', 1810),
  ('BA', 'default', '58', 'Rashodi/gubici iz osnova umanjenja vrijednosti sredstava', '{"en":"Impairment losses"}'::jsonb, 'expense', false, null, 1820),
  ('BA', 'default', '580', 'Umanjenje vrijednosti nematerijalnih sredstava', '{"en":"Impairment of intangible assets"}'::jsonb, 'expense', false, '58', 1830),
  ('BA', 'default', '581', 'Umanjenje vrijednosti materijalnih stalnih sredstava', '{"en":"Impairment of tangible fixed assets"}'::jsonb, 'expense', false, '58', 1840),
  ('BA', 'default', '585', 'Umanjenje vrijednosti zaliha', '{"en":"Impairment of inventories"}'::jsonb, 'expense', false, '58', 1850),
  ('BA', 'default', '59', 'Efekti promjena računovodstvenih politika i ispravki grešaka', '{"en":"Effects of changes in accounting policy"}'::jsonb, 'expense', false, null, 1860),
  ('BA', 'default', '590', 'Rashodi iz osnova promjene računovodstvenih politika', '{"en":"Expenses from changes in accounting policy"}'::jsonb, 'expense', false, '59', 1870),
  ('BA', 'default', '60', 'Prihodi od prodaje robe', '{"en":"Revenue from sale of goods"}'::jsonb, 'income', false, null, 1880),
  ('BA', 'default', '600', 'Prihodi od prodaje robe povezanim pravnim licima', '{"en":"Revenue from sale of goods to related parties"}'::jsonb, 'income', false, '60', 1890),
  ('BA', 'default', '601', 'Prihodi od prodaje robe na domaćem tržištu', '{"en":"Revenue from sale of goods — domestic market"}'::jsonb, 'income', false, '60', 1900),
  ('BA', 'default', '602', 'Prihodi od prodaje robe na stranom tržištu', '{"en":"Revenue from sale of goods — foreign market"}'::jsonb, 'income', false, '60', 1910),
  ('BA', 'default', '61', 'Prihodi od prodaje učinaka', '{"en":"Revenue from sale of products and services"}'::jsonb, 'income', false, null, 1920),
  ('BA', 'default', '610', 'Prihodi od prodaje učinaka povezanim pravnim licima', '{"en":"Revenue from sale of products/services to related parties"}'::jsonb, 'income', false, '61', 1930),
  ('BA', 'default', '611', 'Prihodi od prodaje učinaka na domaćem tržištu', '{"en":"Revenue from sale of products/services — domestic market"}'::jsonb, 'income', false, '61', 1940),
  ('BA', 'default', '612', 'Prihodi od prodaje učinaka na stranom tržištu', '{"en":"Revenue from sale of products/services — foreign market"}'::jsonb, 'income', false, '61', 1950),
  ('BA', 'default', '62', 'Prihodi od aktiviranja ili potrošnje robe i učinaka', '{"en":"Revenue from own consumption of goods and products"}'::jsonb, 'income', false, null, 1960),
  ('BA', 'default', '620', 'Prihodi od aktiviranja ili potrošnje robe', '{"en":"Revenue from own use or consumption of goods"}'::jsonb, 'income', false, '62', 1970),
  ('BA', 'default', '64', 'Promjena vrijednosti specifičnih stalnih sredstava', '{"en":"Change in value of specific fixed assets"}'::jsonb, 'income_other', false, null, 1980),
  ('BA', 'default', '640', 'Povećanje vrijednosti investicijskih nekretnina koje se ne amortizuju', '{"en":"Increase in value of non-depreciated investment property"}'::jsonb, 'income_other', false, '64', 1990),
  ('BA', 'default', '65', 'Ostali poslovni prihodi', '{"en":"Other operating income"}'::jsonb, 'income_other', false, null, 2000),
  ('BA', 'default', '650', 'Prihodi od premija, subvencija, poticaja i sl.', '{"en":"Income from premiums, subsidies and incentives"}'::jsonb, 'income_other', false, '65', 2010),
  ('BA', 'default', '651', 'Prihodi od zakupa', '{"en":"Rental income"}'::jsonb, 'income_other', false, '65', 2020),
  ('BA', 'default', '652', 'Prihodi od donacija', '{"en":"Income from donations"}'::jsonb, 'income_other', false, '65', 2030),
  ('BA', 'default', '66', 'Finansijski prihodi', '{"en":"Finance income"}'::jsonb, 'income_other', false, null, 2040),
  ('BA', 'default', '660', 'Finansijski prihodi od povezanih pravnih lica', '{"en":"Finance income from related parties"}'::jsonb, 'income_other', false, '66', 2050),
  ('BA', 'default', '661', 'Prihodi od kamata', '{"en":"Interest income"}'::jsonb, 'income_other', false, '66', 2060),
  ('BA', 'default', '662', 'Pozitivne kursne razlike', '{"en":"Positive exchange rate differences"}'::jsonb, 'income_other', false, '66', 2070),
  ('BA', 'default', '67', 'Ostali prihodi i dobici', '{"en":"Other income and gains"}'::jsonb, 'income_other', false, null, 2080),
  ('BA', 'default', '670', 'Dobici od prodaje nematerijalnih i materijalnih stalnih sredstava', '{"en":"Gains on disposal of fixed assets"}'::jsonb, 'income_other', false, '67', 2090),
  ('BA', 'default', '676', 'Viškovi', '{"en":"Surpluses"}'::jsonb, 'income_other', false, '67', 2100),
  ('BA', 'default', '68', 'Prihodi/dobici iz osnova usklađivanja vrijednosti sredstava', '{"en":"Income from adjustment of asset values"}'::jsonb, 'income_other', false, null, 2110),
  ('BA', 'default', '680', 'Prihodi od usklađivanja vrijednosti nematerijalnih sredstava', '{"en":"Income from adjustment of intangible asset values"}'::jsonb, 'income_other', false, '68', 2120),
  ('BA', 'default', '69', 'Efekti promjena računovodstvenih politika i prihoda', '{"en":"Effects of changes in accounting policy (income)"}'::jsonb, 'income_other', false, null, 2130),
  ('BA', 'default', '690', 'Prihodi iz osnova promjene računovodstvenih politika', '{"en":"Income from changes in accounting policy"}'::jsonb, 'income_other', false, '69', 2140)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('BA', 'BNK', 'Dnevnik banke', '{"en":"Bank journal"}'::jsonb, 'bank', 30),
  ('BA', 'CSH', 'Dnevnik blagajne', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('BA', 'GEN', 'Opći dnevnik', '{"en":"General journal"}'::jsonb, 'general', 50),
  ('BA', 'OPN', 'Dnevnik otvaranja', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('BA', 'PUR', 'Dnevnik nabavke', '{"en":"Purchase journal"}'::jsonb, 'purchase', 20),
  ('BA', 'SAL', 'Dnevnik prodaje', '{"en":"Sales journal"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('BA', 'BA-P-17', 'PDV 17 % — nabavke od registrovanih obveznika PDV-a u BiH (kupovina)', '{"en":"VAT 17% — purchases from registered VAT payers in Bosnia and Herzegovina"}'::jsonb, null, 'percent', 17, 'purchase', 'domestic', date '2006-01-01', null, 'Zakon o porezu na dodanu vrijednost, član 23 (standardna stopa 17 %) u vezi s članom 32 — poreski obveznik ima pravo odbiti PDV koji je obavezan platiti ili ga je platio na nabavku dobara ili usluga od drugog poreskog obveznika, ako ta dobra ili usluge koristi za promet dobara i usluga koji podliježe PDV-u.', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('BA', 'BA-P-IMPORT', 'PDV 17 % — uvoz dobara u Bosnu i Hercegovinu (kupovina)', '{"en":"VAT 17% — import of goods into Bosnia and Herzegovina"}'::jsonb, null, 'percent', 17, 'purchase', 'import', date '2006-01-01', null, 'Zakon o porezu na dodanu vrijednost, član 23 (standardna stopa 17 %) u vezi s članom 21 (poreska osnovica pri uvozu dobara) — PDV na uvoz obračunava i naplaćuje Uprava za indirektno oporezivanje po carinskim propisima, a obveznik ga odbija kao ulazni porez u skladu s članom 32, stav 8, tačka 2 Zakona.', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('BA', 'BA-S-17', 'PDV 17 % — promet dobara i usluga na teritoriji BiH (prodaja)', '{"en":"VAT 17% — sale of goods and services in Bosnia and Herzegovina"}'::jsonb, null, 'percent', 17, 'sale', 'domestic', date '2006-01-01', null, 'Zakon o porezu na dodanu vrijednost ("Službeni glasnik BiH", br. 9/05, 35/05, 100/08, 33/17 i 46/23), član 23 — standardna stopa PDV-a na oporezivi promet dobara i usluga i uvoz dobara u Bosnu i Hercegovinu iznosi 17 %. Ovo je jedina pozitivna stopa koju Zakon poznaje: nema snižene stope.', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('BA', 'BA-S-EXEMPT-EDU', 'Oslobođeno od PDV-a — usluge obrazovanja (prodaja)', '{"en":"Exempt from VAT — education services"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2006-01-01', null, 'Zakon o porezu na dodanu vrijednost, član 24, stav 1, tačka 4 — od PDV-a su oslobođene usluge obrazovanja (predškolsko, osnovno, srednje obrazovanje, obrazovanje u okviru daljnjeg obrazovanja i univerziteta), kao i promet dobara i usluga usko povezanih s tim djelatnostima, ako se te djelatnosti obavljaju u skladu s propisima koji uređuju tu oblast.', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null),
  ('BA', 'BA-S-EXPORT', 'PDV 0 % — izvoz dobara iz Bosne i Hercegovine (prodaja)', '{"en":"VAT 0% — export of goods from Bosnia and Herzegovina"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2006-01-01', null, 'Zakon o porezu na dodanu vrijednost, član 27, stav 1, tačka 1 — oslobođen je (oporezuje se po nultoj stopi) izvoz dobara iz Bosne i Hercegovine od strane ili u ime prodavca.', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-law', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('BA-P-17', 'invoice', 'base', 100, null, '21', array['21']::text[], 100, 'BA-PDV', 10),
    ('BA-P-17', 'invoice', 'tax', 100, '270', '41', array['41']::text[], 100, 'BA-PDV', 20),
    ('BA-P-17', 'credit_note', 'base', 100, null, '21', array['21']::text[], -100, 'BA-PDV', 10),
    ('BA-P-17', 'credit_note', 'tax', 100, '270', '41', array['41']::text[], -100, 'BA-PDV', 20),
    ('BA-P-IMPORT', 'invoice', 'base', 100, null, '22', array['22']::text[], 100, 'BA-PDV', 10),
    ('BA-P-IMPORT', 'invoice', 'tax', 100, '271', '42', array['42']::text[], 100, 'BA-PDV', 20),
    ('BA-P-IMPORT', 'credit_note', 'base', 100, null, '22', array['22']::text[], -100, 'BA-PDV', 10),
    ('BA-P-IMPORT', 'credit_note', 'tax', 100, '271', '42', array['42']::text[], -100, 'BA-PDV', 20),
    ('BA-S-17', 'invoice', 'base', 100, null, '11', array['11']::text[], 100, 'BA-PDV', 10),
    ('BA-S-17', 'invoice', 'tax', 100, '470', '51', array['51']::text[], 100, 'BA-PDV', 20),
    ('BA-S-17', 'credit_note', 'base', 100, null, '11', array['11']::text[], -100, 'BA-PDV', 10),
    ('BA-S-17', 'credit_note', 'tax', 100, '470', '51', array['51']::text[], -100, 'BA-PDV', 20),
    ('BA-S-EXEMPT-EDU', 'invoice', 'base', 100, null, '13', array['13']::text[], 100, 'BA-PDV', 10),
    ('BA-S-EXEMPT-EDU', 'credit_note', 'base', 100, null, '13', array['13']::text[], -100, 'BA-PDV', 10),
    ('BA-S-EXPORT', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'BA-PDV', 10),
    ('BA-S-EXPORT', 'credit_note', 'base', 100, null, '12', array['12']::text[], -100, 'BA-PDV', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'BA' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('BA', 'BA-PDV', 'Prijava poreza na dodanu vrijednost (Obrazac P PDV)', array['month']::declaration_period[], 'month'::declaration_period, date '2006-01-01', null, 'Zakon o porezu na dodanu vrijednost ("Službeni glasnik BiH", br. 9/05, 35/05, 100/08, 33/17 i 46/23), član 38 — poreski period za koji se obračunava PDV je jedan kalendarski mjesec — i Pravilnik o primjeni Zakona o porezu na dodanu vrijednost, koji propisuje Obrazac P PDV. Ovaj paket transcribuje dio I (Isporuke i nabavke) i dio II (Izlazni/Ulazni PDV) obrasca, koje njegovi porezi dosežu; dio III (Podaci o krajnjoj potrošnji, kutije 32-34 — raspodjela prometa fizičkim licima po entitetima FBiH/RS/Brčko distrikt) nije transkribovan — vidjeti README.md.', true,'day_of_month_after_period'::filing_deadline_rule, 10, null, 'Zakon o porezu na dodanu vrijednost, član 39, stav 2 — poreski obveznik podnosi prijavu Upravi za indirektno oporezivanje do 10-og u mjesecu po isteku poreskog perioda.', 'vat-law', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('BA', 'BA-PDV', '11', 'base', 'Isporuke (uključujući i one u vanposlovne svrhe), osim onih u poljima 12 i 13 — vrijednost bez PDV-a', '{"en":"Supplies (including for non-business purposes), other than fields 12 and 13 — value excluding VAT"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio I, polje 11.', 'vat-form'),
  ('BA', 'BA-PDV', '12', 'base', 'Vrijednost izvoza — vrijednost bez PDV-a', '{"en":"Value of exports — value excluding VAT"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio I, polje 12; Zakon o porezu na dodanu vrijednost, član 27.', 'vat-form'),
  ('BA', 'BA-PDV', '13', 'base', 'Isporuke oslobođene plaćanja PDV-a — vrijednost bez PDV-a', '{"en":"Supplies exempt from VAT — value excluding VAT"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio I, polje 13; Zakon o porezu na dodanu vrijednost, čl. 24 i 25.', 'vat-form'),
  ('BA', 'BA-PDV', '21', 'base', 'Sve nabavke osim onih u poljima 22 i 23 — vrijednost bez PDV-a', '{"en":"All purchases other than fields 22 and 23 — value excluding VAT"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio I, polje 21.', 'vat-form'),
  ('BA', 'BA-PDV', '22', 'base', 'Vrijednost uvoza — vrijednost bez PDV-a', '{"en":"Value of imports — value excluding VAT"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio I, polje 22.', 'vat-form'),
  ('BA', 'BA-PDV', '23', 'base', 'Vrijednost nabavke od poljoprivrednika — vrijednost bez PDV-a', '{"en":"Value of purchases from farmers — value excluding VAT"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio I, polje 23; Zakon o porezu na dodanu vrijednost, član 45 (paušalna naknada). Nijedan porez ovog paketa ne postira u ovu kutiju — vidjeti README.md.', 'vat-form'),
  ('BA', 'BA-PDV', '41', 'tax', 'PDV obračunat na ulaze (dobra i usluge) od registrovanih obveznika PDV-a, osim iznosa u poljima 42 i 43', '{"en":"VAT calculated on purchases (goods and services) from registered VAT payers, other than fields 42 and 43"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio II, polje 41.', 'vat-form'),
  ('BA', 'BA-PDV', '42', 'tax', 'PDV na uvoz', '{"en":"VAT on imports"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio II, polje 42.', 'vat-form'),
  ('BA', 'BA-PDV', '43', 'tax', 'Paušalna naknada za poljoprivrednike', '{"en":"Flat-rate compensation for farmers"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio II, polje 43; Zakon o porezu na dodanu vrijednost, član 45. Nijedan porez ovog paketa ne postira u ovu kutiju — vidjeti README.md.', 'vat-form'),
  ('BA', 'BA-PDV', '51', 'tax', 'PDV obračunat na izlaze (dobra i usluge)', '{"en":"VAT calculated on supplies (goods and services)"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio II, polje 51.', 'vat-form'),
  ('BA', 'BA-PDV', '61', 'total', 'Ulazni PDV (ukupno)', '{"en":"Input VAT (total)"}'::jsonb, 110, null, array['41', '42', '43']::text[], '{}'::text[], null, null, false, false, null, 'Obrazac P PDV, dio II, polje 61 — zbir polja 41, 42 i 43.', 'vat-form'),
  ('BA', 'BA-PDV', '71', 'total', 'Iznos PDV-a za uplatu/povrat (razlika polja 51 i 61)', '{"en":"Amount of VAT payable/refundable (difference between fields 51 and 61)"}'::jsonb, 120, null, array['51']::text[], array['61']::text[], null, null, false, false, null, 'Obrazac P PDV, dio II, polje 71; Zakon o porezu na dodanu vrijednost, član 52 — ako je iznos ulaznog poreza veći od iznosa izlaznog poreza, poreski obveznik ima pravo na povrat razlike ili na zadržavanje poreskog kredita. Polje se ne ograničava na nulu: negativna vrijednost je iznos koji se vraća ili prenosi kao poreski kredit.', 'vat-law')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('BA-FBIH-BS', 'BA', 'default', 'Bilans stanja — Izvještaj o finansijskom položaju', 'balance_sheet', 'MRS/MSFI za MSP (FBiH)', date '2022-01-01', null, 'Pravilnik o sadržaju i formi obrazaca finansijskih izvještaja za privredna društva ("Službene novine Federacije BiH", broj 82/10), Prilog 1 — Bilans stanja, čije su pozicije (A-E, rimski i arapski podnaslovi) preuzete od reda do reda; naslijedio ga je od 01.01.2022. istoimeni obrazac uz Pravilnik o kontnom okviru i sadržaju konta za privredna društva ("Službene novine Federacije BiH", broj 81/21), čiji puni tekst ovaj paket nije mogao strojno pročitati. Ovaj paket transkribuje strukturu i nazive pozicija onako kako ih nosi Prilog 1 Pravilnika 82/10 (grupe konta po pozicijama), a ne doslovne AOP oznake obrasca 81/21, koje bi trebalo provjeriti prije podnošenja stvarnog izvještaja — vidjeti README.md.', 'fs-2010'),
  ('BA-FBIH-IS', 'BA', 'default', 'Bilans uspjeha — Izvještaj o ukupnom rezultatu za period', 'income_statement', 'MRS/MSFI za MSP (FBiH)', date '2022-01-01', null, 'Pravilnik o sadržaju i formi obrazaca finansijskih izvještaja za privredna društva ("Službene novine Federacije BiH", broj 82/10), Prilog 2 — Bilans uspjeha, čije su pozicije preuzete od reda do reda; naslijedio ga je od 01.01.2022. istoimeni obrazac uz Pravilnik o kontnom okviru i sadržaju konta za privredna društva ("Službene novine Federacije BiH", broj 81/21), čiji puni tekst ovaj paket nije mogao strojno pročitati. Ovaj paket ne razlikuje, kao službeni obrazac, poseban red za dobit i poseban red za gubitak istog međuzbira: svaki takav red ovdje je jedan red sa predznakom (pozitivna vrijednost — dobit, negativna — gubitak). Porez na dobit nije uključen — vidjeti README.md.', 'fs-2010')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('BA-FBIH-BS', 'R00', null, 'UKUPNO AKTIVA', '{"en":"TOTAL ASSETS"}'::jsonb, 10, 1, true, array['R10', 'R20']::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R10', null, 'A) STALNA SREDSTVA I DUGOROČNI PLASMANI', '{"en":"A) FIXED ASSETS AND LONG-TERM PLACEMENTS"}'::jsonb, 20, 1, true, array['R11', 'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18']::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R11', null, 'I. Nematerijalna sredstva', '{"en":"I. Intangible assets"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R12', null, 'II. Nekretnine, postrojenja i oprema', '{"en":"II. Property, plant and equipment"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R13', null, 'III. Investicijske nekretnine', '{"en":"III. Investment property"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R14', null, 'IV. Biološka sredstva', '{"en":"IV. Biological assets"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R15', null, 'V. Ostala (specifična) stalna materijalna sredstva', '{"en":"V. Other (specific) tangible fixed assets"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R16', null, 'VI. Dugoročni finansijski plasmani', '{"en":"VI. Long-term financial investments"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R17', null, 'VII. Druga dugoročna potraživanja', '{"en":"VII. Other long-term receivables"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R18', null, 'VIII. Odložena porezna sredstva i dugoročna razgraničenja', '{"en":"VIII. Deferred tax assets and long-term accruals"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R20', null, 'B) TEKUĆA SREDSTVA', '{"en":"B) CURRENT ASSETS"}'::jsonb, 110, 1, true, array['R21', 'R22', 'R23', 'R24']::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R21', null, 'I. Zalihe i sredstva namijenjena prodaji', '{"en":"I. Inventories and assets held for sale"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R22', null, 'II. Dati avansi', '{"en":"II. Advances given"}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R23', null, 'III. Kratkoročna potraživanja i kratkoročni plasmani', '{"en":"III. Short-term receivables and short-term placements"}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R24', null, 'IV. Gotovina i gotovinski ekvivalenti', '{"en":"IV. Cash and cash equivalents"}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R99', null, 'UKUPNO PASIVA', '{"en":"TOTAL EQUITY AND LIABILITIES"}'::jsonb, 160, 1, true, array['R30', 'R40', 'R50']::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R30', null, 'C) KAPITAL', '{"en":"C) EQUITY"}'::jsonb, 170, 1, true, array['R31', 'R32', 'R33']::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R31', null, 'I. Osnovni i upisani neuplaćeni kapital', '{"en":"I. Share capital and subscribed unpaid capital"}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R32', null, 'II. Rezerve i revalorizacijske rezerve', '{"en":"II. Reserves and revaluation reserves"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R33', null, 'III. Neraspoređena dobit, gubitak i otkupljene vlastite dionice', '{"en":"III. Retained earnings, accumulated loss and treasury shares"}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R40', null, 'D) DUGOROČNA REZERVISANJA I DUGOROČNE OBAVEZE', '{"en":"D) LONG-TERM PROVISIONS AND LONG-TERM LIABILITIES"}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-BS', 'R50', null, 'E) KRATKOROČNE OBAVEZE I RAZGRANIČENJA', '{"en":"E) SHORT-TERM LIABILITIES AND ACCRUALS"}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R10', null, 'I. Poslovni prihodi', '{"en":"I. Operating income"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R20', null, 'II. Poslovni rashodi', '{"en":"II. Operating expenses"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R30', null, 'Poslovni dobitak (gubitak)', '{"en":"Operating profit (loss)"}'::jsonb, 30, 1, true, array['R10']::text[], array['R20']::text[], null, null, null),
  ('BA-FBIH-IS', 'R40', null, 'III. Finansijski prihodi', '{"en":"III. Finance income"}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R50', null, 'IV. Finansijski rashodi', '{"en":"IV. Finance costs"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R60', null, 'Dobitak (gubitak) iz finansiranja', '{"en":"Profit (loss) from financing"}'::jsonb, 60, 1, true, array['R40']::text[], array['R50']::text[], null, null, null),
  ('BA-FBIH-IS', 'R70', null, 'V. Ostali prihodi', '{"en":"V. Other income"}'::jsonb, 70, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R80', null, 'VI. Ostali rashodi', '{"en":"VI. Other expenses"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('BA-FBIH-IS', 'R90', null, 'Ostali dobitak (gubitak)', '{"en":"Other profit (loss)"}'::jsonb, 90, 1, true, array['R70']::text[], array['R80']::text[], null, null, null),
  ('BA-FBIH-IS', 'R99', null, 'NETO DOBITAK (GUBITAK) PERIODA', '{"en":"NET PROFIT (LOSS) FOR THE PERIOD"}'::jsonb, 100, 1, true, array['R30', 'R60', 'R90']::text[], '{}'::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('BA-FBIH-BS', 'R11', 10, 'code_prefix', '01', null, null, 'any'),
    ('BA-FBIH-BS', 'R12', 10, 'code_prefix', '02', null, null, 'any'),
    ('BA-FBIH-BS', 'R13', 10, 'code_prefix', '03', null, null, 'any'),
    ('BA-FBIH-BS', 'R14', 10, 'code_prefix', '04', null, null, 'any'),
    ('BA-FBIH-BS', 'R15', 10, 'code_prefix', '05', null, null, 'any'),
    ('BA-FBIH-BS', 'R16', 10, 'code_prefix', '06', null, null, 'any'),
    ('BA-FBIH-BS', 'R17', 10, 'code_prefix', '07', null, null, 'any'),
    ('BA-FBIH-BS', 'R18', 10, 'code_prefix', '09', null, null, 'any'),
    ('BA-FBIH-BS', 'R21', 10, 'code_range', '10', '14', null, 'any'),
    ('BA-FBIH-BS', 'R22', 10, 'code_prefix', '15', null, null, 'any'),
    ('BA-FBIH-BS', 'R23', 10, 'code_prefix', '21', null, null, 'any'),
    ('BA-FBIH-BS', 'R23', 20, 'code_prefix', '22', null, null, 'any'),
    ('BA-FBIH-BS', 'R23', 30, 'code_prefix', '23', null, null, 'any'),
    ('BA-FBIH-BS', 'R23', 40, 'code_prefix', '24', null, null, 'any'),
    ('BA-FBIH-BS', 'R23', 50, 'code_prefix', '27', null, null, 'any'),
    ('BA-FBIH-BS', 'R23', 60, 'code_prefix', '28', null, null, 'any'),
    ('BA-FBIH-BS', 'R24', 10, 'code_prefix', '20', null, null, 'any'),
    ('BA-FBIH-BS', 'R31', 10, 'code_prefix', '30', null, null, 'any'),
    ('BA-FBIH-BS', 'R31', 20, 'code_prefix', '31', null, null, 'any'),
    ('BA-FBIH-BS', 'R32', 10, 'code_prefix', '32', null, null, 'any'),
    ('BA-FBIH-BS', 'R32', 20, 'code_prefix', '33', null, null, 'any'),
    ('BA-FBIH-BS', 'R33', 10, 'code_prefix', '34', null, null, 'any'),
    ('BA-FBIH-BS', 'R33', 20, 'code_prefix', '35', null, null, 'any'),
    ('BA-FBIH-BS', 'R33', 30, 'code_prefix', '36', null, null, 'any'),
    ('BA-FBIH-BS', 'R40', 10, 'code_prefix', '40', null, null, 'any'),
    ('BA-FBIH-BS', 'R40', 20, 'code_prefix', '41', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 10, 'code_prefix', '42', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 20, 'code_prefix', '43', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 30, 'code_prefix', '44', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 40, 'code_prefix', '45', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 50, 'code_prefix', '46', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 60, 'code_prefix', '47', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 70, 'code_prefix', '48', null, null, 'any'),
    ('BA-FBIH-BS', 'R50', 80, 'code_prefix', '49', null, null, 'any'),
    ('BA-FBIH-IS', 'R10', 10, 'code_prefix', '60', null, null, 'any'),
    ('BA-FBIH-IS', 'R10', 20, 'code_prefix', '61', null, null, 'any'),
    ('BA-FBIH-IS', 'R10', 30, 'code_prefix', '62', null, null, 'any'),
    ('BA-FBIH-IS', 'R10', 40, 'code_prefix', '64', null, null, 'any'),
    ('BA-FBIH-IS', 'R10', 50, 'code_prefix', '65', null, null, 'any'),
    ('BA-FBIH-IS', 'R20', 10, 'code_prefix', '50', null, null, 'any'),
    ('BA-FBIH-IS', 'R20', 20, 'code_prefix', '51', null, null, 'any'),
    ('BA-FBIH-IS', 'R20', 30, 'code_prefix', '52', null, null, 'any'),
    ('BA-FBIH-IS', 'R20', 40, 'code_prefix', '53', null, null, 'any'),
    ('BA-FBIH-IS', 'R20', 50, 'code_prefix', '54', null, null, 'any'),
    ('BA-FBIH-IS', 'R20', 60, 'code_prefix', '55', null, null, 'any'),
    ('BA-FBIH-IS', 'R40', 10, 'code_prefix', '66', null, null, 'any'),
    ('BA-FBIH-IS', 'R50', 10, 'code_prefix', '56', null, null, 'any'),
    ('BA-FBIH-IS', 'R70', 10, 'code_prefix', '67', null, null, 'any'),
    ('BA-FBIH-IS', 'R70', 20, 'code_prefix', '68', null, null, 'any'),
    ('BA-FBIH-IS', 'R70', 30, 'code_prefix', '69', null, null, 'any'),
    ('BA-FBIH-IS', 'R80', 10, 'code_prefix', '57', null, null, 'any'),
    ('BA-FBIH-IS', 'R80', 20, 'code_prefix', '58', null, null, 'any'),
    ('BA-FBIH-IS', 'R80', 30, 'code_prefix', '59', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('BA', 'Bosna i Hercegovina', '{"en":"Bosnia and Herzegovina"}'::jsonb, array['bs', 'en']::text[], 'BAM', '211', '432', '4699', '5599', '340', '611', '500', '200', '206', 'SAL', 'PUR', 'GEN', 'bs', 'retained_earnings', null, null, null, 'OPN', 'half_up', default, '662', '562', null, null, null, null, '479', '279', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{NNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Zakon o porezu na dodanu vrijednost, član 55 — poreski obveznik je obavezan izdati fakturu ili drugi dokument koji služi kao faktura za svaki promet dobara i usluga, osim za promet oslobođen po čl. 24 i 25. Zakon ne propisuje jedinstven oblik broja fakture; format ovog paketa je primjer sekvencijalnog numerisanja, a ne jedina zakonom nametnuta forma.',
  numbering_source_key          = 'vat-law',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'earliest_of_delivery_or_payment',
  tax_point_legal_reference     = 'Zakon o porezu na dodanu vrijednost, član 17, stav 1 — poreska obaveza nastaje u trenutku koji nastupi najranije od sljedećih događaja: isporuke dobara ili izvršenja usluga, izdavanja fakture u skladu sa Zakonom, plaćanja ili djelimičnog plaćanja prije izdavanja fakture, odnosno nastanka obaveze plaćanja carinskog duga pri uvozu. Ovo je pravilo ''najranijeg od tri događaja'', gdje je izdavanje fakture samostalan okidač jednako kao isporuka i plaćanje — nijedna od tih triju činjenica nema prednost po pravilu formata (za razliku od Belgije ili Luksemburga, gdje je datum isporuke princip a datum fakture izuzetak). `earliest_of_delivery_or_payment` ovdje je približna vrijednost: obuhvata isporuku i plaćanje, ali ne i samostalno izdavanje fakture prije jednog od njih dvoje kao treći okidač. Propust je zabilježen u README.md i u docs/international.md, odjeljak ''From Bosnia and Herzegovina''.',
  tax_point_source_key          = 'vat-law',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Zakon o porezu na dodanu vrijednost, član 55, stav 6 — knjižno odobrenje (credit note) izdaje se kada je roba vraćena nakon izdavanja fakture, kada dobavljač naknadno odobri sniženje cijene ili popust, ili kada dobavljač naknadno primi dodatno plaćanje za isporučena dobra ili usluge; ispravka se, dakle, vrši novim dokumentom, a ne izmjenom već izdate fakture.',
  posted_edit_policy_source_key = 'vat-law',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Zakon o porezu na dodanu vrijednost, član 55 — faktura se izdaje kupcu, a njen sadržaj i uvjeti izdavanja bliže se uređuju podzakonskim aktom UIO-a (Pravilnik o primjeni Zakona o porezu na dodatu vrijednost); nijedan od pročitanih izvora ne propisuje opću obavezu strukturirane elektronske fakture (e-Faktura) niti državnu platformu za razmjenu ili validaciju faktura između poslovnih subjekata — postoji isključivo elektronsko podnošenje same prijave PDV-a (obavezno od januara 2019.) preko portala e-Porezi. `profile` ostaje prazan jer nijedan profil izgrađen na semantičkom modelu EN 16931 (Peppol BIS, Factur-X, XRechnung, PINT) nije zakonski propisan niti poznat iz istraženih izvora. Propust je zabilježen u README.md i u docs/international.md, odjeljak ''From Bosnia and Herzegovina''.',
  einvoice_source_key           = 'vat-law',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'BA';
