-- Ekwo OS — Albania: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/al at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build al`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Ligj Nr. 92/2014, datë 24.7.2014, «Për tatimin mbi vlerën e shtuar në Republikën e Shqipërisë», i ndryshuar — botim i Drejtorisë së Përgjithshme të Tatimeve, Legjislacioni Tatimor (Drejtoria e Përgjithshme e Tatimeve)
--     https://www.tatime.gov.al/eng/shkarko.php?id=36
--   Buletini Fiskal 2024 — Drejtoria e Politikave Tatimore, seksioni II.1 «Tatimi mbi Vlerën e Shtuar (TVSH)»: normat tatimore të zbatuara përgjatë vitit 2024 (20%, 6%, 10%, 0%) dhe listat e furnizimeve që përfitojnë secilën normë të reduktuar (Ministria e Financave)
--     https://financa.gov.al/wp-content/uploads/2025/03/Buletini-Fiskal-2024-Drejtoria-e-Politikave-Tatimore2-Copy.pdf
--   Vendim i Këshillit të Ministrave Nr. 576, datë 22.7.2020, «Për disa ndryshime dhe shtesa në vendimin nr. 953, datë 29.12.2014» — kufiri minimal i regjistrimit për TVSH-në në 10 000 000 lekë, në fuqi nga 1 janari 2021 (Këshilli i Ministrave — Qendra e Botimeve Zyrtare (QBZ))
--     https://qbz.gov.al/eli/vendim/2020/07/22/576/fa14cde6-0154-4107-8936-eed6743b8a2d
--   Ligj Nr. 25/2018, datë 10.5.2018, «Për kontabilitetin dhe pasqyrat financiare» (Kuvendi i Shqipërisë — botuar nga Këshilli Kombëtar i Kontabilitetit)
--     https://kkk.gov.al/wp-content/uploads/2025/02/ligj-nr.-25-dt.-10.5.2018.pdf
--   Standardi Kombëtar i Kontabilitetit Nr. 2, «Paraqitja e Pasqyrave Financiare», Shtojca 1 (zërat e bilancit) dhe Shtojca 2, Formati 1 (pasqyra e të ardhurave dhe shpenzimeve) (Këshilli Kombëtar i Kontabilitetit)
--     https://kkk.gov.al/wp-content/uploads/2025/03/SKK-02-Paraqitja-e-pasqyrave-financiare.pdf
--   Ligj Nr. 87/2019, datë 18.12.2019, «Për faturën dhe sistemin e monitorimit të qarkullimit» (fiskalizimi), botuar në Fletoren Zyrtare Nr. 3, datë 20.1.2020 — njoftim i Drejtorisë së Përgjithshme të Tatimeve mbi zbatimin me faza (Drejtoria e Përgjithshme e Tatimeve)
--     https://www.tatime.gov.al/d/8/45/45/1506/njoftim-per-faturen-dhe-sistemin-e-monitorimit-te-qarkulllimit
--   DEKLARATA E TVSH-SË — Librat e Shitjes dhe Blerjes: përshkrimi zyrtar i kategorive të detyrueshme të Librit të Shitjeve dhe të Librit të Blerjeve që ushqejnë Formularin e Deklarimit dhe Pagesës (FDP) (Drejtoria e Përgjithshme e Tatimeve)
--     https://www.tatime.gov.al/shkarko.php?id=6235
--   e-Filing — portali i deklarimit elektronik të Drejtorisë së Përgjithshme të Tatimeve, ku dorëzohet deklarata e TVSH-së (Drejtoria e Përgjithshme e Tatimeve)
--     https://efiling.tatime.gov.al/cats_public/Account/LogOn
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('AL', 'Albania', '0.1.0', date '2026-09-26', '20260923110000', 'community', null, null, '60be2ce520ea6f3c8830c8ea7d9c1055aff860ff5196d8375ccbabdafa58e03e', '[{"key":"ligji-92-2014","title":"Ligj Nr. 92/2014, datë 24.7.2014, «Për tatimin mbi vlerën e shtuar në Republikën e Shqipërisë», i ndryshuar — botim i Drejtorisë së Përgjithshme të Tatimeve, Legjislacioni Tatimor","publisher":"Drejtoria e Përgjithshme e Tatimeve","url":"https://www.tatime.gov.al/eng/shkarko.php?id=36","consulted_on":"2026-09-26","kind":"law"},{"key":"buletini-fiskal-2024","title":"Buletini Fiskal 2024 — Drejtoria e Politikave Tatimore, seksioni II.1 «Tatimi mbi Vlerën e Shtuar (TVSH)»: normat tatimore të zbatuara përgjatë vitit 2024 (20%, 6%, 10%, 0%) dhe listat e furnizimeve që përfitojnë secilën normë të reduktuar","publisher":"Ministria e Financave","url":"https://financa.gov.al/wp-content/uploads/2025/03/Buletini-Fiskal-2024-Drejtoria-e-Politikave-Tatimore2-Copy.pdf","consulted_on":"2026-09-26","kind":"regulation"},{"key":"vkm-576-2020","title":"Vendim i Këshillit të Ministrave Nr. 576, datë 22.7.2020, «Për disa ndryshime dhe shtesa në vendimin nr. 953, datë 29.12.2014» — kufiri minimal i regjistrimit për TVSH-në në 10 000 000 lekë, në fuqi nga 1 janari 2021","publisher":"Këshilli i Ministrave — Qendra e Botimeve Zyrtare (QBZ)","url":"https://qbz.gov.al/eli/vendim/2020/07/22/576/fa14cde6-0154-4107-8936-eed6743b8a2d","consulted_on":"2026-09-26","kind":"regulation"},{"key":"ligji-25-2018","title":"Ligj Nr. 25/2018, datë 10.5.2018, «Për kontabilitetin dhe pasqyrat financiare»","publisher":"Kuvendi i Shqipërisë — botuar nga Këshilli Kombëtar i Kontabilitetit","url":"https://kkk.gov.al/wp-content/uploads/2025/02/ligj-nr.-25-dt.-10.5.2018.pdf","consulted_on":"2026-09-26","kind":"law"},{"key":"skk-2","title":"Standardi Kombëtar i Kontabilitetit Nr. 2, «Paraqitja e Pasqyrave Financiare», Shtojca 1 (zërat e bilancit) dhe Shtojca 2, Formati 1 (pasqyra e të ardhurave dhe shpenzimeve)","publisher":"Këshilli Kombëtar i Kontabilitetit","url":"https://kkk.gov.al/wp-content/uploads/2025/03/SKK-02-Paraqitja-e-pasqyrave-financiare.pdf","consulted_on":"2026-09-26","kind":"standard"},{"key":"ligji-87-2019","title":"Ligj Nr. 87/2019, datë 18.12.2019, «Për faturën dhe sistemin e monitorimit të qarkullimit» (fiskalizimi), botuar në Fletoren Zyrtare Nr. 3, datë 20.1.2020 — njoftim i Drejtorisë së Përgjithshme të Tatimeve mbi zbatimin me faza","publisher":"Drejtoria e Përgjithshme e Tatimeve","url":"https://www.tatime.gov.al/d/8/45/45/1506/njoftim-per-faturen-dhe-sistemin-e-monitorimit-te-qarkulllimit","consulted_on":"2026-09-26","kind":"guidance"},{"key":"deklarata-tvsh-librat","title":"DEKLARATA E TVSH-SË — Librat e Shitjes dhe Blerjes: përshkrimi zyrtar i kategorive të detyrueshme të Librit të Shitjeve dhe të Librit të Blerjeve që ushqejnë Formularin e Deklarimit dhe Pagesës (FDP)","publisher":"Drejtoria e Përgjithshme e Tatimeve","url":"https://www.tatime.gov.al/shkarko.php?id=6235","consulted_on":"2026-09-26","kind":"guidance"},{"key":"efiling-portal","title":"e-Filing — portali i deklarimit elektronik të Drejtorisë së Përgjithshme të Tatimeve, ku dorëzohet deklarata e TVSH-së","publisher":"Drejtoria e Përgjithshme e Tatimeve","url":"https://efiling.tatime.gov.al/cats_public/Account/LogOn","consulted_on":"2026-09-26","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('AL', 'default', 'Plani kontabël (klasat 1-7)', '{"en":"Chart of accounts (classes 1-7)"}'::jsonb, true, 'companies', array['AL-SKK2-BS', 'AL-SKK2-IS']::text[], null, 'Ligji Nr. 25/2018 «Për kontabilitetin dhe pasqyrat financiare» detyron çdo njësi ekonomike të mbajë kontabilitet sipas Standardeve Kombëtare të Kontabilitetit (SKK); asnjë tekst zyrtar shqiptar nuk boton një plan kontabël të detyrueshëm me kode numerike fikse siç bën udhëzimi francez apo ai rumun — SKK përcaktojnë njohjen, matjen dhe paraqitjen, jo numërtimin e llogarive. Kodet e këtij plani (klasa 1 kapitalet, 2 aktivet afatgjata, 3 inventari, 4 të tretët, 5 thesari, 6 shpenzimet, 7 të ardhurat) transkriptojnë numërtimin kontinental me shtatë klasa që praktika kontabël shqiptare e përdor prej reformës së vitit 1993 dhe që literatura e IEKA-s (Institutit të Ekspertëve Kontabël të Autorizuar) e mëson ende sot; janë një konvencion i këtij paketimi dhe jo një kërkesë ligjore e numrave të saktë, siç shënohet në README.md.', 'ligji-25-2018')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('AL', 'default', '10', 'Kapital dhe rezerva', '{"en":"Capital and reserves"}'::jsonb, 'equity', false, null, 10),
  ('AL', 'default', '101', 'Kapitali themeltar (aksionar)', '{"en":"Share capital"}'::jsonb, 'equity', false, '10', 20),
  ('AL', 'default', '104', 'Prime kapitali', '{"en":"Share premium"}'::jsonb, 'equity', false, '10', 30),
  ('AL', 'default', '105', 'Rezerva nga rivlerësimi', '{"en":"Revaluation reserve"}'::jsonb, 'equity', false, '10', 40),
  ('AL', 'default', '106', 'Rezerva', '{"en":"Reserves"}'::jsonb, 'equity', false, '10', 50),
  ('AL', 'default', '1061', 'Rezerva ligjore', '{"en":"Legal reserve"}'::jsonb, 'equity', false, '106', 60),
  ('AL', 'default', '1063', 'Rezerva statutore', '{"en":"Statutory reserve"}'::jsonb, 'equity', false, '106', 70),
  ('AL', 'default', '1068', 'Rezerva të tjera', '{"en":"Other reserves"}'::jsonb, 'equity', false, '106', 80),
  ('AL', 'default', '11', 'Fitime (Humbje) të pashpërndara', '{"en":"Retained earnings (losses)"}'::jsonb, 'equity_retained', false, null, 90),
  ('AL', 'default', '117', 'Fitime (Humbje) të pashpërndara', '{"en":"Retained earnings (losses)"}'::jsonb, 'equity_retained', false, '11', 100),
  ('AL', 'default', '12', 'Rezultati i ushtrimit', '{"en":"Result of the year"}'::jsonb, 'equity', false, null, 110),
  ('AL', 'default', '121', 'Fitimi (Humbja) e vitit financiar', '{"en":"Profit (loss) for the financial year"}'::jsonb, 'equity', false, '12', 120),
  ('AL', 'default', '13', 'Grante dhe të ardhura të shtyra', '{"en":"Grants and deferred income"}'::jsonb, 'liability_non_current', false, null, 130),
  ('AL', 'default', '131', 'Grante për investime', '{"en":"Investment grants"}'::jsonb, 'liability_non_current', false, '13', 140),
  ('AL', 'default', '15', 'Provizione afatgjata', '{"en":"Non-current provisions"}'::jsonb, 'liability_non_current', false, null, 150),
  ('AL', 'default', '151', 'Provizione për garanci', '{"en":"Provisions for warranties"}'::jsonb, 'liability_non_current', false, '15', 160),
  ('AL', 'default', '158', 'Provizione të tjera afatgjata', '{"en":"Other non-current provisions"}'::jsonb, 'liability_non_current', false, '15', 170),
  ('AL', 'default', '16', 'Hua afatgjata dhe detyrime të ngjashme', '{"en":"Long-term borrowings and similar liabilities"}'::jsonb, 'liability_non_current', false, null, 180),
  ('AL', 'default', '162', 'Kredi bankare afatgjata', '{"en":"Long-term bank loans"}'::jsonb, 'liability_non_current', false, '16', 190),
  ('AL', 'default', '166', 'Detyrime nga qiraja financiare', '{"en":"Finance lease liabilities"}'::jsonb, 'liability_non_current', false, '16', 200),
  ('AL', 'default', '167', 'Hua të tjera afatgjata', '{"en":"Other long-term borrowings"}'::jsonb, 'liability_non_current', false, '16', 210),
  ('AL', 'default', '20', 'Aktive afatgjata jomateriale', '{"en":"Intangible non-current assets"}'::jsonb, 'asset_fixed', false, null, 220),
  ('AL', 'default', '201', 'Shpenzime themelimi', '{"en":"Formation expenses"}'::jsonb, 'asset_fixed', false, '20', 230),
  ('AL', 'default', '203', 'Shpenzime zhvillimi', '{"en":"Development expenses"}'::jsonb, 'asset_fixed', false, '20', 240),
  ('AL', 'default', '205', 'Koncesione, patenta, licenca, marka tregtare', '{"en":"Concessions, patents, licences, trademarks"}'::jsonb, 'asset_fixed', false, '20', 250),
  ('AL', 'default', '207', 'Emri i mirë (goodwill)', '{"en":"Goodwill"}'::jsonb, 'asset_fixed', false, '20', 260),
  ('AL', 'default', '208', 'Aktive të tjera afatgjata jomateriale', '{"en":"Other intangible non-current assets"}'::jsonb, 'asset_fixed', false, '20', 270),
  ('AL', 'default', '21', 'Toka dhe ndërtesa', '{"en":"Land and buildings"}'::jsonb, 'asset_fixed', false, null, 280),
  ('AL', 'default', '211', 'Toka', '{"en":"Land"}'::jsonb, 'asset_fixed', false, '21', 290),
  ('AL', 'default', '212', 'Ndërtesa', '{"en":"Buildings"}'::jsonb, 'asset_fixed', false, '21', 300),
  ('AL', 'default', '213', 'Makineri, pajisje dhe mjete transporti', '{"en":"Machinery, equipment and vehicles"}'::jsonb, 'asset_fixed', false, '21', 310),
  ('AL', 'default', '2131', 'Makineri dhe pajisje', '{"en":"Machinery and equipment"}'::jsonb, 'asset_fixed', false, '213', 320),
  ('AL', 'default', '2133', 'Mjete transporti', '{"en":"Vehicles"}'::jsonb, 'asset_fixed', false, '213', 330),
  ('AL', 'default', '214', 'Mobilie dhe pajisje zyre', '{"en":"Fixtures, fittings and office equipment"}'::jsonb, 'asset_fixed', false, '21', 340),
  ('AL', 'default', '23', 'Aktive afatgjata në ndërtim e sipër', '{"en":"Non-current assets under construction"}'::jsonb, 'asset_fixed', false, null, 350),
  ('AL', 'default', '231', 'Aktive afatgjata materiale në proces', '{"en":"Tangible non-current assets in progress"}'::jsonb, 'asset_fixed', false, '23', 360),
  ('AL', 'default', '232', 'Parapagime për aktive afatgjata', '{"en":"Advances on non-current assets"}'::jsonb, 'asset_fixed', false, '23', 370),
  ('AL', 'default', '26', 'Investime financiare afatgjata', '{"en":"Long-term financial investments"}'::jsonb, 'asset_non_current', false, null, 380),
  ('AL', 'default', '261', 'Aksione dhe pjesëmarrje në njësi të kontrolluara', '{"en":"Shares and interests in controlled entities"}'::jsonb, 'asset_non_current', false, '26', 390),
  ('AL', 'default', '267', 'Llogari të arkëtueshme afatgjata', '{"en":"Long-term receivables"}'::jsonb, 'asset_non_current', false, '26', 400),
  ('AL', 'default', '28', 'Amortizimi i akumuluar', '{"en":"Accumulated depreciation"}'::jsonb, 'asset_fixed', false, null, 410),
  ('AL', 'default', '280', 'Amortizimi i aktiveve afatgjata jomateriale', '{"en":"Amortisation of intangible non-current assets"}'::jsonb, 'asset_fixed', false, '28', 420),
  ('AL', 'default', '281', 'Amortizimi i aktiveve afatgjata materiale', '{"en":"Depreciation of tangible non-current assets"}'::jsonb, 'asset_fixed', false, '28', 430),
  ('AL', 'default', '2811', 'Amortizimi i ndërtesave', '{"en":"Depreciation of buildings"}'::jsonb, 'asset_fixed', false, '281', 440),
  ('AL', 'default', '2813', 'Amortizimi i makinerive dhe pajisjeve', '{"en":"Depreciation of machinery and equipment"}'::jsonb, 'asset_fixed', false, '281', 450),
  ('AL', 'default', '2814', 'Amortizimi i mobilieve dhe pajisjeve zyre', '{"en":"Depreciation of fixtures and office equipment"}'::jsonb, 'asset_fixed', false, '281', 460),
  ('AL', 'default', '29', 'Zhvlerësimi i aktiveve afatgjata', '{"en":"Impairment of non-current assets"}'::jsonb, 'asset_fixed', false, null, 470),
  ('AL', 'default', '291', 'Zhvlerësimi i aktiveve afatgjata materiale', '{"en":"Impairment of tangible non-current assets"}'::jsonb, 'asset_fixed', false, '29', 480),
  ('AL', 'default', '30', 'Lëndë të para dhe materiale', '{"en":"Raw materials and supplies"}'::jsonb, 'asset_current', false, null, 490),
  ('AL', 'default', '301', 'Lëndë të para', '{"en":"Raw materials"}'::jsonb, 'asset_current', false, '30', 500),
  ('AL', 'default', '302', 'Materiale të tjera', '{"en":"Other supplies"}'::jsonb, 'asset_current', false, '30', 510),
  ('AL', 'default', '303', 'Materiale ambalazhimi', '{"en":"Packaging materials"}'::jsonb, 'asset_current', false, '30', 520),
  ('AL', 'default', '33', 'Prodhim në proces', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, null, 530),
  ('AL', 'default', '331', 'Produkte në proces', '{"en":"Products in progress"}'::jsonb, 'asset_current', false, '33', 540),
  ('AL', 'default', '332', 'Shërbime në proces', '{"en":"Services in progress"}'::jsonb, 'asset_current', false, '33', 550),
  ('AL', 'default', '35', 'Produkte të gatshme', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, null, 560),
  ('AL', 'default', '351', 'Produkte të gatshme', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, '35', 570),
  ('AL', 'default', '37', 'Mallra', '{"en":"Goods for resale"}'::jsonb, 'asset_current', false, null, 580),
  ('AL', 'default', '371', 'Mallra për rishitje', '{"en":"Goods for resale"}'::jsonb, 'asset_current', false, '37', 590),
  ('AL', 'default', '38', 'Mallra dhe materiale rrugës', '{"en":"Goods and supplies in transit"}'::jsonb, 'asset_current', false, null, 600),
  ('AL', 'default', '381', 'Mallra rrugës', '{"en":"Goods in transit"}'::jsonb, 'asset_current', false, '38', 610),
  ('AL', 'default', '39', 'Zhvlerësimi i inventarit', '{"en":"Impairment of inventory"}'::jsonb, 'asset_current', false, null, 620),
  ('AL', 'default', '391', 'Zhvlerësimi i lëndëve të para', '{"en":"Impairment of raw materials"}'::jsonb, 'asset_current', false, '39', 630),
  ('AL', 'default', '397', 'Zhvlerësimi i mallrave', '{"en":"Impairment of goods for resale"}'::jsonb, 'asset_current', false, '39', 640),
  ('AL', 'default', '40', 'Furnitorë', '{"en":"Suppliers"}'::jsonb, 'liability_payable', true, null, 650),
  ('AL', 'default', '401', 'Furnitorë', '{"en":"Suppliers"}'::jsonb, 'liability_payable', true, '40', 660),
  ('AL', 'default', '403', 'Furnitorë - efekte për t''u paguar', '{"en":"Suppliers — bills payable"}'::jsonb, 'liability_payable', true, '40', 670),
  ('AL', 'default', '404', 'Furnitorë të aktiveve afatgjata', '{"en":"Suppliers of non-current assets"}'::jsonb, 'liability_payable', true, '40', 680),
  ('AL', 'default', '408', 'Furnitorë - fatura të pritura', '{"en":"Suppliers — invoices not yet received"}'::jsonb, 'liability_payable', true, '40', 690),
  ('AL', 'default', '409', 'Furnitorë - debitorë (parapagime dhëna)', '{"en":"Suppliers — debit balances (advances paid)"}'::jsonb, 'asset_current', false, '40', 700),
  ('AL', 'default', '41', 'Klientë', '{"en":"Customers"}'::jsonb, 'asset_receivable', true, null, 710),
  ('AL', 'default', '411', 'Klientë', '{"en":"Customers"}'::jsonb, 'asset_receivable', true, '41', 720),
  ('AL', 'default', '413', 'Klientë - efekte për t''u arkëtuar', '{"en":"Customers — bills receivable"}'::jsonb, 'asset_receivable', true, '41', 730),
  ('AL', 'default', '418', 'Klientë - fatura për t''u lëshuar', '{"en":"Customers — invoices to be issued"}'::jsonb, 'asset_receivable', true, '41', 740),
  ('AL', 'default', '419', 'Klientë - kreditorë (parapagime marra)', '{"en":"Customers — credit balances (advances received)"}'::jsonb, 'liability_current', false, '41', 750),
  ('AL', 'default', '42', 'Personeli', '{"en":"Staff"}'::jsonb, 'liability_current', false, null, 760),
  ('AL', 'default', '421', 'Personeli - paga të pagueshme', '{"en":"Staff — wages payable"}'::jsonb, 'liability_current', false, '42', 770),
  ('AL', 'default', '425', 'Personeli - avanca', '{"en":"Staff — advances"}'::jsonb, 'asset_current', false, '42', 780),
  ('AL', 'default', '427', 'Personeli - mbajtje në favor të të tretëve', '{"en":"Staff — amounts withheld for third parties"}'::jsonb, 'liability_current', false, '42', 790),
  ('AL', 'default', '43', 'Sigurimet shoqërore dhe shëndetësore', '{"en":"Social and health insurance"}'::jsonb, 'liability_current', false, null, 800),
  ('AL', 'default', '431', 'Sigurimet shoqërore', '{"en":"Social insurance"}'::jsonb, 'liability_current', false, '43', 810),
  ('AL', 'default', '437', 'Sigurimet shëndetësore', '{"en":"Health insurance"}'::jsonb, 'liability_current', false, '43', 820),
  ('AL', 'default', '44', 'Shteti - tatime dhe taksa', '{"en":"State — taxes and duties"}'::jsonb, 'liability_current', false, null, 830),
  ('AL', 'default', '441', 'Tatimi mbi fitimin', '{"en":"Corporate income tax"}'::jsonb, 'liability_current', false, '44', 840),
  ('AL', 'default', '442', 'Tatimi mbi vlerën e shtuar', '{"en":"Value added tax"}'::jsonb, 'liability_current', false, '44', 850),
  ('AL', 'default', '4423', 'TVSH për t''u paguar', '{"en":"VAT payable"}'::jsonb, 'liability_current', true, '442', 860),
  ('AL', 'default', '4424', 'TVSH për t''u rimbursuar', '{"en":"VAT receivable"}'::jsonb, 'asset_current', true, '442', 870),
  ('AL', 'default', '4426', 'TVSH e zbritshme mbi blerjet', '{"en":"VAT deductible on purchases"}'::jsonb, 'asset_current', false, '442', 880),
  ('AL', 'default', '4427', 'TVSH e mbledhur mbi shitjet', '{"en":"VAT collected on sales"}'::jsonb, 'liability_current', false, '442', 890),
  ('AL', 'default', '4428', 'TVSH - operacione të veçanta', '{"en":"VAT — special operations"}'::jsonb, 'liability_current', false, '442', 900),
  ('AL', 'default', '44281', 'TVSH e vetëngarkuar (autoliquidim) - e mbledhur', '{"en":"Self-assessed (reverse-charged) VAT — collected"}'::jsonb, 'liability_current', false, '4428', 910),
  ('AL', 'default', '44282', 'TVSH e vetëngarkuar (autoliquidim) - e zbritshme', '{"en":"Self-assessed (reverse-charged) VAT — deductible"}'::jsonb, 'asset_current', false, '4428', 920),
  ('AL', 'default', '445', 'Tatime dhe taksa të tjera', '{"en":"Other taxes and duties"}'::jsonb, 'liability_current', false, '44', 940),
  ('AL', 'default', '4456', 'TVSH e paguar në import', '{"en":"VAT paid on import"}'::jsonb, 'asset_current', false, '442', 930),
  ('AL', 'default', '446', 'Taksa vendore', '{"en":"Local taxes"}'::jsonb, 'liability_current', false, '44', 950),
  ('AL', 'default', '45', 'Grupi dhe ortakët', '{"en":"Group and shareholders"}'::jsonb, 'liability_current', false, null, 960),
  ('AL', 'default', '455', 'Shuma të papaguara ortakëve', '{"en":"Amounts due to shareholders"}'::jsonb, 'liability_current', false, '45', 970),
  ('AL', 'default', '456', 'Shlyerje me ortakët për kapitalin', '{"en":"Settlements with shareholders on capital"}'::jsonb, 'liability_current', false, '45', 980),
  ('AL', 'default', '457', 'Dividentë për t''u paguar', '{"en":"Dividends payable"}'::jsonb, 'liability_current', false, '45', 990),
  ('AL', 'default', '46', 'Debitorë dhe kreditorë të tjerë', '{"en":"Other debtors and creditors"}'::jsonb, 'asset_current', false, null, 1000),
  ('AL', 'default', '461', 'Debitorë të tjerë', '{"en":"Other debtors"}'::jsonb, 'asset_current', false, '46', 1010),
  ('AL', 'default', '462', 'Kreditorë të tjerë', '{"en":"Other creditors"}'::jsonb, 'liability_current', false, '46', 1020),
  ('AL', 'default', '47', 'Llogari kalimtare', '{"en":"Suspense and accrual accounts"}'::jsonb, 'asset_prepayments', false, null, 1030),
  ('AL', 'default', '471', 'Shpenzime të konstatuara paraprakisht', '{"en":"Prepaid expenses"}'::jsonb, 'asset_prepayments', false, '47', 1040),
  ('AL', 'default', '472', 'Të ardhura të konstatuara paraprakisht', '{"en":"Deferred income"}'::jsonb, 'liability_current', false, '47', 1050),
  ('AL', 'default', '473', 'Llogari të papërcaktuara (pritje)', '{"en":"Suspense account (items awaiting clarification)"}'::jsonb, 'liability_current', false, '47', 1060),
  ('AL', 'default', '49', 'Zhvlerësimi i llogarive të klientëve', '{"en":"Impairment of customer receivables"}'::jsonb, 'asset_current', false, null, 1070),
  ('AL', 'default', '491', 'Zhvlerësimi i llogarive të klientëve', '{"en":"Impairment of customer receivables"}'::jsonb, 'asset_current', false, '49', 1080),
  ('AL', 'default', '50', 'Letra me vlerë afatshkurtra', '{"en":"Short-term securities"}'::jsonb, 'asset_current', false, null, 1090),
  ('AL', 'default', '508', 'Investime të tjera afatshkurtra', '{"en":"Other short-term investments"}'::jsonb, 'asset_current', false, '50', 1100),
  ('AL', 'default', '51', 'Llogari bankare', '{"en":"Bank accounts"}'::jsonb, 'asset_cash', false, null, 1110),
  ('AL', 'default', '512', 'Llogari bankare në lekë', '{"en":"Bank accounts in lek"}'::jsonb, 'asset_cash', false, '51', 1120),
  ('AL', 'default', '514', 'Llogari bankare në valutë', '{"en":"Bank accounts in foreign currency"}'::jsonb, 'asset_cash', false, '51', 1130),
  ('AL', 'default', '519', 'Kredi bankare afatshkurtra', '{"en":"Short-term bank loans"}'::jsonb, 'liability_current', false, '51', 1140),
  ('AL', 'default', '53', 'Arka', '{"en":"Cash on hand"}'::jsonb, 'asset_cash', false, null, 1150),
  ('AL', 'default', '531', 'Arka në lekë', '{"en":"Cash on hand in lek"}'::jsonb, 'asset_cash', false, '53', 1160),
  ('AL', 'default', '534', 'Arka në valutë', '{"en":"Cash on hand in foreign currency"}'::jsonb, 'asset_cash', false, '53', 1170),
  ('AL', 'default', '54', 'Akreditiva dhe avanca thesari', '{"en":"Letters of credit and cash advances"}'::jsonb, 'asset_current', false, null, 1180),
  ('AL', 'default', '541', 'Akreditiva', '{"en":"Letters of credit"}'::jsonb, 'asset_current', false, '54', 1190),
  ('AL', 'default', '542', 'Avanca thesari', '{"en":"Cash advances"}'::jsonb, 'asset_current', false, '54', 1200),
  ('AL', 'default', '58', 'Transferta të brendshme', '{"en":"Internal transfers"}'::jsonb, 'asset_current', false, null, 1210),
  ('AL', 'default', '581', 'Transferta të brendshme', '{"en":"Internal transfers"}'::jsonb, 'asset_current', false, '58', 1220),
  ('AL', 'default', '60', 'Shpenzime për blerje', '{"en":"Purchases"}'::jsonb, 'expense_direct_cost', false, null, 1230),
  ('AL', 'default', '600', 'Blerje mallrash', '{"en":"Purchases of goods"}'::jsonb, 'expense_direct_cost', false, '60', 1240),
  ('AL', 'default', '601', 'Blerje lëndësh të para', '{"en":"Purchases of raw materials"}'::jsonb, 'expense_direct_cost', false, '60', 1250),
  ('AL', 'default', '602', 'Blerje materialesh të tjera', '{"en":"Purchases of other supplies"}'::jsonb, 'expense_direct_cost', false, '60', 1260),
  ('AL', 'default', '605', 'Energji dhe ujë', '{"en":"Energy and water"}'::jsonb, 'expense_direct_cost', false, '60', 1270),
  ('AL', 'default', '609', 'Zbritje tregtare të përfituara', '{"en":"Trade discounts received"}'::jsonb, 'expense_direct_cost', false, '60', 1280),
  ('AL', 'default', '61', 'Shërbime nga të tretët', '{"en":"Services from third parties"}'::jsonb, 'expense', false, null, 1290),
  ('AL', 'default', '611', 'Mirëmbajtje dhe riparime', '{"en":"Maintenance and repairs"}'::jsonb, 'expense', false, '61', 1300),
  ('AL', 'default', '612', 'Qira', '{"en":"Rent"}'::jsonb, 'expense', false, '61', 1310),
  ('AL', 'default', '613', 'Sigurime', '{"en":"Insurance"}'::jsonb, 'expense', false, '61', 1320),
  ('AL', 'default', '614', 'Studime dhe kërkime', '{"en":"Studies and research"}'::jsonb, 'expense', false, '61', 1330),
  ('AL', 'default', '62', 'Shërbime të tjera nga të tretët', '{"en":"Other services from third parties"}'::jsonb, 'expense', false, null, 1340),
  ('AL', 'default', '621', 'Personel i jashtëm', '{"en":"External personnel"}'::jsonb, 'expense', false, '62', 1350),
  ('AL', 'default', '622', 'Komisione dhe honorare', '{"en":"Commissions and fees"}'::jsonb, 'expense', false, '62', 1360),
  ('AL', 'default', '623', 'Reklama dhe promocion', '{"en":"Advertising and promotion"}'::jsonb, 'expense', false, '62', 1370),
  ('AL', 'default', '624', 'Transport mallrash dhe personeli', '{"en":"Transport of goods and personnel"}'::jsonb, 'expense', false, '62', 1380),
  ('AL', 'default', '625', 'Udhëtime dhe dieta', '{"en":"Travel and subsistence"}'::jsonb, 'expense', false, '62', 1390),
  ('AL', 'default', '626', 'Postë dhe telekomunikacione', '{"en":"Postage and telecommunications"}'::jsonb, 'expense', false, '62', 1400),
  ('AL', 'default', '627', 'Shërbime bankare', '{"en":"Bank charges"}'::jsonb, 'expense', false, '62', 1410),
  ('AL', 'default', '628', 'Shërbime të tjera', '{"en":"Other services"}'::jsonb, 'expense', false, '62', 1420),
  ('AL', 'default', '63', 'Taksa dhe tatime të tjera', '{"en":"Other taxes and duties (expense)"}'::jsonb, 'expense', false, null, 1430),
  ('AL', 'default', '635', 'Taksa vendore dhe tatime të tjera', '{"en":"Local taxes and other duties"}'::jsonb, 'expense', false, '63', 1440),
  ('AL', 'default', '64', 'Shpenzime personeli', '{"en":"Staff costs"}'::jsonb, 'expense', false, null, 1450),
  ('AL', 'default', '641', 'Paga', '{"en":"Wages and salaries"}'::jsonb, 'expense', false, '64', 1460),
  ('AL', 'default', '645', 'Sigurime shoqërore e shëndetësore', '{"en":"Social and health insurance contributions"}'::jsonb, 'expense', false, '64', 1470),
  ('AL', 'default', '65', 'Shpenzime të tjera operative', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, null, 1480),
  ('AL', 'default', '654', 'Humbje nga arkëtimet e pambledhshme', '{"en":"Bad debt losses"}'::jsonb, 'expense', false, '65', 1490),
  ('AL', 'default', '658', 'Shpenzime të tjera operative', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, '65', 1500),
  ('AL', 'default', '6588', 'Rrumbullakosje', '{"en":"Rounding differences"}'::jsonb, 'expense', false, '658', 1510),
  ('AL', 'default', '66', 'Shpenzime financiare', '{"en":"Financial expenses"}'::jsonb, 'expense', false, null, 1520),
  ('AL', 'default', '663', 'Humbje nga investime financiare', '{"en":"Losses on financial investments"}'::jsonb, 'expense', false, '66', 1530),
  ('AL', 'default', '665', 'Humbje nga kursi i këmbimit', '{"en":"Foreign exchange losses"}'::jsonb, 'expense', false, '66', 1540),
  ('AL', 'default', '666', 'Interesa', '{"en":"Interest expense"}'::jsonb, 'expense', false, '66', 1550),
  ('AL', 'default', '668', 'Shpenzime të tjera financiare', '{"en":"Other financial expenses"}'::jsonb, 'expense', false, '66', 1560),
  ('AL', 'default', '68', 'Amortizimi dhe provizionet', '{"en":"Depreciation and provisions"}'::jsonb, 'expense_depreciation', false, null, 1570),
  ('AL', 'default', '681', 'Amortizimi i aktiveve afatgjata', '{"en":"Depreciation of non-current assets"}'::jsonb, 'expense_depreciation', false, '68', 1580),
  ('AL', 'default', '685', 'Provizione', '{"en":"Provisions"}'::jsonb, 'expense_depreciation', false, '68', 1590),
  ('AL', 'default', '69', 'Tatimi mbi fitimin', '{"en":"Income tax expense"}'::jsonb, 'expense', false, null, 1600),
  ('AL', 'default', '691', 'Shpenzimi i tatimit mbi fitimin', '{"en":"Corporate income tax expense"}'::jsonb, 'expense', false, '69', 1610),
  ('AL', 'default', '70', 'Shitje', '{"en":"Sales"}'::jsonb, 'income', false, null, 1620),
  ('AL', 'default', '700', 'Shitje mallrash', '{"en":"Sales of goods"}'::jsonb, 'income', false, '70', 1630),
  ('AL', 'default', '701', 'Shitje produktesh', '{"en":"Sales of products"}'::jsonb, 'income', false, '70', 1640),
  ('AL', 'default', '706', 'Shitje shërbimesh', '{"en":"Sales of services"}'::jsonb, 'income', false, '70', 1650),
  ('AL', 'default', '709', 'Zbritje tregtare të dhëna', '{"en":"Trade discounts granted"}'::jsonb, 'income', false, '70', 1660),
  ('AL', 'default', '71', 'Ndryshime në inventarin e prodhimit', '{"en":"Changes in inventories of production"}'::jsonb, 'income', false, null, 1670),
  ('AL', 'default', '711', 'Ndryshime në inventarin e produkteve', '{"en":"Changes in inventories of products"}'::jsonb, 'income', false, '71', 1680),
  ('AL', 'default', '74', 'Subvencione shfrytëzimi', '{"en":"Operating grants"}'::jsonb, 'income_other', false, null, 1690),
  ('AL', 'default', '741', 'Subvencione shfrytëzimi', '{"en":"Operating grants"}'::jsonb, 'income_other', false, '74', 1700),
  ('AL', 'default', '75', 'Të ardhura të tjera operative', '{"en":"Other operating income"}'::jsonb, 'income_other', false, null, 1710),
  ('AL', 'default', '758', 'Të ardhura të tjera operative', '{"en":"Other operating income"}'::jsonb, 'income_other', false, '75', 1720),
  ('AL', 'default', '76', 'Të ardhura financiare', '{"en":"Financial income"}'::jsonb, 'income_other', false, null, 1730),
  ('AL', 'default', '761', 'Fitime nga investime financiare', '{"en":"Gains on financial investments"}'::jsonb, 'income_other', false, '76', 1740),
  ('AL', 'default', '765', 'Fitime nga kursi i këmbimit', '{"en":"Foreign exchange gains"}'::jsonb, 'income_other', false, '76', 1750),
  ('AL', 'default', '766', 'Të ardhura nga interesa', '{"en":"Interest income"}'::jsonb, 'income_other', false, '76', 1760),
  ('AL', 'default', '768', 'Të ardhura të tjera financiare', '{"en":"Other financial income"}'::jsonb, 'income_other', false, '76', 1770),
  ('AL', 'default', '78', 'Rimarrje amortizimi dhe provizionesh', '{"en":"Reversal of depreciation and provisions"}'::jsonb, 'income_other', false, null, 1780),
  ('AL', 'default', '781', 'Rimarrje amortizimi dhe provizionesh', '{"en":"Reversal of depreciation and provisions"}'::jsonb, 'income_other', false, '78', 1790)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('AL', 'ARK', 'Regjistri i arkës', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('AL', 'BLE', 'Regjistri i blerjeve', '{"en":"Purchase journal"}'::jsonb, 'purchase', 20),
  ('AL', 'BNK', 'Regjistri i bankës', '{"en":"Bank journal"}'::jsonb, 'bank', 30),
  ('AL', 'GJN', 'Regjistër i përgjithshëm', '{"en":"General journal"}'::jsonb, 'general', 50),
  ('AL', 'HAP', 'Regjistrimi i hapjes', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('AL', 'SHT', 'Regjistri i shitjeve', '{"en":"Sales journal"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('AL', 'AL-P-20', 'TVSH 20% — blerje brenda vendit', '{"en":"VAT 20% — domestic purchase"}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 48 dhe neni 68 — e drejta e zbritjes së TVSH-së mbi blerjet e përdorura për qëllime të veprimtarisë ekonomike të tatueshme; neni 75, shkronja «a» — kriteri i zotërimit të një fature të lëshuar sipas neneve 96-105.', null, null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-P-IMPORT-20', 'TVSH 20% — import mallrash', '{"en":"VAT 20% — import of goods"}'::jsonb, null, 'percent', 20, 'purchase', 'import', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 50 — shkalla e TVSH-së në importim është ajo e zbatueshme për shitjen e të njëjtit mall brenda territorit; neni 34 — lindja e tatimit dhe kërkueshmëria ndodhin kur importimi kryhet; neni 75, shkronja «c» — e drejta e zbritjes kërkon dokumentin doganor të çlirimit për qarkullim të lirë, ku shënohet shuma e TVSH-së së paguar.', null, null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-P-REVCHG-20', 'TVSH 20% — vetëngarkim mbi shërbime të marra nga jashtë', '{"en":"VAT 20% — self-assessment on services received from abroad"}'::jsonb, null, 'percent', 20, 'purchase', 'foreign_services_received', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 86, pika 2 — TVSH-ja paguhet nga personi i tatueshëm marrës i shërbimeve të përcaktuara në nenin 24, pika 1 (rregulli i përgjithshëm i vendit të furnizimit të shërbimeve mes personave të tatueshëm), kur furnizuesi nuk është i vendosur në Republikën e Shqipërisë; neni 75, shkronja «ç» — e drejta e zbritjes kërkon formalitetet e përcaktuara me udhëzim të Ministrit të Financave. Shqipëria është jashtë sistemit të përbashkët të TVSH-së; ky mekanizëm i vetëngarkimit korrespondon me kategorinë ''foreign_services_received'' të docs/packs.md dhe jo me një ''reverse charge'' brenda BE-së.', null, null, 90, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-S-20', 'TVSH 20% — shitje me shkallë standarde', '{"en":"VAT 20% — standard-rated sale"}'::jsonb, null, 'percent', 20, 'sale', 'domestic', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 48 — shkalla standarde e TVSH-së për furnizimet e mallrave dhe shërbimeve, e aplikuar si përqindje e vlerës së tatueshme, është 20%; neni 32 — lindja dhe kërkueshmëria e tatimit ndodhin kur furnizimi kryhet.', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-S-6-ACCOM', 'TVSH 6% — shërbimi i akomodimit dhe i strukturave akomoduese', '{"en":"VAT 6% — accommodation service"}'::jsonb, null, 'percent', 6, 'sale', 'domestic', date '2017-06-05', null, 'Ligji Nr. 92/2014, neni 49, pika 3, shtuar me Ligjin Nr. 71/2017 — shkalla e reduktuar 6% zbatohet për furnizimin e shërbimit të akomodimit në strukturat akomoduese; Buletini Fiskal 2024 (Ministria e Financave), pika II.1.1, konfirmon normën 6% për akomodimin ende në fuqi për vitin 2024, si dhe shtrirjen e saj te shërbimet e strukturave ''Hotel/Resort me pesë yje, status special'' me markë tregtare të njohur ndërkombëtarisht dhe te akomodimi/restoranti (pa pije) i agroturizmit të certifikuar.', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-S-6-BOOKS', 'TVSH 6% — furnizimi i librave të çdo lloji', '{"en":"VAT 6% — supply of books"}'::jsonb, null, 'percent', 6, 'sale', 'domestic', date '2021-01-01', null, 'Buletini Fiskal 2024 (Ministria e Financave), pika II.1.1 — shkalla e reduktuar 6% zbatohet për furnizimin e librave të çdo lloji. Ligji Nr. 92/2014, neni 53, shkronja «j», në tekstin origjinal të vitit 2014, e trajtonte furnizimin e librave si të përjashtuar nga TVSH-ja; kërkimi për këtë paketim nuk ka mundur të gjejë numrin e saktë të ligjit ndryshues që e ka kaluar librin nga furnizim i përjashtuar në furnizim me shkallë të reduktuar 6% — data e mësipërme (2021-01-01) është një supozim i arsyeshëm bazuar në kohën kur norma 6% e librave shfaqet në praktikën e administratës, dhe duhet verifikuar me një kontabilist vendas, siç shënohet në README.md.', 'S', null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'buletini-fiskal-2024', null, null, null, null),
  ('AL', 'AL-S-EXEMPT-FIN', 'Përjashtuar nga TVSH — shërbime financiare dhe sigurimi', '{"en":"VAT exempt — financial and insurance services"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 53, shkronjat «a»-«d» — janë furnizime të përjashtuara nga TVSH-ja shërbimet e sigurimit dhe risigurimit, dhënia dhe negocimi i kredive, garancitë e kredive, dhe transaksionet mbi llogaritë, depozitat, valutën dhe letrat me vlerë.', 'E', null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-S-EXEMPT-RENT', 'Përjashtuar nga TVSH — dhënie me qira e pasurisë së paluajtshme', '{"en":"VAT exempt — rental of immovable property"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 53, shkronja «h» — dhënia me qira e pasurive të paluajtshme është e përjashtuar nga TVSH-ja, me përjashtimet e numëruara në nën-shkronjat (i)-(v) të së njëjtës shkronjë (qira deri në dy muaj, strehim hotelier, parkim, pajisje të fiksuara, kasaforta), të cilat mbeten të tatueshme dhe nuk përdorin këtë kod.', 'E', null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null),
  ('AL', 'AL-S-EXPORT', 'TVSH 0% — eksport mallrash', '{"en":"VAT 0% — export of goods"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 57 (KREU VIII, furnizimet me shkallë zero) — trajtohet me shkallë zero për qind furnizimi i mallrave të eksportuara jashtë territorit doganor të Republikës së Shqipërisë. Shqipëria është jashtë sistemit të përbashkët të TVSH-së të Bashkimit Evropian (Direktiva 2006/112/KE, neni 5(2)); asnjë kod VATEX dhe asnjë nga trajtimet ''intracom_*'' nuk zbatohen këtu, siç shënohet për vendet jashtë BE-së në docs/packs.md.', 'G', null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ligji-92-2014', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('AL-P-20', 'invoice', 'base', 100, null, 'BVB', array['BVB']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-P-20', 'invoice', 'tax', 100, '4426', 'BVT', array['BVT']::text[], 100, 'AL-TVSH-FDP', 20),
    ('AL-P-20', 'credit_note', 'base', 100, null, 'BVB', array['BVB']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-P-20', 'credit_note', 'tax', 100, '4426', 'BVT', array['BVT']::text[], -100, 'AL-TVSH-FDP', 20),
    ('AL-P-IMPORT-20', 'invoice', 'base', 100, null, 'BIB', array['BIB']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-P-IMPORT-20', 'invoice', 'tax', 100, '4456', 'BIT', array['BIT']::text[], 100, 'AL-TVSH-FDP', 20),
    ('AL-P-IMPORT-20', 'credit_note', 'base', 100, null, 'BIB', array['BIB']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-P-IMPORT-20', 'credit_note', 'tax', 100, '4456', 'BIT', array['BIT']::text[], -100, 'AL-TVSH-FDP', 20),
    ('AL-P-REVCHG-20', 'invoice', 'base', 100, null, 'AGB', array['AGB']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-P-REVCHG-20', 'invoice', 'tax', -100, '44281', 'AGT', array['AGT']::text[], 100, 'AL-TVSH-FDP', 20),
    ('AL-P-REVCHG-20', 'invoice', 'tax', 100, '44282', 'AGZ', array['AGZ']::text[], 100, 'AL-TVSH-FDP', 30),
    ('AL-P-REVCHG-20', 'credit_note', 'base', 100, null, 'AGB', array['AGB']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-P-REVCHG-20', 'credit_note', 'tax', -100, '44281', 'AGT', array['AGT']::text[], -100, 'AL-TVSH-FDP', 20),
    ('AL-P-REVCHG-20', 'credit_note', 'tax', 100, '44282', 'AGZ', array['AGZ']::text[], -100, 'AL-TVSH-FDP', 30),
    ('AL-S-20', 'invoice', 'base', 100, null, 'S20B', array['S20B']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-S-20', 'invoice', 'tax', 100, '4427', 'S20T', array['S20T']::text[], 100, 'AL-TVSH-FDP', 20),
    ('AL-S-20', 'credit_note', 'base', 100, null, 'S20B', array['S20B']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-S-20', 'credit_note', 'tax', 100, '4427', 'S20T', array['S20T']::text[], -100, 'AL-TVSH-FDP', 20),
    ('AL-S-6-ACCOM', 'invoice', 'base', 100, null, 'S06B', array['S06B']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-S-6-ACCOM', 'invoice', 'tax', 100, '4427', 'S06T', array['S06T']::text[], 100, 'AL-TVSH-FDP', 20),
    ('AL-S-6-ACCOM', 'credit_note', 'base', 100, null, 'S06B', array['S06B']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-S-6-ACCOM', 'credit_note', 'tax', 100, '4427', 'S06T', array['S06T']::text[], -100, 'AL-TVSH-FDP', 20),
    ('AL-S-6-BOOKS', 'invoice', 'base', 100, null, 'S06B', array['S06B']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-S-6-BOOKS', 'invoice', 'tax', 100, '4427', 'S06T', array['S06T']::text[], 100, 'AL-TVSH-FDP', 20),
    ('AL-S-6-BOOKS', 'credit_note', 'base', 100, null, 'S06B', array['S06B']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-S-6-BOOKS', 'credit_note', 'tax', 100, '4427', 'S06T', array['S06T']::text[], -100, 'AL-TVSH-FDP', 20),
    ('AL-S-EXEMPT-FIN', 'invoice', 'base', 100, null, 'SEXE', array['SEXE']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-S-EXEMPT-FIN', 'credit_note', 'base', 100, null, 'SEXE', array['SEXE']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-S-EXEMPT-RENT', 'invoice', 'base', 100, null, 'SEXE', array['SEXE']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-S-EXEMPT-RENT', 'credit_note', 'base', 100, null, 'SEXE', array['SEXE']::text[], -100, 'AL-TVSH-FDP', 10),
    ('AL-S-EXPORT', 'invoice', 'base', 100, null, 'EXP0', array['EXP0']::text[], 100, 'AL-TVSH-FDP', 10),
    ('AL-S-EXPORT', 'credit_note', 'base', 100, null, 'EXP0', array['EXP0']::text[], -100, 'AL-TVSH-FDP', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'AL' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('AL', 'AL-TVSH-FDP', 'Deklarata e TVSH-së — Formulari i Deklarimit dhe Pagesës (FDP)', array['month']::declaration_period[], 'month'::declaration_period, date '2015-01-01', null, 'Ligji Nr. 92/2014, neni 106 — çdo person i tatueshëm duhet të dorëzojë një deklaratë TVSH-je; neni 107, pika 1 dhe 2 — deklarata dorëzohet jo më vonë se 14 ditë pas përfundimit të periudhës tatimore, e cila është muaji kalendarik. Neni 107, pika 5, lejon Ministrin e Financave të caktojë me udhëzim një periudhë tatimore më të gjatë për ndonjë kategori tatimpaguesish; kërkimi për këtë paketim ka gjetur një referencë administrative për një kategori me deklarim tremujor për tatimpagues me qarkullim 2-5 milionë lekë, praktikë e mëparshme e lidhur me pragun e vjetër të regjistrimit (2 milionë lekë) — e pambuluar nga ky pack, siç shënohet në README.md, pasi pragu aktual i regjistrimit (10 milionë lekë, VKM 576/2020) e ka lënë pa objekt shumicën e rasteve të asaj kategorie. Kutitë e mëposhtme janë emërtimet e vetë këtij paketimi, jo numra rreshtash të një formulari me kuti të numëruara: kërkimi i këtij paketimi ka gjetur vetëm kategoritë me emra të Librit të Shitjeve dhe Librit të Blerjeve (burimi «deklarata-tvsh-librat»), të cilat FDP-ja i mbledh; asnjë kopje e drejtpërdrejtë dhe e verifikueshme e ekranit të vetë formularit FDP nuk është gjetur, siç ndodhi edhe me ekranin e e-Beyanname turk (shih packs/tr).', true,'day_of_month_after_period'::filing_deadline_rule, 14, null, 'Ligji Nr. 92/2014, neni 107, pika 1 — deklarata e TVSH-së dorëzohet jo më vonë se 14 ditë pas përfundimit të periudhës tatimore; neni 89 — TVSH-ja e pagueshme paguhet jo më vonë se data e paraqitjes së deklaratës.', 'ligji-92-2014', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('AL', 'AL-TVSH-FDP', 'S20B', 'base', 'Vlera e tatueshme e shitjeve me shkallë standarde 20%', '{"en":"Taxable value of sales at the standard rate 20%"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 48; DEKLARATA E TVSH-SË — Librat e shitjes dhe blerjes: kategoria «shitje të tatueshme me TVSH 20%» e Librit të shitjeve.', 'deklarata-tvsh-librat'),
  ('AL', 'AL-TVSH-FDP', 'S20T', 'tax', 'TVSH e llogaritur mbi shitjet me shkallë standarde 20%', '{"en":"VAT computed on sales at the standard rate 20%"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 48.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'S06B', 'base', 'Vlera e tatueshme e shitjeve me shkallë të reduktuar 6%', '{"en":"Taxable value of sales at the reduced rate 6%"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 49, pika 3; Buletini Fiskal 2024, pika II.1.1.', 'buletini-fiskal-2024'),
  ('AL', 'AL-TVSH-FDP', 'S06T', 'tax', 'TVSH e llogaritur mbi shitjet me shkallë të reduktuar 6%', '{"en":"VAT computed on sales at the reduced rate 6%"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 49, pika 3.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'EXP0', 'base', 'Vlera e shitjeve me shkallë zero, eksporte', '{"en":"Value of sales at the zero rate, exports"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 57; DEKLARATA E TVSH-SË — Librat e shitjes dhe blerjes: kategoria «shitje me TVSH zero %, eksporte».', 'deklarata-tvsh-librat'),
  ('AL', 'AL-TVSH-FDP', 'SEXE', 'base', 'Vlera e shitjeve të përjashtuara nga TVSH-ja', '{"en":"Value of exempt sales"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 51 dhe neni 53; DEKLARATA E TVSH-SË — Librat e shitjes dhe blerjes: kategoria «shitje të përjashtuara».', 'deklarata-tvsh-librat'),
  ('AL', 'AL-TVSH-FDP', 'TDET', 'total', 'TVSH e llogaritur (detyrimi bruto i periudhës)', '{"en":"VAT computed (gross liability of the period)"}'::jsonb, 70, null, array['S20T', 'S06T', 'AGT']::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 76, pika 1 — TVSH-ja e llogaritur mbi vlerën totale të tatueshme të të gjitha furnizimeve të tatueshme të kryera gjatë periudhës tatimore.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'BVB', 'base', 'Vlera e tatueshme e blerjeve brenda vendit me TVSH të zbritshme', '{"en":"Taxable value of domestic purchases with deductible VAT"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 68; DEKLARATA E TVSH-SË — Librat e shitjes dhe blerjes: kategoria «blerje brenda vendit» e Librit të blerjeve.', 'deklarata-tvsh-librat'),
  ('AL', 'AL-TVSH-FDP', 'BVT', 'tax', 'TVSH e zbritshme mbi blerjet brenda vendit', '{"en":"Deductible VAT on domestic purchases"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 68 dhe neni 75, shkronja «a».', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'BIB', 'base', 'Vlera e tatueshme e importeve me TVSH të zbritshme', '{"en":"Taxable value of imports with deductible VAT"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 50 dhe neni 34; DEKLARATA E TVSH-SË — Librat e shitjes dhe blerjes: kategoria «importe» e Librit të blerjeve.', 'deklarata-tvsh-librat'),
  ('AL', 'AL-TVSH-FDP', 'BIT', 'tax', 'TVSH e paguar dhe e zbritshme në import', '{"en":"VAT paid and deductible on import"}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 75, shkronja «c».', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'AGB', 'base', 'Vlera e shërbimeve të marra nga jashtë, subjekt i vetëngarkimit', '{"en":"Value of services received from abroad, subject to self-assessment"}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 86, pika 2.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'AGT', 'tax', 'TVSH e vetëngarkuar mbi shërbimet e marra nga jashtë', '{"en":"Self-assessed VAT on services received from abroad"}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 86, pika 2.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'AGZ', 'tax', 'TVSH e zbritshme mbi vetëngarkimin e shërbimeve nga jashtë', '{"en":"Deductible VAT on the self-assessment of services from abroad"}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 75, shkronja «ç».', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'TZBR', 'total', 'TVSH e zbritshme (totali i periudhës)', '{"en":"Deductible VAT (total of the period)"}'::jsonb, 150, null, array['BVT', 'BIT', 'AGZ']::text[], '{}'::text[], null, null, false, false, null, 'Ligji Nr. 92/2014, neni 76, pika 1.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'TPAG', 'total', 'TVSH për t''u paguar', '{"en":"VAT payable"}'::jsonb, 160, null, array['TDET']::text[], array['TZBR']::text[], null, null, true, false, null, 'Ligji Nr. 92/2014, neni 76, pika 1 — kur TVSH-ja e llogaritur tejkalon TVSH-në e zbritshme, diferenca është TVSH-ja për t''u paguar.', 'ligji-92-2014'),
  ('AL', 'AL-TVSH-FDP', 'TBART', 'total', 'Teprica e TVSH-së e mbartur për periudhën pasardhëse', '{"en":"VAT credit carried forward to the following period"}'::jsonb, 170, null, array['TZBR']::text[], array['TDET']::text[], null, null, true, false, null, 'Ligji Nr. 92/2014, neni 76, pika 2 — kur TVSH-ja e zbritshme tejkalon TVSH-në e llogaritur, teprica mbartet për t''u zbritur në periudhën pasardhëse; neni 77 — rimbursimi mund të kërkohet pas 3 muajsh radhazi me tepricë, kur shuma e kërkuar tejkalon 400 000 lekë (procedurë e jashtme këtij formulari, jo një kuti e vet).', 'ligji-92-2014')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('AL-SKK2-BS', 'AL', 'default', 'Bilanci', 'balance_sheet', 'SKK 2', date '2015-01-01', null, 'Standardi Kombëtar i Kontabilitetit Nr. 2 «Paraqitja e Pasqyrave Financiare», Shtojca 1 «Zërat e bilancit». Ky pack transkripton zërat kryesorë të Shtojcës 1 (kolona «Zëri i bilancit»), duke i paraqitur aktivet afatgjata materiale dhe amortizimin e akumuluar në të njëjtin rresht (vlerë neto) dhe duke kombinuar disa nën-zëra që SKK 2 lejon t''i japë në shënimet shpjeguese në një rresht të vetëm të bilancit; nuk riprodhon zërat e pasqyrave të konsoliduara (aksionet e pakicës, kapitali i shoqërisë mëmë) as ata të veprimeve me instrumente derivativë apo grante, të cilat asnjë llogari e këtij paketimi nuk i kërkon. Shih README.md.', 'skk-2'),
  ('AL-SKK2-IS', 'AL', 'default', 'Pasqyra e të ardhurave dhe shpenzimeve', 'income_statement', 'SKK 2', date '2015-01-01', null, 'Standardi Kombëtar i Kontabilitetit Nr. 2, Shtojca 2, «Formati 1» (pasqyra sipas natyrës së shpenzimit) — SKK 2 lejon zbatimin e vetëm njërit prej dy formateve; ky pack zbaton Formatin 1. Disa zëra të Formatit 1 (fitimet/humbjet nga metoda e kapitalit, pjesa e fitimit për aksionarët e pakicës) i përkasin vetëm pasqyrave të konsoliduara dhe nuk transkriptohen, asnjë llogari e këtij paketimi nuk i kërkon. Shih README.md.', 'skk-2')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('AL-SKK2-BS', 'AL-BS-A-INTANG', null, 'Aktive afatgjata jomateriale (neto)', '{"en":"Intangible non-current assets (net)"}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-LAND', null, 'Toka', '{"en":"Land"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-PPE', null, 'Ndërtesa, makineri, pajisje dhe mjete transporti (neto)', '{"en":"Buildings, machinery, equipment and vehicles (net)"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-WIP', null, 'Aktive afatgjata në ndërtim e sipër', '{"en":"Non-current assets under construction"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-FIN-LT', null, 'Investime financiare afatgjata', '{"en":"Long-term financial investments"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-NONCURRENT', null, 'Totali i aktiveve afatgjata', '{"en":"Total non-current assets"}'::jsonb, 60, 1, true, array['AL-BS-A-INTANG', 'AL-BS-A-LAND', 'AL-BS-A-PPE', 'AL-BS-A-WIP', 'AL-BS-A-FIN-LT']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-INV', null, 'Inventari', '{"en":"Inventory"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-CLIENTS', null, 'Klientë', '{"en":"Customers"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-OTHREC', null, 'Debitorë të tjerë dhe llogari kalimtare', '{"en":"Other receivables and accruals"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-VATREC', null, 'TVSH dhe kredi tatimore të tjera', '{"en":"VAT and other tax credits"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-FIN-ST', null, 'Investime financiare afatshkurtra dhe thesari tjetër', '{"en":"Short-term financial investments and other treasury"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-CASH', null, 'Mjete monetare', '{"en":"Cash and cash equivalents"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-CURRENT', null, 'Totali i aktiveve afatshkurtra', '{"en":"Total current assets"}'::jsonb, 130, 1, true, array['AL-BS-A-INV', 'AL-BS-A-CLIENTS', 'AL-BS-A-OTHREC', 'AL-BS-A-VATREC', 'AL-BS-A-FIN-ST', 'AL-BS-A-CASH']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-A-TOTAL', null, 'TOTALI I AKTIVEVE', '{"en":"TOTAL ASSETS"}'::jsonb, 140, 1, true, array['AL-BS-A-NONCURRENT', 'AL-BS-A-CURRENT']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-E-CAPITAL', null, 'Kapitali themeltar (aksionar)', '{"en":"Share capital"}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-E-PREMIUM', null, 'Prime kapitali', '{"en":"Share premium"}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-E-RESERVES', null, 'Rezerva', '{"en":"Reserves"}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-E-RETAINED', null, 'Fitime (Humbje) të pashpërndara', '{"en":"Retained earnings (losses)"}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-E-RESULT', null, 'Fitimi (Humbja) e vitit financiar', '{"en":"Profit (loss) for the financial year"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-E-TOTAL', null, 'Totali i kapitalit', '{"en":"Total equity"}'::jsonb, 200, 1, true, array['AL-BS-E-CAPITAL', 'AL-BS-E-PREMIUM', 'AL-BS-E-RESERVES', 'AL-BS-E-RETAINED', 'AL-BS-E-RESULT']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-GRANTS', null, 'Grante dhe të ardhura të shtyra', '{"en":"Grants and deferred income"}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-PROV-LT', null, 'Provizione afatgjata', '{"en":"Non-current provisions"}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-DEBT-LT', null, 'Hua afatgjata dhe detyrime nga qiraja financiare', '{"en":"Long-term borrowings and finance lease liabilities"}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-NONCURRENT', null, 'Totali i pasiveve afatgjata', '{"en":"Total non-current liabilities"}'::jsonb, 240, 1, true, array['AL-BS-L-GRANTS', 'AL-BS-L-PROV-LT', 'AL-BS-L-DEBT-LT']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-SUPPLIERS', null, 'Furnitorë', '{"en":"Suppliers"}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-STAFF', null, 'Personeli dhe sigurimet shoqërore e shëndetësore', '{"en":"Staff and social/health insurance"}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-TAX', null, 'Tatimi mbi fitimin dhe taksa të tjera', '{"en":"Corporate income tax and other duties"}'::jsonb, 270, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-VATPAY', null, 'TVSH për t''u paguar dhe operacione të veçanta', '{"en":"VAT payable and special operations"}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-BANKLOAN-ST', null, 'Kredi bankare afatshkurtra', '{"en":"Short-term bank loans"}'::jsonb, 290, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-GROUP', null, 'Grupi, ortakët dhe dividentë për t''u paguar', '{"en":"Group, shareholders and dividends payable"}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-OTHPAY', null, 'Kreditorë të tjerë dhe llogari kalimtare', '{"en":"Other creditors and accruals"}'::jsonb, 310, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-CURRENT', null, 'Totali i pasiveve afatshkurtra', '{"en":"Total current liabilities"}'::jsonb, 320, 1, true, array['AL-BS-L-SUPPLIERS', 'AL-BS-L-STAFF', 'AL-BS-L-TAX', 'AL-BS-L-VATPAY', 'AL-BS-L-BANKLOAN-ST', 'AL-BS-L-GROUP', 'AL-BS-L-OTHPAY']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-L-TOTAL', null, 'Totali i pasiveve', '{"en":"Total liabilities"}'::jsonb, 330, 1, true, array['AL-BS-L-NONCURRENT', 'AL-BS-L-CURRENT']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-BS', 'AL-BS-LE-TOTAL', null, 'TOTALI I PASIVEVE DHE KAPITALIT', '{"en":"TOTAL LIABILITIES AND EQUITY"}'::jsonb, 340, 1, true, array['AL-BS-E-TOTAL', 'AL-BS-L-TOTAL']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-SALES', null, 'Shitjet neto', '{"en":"Net sales"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-OTHINC', null, 'Të ardhura të tjera nga veprimtaritë e shfrytëzimit', '{"en":"Other operating income"}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-STOCKVAR', null, 'Ndryshimet në inventarin e produkteve të gatshme dhe punës në proces', '{"en":"Changes in inventories of finished goods and work in progress"}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-COGS', null, 'Mallrat, lëndët e para dhe shërbimet', '{"en":"Goods, raw materials and services consumed"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-OTHOPEX', null, 'Shpenzime të tjera nga veprimtaritë e shfrytëzimit', '{"en":"Other operating expenses"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-STAFFCOST', null, 'Shpenzime të personelit', '{"en":"Staff costs"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-DEPREC', null, 'Rënia në vlerë (zhvlerësimi) dhe amortizimi', '{"en":"Depreciation, amortisation and impairment"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-OPRESULT', null, 'Fitimi (Humbja) nga veprimtaritë e shfrytëzimit', '{"en":"Profit (loss) from operating activities"}'::jsonb, 80, 1, true, array['AL-IS-SALES', 'AL-IS-OTHINC', 'AL-IS-STOCKVAR']::text[], array['AL-IS-COGS', 'AL-IS-OTHOPEX', 'AL-IS-STAFFCOST', 'AL-IS-DEPREC']::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-FININC', null, 'Të ardhura financiare', '{"en":"Financial income"}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-FXGAIN', null, 'Fitime nga kursi i këmbimit', '{"en":"Foreign exchange gains"}'::jsonb, 100, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-FINEXP', null, 'Shpenzime financiare', '{"en":"Financial expenses"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-FXLOSS', null, 'Humbje nga kursi i këmbimit', '{"en":"Foreign exchange losses"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-FINRESULT', null, 'Totali i të ardhurave dhe shpenzimeve financiare', '{"en":"Total financial income and expenses"}'::jsonb, 130, 1, true, array['AL-IS-FININC', 'AL-IS-FXGAIN']::text[], array['AL-IS-FINEXP', 'AL-IS-FXLOSS']::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-PRETAX', null, 'Fitimi (Humbja) para tatimit', '{"en":"Profit (loss) before tax"}'::jsonb, 140, 1, true, array['AL-IS-OPRESULT', 'AL-IS-FINRESULT']::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-TAXEXP', null, 'Shpenzimi i tatimit mbi fitimin', '{"en":"Corporate income tax expense"}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AL-SKK2-IS', 'AL-IS-NETRESULT', null, 'Fitimi (Humbja) neto e vitit financiar', '{"en":"Net profit (loss) for the financial year"}'::jsonb, 160, 1, true, array['AL-IS-PRETAX']::text[], array['AL-IS-TAXEXP']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('AL-SKK2-BS', 'AL-BS-A-INTANG', 10, 'account_code', '201', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INTANG', 20, 'account_code', '203', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INTANG', 30, 'account_code', '205', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INTANG', 40, 'account_code', '207', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INTANG', 50, 'account_code', '208', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INTANG', 60, 'account_code', '280', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-LAND', 10, 'account_code', '211', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 10, 'account_code', '212', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 20, 'account_code', '2131', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 30, 'account_code', '2133', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 40, 'account_code', '214', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 50, 'account_code', '2811', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 60, 'account_code', '2813', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 70, 'account_code', '2814', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-PPE', 80, 'account_code', '291', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-WIP', 10, 'account_code', '231', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-WIP', 20, 'account_code', '232', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-FIN-LT', 10, 'account_code', '261', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-FIN-LT', 20, 'account_code', '267', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 10, 'account_code', '301', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 20, 'account_code', '302', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 30, 'account_code', '303', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 40, 'account_code', '331', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 50, 'account_code', '332', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 60, 'account_code', '351', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 70, 'account_code', '371', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 80, 'account_code', '381', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 90, 'account_code', '391', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-INV', 100, 'account_code', '397', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CLIENTS', 10, 'account_code', '411', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CLIENTS', 20, 'account_code', '413', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CLIENTS', 30, 'account_code', '418', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CLIENTS', 40, 'account_code', '491', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-OTHREC', 10, 'account_code', '409', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-OTHREC', 20, 'account_code', '425', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-OTHREC', 30, 'account_code', '461', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-OTHREC', 40, 'account_code', '471', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-VATREC', 10, 'account_code', '4424', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-VATREC', 20, 'account_code', '4426', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-VATREC', 30, 'account_code', '44282', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-VATREC', 40, 'account_code', '4456', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-FIN-ST', 10, 'account_code', '508', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-FIN-ST', 20, 'account_code', '541', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-FIN-ST', 30, 'account_code', '542', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-FIN-ST', 40, 'account_code', '581', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CASH', 10, 'account_code', '512', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CASH', 20, 'account_code', '514', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CASH', 30, 'account_code', '531', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-A-CASH', 40, 'account_code', '534', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-CAPITAL', 10, 'account_code', '101', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-PREMIUM', 10, 'account_code', '104', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-RESERVES', 10, 'account_code', '105', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-RESERVES', 20, 'account_code', '1061', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-RESERVES', 30, 'account_code', '1063', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-RESERVES', 40, 'account_code', '1068', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-RETAINED', 10, 'account_code', '117', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-E-RESULT', 10, 'account_code', '121', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-GRANTS', 10, 'account_code', '131', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-PROV-LT', 10, 'account_code', '151', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-PROV-LT', 20, 'account_code', '158', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-DEBT-LT', 10, 'account_code', '162', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-DEBT-LT', 20, 'account_code', '166', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-DEBT-LT', 30, 'account_code', '167', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-SUPPLIERS', 10, 'account_code', '401', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-SUPPLIERS', 20, 'account_code', '403', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-SUPPLIERS', 30, 'account_code', '404', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-SUPPLIERS', 40, 'account_code', '408', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-STAFF', 10, 'account_code', '421', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-STAFF', 20, 'account_code', '427', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-STAFF', 30, 'account_code', '431', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-STAFF', 40, 'account_code', '437', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-TAX', 10, 'account_code', '441', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-TAX', 20, 'account_code', '445', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-TAX', 30, 'account_code', '446', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-VATPAY', 10, 'account_code', '4423', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-VATPAY', 20, 'account_code', '4427', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-VATPAY', 30, 'account_code', '44281', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-BANKLOAN-ST', 10, 'account_code', '519', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-GROUP', 10, 'account_code', '455', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-GROUP', 20, 'account_code', '456', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-GROUP', 30, 'account_code', '457', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-OTHPAY', 10, 'account_code', '419', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-OTHPAY', 20, 'account_code', '462', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-OTHPAY', 30, 'account_code', '472', null, null, 'any'),
    ('AL-SKK2-BS', 'AL-BS-L-OTHPAY', 40, 'account_code', '473', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-SALES', 10, 'account_code', '700', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-SALES', 20, 'account_code', '701', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-SALES', 30, 'account_code', '706', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-SALES', 40, 'account_code', '709', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHINC', 10, 'account_code', '741', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHINC', 20, 'account_code', '758', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHINC', 30, 'account_code', '781', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-STOCKVAR', 10, 'account_code', '711', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-COGS', 10, 'account_code', '600', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-COGS', 20, 'account_code', '601', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-COGS', 30, 'account_code', '602', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-COGS', 40, 'account_code', '605', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-COGS', 50, 'account_code', '609', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 10, 'account_code', '611', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 20, 'account_code', '612', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 30, 'account_code', '613', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 40, 'account_code', '614', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 50, 'account_code', '621', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 60, 'account_code', '622', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 70, 'account_code', '623', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 80, 'account_code', '624', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 90, 'account_code', '625', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 100, 'account_code', '626', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 110, 'account_code', '627', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 120, 'account_code', '628', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 130, 'account_code', '635', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 140, 'account_code', '654', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-OTHOPEX', 150, 'account_code', '6588', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-STAFFCOST', 10, 'account_code', '641', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-STAFFCOST', 20, 'account_code', '645', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-DEPREC', 10, 'account_code', '681', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-DEPREC', 20, 'account_code', '685', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FININC', 10, 'account_code', '761', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FININC', 20, 'account_code', '766', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FININC', 30, 'account_code', '768', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FXGAIN', 10, 'account_code', '765', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FINEXP', 10, 'account_code', '663', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FINEXP', 20, 'account_code', '666', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FINEXP', 30, 'account_code', '668', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-FXLOSS', 10, 'account_code', '665', null, null, 'any'),
    ('AL-SKK2-IS', 'AL-IS-TAXEXP', 10, 'account_code', '691', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('AL', 'Albania', '{"en":"Albania"}'::jsonb, array['sq', 'en']::text[], 'ALL', '411', '401', '473', '6588', '117', '700', '600', '512', '531', 'SHT', 'BLE', 'GJN', 'sq', 'result_accounts', '121', '121', null, 'HAP', 'half_up', default, '765', '665', null, null, null, null, '4423', '4424', 'Regjistrimi i hapjes', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Ligji Nr. 92/2014, neni 99, pika 1, 3 dhe 4 — fatura lëshohet në momentin e furnizimit të mallit ose të kryerjes së shërbimit; neni 98 përjashton nga detyrimi i faturës tatimore me përmbajtje të plotë furnizimet deri në 40 000 lekë, përveç kur blerësi e kërkon. Ligji nuk imponon një format specifik numrash rendorë me vit e numërues; formati këtu është një shembull i pranueshëm dhe jo i vetmi.',
  numbering_source_key          = 'ligji-92-2014',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Ligji Nr. 92/2014, neni 32 — lindja e tatimit ndodh dhe TVSH-ja bëhet e kërkueshme kur furnizimi i mallrave ose shërbimeve kryhet, rregulli i përgjithshëm; neni 33, pika 3 — për çdo pagesë të kryer para furnizimit, TVSH-ja lind në momentin e arkëtimit; pika 4 — kur fatura tatimore lëshohet përpara furnizimit, TVSH-ja bëhet e kërkueshme në momentin e lëshimit të faturës. Furnizimi është rregulli, fatura e lëshuar më parë përjashtimi — e njëjta strukturë si neni 16/17 i ligjit belg dhe neni 21-24, par. 1, i ligjit luksemburgez.',
  tax_point_source_key          = 'ligji-92-2014',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Ligji Nr. 92/2014, neni 95, shkronja «c» — një notë krediti apo notë debiti trajtohet si faturë vetëm nëse ndryshon dhe i referohet në mënyrë specifike e të qartë faturës fillestare, pasi kjo e fundit është lëshuar. Vini re shenjën e kundërt me zakonin: sipas nenit 95(c)(i), «nota e kreditit» RRIT detyrimin e TVSH-së, dhe «nota e debitit» (c)(ii) e ZBRET — e kundërta e emërtimit të zakonshëm anglez apo francez, ku një «credit note»/«note de crédit» zvogëlon shitjen. Dokumenti i korrigjimit të Ekwo (credit_note, që zvogëlon një shitje të postuar) korrespondon pra me «notën e debitit» të nenit 95(c)(ii) të këtij ligji, jo me «notën e kreditit» të tij — shih README.md.',
  posted_edit_policy_source_key = 'ligji-92-2014',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Ligji Nr. 87/2019, datë 18.12.2019, «Për faturën dhe sistemin e monitorimit të qarkullimit» (fiskalizimi) detyron çdo tatimpagues të lëshojë fatura elektronike, të nënshkruara me certifikatë elektronike të lëshuar nga AKSHI, dhe t''i transmetojë në kohë reale në Platformën Qendrore të Faturave të administratës tatimore (CIS), e cila u kthen një Numër Identifikues i Vlefshmërisë së Faturës (NIVF) përpara se fatura t''i konsiderohet e vlefshme — një model *clearance*, jo një shkëmbim i drejtpërdrejtë ndërmjet palëve. Zbatimi u bë me faza, sipas njoftimit të Drejtorisë së Përgjithshme të Tatimeve: transaksionet pa para në dorë ndërmjet tatimpaguesve dhe organeve publike, nga 1 janari 2021; transaksionet pa para në dorë ndërmjet tatimpaguesve, nga 1 korrik 2021; të gjitha transaksionet me para në dorë, pavarësisht xhiros, nga 1 shtator 2021. `mandatory_from` mbetet bosh sepse fusha, sipas skemës së këtij formati, emërton ditën kur bëhet i detyrueshëm profili i EN 16931 që `profile` do të kishte emërtuar — dhe asnjë profil i tillë nuk ekziston këtu; datat e sipërpërmendura mbeten vetëm në këtë `legal_reference`, si te pako `tr` dhe `ro` për mekanizma të ngjashëm *clearance* jo-EN16931. `profile` mbetet bosh: formati i faturës elektronike shqiptare nuk është ndërtuar mbi modelin semantik të EN 16931 (as Peppol BIS, as Factur-X, as XRechnung, as ndonjë PINT) por mbi skemën e vet XML të Drejtorisë së Përgjithshme të Tatimeve, dhe asnjë pjesë e packages/formats/ nuk e shkruan apo transmeton sot këtë skemë — shih seksionin «From Albania» të docs/international.md. `party_scheme` dhe `vat_scheme` mbeten bosh për të njëjtën arsye: një tatimpagues shqiptar identifikohet me NIPT-in e vet (Numri i Identifikimit të Personit të Tatueshëm), jo me një skemë ISO 6523 të regjistruar në rrjetin Peppol.',
  einvoice_source_key           = 'ligji-87-2019',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'AL';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('AL', 'reverse_charge', 'reverse_charge', 'TVSH-ja deklarohet dhe paguhet nga marrësi i shërbimit, sipas pikës 2, të nenit 86, të Ligjit Nr. 92/2014.', '{"en":"VAT is declared and paid by the recipient of the service, under article 86, point 2, of Ligji Nr. 92/2014."}'::jsonb, 10, date '1970-01-01', null, 'Ligji Nr. 92/2014, neni 86, pika 2 — TVSH-ja është e pagueshme nga personi i tatueshëm, të cilit i janë furnizuar shërbimet e përcaktuara në nenin 24, pika 1, nëse furnizuesi nuk është i vendosur në territorin e Republikës së Shqipërisë.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
