-- Ekwo OS — Crna Gora: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/me at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build me`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Zakon o porezu na dodatu vrijednost (prečišćeni tekst koji uključuje Zakon o izmjenama i dopuni, "Službeni list Crne Gore", br. 094/24 od 30.09.2024, u primjeni od 01.01.2025) (Uprava prihoda i carina / Ministarstvo finansija Crne Gore (gov.me))
--     https://www.gov.me/dokumenta/2c9e967b-8998-4356-b601-2f0ecd85cb6f
--   Obrazac PR PDV-2 — Mjesečna prijava za obračun poreza na dodatu vrijednost, sa uputstvom za popunjavanje (Uprava prihoda i carina Crne Gore)
--     https://wapi.gov.me/download/e3d2b1f2-341b-487e-8e2a-d77868bbf52e?version=1.0
--   ePorezi / Elektronska prijava — portal za podnošenje poreskih prijava (Uprava prihoda i carina Crne Gore)
--     https://eprijava.tax.gov.me/
--   Zakon o računovodstvu ("Službeni list Crne Gore", br. 052/16 od 09.08.2016), usklađen sa Direktivom 2013/34/EU (Institut internih revizora Crne Gore / Ministarstvo finansija)
--     https://iircg.co.me/wp-content/uploads/2022/01/Zakon-o-racunovodstvu.pdf
--   Pravilnik o kontnom okviru i sadržini računa u kontnom okviru za privredna društva i druga pravna lica (izvorno "Službeni list CG", br. 5/11 od 21.01.2011, zamijenjen Pravilnikom objavljenim u "Službenom listu Crne Gore", br. 11/20 od 06.03.2020, iste strukture klasa i grupa računa) (Ministarstvo finansija Crne Gore)
--     https://www.ucg.ac.me/skladiste/blog_5675/objava_150439/fajlovi/Kontni%20okvir%20za%20privredna%20drustva%20i%20druga%20pravna%20lica.pdf
--   Iskaz o finansijskoj poziciji /Bilans stanja/ i Iskaz o ukupnom rezultatu /Bilans uspjeha/ — obrasci usklađeni sa članom 4. Zakona o računovodstvu ("Sl. list CG" broj 052/16) i Direktivom 2013/34/EU, primjer popunjenog iskaza koji prikazuje sve pozicije i AOP brojeve obrasca (Uprava prihoda i carina Crne Gore (obrazac), primjer podnesenog iskaza)
--     https://www.nvocoe.me/dms/izvjestaji/Finansijski%20izvje%C5%A1taj%20-%202021%20(NVO%20COE).pdf
--   Zakon o fiskalizaciji u prometu proizvoda i usluga ("Službeni list Crne Gore", br. 046/19 od 07.08.2019, sa izmjenama 073/19, 080/20 i 008/21) (Ministarstvo finansija Crne Gore (gov.me))
--     https://www.gov.me/dokumenta/6a29403c-2397-4107-a591-7aac91c38ecf
--   Elektronska fiskalizacija — portal za registraciju i fiskalizaciju prometa u realnom vremenu (Uprava prihoda i carina Crne Gore)
--     https://www.elektronskafiskalizacija.me/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('ME', 'Crna Gora', '0.1.0', date '2026-09-26', '20260917170000', 'community', null, null, 'baf6c018ea6e5a35e2bb583f3fe1a18287218c6cb5cffd538284c43851f6cf63', '[{"key":"pdv-zakon","title":"Zakon o porezu na dodatu vrijednost (prečišćeni tekst koji uključuje Zakon o izmjenama i dopuni, \"Službeni list Crne Gore\", br. 094/24 od 30.09.2024, u primjeni od 01.01.2025)","publisher":"Uprava prihoda i carina / Ministarstvo finansija Crne Gore (gov.me)","url":"https://www.gov.me/dokumenta/2c9e967b-8998-4356-b601-2f0ecd85cb6f","consulted_on":"2026-09-26","kind":"law"},{"key":"pdv-prijava-obrazac","title":"Obrazac PR PDV-2 — Mjesečna prijava za obračun poreza na dodatu vrijednost, sa uputstvom za popunjavanje","publisher":"Uprava prihoda i carina Crne Gore","url":"https://wapi.gov.me/download/e3d2b1f2-341b-487e-8e2a-d77868bbf52e?version=1.0","consulted_on":"2026-09-26","kind":"form"},{"key":"eprijava-portal","title":"ePorezi / Elektronska prijava — portal za podnošenje poreskih prijava","publisher":"Uprava prihoda i carina Crne Gore","url":"https://eprijava.tax.gov.me/","consulted_on":"2026-09-26","kind":"portal"},{"key":"racunovodstvo-zakon","title":"Zakon o računovodstvu (\"Službeni list Crne Gore\", br. 052/16 od 09.08.2016), usklađen sa Direktivom 2013/34/EU","publisher":"Institut internih revizora Crne Gore / Ministarstvo finansija","url":"https://iircg.co.me/wp-content/uploads/2022/01/Zakon-o-racunovodstvu.pdf","consulted_on":"2026-09-26","kind":"law"},{"key":"kontni-okvir","title":"Pravilnik o kontnom okviru i sadržini računa u kontnom okviru za privredna društva i druga pravna lica (izvorno \"Službeni list CG\", br. 5/11 od 21.01.2011, zamijenjen Pravilnikom objavljenim u \"Službenom listu Crne Gore\", br. 11/20 od 06.03.2020, iste strukture klasa i grupa računa)","publisher":"Ministarstvo finansija Crne Gore","url":"https://www.ucg.ac.me/skladiste/blog_5675/objava_150439/fajlovi/Kontni%20okvir%20za%20privredna%20drustva%20i%20druga%20pravna%20lica.pdf","consulted_on":"2026-09-26","kind":"regulation"},{"key":"fin-iskazi-obrazac","title":"Iskaz o finansijskoj poziciji /Bilans stanja/ i Iskaz o ukupnom rezultatu /Bilans uspjeha/ — obrasci usklađeni sa članom 4. Zakona o računovodstvu (\"Sl. list CG\" broj 052/16) i Direktivom 2013/34/EU, primjer popunjenog iskaza koji prikazuje sve pozicije i AOP brojeve obrasca","publisher":"Uprava prihoda i carina Crne Gore (obrazac), primjer podnesenog iskaza","url":"https://www.nvocoe.me/dms/izvjestaji/Finansijski%20izvje%C5%A1taj%20-%202021%20(NVO%20COE).pdf","consulted_on":"2026-09-26","kind":"form"},{"key":"fiskalizacija-zakon","title":"Zakon o fiskalizaciji u prometu proizvoda i usluga (\"Službeni list Crne Gore\", br. 046/19 od 07.08.2019, sa izmjenama 073/19, 080/20 i 008/21)","publisher":"Ministarstvo finansija Crne Gore (gov.me)","url":"https://www.gov.me/dokumenta/6a29403c-2397-4107-a591-7aac91c38ecf","consulted_on":"2026-09-26","kind":"law"},{"key":"efiskalizacija-portal","title":"Elektronska fiskalizacija — portal za registraciju i fiskalizaciju prometa u realnom vremenu","publisher":"Uprava prihoda i carina Crne Gore","url":"https://www.elektronskafiskalizacija.me/","consulted_on":"2026-09-26","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('ME', 'default', 'Kontni okvir za privredna društva i druga pravna lica', '{"en":"Chart of accounts for companies and other legal entities"}'::jsonb, true, 'companies', array['ME-FS-BS', 'ME-FS-IS']::text[], null, 'Pravilnik o kontnom okviru i sadržini računa u kontnom okviru za privredna društva i druga pravna lica ("Sl. list CG", br. 11/20, koji zamjenjuje Pravilnik iz 2011 — "Sl. list CG", br. 5/11, iste podjele na klase 0-9). Ovaj paket transkribuje klase 0 do 6 (stalna imovina, zalihe, kratkoročna potraživanja i gotovina, kapital, dugoročna rezervisanja i obaveze, rashodi, prihodi) i njihove najčešće korišćene grupe i konta prvog reda; klase 7 (otvaranje i zaključak računa), 8 (vanbilansna evidencija) i 9 (obračun troškova i učinaka) nijesu transkribovane jer ih socle ne zahtijeva — zatvaranje poslovne godine obavlja `close_fiscal_year()` preko uloga (`defaults.roles`), a vanbilansna evidencija i obračun troškova po mjestima troškova nijesu dio ovog izdanja. Uputstvo o primjeni Pravilnika izričito dozvoljava pravnim licima da uvedu podračune višeg reda uz zadržavanje brojčane oznake konta iz Kontnog okvira; na toj osnovi ovaj paket dodaje četvorocifrene podračune 2715/2717 (ulazni PDV po stopama od 15% i 7%, koje Kontni okvir iz 2011/2020 ne razlikuje jer je stopa od 15% uvedena tek 01.01.2025), 4711/4717 (odgovarajuće obaveze za PDV po izdatim fakturama) i 4698 (razlike po osnovu zaokruživanja, konto koji Kontni okvir ne imenuje posebno). Vidjeti README.md.', 'kontni-okvir')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('ME', 'default', '00', 'Neuplaćeni upisani kapital', '{"en":"Uncalled subscribed capital"}'::jsonb, 'asset_non_current', false, null, 10),
  ('ME', 'default', '000', 'Neuplaćene upisane akcije', '{"en":"Uncalled subscribed shares"}'::jsonb, 'asset_non_current', false, '00', 20),
  ('ME', 'default', '001', 'Neuplaćeni upisani udjeli', '{"en":"Uncalled subscribed capital contributions"}'::jsonb, 'asset_non_current', false, '00', 30),
  ('ME', 'default', '01', 'Nematerijalna ulaganja', '{"en":"Intangible assets"}'::jsonb, 'asset_fixed', false, null, 40),
  ('ME', 'default', '010', 'Ulaganja u razvoj', '{"en":"Development costs"}'::jsonb, 'asset_fixed', false, '01', 50),
  ('ME', 'default', '011', 'Koncesije patenti licence i slična prava', '{"en":"Concessions, patents, licences and similar rights"}'::jsonb, 'asset_fixed', false, '01', 60),
  ('ME', 'default', '012', 'Goodwill', '{"en":"Goodwill"}'::jsonb, 'asset_fixed', false, '01', 70),
  ('ME', 'default', '014', 'Ostala nematerijalna ulaganja', '{"en":"Other intangible assets"}'::jsonb, 'asset_fixed', false, '01', 80),
  ('ME', 'default', '015', 'Nematerijalna ulaganja u pripremi', '{"en":"Intangible assets under construction"}'::jsonb, 'asset_fixed', false, '01', 90),
  ('ME', 'default', '016', 'Avansi za nematerijalna ulaganja', '{"en":"Advances for intangible assets"}'::jsonb, 'asset_fixed', false, '01', 100),
  ('ME', 'default', '02', 'Nekretnine postrojenja oprema i biološka sredstva', '{"en":"Property, plant, equipment and biological assets"}'::jsonb, 'asset_fixed', false, null, 110),
  ('ME', 'default', '020', 'Zemljišta', '{"en":"Land"}'::jsonb, 'asset_fixed', false, '02', 120),
  ('ME', 'default', '021', 'Šume i višegodišnji zasadi', '{"en":"Forests and perennial plantations"}'::jsonb, 'asset_fixed', false, '02', 130),
  ('ME', 'default', '022', 'Građevinski objekti', '{"en":"Buildings"}'::jsonb, 'asset_fixed', false, '02', 140),
  ('ME', 'default', '023', 'Postrojenja i oprema', '{"en":"Plant and equipment"}'::jsonb, 'asset_fixed', false, '02', 150),
  ('ME', 'default', '024', 'Investicione nekretnine', '{"en":"Investment property"}'::jsonb, 'asset_fixed', false, '02', 160),
  ('ME', 'default', '025', 'Osnovno stado', '{"en":"Livestock"}'::jsonb, 'asset_fixed', false, '02', 170),
  ('ME', 'default', '026', 'Ostale nekretnine postrojenja i oprema', '{"en":"Other property, plant and equipment"}'::jsonb, 'asset_fixed', false, '02', 180),
  ('ME', 'default', '027', 'Nekretnine postrojenja oprema i biološka sredstva u pripremi', '{"en":"Property, plant, equipment and biological assets under construction"}'::jsonb, 'asset_fixed', false, '02', 190),
  ('ME', 'default', '028', 'Avansi za nekretnine postrojenja opremu i biološka sredstva', '{"en":"Advances for property, plant, equipment and biological assets"}'::jsonb, 'asset_fixed', false, '02', 200),
  ('ME', 'default', '029', 'Ulaganja na tuđim nekretninama postrojenjima i opremi', '{"en":"Leasehold improvements"}'::jsonb, 'asset_fixed', false, '02', 210),
  ('ME', 'default', '03', 'Dugoročni finansijski plasmani', '{"en":"Long-term financial investments"}'::jsonb, 'asset_non_current', false, null, 220),
  ('ME', 'default', '030', 'Učešća u kapitalu zavisnih pravnih lica', '{"en":"Investments in subsidiaries"}'::jsonb, 'asset_non_current', false, '03', 230),
  ('ME', 'default', '031', 'Učešća u kapitalu pridruženih pravnih lica', '{"en":"Investments in associates"}'::jsonb, 'asset_non_current', false, '03', 240),
  ('ME', 'default', '032', 'Učešća u kapitalu ostalih pravnih lica', '{"en":"Investments in other entities"}'::jsonb, 'asset_non_current', false, '03', 250),
  ('ME', 'default', '033', 'Dugoročni krediti povezanim pravnim licima', '{"en":"Long-term loans to related parties"}'::jsonb, 'asset_non_current', false, '03', 260),
  ('ME', 'default', '034', 'Dugoročni krediti u zemlji', '{"en":"Long-term loans in Montenegro"}'::jsonb, 'asset_non_current', false, '03', 270),
  ('ME', 'default', '035', 'Dugoročni krediti u inostranstvu', '{"en":"Long-term loans abroad"}'::jsonb, 'asset_non_current', false, '03', 280),
  ('ME', 'default', '036', 'Hartije od vrijednosti koje se drže do dospijeća', '{"en":"Held-to-maturity securities"}'::jsonb, 'asset_non_current', false, '03', 290),
  ('ME', 'default', '038', 'Ostali dugoročni finansijski plasmani', '{"en":"Other long-term financial investments"}'::jsonb, 'asset_non_current', false, '03', 300),
  ('ME', 'default', '04', 'Stalna sredstva namijenjena prodaji', '{"en":"Non-current assets held for sale"}'::jsonb, 'asset_non_current', false, null, 310),
  ('ME', 'default', '10', 'Zalihe materijala', '{"en":"Inventories of materials"}'::jsonb, 'asset_current', false, null, 320),
  ('ME', 'default', '101', 'Materijal', '{"en":"Materials"}'::jsonb, 'asset_current', false, '10', 330),
  ('ME', 'default', '102', 'Rezervni djelovi', '{"en":"Spare parts"}'::jsonb, 'asset_current', false, '10', 340),
  ('ME', 'default', '103', 'Alat i inventar', '{"en":"Tools and small inventory"}'::jsonb, 'asset_current', false, '10', 350),
  ('ME', 'default', '11', 'Nedovršena proizvodnja', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, null, 360),
  ('ME', 'default', '110', 'Nedovršena proizvodnja', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, '11', 370),
  ('ME', 'default', '111', 'Nedovršene usluge', '{"en":"Services in progress"}'::jsonb, 'asset_current', false, '11', 380),
  ('ME', 'default', '12', 'Gotovi proizvodi', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, null, 390),
  ('ME', 'default', '120', 'Gotovi proizvodi', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, '12', 400),
  ('ME', 'default', '13', 'Roba', '{"en":"Merchandise"}'::jsonb, 'asset_current', false, null, 410),
  ('ME', 'default', '131', 'Roba u magacinu', '{"en":"Merchandise in the warehouse"}'::jsonb, 'asset_current', false, '13', 420),
  ('ME', 'default', '132', 'Roba u prometu na veliko', '{"en":"Merchandise in wholesale trade"}'::jsonb, 'asset_current', false, '13', 430),
  ('ME', 'default', '134', 'Roba u prometu na malo', '{"en":"Merchandise in retail trade"}'::jsonb, 'asset_current', false, '13', 440),
  ('ME', 'default', '137', 'Roba na putu', '{"en":"Merchandise in transit"}'::jsonb, 'asset_current', false, '13', 450),
  ('ME', 'default', '15', 'Dati avansi', '{"en":"Advances paid"}'::jsonb, 'asset_prepayments', false, null, 460),
  ('ME', 'default', '150', 'Dati avansi za zalihe i usluge', '{"en":"Advances paid for inventories and services"}'::jsonb, 'asset_prepayments', false, '15', 470),
  ('ME', 'default', '20', 'Potraživanja po osnovu prodaje', '{"en":"Trade receivables"}'::jsonb, 'asset_current', false, null, 480),
  ('ME', 'default', '202', 'Kupci u zemlji', '{"en":"Domestic customers"}'::jsonb, 'asset_receivable', true, '20', 490),
  ('ME', 'default', '203', 'Kupci u inostranstvu', '{"en":"Foreign customers"}'::jsonb, 'asset_receivable', true, '20', 500),
  ('ME', 'default', '21', 'Potraživanja iz specifičnih poslova', '{"en":"Receivables from specific transactions"}'::jsonb, 'asset_current', false, null, 510),
  ('ME', 'default', '210', 'Potraživanja od izvoznika', '{"en":"Receivables from exporters"}'::jsonb, 'asset_current', false, '21', 520),
  ('ME', 'default', '22', 'Druga potraživanja', '{"en":"Other receivables"}'::jsonb, 'asset_current', false, null, 530),
  ('ME', 'default', '220', 'Potraživanja za kamatu i dividende', '{"en":"Receivables for interest and dividends"}'::jsonb, 'asset_current', false, '22', 540),
  ('ME', 'default', '221', 'Potraživanja od zaposlenih', '{"en":"Receivables from employees"}'::jsonb, 'asset_current', false, '22', 550),
  ('ME', 'default', '222', 'Potraživanja od državnih organa i organizacija', '{"en":"Receivables from state bodies and organisations"}'::jsonb, 'asset_current', false, '22', 560),
  ('ME', 'default', '23', 'Kratkoročni finansijski plasmani', '{"en":"Short-term financial investments"}'::jsonb, 'asset_current', false, null, 570),
  ('ME', 'default', '232', 'Kratkoročni krediti u zemlji', '{"en":"Short-term loans in Montenegro"}'::jsonb, 'asset_current', false, '23', 580),
  ('ME', 'default', '24', 'Gotovina i gotovinski ekvivalenti', '{"en":"Cash and cash equivalents"}'::jsonb, 'asset_cash', false, null, 590),
  ('ME', 'default', '241', 'Tekući računi', '{"en":"Current (business) accounts"}'::jsonb, 'asset_cash', false, '24', 600),
  ('ME', 'default', '243', 'Blagajna', '{"en":"Cash on hand"}'::jsonb, 'asset_cash', false, '24', 610),
  ('ME', 'default', '244', 'Devizni račun', '{"en":"Foreign-currency account"}'::jsonb, 'asset_cash', false, '24', 620),
  ('ME', 'default', '27', 'Porez na dodatu vrijednost', '{"en":"Value added tax"}'::jsonb, 'asset_current', false, null, 630),
  ('ME', 'default', '270', 'PDV u primljenim fakturama po opštoj stopi od 21%', '{"en":"VAT on purchase invoices at the standard rate of 21%"}'::jsonb, 'asset_current', false, '27', 640),
  ('ME', 'default', '271', 'PDV u primljenim fakturama po sniženim stopama', '{"en":"VAT on purchase invoices at the reduced rates"}'::jsonb, 'asset_current', false, '27', 650),
  ('ME', 'default', '2715', 'PDV u primljenim fakturama po sniženoj stopi od 15%', '{"en":"VAT on purchase invoices at the reduced rate of 15%"}'::jsonb, 'asset_current', false, '271', 660),
  ('ME', 'default', '2717', 'PDV u primljenim fakturama po sniženoj stopi od 7%', '{"en":"VAT on purchase invoices at the reduced rate of 7%"}'::jsonb, 'asset_current', false, '271', 670),
  ('ME', 'default', '274', 'PDV plaćen pri uvozu proizvoda po opštoj stopi', '{"en":"VAT paid on imports at the standard rate"}'::jsonb, 'asset_current', false, '27', 680),
  ('ME', 'default', '275', 'PDV plaćen pri uvozu proizvoda po sniženim stopama', '{"en":"VAT paid on imports at the reduced rates"}'::jsonb, 'asset_current', false, '27', 690),
  ('ME', 'default', '276', 'PDV obračunat na usluge inostranih lica', '{"en":"VAT self-assessed on services from foreign persons"}'::jsonb, 'asset_current', false, '27', 700),
  ('ME', 'default', '279', 'Potraživanja za više plaćeni porez na dodatu vrijednost', '{"en":"Receivable for VAT overpaid"}'::jsonb, 'asset_current', true, '27', 710),
  ('ME', 'default', '28', 'Aktivna vremenska razgraničenja', '{"en":"Prepayments and accrued income"}'::jsonb, 'asset_prepayments', false, null, 720),
  ('ME', 'default', '280', 'Unaprijed plaćeni troškovi', '{"en":"Prepaid expenses"}'::jsonb, 'asset_prepayments', false, '28', 730),
  ('ME', 'default', '281', 'Potraživanja za nefakturisani prihod', '{"en":"Receivables for unbilled revenue"}'::jsonb, 'asset_prepayments', false, '28', 740),
  ('ME', 'default', '288', 'Odložena poreska sredstva', '{"en":"Deferred tax assets"}'::jsonb, 'asset_non_current', false, '28', 750),
  ('ME', 'default', '30', 'Osnovni kapital', '{"en":"Share capital"}'::jsonb, 'equity', false, null, 760),
  ('ME', 'default', '300', 'Akcijski kapital', '{"en":"Share capital"}'::jsonb, 'equity', false, '30', 770),
  ('ME', 'default', '301', 'Udjeli društava sa ograničenom odgovornošću', '{"en":"Capital contributions of a limited liability company"}'::jsonb, 'equity', false, '30', 780),
  ('ME', 'default', '303', 'Državni kapital', '{"en":"State capital"}'::jsonb, 'equity', false, '30', 790),
  ('ME', 'default', '31', 'Neuplaćeni upisani kapital', '{"en":"Uncalled subscribed capital"}'::jsonb, 'equity', false, null, 800),
  ('ME', 'default', '310', 'Neuplaćene upisane akcije', '{"en":"Uncalled subscribed shares"}'::jsonb, 'equity', false, '31', 810),
  ('ME', 'default', '311', 'Neuplaćeni upisani udjeli', '{"en":"Uncalled subscribed capital contributions"}'::jsonb, 'equity', false, '31', 820),
  ('ME', 'default', '32', 'Rezerve', '{"en":"Reserves"}'::jsonb, 'equity', false, null, 830),
  ('ME', 'default', '320', 'Emisiona premija', '{"en":"Share premium"}'::jsonb, 'equity', false, '32', 840),
  ('ME', 'default', '321', 'Zakonske rezerve', '{"en":"Legal reserves"}'::jsonb, 'equity', false, '32', 850),
  ('ME', 'default', '322', 'Statutarne i druge rezerve', '{"en":"Statutory and other reserves"}'::jsonb, 'equity', false, '32', 860),
  ('ME', 'default', '33', 'Revalorizacione rezerve i nerealizovani dobici i gubici', '{"en":"Revaluation reserves and unrealised gains and losses"}'::jsonb, 'equity', false, null, 870),
  ('ME', 'default', '330', 'Revalorizacione rezerve', '{"en":"Revaluation reserves"}'::jsonb, 'equity', false, '33', 880),
  ('ME', 'default', '333', 'Nerealizovani dobici po osnovu hartija od vrijednosti raspoloživih za prodaju', '{"en":"Unrealised gains on available-for-sale securities"}'::jsonb, 'equity', false, '33', 890),
  ('ME', 'default', '334', 'Nerealizovani gubici po osnovu hartija od vrijednosti raspoloživih za prodaju', '{"en":"Unrealised losses on available-for-sale securities"}'::jsonb, 'equity', false, '33', 900),
  ('ME', 'default', '34', 'Neraspoređeni dobitak', '{"en":"Retained earnings"}'::jsonb, 'equity_retained', false, null, 910),
  ('ME', 'default', '340', 'Neraspoređeni dobitak ranijih godina', '{"en":"Retained earnings from prior years"}'::jsonb, 'equity_retained', false, '34', 920),
  ('ME', 'default', '341', 'Neraspoređeni dobitak tekuće godine', '{"en":"Retained earnings of the current year"}'::jsonb, 'equity_retained', false, '34', 930),
  ('ME', 'default', '35', 'Gubitak', '{"en":"Accumulated loss"}'::jsonb, 'equity_retained', false, null, 940),
  ('ME', 'default', '350', 'Gubitak ranijih godina', '{"en":"Accumulated loss from prior years"}'::jsonb, 'equity_retained', false, '35', 950),
  ('ME', 'default', '351', 'Gubitak tekuće godine', '{"en":"Loss of the current year"}'::jsonb, 'equity_retained', false, '35', 960),
  ('ME', 'default', '40', 'Dugoročna rezervisanja', '{"en":"Long-term provisions"}'::jsonb, 'liability_non_current', false, null, 970),
  ('ME', 'default', '400', 'Rezervisanja za troškove u garantnom roku', '{"en":"Provisions for warranty costs"}'::jsonb, 'liability_non_current', false, '40', 980),
  ('ME', 'default', '404', 'Rezervisanja za naknade i druge beneficije zaposlenih', '{"en":"Provisions for employee benefits"}'::jsonb, 'liability_non_current', false, '40', 990),
  ('ME', 'default', '41', 'Dugoročne obaveze', '{"en":"Long-term liabilities"}'::jsonb, 'liability_non_current', false, null, 1000),
  ('ME', 'default', '414', 'Dugoročni krediti u zemlji', '{"en":"Long-term loans in Montenegro"}'::jsonb, 'liability_non_current', false, '41', 1010),
  ('ME', 'default', '415', 'Dugoročni krediti u inostranstvu', '{"en":"Long-term loans abroad"}'::jsonb, 'liability_non_current', false, '41', 1020),
  ('ME', 'default', '419', 'Ostale dugoročne obaveze', '{"en":"Other long-term liabilities"}'::jsonb, 'liability_non_current', false, '41', 1030),
  ('ME', 'default', '42', 'Kratkoročne finansijske obaveze', '{"en":"Short-term financial liabilities"}'::jsonb, 'liability_current', false, null, 1040),
  ('ME', 'default', '422', 'Kratkoročni krediti u zemlji', '{"en":"Short-term loans in Montenegro"}'::jsonb, 'liability_current', false, '42', 1050),
  ('ME', 'default', '423', 'Kratkoročni krediti u inostranstvu', '{"en":"Short-term loans abroad"}'::jsonb, 'liability_current', false, '42', 1060),
  ('ME', 'default', '424', 'Dio dugoročnih kredita koji dospijeva do jedne godine', '{"en":"Current portion of long-term loans"}'::jsonb, 'liability_current', false, '42', 1070),
  ('ME', 'default', '43', 'Obaveze iz poslovanja', '{"en":"Trade payables"}'::jsonb, 'liability_current', false, null, 1080),
  ('ME', 'default', '430', 'Primljeni avansi depoziti i kaucije', '{"en":"Advances, deposits and guarantees received"}'::jsonb, 'liability_current', false, '43', 1090),
  ('ME', 'default', '433', 'Dobavljači u zemlji', '{"en":"Domestic suppliers"}'::jsonb, 'liability_payable', true, '43', 1100),
  ('ME', 'default', '434', 'Dobavljači u inostranstvu', '{"en":"Foreign suppliers"}'::jsonb, 'liability_payable', true, '43', 1110),
  ('ME', 'default', '439', 'Ostale obaveze iz poslovanja', '{"en":"Other trade payables"}'::jsonb, 'liability_current', false, '43', 1120),
  ('ME', 'default', '44', 'Obaveze iz specifičnih poslova', '{"en":"Liabilities from specific transactions"}'::jsonb, 'liability_current', false, null, 1130),
  ('ME', 'default', '440', 'Obaveze prema uvozniku', '{"en":"Liabilities to the importer"}'::jsonb, 'liability_current', false, '44', 1140),
  ('ME', 'default', '45', 'Obaveze po osnovu zarada i naknada zarada', '{"en":"Liabilities for salaries and salary compensations"}'::jsonb, 'liability_current', false, null, 1150),
  ('ME', 'default', '450', 'Obaveze za neto zarade i naknade zarada', '{"en":"Liabilities for net salaries and salary compensations"}'::jsonb, 'liability_current', false, '45', 1160),
  ('ME', 'default', '451', 'Obaveze za porez na zarade i naknade zarada na teret zaposlenog', '{"en":"Liabilities for payroll tax withheld from employees"}'::jsonb, 'liability_current', false, '45', 1170),
  ('ME', 'default', '452', 'Obaveze za doprinose na zarade i naknade zarada na teret zaposlenog', '{"en":"Liabilities for social contributions withheld from employees"}'::jsonb, 'liability_current', false, '45', 1180),
  ('ME', 'default', '453', 'Obaveze za poreze i doprinose na zarade i naknade zarada na teret poslodavca', '{"en":"Liabilities for payroll taxes and contributions borne by the employer"}'::jsonb, 'liability_current', false, '45', 1190),
  ('ME', 'default', '46', 'Ostale obaveze', '{"en":"Other liabilities"}'::jsonb, 'liability_current', false, null, 1200),
  ('ME', 'default', '460', 'Obaveze po osnovu kamata i troškova finansiranja', '{"en":"Liabilities for interest and financing costs"}'::jsonb, 'liability_current', false, '46', 1210),
  ('ME', 'default', '461', 'Obaveze za dividende', '{"en":"Liabilities for dividends"}'::jsonb, 'liability_current', false, '46', 1220),
  ('ME', 'default', '463', 'Obaveze prema zaposlenima', '{"en":"Liabilities to employees"}'::jsonb, 'liability_current', false, '46', 1230),
  ('ME', 'default', '465', 'Obaveze prema fizičkim licima za naknade po ugovorima', '{"en":"Liabilities to individuals for contractual fees"}'::jsonb, 'liability_current', false, '46', 1240),
  ('ME', 'default', '469', 'Ostale obaveze', '{"en":"Other liabilities"}'::jsonb, 'liability_current', false, '46', 1250),
  ('ME', 'default', '4698', 'Razlike po osnovu zaokruživanja', '{"en":"Rounding differences"}'::jsonb, 'liability_current', false, '46', 1260),
  ('ME', 'default', '47', 'Obaveze za porez na dodatu vrijednost', '{"en":"Liabilities for value added tax"}'::jsonb, 'liability_current', false, null, 1270),
  ('ME', 'default', '470', 'Obaveze za PDV po izdatim fakturama po opštoj stopi od 21%', '{"en":"VAT liability on sales invoices at the standard rate of 21%"}'::jsonb, 'liability_current', false, '47', 1280),
  ('ME', 'default', '471', 'Obaveze za PDV po izdatim fakturama po sniženim stopama', '{"en":"VAT liability on sales invoices at the reduced rates"}'::jsonb, 'liability_current', false, '47', 1290),
  ('ME', 'default', '4711', 'Obaveze za PDV po izdatim fakturama po stopi od 15%', '{"en":"VAT liability on sales invoices at the reduced rate of 15%"}'::jsonb, 'liability_current', false, '471', 1300),
  ('ME', 'default', '4717', 'Obaveze za PDV po izdatim fakturama po stopi od 7%', '{"en":"VAT liability on sales invoices at the reduced rate of 7%"}'::jsonb, 'liability_current', false, '471', 1310),
  ('ME', 'default', '472', 'Obaveze za PDV po primljenim avansima po opštoj stopi', '{"en":"VAT liability on advances received at the standard rate"}'::jsonb, 'liability_current', false, '47', 1320),
  ('ME', 'default', '473', 'Obaveze za PDV po primljenim avansima po sniženim stopama', '{"en":"VAT liability on advances received at the reduced rates"}'::jsonb, 'liability_current', false, '47', 1330),
  ('ME', 'default', '476', 'Obaveze za PDV po osnovu prodaje za gotovinu', '{"en":"VAT liability on cash sales"}'::jsonb, 'liability_current', false, '47', 1340),
  ('ME', 'default', '479', 'Obaveze za PDV po osnovu razlike obračunatog i prethodnog poreza', '{"en":"VAT payable, net of the period''s return"}'::jsonb, 'liability_current', true, '47', 1350),
  ('ME', 'default', '48', 'Obaveze za ostale poreze doprinose i druge dažbine', '{"en":"Liabilities for other taxes, contributions and duties"}'::jsonb, 'liability_current', false, null, 1360),
  ('ME', 'default', '480', 'Obaveze za akcize', '{"en":"Liabilities for excise duties"}'::jsonb, 'liability_current', false, '48', 1370),
  ('ME', 'default', '481', 'Obaveze za porez iz rezultata', '{"en":"Liabilities for corporate income tax"}'::jsonb, 'liability_current', false, '48', 1380),
  ('ME', 'default', '482', 'Obaveze za poreze carine i druge dažbine iz nabavke ili na teret troškova', '{"en":"Liabilities for taxes, customs duties and other charges on purchases"}'::jsonb, 'liability_current', false, '48', 1390),
  ('ME', 'default', '49', 'Pasivna vremenska razgraničenja', '{"en":"Accrued expenses and deferred income"}'::jsonb, 'liability_current', false, null, 1400),
  ('ME', 'default', '490', 'Unaprijed obračunati troškovi', '{"en":"Accrued expenses"}'::jsonb, 'liability_current', false, '49', 1410),
  ('ME', 'default', '491', 'Obračunati prihodi budućeg perioda', '{"en":"Accrued income of a future period"}'::jsonb, 'liability_current', false, '49', 1420),
  ('ME', 'default', '495', 'Odloženi prihodi i primljene donacije', '{"en":"Deferred income and donations received"}'::jsonb, 'liability_current', false, '49', 1430),
  ('ME', 'default', '498', 'Odložene poreske obaveze', '{"en":"Deferred tax liabilities"}'::jsonb, 'liability_non_current', false, '49', 1440),
  ('ME', 'default', '499', 'Ostala pasivna vremenska razgraničenja', '{"en":"Other accrued expenses and deferred income"}'::jsonb, 'liability_current', false, '49', 1450),
  ('ME', 'default', '50', 'Nabavna vrijednost prodate robe', '{"en":"Cost of merchandise sold"}'::jsonb, 'expense_direct_cost', false, null, 1460),
  ('ME', 'default', '500', 'Nabavka robe', '{"en":"Purchases of merchandise"}'::jsonb, 'expense_direct_cost', false, '50', 1470),
  ('ME', 'default', '501', 'Nabavna vrijednost prodate robe', '{"en":"Cost of merchandise sold"}'::jsonb, 'expense_direct_cost', false, '50', 1480),
  ('ME', 'default', '51', 'Troškovi materijala', '{"en":"Cost of materials"}'::jsonb, 'expense_direct_cost', false, null, 1490),
  ('ME', 'default', '510', 'Nabavka materijala', '{"en":"Purchases of materials"}'::jsonb, 'expense_direct_cost', false, '51', 1500),
  ('ME', 'default', '511', 'Troškovi materijala za izradu', '{"en":"Materials consumed in production"}'::jsonb, 'expense_direct_cost', false, '51', 1510),
  ('ME', 'default', '512', 'Troškovi ostalog materijala', '{"en":"Other materials consumed"}'::jsonb, 'expense_direct_cost', false, '51', 1520),
  ('ME', 'default', '513', 'Troškovi goriva i energije', '{"en":"Fuel and energy costs"}'::jsonb, 'expense_direct_cost', false, '51', 1530),
  ('ME', 'default', '52', 'Troškovi zarada naknada zarada i ostali lični rashodi', '{"en":"Salary costs and other personal expenses"}'::jsonb, 'expense', false, null, 1540),
  ('ME', 'default', '520', 'Troškovi zarada i naknada zarada bruto', '{"en":"Gross salaries and salary compensations"}'::jsonb, 'expense', false, '52', 1550),
  ('ME', 'default', '521', 'Troškovi poreza i doprinosa na zarade i naknade zarada na teret poslodavca', '{"en":"Payroll taxes and contributions borne by the employer"}'::jsonb, 'expense', false, '52', 1560),
  ('ME', 'default', '522', 'Troškovi naknada po ugovoru o djelu', '{"en":"Fees under service contracts"}'::jsonb, 'expense', false, '52', 1570),
  ('ME', 'default', '526', 'Troškovi naknada članovima upravnog i nadzornog odbora', '{"en":"Fees to members of the management and supervisory board"}'::jsonb, 'expense', false, '52', 1580),
  ('ME', 'default', '53', 'Troškovi proizvodnih usluga', '{"en":"Costs of production services"}'::jsonb, 'expense', false, null, 1590),
  ('ME', 'default', '530', 'Troškovi usluga na izradi učinaka', '{"en":"Costs of outsourced production work"}'::jsonb, 'expense', false, '53', 1600),
  ('ME', 'default', '531', 'Troškovi transportnih usluga', '{"en":"Transport costs"}'::jsonb, 'expense', false, '53', 1610),
  ('ME', 'default', '532', 'Troškovi usluga održavanja', '{"en":"Maintenance costs"}'::jsonb, 'expense', false, '53', 1620),
  ('ME', 'default', '533', 'Troškovi zakupnina', '{"en":"Rent expense"}'::jsonb, 'expense', false, '53', 1630),
  ('ME', 'default', '535', 'Troškovi reklame i propagande', '{"en":"Advertising costs"}'::jsonb, 'expense', false, '53', 1640),
  ('ME', 'default', '539', 'Troškovi ostalih usluga', '{"en":"Costs of other services"}'::jsonb, 'expense', false, '53', 1650),
  ('ME', 'default', '54', 'Troškovi amortizacije i rezervisanja', '{"en":"Depreciation and provision costs"}'::jsonb, 'expense_depreciation', false, null, 1660),
  ('ME', 'default', '540', 'Troškovi amortizacije', '{"en":"Depreciation costs"}'::jsonb, 'expense_depreciation', false, '54', 1670),
  ('ME', 'default', '541', 'Troškovi rezervisanja za garantni rok', '{"en":"Warranty provision costs"}'::jsonb, 'expense', false, '54', 1680),
  ('ME', 'default', '55', 'Nematerijalni troškovi', '{"en":"Intangible costs"}'::jsonb, 'expense', false, null, 1690),
  ('ME', 'default', '550', 'Troškovi neproizvodnih usluga', '{"en":"Costs of non-production services"}'::jsonb, 'expense', false, '55', 1700),
  ('ME', 'default', '551', 'Troškovi reprezentacije', '{"en":"Entertainment costs"}'::jsonb, 'expense', false, '55', 1710),
  ('ME', 'default', '552', 'Troškovi premija osiguranja', '{"en":"Insurance premium costs"}'::jsonb, 'expense', false, '55', 1720),
  ('ME', 'default', '553', 'Troškovi platnog prometa', '{"en":"Bank charges"}'::jsonb, 'expense', false, '55', 1730),
  ('ME', 'default', '554', 'Troškovi članarina', '{"en":"Membership fees"}'::jsonb, 'expense', false, '55', 1740),
  ('ME', 'default', '555', 'Troškovi poreza', '{"en":"Tax costs"}'::jsonb, 'expense', false, '55', 1750),
  ('ME', 'default', '556', 'Troškovi doprinosa', '{"en":"Contribution costs"}'::jsonb, 'expense', false, '55', 1760),
  ('ME', 'default', '56', 'Finansijski rashodi', '{"en":"Financial expenses"}'::jsonb, 'expense', false, null, 1770),
  ('ME', 'default', '562', 'Rashodi kamata', '{"en":"Interest expense"}'::jsonb, 'expense', false, '56', 1780),
  ('ME', 'default', '563', 'Negativne kursne razlike', '{"en":"Foreign exchange losses"}'::jsonb, 'expense', false, '56', 1790),
  ('ME', 'default', '57', 'Ostali rashodi', '{"en":"Other expenses"}'::jsonb, 'expense', false, null, 1800),
  ('ME', 'default', '570', 'Gubici po osnovu rashodovanja i prodaje nematerijalnih ulaganja nekretnina postrojenja i opreme', '{"en":"Losses on disposal of intangible assets and property, plant and equipment"}'::jsonb, 'expense', false, '57', 1810),
  ('ME', 'default', '573', 'Gubici od prodaje materijala', '{"en":"Losses on sale of materials"}'::jsonb, 'expense', false, '57', 1820),
  ('ME', 'default', '574', 'Manjkovi', '{"en":"Inventory shortages"}'::jsonb, 'expense', false, '57', 1830),
  ('ME', 'default', '576', 'Rashodi po osnovu direktnih otpisa potraživanja', '{"en":"Expenses from direct write-off of receivables"}'::jsonb, 'expense', false, '57', 1840),
  ('ME', 'default', '58', 'Rashodi po osnovu usklađivanja vrijednosti imovine', '{"en":"Impairment expenses"}'::jsonb, 'expense', false, null, 1850),
  ('ME', 'default', '582', 'Rashodi po osnovu usklađivanja vrijednosti nekretnina postrojenja i opreme', '{"en":"Impairment of property, plant and equipment"}'::jsonb, 'expense', false, '58', 1860),
  ('ME', 'default', '584', 'Rashodi po osnovu usklađivanja vrijednosti zaliha materijala i robe', '{"en":"Impairment of inventories"}'::jsonb, 'expense', false, '58', 1870),
  ('ME', 'default', '585', 'Rashodi po osnovu usklađivanja vrijednosti potraživanja i kratkoročnih finansijskih plasmana', '{"en":"Impairment of receivables and short-term financial investments"}'::jsonb, 'expense', false, '58', 1880),
  ('ME', 'default', '60', 'Prihodi od prodaje robe', '{"en":"Revenue from sale of merchandise"}'::jsonb, 'income', false, null, 1890),
  ('ME', 'default', '602', 'Prihodi od prodaje robe na domaćem tržištu', '{"en":"Revenue from sale of merchandise, domestic market"}'::jsonb, 'income', false, '60', 1900),
  ('ME', 'default', '603', 'Prihodi od prodaje robe na inostranom tržištu', '{"en":"Revenue from sale of merchandise, foreign market"}'::jsonb, 'income', false, '60', 1910),
  ('ME', 'default', '61', 'Prihodi od prodaje proizvoda i usluga', '{"en":"Revenue from sale of products and services"}'::jsonb, 'income', false, null, 1920),
  ('ME', 'default', '612', 'Prihodi od prodaje proizvoda i usluga na domaćem tržištu', '{"en":"Revenue from sale of products and services, domestic market"}'::jsonb, 'income', false, '61', 1930),
  ('ME', 'default', '613', 'Prihodi od prodaje proizvoda i usluga na inostranom tržištu', '{"en":"Revenue from sale of products and services, foreign market"}'::jsonb, 'income', false, '61', 1940),
  ('ME', 'default', '62', 'Prihodi od aktiviranja učinaka i robe', '{"en":"Revenue from own work capitalised"}'::jsonb, 'income', false, null, 1950),
  ('ME', 'default', '620', 'Prihodi od aktiviranja ili potrošnje robe za sopstvene potrebe', '{"en":"Revenue from own consumption of merchandise"}'::jsonb, 'income', false, '62', 1960),
  ('ME', 'default', '621', 'Prihodi od aktiviranja ili potrošnje proizvoda i usluga za sopstvene potrebe', '{"en":"Revenue from own consumption of products and services"}'::jsonb, 'income', false, '62', 1970),
  ('ME', 'default', '63', 'Promjena vrijednosti zaliha učinaka', '{"en":"Change in inventories"}'::jsonb, 'income', false, null, 1980),
  ('ME', 'default', '630', 'Povećanje vrijednosti zaliha nedovršenih i gotovih proizvoda i nedovršenih usluga', '{"en":"Increase in inventories of work in progress and finished goods"}'::jsonb, 'income', false, '63', 1990),
  ('ME', 'default', '631', 'Smanjenje vrijednosti zaliha nedovršenih i gotovih proizvoda i nedovršenih usluga', '{"en":"Decrease in inventories of work in progress and finished goods"}'::jsonb, 'income', false, '63', 2000),
  ('ME', 'default', '64', 'Prihodi od premija subvencija dotacija i donacija', '{"en":"Revenue from grants, subsidies and donations"}'::jsonb, 'income', false, null, 2010),
  ('ME', 'default', '640', 'Prihodi od premija subvencija dotacija regresa kompenzacija i povraćaja poreskih dažbina', '{"en":"Revenue from premiums, subsidies, grants and tax refunds"}'::jsonb, 'income', false, '64', 2020),
  ('ME', 'default', '65', 'Drugi poslovni prihodi', '{"en":"Other operating revenue"}'::jsonb, 'income', false, null, 2030),
  ('ME', 'default', '650', 'Prihodi od zakupnina', '{"en":"Rental income"}'::jsonb, 'income', false, '65', 2040),
  ('ME', 'default', '651', 'Prihodi od članarina', '{"en":"Membership fee income"}'::jsonb, 'income', false, '65', 2050),
  ('ME', 'default', '659', 'Ostali poslovni prihodi', '{"en":"Other operating revenue"}'::jsonb, 'income', false, '65', 2060),
  ('ME', 'default', '66', 'Finansijski prihodi', '{"en":"Financial revenue"}'::jsonb, 'income', false, null, 2070),
  ('ME', 'default', '662', 'Prihodi od kamata', '{"en":"Interest income"}'::jsonb, 'income', false, '66', 2080),
  ('ME', 'default', '663', 'Pozitivne kursne razlike', '{"en":"Foreign exchange gains"}'::jsonb, 'income', false, '66', 2090),
  ('ME', 'default', '67', 'Ostali prihodi', '{"en":"Other revenue"}'::jsonb, 'income', false, null, 2100),
  ('ME', 'default', '670', 'Dobici od prodaje nematerijalnih ulaganja nekretnina postrojenja i opreme', '{"en":"Gains on disposal of intangible assets and property, plant and equipment"}'::jsonb, 'income', false, '67', 2110),
  ('ME', 'default', '674', 'Viškovi', '{"en":"Inventory surpluses"}'::jsonb, 'income', false, '67', 2120),
  ('ME', 'default', '675', 'Naplaćena otpisana potraživanja', '{"en":"Recovered receivables previously written off"}'::jsonb, 'income', false, '67', 2130),
  ('ME', 'default', '68', 'Prihodi od usklađivanja vrijednosti imovine', '{"en":"Revenue from reversal of impairment"}'::jsonb, 'income', false, null, 2140),
  ('ME', 'default', '682', 'Prihodi od usklađivanja vrijednosti nekretnina postrojenja i opreme', '{"en":"Reversal of impairment of property, plant and equipment"}'::jsonb, 'income', false, '68', 2150),
  ('ME', 'default', '684', 'Prihodi od usklađivanja vrijednosti zaliha materijala i robe', '{"en":"Reversal of impairment of inventories"}'::jsonb, 'income', false, '68', 2160),
  ('ME', 'default', '685', 'Prihodi od usklađivanja vrijednosti potraživanja i kratkoročnih finansijskih plasmana', '{"en":"Reversal of impairment of receivables and short-term financial investments"}'::jsonb, 'income', false, '68', 2170)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('ME', 'BNK', 'Dnevnik banke', '{"en":"Bank journal"}'::jsonb, 'bank', 30),
  ('ME', 'CSH', 'Dnevnik blagajne', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('ME', 'GEN', 'Opšti dnevnik', '{"en":"General journal"}'::jsonb, 'general', 50),
  ('ME', 'OPN', 'Dnevnik otvaranja', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('ME', 'PUR', 'Dnevnik nabavke', '{"en":"Purchase journal"}'::jsonb, 'purchase', 20),
  ('ME', 'SAL', 'Dnevnik prodaje', '{"en":"Sales journal"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('ME', 'ME-P-15', 'PDV 15% — smještaj, hrana i piće u ugostiteljstvu, knjige i dr. (nabavka)', '{"en":"VAT 15% — accommodation, food and drink in hospitality, books etc. (purchase)"}'::jsonb, null, 'percent', 15, 'purchase', 'domestic', date '2025-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 24a stav 2 i član 37 — pravo na odbitak ulaznog PDV obračunatog po sniženoj stopi od 15% (usluge smještaja, hrane i pića u ugostiteljstvu, knjige), pod uslovima člana 37.', null, null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-P-21', 'PDV 21% — opšta stopa (nabavka)', '{"en":"VAT 21% — standard rate (purchase)"}'::jsonb, null, 'percent', 21, 'purchase', 'domestic', date '2018-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 24 (stopa) i član 37 (uslovi za odbijanje ulaznog PDV) — poreski obveznik može odbiti PDV koji je dužan da plati ili je platio prilikom nabavke proizvoda, odnosno usluga, ako ih koristi u svrhe ostvarivanja prihoda pri obavljanju oporezive djelatnosti.', null, null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-P-7', 'PDV 7% — osnovni proizvodi za ljudsku ishranu i dr. (nabavka)', '{"en":"VAT 7% — basic foodstuffs and other essentials (purchase)"}'::jsonb, null, 'percent', 7, 'purchase', 'domestic', date '2018-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 24a stav 1 tačka 1 i član 37 — pravo na odbitak ulaznog PDV obračunatog po sniženoj stopi od 7% na osnovne proizvode za ljudsku ishranu.', null, null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-P-FOREIGN', 'PDV 21% — usluge inostranih lica, poreski dužnik primalac (nabavka)', '{"en":"VAT 21% — services from foreign persons, recipient is the tax debtor (purchase)"}'::jsonb, null, 'percent', 21, 'purchase', 'foreign_services_received', date '2018-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 12 stav 1 tačka 2 — poreski dužnik PDV je poreski zastupnik, odnosno, kada ga poreski obveznik koji nema sjedište u Crnoj Gori ne imenuje, primalac proizvoda, odnosno usluga plaća PDV. Obrazac PR PDV-2, redni broj 21 ("PDV na usluge inostranih lica") — iznos se istovremeno iskazuje kao dio izlaznog PDV (obračunat na uslugu, redni broj 24) i kao dio ulaznog PDV (pretporez, redni broj 25), pod uslovom da poreski obveznik ima pravo na odbitak prema članu 37. Ovaj paket pretpostavlja opštu stopu od 21% za samooporezovanu uslugu; kad bi osnovna usluga, da je izvršio rezident, nosila sniženu stopu, treba provjeriti sa računovođom.', null, null, 90, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-S-15', 'PDV 15% — smještaj, hrana i piće u ugostiteljstvu, knjige i dr. (prodaja)', '{"en":"VAT 15% — accommodation, food and drink in hospitality, books etc. (sale)"}'::jsonb, null, 'percent', 15, 'sale', 'domestic', date '2025-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 24a stav 2 — snižena stopa od 15% se, između ostalog, obračunava i plaća na usluge smještaja u ugostiteljskim objektima za smještaj (tačka 2), na usluge pripremanja i usluživanja hrane, pića i napitaka u ugostiteljskim objektima, osim alkoholnih pića, gaziranih i negaziranih pića sa dodatkom šećera i kafe (tačka 3), i na knjige, monografske i serijske publikacije (tačka 1). Izmjena je uvedena Zakonom o izmjenama i dopuni Zakona o porezu na dodatu vrijednost, "Sl. list CG", br. 094/24 od 30.09.2024, u primjeni od 01.01.2025 (prije toga usluge smještaja bile su oporezovane po stopi od 7%).', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-S-21', 'PDV 21% — opšta stopa (prodaja)', '{"en":"VAT 21% — standard rate (sale)"}'::jsonb, null, 'percent', 21, 'sale', 'domestic', date '2018-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 24 — PDV se obračunava i plaća po opštoj stopi od 21% od svakog prometa proizvoda, usluga i uvoza proizvoda, osim prometa za koji je propisana snižena ili nulta stopa.', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-S-7', 'PDV 7% — osnovni proizvodi za ljudsku ishranu i dr. (prodaja)', '{"en":"VAT 7% — basic foodstuffs and other essentials (sale)"}'::jsonb, null, 'percent', 7, 'sale', 'domestic', date '2025-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 24a stav 1 tačka 1 — snižena stopa od 7% se obračunava i plaća na promet osnovnih proizvoda za ljudsku ishranu (hljeb, brašno, mlijeko i mliječni proizvodi, hrana za odojčad, mast, ulje, meso, jaja i šećer). Rate carries the same 7% since the amendment of "Sl. list CG", br. 094/24 od 30.09.2024 (u primjeni od 01.01.2025), koja je samo dio proizvoda i usluga sa stope 7% prebacila na novu stopu od 15%.', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-S-EXEMPT-LEASE', 'Oslobođeno PDV — dugoročni zakup stambenog prostora (prodaja)', '{"en":"Exempt from VAT — long-term residential lease (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2018-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 27 stav 1 tačka 3 — plaćanja PDV su oslobođene usluge davanja u zakup ili podzakup kuća za stanovanje, stanova, odnosno stambenih prostora za stalno stanovanje duže od 60 dana, kao i zakup poljoprivrednog zemljišta ili šuma, koji su upisani u zemljišne knjige. Crna Gora je izvan zajedničkog sistema PDV Evropske unije (Direktiva 2006/112/EZ, član 5 stav 2, ne obavezuje kandidata za pristupanje), pa ovaj paket ne pripisuje kôd VATEX niti kategoriju BT-118/BT-151 ovoj tarifi — vidjeti docs/packs.md, odjeljak o zemljama van zajedničkog sistema PDV.', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null),
  ('ME', 'ME-S-EXPORT', 'PDV 0% — izvoz proizvoda (prodaja)', '{"en":"VAT 0% — export of goods (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2018-01-01', null, 'Zakon o porezu na dodatu vrijednost, član 25 stav 1 tačka 1 — PDV se plaća po stopi od 0% na proizvode koje iz Crne Gore izvozi prodavac, odnosno proizvode koje za njegov račun izvozi drugo lice.', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pdv-zakon', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('ME-P-15', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('ME-P-15', 'invoice', 'tax', 100, '2715', '19', array['19']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-P-15', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('ME-P-15', 'credit_note', 'tax', 100, '2715', '19', array['19']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-P-21', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('ME-P-21', 'invoice', 'tax', 100, '270', '19', array['19']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-P-21', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('ME-P-21', 'credit_note', 'tax', 100, '270', '19', array['19']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-P-7', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('ME-P-7', 'invoice', 'tax', 100, '2717', '19', array['19']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-P-7', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('ME-P-7', 'credit_note', 'tax', 100, '2717', '19', array['19']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-P-FOREIGN', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('ME-P-FOREIGN', 'invoice', 'tax', 100, '276', '21', array['21']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-P-FOREIGN', 'invoice', 'tax', -100, '470', null, null, 100, null, 30),
    ('ME-P-FOREIGN', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('ME-P-FOREIGN', 'credit_note', 'tax', 100, '276', '21', array['21']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-P-FOREIGN', 'credit_note', 'tax', -100, '470', null, null, -100, null, 30),
    ('ME-S-15', 'invoice', 'base', 100, null, '11', array['11']::text[], 100, 'ME-PR-PDV-2', 10),
    ('ME-S-15', 'invoice', 'tax', 100, '4711', '17', array['17']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-S-15', 'credit_note', 'base', 100, null, '11', array['11']::text[], -100, 'ME-PR-PDV-2', 10),
    ('ME-S-15', 'credit_note', 'tax', 100, '4711', '17', array['17']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-S-21', 'invoice', 'base', 100, null, '10', array['10']::text[], 100, 'ME-PR-PDV-2', 10),
    ('ME-S-21', 'invoice', 'tax', 100, '470', '16', array['16']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-S-21', 'credit_note', 'base', 100, null, '10', array['10']::text[], -100, 'ME-PR-PDV-2', 10),
    ('ME-S-21', 'credit_note', 'tax', 100, '470', '16', array['16']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-S-7', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'ME-PR-PDV-2', 10),
    ('ME-S-7', 'invoice', 'tax', 100, '4717', '18', array['18']::text[], 100, 'ME-PR-PDV-2', 20),
    ('ME-S-7', 'credit_note', 'base', 100, null, '12', array['12']::text[], -100, 'ME-PR-PDV-2', 10),
    ('ME-S-7', 'credit_note', 'tax', 100, '4717', '18', array['18']::text[], -100, 'ME-PR-PDV-2', 20),
    ('ME-S-EXEMPT-LEASE', 'invoice', 'base', 100, null, '14', array['14']::text[], 100, 'ME-PR-PDV-2', 10),
    ('ME-S-EXEMPT-LEASE', 'credit_note', 'base', 100, null, '14', array['14']::text[], -100, 'ME-PR-PDV-2', 10),
    ('ME-S-EXPORT', 'invoice', 'base', 100, null, '13', array['13']::text[], 100, 'ME-PR-PDV-2', 10),
    ('ME-S-EXPORT', 'credit_note', 'base', 100, null, '13', array['13']::text[], -100, 'ME-PR-PDV-2', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'ME' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('ME', 'ME-PR-PDV-2', 'Mjesečna prijava za obračun poreza na dodatu vrijednost — Obrazac PR PDV-2', array['month']::declaration_period[], 'month'::declaration_period, date '2025-01-01', null, 'Obrazac PR PDV-2, propisan od strane Uprave prihoda i carina. Zakon o porezu na dodatu vrijednost, član 33 stav 2 — poreski period je period od prvog do zadnjeg dana u mjesecu (kalendarski mjesec), jedina propisana dinamika. Ovaj paket transkribuje redne brojeve obrasca koje njegovi porezi dosežu: oporezivi promet i PDV po stopama od 21%, 15% i 7% (redni brojevi 10/16, 11/17, 12/18), promet po nultoj stopi (13) i oslobođeni promet (14), ulazni PDV na domaći promet (19) i PDV na usluge inostranih lica (21), te zbirne redne brojeve 24, 25, 28 i 29. Nijesu transkribovani: redni broj 9 (obilježje "bez transakcija", nije numerička vrijednost), 15 i 23 (promet/PDV prirodnog gasa, električne energije i energije za grijanje ili hlađenje za koji je izvršen prenos poreske obaveze — uska energetska šema van obima ovog izdanja), 20 (PDV plaćen na uvoz — socle ovog izdanja nema modul carinskog uvoza), 22 (paušalna nadoknada poljoprivredniku po stopi od 8% — posebna šema van obima), 26 i 27 (razdvajanje ulaznog PDV bez i sa pravom na odbitak — ovaj paket pretpostavlja puno pravo na odbitak i ne modeluje srazmjerni odbitak iz člana 38), i 30 (zahtjev za povraćaj PDV kredita, administrativno polje). Vidjeti README.md i docs/international.md, odjeljak «From Montenegro».', true,'day_of_month_after_period'::filing_deadline_rule, 15, null, 'Zakon o porezu na dodatu vrijednost, član 35 stav 2 — poreski obveznik prijavu za obračun PDV podnosi elektronskim putem nadležnom poreskom organu do 15. dana narednog mjeseca po isteku poreskog perioda; član 36 stav 1 — poreska obaveza za poreski period dospijeva za plaćanje istog dana, 15. dana u mjesecu po isteku poreskog perioda. Ovo polje modeluje samo rok za podnošenje prijave; socle ne razlikuje rok podnošenja od roka plaćanja, koji se ovdje poklapaju.', 'pdv-zakon', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('ME', 'ME-PR-PDV-2', '10', 'base', 'Oporezivi promet (isporuke) po stopi od 21%', '{"en":"Taxable supplies at the rate of 21%"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 10.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '11', 'base', 'Oporezivi promet (isporuke) po stopi od 15%', '{"en":"Taxable supplies at the rate of 15%"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 11.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '12', 'base', 'Oporezivi promet (isporuke) po stopi od 7%', '{"en":"Taxable supplies at the rate of 7%"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 12.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '13', 'base', 'Oporezivi promet (isporuke) po stopi od 0%', '{"en":"Taxable supplies at the rate of 0%"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 13; Zakon o porezu na dodatu vrijednost, član 25.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '14', 'base', 'Oslobođeni promet — isporuke', '{"en":"Exempt supplies"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 14; Zakon o porezu na dodatu vrijednost, čl. 26 i 27.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '16', 'tax', 'PDV na domaći promet proizvoda i usluga po stopi od 21%', '{"en":"VAT on domestic supplies at the rate of 21%"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 16.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '17', 'tax', 'PDV na domaći promet proizvoda i usluga po stopi od 15%', '{"en":"VAT on domestic supplies at the rate of 15%"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 17.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '18', 'tax', 'PDV na domaći promet proizvoda i usluga po stopi od 7%', '{"en":"VAT on domestic supplies at the rate of 7%"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 18.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '19', 'tax', 'Ulazni PDV na domaći promet proizvoda i usluga', '{"en":"Input VAT on domestic supplies"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 19.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '21', 'tax', 'PDV na usluge inostranih lica', '{"en":"VAT on services from foreign persons"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 21; Zakon o porezu na dodatu vrijednost, član 12 stav 1 tačka 2 — istovremeno dio izlaznog PDV (redni broj 24) i ulaznog PDV (redni broj 25).', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '24', 'total', 'Ukupan izlazni PDV na isporuke', '{"en":"Total output VAT on supplies"}'::jsonb, 110, null, array['16', '17', '18', '21']::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 24 — zbir rednih brojeva 16+17+18+21.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '25', 'total', 'Ukupan ulazni PDV — pretporez', '{"en":"Total input VAT (deductible)"}'::jsonb, 120, null, array['19', '21']::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PR PDV-2, redni broj 25 — zbir rednih brojeva 19+20+21+22; ovaj paket ne transkribuje redne brojeve 20 (uvoz) i 22 (paušalna nadoknada poljoprivredniku), pa ovdje zbraja samo 19+21. Vidjeti napomenu na vrhu ovog fajla.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '28', 'total', 'Dospjeli PDV za uplatu', '{"en":"VAT due for payment"}'::jsonb, 130, null, array['24']::text[], array['25']::text[], null, null, true, false, null, 'Obrazac PR PDV-2, redni broj 28 — razlika rednih brojeva 24-27; ovaj paket ne transkribuje redni broj 26 (ulazni PDV bez prava na odbitak) niti 27 (25 minus 26) i pretpostavlja puno pravo na odbitak, pa ovdje oduzima direktno redni broj 25.', 'pdv-prijava-obrazac'),
  ('ME', 'ME-PR-PDV-2', '29', 'total', 'PDV kredit', '{"en":"VAT credit"}'::jsonb, 140, null, array['25']::text[], array['24']::text[], null, null, true, false, null, 'Obrazac PR PDV-2, redni broj 29 — razlika rednih brojeva 27-24, ovdje 25-24 iz istog razloga kao redni broj 28.', 'pdv-prijava-obrazac')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('ME-FS-BS', 'ME', 'default', 'Iskaz o finansijskoj poziciji /Bilans stanja/', 'balance_sheet', 'MSFI / Zakon o računovodstvu', date '2018-01-01', null, 'Zakon o računovodstvu ("Sl. list CG", br. 052/16), član 4, i Pravilnik o sadržini i formi obrazaca finansijskih iskaza za privredna društva i druga pravna lica, usklađen sa Direktivom 2013/34/EU — obrazac "Iskaz o finansijskoj poziciji /Bilans stanja/" nosi redne brojeve (AOP) od 001 do 144. Ovaj paket transkribuje jedanaest zbirnih redova na nivou klase/grupe konta Kontnog okvira umjesto svakog od preko sto pojedinačnih redova obrasca — svaki konto ovog paketa dostiže tačno jedan od njih. Kompletnu podjelu po pojedinačnim rednim brojevima obrasca vidjeti u README.md.', 'fin-iskazi-obrazac'),
  ('ME-FS-IS', 'ME', 'default', 'Iskaz o ukupnom rezultatu /Bilans uspjeha/', 'income_statement', 'MSFI / Zakon o računovodstvu', date '2018-01-01', null, 'Zakon o računovodstvu ("Sl. list CG", br. 052/16), član 4, i Pravilnik o sadržini i formi obrazaca finansijskih iskaza za privredna društva i druga pravna lica — obrazac "Iskaz o ukupnom rezultatu /Bilans uspjeha/" nosi redne brojeve (AOP) od 201 do 265. Ovaj paket transkribuje trinaest zbirnih redova na nivou klase/grupe konta Kontnog okvira umjesto svakog pojedinačnog reda obrasca (koji dalje razlaže prihode i rashode po povezanim/nepovezanim licima); ne transkribuje redove 249-265 (bruto rezultat drugih stavki rezultata povezanih sa kapitalom — nerealizovani dobici/gubici po osnovu revalorizacije, hedžinga i sl.), koje nijedan konto ovog paketa ne dostiže. Vidjeti README.md.', 'fin-iskazi-obrazac')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('ME-FS-BS', 'ME-BS-000', null, 'Neuplaćeni upisani kapital', '{"en":"Uncalled subscribed capital"}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-010', null, 'Nematerijalna ulaganja', '{"en":"Intangible assets"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-020', null, 'Nekretnine, postrojenja, oprema i biološka sredstva', '{"en":"Property, plant, equipment and biological assets"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-030', null, 'Dugoročni finansijski plasmani', '{"en":"Long-term financial investments"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-040', null, 'Stalna sredstva namijenjena prodaji', '{"en":"Non-current assets held for sale"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-090', null, 'Stalna imovina — ukupno', '{"en":"Non-current assets — total"}'::jsonb, 60, 1, true, array['ME-BS-000', 'ME-BS-010', 'ME-BS-020', 'ME-BS-030', 'ME-BS-040']::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-100', null, 'Zalihe', '{"en":"Inventories"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-110', null, 'Dati avansi', '{"en":"Advances paid"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-120', null, 'Kratkoročna potraživanja i finansijski plasmani', '{"en":"Current receivables and financial investments"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-130', null, 'Gotovina i gotovinski ekvivalenti', '{"en":"Cash and cash equivalents"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-140', null, 'Porez na dodatu vrijednost i aktivna vremenska razgraničenja', '{"en":"Value added tax and prepayments"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-190', null, 'Obrtna sredstva — ukupno', '{"en":"Current assets — total"}'::jsonb, 120, 1, true, array['ME-BS-100', 'ME-BS-110', 'ME-BS-120', 'ME-BS-130', 'ME-BS-140']::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-300', null, 'Ukupna aktiva', '{"en":"Total assets"}'::jsonb, 130, 1, true, array['ME-BS-090', 'ME-BS-190']::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2000', null, 'Osnovni kapital', '{"en":"Share capital"}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2010', null, 'Neuplaćeni upisani kapital', '{"en":"Uncalled subscribed capital"}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2020', null, 'Rezerve', '{"en":"Reserves"}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2030', null, 'Revalorizacione rezerve i nerealizovani dobici/gubici', '{"en":"Revaluation reserves and unrealised gains/losses"}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2040', null, 'Neraspoređeni dobitak', '{"en":"Retained earnings"}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2050', null, 'Gubitak', '{"en":"Accumulated loss"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2090', null, 'Kapital — ukupno', '{"en":"Equity — total"}'::jsonb, 200, 1, true, array['ME-BS-2000', 'ME-BS-2010', 'ME-BS-2020', 'ME-BS-2030', 'ME-BS-2040', 'ME-BS-2050']::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2100', null, 'Dugoročna rezervisanja i dugoročne obaveze', '{"en":"Long-term provisions and long-term liabilities"}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2200', null, 'Kratkoročne finansijske obaveze', '{"en":"Short-term financial liabilities"}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2210', null, 'Obaveze iz poslovanja i iz specifičnih poslova', '{"en":"Trade payables and liabilities from specific transactions"}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2220', null, 'Obaveze po osnovu zarada i naknada zarada', '{"en":"Liabilities for salaries and salary compensations"}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2230', null, 'Ostale obaveze', '{"en":"Other liabilities"}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2240', null, 'Obaveze za porez na dodatu vrijednost i ostale poreze', '{"en":"Liabilities for value added tax and other taxes"}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2250', null, 'Pasivna vremenska razgraničenja', '{"en":"Accrued expenses and deferred income"}'::jsonb, 270, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2290', null, 'Dugoročna rezervisanja i obaveze — ukupno', '{"en":"Long-term provisions and liabilities — total"}'::jsonb, 280, 1, true, array['ME-BS-2100', 'ME-BS-2200', 'ME-BS-2210', 'ME-BS-2220', 'ME-BS-2230', 'ME-BS-2240', 'ME-BS-2250']::text[], '{}'::text[], null, null, null),
  ('ME-FS-BS', 'ME-BS-2900', null, 'Ukupna pasiva', '{"en":"Total equity and liabilities"}'::jsonb, 290, 1, true, array['ME-BS-2090', 'ME-BS-2290']::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-201', null, 'Prihodi od prodaje robe', '{"en":"Revenue from sale of merchandise"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-202', null, 'Prihodi od prodaje proizvoda i usluga', '{"en":"Revenue from sale of products and services"}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-203', null, 'Prihodi od aktiviranja učinaka i robe', '{"en":"Revenue from own work capitalised"}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-204', null, 'Promjena vrijednosti zaliha učinaka', '{"en":"Change in inventories"}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-205', null, 'Prihodi od premija, subvencija, dotacija i donacija', '{"en":"Revenue from grants, subsidies and donations"}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-206', null, 'Drugi poslovni prihodi', '{"en":"Other operating revenue"}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-209', null, 'Poslovni prihodi — ukupno', '{"en":"Operating revenue — total"}'::jsonb, 70, 1, true, array['ME-IS-201', 'ME-IS-202', 'ME-IS-203', 'ME-IS-204', 'ME-IS-205', 'ME-IS-206']::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-210', null, 'Nabavna vrijednost prodate robe', '{"en":"Cost of merchandise sold"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-211', null, 'Troškovi materijala', '{"en":"Cost of materials"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-212', null, 'Troškovi zarada, naknada zarada i ostali lični rashodi', '{"en":"Salary costs and other personal expenses"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-213', null, 'Troškovi proizvodnih usluga', '{"en":"Costs of production services"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-214', null, 'Troškovi amortizacije i rezervisanja', '{"en":"Depreciation and provision costs"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-215', null, 'Nematerijalni troškovi', '{"en":"Intangible costs"}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-220', null, 'Poslovni rashodi — ukupno', '{"en":"Operating expenses — total"}'::jsonb, 140, 1, true, array['ME-IS-210', 'ME-IS-211', 'ME-IS-212', 'ME-IS-213', 'ME-IS-214', 'ME-IS-215']::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-221', null, 'Poslovni rezultat', '{"en":"Operating result"}'::jsonb, 150, 1, true, array['ME-IS-209']::text[], array['ME-IS-220']::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-226', null, 'Finansijski prihodi', '{"en":"Financial revenue"}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-237', null, 'Finansijski rashodi', '{"en":"Financial expenses"}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-241', null, 'Finansijski rezultat', '{"en":"Financial result"}'::jsonb, 180, 1, true, array['ME-IS-226']::text[], array['ME-IS-237']::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-250', null, 'Ostali prihodi', '{"en":"Other revenue"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-260', null, 'Ostali rashodi', '{"en":"Other expenses"}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-270', null, 'Ostali rezultat', '{"en":"Other result"}'::jsonb, 210, 1, true, array['ME-IS-250']::text[], array['ME-IS-260']::text[], null, null, null),
  ('ME-FS-IS', 'ME-IS-244', null, 'Rezultat prije oporezivanja', '{"en":"Result before taxation"}'::jsonb, 220, 1, true, array['ME-IS-221', 'ME-IS-241', 'ME-IS-270']::text[], '{}'::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('ME-FS-BS', 'ME-BS-000', 10, 'code_range', '00', '00', null, 'any'),
    ('ME-FS-BS', 'ME-BS-010', 10, 'code_range', '01', '01', null, 'any'),
    ('ME-FS-BS', 'ME-BS-020', 10, 'code_range', '02', '02', null, 'any'),
    ('ME-FS-BS', 'ME-BS-030', 10, 'code_range', '03', '03', null, 'any'),
    ('ME-FS-BS', 'ME-BS-040', 10, 'code_range', '04', '04', null, 'any'),
    ('ME-FS-BS', 'ME-BS-100', 10, 'code_range', '10', '13', null, 'any'),
    ('ME-FS-BS', 'ME-BS-110', 10, 'code_range', '15', '15', null, 'any'),
    ('ME-FS-BS', 'ME-BS-120', 10, 'code_range', '20', '23', null, 'any'),
    ('ME-FS-BS', 'ME-BS-130', 10, 'code_range', '24', '24', null, 'any'),
    ('ME-FS-BS', 'ME-BS-140', 10, 'code_range', '27', '28', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2000', 10, 'code_range', '30', '30', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2010', 10, 'code_range', '31', '31', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2020', 10, 'code_range', '32', '32', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2030', 10, 'code_range', '33', '33', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2040', 10, 'code_range', '34', '34', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2050', 10, 'code_range', '35', '35', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2100', 10, 'code_range', '40', '41', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2200', 10, 'code_range', '42', '42', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2210', 10, 'code_range', '43', '44', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2220', 10, 'code_range', '45', '45', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2230', 10, 'code_range', '46', '46', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2240', 10, 'code_range', '47', '48', null, 'any'),
    ('ME-FS-BS', 'ME-BS-2250', 10, 'code_range', '49', '49', null, 'any'),
    ('ME-FS-IS', 'ME-IS-201', 10, 'code_range', '60', '60', null, 'any'),
    ('ME-FS-IS', 'ME-IS-202', 10, 'code_range', '61', '61', null, 'any'),
    ('ME-FS-IS', 'ME-IS-203', 10, 'code_range', '62', '62', null, 'any'),
    ('ME-FS-IS', 'ME-IS-204', 10, 'code_range', '63', '63', null, 'any'),
    ('ME-FS-IS', 'ME-IS-205', 10, 'code_range', '64', '64', null, 'any'),
    ('ME-FS-IS', 'ME-IS-206', 10, 'code_range', '65', '65', null, 'any'),
    ('ME-FS-IS', 'ME-IS-210', 10, 'code_range', '50', '50', null, 'any'),
    ('ME-FS-IS', 'ME-IS-211', 10, 'code_range', '51', '51', null, 'any'),
    ('ME-FS-IS', 'ME-IS-212', 10, 'code_range', '52', '52', null, 'any'),
    ('ME-FS-IS', 'ME-IS-213', 10, 'code_range', '53', '53', null, 'any'),
    ('ME-FS-IS', 'ME-IS-214', 10, 'code_range', '54', '54', null, 'any'),
    ('ME-FS-IS', 'ME-IS-215', 10, 'code_range', '55', '55', null, 'any'),
    ('ME-FS-IS', 'ME-IS-226', 10, 'code_range', '66', '66', null, 'any'),
    ('ME-FS-IS', 'ME-IS-237', 10, 'code_range', '56', '56', null, 'any'),
    ('ME-FS-IS', 'ME-IS-250', 10, 'code_range', '67', '68', null, 'any'),
    ('ME-FS-IS', 'ME-IS-260', 10, 'code_range', '57', '58', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('ME', 'Crna Gora', '{"en":"Montenegro"}'::jsonb, array['sr', 'en']::text[], 'EUR', '202', '433', '469', '4698', '341', '612', '510', '241', '243', 'SAL', 'PUR', 'GEN', 'sr', 'retained_earnings', null, null, '351', 'OPN', 'half_up', default, '663', '563', null, null, null, null, '479', '279', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{NNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Zakon o porezu na dodatu vrijednost, član 31 stav 1 — poreski obveznik je dužan da za izvršeni promet proizvoda, odnosno usluga izda račun ili drugi dokument koji služi kao račun; član 32 propisuje obavezne podatke računa, uključujući mjesto, datum izdavanja i redni broj računa (stav 1 tačka 1), ali ne nameće jedan oblik numeracije. Format ovdje je primjer sekvencijalne numeracije, a ne jedini dozvoljeni.',
  numbering_source_key          = 'pdv-zakon',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Zakon o porezu na dodatu vrijednost, član 18 st. 1 i 2 — PDV se obračunava u trenutku isporuke proizvoda, odnosno u trenutku izvršenja usluge, a smatra se da je proizvod isporučen, odnosno usluga izvršena u trenutku izdavanja računa (fakture). Ako račun nije izdat, PDV se obračunava osam dana od dana isporuke, odnosno izvršenja usluge (stav 3); ako je plaćanje u cjelini ili djelimično izvršeno prije izdavanja računa, PDV se obračunava na dan prijema naknade (stav 4).',
  tax_point_source_key          = 'pdv-zakon',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Zakon o računovodstvu, obaveza vjerodostojnog, urednog i ažurnog knjigovodstva; ispravka poslovne promjene koja je već proknjižena vrši se novim knjigovodstvenim dokumentom (stornom ili knjigom uz obrazloženje), a ne brisanjem prethodnog zapisa. Zakon o porezu na dodatu vrijednost, član 39 (ispravka odbitka ulaznog PDV) i praksa izdavanja knjigovodstvenih obavještenja za izmjenu poreske osnovice iz člana 20 stav 9 potvrđuju isti princip za izlazne fakture.',
  posted_edit_policy_source_key = 'racunovodstvo-zakon',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'Crna Gora ne nameće razmjenu strukturiranih elektronskih faktura između preduzeća izgrađenih na semantičkom modelu EN 16931 (Peppol BIS, Factur-X, XRechnung, PINT); nijedan propis to ne zahtijeva na dan izdavanja ovog paketa (`released_at`), pa je `obligation` postavljeno na `none`, a ne na `on_request`. Crna Gora umjesto toga poznaje fiskalizaciju prometa: Zakon o fiskalizaciji u prometu proizvoda i usluga ("Sl. list CG", br. 046/19, 073/19, 080/20, 008/21) nameće poreskom obvezniku da podatke o prometu proizvoda i usluga i fiskalne račune dostavlja Poreskoj upravi u realnom vremenu preko fiskalne službe (obavezno od 01.06.2021 za obveznike koji naplaćuju gotovinom ili platnim karticama). To je izvještavanje državnog servera o pojedinačnom računu u trenutku izdavanja (clearance), a ne razmjena strukturiranog dokumenta između prodavca i kupca — socle ovog izdanja Ekwo OS-a nema modul za fiskalizaciju u realnom vremenu prema državnom serveru; vidjeti README.md i docs/international.md, odjeljak «From Montenegro».',
  einvoice_source_key           = 'fiskalizacija-zakon',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'ME';
