-- Ekwo OS — Tanzania: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/tz at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build tz`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   The Value Added Tax Act, Chapter 148, Revised Edition 2019 (Attorney General's Chambers, United Republic of Tanzania)
--     https://www.mof.go.tz/uploads/documents/en-1676548670-THE%20VALUE%20ADDED%20TAX%20ACT,%20CAP%20148%20R.E.%202019.pdf
--   The Companies Act, 2002, Chapter 212 — ss. 151, 153, 154 (accounts and audit) (Tanzania Legal Information Institute (TanzLII) / Laws.Africa)
--     https://media.tanzlii.org/media/legislation/323287/source_file/9e4d2bac245b2936/2002-12.pdf
--   Value Added Tax (VAT) — rate, registration threshold, filing (Tanzania Revenue Authority)
--     https://www.tra.go.tz/page/value-added-tax-vat
--   Know about Electronic Fiscal Devices (EFD) (Tanzania Revenue Authority)
--     https://www.tra.go.tz/page/know-about-e-fiscal-devices-efd
--   IDRAS — the Integrated Domestic Revenue Administration System, where a value added tax return is filed (Tanzania Revenue Authority)
--     https://gateway.tra.go.tz/Efiling/login.aspx
--   Tanzania, United Republic of — Member Country (National Board of Accountants and Auditors: adoption of the IFRS Accounting Standards and the IFRS for SMEs Accounting Standard) (International Federation of Accountants)
--     https://www.ifac.org/about-ifac/membership/profile/tanzania-united-republic
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('TZ', 'Tanzania', '0.1.0', date '2026-09-26', '20260923110000', 'community', null, null, '5d114c3149ee9eac982ad49a886561351a711a910cee91ae1661ba48f77c26f2', '[{"key":"vat-act","title":"The Value Added Tax Act, Chapter 148, Revised Edition 2019","publisher":"Attorney General''s Chambers, United Republic of Tanzania","url":"https://www.mof.go.tz/uploads/documents/en-1676548670-THE%20VALUE%20ADDED%20TAX%20ACT,%20CAP%20148%20R.E.%202019.pdf","consulted_on":"2026-09-26","kind":"law"},{"key":"companies-act-2002","title":"The Companies Act, 2002, Chapter 212 — ss. 151, 153, 154 (accounts and audit)","publisher":"Tanzania Legal Information Institute (TanzLII) / Laws.Africa","url":"https://media.tanzlii.org/media/legislation/323287/source_file/9e4d2bac245b2936/2002-12.pdf","consulted_on":"2026-09-26","kind":"law"},{"key":"tra-vat","title":"Value Added Tax (VAT) — rate, registration threshold, filing","publisher":"Tanzania Revenue Authority","url":"https://www.tra.go.tz/page/value-added-tax-vat","consulted_on":"2026-09-26","kind":"guidance"},{"key":"efd-guidance","title":"Know about Electronic Fiscal Devices (EFD)","publisher":"Tanzania Revenue Authority","url":"https://www.tra.go.tz/page/know-about-e-fiscal-devices-efd","consulted_on":"2026-09-26","kind":"guidance"},{"key":"idras","title":"IDRAS — the Integrated Domestic Revenue Administration System, where a value added tax return is filed","publisher":"Tanzania Revenue Authority","url":"https://gateway.tra.go.tz/Efiling/login.aspx","consulted_on":"2026-09-26","kind":"portal"},{"key":"ifac-tanzania","title":"Tanzania, United Republic of — Member Country (National Board of Accountants and Auditors: adoption of the IFRS Accounting Standards and the IFRS for SMEs Accounting Standard)","publisher":"International Federation of Accountants","url":"https://www.ifac.org/about-ifac/membership/profile/tanzania-united-republic","consulted_on":"2026-09-26","kind":"guidance"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('TZ', 'default', 'Tanzania reference chart of accounts', '{}'::jsonb, true, 'companies', array['TZ-NBAA-IS', 'TZ-NBAA-SFP']::text[], null, 'There is no legal chart of accounts in Tanzania. Companies Act, 2002 (Cap. 212), s. 151(1) requires every company to keep proper books of account sufficient to disclose the company''s financial position and to enable the directors to ensure that a balance sheet, profit and loss account and cash flow statement comply with the requirements of the Act; s. 153 requires the directors to prepare, for each accounting period, a profit and loss account, a balance sheet and a cash flow statement; s. 154(1) requires each of them to give a true and fair view; s. 154(2) requires them to comply with the requirements prescribed by the Minister or the National Board of Accountants and Auditors, having regard to generally accepted principles of accounting. NBAA, the standard-setting body the Auditors and Accountants (Registration) Act (Cap. 286) recognises, adopted the IFRS Accounting Standards and, for a commercial entity that is not a public-interest entity, the IFRS for SMEs Accounting Standard. This chart is original: four digits, blocked so that each range reaches one line of the IFRS for SMEs statements below, with the accounts a Tanzanian company actually keeps — VAT input and output tax, import VAT owed to TRA at the border, NSSF, Workers Compensation Fund and Skills Development Levy contributions, withholding tax, amounts due to directors.', 'companies-act-2002')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('TZ', 'default', '1000', 'Petty cash', '{}'::jsonb, 'asset_cash', false, null, 10),
  ('TZ', 'default', '1010', 'Current account — TZS', '{}'::jsonb, 'asset_cash', false, null, 20),
  ('TZ', 'default', '1020', 'Fixed deposits placed for three months or less', '{}'::jsonb, 'asset_cash', false, null, 30),
  ('TZ', 'default', '1030', 'Foreign currency account', '{}'::jsonb, 'asset_cash', false, null, 40),
  ('TZ', 'default', '1040', 'Cash in transit — mobile money and card settlements', '{}'::jsonb, 'asset_cash', false, null, 50),
  ('TZ', 'default', '1100', 'Trade receivables', '{}'::jsonb, 'asset_receivable', true, null, 60),
  ('TZ', 'default', '1110', 'Trade receivables — allowance for impairment', '{}'::jsonb, 'asset_current', false, null, 70),
  ('TZ', 'default', '1120', 'Other receivables', '{}'::jsonb, 'asset_current', false, null, 80),
  ('TZ', 'default', '1130', 'Amounts due from related companies', '{}'::jsonb, 'asset_current', false, null, 90),
  ('TZ', 'default', '1140', 'Deposits paid', '{}'::jsonb, 'asset_current', false, null, 100),
  ('TZ', 'default', '1150', 'VAT input tax', '{}'::jsonb, 'asset_current', false, null, 110),
  ('TZ', 'default', '1155', 'VAT refundable by TRA — net of a filed return', '{}'::jsonb, 'asset_current', true, null, 120),
  ('TZ', 'default', '1160', 'Advances to staff', '{}'::jsonb, 'asset_current', false, null, 130),
  ('TZ', 'default', '1200', 'Inventories — goods for resale', '{}'::jsonb, 'asset_current', false, null, 140),
  ('TZ', 'default', '1210', 'Inventories — raw materials', '{}'::jsonb, 'asset_current', false, null, 150),
  ('TZ', 'default', '1220', 'Inventories — work in progress', '{}'::jsonb, 'asset_current', false, null, 160),
  ('TZ', 'default', '1230', 'Inventories — finished goods', '{}'::jsonb, 'asset_current', false, null, 170),
  ('TZ', 'default', '1300', 'Short-term investments', '{}'::jsonb, 'asset_current', false, null, 180),
  ('TZ', 'default', '1350', 'Current tax recoverable', '{}'::jsonb, 'asset_current', false, null, 190),
  ('TZ', 'default', '1400', 'Prepayments', '{}'::jsonb, 'asset_prepayments', false, null, 200),
  ('TZ', 'default', '1410', 'Accrued income', '{}'::jsonb, 'asset_prepayments', false, null, 210),
  ('TZ', 'default', '1600', 'Land and buildings — cost', '{}'::jsonb, 'asset_fixed', false, null, 220),
  ('TZ', 'default', '1601', 'Land and buildings — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 230),
  ('TZ', 'default', '1610', 'Leasehold improvements — cost', '{}'::jsonb, 'asset_fixed', false, null, 240),
  ('TZ', 'default', '1611', 'Leasehold improvements — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 250),
  ('TZ', 'default', '1620', 'Plant and machinery — cost', '{}'::jsonb, 'asset_fixed', false, null, 260),
  ('TZ', 'default', '1621', 'Plant and machinery — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 270),
  ('TZ', 'default', '1630', 'Office equipment — cost', '{}'::jsonb, 'asset_fixed', false, null, 280),
  ('TZ', 'default', '1631', 'Office equipment — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 290),
  ('TZ', 'default', '1640', 'Computers — cost', '{}'::jsonb, 'asset_fixed', false, null, 300),
  ('TZ', 'default', '1641', 'Computers — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 310),
  ('TZ', 'default', '1650', 'Furniture and fittings — cost', '{}'::jsonb, 'asset_fixed', false, null, 320),
  ('TZ', 'default', '1651', 'Furniture and fittings — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 330),
  ('TZ', 'default', '1660', 'Motor vehicles — cost', '{}'::jsonb, 'asset_fixed', false, null, 340),
  ('TZ', 'default', '1661', 'Motor vehicles — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 350),
  ('TZ', 'default', '1670', 'Right-of-use assets — cost', '{}'::jsonb, 'asset_fixed', false, null, 360),
  ('TZ', 'default', '1671', 'Right-of-use assets — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 370),
  ('TZ', 'default', '1700', 'Investment property', '{}'::jsonb, 'asset_non_current', false, null, 380),
  ('TZ', 'default', '1750', 'Intangible assets — cost', '{}'::jsonb, 'asset_fixed', false, null, 390),
  ('TZ', 'default', '1751', 'Intangible assets — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 400),
  ('TZ', 'default', '1760', 'Goodwill', '{}'::jsonb, 'asset_fixed', false, null, 410),
  ('TZ', 'default', '1800', 'Investments in associates', '{}'::jsonb, 'asset_non_current', false, null, 420),
  ('TZ', 'default', '1810', 'Investments in joint ventures', '{}'::jsonb, 'asset_non_current', false, null, 430),
  ('TZ', 'default', '1830', 'Long-term financial assets', '{}'::jsonb, 'asset_non_current', false, null, 440),
  ('TZ', 'default', '1840', 'Long-term deposits', '{}'::jsonb, 'asset_non_current', false, null, 450),
  ('TZ', 'default', '1900', 'Deferred tax assets', '{}'::jsonb, 'asset_non_current', false, null, 460),
  ('TZ', 'default', '2000', 'Trade payables', '{}'::jsonb, 'liability_payable', true, null, 470),
  ('TZ', 'default', '2010', 'Accrued expenses', '{}'::jsonb, 'liability_current', false, null, 480),
  ('TZ', 'default', '2020', 'Other payables', '{}'::jsonb, 'liability_current', false, null, 490),
  ('TZ', 'default', '2030', 'Amounts due to related companies', '{}'::jsonb, 'liability_current', false, null, 500),
  ('TZ', 'default', '2040', 'Deposits received from customers', '{}'::jsonb, 'liability_current', false, null, 510),
  ('TZ', 'default', '2100', 'VAT output tax', '{}'::jsonb, 'liability_current', false, null, 520),
  ('TZ', 'default', '2110', 'VAT payable to TRA — net of a filed return', '{}'::jsonb, 'liability_current', true, null, 530),
  ('TZ', 'default', '2125', 'Import VAT payable to TRA at the border', '{}'::jsonb, 'liability_current', false, null, 540),
  ('TZ', 'default', '2140', 'Withholding tax payable to TRA', '{}'::jsonb, 'liability_current', false, null, 550),
  ('TZ', 'default', '2150', 'NSSF contributions payable', '{}'::jsonb, 'liability_current', false, null, 560),
  ('TZ', 'default', '2155', 'Workers Compensation Fund contributions payable', '{}'::jsonb, 'liability_current', false, null, 570),
  ('TZ', 'default', '2160', 'Skills Development Levy payable', '{}'::jsonb, 'liability_current', false, null, 580),
  ('TZ', 'default', '2180', 'Salaries payable', '{}'::jsonb, 'liability_current', false, null, 590),
  ('TZ', 'default', '2190', 'Directors'' fees payable', '{}'::jsonb, 'liability_current', false, null, 600),
  ('TZ', 'default', '2200', 'Bank overdraft', '{}'::jsonb, 'liability_current', false, null, 610),
  ('TZ', 'default', '2210', 'Bank loans — current portion', '{}'::jsonb, 'liability_current', false, null, 620),
  ('TZ', 'default', '2220', 'Lease liabilities — current portion', '{}'::jsonb, 'liability_current', false, null, 630),
  ('TZ', 'default', '2230', 'Hire purchase — current portion', '{}'::jsonb, 'liability_current', false, null, 640),
  ('TZ', 'default', '2240', 'Corporate credit card', '{}'::jsonb, 'liability_credit_card', false, null, 650),
  ('TZ', 'default', '2250', 'Amounts due to directors', '{}'::jsonb, 'liability_current', false, null, 660),
  ('TZ', 'default', '2300', 'Current tax payable', '{}'::jsonb, 'liability_current', false, null, 670),
  ('TZ', 'default', '2350', 'Provision for unutilised leave', '{}'::jsonb, 'liability_current', false, null, 680),
  ('TZ', 'default', '2360', 'Other provisions — current', '{}'::jsonb, 'liability_current', false, null, 690),
  ('TZ', 'default', '2400', 'Bank loans — non-current portion', '{}'::jsonb, 'liability_non_current', false, null, 700),
  ('TZ', 'default', '2410', 'Lease liabilities — non-current portion', '{}'::jsonb, 'liability_non_current', false, null, 710),
  ('TZ', 'default', '2420', 'Hire purchase — non-current portion', '{}'::jsonb, 'liability_non_current', false, null, 720),
  ('TZ', 'default', '2430', 'Loans from shareholders and directors — non-current', '{}'::jsonb, 'liability_non_current', false, null, 730),
  ('TZ', 'default', '2500', 'Deferred tax liabilities', '{}'::jsonb, 'liability_non_current', false, null, 740),
  ('TZ', 'default', '2550', 'Provision for reinstatement costs', '{}'::jsonb, 'liability_non_current', false, null, 750),
  ('TZ', 'default', '2990', 'Suspense account', '{}'::jsonb, 'liability_current', false, null, 760),
  ('TZ', 'default', '3000', 'Share capital', '{}'::jsonb, 'equity', false, null, 770),
  ('TZ', 'default', '3010', 'Treasury shares', '{}'::jsonb, 'equity', false, null, 780),
  ('TZ', 'default', '3100', 'Other reserves', '{}'::jsonb, 'equity', false, null, 790),
  ('TZ', 'default', '3110', 'Foreign currency translation reserve', '{}'::jsonb, 'equity', false, null, 800),
  ('TZ', 'default', '3200', 'Retained earnings', '{}'::jsonb, 'equity_retained', false, null, 810),
  ('TZ', 'default', '3210', 'Dividends paid', '{}'::jsonb, 'equity_retained', false, null, 820),
  ('TZ', 'default', '4000', 'Sales of goods', '{}'::jsonb, 'income', false, null, 830),
  ('TZ', 'default', '4010', 'Services rendered', '{}'::jsonb, 'income', false, null, 840),
  ('TZ', 'default', '4020', 'Export sales of goods', '{}'::jsonb, 'income', false, null, 850),
  ('TZ', 'default', '4030', 'Export of services', '{}'::jsonb, 'income', false, null, 860),
  ('TZ', 'default', '4500', 'Interest income', '{}'::jsonb, 'income_other', false, null, 870),
  ('TZ', 'default', '4510', 'Dividend income', '{}'::jsonb, 'income_other', false, null, 880),
  ('TZ', 'default', '4520', 'Rental income', '{}'::jsonb, 'income_other', false, null, 890),
  ('TZ', 'default', '4530', 'Government grants', '{}'::jsonb, 'income_other', false, null, 900),
  ('TZ', 'default', '4700', 'Foreign exchange gains', '{}'::jsonb, 'income_other', false, null, 910),
  ('TZ', 'default', '4750', 'Gain on disposal of property plant and equipment', '{}'::jsonb, 'income_other', false, null, 920),
  ('TZ', 'default', '4790', 'Other income', '{}'::jsonb, 'income_other', false, null, 930),
  ('TZ', 'default', '5000', 'Purchases of goods for resale', '{}'::jsonb, 'expense_direct_cost', false, null, 940),
  ('TZ', 'default', '5010', 'Freight inwards and import duties', '{}'::jsonb, 'expense_direct_cost', false, null, 950),
  ('TZ', 'default', '5020', 'Subcontract costs', '{}'::jsonb, 'expense_direct_cost', false, null, 960),
  ('TZ', 'default', '5100', 'Changes in inventories', '{}'::jsonb, 'expense_direct_cost', false, null, 970),
  ('TZ', 'default', '6000', 'Salaries and wages', '{}'::jsonb, 'expense', false, null, 980),
  ('TZ', 'default', '6010', 'Directors'' remuneration', '{}'::jsonb, 'expense', false, null, 990),
  ('TZ', 'default', '6020', 'Directors'' fees', '{}'::jsonb, 'expense', false, null, 1000),
  ('TZ', 'default', '6030', 'NSSF contributions — employer', '{}'::jsonb, 'expense', false, null, 1010),
  ('TZ', 'default', '6035', 'Workers Compensation Fund contributions — employer', '{}'::jsonb, 'expense', false, null, 1020),
  ('TZ', 'default', '6040', 'Skills Development Levy', '{}'::jsonb, 'expense', false, null, 1030),
  ('TZ', 'default', '6060', 'Staff welfare', '{}'::jsonb, 'expense', false, null, 1040),
  ('TZ', 'default', '6070', 'Staff medical expenses and insurance', '{}'::jsonb, 'expense', false, null, 1050),
  ('TZ', 'default', '6080', 'Staff training', '{}'::jsonb, 'expense', false, null, 1060),
  ('TZ', 'default', '6200', 'Depreciation of property plant and equipment', '{}'::jsonb, 'expense_depreciation', false, null, 1070),
  ('TZ', 'default', '6210', 'Depreciation of right-of-use assets', '{}'::jsonb, 'expense_depreciation', false, null, 1080),
  ('TZ', 'default', '6220', 'Amortisation of intangible assets', '{}'::jsonb, 'expense_depreciation', false, null, 1090),
  ('TZ', 'default', '6300', 'Rent — short-term leases', '{}'::jsonb, 'expense', false, null, 1100),
  ('TZ', 'default', '6310', 'Utilities', '{}'::jsonb, 'expense', false, null, 1110),
  ('TZ', 'default', '6320', 'Repairs and maintenance', '{}'::jsonb, 'expense', false, null, 1120),
  ('TZ', 'default', '6330', 'Cleaning and security services', '{}'::jsonb, 'expense', false, null, 1130),
  ('TZ', 'default', '6340', 'Telephone and internet', '{}'::jsonb, 'expense', false, null, 1140),
  ('TZ', 'default', '6350', 'Software subscriptions', '{}'::jsonb, 'expense', false, null, 1150),
  ('TZ', 'default', '6360', 'Advertising and marketing', '{}'::jsonb, 'expense', false, null, 1160),
  ('TZ', 'default', '6370', 'Travelling', '{}'::jsonb, 'expense', false, null, 1170),
  ('TZ', 'default', '6380', 'Motor vehicle expenses', '{}'::jsonb, 'expense', false, null, 1180),
  ('TZ', 'default', '6390', 'Entertainment', '{}'::jsonb, 'expense', false, null, 1190),
  ('TZ', 'default', '6400', 'Subscriptions and memberships', '{}'::jsonb, 'expense', false, null, 1200),
  ('TZ', 'default', '6410', 'Insurance', '{}'::jsonb, 'expense', false, null, 1210),
  ('TZ', 'default', '6420', 'Professional fees', '{}'::jsonb, 'expense', false, null, 1220),
  ('TZ', 'default', '6430', 'Audit fees', '{}'::jsonb, 'expense', false, null, 1230),
  ('TZ', 'default', '6440', 'Company secretarial and registration fees', '{}'::jsonb, 'expense', false, null, 1240),
  ('TZ', 'default', '6450', 'Bank charges', '{}'::jsonb, 'expense', false, null, 1250),
  ('TZ', 'default', '6460', 'Printing and stationery', '{}'::jsonb, 'expense', false, null, 1260),
  ('TZ', 'default', '6470', 'Postage and courier', '{}'::jsonb, 'expense', false, null, 1270),
  ('TZ', 'default', '6480', 'Licences permits and local government fees', '{}'::jsonb, 'expense', false, null, 1280),
  ('TZ', 'default', '6490', 'Royalties', '{}'::jsonb, 'expense', false, null, 1290),
  ('TZ', 'default', '6500', 'Bad debts written off', '{}'::jsonb, 'expense', false, null, 1300),
  ('TZ', 'default', '6510', 'Impairment loss on trade receivables', '{}'::jsonb, 'expense', false, null, 1310),
  ('TZ', 'default', '6900', 'Donations', '{}'::jsonb, 'expense', false, null, 1320),
  ('TZ', 'default', '6950', 'Foreign exchange losses', '{}'::jsonb, 'expense', false, null, 1330),
  ('TZ', 'default', '6960', 'Loss on disposal of property plant and equipment', '{}'::jsonb, 'expense', false, null, 1340),
  ('TZ', 'default', '6990', 'Rounding differences', '{}'::jsonb, 'expense', false, null, 1350),
  ('TZ', 'default', '7000', 'Interest on bank loans', '{}'::jsonb, 'expense', false, null, 1360),
  ('TZ', 'default', '7010', 'Interest on lease liabilities', '{}'::jsonb, 'expense', false, null, 1370),
  ('TZ', 'default', '7020', 'Hire purchase interest', '{}'::jsonb, 'expense', false, null, 1380),
  ('TZ', 'default', '7030', 'Interest on loans from related parties and others', '{}'::jsonb, 'expense', false, null, 1390),
  ('TZ', 'default', '8000', 'Current income tax expense', '{}'::jsonb, 'expense', false, null, 1400),
  ('TZ', 'default', '8010', 'Deferred tax expense', '{}'::jsonb, 'expense', false, null, 1410),
  ('TZ', 'default', '8020', 'Under or over provision of income tax in prior years', '{}'::jsonb, 'expense', false, null, 1420)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('TZ', 'BNK', 'Bank', '{}'::jsonb, 'bank', 30),
  ('TZ', 'CSH', 'Petty cash', '{}'::jsonb, 'cash', 40),
  ('TZ', 'GEN', 'General journal', '{}'::jsonb, 'general', 50),
  ('TZ', 'OPN', 'Opening balances', '{}'::jsonb, 'opening', 60),
  ('TZ', 'PUR', 'Purchases journal', '{}'::jsonb, 'purchase', 20),
  ('TZ', 'SAL', 'Sales journal', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('TZ', 'TZ-P-18', 'Purchase, standard rate 18 %, deductible', '{}'::jsonb, 'A local purchase at the general rate, acquired for the purpose of making taxable supplies', 'percent', 18, 'purchase', 'domestic', date '2015-07-01', null, 'Value Added Tax Act, s. 68(1) — a taxable person is allowed a credit for input tax incurred if the goods, services or immovable property were acquired in Mainland Tanzania by the person in the course of the person''s economic activity and for the purpose of making taxable supplies, and the person paid, or is liable to pay, the consideration for the supply.', null, null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-P-18-BL', 'Purchase, standard rate 18 %, input tax disallowed', '{}'::jsonb, 'Entertainment, a club or association membership, or a passenger vehicle and its running costs, bought other than in the ordinary course of a business that deals in, hires out or provides transport services in them', 'percent', 18, 'purchase', 'domestic', date '2015-07-01', null, 'Value Added Tax Act, s. 68(3) — a taxable person is not allowed an input tax credit for an acquisition, to the extent it is used to provide entertainment (unless the person''s economic activity involves providing entertainment in the ordinary course of that activity); for a membership or right of entry to a club, association or society of a sporting, social or recreational nature; or for the acquisition or import of a passenger vehicle, or of spare parts or repair and maintenance services for one, unless the person''s economic activity involves dealing in, hiring out, or providing transport services in passenger vehicles and the vehicle was acquired for that purpose. The disallowed tax is not a claim on the return, so it lands on the account of the line it taxes and reaches no box.', null, null, 120, 'vat', false, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-P-EX', 'Purchase, exempt', '{}'::jsonb, 'An insurance premium, or another exempt supply bought for the business', 'percent', 0, 'purchase', 'exempt', date '2015-07-01', null, 'Value Added Tax Act, s. 6(1); First Schedule, Part I, item 13 — life insurance or health insurance, and insurance for workers compensation, are exempt intermediary services, so there is no value added tax to deduct on the premium.', null, null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-P-IMP', 'Import of goods, VAT paid at the border', '{}'::jsonb, 'Value added tax collected by the Commissioner General on importation and claimed as input tax once paid', 'percent', 18, 'purchase', 'import', date '2015-07-01', null, 'Value Added Tax Act, s. 8(1) and (3) — the value added tax payable on a taxable import is paid where goods are entered for home consumption, in accordance with the East African Customs Management Act, and the Commissioner General collects it at the time of import; s. 9 — the value of an import; s. 68(1)(c) — input tax includes value added tax paid under this Act on a taxable import. The tax is owed to the Tanzania Revenue Authority at the border and not to the supplier, so it waits on 2125 until the import declaration is settled.', null, null, 140, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-P-RC-IMPSVC', 'Imported service, self-charged and claimed', '{}'::jsonb, 'A service supplied by a person with no place of business in Mainland Tanzania, acquired for a taxable economic activity', 'percent', 18, 'purchase', 'foreign_services_received', date '2015-07-01', null, 'Value Added Tax Act, s. 2(1), definition of "taxable supply", paragraph (b) — a supply of imported services to a taxable person who acquires them in the course of an economic activity is itself a taxable supply where, had the supply been made in Mainland Tanzania, it would have been taxed at a rate other than zero and the purchaser would not have been entitled to a credit for ninety per cent or more of the tax; s. 4(c) — the purchaser of a taxable supply of imported services is the person liable to pay the tax; s. 68(1)(a) and s. 68(2) — input tax includes value added tax payable by the person on a taxable supply of imported services, and the purchaser is not allowed the input tax credit unless the output tax has been accounted for in the same return. Unlike a jurisdiction where a reverse charge reaches only an input-side box, the Tanzanian Act makes the same amount both the purchaser''s output tax and input tax in one return, so this code posts the deemed output liability to box 5 and the matching claim to box 10.', null, null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-S-18', 'Sale, standard rate 18 %', '{}'::jsonb, 'A taxable supply made in Mainland Tanzania that is neither zero-rated nor exempt', 'percent', 18, 'sale', 'domestic', date '2015-07-01', null, 'Value Added Tax Act (Cap. 148), s. 3 — value added tax is imposed and payable on taxable supplies and taxable imports; s. 5(1) — the amount of value added tax payable is calculated by multiplying the value of the supply by the value added tax rate, which is eighteen per cent. `vat_category` and `exemption_code` are left null: this pack declares no `einvoicing.profile`, so BT-118/BT-151/BT-121 are not terms of any invoice a Mainland Tanzanian company issues.', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-S-EX-HEALTH', 'Sale, exempt (health care services)', '{}'::jsonb, 'Medical, dental, nursing, rehabilitation or similar services provided by or in an institution approved by the Government and by or under the supervision of a person registered to perform the service', 'percent', 0, 'sale', 'exempt', date '2015-07-01', null, 'Value Added Tax Act, s. 6(1) — except as otherwise provided in this Act or the Schedule, a supply not listed there is not exempt; First Schedule, Part I, item 10(1) — a supply of medical, dental, nursing, convalescent, rehabilitation, midwifery, paramedical, optical or other similar services is exempt where the services are provided by or in an institution approved for their provision by the Government, and by or under the supervision and control of a person registered as qualified to perform that service under Tanzanian law.', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-S-ZR-EXP', 'Sale, zero-rated (export of goods)', '{}'::jsonb, 'Goods exported from Mainland Tanzania within the meaning the Act gives to "export"', 'percent', 0, 'sale', 'export', date '2015-07-01', null, 'Value Added Tax Act, s. 5(2) — where the supply is zero-rated, the value added tax rate is zero per cent; s. 55(1) — a supply of goods is zero-rated if the goods are exported within the meaning of "export" under s. 2, that is, the removal of goods from a place in Mainland Tanzania to a place outside the United Republic.', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-S-ZR-SVC', 'Sale, zero-rated (export of services)', '{}'::jsonb, 'A service whose customer is outside the United Republic at the time of supply and who effectively uses or enjoys it there', 'percent', 0, 'sale', 'export', date '2016-07-01', null, 'Value Added Tax Act, s. 61A(1), inserted by the Finance Act, 2016 (Act No. 2 of 2016, s. 96) — a supply of services is zero-rated if the customer is outside the United Republic at the time of supply and effectively uses or enjoys the services outside the United Republic, and the services are neither directly related to land situated in the United Republic nor physically performed on goods situated in the United Republic at the time of supply; s. 61A(2) — not zero-rated where the supply is of a right or option to receive a subsequent supply of something else in the United Republic, or is rendered under an agreement with a non-resident to a person in the United Republic who is not a registered person.', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('TZ', 'TZ-S-ZR-ZNZ', 'Sale, zero-rated (locally manufactured goods supplied to Tanzania Zanzibar)', '{}'::jsonb, 'Locally manufactured goods supplied by a local manufacturer to a taxable person registered under the value added tax law of Tanzania Zanzibar', 'percent', 0, 'sale', 'export', date '2016-07-01', null, 'Value Added Tax Act, s. 55A, inserted by the Finance Act, 2016 (Act No. 2 of 2016, s. 94) — a supply of locally manufactured goods by a local manufacturer is zero-rated if the goods are supplied to a taxable person registered under the value added tax law administered in Tanzania Zanzibar and are removed from Mainland Tanzania without being effectively used or enjoyed in Mainland Tanzania. Zanzibar administers its own value added tax under a separate law, so this movement is zero-rated the way an export to a country outside the United Republic is, and not treated as a domestic supply; `treatment` is declared `export` for that reason, and the gap between this and a true cross-border export is recorded in docs/international.md.', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('TZ-P-18', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-18', 'invoice', 'tax', 100, '1150', '7', array['7']::text[], 100, 'TZ-VAT-RETURN', 20),
    ('TZ-P-18', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-18', 'credit_note', 'tax', 100, '1150', '7', array['7']::text[], -100, 'TZ-VAT-RETURN', 20),
    ('TZ-P-18-BL', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('TZ-P-18-BL', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('TZ-P-18-BL', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('TZ-P-18-BL', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('TZ-P-EX', 'invoice', 'base', 100, null, '8', array['8']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-EX', 'credit_note', 'base', 100, null, '8', array['8']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-IMP', 'invoice', 'base', 100, null, '9', array['9']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-IMP', 'invoice', 'tax', 100, '1150', '9', array['9']::text[], 100, 'TZ-VAT-RETURN', 20),
    ('TZ-P-IMP', 'invoice', 'tax', -100, '2125', null, null, 100, null, 30),
    ('TZ-P-IMP', 'credit_note', 'base', 100, null, '9', array['9']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-IMP', 'credit_note', 'tax', 100, '1150', '9', array['9']::text[], -100, 'TZ-VAT-RETURN', 20),
    ('TZ-P-IMP', 'credit_note', 'tax', -100, '2125', null, null, 100, null, 30),
    ('TZ-P-RC-IMPSVC', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-RC-IMPSVC', 'invoice', 'tax', 100, '1150', '10', array['10']::text[], 100, 'TZ-VAT-RETURN', 20),
    ('TZ-P-RC-IMPSVC', 'invoice', 'tax', -100, '2100', '5', array['5']::text[], 100, 'TZ-VAT-RETURN', 30),
    ('TZ-P-RC-IMPSVC', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-P-RC-IMPSVC', 'credit_note', 'tax', 100, '1150', '10', array['10']::text[], -100, 'TZ-VAT-RETURN', 20),
    ('TZ-P-RC-IMPSVC', 'credit_note', 'tax', -100, '2100', '5', array['5']::text[], -100, 'TZ-VAT-RETURN', 30),
    ('TZ-S-18', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-18', 'invoice', 'tax', 100, '2100', '1', array['1']::text[], 100, 'TZ-VAT-RETURN', 20),
    ('TZ-S-18', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-18', 'credit_note', 'tax', 100, '2100', '1', array['1']::text[], -100, 'TZ-VAT-RETURN', 20),
    ('TZ-S-EX-HEALTH', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-EX-HEALTH', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-ZR-EXP', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-ZR-EXP', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-ZR-SVC', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-ZR-SVC', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-ZR-ZNZ', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'TZ-VAT-RETURN', 10),
    ('TZ-S-ZR-ZNZ', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'TZ-VAT-RETURN', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'TZ' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('TZ', 'TZ-VAT-RETURN', 'VAT return', array['month']::declaration_period[], 'month'::declaration_period, date '2015-07-01', null, 'Value Added Tax Act (Cap. 148), s. 2(1) — a "tax period" means a calendar month; s. 66(1) — a taxable person lodges a value added tax return in the form and manner prescribed by the Minister, on the twentieth day of the month after the tax period, whether or not a net amount is payable for that period; s. 67(1) — the net amount payable is calculated by adding all output tax that becomes payable in the tax period, subtracting all input tax credits allowed in that period, and adjusting the result by any increasing or decreasing adjustments. No box-by-box specification of the on-screen field layout of the Tanzania Revenue Authority''s electronic return (filed through the IDRAS portal, which superseded the paper form ITX 240.02.B) could be independently verified from an official source at the time this pack was written — the archived paper form no longer resolves on tra.go.tz. The boxes below are this pack''s own numbering of the return the Act itself describes in ss. 66 to 68, not a transcription of TRA''s field numbers; a reviewer who can check the current IDRAS screen against them is asked to in packs/tz/README.md.', true,'day_of_month_after_period'::filing_deadline_rule, 20, null, 'Value Added Tax Act, s. 66(1) — the return is lodged, and s. 67(3)(a) — the net amount is paid, on the twentieth day of the month after the tax period; s. 66(7) — where the twentieth day falls on a Saturday, Sunday or public holiday, the return is lodged on the first working day following it.', 'vat-act', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('TZ', 'TZ-VAT-RETURN', '1', 'base', 'Standard-rated sales — value', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 5(1) — the value of a taxable supply taxed at the general rate.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '1', 'tax', 'Standard-rated sales — output VAT', '{}'::jsonb, 15, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 5(1) — the value added tax charged on the supply at eighteen per cent.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '2', 'base', 'Zero-rated sales', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, ss. 55, 55A and 61A — exports of goods, locally manufactured goods supplied to Tanzania Zanzibar, and exports of services, all zero-rated under Part IV(b) of the Act.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '3', 'base', 'Exempt sales', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 6(1) and the First Schedule — a supply exempted by the Schedule.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '4', 'total', 'Total sales', '{}'::jsonb, 40, null, array['1:base', '2', '3']::text[], '{}'::text[], null, null, false, false, null, 'The sum of standard-rated, zero-rated and exempt sales for the tax period.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '5', 'base', 'Imported services — deemed value', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 2(1), definition of "taxable supply", paragraph (b) — the value of a taxable supply of imported services the purchaser is deemed to have made to itself.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '5', 'tax', 'Imported services — output VAT self-charged', '{}'::jsonb, 55, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 4(c) and s. 2(1) definition of "output tax", paragraph (b) — value added tax payable by the purchaser on a taxable supply of imported services acquired.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '6', 'total', 'Total output tax', '{}'::jsonb, 60, null, array['1:tax', '5:tax']::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 67(1)(a) — all output tax that becomes payable by the taxable person in the tax period.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '7', 'base', 'Standard-rated purchases — value', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 68(1) — the value of a local purchase whose input tax is claimable.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '7', 'tax', 'Standard-rated purchases — input VAT', '{}'::jsonb, 75, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 68(1) — the input tax credit allowed on the purchase.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '8', 'base', 'Exempt purchases', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 6(1) and the First Schedule — a purchase exempted by the Schedule, carrying no value added tax to deduct.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '9', 'base', 'Import of goods — value', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 9 — the value of an import of goods.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '9', 'tax', 'Import of goods — input VAT', '{}'::jsonb, 95, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 8 and s. 68(1)(c) — value added tax paid to the Commissioner General on a taxable import, claimed as input tax.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '10', 'tax', 'Imported services — input VAT claimed', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 68(1)(a) and s. 68(2) — value added tax payable on a taxable supply of imported services is also input tax of the purchaser, claimable once the matching output tax is accounted for in the same return.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '11', 'total', 'Total purchases', '{}'::jsonb, 110, null, array['7:base', '8', '9:base']::text[], '{}'::text[], null, null, false, false, null, 'The sum of standard-rated, exempt and imported purchases for the tax period.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '12', 'total', 'Total input tax credit', '{}'::jsonb, 120, null, array['7:tax', '9:tax', '10']::text[], '{}'::text[], null, null, false, false, null, 'Value Added Tax Act, s. 67(1)(b) — all input tax credits allowed in the tax period.', 'vat-act'),
  ('TZ', 'TZ-VAT-RETURN', '13', 'total', 'Net VAT payable / (credit)', '{}'::jsonb, 130, null, array['6']::text[], array['12']::text[], null, null, false, false, null, 'Value Added Tax Act, s. 67(1) and (3) — the net amount payable for the tax period is output tax less input tax credits, adjusted for any increasing or decreasing adjustment; a positive amount is accounted for and paid by the day the return is due, s. 67(3)(a); a negative amount is a negative net amount, carried forward under s. 81 or refunded within the conditions s. 82 sets, neither of which this pack carries — see packs/tz/README.md.', 'vat-act')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('TZ-NBAA-IS', 'TZ', 'default', 'Profit and loss account', 'income_statement', 'IFRS-SME', date '2018-01-01', null, 'Companies Act, 2002 (Cap. 212), s. 153(a) — the directors prepare a profit and loss account for each accounting period; s. 154(1) — it gives a true and fair view of the profit or loss of the company for the accounting period. The IFRS for SMEs Accounting Standard''s illustrative statement of comprehensive income aggregates expenses by nature, which these lines follow.', 'companies-act-2002'),
  ('TZ-NBAA-SFP', 'TZ', 'default', 'Statement of financial position', 'balance_sheet', 'IFRS-SME', date '2018-01-01', null, 'Companies Act, 2002 (Cap. 212), s. 153 — the directors of every company prepare individual accounts for each accounting period indicating a profit and loss account, a balance sheet as at the last day of the accounting period, and a cash flow statement; s. 154(1) — the balance sheet gives a true and fair view of the state of affairs of the company as at the end of its accounting period; s. 154(2) — a company''s balance sheet, profit and loss account and cash flow statement comply with the requirements specified in regulations prescribed by the Minister, or the National Board of Accountants and Auditors, having regard to generally accepted principles of accounting. The National Board of Accountants and Auditors, the standard-setting body the Auditors and Accountants (Registration) Act (Cap. 286) entrusts, adopted the IFRS for SMEs Accounting Standard with effect from 2010 and, by its 2018 technical pronouncement, requires a commercial enterprise that is not a public-interest entity with an annual turnover of TZS 800,000,000 or more and total assets of TZS 400,000,000 or more to report under it; the lines below follow the statement of financial position that Standard sets out at section 4. This pack does not carry a cash flow statement or a statement of changes in equity: `statements.json` knows a `balance_sheet` and an `income_statement`, and no third kind of statement.', 'companies-act-2002')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('TZ-NBAA-IS', '1', null, 'Revenue', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '2', null, 'Other income', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '3', null, 'Purchases and changes in inventories', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '4', null, 'Employee benefits expense', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '5', null, 'Depreciation and amortisation', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '6', null, 'Other operating expenses', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '7', null, 'Finance costs', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '8', null, 'Profit before tax', '{}'::jsonb, 80, 1, true, array['1', '2']::text[], array['3', '4', '5', '6', '7']::text[], null, null, null),
  ('TZ-NBAA-IS', '9', null, 'Income tax expense', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-IS', '10', null, 'Profit for the year', '{}'::jsonb, 100, 1, true, array['8']::text[], array['9']::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA', null, 'Current assets', '{}'::jsonb, 10, 1, true, array['CA.1', 'CA.2', 'CA.3', 'CA.4', 'CA.5', 'CA.6']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA.1', null, 'Cash and cash equivalents', '{}'::jsonb, 11, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA.2', null, 'Trade and other receivables', '{}'::jsonb, 12, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA.3', null, 'Inventories', '{}'::jsonb, 13, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA.4', null, 'Financial assets', '{}'::jsonb, 14, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA.5', null, 'Current tax recoverable', '{}'::jsonb, 15, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CA.6', null, 'Prepayments and accrued income', '{}'::jsonb, 16, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA', null, 'Non-current assets', '{}'::jsonb, 20, 1, true, array['NCA.1', 'NCA.2', 'NCA.3', 'NCA.4', 'NCA.5', 'NCA.6', 'NCA.7']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.1', null, 'Property, plant and equipment', '{}'::jsonb, 21, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.2', null, 'Investment property', '{}'::jsonb, 22, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.3', null, 'Intangible assets', '{}'::jsonb, 23, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.4', null, 'Investments in associates', '{}'::jsonb, 24, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.5', null, 'Investments in joint ventures', '{}'::jsonb, 25, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.6', null, 'Financial assets', '{}'::jsonb, 26, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCA.7', null, 'Deferred tax assets', '{}'::jsonb, 27, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'TA', null, 'Total assets', '{}'::jsonb, 30, 1, true, array['CA', 'NCA']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CL', null, 'Current liabilities', '{}'::jsonb, 40, 1, true, array['CL.1', 'CL.2', 'CL.3', 'CL.4', 'CL.5']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CL.1', null, 'Trade and other payables', '{}'::jsonb, 41, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CL.2', null, 'Borrowings and other financial liabilities', '{}'::jsonb, 42, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CL.3', null, 'Amounts due to directors', '{}'::jsonb, 43, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CL.4', null, 'Current tax payable', '{}'::jsonb, 44, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'CL.5', null, 'Provisions', '{}'::jsonb, 45, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCL', null, 'Non-current liabilities', '{}'::jsonb, 50, 1, true, array['NCL.1', 'NCL.2', 'NCL.3']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCL.1', null, 'Borrowings and other financial liabilities', '{}'::jsonb, 51, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCL.2', null, 'Deferred tax liabilities', '{}'::jsonb, 52, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NCL.3', null, 'Provisions', '{}'::jsonb, 53, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'TL', null, 'Total liabilities', '{}'::jsonb, 60, 1, true, array['CL', 'NCL']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'NA', null, 'Net assets', '{}'::jsonb, 70, 1, true, array['TA']::text[], array['TL']::text[], null, null, null),
  ('TZ-NBAA-SFP', 'EQ', null, 'Equity', '{}'::jsonb, 80, 1, true, array['EQ.1', 'EQ.2', 'EQ.3']::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'EQ.1', null, 'Share capital', '{}'::jsonb, 81, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'EQ.2', null, 'Other reserves', '{}'::jsonb, 82, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TZ-NBAA-SFP', 'EQ.3', null, 'Retained earnings', '{}'::jsonb, 83, -1, false, '{}'::text[], '{}'::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('TZ-NBAA-IS', '1', 10, 'code_range', '4000', '4030', null, 'any'),
    ('TZ-NBAA-IS', '2', 10, 'code_range', '4500', '4790', null, 'any'),
    ('TZ-NBAA-IS', '3', 10, 'code_range', '5000', '5100', null, 'any'),
    ('TZ-NBAA-IS', '4', 10, 'code_range', '6000', '6080', null, 'any'),
    ('TZ-NBAA-IS', '5', 10, 'code_range', '6200', '6220', null, 'any'),
    ('TZ-NBAA-IS', '6', 10, 'code_range', '6300', '6990', null, 'any'),
    ('TZ-NBAA-IS', '7', 10, 'code_range', '7000', '7030', null, 'any'),
    ('TZ-NBAA-IS', '9', 10, 'code_range', '8000', '8020', null, 'any'),
    ('TZ-NBAA-SFP', 'CA.1', 10, 'code_range', '1000', '1040', null, 'any'),
    ('TZ-NBAA-SFP', 'CA.2', 10, 'code_range', '1100', '1160', null, 'any'),
    ('TZ-NBAA-SFP', 'CA.3', 10, 'code_range', '1200', '1230', null, 'any'),
    ('TZ-NBAA-SFP', 'CA.4', 10, 'account_code', '1300', null, null, 'any'),
    ('TZ-NBAA-SFP', 'CA.5', 10, 'account_code', '1350', null, null, 'any'),
    ('TZ-NBAA-SFP', 'CA.6', 10, 'code_range', '1400', '1410', null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.1', 10, 'code_range', '1600', '1671', null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.2', 10, 'account_code', '1700', null, null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.3', 10, 'code_range', '1750', '1760', null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.4', 10, 'account_code', '1800', null, null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.5', 10, 'account_code', '1810', null, null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.6', 10, 'code_range', '1830', '1840', null, 'any'),
    ('TZ-NBAA-SFP', 'NCA.7', 10, 'account_code', '1900', null, null, 'any'),
    ('TZ-NBAA-SFP', 'CL.1', 10, 'code_range', '2000', '2190', null, 'any'),
    ('TZ-NBAA-SFP', 'CL.1', 20, 'account_code', '2990', null, null, 'credit'),
    ('TZ-NBAA-SFP', 'CL.2', 10, 'code_range', '2200', '2240', null, 'any'),
    ('TZ-NBAA-SFP', 'CL.3', 10, 'account_code', '2250', null, null, 'any'),
    ('TZ-NBAA-SFP', 'CL.4', 10, 'account_code', '2300', null, null, 'any'),
    ('TZ-NBAA-SFP', 'CL.5', 10, 'code_range', '2350', '2360', null, 'any'),
    ('TZ-NBAA-SFP', 'NCL.1', 10, 'code_range', '2400', '2430', null, 'any'),
    ('TZ-NBAA-SFP', 'NCL.2', 10, 'account_code', '2500', null, null, 'any'),
    ('TZ-NBAA-SFP', 'NCL.3', 10, 'account_code', '2550', null, null, 'any'),
    ('TZ-NBAA-SFP', 'EQ.1', 10, 'code_range', '3000', '3010', null, 'any'),
    ('TZ-NBAA-SFP', 'EQ.2', 10, 'code_range', '3100', '3110', null, 'any'),
    ('TZ-NBAA-SFP', 'EQ.3', 10, 'code_range', '3200', '3210', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('TZ', 'Tanzania', '{}'::jsonb, array['en']::text[], 'TZS', '1100', '2000', '2990', '6990', '3200', '4000', '5000', '1010', '1000', 'SAL', 'PUR', 'GEN', 'en', 'retained_earnings', null, null, null, 'OPN', 'half_up', default, '4700', '6950', '4750', '6960', null, null, '2110', '1155', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Value Added Tax Act, s. 86(1) — a registered person making a taxable supply issues, no later than the day value added tax becomes payable on it, a serially numbered true and correct tax invoice generated by an electronic fiscal device; the section asks that each invoice be identified in sequence by the device, and not that a company''s own document series carry no gap, which is why the style is `sequential`.',
  numbering_source_key          = 'vat-act',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'earliest_of_delivery_or_payment',
  tax_point_legal_reference     = 'Value Added Tax Act, s. 15 — value added tax imposed on a taxable supply becomes payable at the EARLIEST of: (a) the time the invoice for the supply is issued by the supplier; (b) the time the consideration is received, in whole or in part; or (c) the time of supply. This is a three-way earliest-of test, and Ekwo''s closed vocabulary expresses only a two-way one; `earliest_of_delivery_or_payment` is the nearer of the two derogation values, matching branches (b) and (c) of section 15. The gap — an invoice issued ahead of both delivery and payment, which fixes the tax point in Tanzania under branch (a) but which this value does not itself read — is recorded in docs/international.md, the same reading Bosnia and Herzegovina''s three-way test under article 17(1) was given.',
  tax_point_source_key          = 'vat-act',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'No Tanzanian statute obliges a business to exchange a structured electronic invoice with another business, or to accept one, in the sense Ekwo''s vocabulary gives the word — there is no Tanzanian Peppol authority, no published profile and no ISO 6523 scheme a party is addressed by, so `profile`, `party_scheme` and `vat_scheme` are all null and `obligation` is `none`. What Tanzania has instead is a clearance system built into the tax invoice itself: Value Added Tax Act, s. 86(1) requires a registered person to issue, no later than the day the tax becomes payable, a serially numbered true and correct tax invoice generated by an electronic fiscal device (EFD) or, since 2020, its software equivalent, a virtual fiscal device (VFD); the device or the VFD channel reports the transaction to the Tanzania Revenue Authority''s Electronic Fiscal Device Management System in real time. This validates an invoice already addressed to a Tanzanian buyer through the seller''s own device, and is not a peer-to-peer exchange of a structured document between two businesses in the sense `einvoicing.profile` describes; the gap is recorded in docs/international.md and in this pack''s README, and the socle is not patched to fit it.',
  einvoice_source_key           = 'vat-act',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'TZ';
