-- Ekwo OS — Հայաստան: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/am at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build am`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Հայաստանի Հանրապետության հարկային օրենսգիրք (ՀՕ-165-Ն, 04.10.2016), պաշտոնական ինկորպորացիա — հոդվածներ 56, 60, 63-76 (ԱԱՀ), 254-258 (շրջանառության հարկ) (ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am)
--     https://www.arlis.am/hy/acts/199704
--   Tax Code of the Republic of Armenia (HO-165-N of 4 October 2016), English translation — Articles 56, 60, 63-76 (VAT), 254-258 (turnover tax) (Armenian Legal Information System (ARLIS) — arlis.am)
--     https://www.arlis.am/en/acts/205620
--   ՀՀ կառավարությանն առընթեր պետական եկամուտների կոմիտեի նախագահի 2016 թվականի դեկտեմբերի 30-ի N 298-Ն հրաման — Ավելացված արժեքի հարկի և ակցիզային հարկի միասնական հաշվարկի ձևը և դրա լրացման կարգը (ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am)
--     https://www.arlis.am/hy/acts/136996
--   ՀՀ ֆինանսների նախարարի 2012 թվականի ապրիլի 17-ի թիվ 353-Ն հրաման — Կազմակերպությունների ֆինանսատնտեսական գործունեության հաշվապահական հաշվառման հաշվային պլանը և դրա կիրառման հրահանգը (ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am)
--     https://www.arlis.am/hy/acts/75961
--   ՀՀ ֆինանսների նախարարի 2012 թվականի նոյեմբերի 21-ի թիվ 1016-Ն հրաման — Փոքր և միջին կազմակերպությունների ֆինանսատնտեսական գործունեության հաշվապահական հաշվառման հաշվային պլանը և դրա կիրառման հրահանգը (ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am)
--     https://www.arlis.am/hy/acts/79913
--   ՀՀ օրենքը հաշվապահական հաշվառման մասին (ընդունված 04.12.2019) (ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am)
--     https://www.arlis.am/hy/acts/208618
--   Առցանց ներկայացման համակարգ (File Online) — ԱԱՀ-ի և ակցիզային հարկի միասնական հաշվարկի և էլեկտրոնային հաշվարկային փաստաթղթերի ներկայացում (ՀՀ պետական եկամուտների կոմիտե (State Revenue Committee))
--     https://file-online.taxservice.am/
--   ՀՀ պետական եկամուտների կոմիտե — պաշտոնական կայք (ՀՀ պետական եկամուտների կոմիտե (State Revenue Committee) — src.am)
--     https://www.src.am/en
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('AM', 'Հայաստան', '0.1.0', date '2026-10-09', '20260929141500', 'community', null, null, '03e466c985a1273c3fcf6773aae6e6656dbe6b9e90c7eb409799ce4c2e8a4484', '[{"key":"tax-code","title":"Հայաստանի Հանրապետության հարկային օրենսգիրք (ՀՕ-165-Ն, 04.10.2016), պաշտոնական ինկորպորացիա — հոդվածներ 56, 60, 63-76 (ԱԱՀ), 254-258 (շրջանառության հարկ)","publisher":"ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am","url":"https://www.arlis.am/hy/acts/199704","consulted_on":"2026-10-09","kind":"law"},{"key":"tax-code-en","title":"Tax Code of the Republic of Armenia (HO-165-N of 4 October 2016), English translation — Articles 56, 60, 63-76 (VAT), 254-258 (turnover tax)","publisher":"Armenian Legal Information System (ARLIS) — arlis.am","url":"https://www.arlis.am/en/acts/205620","consulted_on":"2026-10-09","kind":"law"},{"key":"vat-return-form","title":"ՀՀ կառավարությանն առընթեր պետական եկամուտների կոմիտեի նախագահի 2016 թվականի դեկտեմբերի 30-ի N 298-Ն հրաման — Ավելացված արժեքի հարկի և ակցիզային հարկի միասնական հաշվարկի ձևը և դրա լրացման կարգը","publisher":"ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am","url":"https://www.arlis.am/hy/acts/136996","consulted_on":"2026-10-09","kind":"form"},{"key":"chart-order","title":"ՀՀ ֆինանսների նախարարի 2012 թվականի ապրիլի 17-ի թիվ 353-Ն հրաման — Կազմակերպությունների ֆինանսատնտեսական գործունեության հաշվապահական հաշվառման հաշվային պլանը և դրա կիրառման հրահանգը","publisher":"ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am","url":"https://www.arlis.am/hy/acts/75961","consulted_on":"2026-10-09","kind":"regulation"},{"key":"chart-sme-order","title":"ՀՀ ֆինանսների նախարարի 2012 թվականի նոյեմբերի 21-ի թիվ 1016-Ն հրաման — Փոքր և միջին կազմակերպությունների ֆինանսատնտեսական գործունեության հաշվապահական հաշվառման հաշվային պլանը և դրա կիրառման հրահանգը","publisher":"ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am","url":"https://www.arlis.am/hy/acts/79913","consulted_on":"2026-10-09","kind":"regulation"},{"key":"accounting-law","title":"ՀՀ օրենքը հաշվապահական հաշվառման մասին (ընդունված 04.12.2019)","publisher":"ՀՀ իրավական տեղեկատվական համակարգ (ARLIS) — arlis.am","url":"https://www.arlis.am/hy/acts/208618","consulted_on":"2026-10-09","kind":"law"},{"key":"filing-portal","title":"Առցանց ներկայացման համակարգ (File Online) — ԱԱՀ-ի և ակցիզային հարկի միասնական հաշվարկի և էլեկտրոնային հաշվարկային փաստաթղթերի ներկայացում","publisher":"ՀՀ պետական եկամուտների կոմիտե (State Revenue Committee)","url":"https://file-online.taxservice.am/","consulted_on":"2026-10-09","kind":"portal"},{"key":"src-portal","title":"ՀՀ պետական եկամուտների կոմիտե — պաշտոնական կայք","publisher":"ՀՀ պետական եկամուտների կոմիտե (State Revenue Committee) — src.am","url":"https://www.src.am/en","consulted_on":"2026-10-09","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('AM', 'default', 'Կազմակերպությունների հաշվապահական հաշվառման հաշվային պլան (ՖՀՄՍ-ներին համապատասխան)', '{"en":"Chart of accounts of organisations (Order No. 353-N, IFRS-aligned, exemplary)"}'::jsonb, true, 'companies', array['AM-BS', 'AM-IS']::text[], null, 'ՀՀ ֆինանսների նախարարի 2012 թվականի ապրիլի 17-ի թիվ 353-Ն հրաման — հաշվային պլանը օրինակելի է և պարտադիր բնույթ չունի (հրահանգի I բաժին); փոքր և միջին կազմակերպությունների համար գործում է առանձին հաշվային պլան՝ 2012 թվականի նոյեմբերի 21-ի թիվ 1016-Ն հրաման, որը չի ներառված այս փաթեթում (տե՛ս README.md)։', 'chart-order')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('AM', 'default', '111', 'Մաշվող հիմնական միջոցներ', '{"en":"Depreciable fixed assets"}'::jsonb, 'asset_fixed', false, null, 10),
  ('AM', 'default', '1111', 'Շենքեր', '{"en":"Buildings"}'::jsonb, 'asset_fixed', false, '111', 20),
  ('AM', 'default', '1112', 'Կառուցվածքներ', '{"en":"Structures"}'::jsonb, 'asset_fixed', false, '111', 30),
  ('AM', 'default', '1114', 'Մեքենաներ և սարքավորումներ', '{"en":"Machinery and equipment"}'::jsonb, 'asset_fixed', false, '111', 40),
  ('AM', 'default', '1115', 'Տրանսպորտային միջոցներ', '{"en":"Vehicles"}'::jsonb, 'asset_fixed', false, '111', 50),
  ('AM', 'default', '1116', 'Արտադրական գույք, տնտեսական գույք, գործիքներ', '{"en":"Production and household equipment, tools"}'::jsonb, 'asset_fixed', false, '111', 60),
  ('AM', 'default', '1119', 'Այլ հիմնական միջոցներ', '{"en":"Other fixed assets"}'::jsonb, 'asset_fixed', false, '111', 70),
  ('AM', 'default', '112', 'Հիմնական միջոցների մաշվածություն', '{"en":"Accumulated depreciation of fixed assets"}'::jsonb, 'asset_fixed', false, null, 80),
  ('AM', 'default', '1121', 'Շենքերի մաշվածություն', '{"en":"Accumulated depreciation of buildings"}'::jsonb, 'asset_fixed', false, '112', 90),
  ('AM', 'default', '1122', 'Կառուցվածքների մաշվածություն', '{"en":"Accumulated depreciation of structures"}'::jsonb, 'asset_fixed', false, '112', 100),
  ('AM', 'default', '1124', 'Մեքենաների և սարքավորումների մաշվածություն', '{"en":"Accumulated depreciation of machinery and equipment"}'::jsonb, 'asset_fixed', false, '112', 110),
  ('AM', 'default', '1125', 'Տրանսպորտային միջոցների մաշվածություն', '{"en":"Accumulated depreciation of vehicles"}'::jsonb, 'asset_fixed', false, '112', 120),
  ('AM', 'default', '1126', 'Արտադրական գույքի, տնտեսական գույքի, գործիքների մաշվածություն', '{"en":"Accumulated depreciation of production and household equipment, tools"}'::jsonb, 'asset_fixed', false, '112', 130),
  ('AM', 'default', '1129', 'Այլ հիմնական միջոցների մաշվածություն', '{"en":"Accumulated depreciation of other fixed assets"}'::jsonb, 'asset_fixed', false, '112', 140),
  ('AM', 'default', '115', 'Հողամասեր', '{"en":"Land"}'::jsonb, 'asset_fixed', false, null, 150),
  ('AM', 'default', '116', 'Կենսաբանական ակտիվներ', '{"en":"Biological assets"}'::jsonb, 'asset_fixed', false, null, 160),
  ('AM', 'default', '118', 'Օգտագործման համար ոչ մատչելի հիմնական միջոցներ', '{"en":"Fixed assets not yet available for use"}'::jsonb, 'asset_fixed', false, null, 170),
  ('AM', 'default', '119', 'Ֆինանսական վարձակալությամբ ստացված հիմնական միջոցներ', '{"en":"Fixed assets acquired under finance leases"}'::jsonb, 'asset_fixed', false, null, 180),
  ('AM', 'default', '121', 'Ֆինանսական վարձակալությամբ ստացված հիմնական միջոցների մաշվածություն', '{"en":"Accumulated depreciation of fixed assets acquired under finance leases"}'::jsonb, 'asset_fixed', false, null, 190),
  ('AM', 'default', '122', 'Ներդրումային գույք', '{"en":"Investment property"}'::jsonb, 'asset_fixed', false, null, 200),
  ('AM', 'default', '123', 'Սկզբնական արժեքով հաշվառվող ներդրումային գույքի մաշվածություն', '{"en":"Accumulated depreciation of investment property at cost"}'::jsonb, 'asset_fixed', false, null, 210),
  ('AM', 'default', '124', 'Ոչ ընթացիկ նյութական ակտիվների արժեզրկում', '{"en":"Impairment of non-current tangible assets"}'::jsonb, 'asset_fixed', false, null, 220),
  ('AM', 'default', '131', 'Ոչ նյութական ակտիվներ', '{"en":"Intangible assets"}'::jsonb, 'asset_fixed', false, null, 230),
  ('AM', 'default', '132', 'Ոչ նյութական ակտիվների ամորտիզացիա', '{"en":"Accumulated amortisation of intangible assets"}'::jsonb, 'asset_fixed', false, null, 240),
  ('AM', 'default', '133', 'Անավարտ ոչ նյութական ակտիվներ', '{"en":"Intangible assets under development"}'::jsonb, 'asset_fixed', false, null, 250),
  ('AM', 'default', '134', 'Գուդվիլ', '{"en":"Goodwill"}'::jsonb, 'asset_fixed', false, null, 260),
  ('AM', 'default', '136', 'Ոչ նյութական ակտիվների արժեզրկում', '{"en":"Impairment of intangible assets"}'::jsonb, 'asset_fixed', false, null, 270),
  ('AM', 'default', '141', 'Սկզբնական արժեքով հաշվառվող ոչ ընթացիկ ներդրումներ չկապակցված կազմակերպություններում', '{"en":"Non-current investments at cost, not related parties"}'::jsonb, 'asset_non_current', false, null, 280),
  ('AM', 'default', '142', 'Սկզբնական արժեքով հաշվառվող ոչ ընթացիկ ներդրումներ կապակցված կազմակերպությունների կանոնադրական կապիտալում', '{"en":"Non-current investments at cost, related parties"}'::jsonb, 'asset_non_current', false, null, 290),
  ('AM', 'default', '143', 'Իրական արժեքով չափվող ոչ ընթացիկ ֆինանսական ակտիվներ', '{"en":"Non-current financial assets at fair value"}'::jsonb, 'asset_non_current', false, null, 300),
  ('AM', 'default', '145', 'Երկարաժամկետ փոխառությունների գծով ստացվելիք համախառն մուտքեր', '{"en":"Gross receipts from long-term loans receivable"}'::jsonb, 'asset_non_current', false, null, 310),
  ('AM', 'default', '149', 'Ոչ ընթացիկ ֆինանսական ակտիվների արժեզրկում (անհավաքագրելիություն)', '{"en":"Impairment (uncollectibility) of non-current financial assets"}'::jsonb, 'asset_non_current', false, null, 320),
  ('AM', 'default', '151', 'Հետաձգված հարկային ակտիվներ', '{"en":"Deferred tax assets"}'::jsonb, 'asset_non_current', false, null, 330),
  ('AM', 'default', '152', 'Կանխավճարներ ոչ ընթացիկ ակտիվներ ձեռք բերելու համար', '{"en":"Advances for acquiring non-current assets"}'::jsonb, 'asset_non_current', false, null, 340),
  ('AM', 'default', '211', 'Նյութեր', '{"en":"Materials"}'::jsonb, 'asset_current', false, null, 350),
  ('AM', 'default', '2111', 'Հումք և նյութեր', '{"en":"Raw materials and supplies"}'::jsonb, 'asset_current', false, '211', 360),
  ('AM', 'default', '2113', 'Վառելիք', '{"en":"Fuel"}'::jsonb, 'asset_current', false, '211', 370),
  ('AM', 'default', '2115', 'Պահեստամասեր', '{"en":"Spare parts"}'::jsonb, 'asset_current', false, '211', 380),
  ('AM', 'default', '2119', 'Այլ նյութեր', '{"en":"Other materials"}'::jsonb, 'asset_current', false, '211', 390),
  ('AM', 'default', '214', 'Անավարտ արտադրություն', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, null, 400),
  ('AM', 'default', '215', 'Արտադրանք', '{"en":"Finished products"}'::jsonb, 'asset_current', false, null, 410),
  ('AM', 'default', '216', 'Ապրանքներ', '{"en":"Goods"}'::jsonb, 'asset_current', false, null, 420),
  ('AM', 'default', '2161', 'Ապրանքներ պահեստում', '{"en":"Goods in warehouse"}'::jsonb, 'asset_current', false, '216', 430),
  ('AM', 'default', '2162', 'Ապրանքներ մանրածախ առևտրում', '{"en":"Goods in retail trade"}'::jsonb, 'asset_current', false, '216', 440),
  ('AM', 'default', '218', 'Պաշարների արժեքի նվազում', '{"en":"Inventory write-down"}'::jsonb, 'asset_current', false, null, 450),
  ('AM', 'default', '221', 'Դեբիտորական պարտքեր վաճառքների գծով', '{"en":"Trade receivables (sales)"}'::jsonb, 'asset_receivable', true, null, 460),
  ('AM', 'default', '222', 'Դեբիտորական պարտքեր այլ եկամուտների գծով', '{"en":"Receivables on other income"}'::jsonb, 'asset_current', false, null, 470),
  ('AM', 'default', '223', 'Դեբիտորական պարտքերի հնարավոր կորուստների պահուստ', '{"en":"Allowance for expected credit losses on receivables"}'::jsonb, 'asset_current', false, null, 480),
  ('AM', 'default', '224', 'Տրված ընթացիկ կանխավճարներ', '{"en":"Advances paid (current)"}'::jsonb, 'asset_prepayments', false, null, 490),
  ('AM', 'default', '225', 'Դեբիտորական պարտքեր հարկերի և այլ պարտադիր վճարների գծով', '{"en":"Receivables on taxes and other mandatory payments"}'::jsonb, 'asset_current', false, null, 500),
  ('AM', 'default', '2251', 'Դեբիտորական պարտքեր շահութահարկի գծով', '{"en":"Corporate income tax receivable"}'::jsonb, 'asset_current', false, '225', 510),
  ('AM', 'default', '2252', 'Դեբիտորական պարտքեր եկամտահարկի գծով', '{"en":"Income tax receivable"}'::jsonb, 'asset_current', false, '225', 520),
  ('AM', 'default', '2253', 'Դեբիտորական պարտքեր ավելացված արժեքի հարկի գծով', '{"en":"VAT receivable (settlement with the budget)"}'::jsonb, 'asset_current', true, '225', 530),
  ('AM', 'default', '2255', 'Դեբիտորական պարտքեր գույքահարկի գծով', '{"en":"Property tax receivable"}'::jsonb, 'asset_current', false, '225', 540),
  ('AM', 'default', '226', 'Հաշվանցման (փոխհատուցման) ենթակա անուղղակի հարկեր', '{"en":"Indirect taxes subject to offset (recovery)"}'::jsonb, 'asset_current', false, null, 550),
  ('AM', 'default', '2261', 'Հաշվանցման ենթակա ԱԱՀ՝ Հայաստանի տարածքում ձեռք բերված ապրանքների, աշխատանքների և ծառայությունների գծով', '{"en":"Input VAT on goods, works and services acquired in Armenia"}'::jsonb, 'asset_current', false, '226', 560),
  ('AM', 'default', '2262', 'Հաշվանցման ենթակա ԱԱՀ՝ ներմուծված ապրանքների գծով', '{"en":"Input VAT on imported goods"}'::jsonb, 'asset_current', false, '226', 570),
  ('AM', 'default', '227', 'Դեբիտորական պարտքեր պարտադիր սոցիալական ապահովության գծով', '{"en":"Receivables on mandatory social security"}'::jsonb, 'asset_current', false, null, 580),
  ('AM', 'default', '228', 'Դեբիտորական պարտքեր առհաշիվ տրված գումարների գծով', '{"en":"Amounts advanced on account (imprest)"}'::jsonb, 'asset_current', false, null, 590),
  ('AM', 'default', '2283', 'Առհաշիվ տրված գումարներ գործուղումների համար', '{"en":"Imprest for business trips"}'::jsonb, 'asset_current', false, '228', 600),
  ('AM', 'default', '229', 'Այլ դեբիտորական պարտքեր', '{"en":"Other receivables"}'::jsonb, 'asset_current', false, null, 610),
  ('AM', 'default', '231', 'Իրական արժեքով՝ շահույթի կամ վնասի միջոցով չափվող ընթացիկ ֆինանսական ակտիվներ', '{"en":"Current financial assets at fair value through profit or loss"}'::jsonb, 'asset_current', false, null, 620),
  ('AM', 'default', '232', 'Վաճառքի համար մատչելի ընթացիկ ֆինանսական ակտիվներ', '{"en":"Current financial assets available for sale"}'::jsonb, 'asset_current', false, null, 630),
  ('AM', 'default', '235', 'Կարճաժամկետ փոխառությունների գծով ստացվելիք համախառն մուտքեր', '{"en":"Gross receipts from short-term loans receivable"}'::jsonb, 'asset_current', false, null, 640),
  ('AM', 'default', '241', 'Ընթացիկ ֆինանսական ներդրումների արժեզրկում (անհավաքագրելիություն)', '{"en":"Impairment (uncollectibility) of current financial investments"}'::jsonb, 'asset_current', false, null, 650),
  ('AM', 'default', '251', 'Դրամարկղ', '{"en":"Cash on hand"}'::jsonb, 'asset_cash', false, null, 660),
  ('AM', 'default', '2511', 'Ազգային արժույթի դրամարկղ', '{"en":"Cash on hand in national currency"}'::jsonb, 'asset_cash', false, '251', 670),
  ('AM', 'default', '2512', 'Արտարժույթի դրամարկղ', '{"en":"Cash on hand in foreign currency"}'::jsonb, 'asset_cash', false, '251', 680),
  ('AM', 'default', '252', 'Հաշվարկային հաշիվ', '{"en":"Settlement account"}'::jsonb, 'asset_cash', false, null, 690),
  ('AM', 'default', '2521', 'Հաշվարկային հաշիվ', '{"en":"Settlement account in national currency"}'::jsonb, 'asset_cash', false, '252', 700),
  ('AM', 'default', '253', 'Արտարժութային հաշիվ', '{"en":"Foreign currency account"}'::jsonb, 'asset_cash', false, null, 710),
  ('AM', 'default', '2531', 'Արտարժութային հաշիվ երկրի ներսում', '{"en":"Foreign currency account in Armenia"}'::jsonb, 'asset_cash', false, '253', 720),
  ('AM', 'default', '2532', 'Արտարժութային հաշիվ արտերկրում', '{"en":"Foreign currency account abroad"}'::jsonb, 'asset_cash', false, '253', 730),
  ('AM', 'default', '254', 'Այլ հաշիվներ բանկերում', '{"en":"Other accounts in banks"}'::jsonb, 'asset_cash', false, null, 740),
  ('AM', 'default', '255', 'Դրամական միջոցներ ճանապարհին', '{"en":"Cash in transit"}'::jsonb, 'asset_cash', false, null, 750),
  ('AM', 'default', '256', 'Դրամական փաստաթղթեր', '{"en":"Cash documents"}'::jsonb, 'asset_cash', false, null, 760),
  ('AM', 'default', '311', 'Կանոնադրական կապիտալ', '{"en":"Share (charter) capital"}'::jsonb, 'equity', false, null, 770),
  ('AM', 'default', '312', 'Չվճարված կապիտալ', '{"en":"Unpaid capital"}'::jsonb, 'equity', false, null, 780),
  ('AM', 'default', '313', 'Հետ գնված կապիտալ', '{"en":"Repurchased capital"}'::jsonb, 'equity', false, null, 790),
  ('AM', 'default', '314', 'Էմիսիոն եկամուտ', '{"en":"Share premium"}'::jsonb, 'equity', false, null, 800),
  ('AM', 'default', '321', 'Հիմնական միջոցների և ոչ նյութական ակտիվների վերագնահատումից արժեքի աճ', '{"en":"Revaluation surplus on fixed and intangible assets"}'::jsonb, 'equity', false, null, 810),
  ('AM', 'default', '331', 'Շահույթ կամ վնաս', '{"en":"Profit or loss (closing account)"}'::jsonb, 'equity', false, null, 820),
  ('AM', 'default', '341', 'Նախորդ տարիների ֆինանսական արդյունքների ճշգրտում', '{"en":"Adjustment of prior-year financial results"}'::jsonb, 'equity_retained', false, null, 830),
  ('AM', 'default', '342', 'Նախորդ տարիների չբաշխված շահույթ (չծածկված վնաս)', '{"en":"Retained earnings (uncovered loss) of prior years"}'::jsonb, 'equity_retained', false, null, 840),
  ('AM', 'default', '343', 'Հաշվետու տարվա զուտ շահույթ (վնաս)', '{"en":"Net profit (loss) of the reporting year"}'::jsonb, 'equity_retained', false, null, 850),
  ('AM', 'default', '344', 'Միջանկյալ շահաբաժիններ', '{"en":"Interim dividends"}'::jsonb, 'equity', false, null, 860),
  ('AM', 'default', '351', 'Պահուստային կապիտալ', '{"en":"Reserve capital"}'::jsonb, 'equity', false, null, 870),
  ('AM', 'default', '411', 'Երկարաժամկետ վարկերի գծով վճարվելիք համախառն գումարներ', '{"en":"Gross amounts payable on long-term loans"}'::jsonb, 'liability_non_current', false, null, 880),
  ('AM', 'default', '412', 'Երկարաժամկետ փոխառությունների գծով վճարվելիք համախառն գումարներ', '{"en":"Gross amounts payable on long-term borrowings"}'::jsonb, 'liability_non_current', false, null, 890),
  ('AM', 'default', '413', 'Ֆինանսական վարձակալության գծով վճարվելիք համախառն գումարներ', '{"en":"Gross amounts payable on finance leases"}'::jsonb, 'liability_non_current', false, null, 900),
  ('AM', 'default', '421', 'Ակտիվներին վերաբերող շնորհներ', '{"en":"Grants related to assets"}'::jsonb, 'liability_non_current', false, null, 910),
  ('AM', 'default', '422', 'Հետաձգված հարկային պարտավորություններ', '{"en":"Deferred tax liabilities"}'::jsonb, 'liability_non_current', false, null, 920),
  ('AM', 'default', '425', 'Ոչ ընթացիկ պահուստներ', '{"en":"Non-current provisions"}'::jsonb, 'liability_non_current', false, null, 930),
  ('AM', 'default', '429', 'Այլ ոչ ընթացիկ պարտավորություններ', '{"en":"Other non-current liabilities"}'::jsonb, 'liability_non_current', false, null, 940),
  ('AM', 'default', '511', 'Կարճաժամկետ վարկերի գծով վճարվելիք համախառն գումարներ', '{"en":"Gross amounts payable on short-term loans"}'::jsonb, 'liability_current', false, null, 950),
  ('AM', 'default', '512', 'Երկարաժամկետ վարկերի գծով վճարվելիք համախառն գումարների կարճաժամկետ մաս', '{"en":"Current portion of long-term loans"}'::jsonb, 'liability_current', false, null, 960),
  ('AM', 'default', '513', 'Կարճաժամկետ փոխառությունների գծով վճարվելիք համախառն գումարներ', '{"en":"Gross amounts payable on short-term borrowings"}'::jsonb, 'liability_current', false, null, 970),
  ('AM', 'default', '515', 'Ֆինանսական վարձակալության գծով վճարվելիք համախառն գումարների կարճաժամկետ մաս', '{"en":"Current portion of finance lease liabilities"}'::jsonb, 'liability_current', false, null, 980),
  ('AM', 'default', '521', 'Կրեդիտորական պարտքեր գնումների գծով', '{"en":"Trade payables (purchases)"}'::jsonb, 'liability_payable', true, null, 990),
  ('AM', 'default', '523', 'Ստացված կանխավճարներ', '{"en":"Advances received"}'::jsonb, 'liability_current', false, null, 1000),
  ('AM', 'default', '524', 'Պարտքեր հարկերի և այլ պարտադիր վճարների գծով', '{"en":"Payables on taxes and other mandatory payments"}'::jsonb, 'liability_current', false, null, 1010),
  ('AM', 'default', '5241', 'Պարտքեր շահութահարկի գծով', '{"en":"Corporate income tax payable"}'::jsonb, 'liability_current', false, '524', 1020),
  ('AM', 'default', '5242', 'Պարտքեր եկամտահարկի գծով', '{"en":"Income tax payable (withheld)"}'::jsonb, 'liability_current', false, '524', 1030),
  ('AM', 'default', '5243', 'Պարտքեր ավելացված արժեքի հարկի գծով', '{"en":"VAT payable (settlement with the budget)"}'::jsonb, 'liability_current', true, '524', 1040),
  ('AM', 'default', '52431', 'Իրացման գործարքների գծով հաշվարկված ԱԱՀ', '{"en":"Output VAT calculated on supplies"}'::jsonb, 'liability_current', false, '5243', 1050),
  ('AM', 'default', '5244', 'Պարտքեր ակցիզային հարկի գծով', '{"en":"Excise tax payable"}'::jsonb, 'liability_current', false, '524', 1060),
  ('AM', 'default', '5245', 'Պարտքեր գույքահարկի գծով', '{"en":"Property tax payable"}'::jsonb, 'liability_current', false, '524', 1070),
  ('AM', 'default', '5248', 'Պարտքեր հարկերի դիմաց հաշվարկված տույժերի, տուգանքների գծով', '{"en":"Payables on penalties and fines calculated on taxes"}'::jsonb, 'liability_current', false, '524', 1080),
  ('AM', 'default', '5249', 'Պարտքեր այլ պարտադիր վճարների գծով', '{"en":"Payables on other mandatory payments"}'::jsonb, 'liability_current', false, '524', 1090),
  ('AM', 'default', '525', 'Պարտքեր պարտադիր սոցիալական ապահովության գծով', '{"en":"Payables on mandatory social security"}'::jsonb, 'liability_current', false, null, 1100),
  ('AM', 'default', '5251', 'Պարտքեր պարտադիր սոցիալական ապահովության վճարների գծով՝ աշխատակիցների հաշվին', '{"en":"Social security payments at the employees expense"}'::jsonb, 'liability_current', false, '525', 1110),
  ('AM', 'default', '5252', 'Պարտքեր պարտադիր սոցիալական ապահովության վճարների գծով՝ գործատուների հաշվին', '{"en":"Social security payments at the employers expense"}'::jsonb, 'liability_current', false, '525', 1120),
  ('AM', 'default', '527', 'Պարտքեր աշխատավարձի և աշխատակիցների այլ կարճաժամկետ հատուցումների գծով', '{"en":"Payables on wages and other short-term employee benefits"}'::jsonb, 'liability_current', false, null, 1130),
  ('AM', 'default', '5271', 'Պարտքեր աշխատավարձի վճարման գծով', '{"en":"Wages payable"}'::jsonb, 'liability_current', false, '527', 1140),
  ('AM', 'default', '528', 'Պարտքեր աշխատակիցներին այլ գործառնությունների գծով', '{"en":"Payables to employees on other operations"}'::jsonb, 'liability_current', false, null, 1150),
  ('AM', 'default', '529', 'Պարտքեր շահաբաժինների գծով', '{"en":"Dividends payable"}'::jsonb, 'liability_current', false, null, 1160),
  ('AM', 'default', '531', 'Այլ ընթացիկ պարտավորություններ', '{"en":"Other current liabilities"}'::jsonb, 'liability_current', false, null, 1170),
  ('AM', 'default', '5311', 'Պարտքեր գործառնական վարձակալության գծով', '{"en":"Payables on operating leases"}'::jsonb, 'liability_current', false, '531', 1180),
  ('AM', 'default', '5312', 'Պարտքեր տույժերի, տուգանքների գծով', '{"en":"Payables on penalties and fines"}'::jsonb, 'liability_current', false, '531', 1190),
  ('AM', 'default', '5313', 'Պարտքեր ապահովագրավճարների գծով', '{"en":"Payables on insurance premiums"}'::jsonb, 'liability_current', false, '531', 1200),
  ('AM', 'default', '5319', 'Անցումային հաշիվ (ճշտման ենթակա գումարներ)', '{"en":"Suspense account (amounts to be clarified)"}'::jsonb, 'liability_current', false, '531', 1210),
  ('AM', 'default', '541', 'Եկամուտներին վերաբերող շնորհներ', '{"en":"Grants related to income"}'::jsonb, 'liability_current', false, null, 1220),
  ('AM', 'default', '543', 'Ընթացիկ պահուստներ', '{"en":"Current provisions"}'::jsonb, 'liability_current', false, null, 1230),
  ('AM', 'default', '5435', 'Վաստակած արձակուրդայինի գծով պահուստ', '{"en":"Provision for accrued vacation"}'::jsonb, 'liability_current', false, '543', 1240),
  ('AM', 'default', '611', 'Արտադրանքի, ապրանքների, աշխատանքների, ծառայությունների իրացումից հասույթ', '{"en":"Revenue from sales of products, goods, works and services"}'::jsonb, 'income', false, null, 1250),
  ('AM', 'default', '6111', 'Արտադրանքի վաճառքներից հասույթ', '{"en":"Revenue from sales of products"}'::jsonb, 'income', false, '611', 1260),
  ('AM', 'default', '6112', 'Ապրանքների վաճառքներից հասույթ', '{"en":"Revenue from sales of goods"}'::jsonb, 'income', false, '611', 1270),
  ('AM', 'default', '6113', 'Աշխատանքների կատարումից հասույթ', '{"en":"Revenue from works performed"}'::jsonb, 'income', false, '611', 1280),
  ('AM', 'default', '6114', 'Ծառայությունների մատուցումից հասույթ', '{"en":"Revenue from services rendered"}'::jsonb, 'income', false, '611', 1290),
  ('AM', 'default', '612', 'Իրացված արտադրանքի, ապրանքների հետ վերադարձումից հասույթի ճշգրտում', '{"en":"Adjustment of revenue for returned products and goods"}'::jsonb, 'income', false, null, 1300),
  ('AM', 'default', '614', 'Գործառնական այլ եկամուտներ', '{"en":"Other operating income"}'::jsonb, 'income', false, null, 1310),
  ('AM', 'default', '6143', 'Գործառնական վարձակալությունից եկամուտներ', '{"en":"Income from operating leases"}'::jsonb, 'income', false, '614', 1320),
  ('AM', 'default', '6144', 'Եկամուտներ տույժերից, տուգանքներից', '{"en":"Income from penalties and fines"}'::jsonb, 'income', false, '614', 1330),
  ('AM', 'default', '6146', 'Գործառնական այլ եկամուտներ', '{"en":"Other operating income (miscellaneous)"}'::jsonb, 'income', false, '614', 1340),
  ('AM', 'default', '621', 'Ոչ ընթացիկ ակտիվների օտարումից եկամուտներ', '{"en":"Income from disposal of non-current assets"}'::jsonb, 'income_other', false, null, 1350),
  ('AM', 'default', '6211', 'Հիմնական միջոցների օտարումից եկամուտներ', '{"en":"Income from disposal of fixed assets"}'::jsonb, 'income_other', false, '621', 1360),
  ('AM', 'default', '622', 'Ընթացիկ ֆինանսական ակտիվների օտարումից եկամուտներ', '{"en":"Income from disposal of current financial assets"}'::jsonb, 'income_other', false, null, 1370),
  ('AM', 'default', '625', 'Արտարժույթի փոխարժեքային տարբերություններից օգուտներ', '{"en":"Gains from foreign exchange differences"}'::jsonb, 'income_other', false, null, 1380),
  ('AM', 'default', '627', 'Ֆինանսական ներդրումներից եկամուտներ', '{"en":"Income from financial investments"}'::jsonb, 'income_other', false, null, 1390),
  ('AM', 'default', '628', 'Շնորհներից և անհատույց ստացումներից եկամուտներ', '{"en":"Income from grants and gratuitous receipts"}'::jsonb, 'income_other', false, null, 1400),
  ('AM', 'default', '629', 'Այլ եկամուտներ', '{"en":"Other income"}'::jsonb, 'income_other', false, null, 1410),
  ('AM', 'default', '711', 'Իրացված արտադրանքի, ապրանքների, աշխատանքների, ծառայությունների ինքնարժեք', '{"en":"Cost of products, goods, works and services sold"}'::jsonb, 'expense_direct_cost', false, null, 1420),
  ('AM', 'default', '7111', 'Վաճառված արտադրանքի ինքնարժեք', '{"en":"Cost of products sold"}'::jsonb, 'expense_direct_cost', false, '711', 1430),
  ('AM', 'default', '7112', 'Վաճառված ապրանքների ինքնարժեք', '{"en":"Cost of goods sold"}'::jsonb, 'expense_direct_cost', false, '711', 1440),
  ('AM', 'default', '7113', 'Կատարված աշխատանքների ինքնարժեք', '{"en":"Cost of works performed"}'::jsonb, 'expense_direct_cost', false, '711', 1450),
  ('AM', 'default', '7114', 'Մատուցված ծառայությունների ինքնարժեք', '{"en":"Cost of services rendered"}'::jsonb, 'expense_direct_cost', false, '711', 1460),
  ('AM', 'default', '712', 'Իրացման ծախսեր', '{"en":"Selling expenses"}'::jsonb, 'expense', false, null, 1470),
  ('AM', 'default', '7121', 'Աշխատանքի վճարման ծախսեր, սոցիալական ապահովության վճարներ', '{"en":"Selling: labour costs and social security contributions"}'::jsonb, 'expense', false, '712', 1480),
  ('AM', 'default', '7122', 'Հիմնական միջոցների մաշվածության, դրանց նորոգման և սպասարկման գծով ծախսեր', '{"en":"Selling: depreciation, repair and maintenance of fixed assets"}'::jsonb, 'expense', false, '712', 1490),
  ('AM', 'default', '7123', 'Պահեստում գտնվող արտադրանքի, ապրանքների փաթեթավորման, տարայի, տեսակավորման, պահպանման ծախսեր', '{"en":"Selling: packaging, storage and sorting"}'::jsonb, 'expense', false, '712', 1500),
  ('AM', 'default', '7124', 'Արտադրանքի, ապրանքների իրացման տրանսպորտային և ապահովության ծախսեր', '{"en":"Selling: transport and security of goods sold"}'::jsonb, 'expense', false, '712', 1510),
  ('AM', 'default', '7126', 'Մարկետինգի և գովազդի ծախսեր', '{"en":"Marketing and advertising expenses"}'::jsonb, 'expense', false, '712', 1520),
  ('AM', 'default', '7127', 'Իրացման այլ ծախսեր', '{"en":"Other selling expenses"}'::jsonb, 'expense', false, '712', 1530),
  ('AM', 'default', '713', 'Վարչական ծախսեր', '{"en":"Administrative expenses"}'::jsonb, 'expense', false, null, 1540),
  ('AM', 'default', '7131', 'Աշխատանքի վճարման ծախսեր, սոցիալական ապահովության վճարներ', '{"en":"Administrative: labour costs and social security contributions"}'::jsonb, 'expense', false, '713', 1550),
  ('AM', 'default', '7132', 'Հիմնական միջոցների և ոչ նյութական ակտիվների մաշվածության (ամորտիզացիայի), դրանց նորոգման և սպասարկման ծախսեր', '{"en":"Administrative: depreciation, amortisation, repair and maintenance"}'::jsonb, 'expense_depreciation', false, '713', 1560),
  ('AM', 'default', '7133', 'Գործուղման և ներկայացուցչական ծախսեր', '{"en":"Business trip and representation expenses"}'::jsonb, 'expense', false, '713', 1570),
  ('AM', 'default', '7134', 'Փոստի և հեռահաղորդակցության ծախսեր', '{"en":"Postal and telecommunication expenses"}'::jsonb, 'expense', false, '713', 1580),
  ('AM', 'default', '7135', 'Գրասենյակային և կոմունալ ծախսեր', '{"en":"Office and utility expenses"}'::jsonb, 'expense', false, '713', 1590),
  ('AM', 'default', '7136', 'Աուդիտորական և խորհրդատվական ծախսեր', '{"en":"Audit and consulting expenses"}'::jsonb, 'expense', false, '713', 1600),
  ('AM', 'default', '7137', 'Բանկային ծառայությունների ծախսեր, ապահովության ծախսեր', '{"en":"Bank service and security expenses"}'::jsonb, 'expense', false, '713', 1610),
  ('AM', 'default', '7138', 'Չփոխհատուցվող հարկերից ծախսեր', '{"en":"Non-recoverable tax expenses"}'::jsonb, 'expense', false, '713', 1620),
  ('AM', 'default', '7139', 'Վարչական այլ ծախսեր', '{"en":"Other administrative expenses"}'::jsonb, 'expense', false, '713', 1630),
  ('AM', 'default', '714', 'Գործառնական այլ ծախսեր', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, null, 1640),
  ('AM', 'default', '7141', 'Այլ պաշարների օտարումից ծախսեր', '{"en":"Expenses on disposal of other inventories"}'::jsonb, 'expense', false, '714', 1650),
  ('AM', 'default', '7142', 'Պաշարների արժեքի փոփոխությունից ծախսեր, վաճառքների գծով դեբիտորական պարտքերի կորուստների (հնարավոր կորուստների պահուստի) գծով ծախսեր, երաշխիքային սպասարկման և վերանորոգման գծով ծախսեր', '{"en":"Inventory write-downs, credit losses and warranty expenses"}'::jsonb, 'expense', false, '714', 1660),
  ('AM', 'default', '7144', 'Ծախսեր տույժերից, տուգանքներից, դատական ծախսեր', '{"en":"Penalties, fines and court costs"}'::jsonb, 'expense', false, '714', 1670),
  ('AM', 'default', '7146', 'Հետազոտության և մշակման ծախսեր', '{"en":"Research and development expenses"}'::jsonb, 'expense', false, '714', 1680),
  ('AM', 'default', '7148', 'Գործառնական այլ ծախսեր', '{"en":"Other operating expenses (miscellaneous)"}'::jsonb, 'expense', false, '714', 1690),
  ('AM', 'default', '721', 'Ոչ ընթացիկ ակտիվների օտարումից ծախսեր', '{"en":"Expenses on disposal of non-current assets"}'::jsonb, 'expense', false, null, 1700),
  ('AM', 'default', '7211', 'Հիմնական միջոցների օտարումից ծախսեր', '{"en":"Expenses on disposal of fixed assets"}'::jsonb, 'expense', false, '721', 1710),
  ('AM', 'default', '722', 'Ընթացիկ ֆինանսական ակտիվների օտարումից ծախսեր', '{"en":"Expenses on disposal of current financial assets"}'::jsonb, 'expense', false, null, 1720),
  ('AM', 'default', '725', 'Արտարժույթի փոխարժեքային տարբերություններից կորուստներ', '{"en":"Losses from foreign exchange differences"}'::jsonb, 'expense', false, null, 1730),
  ('AM', 'default', '727', 'Ֆինանսական ծախսեր', '{"en":"Finance costs"}'::jsonb, 'expense', false, null, 1740),
  ('AM', 'default', '7271', 'Վարկերի և փոխառությունների գծով տոկոսային ծախսեր՝ հաշվի առած գործարքի հետ կապված ծախսումները', '{"en":"Interest expense on loans and borrowings"}'::jsonb, 'expense', false, '727', 1750),
  ('AM', 'default', '728', 'Անհատույց տրված ակտիվների գծով ծախսեր', '{"en":"Expenses on assets given free of charge"}'::jsonb, 'expense', false, null, 1760),
  ('AM', 'default', '729', 'Այլ ծախսեր', '{"en":"Other expenses"}'::jsonb, 'expense', false, null, 1770),
  ('AM', 'default', '7291', 'Կլորացման տարբերություններ', '{"en":"Rounding differences"}'::jsonb, 'expense', false, '729', 1780),
  ('AM', 'default', '751', 'Շահութահարկի գծով ծախս (եկամուտ)', '{"en":"Income tax expense (income)"}'::jsonb, 'expense', false, null, 1790),
  ('AM', 'default', '911', 'Գործառնական վարձակալությամբ ընդունված հիմնական միջոցներ', '{"en":"Fixed assets accepted under operating leases"}'::jsonb, 'off_balance', false, null, 1800),
  ('AM', 'default', '912', 'Պատասխանատու պահպանման ընդունված ապրանքանյութական արժեքներ', '{"en":"Goods accepted for safekeeping"}'::jsonb, 'off_balance', false, null, 1810),
  ('AM', 'default', '915', 'Կոմիսիայի և կոնսիգնացիայի պայմանագրերով ընդունված ապրանքներ', '{"en":"Goods accepted under commission and consignment contracts"}'::jsonb, 'off_balance', false, null, 1820)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('AM', 'BNK', 'Բանկի ամսագիր', '{"en":"Bank journal"}'::jsonb, 'bank', 30),
  ('AM', 'CSH', 'Դրամարկղի ամսագիր', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('AM', 'GEN', 'Ընդհանուր ամսագիր', '{"en":"General journal"}'::jsonb, 'general', 50),
  ('AM', 'OPN', 'Բացման ամսագիր', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('AM', 'PUR', 'Գնումների ամսագիր', '{"en":"Purchase journal"}'::jsonb, 'purchase', 20),
  ('AM', 'SAL', 'Վաճառքների ամսագիր', '{"en":"Sales journal"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('AM', 'AM-P-20', 'ԱԱՀ 20 % — ձեռքբերում Հայաստանի Հանրապետությունում (գնում)', '{"en":"VAT 20% — acquisition in Armenia (purchase)"}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2018-01-01', null, 'Հարկային օրենսգիրք, հոդված 71, 1-ին մաս, 1-ին կետ — հաշվանցվում (պակասեցվում) են հարկային հաշիվներում առանձնացված ԱԱՀ-ի գումարները՝ ստացողի կողմից էլեկտրոնային ստորագրությամբ հաստատված լինելու պայմանով (հոդված 68)։ Միասնական հաշվարկ, կետ 18 (և կետ 19.1՝ ճշգրտող հարկային հաշիվ)։', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'tax-code', null, null, null, null),
  ('AM', 'AM-P-IMPORT', 'ԱԱՀ 20 % — ապրանքների ներմուծում (գնում)', '{"en":"VAT 20% — import of goods (purchase)"}'::jsonb, null, 'percent', 20, 'purchase', 'import', date '2018-01-01', null, 'Հարկային օրենսգիրք, հոդված 71, 1-ին մաս, 2-րդ և 3-րդ կետեր — «Բաց թողնում՝ ներքին սպառման համար» մաքսային ընթացակարգով ներմուծված ապրանքների և ԵՏՄ անդամ պետություններից ներմուծված ԵՏՄ ապրանքների համար վճարված ԱԱՀ-ի գումարները հաշվանցվում են։ Միասնական հաշվարկ, կետ 17։', null, null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'tax-code', null, null, null, null),
  ('AM', 'AM-S-0-EXPORT', 'ԱԱՀ 0 % — ապրանքի արտահանում (վաճառք)', '{"en":"VAT 0% — export of goods (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2018-01-01', null, 'Հարկային օրենսգիրք, հոդված 65, 2-րդ մաս, 1-ին և 2-րդ կետեր — «Արտահանում» մաքսային ընթացակարգով արտահանված ապրանքի, ինչպես նաև ԵՏՄ անդամ պետություն արտահանված ԵՏՄ ապրանքի մատակարարումը հարկվում է 0 տոկոս դրույքաչափով։ Միասնական հաշվարկ, կետ 12։', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'tax-code', null, null, null, null),
  ('AM', 'AM-S-0-SERVICES', 'ԱԱՀ 0 % — միջազգային փոխադրումներ և Հայաստանից դուրս մատուցվող ծառայություններ (վաճառք)', '{"en":"VAT 0% — international transport and services supplied outside Armenia (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2018-01-01', null, 'Հարկային օրենսգիրք, հոդված 65, 2-րդ մաս, 4-րդ և 11-րդ կետեր — բեռների, փոստի և ուղևորների միջազգային փոխադրման ծառայություններ, ինչպես նաև աշխատանքներ և ծառայություններ, որոնց կատարման վայրը 38-րդ հոդվածի համաձայն Հայաստանի Հանրապետությունը չէ։ Միասնական հաշվարկ, կետ 12։', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'tax-code', null, null, null, null),
  ('AM', 'AM-S-20', 'ԱԱՀ 20 % — մատակարարում Հայաստանի Հանրապետությունում (վաճառք)', '{"en":"VAT 20% — supply in Armenia (sale)"}'::jsonb, null, 'percent', 20, 'sale', 'domestic', date '2018-01-01', null, 'Հարկային օրենսգիրք, հոդված 63, 1-ին մաս — ԱԱՀ-ն հաշվարկվում է 20 տոկոս դրույքաչափով, բացառությամբ 64-րդ և 65-րդ հոդվածներով սահմանված գործարքների։ Միասնական հաշվարկ, կետ 7 (դեպի ավելացում) և կետ 8.1 (ճշգրտող հարկային հաշիվ՝ նվազեցում)։', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'tax-code', null, null, null, null),
  ('AM', 'AM-S-EXEMPT', 'ԱԱՀ-ից ազատված գործարք (վաճառք)', '{"en":"VAT-exempt transaction (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2018-01-01', null, 'Հարկային օրենսգիրք, հոդված 64, 2-րդ մաս — ԱԱՀ-ից ազատվում են, ի թիվս այլոց, կրթական ծառայությունները (1-ին կետ), բժշկական օգնությունը և առողջապահական ծառայությունները (11-րդ կետ), ապահովագրական ծառայությունները (44-րդ կետ) և բանկային ու այլ ֆինանսական գործառնությունները (47-րդ կետ)։ Ձեռք բերվածի նկատմամբ ԱԱՀ-ի հաշվանցում չի կատարվում (հոդված 72, 1-ին մաս, 2-րդ կետ)։ Միասնական հաշվարկ, կետ 13։', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'tax-code', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('AM-P-20', 'invoice', 'base', 100, null, '18A', array['18A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-P-20', 'invoice', 'tax', 100, '2261', '18B', array['18B']::text[], 100, 'AM-VAT-MONTHLY', 20),
    ('AM-P-20', 'credit_note', 'base', 100, null, '191A', array['191A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-P-20', 'credit_note', 'tax', 100, '2261', '191B', array['191B']::text[], 100, 'AM-VAT-MONTHLY', 20),
    ('AM-P-IMPORT', 'invoice', 'base', 100, null, '17A', array['17A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-P-IMPORT', 'invoice', 'tax', 100, '2262', '17B', array['17B']::text[], 100, 'AM-VAT-MONTHLY', 20),
    ('AM-P-IMPORT', 'credit_note', 'base', 100, null, '17A', array['17A']::text[], -100, 'AM-VAT-MONTHLY', 10),
    ('AM-P-IMPORT', 'credit_note', 'tax', 100, '2262', '17B', array['17B']::text[], -100, 'AM-VAT-MONTHLY', 20),
    ('AM-S-0-EXPORT', 'invoice', 'base', 100, null, '12A', array['12A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-0-EXPORT', 'credit_note', 'base', 100, null, '12A', array['12A']::text[], -100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-0-SERVICES', 'invoice', 'base', 100, null, '12A', array['12A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-0-SERVICES', 'credit_note', 'base', 100, null, '12A', array['12A']::text[], -100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-20', 'invoice', 'base', 100, null, '7A', array['7A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-20', 'invoice', 'tax', 100, '52431', '7B', array['7B']::text[], 100, 'AM-VAT-MONTHLY', 20),
    ('AM-S-20', 'credit_note', 'base', 100, null, '81A', array['81A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-20', 'credit_note', 'tax', 100, '52431', '81B', array['81B']::text[], 100, 'AM-VAT-MONTHLY', 20),
    ('AM-S-EXEMPT', 'invoice', 'base', 100, null, '13A', array['13A']::text[], 100, 'AM-VAT-MONTHLY', 10),
    ('AM-S-EXEMPT', 'credit_note', 'base', 100, null, '13A', array['13A']::text[], -100, 'AM-VAT-MONTHLY', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'AM' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format,
   rounding_unit, rounding_reference, rounding_source_key)
values
  ('AM', 'AM-VAT-MONTHLY', 'Ավելացված արժեքի հարկի և ակցիզային հարկի միասնական հաշվարկ (բաժին 1՝ ԱԱՀ)', array['month']::declaration_period[], 'month'::declaration_period, date '2018-01-01', null, 'ՀՀ կառավարությանն առընթեր պետական եկամուտների կոմիտեի նախագահի 2016 թվականի դեկտեմբերի 30-ի N 298-Ն հրամանի հավելված (ձև, տեղակայված 30.01.2023 N 76-Ն փոփոխությամբ)․ Հարկային օրենսգիրք, հոդված 69, 1-ին մաս — հաշվետու ժամանակաշրջանը օրացուցային ամիսն է։ Բաժին 2-ը (ակցիզային հարկ) այս փաթեթում չի ներառված։', true,'day_of_month_after_period'::filing_deadline_rule, 20, null, 'Հարկային օրենսգիրք, հոդված 75, 1-ին մաս — ԱԱՀ վճարողները միասնական հաշվարկը ներկայացնում են հաշվետու ժամանակաշրջանին հաջորդող ամսվա 20-ը ներառյալ։', 'tax-code', null, 1, 'N 298-Ն հրամանի հավելված, լրացման կարգի 4-րդ կետ — արժեքային մեծությունները լրացվում են դրամներով՝ առանց լումաների։', 'vat-return-form')
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  rounding_unit       = excluded.rounding_unit,
  rounding_reference  = excluded.rounding_reference,
  rounding_source_key = excluded.rounding_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('AM', 'AM-VAT-MONTHLY', '7A', 'base', 'Հարկման բազա — ԱԱՀ-ի 20 % դրույքաչափով հարկվող գործարքներ', '{"en":"Tax base — transactions taxed at the 20% VAT rate (line 7, box A)"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 7, վանդակ [Ա]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '7B', 'tax', 'ԱԱՀ կրեդիտ — ԱԱՀ-ի 20 % դրույքաչափով հարկվող գործարքների գծով հաշվարկված ԱԱՀ', '{"en":"VAT credit — VAT calculated on transactions taxed at 20% (line 7, box B)"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 7, վանդակ [Բ]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '81A', 'base', 'Ճշգրտող հարկային հաշիվներով գործարքների հարկման բազա՝ նվազեցում', '{"en":"Tax base of transactions on adjusting tax invoices — reduction (line 8.1, box A)"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 8, ենթակետ 1, վանդակ [Ա]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '81B', 'tax', 'Ճշգրտող հարկային հաշիվներով գործարքների ԱԱՀ՝ նվազեցում', '{"en":"VAT on transactions on adjusting tax invoices — reduction (line 8.1, box B)"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 8, ենթակետ 1, վանդակ [Բ]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '12A', 'base', 'Հարկման բազա — ԱԱՀ-ի 0-ական դրույքաչափով հարկվող գործարքներ', '{"en":"Tax base — transactions taxed at the 0% VAT rate (line 12, box A)"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 12, վանդակ [Ա]․ Հարկային օրենսգիրք, հոդված 65։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '13A', 'base', 'Հարկման բազա — ԱԱՀ-ից ազատված գործարքներ', '{"en":"Tax base — VAT-exempt transactions (line 13, box A)"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 13, վանդակ [Ա]․ Հարկային օրենսգիրք, հոդված 64։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '16A', 'total', 'Ընդամենը ԱԱՀ-ի կրեդիտ — հարկման բազա', '{"en":"Total VAT credit — tax base (line 16, box A)"}'::jsonb, 70, null, array['7A', '12A', '13A']::text[], array['81A']::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 16, վանդակ [Ա] (այս փաթեթը կիրառում է միայն 7, 8.1, 12 և 13 կետերը)։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '16B', 'total', 'Ընդամենը ԱԱՀ-ի կրեդիտ — հաշվարկված ԱԱՀ', '{"en":"Total VAT credit — VAT calculated (line 16, box B)"}'::jsonb, 80, null, array['7B']::text[], array['81B']::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 16, վանդակ [Բ] (այս փաթեթը կիրառում է միայն 7 և 8.1 կետերը)։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '17A', 'base', 'ՀՀ տարածք ներմուծված ապրանքների արժեք', '{"en":"Value of goods imported into Armenia (line 17, box A)"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, ԱԱՀ-ի դեբետ, կետ 17, վանդակ [Ա]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '17B', 'tax', 'ՀՀ տարածք ներմուծված ապրանքների գծով ԱԱՀ դեբետ', '{"en":"VAT debit on goods imported into Armenia (line 17, box B)"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, ԱԱՀ-ի դեբետ, կետ 17, վանդակ [Բ]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '18A', 'base', 'ՀՀ տարածքում ձեռք բերված ապրանքների և ծառայությունների արժեք', '{"en":"Value of goods and services acquired in Armenia (line 18, box A)"}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, ԱԱՀ-ի դեբետ, կետ 18, վանդակ [Ա]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '18B', 'tax', 'ՀՀ տարածքում ձեռք բերված ապրանքների և ծառայությունների գծով ԱԱՀ դեբետ', '{"en":"VAT debit on goods and services acquired in Armenia (line 18, box B)"}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, ԱԱՀ-ի դեբետ, կետ 18, վանդակ [Բ]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '191A', 'base', 'Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներ՝ նվազեցում (արժեք)', '{"en":"Adjusting tax invoices on acquisitions — reduction (value) (line 19.1, box A)"}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 19, ենթակետ 1, վանդակ [Ա]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '191B', 'tax', 'Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներ՝ նվազեցում (ԱԱՀ դեբետ)', '{"en":"Adjusting tax invoices on acquisitions — reduction (VAT debit) (line 19.1, box B)"}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 19, ենթակետ 1, վանդակ [Բ]։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '21A', 'total', 'Ընդամենը ԱԱՀ-ի դեբետ', '{"en":"Total VAT debit (line 21, box A, positive)"}'::jsonb, 150, null, array['17B', '18B']::text[], array['191B']::text[], null, null, false, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 21 = [17.Բ] + [18.Բ] − [19.1Բ] + [20.Ա] − [20.Բ] (20-րդ կետի ճշգրտումները այս փաթեթում չեն կիրառվում)․ դրական արդյունքը գրվում է [Ա] վանդակում։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '23A', 'total', 'Պետական բյուջե վճարման ենթակա ԱԱՀ-ի գումար', '{"en":"VAT payable to the State budget (line 23, box A)"}'::jsonb, 160, null, array['16B']::text[], array['21A']::text[], null, null, true, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 23, վանդակ [Ա] = [16.Բ] − [21.Ա], եթե արդյունքը դրական է։', 'vat-return-form'),
  ('AM', 'AM-VAT-MONTHLY', '23B', 'total', 'Պետական բյուջեից փոխհատուցման ենթակա ԱԱՀ-ի գումար', '{"en":"VAT refundable from the State budget (line 23, box B)"}'::jsonb, 170, null, array['21A']::text[], array['16B']::text[], null, null, true, false, null, 'Միասնական հաշվարկ, բաժին 1, կետ 23, վանդակ [Բ]՝ երբ [21.Ա] > [16.Բ]։', 'vat-return-form')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('AM-BS', 'AM', 'default', 'Ֆինանսական վիճակի մասին հաշվետվություն (ծանոթագրություն՝ ամփոփ)', 'balance_sheet', 'IFRS', date '1970-01-01', null, 'ՀՀ օրենք հաշվապահական հաշվառման մասին (04.12.2019) — ֆինանսական հաշվետվությունները կազմվում են ՖՀՄՍ-ների կամ փոքր և միջին կազմակերպությունների ՖՀՄՍ-ի համաձայն․ տողերը խմբավորում են 353-Ն հրամանի հաշվային պլանի դասերը (1-2՝ ակտիվներ, 3՝ կապիտալ, 4-5՝ պարտավորություններ, 6-7՝ եկամուտներ և ծախսեր)։ Տողերի կառուցվածքը փաթեթի ամփոփ ներկայացումն է, ոչ թե օրենքով հաստատված ձև։', 'accounting-law'),
  ('AM-IS', 'AM', 'default', 'Շահույթի կամ վնասի մասին հաշվետվություն (ծանոթագրություն՝ ամփոփ)', 'income_statement', 'IFRS', date '1970-01-01', null, 'ՀՀ օրենք հաշվապահական հաշվառման մասին (04.12.2019) — ֆինանսական հաշվետվությունները կազմվում են ՖՀՄՍ-ների կամ փոքր և միջին կազմակերպությունների ՖՀՄՍ-ի համաձայն․ տողերը խմբավորում են 353-Ն հրամանի հաշվային պլանի դասերը (1-2՝ ակտիվներ, 3՝ կապիտալ, 4-5՝ պարտավորություններ, 6-7՝ եկամուտներ և ծախսեր)։ Տողերի կառուցվածքը փաթեթի ամփոփ ներկայացումն է, ոչ թե օրենքով հաստատված ձև։', 'accounting-law')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('AM-BS', 'A-NC-FIX', 'A-NC', 'Հիմնական միջոցներ, ներդրումային գույք և ոչ նյութական ակտիվներ', '{"en":"Fixed assets, investment property and intangible assets"}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-NC-FIN', 'A-NC', 'Ոչ ընթացիկ ֆինանսական ակտիվներ և այլ ոչ ընթացիկ ակտիվներ', '{"en":"Non-current financial and other non-current assets"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-NC', null, 'Ոչ ընթացիկ ակտիվներ', '{"en":"Non-current assets"}'::jsonb, 30, 1, true, array['A-NC-FIX', 'A-NC-FIN']::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-C-INV', 'A-C', 'Պաշարներ', '{"en":"Inventories"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-C-REC', 'A-C', 'Դեբիտորական պարտքեր, կանխավճարներ և հարկերի գծով պահանջներ', '{"en":"Receivables, prepayments and tax receivables"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-C-FIN', 'A-C', 'Ընթացիկ ֆինանսական ակտիվներ', '{"en":"Current financial assets"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-C-CASH', 'A-C', 'Դրամական միջոցներ', '{"en":"Cash and cash equivalents"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-C', null, 'Ընթացիկ ակտիվներ', '{"en":"Current assets"}'::jsonb, 80, 1, true, array['A-C-INV', 'A-C-REC', 'A-C-FIN', 'A-C-CASH']::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'A-TOT', null, 'Ակտիվներ, ընդամենը', '{"en":"Total assets"}'::jsonb, 90, 1, true, array['A-NC', 'A-C']::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'E-CAP', 'E-TOT', 'Կապիտալ և պահուստներ', '{"en":"Capital and reserves"}'::jsonb, 100, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'E-RET', 'E-TOT', 'Չբաշխված շահույթ (չծածկված վնաս)', '{"en":"Retained earnings (uncovered loss)"}'::jsonb, 110, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'E-RESULT', 'E-TOT', 'Հաշվետու ժամանակաշրջանի արդյունք (չփակված եկամուտներ և ծախսեր)', '{"en":"Result of the reporting period (income and expenses not yet closed)"}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'E-TOT', null, 'Սեփական կապիտալ, ընդամենը', '{"en":"Total equity"}'::jsonb, 130, 1, true, array['E-CAP', 'E-RET', 'E-RESULT']::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'L-NC', 'L-TOT', 'Ոչ ընթացիկ պարտավորություններ', '{"en":"Non-current liabilities"}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'L-C-FIN', 'L-C', 'Ընթացիկ ֆինանսական պարտավորություններ', '{"en":"Current financial liabilities"}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'L-C-PAY', 'L-C', 'Կրեդիտորական պարտքեր, ստացված կանխավճարներ և հարկերի գծով պարտքեր', '{"en":"Trade payables, advances received and tax payables"}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'L-C-OTH', 'L-C', 'Այլ ընթացիկ պարտավորություններ և պահուստներ', '{"en":"Other current liabilities and provisions"}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'L-C', 'L-TOT', 'Ընթացիկ պարտավորություններ', '{"en":"Current liabilities"}'::jsonb, 180, 1, true, array['L-C-FIN', 'L-C-PAY', 'L-C-OTH']::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'L-TOT', null, 'Պարտավորություններ, ընդամենը', '{"en":"Total liabilities"}'::jsonb, 190, 1, true, array['L-NC', 'L-C']::text[], '{}'::text[], null, null, null),
  ('AM-BS', 'EL-TOT', null, 'Սեփական կապիտալ և պարտավորություններ, ընդամենը', '{"en":"Total equity and liabilities"}'::jsonb, 200, 1, true, array['E-TOT', 'L-TOT']::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'REV', null, 'Հասույթ իրացումից (հանած վերադարձները)', '{"en":"Revenue from sales (net of returns)"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'COST', null, 'Իրացման ինքնարժեք', '{"en":"Cost of sales"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'GROSS', null, 'Համախառն շահույթ', '{"en":"Gross profit"}'::jsonb, 30, 1, true, array['REV']::text[], array['COST']::text[], null, null, null),
  ('AM-IS', 'OTH-OP-INC', null, 'Գործառնական այլ եկամուտներ', '{"en":"Other operating income"}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'SELL', null, 'Իրացման ծախսեր', '{"en":"Selling expenses"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'ADMIN', null, 'Վարչական ծախսեր', '{"en":"Administrative expenses"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'OTH-OP-EXP', null, 'Գործառնական այլ ծախսեր', '{"en":"Other operating expenses"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'OP-PROFIT', null, 'Գործառնական շահույթ (վնաս)', '{"en":"Operating profit (loss)"}'::jsonb, 80, 1, true, array['GROSS', 'OTH-OP-INC']::text[], array['SELL', 'ADMIN', 'OTH-OP-EXP']::text[], null, null, null),
  ('AM-IS', 'NONOP-INC', null, 'Շարունակվող գործունեության այլ եկամուտներ', '{"en":"Other income from continuing operations"}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'NONOP-EXP', null, 'Շարունակվող գործունեության այլ ծախսեր', '{"en":"Other expenses from continuing operations"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'PBT', null, 'Շահույթ (վնաս) մինչև հարկումը', '{"en":"Profit (loss) before tax"}'::jsonb, 110, 1, true, array['OP-PROFIT', 'NONOP-INC']::text[], array['NONOP-EXP']::text[], null, null, null),
  ('AM-IS', 'TAX', null, 'Շահութահարկի գծով ծախս (եկամուտ)', '{"en":"Income tax expense (income)"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AM-IS', 'PROFIT', null, 'Հաշվետու ժամանակաշրջանի զուտ շահույթ (վնաս)', '{"en":"Net profit (loss) of the reporting period"}'::jsonb, 130, 1, true, array['PBT']::text[], array['TAX']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('AM-BS', 'A-NC-FIX', 10, 'code_prefix', '11', null, null, 'any'),
    ('AM-BS', 'A-NC-FIX', 20, 'code_prefix', '12', null, null, 'any'),
    ('AM-BS', 'A-NC-FIX', 30, 'code_prefix', '13', null, null, 'any'),
    ('AM-BS', 'A-NC-FIN', 10, 'code_prefix', '14', null, null, 'any'),
    ('AM-BS', 'A-NC-FIN', 20, 'code_prefix', '15', null, null, 'any'),
    ('AM-BS', 'A-C-INV', 10, 'code_prefix', '21', null, null, 'any'),
    ('AM-BS', 'A-C-REC', 10, 'code_prefix', '22', null, null, 'any'),
    ('AM-BS', 'A-C-FIN', 10, 'code_prefix', '23', null, null, 'any'),
    ('AM-BS', 'A-C-FIN', 20, 'code_prefix', '24', null, null, 'any'),
    ('AM-BS', 'A-C-CASH', 10, 'code_prefix', '25', null, null, 'any'),
    ('AM-BS', 'E-CAP', 10, 'code_prefix', '31', null, null, 'any'),
    ('AM-BS', 'E-CAP', 20, 'code_prefix', '32', null, null, 'any'),
    ('AM-BS', 'E-CAP', 30, 'code_prefix', '35', null, null, 'any'),
    ('AM-BS', 'E-RET', 10, 'code_prefix', '33', null, null, 'any'),
    ('AM-BS', 'E-RET', 20, 'code_prefix', '34', null, null, 'any'),
    ('AM-BS', 'E-RESULT', 10, 'code_prefix', '6', null, null, 'any'),
    ('AM-BS', 'E-RESULT', 20, 'code_prefix', '7', null, null, 'any'),
    ('AM-BS', 'L-NC', 10, 'code_prefix', '4', null, null, 'any'),
    ('AM-BS', 'L-C-FIN', 10, 'code_prefix', '51', null, null, 'any'),
    ('AM-BS', 'L-C-PAY', 10, 'code_prefix', '52', null, null, 'any'),
    ('AM-BS', 'L-C-OTH', 10, 'code_prefix', '53', null, null, 'any'),
    ('AM-BS', 'L-C-OTH', 20, 'code_prefix', '54', null, null, 'any'),
    ('AM-IS', 'REV', 10, 'code_prefix', '611', null, null, 'any'),
    ('AM-IS', 'REV', 20, 'code_prefix', '612', null, null, 'any'),
    ('AM-IS', 'COST', 10, 'code_prefix', '711', null, null, 'any'),
    ('AM-IS', 'OTH-OP-INC', 10, 'code_prefix', '614', null, null, 'any'),
    ('AM-IS', 'OTH-OP-INC', 20, 'code_prefix', '615', null, null, 'any'),
    ('AM-IS', 'SELL', 10, 'code_prefix', '712', null, null, 'any'),
    ('AM-IS', 'ADMIN', 10, 'code_prefix', '713', null, null, 'any'),
    ('AM-IS', 'OTH-OP-EXP', 10, 'code_prefix', '714', null, null, 'any'),
    ('AM-IS', 'OTH-OP-EXP', 20, 'code_prefix', '715', null, null, 'any'),
    ('AM-IS', 'NONOP-INC', 10, 'code_prefix', '62', null, null, 'any'),
    ('AM-IS', 'NONOP-EXP', 10, 'code_prefix', '72', null, null, 'any'),
    ('AM-IS', 'TAX', 10, 'code_prefix', '751', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('AM', 'Հայաստան', '{"en":"Armenia"}'::jsonb, array['hy', 'en']::text[], 'AMD', '221', '521', '5319', '7291', '342', '611', '216', '2521', '2511', 'SAL', 'PUR', 'GEN', 'hy', 'result_accounts', '343', '343', null, 'OPN', 'half_up', default, '625', '725', '6211', '7211', null, null, '5243', '2253', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{NNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Հարկային օրենսգիրք, հոդված 56 — հաշվարկային փաստաթղթերը (այդ թվում՝ հարկային հաշիվները) դուրս են գրվում էլեկտրոնային եղանակով պետական եկամուտների կոմիտեի էլեկտրոնային հաշվարկային փաստաթղթերի համակարգում, որտեղ էլ տրվում է փաստաթղթի համարը․ առևտրային փաստաթղթի սեփական համարակալման պարտադիր ձևաչափ օրենքով սահմանված չէ, այստեղ բերված հաջորդական համարակալումը օրինակ է։',
  numbering_source_key          = 'tax-code',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Հարկային օրենսգիրք, հոդված 56, 4-րդ մաս — հաշվարկային փաստաթուղթը դուրս է գրվում ապրանքի մատակարարման, աշխատանքի կատարման կամ ծառայության մատուցման ավարտի պահին (օրենսգրքի 8-րդ և 8.1-ին մասերով նախատեսված դեպքերում՝ նախապես)․ փաթեթը մոտարկում է կանոնը `invoice_if_issued` արժեքով (տե՛ս README.md)։',
  tax_point_source_key          = 'tax-code',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Հարկային օրենսգիրք, հոդված 56, 10-13-րդ մասեր — հաշվարկային փաստաթուղթը չեղյալ է հայտարարվում կամ ուղղվում է ճշգրտող հաշվարկային փաստաթղթով՝ առանց սկզբնական գրառումը ջնջելու։',
  posted_edit_policy_source_key = 'tax-code',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Հարկային օրենսգիրք, հոդված 56, 3-րդ մաս — հաշվարկային փաստաթղթերը դուրս են գրվում էլեկտրոնային ձևով (բացառություն՝ ՀԴՄ կտրոնը և Կառավարության սահմանած դեպքերը)․ հոդված 68 — ԱԱՀ վճարողները էլեկտրոնային ստորագրությամբ հաստատում են մատակարարների դուրս գրած հարկային հաշիվները։ Համակարգը պետական եկամուտների կոմիտեի էլեկտրոնային հաշվարկային փաստաթղթերի համակարգն է (file-online.taxservice.am), այլ ոչ թե EN 16931 / Peppol մոդելը, ուստի `profile`, `party_scheme` և `vat_scheme` դատարկ են, իսկ `obligation` և `mandatory_from` չեն լրացվում․ ձևաչափը պարտադիրություն է հայտարարում միայն այն դեպքում, երբ պրոֆիլն ասում է, թե ինչն է պարտադիր (տե՛ս README.md և docs/international.md, «From Armenia»)։',
  einvoice_source_key           = 'tax-code',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_account_scheme           = 'iban',
  bank_statement_formats        = array['csv']::text[],
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'AM';
