-- Ekwo OS — Mauritius: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/mu at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build mu`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Value Added Tax Act 1998 (Act No. 2 of 1998), consolidated version up to May 2026 — ss. 4, 5, 9, 10, 11, 14, 14A, 15, 20, 20A, 21, 22, First, Second, Fourth, Fifth and Sixth Schedules (Mauritius Revenue Authority)
--     https://www.mra.mu/download/VATAct.pdf
--   Form VAT 3 — Value Added Tax return, with the notes for completion (Mauritius Revenue Authority)
--     https://www.mra.mu/download/VAT3FormNew.pdf
--   VAT return — periodicity and electronic filing and payment deadlines (Mauritius Revenue Authority)
--     https://www.mra.mu/eservices1/vat-eservices/vat-return
--   Value Added Tax Frequently Asked Questions, September 2025 (Mauritius Revenue Authority)
--     https://www.mra.mu/download/VATFAQs.pdf
--   MRA e-Services — where the VAT return is submitted and the tax paid (Mauritius Revenue Authority)
--     https://eservices.mra.mu
--   Value Added Tax (E-invoicing) Regulations 2023 — Government Notice No. 132 of 2023 (Government of Mauritius, published by the Mauritius Revenue Authority)
--     https://www.mra.mu/download/VATe-InvoicingReg2023.pdf
--   MRA e-Invoicing System — implementation phases by taxpayer category and turnover (Mauritius Revenue Authority)
--     https://www.mra.mu/index.php/e-invoicing
--   Financial Reporting Act 2004 (Act No. 45 of 2004), ss. 72 and 75 — financial reporting and accounting standards (Mauritius Legal Information Institute)
--     https://mauritiuslii.org/akn/mu/act/2004/45/eng@2017-06-30
--   Financial Reporting Council — the financial reporting framework in Mauritius (Financial Reporting Council of Mauritius)
--     https://frc.govmu.org/frc/?page_id=1489
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('MU', 'Mauritius', '0.1.0', date '2026-10-10', '20260929141500', 'community', null, null, '2c3b6a11c3edbc1599df1906cb51208dd81753987ebc550b81ac4765407cc12a', '[{"key":"vat-act","title":"Value Added Tax Act 1998 (Act No. 2 of 1998), consolidated version up to May 2026 — ss. 4, 5, 9, 10, 11, 14, 14A, 15, 20, 20A, 21, 22, First, Second, Fourth, Fifth and Sixth Schedules","publisher":"Mauritius Revenue Authority","url":"https://www.mra.mu/download/VATAct.pdf","consulted_on":"2026-10-09","kind":"law"},{"key":"vat3-form","title":"Form VAT 3 — Value Added Tax return, with the notes for completion","publisher":"Mauritius Revenue Authority","url":"https://www.mra.mu/download/VAT3FormNew.pdf","consulted_on":"2026-10-09","kind":"form"},{"key":"vat-return-page","title":"VAT return — periodicity and electronic filing and payment deadlines","publisher":"Mauritius Revenue Authority","url":"https://www.mra.mu/eservices1/vat-eservices/vat-return","consulted_on":"2026-10-09","kind":"guidance"},{"key":"vat-faqs","title":"Value Added Tax Frequently Asked Questions, September 2025","publisher":"Mauritius Revenue Authority","url":"https://www.mra.mu/download/VATFAQs.pdf","consulted_on":"2026-10-09","kind":"guidance"},{"key":"mra-eservices","title":"MRA e-Services — where the VAT return is submitted and the tax paid","publisher":"Mauritius Revenue Authority","url":"https://eservices.mra.mu","consulted_on":"2026-10-09","kind":"portal"},{"key":"einvoicing-regs","title":"Value Added Tax (E-invoicing) Regulations 2023 — Government Notice No. 132 of 2023","publisher":"Government of Mauritius, published by the Mauritius Revenue Authority","url":"https://www.mra.mu/download/VATe-InvoicingReg2023.pdf","consulted_on":"2026-10-09","kind":"regulation"},{"key":"einvoicing-page","title":"MRA e-Invoicing System — implementation phases by taxpayer category and turnover","publisher":"Mauritius Revenue Authority","url":"https://www.mra.mu/index.php/e-invoicing","consulted_on":"2026-10-09","kind":"guidance"},{"key":"fra-2004","title":"Financial Reporting Act 2004 (Act No. 45 of 2004), ss. 72 and 75 — financial reporting and accounting standards","publisher":"Mauritius Legal Information Institute","url":"https://mauritiuslii.org/akn/mu/act/2004/45/eng@2017-06-30","consulted_on":"2026-10-09","kind":"law"},{"key":"frc-framework","title":"Financial Reporting Council — the financial reporting framework in Mauritius","publisher":"Financial Reporting Council of Mauritius","url":"https://frc.govmu.org/frc/?page_id=1489","consulted_on":"2026-10-09","kind":"guidance"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('MU', 'default', 'Mauritius reference chart of accounts', '{"fr":"Plan comptable de référence de Maurice"}'::jsonb, true, 'companies', array['MU-IFRS-IS', 'MU-IFRS-SFP']::text[], null, 'There is no legal chart of accounts in Mauritius. Financial Reporting Act 2004, s. 72 — the Financial Reporting Council issues the financial reporting and accounting standards and keeps them consistent with the International Financial Reporting Standards; s. 75(1) — the financial statements of a public interest entity comply with IFRS; the Council''s own framework page adds that the other companies prepare theirs under standards consistent with IFRS (Companies Act 2001, s. 211), and that a company which is not a public interest entity may apply IFRS for SMEs. This chart is original: four digits, blocked so that each range reaches one line of the IFRS-style statements below, with the accounts a Mauritian company actually keeps — VAT input and output tax, import VAT owed to the Mauritius Revenue Authority at the border, PAYE, National Pension Fund, National Savings Fund and Contribution Sociale Généralisée contributions, the HRDC levy and the Corporate Social Responsibility fund.', 'frc-framework')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('MU', 'default', '1000', 'Petty cash', '{"fr":"Petite caisse"}'::jsonb, 'asset_cash', false, null, 10),
  ('MU', 'default', '1010', 'Current account — MUR', '{"fr":"Compte courant — MUR"}'::jsonb, 'asset_cash', false, null, 20),
  ('MU', 'default', '1020', 'Fixed deposits placed for three months or less', '{"fr":"Dépôts à terme de trois mois au plus"}'::jsonb, 'asset_cash', false, null, 30),
  ('MU', 'default', '1030', 'Foreign currency account', '{"fr":"Compte en devises"}'::jsonb, 'asset_cash', false, null, 40),
  ('MU', 'default', '1040', 'Cash in transit — card and mobile-payment settlements', '{"fr":"Valeurs en transit — règlements par carte et paiement mobile"}'::jsonb, 'asset_cash', false, null, 50),
  ('MU', 'default', '1100', 'Trade receivables', '{"fr":"Clients"}'::jsonb, 'asset_receivable', true, null, 60),
  ('MU', 'default', '1110', 'Trade receivables — allowance for impairment', '{"fr":"Clients — provision pour dépréciation"}'::jsonb, 'asset_current', false, null, 70),
  ('MU', 'default', '1120', 'Other receivables', '{"fr":"Autres créances"}'::jsonb, 'asset_current', false, null, 80),
  ('MU', 'default', '1130', 'Amounts due from related companies', '{"fr":"Sommes dues par des sociétés liées"}'::jsonb, 'asset_current', false, null, 90),
  ('MU', 'default', '1140', 'Deposits paid', '{"fr":"Dépôts versés"}'::jsonb, 'asset_current', false, null, 100),
  ('MU', 'default', '1150', 'VAT input tax', '{"fr":"TVA déductible"}'::jsonb, 'asset_current', false, null, 110),
  ('MU', 'default', '1155', 'VAT refundable by the MRA — net of a filed return', '{"fr":"TVA remboursable par la MRA — solde d''une déclaration déposée"}'::jsonb, 'asset_current', true, null, 120),
  ('MU', 'default', '1160', 'Advances to staff', '{"fr":"Avances au personnel"}'::jsonb, 'asset_current', false, null, 130),
  ('MU', 'default', '1200', 'Inventories — goods for resale', '{"fr":"Stocks — marchandises"}'::jsonb, 'asset_current', false, null, 140),
  ('MU', 'default', '1210', 'Inventories — raw materials', '{"fr":"Stocks — matières premières"}'::jsonb, 'asset_current', false, null, 150),
  ('MU', 'default', '1220', 'Inventories — work in progress', '{"fr":"Stocks — en cours de production"}'::jsonb, 'asset_current', false, null, 160),
  ('MU', 'default', '1230', 'Inventories — finished goods', '{"fr":"Stocks — produits finis"}'::jsonb, 'asset_current', false, null, 170),
  ('MU', 'default', '1300', 'Short-term investments', '{"fr":"Placements à court terme"}'::jsonb, 'asset_current', false, null, 180),
  ('MU', 'default', '1350', 'Current tax recoverable', '{"fr":"Impôt courant à récupérer"}'::jsonb, 'asset_current', false, null, 190),
  ('MU', 'default', '1400', 'Prepayments', '{"fr":"Charges constatées d''avance"}'::jsonb, 'asset_prepayments', false, null, 200),
  ('MU', 'default', '1410', 'Accrued income', '{"fr":"Produits à recevoir"}'::jsonb, 'asset_prepayments', false, null, 210),
  ('MU', 'default', '1600', 'Land and buildings — cost', '{"fr":"Terrains et constructions — coût"}'::jsonb, 'asset_fixed', false, null, 220),
  ('MU', 'default', '1601', 'Land and buildings — accumulated depreciation', '{"fr":"Terrains et constructions — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 230),
  ('MU', 'default', '1610', 'Leasehold improvements — cost', '{"fr":"Agencements de locaux loués — coût"}'::jsonb, 'asset_fixed', false, null, 240),
  ('MU', 'default', '1611', 'Leasehold improvements — accumulated depreciation', '{"fr":"Agencements de locaux loués — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 250),
  ('MU', 'default', '1620', 'Plant and machinery — cost', '{"fr":"Installations et machines — coût"}'::jsonb, 'asset_fixed', false, null, 260),
  ('MU', 'default', '1621', 'Plant and machinery — accumulated depreciation', '{"fr":"Installations et machines — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 270),
  ('MU', 'default', '1630', 'Office equipment — cost', '{"fr":"Matériel de bureau — coût"}'::jsonb, 'asset_fixed', false, null, 280),
  ('MU', 'default', '1631', 'Office equipment — accumulated depreciation', '{"fr":"Matériel de bureau — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 290),
  ('MU', 'default', '1640', 'Computers — cost', '{"fr":"Matériel informatique — coût"}'::jsonb, 'asset_fixed', false, null, 300),
  ('MU', 'default', '1641', 'Computers — accumulated depreciation', '{"fr":"Matériel informatique — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 310),
  ('MU', 'default', '1650', 'Furniture and fittings — cost', '{"fr":"Mobilier et agencements — coût"}'::jsonb, 'asset_fixed', false, null, 320),
  ('MU', 'default', '1651', 'Furniture and fittings — accumulated depreciation', '{"fr":"Mobilier et agencements — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 330),
  ('MU', 'default', '1660', 'Motor vehicles — cost', '{"fr":"Véhicules — coût"}'::jsonb, 'asset_fixed', false, null, 340),
  ('MU', 'default', '1661', 'Motor vehicles — accumulated depreciation', '{"fr":"Véhicules — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 350),
  ('MU', 'default', '1670', 'Right-of-use assets — cost', '{"fr":"Droits d''utilisation — coût"}'::jsonb, 'asset_fixed', false, null, 360),
  ('MU', 'default', '1671', 'Right-of-use assets — accumulated depreciation', '{"fr":"Droits d''utilisation — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 370),
  ('MU', 'default', '1700', 'Investment property', '{"fr":"Immeubles de placement"}'::jsonb, 'asset_non_current', false, null, 380),
  ('MU', 'default', '1750', 'Intangible assets — cost', '{"fr":"Immobilisations incorporelles — coût"}'::jsonb, 'asset_fixed', false, null, 390),
  ('MU', 'default', '1751', 'Intangible assets — accumulated amortisation', '{"fr":"Immobilisations incorporelles — amortissements cumulés"}'::jsonb, 'asset_fixed', false, null, 400),
  ('MU', 'default', '1760', 'Goodwill', '{"fr":"Écart d''acquisition"}'::jsonb, 'asset_fixed', false, null, 410),
  ('MU', 'default', '1800', 'Investments in associates', '{"fr":"Participations dans des entreprises associées"}'::jsonb, 'asset_non_current', false, null, 420),
  ('MU', 'default', '1810', 'Investments in joint ventures', '{"fr":"Participations dans des coentreprises"}'::jsonb, 'asset_non_current', false, null, 430),
  ('MU', 'default', '1830', 'Long-term financial assets', '{"fr":"Actifs financiers à long terme"}'::jsonb, 'asset_non_current', false, null, 440),
  ('MU', 'default', '1840', 'Long-term deposits', '{"fr":"Dépôts à long terme"}'::jsonb, 'asset_non_current', false, null, 450),
  ('MU', 'default', '1900', 'Deferred tax assets', '{"fr":"Impôts différés actifs"}'::jsonb, 'asset_non_current', false, null, 460),
  ('MU', 'default', '2000', 'Trade payables', '{"fr":"Fournisseurs"}'::jsonb, 'liability_payable', true, null, 470),
  ('MU', 'default', '2010', 'Accrued expenses', '{"fr":"Charges à payer"}'::jsonb, 'liability_current', false, null, 480),
  ('MU', 'default', '2020', 'Other payables', '{"fr":"Autres dettes"}'::jsonb, 'liability_current', false, null, 490),
  ('MU', 'default', '2030', 'Amounts due to related companies', '{"fr":"Sommes dues à des sociétés liées"}'::jsonb, 'liability_current', false, null, 500),
  ('MU', 'default', '2040', 'Deposits received from customers', '{"fr":"Acomptes reçus de clients"}'::jsonb, 'liability_current', false, null, 510),
  ('MU', 'default', '2100', 'VAT output tax', '{"fr":"TVA collectée"}'::jsonb, 'liability_current', false, null, 520),
  ('MU', 'default', '2110', 'VAT payable to the MRA — net of a filed return', '{"fr":"TVA à payer à la MRA — solde d''une déclaration déposée"}'::jsonb, 'liability_current', true, null, 530),
  ('MU', 'default', '2125', 'Import VAT payable to the MRA at the border', '{"fr":"TVA à l''importation due à la MRA à la frontière"}'::jsonb, 'liability_current', false, null, 540),
  ('MU', 'default', '2126', 'VAT deferred on imported capital goods — Deferred Payment Scheme', '{"fr":"TVA différée sur biens d''équipement importés — régime de paiement différé"}'::jsonb, 'liability_current', false, null, 550),
  ('MU', 'default', '2140', 'PAYE and tax deducted at source payable to the MRA', '{"fr":"PAYE et retenues à la source dues à la MRA"}'::jsonb, 'liability_current', false, null, 560),
  ('MU', 'default', '2150', 'National Pension Fund and National Savings Fund contributions payable', '{"fr":"Cotisations NPF et NSF à payer"}'::jsonb, 'liability_current', false, null, 570),
  ('MU', 'default', '2155', 'Contribution Sociale Généralisée (CSG) payable', '{"fr":"Contribution sociale généralisée (CSG) à payer"}'::jsonb, 'liability_current', false, null, 580),
  ('MU', 'default', '2160', 'HRDC levy payable', '{"fr":"Taxe HRDC à payer"}'::jsonb, 'liability_current', false, null, 590),
  ('MU', 'default', '2165', 'Corporate Social Responsibility (CSR) fund payable', '{"fr":"Fonds de responsabilité sociale des entreprises (CSR) à payer"}'::jsonb, 'liability_current', false, null, 600),
  ('MU', 'default', '2180', 'Salaries payable', '{"fr":"Salaires à payer"}'::jsonb, 'liability_current', false, null, 610),
  ('MU', 'default', '2190', 'Directors'' fees payable', '{"fr":"Jetons de présence à payer"}'::jsonb, 'liability_current', false, null, 620),
  ('MU', 'default', '2200', 'Bank overdraft', '{"fr":"Découvert bancaire"}'::jsonb, 'liability_current', false, null, 630),
  ('MU', 'default', '2210', 'Bank loans — current portion', '{"fr":"Emprunts bancaires — part à moins d''un an"}'::jsonb, 'liability_current', false, null, 640),
  ('MU', 'default', '2220', 'Lease liabilities — current portion', '{"fr":"Dettes locatives — part à moins d''un an"}'::jsonb, 'liability_current', false, null, 650),
  ('MU', 'default', '2230', 'Hire purchase — current portion', '{"fr":"Crédit-bail — part à moins d''un an"}'::jsonb, 'liability_current', false, null, 660),
  ('MU', 'default', '2240', 'Corporate credit card', '{"fr":"Carte de crédit d''entreprise"}'::jsonb, 'liability_credit_card', false, null, 670),
  ('MU', 'default', '2250', 'Amounts due to directors', '{"fr":"Sommes dues aux administrateurs"}'::jsonb, 'liability_current', false, null, 680),
  ('MU', 'default', '2300', 'Current tax payable', '{"fr":"Impôt courant à payer"}'::jsonb, 'liability_current', false, null, 690),
  ('MU', 'default', '2350', 'Provision for unutilised leave', '{"fr":"Provision pour congés non pris"}'::jsonb, 'liability_current', false, null, 700),
  ('MU', 'default', '2360', 'Other provisions — current', '{"fr":"Autres provisions — courantes"}'::jsonb, 'liability_current', false, null, 710),
  ('MU', 'default', '2400', 'Bank loans — non-current portion', '{"fr":"Emprunts bancaires — part à plus d''un an"}'::jsonb, 'liability_non_current', false, null, 720),
  ('MU', 'default', '2410', 'Lease liabilities — non-current portion', '{"fr":"Dettes locatives — part à plus d''un an"}'::jsonb, 'liability_non_current', false, null, 730),
  ('MU', 'default', '2420', 'Hire purchase — non-current portion', '{"fr":"Crédit-bail — part à plus d''un an"}'::jsonb, 'liability_non_current', false, null, 740),
  ('MU', 'default', '2430', 'Loans from shareholders and directors — non-current', '{"fr":"Prêts des actionnaires et administrateurs — à long terme"}'::jsonb, 'liability_non_current', false, null, 750),
  ('MU', 'default', '2500', 'Deferred tax liabilities', '{"fr":"Impôts différés passifs"}'::jsonb, 'liability_non_current', false, null, 760),
  ('MU', 'default', '2550', 'Provision for reinstatement costs', '{"fr":"Provision pour remise en état"}'::jsonb, 'liability_non_current', false, null, 770),
  ('MU', 'default', '2990', 'Suspense account', '{"fr":"Compte d''attente"}'::jsonb, 'liability_current', false, null, 780),
  ('MU', 'default', '3000', 'Share capital', '{"fr":"Capital social"}'::jsonb, 'equity', false, null, 790),
  ('MU', 'default', '3010', 'Treasury shares', '{"fr":"Actions propres"}'::jsonb, 'equity', false, null, 800),
  ('MU', 'default', '3100', 'Other reserves', '{"fr":"Autres réserves"}'::jsonb, 'equity', false, null, 810),
  ('MU', 'default', '3110', 'Foreign currency translation reserve', '{"fr":"Réserve de conversion"}'::jsonb, 'equity', false, null, 820),
  ('MU', 'default', '3200', 'Retained earnings', '{"fr":"Résultats non distribués"}'::jsonb, 'equity_retained', false, null, 830),
  ('MU', 'default', '3210', 'Dividends paid', '{"fr":"Dividendes versés"}'::jsonb, 'equity_retained', false, null, 840),
  ('MU', 'default', '4000', 'Sales of goods', '{"fr":"Ventes de marchandises"}'::jsonb, 'income', false, null, 850),
  ('MU', 'default', '4010', 'Services rendered', '{"fr":"Prestations de services"}'::jsonb, 'income', false, null, 860),
  ('MU', 'default', '4020', 'Export sales of goods', '{"fr":"Ventes de marchandises à l''exportation"}'::jsonb, 'income', false, null, 870),
  ('MU', 'default', '4030', 'Export of services', '{"fr":"Prestations de services à l''exportation"}'::jsonb, 'income', false, null, 880),
  ('MU', 'default', '4500', 'Interest income', '{"fr":"Produits d''intérêts"}'::jsonb, 'income_other', false, null, 890),
  ('MU', 'default', '4510', 'Dividend income', '{"fr":"Dividendes reçus"}'::jsonb, 'income_other', false, null, 900),
  ('MU', 'default', '4520', 'Rental income', '{"fr":"Revenus locatifs"}'::jsonb, 'income_other', false, null, 910),
  ('MU', 'default', '4530', 'Government grants', '{"fr":"Subventions publiques"}'::jsonb, 'income_other', false, null, 920),
  ('MU', 'default', '4700', 'Foreign exchange gains', '{"fr":"Gains de change"}'::jsonb, 'income_other', false, null, 930),
  ('MU', 'default', '4750', 'Gain on disposal of property plant and equipment', '{"fr":"Plus-values de cession d''immobilisations corporelles"}'::jsonb, 'income_other', false, null, 940),
  ('MU', 'default', '4790', 'Other income', '{"fr":"Autres produits"}'::jsonb, 'income_other', false, null, 950),
  ('MU', 'default', '5000', 'Purchases of goods for resale', '{"fr":"Achats de marchandises"}'::jsonb, 'expense_direct_cost', false, null, 960),
  ('MU', 'default', '5010', 'Freight inwards and import duties', '{"fr":"Frais de transport et droits d''importation"}'::jsonb, 'expense_direct_cost', false, null, 970),
  ('MU', 'default', '5020', 'Subcontract costs', '{"fr":"Sous-traitance"}'::jsonb, 'expense_direct_cost', false, null, 980),
  ('MU', 'default', '5100', 'Changes in inventories', '{"fr":"Variation des stocks"}'::jsonb, 'expense_direct_cost', false, null, 990),
  ('MU', 'default', '6000', 'Salaries and wages', '{"fr":"Salaires et traitements"}'::jsonb, 'expense', false, null, 1000),
  ('MU', 'default', '6010', 'Directors'' remuneration', '{"fr":"Rémunération des administrateurs"}'::jsonb, 'expense', false, null, 1010),
  ('MU', 'default', '6020', 'Directors'' fees', '{"fr":"Jetons de présence"}'::jsonb, 'expense', false, null, 1020),
  ('MU', 'default', '6030', 'National Pension Fund and National Savings Fund contributions — employer', '{"fr":"Cotisations NPF et NSF — part patronale"}'::jsonb, 'expense', false, null, 1030),
  ('MU', 'default', '6035', 'Contribution Sociale Généralisée (CSG) — employer', '{"fr":"Contribution sociale généralisée (CSG) — part patronale"}'::jsonb, 'expense', false, null, 1040),
  ('MU', 'default', '6040', 'HRDC levy', '{"fr":"Taxe HRDC"}'::jsonb, 'expense', false, null, 1050),
  ('MU', 'default', '6050', 'Retirement gratuity and end-of-service benefits', '{"fr":"Gratification de fin de carrière et indemnités de fin de contrat"}'::jsonb, 'expense', false, null, 1060),
  ('MU', 'default', '6060', 'Staff welfare', '{"fr":"Œuvres sociales"}'::jsonb, 'expense', false, null, 1070),
  ('MU', 'default', '6070', 'Staff medical expenses and insurance', '{"fr":"Frais médicaux et assurance du personnel"}'::jsonb, 'expense', false, null, 1080),
  ('MU', 'default', '6080', 'Staff training', '{"fr":"Formation du personnel"}'::jsonb, 'expense', false, null, 1090),
  ('MU', 'default', '6200', 'Depreciation of property plant and equipment', '{"fr":"Amortissement des immobilisations corporelles"}'::jsonb, 'expense_depreciation', false, null, 1100),
  ('MU', 'default', '6210', 'Depreciation of right-of-use assets', '{"fr":"Amortissement des droits d''utilisation"}'::jsonb, 'expense_depreciation', false, null, 1110),
  ('MU', 'default', '6220', 'Amortisation of intangible assets', '{"fr":"Amortissement des immobilisations incorporelles"}'::jsonb, 'expense_depreciation', false, null, 1120),
  ('MU', 'default', '6300', 'Rent — short-term leases', '{"fr":"Loyers — locations de courte durée"}'::jsonb, 'expense', false, null, 1130),
  ('MU', 'default', '6310', 'Utilities', '{"fr":"Eau, électricité et gaz"}'::jsonb, 'expense', false, null, 1140),
  ('MU', 'default', '6320', 'Repairs and maintenance', '{"fr":"Entretien et réparations"}'::jsonb, 'expense', false, null, 1150),
  ('MU', 'default', '6330', 'Cleaning and security services', '{"fr":"Nettoyage et gardiennage"}'::jsonb, 'expense', false, null, 1160),
  ('MU', 'default', '6340', 'Telephone and internet', '{"fr":"Téléphone et internet"}'::jsonb, 'expense', false, null, 1170),
  ('MU', 'default', '6350', 'Software subscriptions', '{"fr":"Abonnements logiciels"}'::jsonb, 'expense', false, null, 1180),
  ('MU', 'default', '6360', 'Advertising and marketing', '{"fr":"Publicité et marketing"}'::jsonb, 'expense', false, null, 1190),
  ('MU', 'default', '6370', 'Travelling', '{"fr":"Déplacements"}'::jsonb, 'expense', false, null, 1200),
  ('MU', 'default', '6380', 'Motor vehicle expenses', '{"fr":"Frais de véhicules"}'::jsonb, 'expense', false, null, 1210),
  ('MU', 'default', '6390', 'Entertainment', '{"fr":"Réceptions et divertissements"}'::jsonb, 'expense', false, null, 1220),
  ('MU', 'default', '6400', 'Subscriptions and memberships', '{"fr":"Cotisations et abonnements"}'::jsonb, 'expense', false, null, 1230),
  ('MU', 'default', '6410', 'Insurance', '{"fr":"Assurances"}'::jsonb, 'expense', false, null, 1240),
  ('MU', 'default', '6420', 'Professional fees', '{"fr":"Honoraires"}'::jsonb, 'expense', false, null, 1250),
  ('MU', 'default', '6430', 'Audit fees', '{"fr":"Honoraires d''audit"}'::jsonb, 'expense', false, null, 1260),
  ('MU', 'default', '6440', 'Company secretarial and registration fees', '{"fr":"Frais de secrétariat juridique et d''immatriculation"}'::jsonb, 'expense', false, null, 1270),
  ('MU', 'default', '6450', 'Bank charges', '{"fr":"Frais bancaires"}'::jsonb, 'expense', false, null, 1280),
  ('MU', 'default', '6455', 'Corporate Social Responsibility (CSR) fund contribution', '{"fr":"Contribution au fonds CSR"}'::jsonb, 'expense', false, null, 1290),
  ('MU', 'default', '6460', 'Printing and stationery', '{"fr":"Fournitures de bureau et imprimés"}'::jsonb, 'expense', false, null, 1300),
  ('MU', 'default', '6470', 'Postage and courier', '{"fr":"Frais postaux et courrier"}'::jsonb, 'expense', false, null, 1310),
  ('MU', 'default', '6480', 'Licences permits and local authority fees', '{"fr":"Licences, permis et redevances des collectivités locales"}'::jsonb, 'expense', false, null, 1320),
  ('MU', 'default', '6490', 'Royalties', '{"fr":"Redevances"}'::jsonb, 'expense', false, null, 1330),
  ('MU', 'default', '6500', 'Bad debts written off', '{"fr":"Créances irrécouvrables"}'::jsonb, 'expense', false, null, 1340),
  ('MU', 'default', '6510', 'Impairment loss on trade receivables', '{"fr":"Dépréciation des créances clients"}'::jsonb, 'expense', false, null, 1350),
  ('MU', 'default', '6900', 'Donations', '{"fr":"Dons"}'::jsonb, 'expense', false, null, 1360),
  ('MU', 'default', '6950', 'Foreign exchange losses', '{"fr":"Pertes de change"}'::jsonb, 'expense', false, null, 1370),
  ('MU', 'default', '6960', 'Loss on disposal of property plant and equipment', '{"fr":"Moins-values de cession d''immobilisations corporelles"}'::jsonb, 'expense', false, null, 1380),
  ('MU', 'default', '6990', 'Rounding differences', '{"fr":"Écarts d''arrondi"}'::jsonb, 'expense', false, null, 1390),
  ('MU', 'default', '7000', 'Interest on bank loans', '{"fr":"Intérêts sur emprunts bancaires"}'::jsonb, 'expense', false, null, 1400),
  ('MU', 'default', '7010', 'Interest on lease liabilities', '{"fr":"Intérêts sur dettes locatives"}'::jsonb, 'expense', false, null, 1410),
  ('MU', 'default', '7020', 'Hire purchase interest', '{"fr":"Intérêts sur crédit-bail"}'::jsonb, 'expense', false, null, 1420),
  ('MU', 'default', '7030', 'Interest on loans from related parties and others', '{"fr":"Intérêts sur prêts de parties liées et autres"}'::jsonb, 'expense', false, null, 1430),
  ('MU', 'default', '8000', 'Current income tax expense', '{"fr":"Charge d''impôt courant"}'::jsonb, 'expense', false, null, 1440),
  ('MU', 'default', '8010', 'Deferred tax expense', '{"fr":"Charge d''impôt différé"}'::jsonb, 'expense', false, null, 1450),
  ('MU', 'default', '8020', 'Under or over provision of income tax in prior years', '{"fr":"Sous-provision ou sur-provision d''impôt des exercices antérieurs"}'::jsonb, 'expense', false, null, 1460)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('MU', 'BNK', 'Bank', '{"fr":"Banque"}'::jsonb, 'bank', 30),
  ('MU', 'CSH', 'Petty cash', '{"fr":"Petite caisse"}'::jsonb, 'cash', 40),
  ('MU', 'GEN', 'General journal', '{"fr":"Journal général"}'::jsonb, 'general', 50),
  ('MU', 'OPN', 'Opening balances', '{"fr":"À-nouveaux"}'::jsonb, 'opening', 60),
  ('MU', 'PUR', 'Purchases journal', '{"fr":"Journal des achats"}'::jsonb, 'purchase', 20),
  ('MU', 'SAL', 'Sales journal', '{"fr":"Journal des ventes"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('MU', 'MU-P-15', 'Purchase, standard rate 15 %, deductible', '{"fr":"Achat, taux normal 15 %, déductible"}'::jsonb, 'A local purchase of goods or services at the standard rate, used to make taxable supplies', 'percent', 15, 'purchase', 'domestic', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 21(1) and (3)(a) — a taxable person takes the input tax allowable in the taxable period as a credit against output tax, in full where the goods or services are used to make taxable supplies; s. 21(5) — the credit needs a VAT invoice from a supplier authorised to charge VAT. Form VAT 3, line 6.6 — Other goods and services purchased locally.', 'S', null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-15-BL', 'Purchase, standard rate 15 %, input tax not allowed', '{"fr":"Achat, taux normal 15 %, TVA non déductible"}'::jsonb, 'A motor car for up to nine persons, accommodation, catering, entertainment and similar items on which section 21(2) refuses the credit', 'percent', 15, 'purchase', 'domestic', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 21(2) — no input tax is allowed as a credit on motor cars and other vehicles for the transport of not more than nine persons including the driver, motorcycles and mopeds for own use (paragraph (b)) and their maintenance and repairs (paragraph (d)); accommodation or lodging, catering services, receptions and entertainment (paragraph (c)); petroleum oils of heading 27.10 other than fuel oils and oils for resale (paragraph (e)); and, since 1 January 2026, the supply of digital or electronic services (paragraph (i), added by the Finance (Miscellaneous Provisions) Act 2025). The VAT is part of the cost of the line. Form VAT 3, line 7 — Taxable input on which no input tax is allowed as a credit. The form asks for the value inclusive of VAT for paragraph (a) goods; this pack reports the value excluding VAT, a gap recorded in the README.', 'S', null, 130, 'vat', false, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-15-CAP', 'Purchase of capital goods, standard rate 15 %, deductible', '{"fr":"Achat de biens d''investissement, taux normal 15 %, déductible"}'::jsonb, 'Goods of a capital nature bought locally for the business', 'percent', 15, 'purchase', 'domestic', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 21(1) and (3)(a); the VAT 3 notes for completion distinguish goods of a capital nature purchased locally. A repayment of the excess is claimable at line 15 when the input tax on capital goods exceeds Rs 100,000 (VAT FAQ). Form VAT 3, line 6.4 — Capital goods purchased locally.', 'S', null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-EX', 'Purchase, exempt', '{"fr":"Achat, exonéré"}'::jsonb, 'An insurance premium, a bank service or another exempt supply bought for the business', 'percent', 0, 'purchase', 'exempt', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 9 and First Schedule — an exempt supply carries no VAT. Form VAT 3, line 8.2 — Exempt input, goods and services purchased locally.', 'E', null, 160, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-IMP', 'Import of goods, VAT paid at the border', '{"fr":"Importation de biens, TVA payée à la frontière"}'::jsonb, 'Goods imported for the business; the VAT is collected on importation and claimed as input tax', 'percent', 15, 'purchase', 'import', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 10(1)(b) — VAT is charged on the importation of any goods other than those in the First Schedule, by reference to the value determined under s. 13; s. 21(5)(b) — the customs import declaration supports the credit. Form VAT 3, line 6.3 — Other imports. The VAT is held on the import control account until it is settled to the Mauritius Revenue Authority.', null, null, 170, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-IMP-CAP', 'Import of capital goods, VAT paid at the border', '{"fr":"Importation de biens d''investissement, TVA payée à la frontière"}'::jsonb, 'Goods of a capital nature imported for the business', 'percent', 15, 'purchase', 'import', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 10(1)(b) and s. 21(1). Form VAT 3, line 6.1 — Capital goods imported, which includes goods on which VAT payment has been deferred; the Deferred Payment Scheme itself (line 2) is not modelled, see the README.', null, null, 180, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-IMP-EX', 'Import of exempt goods', '{"fr":"Importation de biens exonérés"}'::jsonb, 'Goods imported that the First Schedule exempts', 'percent', 0, 'purchase', 'import', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 10(1)(b) — goods in the First Schedule bear no VAT on importation. Form VAT 3, line 8.1 — Exempt input, imported goods.', null, null, 200, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-IMP-ZR', 'Import of zero-rated goods', '{"fr":"Importation de biens à taux zéro"}'::jsonb, 'Goods imported that the Fifth Schedule zero-rates', 'percent', 0, 'purchase', 'import', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 11 and Fifth Schedule. Form VAT 3, line 6.2 — Zero-rated imports.', null, null, 190, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-NR', 'Purchase from a supplier not registered for VAT', '{"fr":"Achat auprès d''un fournisseur non immatriculé à la TVA"}'::jsonb, 'A purchase from a person who is not a registered person and charges no VAT', 'percent', 0, 'purchase', 'not_subject', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 20(5) — no person may issue a document indicating an amount that purports to be VAT unless registered; no input tax can arise on such a purchase. Form VAT 3, line 7(b) — purchases from non VAT registered persons.', 'O', null, 140, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-RC-SVC', 'Service received from abroad, self-charged and claimed', '{"fr":"Service reçu de l''étranger, autoliquidé et déduit"}'::jsonb, 'A taxable service supplied by a person who does not belong in Mauritius and is not VAT registered, performed or used in Mauritius', 'percent', 15, 'purchase', 'foreign_services_received', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 14(1) to (4) — the registered recipient is treated as having supplied the services itself, accounts for the output tax and may claim it as input tax under s. 21; the supplier''s invoice is treated as a VAT invoice and the value is the amount paid or payable. Form VAT 3, line 1.4 (supplies of services received from abroad, reverse charge) for the value and the output tax, line 6.6 for the input tax. A foreign supplier of digital or electronic services registers and charges Mauritian VAT itself from 1 January 2026 (s. 14A), which is an ordinary purchase and not this tax; the input tax on that supply is refused by s. 21(2)(i).', null, null, 210, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-P-ZR', 'Purchase, zero-rated', '{"fr":"Achat, taux zéro"}'::jsonb, 'A local purchase of a good or service the Fifth Schedule zero-rates, from a registered supplier', 'percent', 0, 'purchase', 'domestic', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 11 and Fifth Schedule — the supply is a taxable supply at a rate of nil, so the buyer carries no input tax. Form VAT 3, line 6.5 — Zero-rated goods and services purchased locally.', 'Z', null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-S-15', 'Sale, standard rate 15 %', '{"fr":"Vente, taux normal 15 %"}'::jsonb, 'A taxable supply of goods or services made in Mauritius by a registered person and neither zero-rated nor exempt', 'percent', 15, 'sale', 'domestic', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 4 and s. 10(1) with the Fourth Schedule — VAT is chargeable on every taxable supply made in Mauritius by a taxable person in the course of a business, at fifteen per cent; the FAQ of the Mauritius Revenue Authority adds that a standard-rated supply is any taxable supply that is neither exempt (First Schedule) nor zero-rated (Fifth Schedule). Form VAT 3, line 1.4 — Other taxable supplies. Time of supply: s. 5(1), the earlier of the invoice and the receipt of payment.', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-S-EX', 'Sale, exempt', '{"fr":"Vente, exonérée"}'::jsonb, 'A supply of a good or service the First Schedule exempts — residential letting over 90 days, education, banking and insurance services, land and residential property', 'percent', 0, 'sale', 'exempt', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 9 and First Schedule — an exempt supply is not a taxable supply, carries no output VAT and gives no right to deduct the input tax of the goods and services used to make it (s. 21(2)(a)); examples are item 16 educational services, item 46 the letting of residential accommodation for a continuous term over 90 days, item 48 the sale of immovable property, item 50 financial services and item 50(f) insurance. A person who makes only exempt supplies cannot register. Form VAT 3, line 3 — Exempt supplies.', 'E', null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-S-ZR-DOM', 'Sale, zero-rated (local supply)', '{"fr":"Vente, taux zéro (opération locale)"}'::jsonb, 'A supply on the local market of a good or service the Fifth Schedule zero-rates — staple foods, medical and hospital services, public transport, hairdressing and the like', 'percent', 0, 'sale', 'domestic', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 11 and Fifth Schedule — a supply of a description listed there is zero-rated although it never leaves Mauritius: among others rice, wheat flour and bread (item 2), the transport of passengers by public service vehicles (item 38), medical, hospital and dental services (item 42, replaced from 5 August 2021) and hairdressing services (item 62, added by the Finance (Miscellaneous Provisions) Act 2025 and deemed in force from 6 June 2025). The pack carries one tax code for the whole list; which item applies is the preparer''s judgement and is not a field of the format. Form VAT 3, line 1.2 — Zero-rated supplies other than exports.', 'Z', null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-S-ZR-EXPG', 'Sale, zero-rated (export of goods)', '{"fr":"Vente, taux zéro (exportation de biens)"}'::jsonb, 'Goods exported from Mauritius under Customs control', 'percent', 0, 'sale', 'export', date '2002-07-01', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 11 and Fifth Schedule, item 1 — goods exported from Mauritius under Customs control are zero-rated: the supply stays a taxable supply at a rate of nil, so the input tax of the exporter remains deductible. Form VAT 3, line 1.1 — Zero-rated supplies (exports); the notes for completion name goods exported, goods shipped, supplies to duty-free shops and supplies to licensees in the freeport zone.', 'G', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null),
  ('MU', 'MU-S-ZR-EXPS', 'Sale, zero-rated (export of services)', '{"fr":"Vente, taux zéro (exportation de services)"}'::jsonb, 'A service supplied to a person who belongs outside Mauritius and is outside Mauritius when it is performed, where the service is not consumed in Mauritius', 'percent', 0, 'sale', 'export', date '2025-08-09', null, 'Value Added Tax Act 1998 (consolidated version up to May 2026), s. 11 and Fifth Schedule, item 6(a) and 6(c) — the supply of services to a person who belongs in a country other than Mauritius (no permanent establishment in Mauritius, or an abode outside it) and who is outside Mauritius at the time the services are performed is zero-rated, provided the services are not consumed in Mauritius; the last proviso was added by the Finance (Miscellaneous Provisions) Act 2025 with effect from 9 August 2025 (endnote 501 of the consolidated text). Form VAT 3, line 1.1.', 'G', null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'vat-act', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('MU-P-15', 'invoice', 'base', 100, null, '6f', array['6f']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-15', 'invoice', 'tax', 100, '1150', '6f', array['6f']::text[], 100, 'MU-VAT3', 20),
    ('MU-P-15', 'credit_note', 'base', 100, null, '6f', array['6f']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-15', 'credit_note', 'tax', 100, '1150', '6f', array['6f']::text[], -100, 'MU-VAT3', 20),
    ('MU-P-15-BL', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-15-BL', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('MU-P-15-BL', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-15-BL', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('MU-P-15-CAP', 'invoice', 'base', 100, null, '6d', array['6d']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-15-CAP', 'invoice', 'tax', 100, '1150', '6d', array['6d']::text[], 100, 'MU-VAT3', 20),
    ('MU-P-15-CAP', 'credit_note', 'base', 100, null, '6d', array['6d']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-15-CAP', 'credit_note', 'tax', 100, '1150', '6d', array['6d']::text[], -100, 'MU-VAT3', 20),
    ('MU-P-EX', 'invoice', 'base', 100, null, '8b', array['8b']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-EX', 'credit_note', 'base', 100, null, '8b', array['8b']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-IMP', 'invoice', 'base', 100, null, '6c', array['6c']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-IMP', 'invoice', 'tax', 100, '1150', '6c', array['6c']::text[], 100, 'MU-VAT3', 20),
    ('MU-P-IMP', 'invoice', 'tax', -100, '2125', null, null, 100, null, 30),
    ('MU-P-IMP', 'credit_note', 'base', 100, null, '6c', array['6c']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-IMP', 'credit_note', 'tax', 100, '1150', '6c', array['6c']::text[], -100, 'MU-VAT3', 20),
    ('MU-P-IMP', 'credit_note', 'tax', -100, '2125', null, null, 100, null, 30),
    ('MU-P-IMP-CAP', 'invoice', 'base', 100, null, '6a', array['6a']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-IMP-CAP', 'invoice', 'tax', 100, '1150', '6a', array['6a']::text[], 100, 'MU-VAT3', 20),
    ('MU-P-IMP-CAP', 'invoice', 'tax', -100, '2125', null, null, 100, null, 30),
    ('MU-P-IMP-CAP', 'credit_note', 'base', 100, null, '6a', array['6a']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-IMP-CAP', 'credit_note', 'tax', 100, '1150', '6a', array['6a']::text[], -100, 'MU-VAT3', 20),
    ('MU-P-IMP-CAP', 'credit_note', 'tax', -100, '2125', null, null, 100, null, 30),
    ('MU-P-IMP-EX', 'invoice', 'base', 100, null, '8a', array['8a']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-IMP-EX', 'credit_note', 'base', 100, null, '8a', array['8a']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-IMP-ZR', 'invoice', 'base', 100, null, '6b', array['6b']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-IMP-ZR', 'credit_note', 'base', 100, null, '6b', array['6b']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-NR', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-NR', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-RC-SVC', 'invoice', 'base', 100, null, '1d', array['1d', '6f']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-RC-SVC', 'invoice', 'tax', 100, '1150', '6f', array['6f']::text[], 100, 'MU-VAT3', 20),
    ('MU-P-RC-SVC', 'invoice', 'tax', -100, '2100', '1d', array['1d']::text[], 100, 'MU-VAT3', 30),
    ('MU-P-RC-SVC', 'credit_note', 'base', 100, null, '1d', array['1d', '6f']::text[], -100, 'MU-VAT3', 10),
    ('MU-P-RC-SVC', 'credit_note', 'tax', 100, '1150', '6f', array['6f']::text[], -100, 'MU-VAT3', 20),
    ('MU-P-RC-SVC', 'credit_note', 'tax', -100, '2100', '1d', array['1d']::text[], -100, 'MU-VAT3', 30),
    ('MU-P-ZR', 'invoice', 'base', 100, null, '6e', array['6e']::text[], 100, 'MU-VAT3', 10),
    ('MU-P-ZR', 'credit_note', 'base', 100, null, '6e', array['6e']::text[], -100, 'MU-VAT3', 10),
    ('MU-S-15', 'invoice', 'base', 100, null, '1d', array['1d']::text[], 100, 'MU-VAT3', 10),
    ('MU-S-15', 'invoice', 'tax', 100, '2100', '1d', array['1d']::text[], 100, 'MU-VAT3', 20),
    ('MU-S-15', 'credit_note', 'base', 100, null, '1d', array['1d']::text[], -100, 'MU-VAT3', 10),
    ('MU-S-15', 'credit_note', 'tax', 100, '2100', '1d', array['1d']::text[], -100, 'MU-VAT3', 20),
    ('MU-S-EX', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'MU-VAT3', 10),
    ('MU-S-EX', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'MU-VAT3', 10),
    ('MU-S-ZR-DOM', 'invoice', 'base', 100, null, '1b', array['1b']::text[], 100, 'MU-VAT3', 10),
    ('MU-S-ZR-DOM', 'credit_note', 'base', 100, null, '1b', array['1b']::text[], -100, 'MU-VAT3', 10),
    ('MU-S-ZR-EXPG', 'invoice', 'base', 100, null, '1a', array['1a']::text[], 100, 'MU-VAT3', 10),
    ('MU-S-ZR-EXPG', 'credit_note', 'base', 100, null, '1a', array['1a']::text[], -100, 'MU-VAT3', 10),
    ('MU-S-ZR-EXPS', 'invoice', 'base', 100, null, '1a', array['1a']::text[], 100, 'MU-VAT3', 10),
    ('MU-S-ZR-EXPS', 'credit_note', 'base', 100, null, '1a', array['1a']::text[], -100, 'MU-VAT3', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'MU' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('MU', 'MU-VAT3', 'VAT return (form VAT 3)', array['month', 'quarter']::declaration_period[], null, date '2002-07-01', null, 'Value Added Tax Act, s. 22(1) — every registered person submits electronically, after the end of every taxable period, a return in the form the Director-General approves; the Second Schedule sets the turnover limit at Rs 10 million. s. 22(1A) — a registered person whose annual turnover of taxable supplies does not exceed that amount files for each quarter (31 March, 30 June, 30 September and 31 December) and may elect, by irrevocable written notice, to file monthly; above Rs 10 million the taxable period is the month (VAT FAQ). The cadence therefore depends on a fact about the company, its turnover, which is why no `period_default` is declared. The form is VAT 3; this pack carries the lines a document writes into (1.1 to 11) and not lines 12 to 19, which settle one period against the next and are recorded in docs/international.md. A monthly filer also uploads a list of taxable supplies other than retail with invoice number and value (s. 22(1C)), an annex the format cannot write.', true,'last_day_of_month_after_period'::filing_deadline_rule, null, null, 'Value Added Tax Act, s. 22(2)(a) — the tax payable is paid electronically when the return is submitted. The Mauritius Revenue Authority''s e-services page gives the date for a return filed and a payment made electronically: for a quarterly return, at the end of the month following the end of the quarter; for a monthly return, at the end of the following month. The default rule printed on form VAT 3 and in the VAT FAQ is shorter — 20 days after the end of the month or quarter — and the electronic one-month period replaces it where both the filing and the payment are electronic. A date that falls on a Saturday, a Sunday or a public holiday moves to the next working day. The pack retains the electronic date, since s. 22(1) obliges the return to be submitted electronically; the 20-day rule is not representable beside it.', 'vat-return-page', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('MU', 'MU-VAT3', '1a', 'base', 'Line 1.1 — Zero-rated supplies (exports)', '{"fr":"Ligne 1.1 — Livraisons à taux zéro (exportations)"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 1.1, column A — export of goods and services, goods shipped, supplies to duty-free shops, to licensees in the freeport zone and the other supplies the notes for completion list under 1.1.', 'vat3-form'),
  ('MU', 'MU-VAT3', '1b', 'base', 'Line 1.2 — Zero-rated supplies other than exports', '{"fr":"Ligne 1.2 — Livraisons à taux zéro autres qu''exportations"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 1.2, column A — zero-rated goods and services supplied on the local market (Fifth Schedule).', 'vat3-form'),
  ('MU', 'MU-VAT3', '1c', 'base', 'Line 1.3 — Taxable supplies made to exempt bodies or persons — value', '{"fr":"Ligne 1.3 — Livraisons imposables à des organismes ou personnes exonérés — valeur"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 1.3, column A — the value of taxable supplies made to bodies or persons exempted from payment of VAT. Declared and empty: which buyer is an exempt body or person is a fact about the customer the format does not hold, so no tax code posts to it and the preparer enters the line by hand.', 'vat3-form'),
  ('MU', 'MU-VAT3', '1c', 'tax', 'Line 1.3 — Taxable supplies made to exempt bodies or persons — VAT', '{"fr":"Ligne 1.3 — Livraisons imposables à des organismes ou personnes exonérés — TVA"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 1.3, column B — declared and empty, for the reason given at the value column.', 'vat3-form'),
  ('MU', 'MU-VAT3', '1d', 'base', 'Line 1.4 — Other taxable supplies — value', '{"fr":"Ligne 1.4 — Autres opérations imposables — valeur"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 1.4, column A — supplies of taxable goods and services, including the disposal of taxable capital goods, supplies for private use, donations and gifts, and supplies of services received from abroad (reverse charge), excluding the zero-rated supplies of lines 1.1 to 1.3.', 'vat3-form'),
  ('MU', 'MU-VAT3', '1d', 'tax', 'Line 1.4 — Other taxable supplies — output VAT', '{"fr":"Ligne 1.4 — Autres opérations imposables — TVA collectée"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 1.4, column B — the output VAT on the value of column A, at 15 %.', 'vat3-form'),
  ('MU', 'MU-VAT3', '2', 'tax', 'Line 2 — Deferred VAT on importation', '{"fr":"Ligne 2 — TVA différée à l''importation"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 2, column B — the VAT deferred on imported capital goods under the VAT Deferred Payment Scheme. Declared and empty: the scheme postpones a payment at the border and has no document of its own in the format; see the README.', 'vat3-form'),
  ('MU', 'MU-VAT3', '3', 'base', 'Line 3 — Exempt supplies', '{"fr":"Ligne 3 — Opérations exonérées"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 3, column A — the value of exempt goods and services supplied on the local market (First Schedule).', 'vat3-form'),
  ('MU', 'MU-VAT3', '4', 'tax', 'Line 4 — Penalty on excess amount overclaimed', '{"fr":"Ligne 4 — Pénalité sur excédent indûment réclamé"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 4, column B — the 20 % penalty on an excess amount overclaimed in a previous period, deemed to be output tax and capped at Rs 100,000. Declared and empty: it is an assessment, not the result of a document.', 'vat3-form'),
  ('MU', 'MU-VAT3', '5A', 'total', 'Line 5 — Total, column A (value)', '{"fr":"Ligne 5 — Total, colonne A (valeur)"}'::jsonb, 100, null, array['1a', '1b', '1c:base', '1d:base', '3']::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 5, column A — the total of the values of lines 1.1 to 1.4 and 3; line 2 and line 4 carry VAT only.', 'vat3-form'),
  ('MU', 'MU-VAT3', '5B', 'total', 'Line 5 — Total, column B (output VAT)', '{"fr":"Ligne 5 — Total, colonne B (TVA collectée)"}'::jsonb, 110, null, array['1c:tax', '1d:tax', '2', '4']::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 5, column B — the total of the VAT of lines 1.3, 1.4, 2 and 4; zero-rated and exempt supplies carry none.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6a', 'base', 'Line 6.1 — Capital goods imported — value', '{"fr":"Ligne 6.1 — Biens d''investissement importés — valeur"}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.1, column A — the importation of goods of a capital nature to the business, including goods on which VAT payment has been deferred.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6a', 'tax', 'Line 6.1 — Capital goods imported — input VAT', '{"fr":"Ligne 6.1 — Biens d''investissement importés — TVA déductible"}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.1, column B.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6b', 'base', 'Line 6.2 — Zero-rated imports', '{"fr":"Ligne 6.2 — Importations à taux zéro"}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.2 — the importation of zero-rated goods.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6c', 'base', 'Line 6.3 — Other imports — value', '{"fr":"Ligne 6.3 — Autres importations — valeur"}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.3, column A — the importation of goods other than capital goods (6.1) and zero-rated goods (6.2).', 'vat3-form'),
  ('MU', 'MU-VAT3', '6c', 'tax', 'Line 6.3 — Other imports — input VAT', '{"fr":"Ligne 6.3 — Autres importations — TVA déductible"}'::jsonb, 160, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.3, column B.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6d', 'base', 'Line 6.4 — Capital goods purchased locally — value', '{"fr":"Ligne 6.4 — Biens d''investissement achetés localement — valeur"}'::jsonb, 170, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.4, column A — goods of a capital nature to the business purchased locally.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6d', 'tax', 'Line 6.4 — Capital goods purchased locally — input VAT', '{"fr":"Ligne 6.4 — Biens d''investissement achetés localement — TVA déductible"}'::jsonb, 180, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.4, column B.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6e', 'base', 'Line 6.5 — Zero-rated goods and services purchased locally', '{"fr":"Ligne 6.5 — Biens et services à taux zéro achetés localement"}'::jsonb, 190, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.5 — zero-rated goods and services supplied to the business locally.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6f', 'base', 'Line 6.6 — Other goods and services purchased locally — value', '{"fr":"Ligne 6.6 — Autres biens et services achetés localement — valeur"}'::jsonb, 200, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.6, column A — local supplies to the business other than capital goods (6.4) and zero-rated supplies (6.5); a service received from abroad under the reverse charge is also reported here.', 'vat3-form'),
  ('MU', 'MU-VAT3', '6f', 'tax', 'Line 6.6 — Other goods and services purchased locally — input VAT', '{"fr":"Ligne 6.6 — Autres biens et services achetés localement — TVA déductible"}'::jsonb, 210, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 6.6, column B.', 'vat3-form'),
  ('MU', 'MU-VAT3', '7', 'base', 'Line 7 — Taxable input on which no input tax is allowed as a credit', '{"fr":"Ligne 7 — Achats pour lesquels aucun crédit de TVA n''est admis"}'::jsonb, 220, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 7 — (a) imports and purchases in respect of which section 21(2) refuses the credit, which the notes ask to be entered inclusive of VAT, and (b) purchases from persons who are not VAT registered. This pack enters the value excluding VAT, see the README.', 'vat3-form'),
  ('MU', 'MU-VAT3', '8a', 'base', 'Line 8.1 — Exempt input, imported goods', '{"fr":"Ligne 8.1 — Achats exonérés, biens importés"}'::jsonb, 230, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 8.1 — imports of exempt goods.', 'vat3-form'),
  ('MU', 'MU-VAT3', '8b', 'base', 'Line 8.2 — Exempt input, goods and services purchased locally', '{"fr":"Ligne 8.2 — Achats exonérés, biens et services achetés localement"}'::jsonb, 240, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 8.2 — exempt goods and services purchased locally.', 'vat3-form'),
  ('MU', 'MU-VAT3', '9A', 'total', 'Line 9 — Total, column A (value)', '{"fr":"Ligne 9 — Total, colonne A (valeur)"}'::jsonb, 250, null, array['6a:base', '6b', '6c:base', '6d:base', '6e', '6f:base', '7', '8a', '8b']::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 9, column A — the total of the values of lines 6.1 to 6.6, 7, 8.1 and 8.2.', 'vat3-form'),
  ('MU', 'MU-VAT3', '9B', 'total', 'Line 9 — Total, column B (input VAT)', '{"fr":"Ligne 9 — Total, colonne B (TVA déductible)"}'::jsonb, 260, null, array['6a:tax', '6c:tax', '6d:tax', '6f:tax']::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 9, column B — the total of the VAT of lines 6.1, 6.3, 6.4 and 6.6.', 'vat3-form'),
  ('MU', 'MU-VAT3', '10', 'total', 'Line 10 — Input tax deductible', '{"fr":"Ligne 10 — TVA déductible"}'::jsonb, 270, null, array['9B']::text[], '{}'::text[], null, null, false, false, null, 'Form VAT 3, line 10, column B — the input tax allowed as a credit. Section 21(3)(b) apportions the input tax of a person who makes both taxable and exempt supplies by the proportion of taxable supplies to total turnover of the previous accounting year (the percentage printed at the head of the input section); this pack carries no such proportion and reports the whole of line 9B, which is the figure a wholly taxable business files. The apportionment is recorded in the README.', 'vat3-form'),
  ('MU', 'MU-VAT3', '11', 'total', 'Line 11 — VAT due and payable / (Excess VAT)', '{"fr":"Ligne 11 — TVA à payer / (crédit de TVA)"}'::jsonb, 280, null, array['5B']::text[], array['10']::text[], null, null, false, false, null, 'Form VAT 3, line 11 — line 5B minus line 10B. A positive figure is payable to the Mauritius Revenue Authority with the return; a negative figure is an excess carried forward on line 12 of the next return or claimed for repayment on line 15 (s. 22(2)(b) and s. 24). Lines 12 to 19 — the excess brought forward, adjustments, the repayment claim, the penalties and interest — are period-to-period settlement and assessment, not the result of a document, and are not carried.', 'vat3-form')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('MU-IFRS-IS', 'MU', 'default', 'Statement of profit or loss', 'income_statement', 'IFRS', date '2015-09-15', null, 'Financial Reporting Act 2004, s. 72 and s. 75(1); IAS 1 asks for a statement of profit or loss, and allows the expenses to be analysed by nature, which these lines follow.', 'fra-2004'),
  ('MU-IFRS-SFP', 'MU', 'default', 'Statement of financial position', 'balance_sheet', 'IFRS', date '2015-09-15', null, 'Financial Reporting Act 2004, s. 72 and s. 75(1) — standards consistent with IFRS apply to the financial statements of a public interest entity, and the Financial Reporting Council''s framework page applies standards consistent with IFRS to the other companies; IAS 1 requires a statement of financial position that separates current from non-current assets and liabilities. The lines below follow the presentation of the IFRS for SMEs and IAS 1, which a company that is not a public interest entity may apply.', 'fra-2004')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('MU-IFRS-IS', '1', null, 'Revenue', '{"fr":"Produits des activités ordinaires"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '2', null, 'Other income', '{"fr":"Autres produits"}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '3', null, 'Purchases and changes in inventories', '{"fr":"Achats et variation des stocks"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '4', null, 'Employee benefits expense', '{"fr":"Charges de personnel"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '5', null, 'Depreciation and amortisation', '{"fr":"Dotations aux amortissements"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '6', null, 'Other operating expenses', '{"fr":"Autres charges d''exploitation"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '7', null, 'Finance costs', '{"fr":"Charges financières"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '8', null, 'Profit before tax', '{"fr":"Résultat avant impôt"}'::jsonb, 80, 1, true, array['1', '2']::text[], array['3', '4', '5', '6', '7']::text[], null, null, null),
  ('MU-IFRS-IS', '9', null, 'Income tax expense', '{"fr":"Charge d''impôt sur le résultat"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-IS', '10', null, 'Profit for the year', '{"fr":"Résultat de l''exercice"}'::jsonb, 100, 1, true, array['8']::text[], array['9']::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA', null, 'Current assets', '{"fr":"Actif courant"}'::jsonb, 10, 1, true, array['CA.1', 'CA.2', 'CA.3', 'CA.4', 'CA.5', 'CA.6']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA.1', null, 'Cash and cash equivalents', '{"fr":"Trésorerie et équivalents"}'::jsonb, 11, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA.2', null, 'Trade and other receivables', '{"fr":"Clients et autres créances"}'::jsonb, 12, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA.3', null, 'Inventories', '{"fr":"Stocks"}'::jsonb, 13, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA.4', null, 'Financial assets', '{"fr":"Actifs financiers"}'::jsonb, 14, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA.5', null, 'Current tax recoverable', '{"fr":"Impôt courant à récupérer"}'::jsonb, 15, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CA.6', null, 'Prepayments and accrued income', '{"fr":"Charges constatées d''avance et produits à recevoir"}'::jsonb, 16, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA', null, 'Non-current assets', '{"fr":"Actif non courant"}'::jsonb, 20, 1, true, array['NCA.1', 'NCA.2', 'NCA.3', 'NCA.4', 'NCA.5', 'NCA.6', 'NCA.7']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.1', null, 'Property, plant and equipment', '{"fr":"Immobilisations corporelles"}'::jsonb, 21, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.2', null, 'Investment property', '{"fr":"Immeubles de placement"}'::jsonb, 22, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.3', null, 'Intangible assets', '{"fr":"Immobilisations incorporelles"}'::jsonb, 23, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.4', null, 'Investments in associates', '{"fr":"Participations dans des entreprises associées"}'::jsonb, 24, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.5', null, 'Investments in joint ventures', '{"fr":"Participations dans des coentreprises"}'::jsonb, 25, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.6', null, 'Financial assets', '{"fr":"Actifs financiers"}'::jsonb, 26, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCA.7', null, 'Deferred tax assets', '{"fr":"Impôts différés actifs"}'::jsonb, 27, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'TA', null, 'Total assets', '{"fr":"Total de l''actif"}'::jsonb, 30, 1, true, array['CA', 'NCA']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CL', null, 'Current liabilities', '{"fr":"Passif courant"}'::jsonb, 40, 1, true, array['CL.1', 'CL.2', 'CL.3', 'CL.4', 'CL.5']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CL.1', null, 'Trade and other payables', '{"fr":"Fournisseurs et autres dettes"}'::jsonb, 41, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CL.2', null, 'Borrowings and other financial liabilities', '{"fr":"Emprunts et autres passifs financiers"}'::jsonb, 42, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CL.3', null, 'Amounts due to directors', '{"fr":"Sommes dues aux administrateurs"}'::jsonb, 43, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CL.4', null, 'Current tax payable', '{"fr":"Impôt courant à payer"}'::jsonb, 44, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'CL.5', null, 'Provisions', '{"fr":"Provisions"}'::jsonb, 45, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCL', null, 'Non-current liabilities', '{"fr":"Passif non courant"}'::jsonb, 50, 1, true, array['NCL.1', 'NCL.2', 'NCL.3']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCL.1', null, 'Borrowings and other financial liabilities', '{"fr":"Emprunts et autres passifs financiers"}'::jsonb, 51, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCL.2', null, 'Deferred tax liabilities', '{"fr":"Impôts différés passifs"}'::jsonb, 52, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NCL.3', null, 'Provisions', '{"fr":"Provisions"}'::jsonb, 53, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'TL', null, 'Total liabilities', '{"fr":"Total du passif"}'::jsonb, 60, 1, true, array['CL', 'NCL']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'NA', null, 'Net assets', '{"fr":"Actif net"}'::jsonb, 70, 1, true, array['TA']::text[], array['TL']::text[], null, null, null),
  ('MU-IFRS-SFP', 'EQ', null, 'Equity', '{"fr":"Capitaux propres"}'::jsonb, 80, 1, true, array['EQ.1', 'EQ.2', 'EQ.3']::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'EQ.1', null, 'Share capital', '{"fr":"Capital social"}'::jsonb, 81, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'EQ.2', null, 'Other reserves', '{"fr":"Autres réserves"}'::jsonb, 82, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('MU-IFRS-SFP', 'EQ.3', null, 'Retained earnings', '{"fr":"Résultats non distribués"}'::jsonb, 83, -1, false, '{}'::text[], '{}'::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('MU-IFRS-IS', '1', 10, 'code_range', '4000', '4030', null, 'any'),
    ('MU-IFRS-IS', '2', 10, 'code_range', '4500', '4790', null, 'any'),
    ('MU-IFRS-IS', '3', 10, 'code_range', '5000', '5100', null, 'any'),
    ('MU-IFRS-IS', '4', 10, 'code_range', '6000', '6080', null, 'any'),
    ('MU-IFRS-IS', '5', 10, 'code_range', '6200', '6220', null, 'any'),
    ('MU-IFRS-IS', '6', 10, 'code_range', '6300', '6990', null, 'any'),
    ('MU-IFRS-IS', '7', 10, 'code_range', '7000', '7030', null, 'any'),
    ('MU-IFRS-IS', '9', 10, 'code_range', '8000', '8020', null, 'any'),
    ('MU-IFRS-SFP', 'CA.1', 10, 'code_range', '1000', '1040', null, 'any'),
    ('MU-IFRS-SFP', 'CA.2', 10, 'code_range', '1100', '1160', null, 'any'),
    ('MU-IFRS-SFP', 'CA.3', 10, 'code_range', '1200', '1230', null, 'any'),
    ('MU-IFRS-SFP', 'CA.4', 10, 'account_code', '1300', null, null, 'any'),
    ('MU-IFRS-SFP', 'CA.5', 10, 'account_code', '1350', null, null, 'any'),
    ('MU-IFRS-SFP', 'CA.6', 10, 'code_range', '1400', '1410', null, 'any'),
    ('MU-IFRS-SFP', 'NCA.1', 10, 'code_range', '1600', '1671', null, 'any'),
    ('MU-IFRS-SFP', 'NCA.2', 10, 'account_code', '1700', null, null, 'any'),
    ('MU-IFRS-SFP', 'NCA.3', 10, 'code_range', '1750', '1760', null, 'any'),
    ('MU-IFRS-SFP', 'NCA.4', 10, 'account_code', '1800', null, null, 'any'),
    ('MU-IFRS-SFP', 'NCA.5', 10, 'account_code', '1810', null, null, 'any'),
    ('MU-IFRS-SFP', 'NCA.6', 10, 'code_range', '1830', '1840', null, 'any'),
    ('MU-IFRS-SFP', 'NCA.7', 10, 'account_code', '1900', null, null, 'any'),
    ('MU-IFRS-SFP', 'CL.1', 10, 'code_range', '2000', '2190', null, 'any'),
    ('MU-IFRS-SFP', 'CL.1', 20, 'account_code', '2990', null, null, 'credit'),
    ('MU-IFRS-SFP', 'CL.2', 10, 'code_range', '2200', '2240', null, 'any'),
    ('MU-IFRS-SFP', 'CL.3', 10, 'account_code', '2250', null, null, 'any'),
    ('MU-IFRS-SFP', 'CL.4', 10, 'account_code', '2300', null, null, 'any'),
    ('MU-IFRS-SFP', 'CL.5', 10, 'code_range', '2350', '2360', null, 'any'),
    ('MU-IFRS-SFP', 'NCL.1', 10, 'code_range', '2400', '2430', null, 'any'),
    ('MU-IFRS-SFP', 'NCL.2', 10, 'account_code', '2500', null, null, 'any'),
    ('MU-IFRS-SFP', 'NCL.3', 10, 'account_code', '2550', null, null, 'any'),
    ('MU-IFRS-SFP', 'EQ.1', 10, 'code_range', '3000', '3010', null, 'any'),
    ('MU-IFRS-SFP', 'EQ.2', 10, 'code_range', '3100', '3110', null, 'any'),
    ('MU-IFRS-SFP', 'EQ.3', 10, 'code_range', '3200', '3210', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('MU', 'Mauritius', '{"fr":"Maurice"}'::jsonb, array['en', 'fr']::text[], 'MUR', '1100', '2000', '2990', '6990', '3200', '4000', '5000', '1010', '1000', 'SAL', 'PUR', 'GEN', 'en', 'retained_earnings', null, null, null, 'OPN', 'half_up', default, '4700', '6950', '4750', '6960', null, null, '2110', '1155', null, null)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Value Added Tax Act, s. 20(2)(a) to (c) — a VAT invoice carries the words "VAT INVOICE" in a prominent place, the supplier''s name, address, VAT registration number and business registration number, its serial number and its date of issue; s. 20(3) — legible copies are kept in chronological order, and s. 20(4) for at least five years. The law asks for a serial number and not for a series without a gap, which is why the style is `sequential`. The fiscal invoice of the e-invoicing system carries, in addition, the Invoice Registration Number the Mauritius Revenue Authority''s platform issues (Value Added Tax (E-invoicing) Regulations 2023, reg. 2 and 5(e)), which this pack cannot generate.',
  numbering_source_key          = 'vat-act',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_date',
  tax_point_legal_reference     = 'Value Added Tax Act, s. 5(1) — a supply of goods or services is deemed to take place at the time an invoice or VAT invoice for it is issued by the supplier or at the time payment is received by the supplier, whichever is the earlier; s. 5(2) applies the same rule to each successive part of a continuous supply of services. The closed vocabulary has no word for "the earlier of the invoice and the payment": `invoice_date` is the principle, and a payment received before the invoice, which brings the tax point forward in Mauritius, is the gap recorded in docs/international.md.',
  tax_point_source_key          = 'vat-act',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'Mauritius has no Peppol profile, no published structured-invoice standard and no ISO 6523 scheme a party is addressed by, so `profile`, `party_scheme` and `vat_scheme` are null and `obligation` is `none`: what Mauritius has instead is a real-time fiscalisation (clearance) system, which the vocabulary of this field does not describe. Value Added Tax Act, s. 20A(1) — the Director-General sets up an e-invoicing system through which a business registers every invoice, debit note and credit note and issues fiscal invoices to its customers; s. 20A(2) — a person who carries on a business activity of a prescribed category, or who is notified in writing by the Director-General, acquires the equipment and software and issues fiscal invoices from the date the Director-General fixes, whether or not it is a taxable person (s. 20A(3)); ss. 20B and 20C — a penalty of Rs 10,000 per month, capped at Rs 200,000, for failing to issue fiscal invoices, and up to Rs 50,000 for tampering. The Value Added Tax (E-invoicing) Regulations 2023 (Government Notice No. 132 of 2023, in force 2 October 2023) require an Electronic Billing System to send each transaction to the Invoice Fiscalisation Platform and to print on the fiscal invoice the Invoice Registration Number and the QR code the platform returns. The Authority''s roll-out table lists limited companies above Rs 100 million of annual turnover from 15 May 2024, and the other taxpayers above Rs 100 million from 1 August 2025, above Rs 80 million from 30 June 2026 and above Rs 40 million from 1 September 2026, each marked as launched. Ekwo does not call the platform and issues no Invoice Registration Number: a company in scope fiscalises through a certified Electronic Billing System, and the gap is recorded in docs/international.md and in the README of this pack.',
  einvoice_source_key           = 'einvoicing-regs',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'MU';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('MU', 'vat_invoice', 'always', 'VAT INVOICE', '{"fr":"VAT INVOICE"}'::jsonb, 10, date '1970-01-01', null, 'Value Added Tax Act, s. 20(2)(a) — a registered person issuing a VAT invoice specifies the words "VAT INVOICE" in a prominent place; s. 20(1) — every registered person who makes a taxable supply to any person issues one.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
