-- Ekwo OS — Angola: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ao at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build ao`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Lei n.º 14/23, de 28 de dezembro — altera e republica o Código do Imposto sobre o Valor Acrescentado (Lei n.º 7/19): artigo 12.º (isenções nas operações internas), artigo 15.º (exportações), artigo 19.º (taxas: 14 %, 7 %, 5 %, 1 %), artigo 21.º (imposto cativo), artigo 44.º (declaração periódica), artigo 60.º (regime de exclusão), artigo 69.º-A (regime simplificado); Anexos I a IV (Assembleia Nacional (Diário da República, I Série, n.º 246))
--     https://lex.ao/docs/assembleia-nacional/2023/lei-n-o-14-23-de-28-de-dezembro/
--   Lei n.º 14/23 — texto da primeira alteração ao Código do IVA, com os artigos 12.º, 15.º, 19.º, 21.º, 44.º, 60.º e 69.º-A e os Anexos I e II (bens alimentares de amplo consumo e insumos agrícolas) (Assembleia Nacional (Diário da República))
--     https://angolex.com/paginas/codigos/alteracao-do-codigo-do-imposto-sobre-o-valor-acrescentado-14a-23a.html
--   Código do Imposto sobre o Valor Acrescentado (Lei n.º 7/19, de 24 de abril) — artigo 11.º (exigibilidade do imposto) e artigo 44.º (a declaração periódica é submetida por transmissão electrónica de dados até ao último dia do mês seguinte àquele a que respeitam as operações) (Assembleia Nacional (Diário da República))
--     https://angolex.com/paginas/codigos/codigo-do-imposto-sobre-o-valor-acrescentado.html
--   Nova taxa do IVA de 5 % para os bens alimentares de amplo consumo e cesta básica entra em vigor a 1 de janeiro de 2024 (Ministério das Finanças)
--     https://www.minfin.gov.ao/sala-de-imprensa/noticias/noticia/nova-taxa-do-iva-em-5-para-os-bens-alimentares-de-amplo-consumo-e-cesta-basica-entra-em-vigor-a-1-de-janeiro-de-2024
--   Redução de 50 % da taxa de IVA para produtos da cesta básica — taxa de 7 % introduzida pelo Orçamento Geral do Estado para 2022 (Lei n.º 32/21), em vigor de 1 de janeiro de 2022 até à taxa de 5 % de 1 de janeiro de 2024 (PLMJ Advogados)
--     https://www.plmj.com/xms/files/03_Novidades_legislativas/2021/11_novembro/N_Colab_Angola_-_Reducao_de_IVA.pdf
--   Lei n.º 14/25, de 30 de dezembro — Orçamento Geral do Estado para 2026: artigo 23.º (taxa de 5 % do IVA na importação ou transmissão de equipamentos industriais pelo fabricante, mediante verificação da Administração Tributária) e artigo 35.º (isenção de IVA e de Imposto do Selo das transacções por plataformas de pagamento e transferências instantâneas móveis autorizadas pelo Banco Nacional de Angola) (Assembleia Nacional (Diário da República))
--     https://angolex.com/paginas/leis/lei-que-aprova-o-orcamento-geral-do-estado-para-o-exercicio-economico-de-2026a-14a-25a.html
--   Modelo 7 — Declaração Periódica do IVA (regime geral e regime de caixa): quadros 1 a 15, campos 01 a 48, fórmulas dos campos 31 a 35 e 37 (Administração Geral Tributária / Ministério das Finanças)
--     https://www.hml.ucm.minfin.gov.ao/cs/groups/public/documents/document/zmlu/mdq5/~edisp/minfin049184.pdf
--   Modelo 7 — Declaração Periódica do IVA, versão publicada no Diário da República (campos 01 a 48): a declaração é submetida até ao último dia de cada mês relativamente às operações do mês anterior (Diário da República / Administração Geral Tributária)
--     https://ivaemangola.ideiasdinamicas.com/docs/02_MODELO_7_DECLARACAO_PERIODICA.pdf
--   Imposto sobre o Valor Acrescentado — página do Portal do Contribuinte (nota: reproduz ainda regras anteriores à Lei n.º 14/23, como Cabinda a 2 % e regime simplificado a 3 %; prevalece o texto da Lei n.º 14/23) (Administração Geral Tributária)
--     https://portaldocontribuinte.minfin.gov.ao/impostos-e-taxas/imposto-sobre-valor-acrescentado
--   Submissão dos ficheiros SAF-T (AO) de facturação e de aquisição de bens e serviços — mensal, até ao último dia do mês seguinte (Decreto Presidencial n.º 312/18) (Administração Geral Tributária)
--     https://portaldocontribuinte.minfin.gov.ao/noticia?id=809127
--   Portal do Contribuinte — onde a declaração periódica (Modelo 7) é submetida e a nota de liquidação é paga (Administração Geral Tributária)
--     https://portaldocontribuinte.minfin.gov.ao/
--   Decreto Presidencial n.º 71/25, de 20 de março — Regime Jurídico das Facturas: artigo 8.º (emissão até ao quinto dia útil), artigo 10.º (numeração sequencial e cronológica por tipo de documento e ano económico), artigo 16.º (facturação electrónica obrigatória nos regimes geral e simplificado do IVA), artigo 17.º (software validado ou disponibilizado pela AGT, comunicação em tempo real), artigo 37.º (fases) (Presidente da República (Diário da República))
--     https://lex.ao/docs/presidente-da-republica/2025/decreto-presidencial-n-o-71-25-de-20-de-marco/
--   Facturação Electrónica a partir de 1 de Janeiro de 2026 — grandes contribuintes e fornecedores do Estado (EY Angola)
--     https://www.ey.com/pt_ao/technical/tax-alerts/facturacao-electronica-a-partir-de-1-de-janeiro-de-2026
--   Decreto n.º 82/01, de 16 de novembro — aprova o Plano Geral de Contabilidade (PGC) (Conselho de Ministros (Diário da República))
--     https://angolex.com/paginas/decreto-presidencial/plano-geral-de-contabilidade-angolano-82a-01a.html
--   Plano Geral de Contabilidade Angolano, Decreto n.º 82/01 — lista de contas das classes 1 a 8 (código e denominação), edição de actualização da Ordem dos Contabilistas e Peritos Contabilistas de Angola (Ordem dos Contabilistas e Peritos Contabilistas de Angola (OCPCA))
--     https://www.segcontas.co.ao/sites/default/files/2022-08/PGC_Decreto_n%C2%BA82_01_ATF%20edi%C3%A7%C3%B5est%C3%A9cnicas.pdf
--   Decreto Presidencial n.º 180/19, de 24 de maio — introduz no Plano Geral de Contabilidade a conta 34.5 «Imposto sobre o Valor Acrescentado» e as suas subcontas (IVA suportado, dedutível, liquidado, regularizações, apuramento, a pagar, a recuperar) (Presidente da República (Diário da República))
--     https://lex.ao/docs/presidente-da-republica/2019/decreto-presidencial-n-o-180-19-de-24-de-maio/
--   Lei n.º 8/19, de 24 de abril — Código do Imposto Especial de Consumo (IEC): incidência, valor tributável e exigibilidade (Assembleia Nacional (Diário da República))
--     https://lex.ao/docs/assembleia-nacional/2019/lei-n-o-8-19-de-24-de-abril/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('AO', 'Angola', '0.1.0', date '2026-10-10', '20260923110000', 'community', null, null, '2d36c4dcba0a4d8181c2433bd3a8a5edbe0dc08d0afd1848a67ac1ac0d8a0aac', '[{"key":"civa-lei-14-23","title":"Lei n.º 14/23, de 28 de dezembro — altera e republica o Código do Imposto sobre o Valor Acrescentado (Lei n.º 7/19): artigo 12.º (isenções nas operações internas), artigo 15.º (exportações), artigo 19.º (taxas: 14 %, 7 %, 5 %, 1 %), artigo 21.º (imposto cativo), artigo 44.º (declaração periódica), artigo 60.º (regime de exclusão), artigo 69.º-A (regime simplificado); Anexos I a IV","publisher":"Assembleia Nacional (Diário da República, I Série, n.º 246)","url":"https://lex.ao/docs/assembleia-nacional/2023/lei-n-o-14-23-de-28-de-dezembro/","consulted_on":"2026-10-10","kind":"law"},{"key":"civa-lei-14-23-texto","title":"Lei n.º 14/23 — texto da primeira alteração ao Código do IVA, com os artigos 12.º, 15.º, 19.º, 21.º, 44.º, 60.º e 69.º-A e os Anexos I e II (bens alimentares de amplo consumo e insumos agrícolas)","publisher":"Assembleia Nacional (Diário da República)","url":"https://angolex.com/paginas/codigos/alteracao-do-codigo-do-imposto-sobre-o-valor-acrescentado-14a-23a.html","consulted_on":"2026-10-10","kind":"law"},{"key":"civa-lei-7-19","title":"Código do Imposto sobre o Valor Acrescentado (Lei n.º 7/19, de 24 de abril) — artigo 11.º (exigibilidade do imposto) e artigo 44.º (a declaração periódica é submetida por transmissão electrónica de dados até ao último dia do mês seguinte àquele a que respeitam as operações)","publisher":"Assembleia Nacional (Diário da República)","url":"https://angolex.com/paginas/codigos/codigo-do-imposto-sobre-o-valor-acrescentado.html","consulted_on":"2026-10-10","kind":"law"},{"key":"mf-iva-5","title":"Nova taxa do IVA de 5 % para os bens alimentares de amplo consumo e cesta básica entra em vigor a 1 de janeiro de 2024","publisher":"Ministério das Finanças","url":"https://www.minfin.gov.ao/sala-de-imprensa/noticias/noticia/nova-taxa-do-iva-em-5-para-os-bens-alimentares-de-amplo-consumo-e-cesta-basica-entra-em-vigor-a-1-de-janeiro-de-2024","consulted_on":"2026-10-10","kind":"guidance"},{"key":"plmj-iva-7","title":"Redução de 50 % da taxa de IVA para produtos da cesta básica — taxa de 7 % introduzida pelo Orçamento Geral do Estado para 2022 (Lei n.º 32/21), em vigor de 1 de janeiro de 2022 até à taxa de 5 % de 1 de janeiro de 2024","publisher":"PLMJ Advogados","url":"https://www.plmj.com/xms/files/03_Novidades_legislativas/2021/11_novembro/N_Colab_Angola_-_Reducao_de_IVA.pdf","consulted_on":"2026-10-10","kind":"guidance"},{"key":"oge-2026","title":"Lei n.º 14/25, de 30 de dezembro — Orçamento Geral do Estado para 2026: artigo 23.º (taxa de 5 % do IVA na importação ou transmissão de equipamentos industriais pelo fabricante, mediante verificação da Administração Tributária) e artigo 35.º (isenção de IVA e de Imposto do Selo das transacções por plataformas de pagamento e transferências instantâneas móveis autorizadas pelo Banco Nacional de Angola)","publisher":"Assembleia Nacional (Diário da República)","url":"https://angolex.com/paginas/leis/lei-que-aprova-o-orcamento-geral-do-estado-para-o-exercicio-economico-de-2026a-14a-25a.html","consulted_on":"2026-10-10","kind":"law"},{"key":"modelo-7","title":"Modelo 7 — Declaração Periódica do IVA (regime geral e regime de caixa): quadros 1 a 15, campos 01 a 48, fórmulas dos campos 31 a 35 e 37","publisher":"Administração Geral Tributária / Ministério das Finanças","url":"https://www.hml.ucm.minfin.gov.ao/cs/groups/public/documents/document/zmlu/mdq5/~edisp/minfin049184.pdf","consulted_on":"2026-10-10","kind":"form"},{"key":"modelo-7-dr","title":"Modelo 7 — Declaração Periódica do IVA, versão publicada no Diário da República (campos 01 a 48): a declaração é submetida até ao último dia de cada mês relativamente às operações do mês anterior","publisher":"Diário da República / Administração Geral Tributária","url":"https://ivaemangola.ideiasdinamicas.com/docs/02_MODELO_7_DECLARACAO_PERIODICA.pdf","consulted_on":"2026-10-10","kind":"form"},{"key":"agt-iva","title":"Imposto sobre o Valor Acrescentado — página do Portal do Contribuinte (nota: reproduz ainda regras anteriores à Lei n.º 14/23, como Cabinda a 2 % e regime simplificado a 3 %; prevalece o texto da Lei n.º 14/23)","publisher":"Administração Geral Tributária","url":"https://portaldocontribuinte.minfin.gov.ao/impostos-e-taxas/imposto-sobre-valor-acrescentado","consulted_on":"2026-10-10","kind":"guidance"},{"key":"agt-saft","title":"Submissão dos ficheiros SAF-T (AO) de facturação e de aquisição de bens e serviços — mensal, até ao último dia do mês seguinte (Decreto Presidencial n.º 312/18)","publisher":"Administração Geral Tributária","url":"https://portaldocontribuinte.minfin.gov.ao/noticia?id=809127","consulted_on":"2026-10-10","kind":"guidance"},{"key":"portal-contribuinte","title":"Portal do Contribuinte — onde a declaração periódica (Modelo 7) é submetida e a nota de liquidação é paga","publisher":"Administração Geral Tributária","url":"https://portaldocontribuinte.minfin.gov.ao/","consulted_on":"2026-10-10","kind":"portal"},{"key":"dp-71-25","title":"Decreto Presidencial n.º 71/25, de 20 de março — Regime Jurídico das Facturas: artigo 8.º (emissão até ao quinto dia útil), artigo 10.º (numeração sequencial e cronológica por tipo de documento e ano económico), artigo 16.º (facturação electrónica obrigatória nos regimes geral e simplificado do IVA), artigo 17.º (software validado ou disponibilizado pela AGT, comunicação em tempo real), artigo 37.º (fases)","publisher":"Presidente da República (Diário da República)","url":"https://lex.ao/docs/presidente-da-republica/2025/decreto-presidencial-n-o-71-25-de-20-de-marco/","consulted_on":"2026-10-10","kind":"law"},{"key":"ey-fact-elec","title":"Facturação Electrónica a partir de 1 de Janeiro de 2026 — grandes contribuintes e fornecedores do Estado","publisher":"EY Angola","url":"https://www.ey.com/pt_ao/technical/tax-alerts/facturacao-electronica-a-partir-de-1-de-janeiro-de-2026","consulted_on":"2026-10-10","kind":"guidance"},{"key":"pgc-82-01","title":"Decreto n.º 82/01, de 16 de novembro — aprova o Plano Geral de Contabilidade (PGC)","publisher":"Conselho de Ministros (Diário da República)","url":"https://angolex.com/paginas/decreto-presidencial/plano-geral-de-contabilidade-angolano-82a-01a.html","consulted_on":"2026-10-10","kind":"law"},{"key":"pgc-lista","title":"Plano Geral de Contabilidade Angolano, Decreto n.º 82/01 — lista de contas das classes 1 a 8 (código e denominação), edição de actualização da Ordem dos Contabilistas e Peritos Contabilistas de Angola","publisher":"Ordem dos Contabilistas e Peritos Contabilistas de Angola (OCPCA)","url":"https://www.segcontas.co.ao/sites/default/files/2022-08/PGC_Decreto_n%C2%BA82_01_ATF%20edi%C3%A7%C3%B5est%C3%A9cnicas.pdf","consulted_on":"2026-10-10","kind":"regulation"},{"key":"dp-180-19","title":"Decreto Presidencial n.º 180/19, de 24 de maio — introduz no Plano Geral de Contabilidade a conta 34.5 «Imposto sobre o Valor Acrescentado» e as suas subcontas (IVA suportado, dedutível, liquidado, regularizações, apuramento, a pagar, a recuperar)","publisher":"Presidente da República (Diário da República)","url":"https://lex.ao/docs/presidente-da-republica/2019/decreto-presidencial-n-o-180-19-de-24-de-maio/","consulted_on":"2026-10-10","kind":"regulation"},{"key":"iec-lei-8-19","title":"Lei n.º 8/19, de 24 de abril — Código do Imposto Especial de Consumo (IEC): incidência, valor tributável e exigibilidade","publisher":"Assembleia Nacional (Diário da República)","url":"https://lex.ao/docs/assembleia-nacional/2019/lei-n-o-8-19-de-24-de-abril/","consulted_on":"2026-10-10","kind":"law"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('AO', 'default', 'Plano Geral de Contabilidade (PGC) — selecção para sociedades comerciais', '{}'::jsonb, true, 'companies', array['AO-PGC-BAL', 'AO-PGC-DR']::text[], null, 'Decreto n.º 82/01, de 16 de novembro, approves the Plano Geral de Contabilidade, the legal chart of accounts of Angola. It applies to companies other than banks and insurers, which follow their own regimes (the International Financial Reporting Standards for banks); the IFRS complement the plan. The chart carries the official codes and names of classes 1 to 8, with the dots removed from each code (34.5.3.1 is 34531), at the level of detail a trading company posts to. The VAT sub-accounts of account 34.5 come from Decreto Presidencial n.º 180/19, de 24 de maio. Where this pack adds a level the plan leaves free, it says so in the name or in the README: 7581 Arredondamentos (rounding) and 3791 IVA de importação a pagar à alfândega (import VAT owed to customs).', 'pgc-82-01')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('AO', 'default', '11', 'Imobilizações corpóreas', '{}'::jsonb, 'asset_fixed', false, null, 10),
  ('AO', 'default', '111', 'Terrenos e recursos naturais', '{}'::jsonb, 'asset_fixed', false, '11', 20),
  ('AO', 'default', '112', 'Edifícios e outras construções', '{}'::jsonb, 'asset_fixed', false, '11', 30),
  ('AO', 'default', '113', 'Equipamento básico', '{}'::jsonb, 'asset_fixed', false, '11', 40),
  ('AO', 'default', '114', 'Equipamento de carga e transporte', '{}'::jsonb, 'asset_fixed', false, '11', 50),
  ('AO', 'default', '115', 'Equipamento administrativo', '{}'::jsonb, 'asset_fixed', false, '11', 60),
  ('AO', 'default', '116', 'Taras e vasilhame', '{}'::jsonb, 'asset_fixed', false, '11', 70),
  ('AO', 'default', '119', 'Outras imobilizações corpóreas', '{}'::jsonb, 'asset_fixed', false, '11', 80),
  ('AO', 'default', '12', 'Imobilizações incorpóreas', '{}'::jsonb, 'asset_fixed', false, null, 90),
  ('AO', 'default', '121', 'Trespasses', '{}'::jsonb, 'asset_fixed', false, '12', 100),
  ('AO', 'default', '122', 'Despesas de investigação e desenvolvimento', '{}'::jsonb, 'asset_fixed', false, '12', 110),
  ('AO', 'default', '123', 'Propriedade industrial e outros direitos e contratos', '{}'::jsonb, 'asset_fixed', false, '12', 120),
  ('AO', 'default', '124', 'Despesas de constituição', '{}'::jsonb, 'asset_fixed', false, '12', 130),
  ('AO', 'default', '129', 'Outras imobilizações incorpóreas', '{}'::jsonb, 'asset_fixed', false, '12', 140),
  ('AO', 'default', '13', 'Investimentos financeiros', '{}'::jsonb, 'asset_non_current', false, null, 150),
  ('AO', 'default', '131', 'Empresas subsidiárias', '{}'::jsonb, 'asset_non_current', false, '13', 160),
  ('AO', 'default', '132', 'Empresas associadas', '{}'::jsonb, 'asset_non_current', false, '13', 170),
  ('AO', 'default', '133', 'Outras empresas', '{}'::jsonb, 'asset_non_current', false, '13', 180),
  ('AO', 'default', '134', 'Investimentos em imóveis', '{}'::jsonb, 'asset_non_current', false, '13', 190),
  ('AO', 'default', '135', 'Fundos', '{}'::jsonb, 'asset_non_current', false, '13', 200),
  ('AO', 'default', '139', 'Outros investimentos financeiros', '{}'::jsonb, 'asset_non_current', false, '13', 210),
  ('AO', 'default', '14', 'Imobilizações em curso', '{}'::jsonb, 'asset_fixed', false, null, 220),
  ('AO', 'default', '141', 'Obras em curso', '{}'::jsonb, 'asset_fixed', false, '14', 230),
  ('AO', 'default', '147', 'Adiantamentos por conta de imobilizado corpóreo', '{}'::jsonb, 'asset_fixed', false, '14', 240),
  ('AO', 'default', '148', 'Adiantamentos por conta de imobilizado incorpóreo', '{}'::jsonb, 'asset_fixed', false, '14', 250),
  ('AO', 'default', '149', 'Adiantamentos por conta de investimentos financeiros', '{}'::jsonb, 'asset_fixed', false, '14', 260),
  ('AO', 'default', '18', 'Amortizações acumuladas', '{}'::jsonb, 'asset_fixed', false, null, 270),
  ('AO', 'default', '181', 'Amortizações acumuladas — imobilizações corpóreas', '{}'::jsonb, 'asset_fixed', false, '18', 280),
  ('AO', 'default', '182', 'Amortizações acumuladas — imobilizações incorpóreas', '{}'::jsonb, 'asset_fixed', false, '18', 290),
  ('AO', 'default', '183', 'Amortizações acumuladas — investimentos financeiros em imóveis', '{}'::jsonb, 'asset_fixed', false, '18', 300),
  ('AO', 'default', '19', 'Provisões para investimentos financeiros', '{}'::jsonb, 'asset_non_current', false, null, 310),
  ('AO', 'default', '21', 'Compras', '{}'::jsonb, 'expense_direct_cost', false, null, 320),
  ('AO', 'default', '211', 'Compras de matérias-primas, subsidiárias e de consumo', '{}'::jsonb, 'expense_direct_cost', false, '21', 330),
  ('AO', 'default', '212', 'Compras de mercadorias', '{}'::jsonb, 'expense_direct_cost', false, '21', 340),
  ('AO', 'default', '217', 'Devoluções de compras', '{}'::jsonb, 'expense_direct_cost', false, '21', 350),
  ('AO', 'default', '218', 'Descontos e abatimentos em compras', '{}'::jsonb, 'expense_direct_cost', false, '21', 360),
  ('AO', 'default', '22', 'Matérias-primas, subsidiárias e de consumo', '{}'::jsonb, 'asset_current', false, null, 370),
  ('AO', 'default', '23', 'Produtos e trabalhos em curso', '{}'::jsonb, 'asset_current', false, null, 380),
  ('AO', 'default', '24', 'Produtos acabados e intermédios', '{}'::jsonb, 'asset_current', false, null, 390),
  ('AO', 'default', '25', 'Sub-produtos, desperdícios, resíduos e refugos', '{}'::jsonb, 'asset_current', false, null, 400),
  ('AO', 'default', '26', 'Mercadorias', '{}'::jsonb, 'asset_current', false, null, 410),
  ('AO', 'default', '27', 'Matérias-primas, mercadorias e outros materiais em trânsito', '{}'::jsonb, 'asset_current', false, null, 420),
  ('AO', 'default', '28', 'Adiantamentos por conta de compras', '{}'::jsonb, 'asset_current', false, null, 430),
  ('AO', 'default', '29', 'Provisão para depreciação de existências', '{}'::jsonb, 'asset_current', false, null, 440),
  ('AO', 'default', '31', 'Clientes', '{}'::jsonb, 'asset_receivable', true, null, 450),
  ('AO', 'default', '311', 'Clientes — correntes', '{}'::jsonb, 'asset_receivable', true, '31', 460),
  ('AO', 'default', '312', 'Clientes — títulos a receber', '{}'::jsonb, 'asset_receivable', true, '31', 470),
  ('AO', 'default', '313', 'Clientes — títulos descontados', '{}'::jsonb, 'asset_receivable', true, '31', 480),
  ('AO', 'default', '318', 'Clientes de cobrança duvidosa', '{}'::jsonb, 'asset_receivable', true, '31', 490),
  ('AO', 'default', '319', 'Clientes — saldos credores (adiantamentos)', '{}'::jsonb, 'liability_current', false, '31', 500),
  ('AO', 'default', '32', 'Fornecedores', '{}'::jsonb, 'liability_payable', true, null, 510),
  ('AO', 'default', '321', 'Fornecedores — correntes', '{}'::jsonb, 'liability_payable', true, '32', 520),
  ('AO', 'default', '322', 'Fornecedores — títulos a pagar', '{}'::jsonb, 'liability_payable', true, '32', 530),
  ('AO', 'default', '328', 'Fornecedores — facturas em recepção e conferência', '{}'::jsonb, 'liability_payable', true, '32', 540),
  ('AO', 'default', '329', 'Fornecedores — saldos devedores (adiantamentos)', '{}'::jsonb, 'asset_current', false, '32', 550),
  ('AO', 'default', '33', 'Empréstimos', '{}'::jsonb, 'liability_current', false, null, 560),
  ('AO', 'default', '331', 'Empréstimos bancários', '{}'::jsonb, 'liability_current', false, '33', 570),
  ('AO', 'default', '332', 'Empréstimos por obrigações', '{}'::jsonb, 'liability_non_current', false, '33', 580),
  ('AO', 'default', '333', 'Empréstimos por títulos de participação', '{}'::jsonb, 'liability_non_current', false, '33', 590),
  ('AO', 'default', '339', 'Outros empréstimos obtidos', '{}'::jsonb, 'liability_non_current', false, '33', 600),
  ('AO', 'default', '34', 'Estado', '{}'::jsonb, 'liability_current', false, null, 610),
  ('AO', 'default', '341', 'Imposto sobre os lucros (Imposto Industrial)', '{}'::jsonb, 'liability_current', false, '34', 620),
  ('AO', 'default', '342', 'Imposto de produção e consumo (Imposto Especial de Consumo)', '{}'::jsonb, 'liability_current', false, '34', 630),
  ('AO', 'default', '343', 'Imposto de rendimento de trabalho (IRT)', '{}'::jsonb, 'liability_current', false, '34', 640),
  ('AO', 'default', '344', 'Imposto de circulação', '{}'::jsonb, 'liability_current', false, '34', 650),
  ('AO', 'default', '345', 'Imposto sobre o Valor Acrescentado (IVA)', '{}'::jsonb, 'liability_current', false, '34', 660),
  ('AO', 'default', '3451', 'IVA suportado', '{}'::jsonb, 'asset_current', false, '345', 670),
  ('AO', 'default', '34511', 'IVA suportado — existências', '{}'::jsonb, 'asset_current', false, '3451', 680),
  ('AO', 'default', '34512', 'IVA suportado — meios fixos e investimentos', '{}'::jsonb, 'asset_current', false, '3451', 690),
  ('AO', 'default', '34513', 'IVA suportado — outros bens e serviços', '{}'::jsonb, 'asset_current', false, '3451', 700),
  ('AO', 'default', '3452', 'IVA dedutível', '{}'::jsonb, 'asset_current', false, '345', 710),
  ('AO', 'default', '34521', 'IVA dedutível — existências', '{}'::jsonb, 'asset_current', false, '3452', 720),
  ('AO', 'default', '34522', 'IVA dedutível — meios fixos e investimentos', '{}'::jsonb, 'asset_current', false, '3452', 730),
  ('AO', 'default', '34523', 'IVA dedutível — outros bens e serviços', '{}'::jsonb, 'asset_current', false, '3452', 740),
  ('AO', 'default', '3453', 'IVA liquidado', '{}'::jsonb, 'liability_current', false, '345', 750),
  ('AO', 'default', '34531', 'IVA liquidado — operações gerais', '{}'::jsonb, 'liability_current', false, '3453', 760),
  ('AO', 'default', '34532', 'IVA liquidado — operações abrangidas pelo regime de IVA de caixa', '{}'::jsonb, 'liability_current', false, '3453', 770),
  ('AO', 'default', '3454', 'IVA regularizações', '{}'::jsonb, 'liability_current', false, '345', 780),
  ('AO', 'default', '3455', 'IVA apuramento', '{}'::jsonb, 'liability_current', false, '345', 790),
  ('AO', 'default', '34551', 'IVA apuramento — regime de IVA normal', '{}'::jsonb, 'liability_current', false, '3455', 800),
  ('AO', 'default', '34552', 'IVA apuramento — regime de IVA de caixa', '{}'::jsonb, 'liability_current', false, '3455', 810),
  ('AO', 'default', '3456', 'IVA a pagar', '{}'::jsonb, 'liability_current', false, '345', 820),
  ('AO', 'default', '34561', 'IVA a pagar — apuramento da declaração periódica', '{}'::jsonb, 'liability_current', true, '3456', 830),
  ('AO', 'default', '34563', 'IVA a pagar — liquidações oficiosas', '{}'::jsonb, 'liability_current', false, '3456', 840),
  ('AO', 'default', '3457', 'IVA a recuperar', '{}'::jsonb, 'asset_current', false, '345', 850),
  ('AO', 'default', '34571', 'IVA a recuperar — apuramentos', '{}'::jsonb, 'asset_current', true, '3457', 860),
  ('AO', 'default', '34572', 'IVA a recuperar — cativo', '{}'::jsonb, 'asset_current', false, '3457', 870),
  ('AO', 'default', '3458', 'IVA reembolsos pedidos', '{}'::jsonb, 'asset_current', false, '345', 880),
  ('AO', 'default', '348', 'Subsídios a preços', '{}'::jsonb, 'asset_current', false, '34', 890),
  ('AO', 'default', '349', 'Outros impostos', '{}'::jsonb, 'liability_current', false, '34', 900),
  ('AO', 'default', '35', 'Entidades participantes e participadas', '{}'::jsonb, 'liability_current', false, null, 910),
  ('AO', 'default', '351', 'Entidades participantes', '{}'::jsonb, 'liability_current', false, '35', 920),
  ('AO', 'default', '352', 'Entidades participadas', '{}'::jsonb, 'liability_current', false, '35', 930),
  ('AO', 'default', '36', 'Pessoal', '{}'::jsonb, 'liability_current', false, null, 940),
  ('AO', 'default', '361', 'Pessoal — remunerações', '{}'::jsonb, 'liability_current', false, '36', 950),
  ('AO', 'default', '362', 'Pessoal — participação nos resultados', '{}'::jsonb, 'liability_current', false, '36', 960),
  ('AO', 'default', '363', 'Pessoal — adiantamentos', '{}'::jsonb, 'asset_current', false, '36', 970),
  ('AO', 'default', '369', 'Pessoal — outros', '{}'::jsonb, 'liability_current', false, '36', 980),
  ('AO', 'default', '37', 'Outros valores a receber e a pagar', '{}'::jsonb, 'liability_current', false, null, 990),
  ('AO', 'default', '371', 'Compras de imobilizado', '{}'::jsonb, 'liability_current', false, '37', 1000),
  ('AO', 'default', '372', 'Vendas de imobilizado', '{}'::jsonb, 'asset_current', false, '37', 1010),
  ('AO', 'default', '373', 'Proveitos a facturar', '{}'::jsonb, 'asset_current', false, '37', 1020),
  ('AO', 'default', '374', 'Encargos a repartir por períodos futuros', '{}'::jsonb, 'asset_prepayments', false, '37', 1030),
  ('AO', 'default', '375', 'Encargos a pagar', '{}'::jsonb, 'liability_current', false, '37', 1040),
  ('AO', 'default', '376', 'Proveitos a repartir por períodos futuros', '{}'::jsonb, 'liability_current', false, '37', 1050),
  ('AO', 'default', '377', 'Contas transitórias', '{}'::jsonb, 'liability_current', false, '37', 1060),
  ('AO', 'default', '379', 'Outros valores a receber e a pagar', '{}'::jsonb, 'liability_current', false, '37', 1070),
  ('AO', 'default', '3791', 'IVA de importação a pagar à alfândega', '{}'::jsonb, 'liability_current', false, '379', 1080),
  ('AO', 'default', '38', 'Provisões para cobranças duvidosas', '{}'::jsonb, 'asset_current', false, null, 1090),
  ('AO', 'default', '381', 'Provisões para clientes', '{}'::jsonb, 'asset_current', false, '38', 1100),
  ('AO', 'default', '382', 'Provisões para saldos devedores de fornecedores', '{}'::jsonb, 'asset_current', false, '38', 1110),
  ('AO', 'default', '383', 'Provisões para participantes e participadas', '{}'::jsonb, 'asset_current', false, '38', 1120),
  ('AO', 'default', '384', 'Provisões para dívidas do pessoal', '{}'::jsonb, 'asset_current', false, '38', 1130),
  ('AO', 'default', '389', 'Provisões para outros saldos a receber', '{}'::jsonb, 'asset_current', false, '38', 1140),
  ('AO', 'default', '39', 'Provisões para outros riscos e encargos', '{}'::jsonb, 'liability_non_current', false, null, 1150),
  ('AO', 'default', '391', 'Provisões para pensões', '{}'::jsonb, 'liability_non_current', false, '39', 1160),
  ('AO', 'default', '392', 'Provisões para processos judiciais em curso', '{}'::jsonb, 'liability_non_current', false, '39', 1170),
  ('AO', 'default', '393', 'Provisões para acidentes de trabalho', '{}'::jsonb, 'liability_non_current', false, '39', 1180),
  ('AO', 'default', '394', 'Provisões para garantias dadas a clientes', '{}'::jsonb, 'liability_non_current', false, '39', 1190),
  ('AO', 'default', '399', 'Provisões para outros riscos e encargos', '{}'::jsonb, 'liability_non_current', false, '39', 1200),
  ('AO', 'default', '41', 'Títulos negociáveis', '{}'::jsonb, 'asset_current', false, null, 1210),
  ('AO', 'default', '411', 'Acções', '{}'::jsonb, 'asset_current', false, '41', 1220),
  ('AO', 'default', '412', 'Obrigações', '{}'::jsonb, 'asset_current', false, '41', 1230),
  ('AO', 'default', '413', 'Títulos da dívida pública', '{}'::jsonb, 'asset_current', false, '41', 1240),
  ('AO', 'default', '42', 'Depósitos a prazo', '{}'::jsonb, 'asset_cash', false, null, 1250),
  ('AO', 'default', '421', 'Depósitos a prazo — moeda nacional', '{}'::jsonb, 'asset_cash', false, '42', 1260),
  ('AO', 'default', '422', 'Depósitos a prazo — moeda estrangeira', '{}'::jsonb, 'asset_cash', false, '42', 1270),
  ('AO', 'default', '43', 'Depósitos à ordem', '{}'::jsonb, 'asset_cash', false, null, 1280),
  ('AO', 'default', '431', 'Depósitos à ordem — moeda nacional', '{}'::jsonb, 'asset_cash', false, '43', 1290),
  ('AO', 'default', '432', 'Depósitos à ordem — moeda estrangeira', '{}'::jsonb, 'asset_cash', false, '43', 1300),
  ('AO', 'default', '44', 'Outros depósitos', '{}'::jsonb, 'asset_cash', false, null, 1310),
  ('AO', 'default', '441', 'Outros depósitos — moeda nacional', '{}'::jsonb, 'asset_cash', false, '44', 1320),
  ('AO', 'default', '442', 'Outros depósitos — moeda estrangeira', '{}'::jsonb, 'asset_cash', false, '44', 1330),
  ('AO', 'default', '45', 'Caixa', '{}'::jsonb, 'asset_cash', false, null, 1340),
  ('AO', 'default', '451', 'Caixa — fundo fixo', '{}'::jsonb, 'asset_cash', false, '45', 1350),
  ('AO', 'default', '452', 'Caixa — valores para depositar', '{}'::jsonb, 'asset_cash', false, '45', 1360),
  ('AO', 'default', '453', 'Caixa — valores destinados a pagamentos específicos', '{}'::jsonb, 'asset_cash', false, '45', 1370),
  ('AO', 'default', '48', 'Conta transitória (banco)', '{}'::jsonb, 'asset_cash', false, null, 1380),
  ('AO', 'default', '49', 'Provisões para aplicações de tesouraria', '{}'::jsonb, 'asset_current', false, null, 1390),
  ('AO', 'default', '51', 'Capital', '{}'::jsonb, 'equity', false, null, 1400),
  ('AO', 'default', '52', 'Acções / quotas próprias', '{}'::jsonb, 'equity', false, null, 1410),
  ('AO', 'default', '53', 'Prémios de emissão', '{}'::jsonb, 'equity', false, null, 1420),
  ('AO', 'default', '54', 'Prestações suplementares', '{}'::jsonb, 'equity', false, null, 1430),
  ('AO', 'default', '55', 'Reservas legais', '{}'::jsonb, 'equity', false, null, 1440),
  ('AO', 'default', '56', 'Reservas de reavaliação', '{}'::jsonb, 'equity', false, null, 1450),
  ('AO', 'default', '57', 'Reservas com fins especiais', '{}'::jsonb, 'equity', false, null, 1460),
  ('AO', 'default', '58', 'Reservas livres', '{}'::jsonb, 'equity', false, null, 1470),
  ('AO', 'default', '61', 'Vendas', '{}'::jsonb, 'income', false, null, 1480),
  ('AO', 'default', '611', 'Vendas de produtos acabados e intermédios', '{}'::jsonb, 'income', false, '61', 1490),
  ('AO', 'default', '612', 'Vendas de sub-produtos, desperdícios, resíduos e refugos', '{}'::jsonb, 'income', false, '61', 1500),
  ('AO', 'default', '613', 'Vendas de mercadorias', '{}'::jsonb, 'income', false, '61', 1510),
  ('AO', 'default', '614', 'Vendas de embalagens de consumo', '{}'::jsonb, 'income', false, '61', 1520),
  ('AO', 'default', '615', 'Subsídios a preços', '{}'::jsonb, 'income', false, '61', 1530),
  ('AO', 'default', '617', 'Devoluções de vendas', '{}'::jsonb, 'income', false, '61', 1540),
  ('AO', 'default', '618', 'Descontos e abatimentos em vendas', '{}'::jsonb, 'income', false, '61', 1550),
  ('AO', 'default', '62', 'Prestações de serviços', '{}'::jsonb, 'income', false, null, 1560),
  ('AO', 'default', '621', 'Serviços principais', '{}'::jsonb, 'income', false, '62', 1570),
  ('AO', 'default', '622', 'Serviços secundários', '{}'::jsonb, 'income', false, '62', 1580),
  ('AO', 'default', '628', 'Descontos e abatimentos em prestações de serviços', '{}'::jsonb, 'income', false, '62', 1590),
  ('AO', 'default', '63', 'Outros proveitos operacionais', '{}'::jsonb, 'income_other', false, null, 1600),
  ('AO', 'default', '631', 'Serviços suplementares', '{}'::jsonb, 'income_other', false, '63', 1610),
  ('AO', 'default', '632', 'Royalties', '{}'::jsonb, 'income_other', false, '63', 1620),
  ('AO', 'default', '633', 'Subsídios à exploração', '{}'::jsonb, 'income_other', false, '63', 1630),
  ('AO', 'default', '634', 'Subsídios a investimento', '{}'::jsonb, 'income_other', false, '63', 1640),
  ('AO', 'default', '638', 'Outros proveitos e ganhos operacionais', '{}'::jsonb, 'income_other', false, '63', 1650),
  ('AO', 'default', '64', 'Variação nos inventários de produtos acabados e de produção em curso', '{}'::jsonb, 'income_other', false, null, 1660),
  ('AO', 'default', '65', 'Trabalhos para a própria empresa', '{}'::jsonb, 'income_other', false, null, 1670),
  ('AO', 'default', '66', 'Proveitos e ganhos financeiros gerais', '{}'::jsonb, 'income_other', false, null, 1680),
  ('AO', 'default', '661', 'Juros obtidos', '{}'::jsonb, 'income_other', false, '66', 1690),
  ('AO', 'default', '662', 'Diferenças de câmbio favoráveis', '{}'::jsonb, 'income_other', false, '66', 1700),
  ('AO', 'default', '663', 'Descontos de pronto pagamento obtidos', '{}'::jsonb, 'income_other', false, '66', 1710),
  ('AO', 'default', '664', 'Rendimentos de investimentos em imóveis', '{}'::jsonb, 'income_other', false, '66', 1720),
  ('AO', 'default', '665', 'Rendimentos de participações de capital', '{}'::jsonb, 'income_other', false, '66', 1730),
  ('AO', 'default', '666', 'Ganhos na alienação de aplicações financeiras', '{}'::jsonb, 'income_other', false, '66', 1740),
  ('AO', 'default', '667', 'Reposição de provisões', '{}'::jsonb, 'income_other', false, '66', 1750),
  ('AO', 'default', '67', 'Proveitos e ganhos financeiros em filiais e associadas', '{}'::jsonb, 'income_other', false, null, 1760),
  ('AO', 'default', '68', 'Outros proveitos e ganhos não operacionais', '{}'::jsonb, 'income_other', false, null, 1770),
  ('AO', 'default', '681', 'Reposição de provisões', '{}'::jsonb, 'income_other', false, '68', 1780),
  ('AO', 'default', '682', 'Anulação de amortizações extraordinárias', '{}'::jsonb, 'income_other', false, '68', 1790),
  ('AO', 'default', '683', 'Ganhos em imobilizações', '{}'::jsonb, 'income_other', false, '68', 1800),
  ('AO', 'default', '684', 'Ganhos em existências', '{}'::jsonb, 'income_other', false, '68', 1810),
  ('AO', 'default', '685', 'Recuperação de dívidas', '{}'::jsonb, 'income_other', false, '68', 1820),
  ('AO', 'default', '686', 'Benefícios de penalidades contratuais', '{}'::jsonb, 'income_other', false, '68', 1830),
  ('AO', 'default', '69', 'Proveitos e ganhos extraordinários', '{}'::jsonb, 'income_other', false, null, 1840),
  ('AO', 'default', '71', 'Custo das existências vendidas e consumidas', '{}'::jsonb, 'expense_direct_cost', false, null, 1850),
  ('AO', 'default', '711', 'Custo das matérias-primas consumidas', '{}'::jsonb, 'expense_direct_cost', false, '71', 1860),
  ('AO', 'default', '712', 'Custo das matérias subsidiárias consumidas', '{}'::jsonb, 'expense_direct_cost', false, '71', 1870),
  ('AO', 'default', '713', 'Custo dos materiais diversos consumidos', '{}'::jsonb, 'expense_direct_cost', false, '71', 1880),
  ('AO', 'default', '714', 'Custo das embalagens de consumo consumidas', '{}'::jsonb, 'expense_direct_cost', false, '71', 1890),
  ('AO', 'default', '715', 'Custo de outros materiais consumidos', '{}'::jsonb, 'expense_direct_cost', false, '71', 1900),
  ('AO', 'default', '72', 'Custos com o pessoal', '{}'::jsonb, 'expense', false, null, 1910),
  ('AO', 'default', '721', 'Remunerações — órgãos sociais', '{}'::jsonb, 'expense', false, '72', 1920),
  ('AO', 'default', '722', 'Remunerações — pessoal', '{}'::jsonb, 'expense', false, '72', 1930),
  ('AO', 'default', '723', 'Pensões', '{}'::jsonb, 'expense', false, '72', 1940),
  ('AO', 'default', '724', 'Prémios para pensões', '{}'::jsonb, 'expense', false, '72', 1950),
  ('AO', 'default', '725', 'Encargos sobre remunerações', '{}'::jsonb, 'expense', false, '72', 1960),
  ('AO', 'default', '726', 'Seguros de acidentes de trabalho e doenças profissionais', '{}'::jsonb, 'expense', false, '72', 1970),
  ('AO', 'default', '727', 'Formação', '{}'::jsonb, 'expense', false, '72', 1980),
  ('AO', 'default', '728', 'Outras despesas com o pessoal', '{}'::jsonb, 'expense', false, '72', 1990),
  ('AO', 'default', '73', 'Amortizações do exercício', '{}'::jsonb, 'expense_depreciation', false, null, 2000),
  ('AO', 'default', '731', 'Amortizações de imobilizações corpóreas', '{}'::jsonb, 'expense_depreciation', false, '73', 2010),
  ('AO', 'default', '732', 'Amortizações de imobilizações incorpóreas', '{}'::jsonb, 'expense_depreciation', false, '73', 2020),
  ('AO', 'default', '75', 'Outros custos e perdas operacionais', '{}'::jsonb, 'expense', false, null, 2030),
  ('AO', 'default', '751', 'Subcontratos', '{}'::jsonb, 'expense', false, '75', 2040),
  ('AO', 'default', '752', 'Fornecimentos e serviços de terceiros', '{}'::jsonb, 'expense', false, '75', 2050),
  ('AO', 'default', '753', 'Impostos', '{}'::jsonb, 'expense', false, '75', 2060),
  ('AO', 'default', '754', 'Despesas confidenciais', '{}'::jsonb, 'expense', false, '75', 2070),
  ('AO', 'default', '755', 'Quotizações', '{}'::jsonb, 'expense', false, '75', 2080),
  ('AO', 'default', '756', 'Ofertas e amostras de existências', '{}'::jsonb, 'expense', false, '75', 2090),
  ('AO', 'default', '758', 'Outros custos e perdas operacionais', '{}'::jsonb, 'expense', false, '75', 2100),
  ('AO', 'default', '7581', 'Arredondamentos', '{}'::jsonb, 'expense', false, '758', 2110),
  ('AO', 'default', '76', 'Custos e perdas financeiros gerais', '{}'::jsonb, 'expense', false, null, 2120),
  ('AO', 'default', '761', 'Juros suportados', '{}'::jsonb, 'expense', false, '76', 2130),
  ('AO', 'default', '762', 'Diferenças de câmbio desfavoráveis', '{}'::jsonb, 'expense', false, '76', 2140),
  ('AO', 'default', '763', 'Descontos de pronto pagamento concedidos', '{}'::jsonb, 'expense', false, '76', 2150),
  ('AO', 'default', '764', 'Amortizações de investimentos em imóveis', '{}'::jsonb, 'expense', false, '76', 2160),
  ('AO', 'default', '765', 'Provisões para aplicações financeiras', '{}'::jsonb, 'expense', false, '76', 2170),
  ('AO', 'default', '766', 'Perdas na alienação de aplicações financeiras', '{}'::jsonb, 'expense', false, '76', 2180),
  ('AO', 'default', '767', 'Serviços bancários', '{}'::jsonb, 'expense', false, '76', 2190),
  ('AO', 'default', '77', 'Custos e perdas financeiros em filiais e associadas', '{}'::jsonb, 'expense', false, null, 2200),
  ('AO', 'default', '78', 'Outros custos e perdas não operacionais', '{}'::jsonb, 'expense', false, null, 2210),
  ('AO', 'default', '781', 'Provisões do exercício', '{}'::jsonb, 'expense', false, '78', 2220),
  ('AO', 'default', '782', 'Amortizações extraordinárias', '{}'::jsonb, 'expense', false, '78', 2230),
  ('AO', 'default', '783', 'Perdas em imobilizações', '{}'::jsonb, 'expense', false, '78', 2240),
  ('AO', 'default', '784', 'Perdas em existências', '{}'::jsonb, 'expense', false, '78', 2250),
  ('AO', 'default', '785', 'Dívidas incobráveis', '{}'::jsonb, 'expense', false, '78', 2260),
  ('AO', 'default', '786', 'Multas e penalidades contratuais', '{}'::jsonb, 'expense', false, '78', 2270),
  ('AO', 'default', '787', 'Custos de reestruturação', '{}'::jsonb, 'expense', false, '78', 2280),
  ('AO', 'default', '79', 'Custos e perdas extraordinários', '{}'::jsonb, 'expense', false, null, 2290),
  ('AO', 'default', '81', 'Resultados transitados', '{}'::jsonb, 'equity_retained', false, null, 2300),
  ('AO', 'default', '82', 'Resultados operacionais', '{}'::jsonb, 'equity', false, null, 2310),
  ('AO', 'default', '83', 'Resultados financeiros', '{}'::jsonb, 'equity', false, null, 2320),
  ('AO', 'default', '84', 'Resultados financeiros em filiais e associadas', '{}'::jsonb, 'equity', false, null, 2330),
  ('AO', 'default', '85', 'Resultados não operacionais', '{}'::jsonb, 'equity', false, null, 2340),
  ('AO', 'default', '86', 'Resultados extraordinários', '{}'::jsonb, 'equity', false, null, 2350),
  ('AO', 'default', '87', 'Imposto sobre os lucros', '{}'::jsonb, 'expense', false, null, 2360),
  ('AO', 'default', '88', 'Resultado líquido do exercício', '{}'::jsonb, 'equity', false, null, 2370),
  ('AO', 'default', '89', 'Dividendos antecipados', '{}'::jsonb, 'equity', false, null, 2380)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('AO', 'ABE', 'Diário de abertura', '{}'::jsonb, 'opening', 60),
  ('AO', 'BAN', 'Diário de bancos', '{}'::jsonb, 'bank', 30),
  ('AO', 'CAI', 'Diário de caixa', '{}'::jsonb, 'cash', 40),
  ('AO', 'COM', 'Diário de compras', '{}'::jsonb, 'purchase', 20),
  ('AO', 'DIV', 'Diário de operações diversas', '{}'::jsonb, 'general', 50),
  ('AO', 'VEN', 'Diário de vendas', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('AO', 'AO-P-14-BL', 'Aquisição à taxa geral (14 %), IVA não dedutível', '{}'::jsonb, 'Tax charged on an expense the code excludes from the right to deduct', 'percent', 14, 'purchase', 'domestic', date '2019-10-01', null, 'Código do IVA, Capítulo V (right to deduct) — the tax charged on an expense the code excludes from deduction (for instance passenger cars and entertainment) is not deducted and is not declared: it adds to the cost of the line. Nothing is reported in the Modelo 7.', null, null, 170, 'vat', false, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-14-EXI', 'Compra de existências à taxa geral (14 %), dedutível', '{}'::jsonb, 'Goods for resale or consumption in production', 'percent', 14, 'purchase', 'domestic', date '2019-10-01', null, 'Código do IVA, art. 19.º — 14 % — and the right to deduct of the Capítulo V. Modelo 7, quadro 9, fields 18 (base) and 19 (tax in favour of the taxpayer) — acquisitions of inventories.', null, null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-14-MFI', 'Compra de meios fixos e investimentos à taxa geral (14 %), dedutível', '{}'::jsonb, 'Equipment and other fixed assets', 'percent', 14, 'purchase', 'domestic', date '2019-10-01', null, 'Código do IVA, art. 19.º — 14 %. Modelo 7, quadro 9, fields 16 (base) and 17 (tax in favour of the taxpayer) — acquisitions of fixed assets and investments.', null, null, 140, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-14-OUT', 'Compra de outros bens de consumo à taxa geral (14 %), dedutível', '{}'::jsonb, 'Consumables and other goods that are neither inventory nor fixed assets', 'percent', 14, 'purchase', 'domestic', date '2019-10-01', null, 'Código do IVA, art. 19.º — 14 %. Modelo 7, quadro 9, fields 20 (base) and 21 (tax in favour of the taxpayer) — acquisitions of other consumable goods.', null, null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-14-SERV', 'Aquisição de serviços à taxa geral (14 %), dedutível', '{}'::jsonb, 'Services bought from a supplier established in Angola', 'percent', 14, 'purchase', 'domestic', date '2019-10-01', null, 'Código do IVA, art. 19.º — 14 %. Modelo 7, quadro 9, fields 22 (base) and 23 (tax in favour of the taxpayer) — acquisitions of services.', null, null, 160, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-5-EXI', 'Compra de existências a 5 %, dedutível', '{}'::jsonb, 'Foodstuffs and agricultural inputs bought at the reduced rate', 'percent', 5, 'purchase', 'domestic', date '2024-01-01', null, 'Código do IVA, art. 19.º, Anexos I and II — 5 %. Modelo 7, quadro 9, fields 18 (base) and 19 (tax in favour of the taxpayer) — acquisitions of inventories.', null, null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-EX', 'Aquisição isenta ou não tributada', '{}'::jsonb, 'Bank charges, medicines and other exempt purchases', 'percent', 0, 'purchase', 'exempt', date '2019-10-01', null, 'Código do IVA, art. 12.º — a purchase of a supply the code exempts, such as bank charges: no tax is charged and the Modelo 7 reports nothing.', null, null, 180, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-EXT-14', 'Serviço adquirido a prestador não residente (14 %), autoliquidado', '{}'::jsonb, 'A service bought abroad; the buyer charges and deducts the tax on the same return', 'percent', 14, 'purchase', 'foreign_services_received', date '2019-10-01', null, 'Código do IVA, art. 29.º — the recipient, a taxable person, accounts for the tax on a service supplied by a provider with no seat, permanent establishment or domicile in Angola. Modelo 7, quadro 9, fields 13 (base), 15 (tax in favour of the State) and 14 (the same tax deductible in favour of the taxpayer): the two net to zero when the right to deduct is complete.', null, null, 200, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-P-IMP-14', 'Importação de bens à taxa geral (14 %), liquidada pela alfândega', '{}'::jsonb, 'Goods imported for home consumption; the customs collect the tax', 'percent', 14, 'purchase', 'import', date '2019-10-01', null, 'Código do IVA, art. 19.º — 14 % on imports; the tax is assessed and collected by the customs services on the import declaration and is deductible. Modelo 7, quadro 9, fields 24 (base) and 25 (deductible tax paid on imports). The tax is owed to customs on account 3791 until paid.', null, null, 190, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-1-CAB', 'Regime especial da província de Cabinda (1 %)', '{}'::jsonb, 'Special regime of Cabinda, 1 % since 1 January 2024', 'percent', 1, 'sale', 'domestic', date '2024-01-01', null, 'Código do IVA, art. 19.º, as republished by the Lei n.º 14/23 — 1 % on imports and supplies of goods subject to the special regime of the province of Cabinda, the goods of Anexo III excepted, which pay the general rate. The page of the Portal do Contribuinte still shows 2 %; the Lei n.º 14/23 prevails. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-14', 'Venda ou serviço à taxa geral (14 %)', '{}'::jsonb, 'The general rate, charged on every taxable supply that no other code of this pack covers', 'percent', 14, 'sale', 'domestic', date '2019-10-01', null, 'Código do IVA, art. 19.º, as republished by the Lei n.º 14/23 — 14 % on imports, supplies of goods and services, the general rate since the VAT replaced the consumption tax on 1 October 2019. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-5', 'Bens alimentares de amplo consumo e insumos agrícolas (5 %)', '{}'::jsonb, 'Reduced rate for the goods of Anexos I and II, since 1 January 2024', 'percent', 5, 'sale', 'domestic', date '2024-01-01', null, 'Código do IVA, art. 19.º, as republished by the Lei n.º 14/23, and its Anexos I and II — 5 % on imports and supplies of widely consumed foodstuffs (meat, fish, milk, eggs, vegetables, fruit, cereals, flour, edible oils, sugar, bread, salt, water) and of agricultural inputs (seeds, fertilisers, tractors, fishing boats); the Ministry of Finance announced the reduction from 7 % on 1 January 2024. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-5-IND', 'Equipamentos industriais do fabricante (5 %)', '{}'::jsonb, 'Industrial equipment supplied by its manufacturer under an approval of the tax administration', 'percent', 5, 'sale', 'domestic', date '2026-01-01', null, 'Lei n.º 14/25 (Orçamento Geral do Estado para 2026), art. 23.º — the VAT rate on the import or supply of industrial equipment by the manufacturer is reduced to 5 %, after a procedure and verification by the tax administration that the equipment is industrial and has the declared purpose. The code is chosen only by a taxpayer who holds that approval. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'oge-2026', null, null, null, null),
  ('AO', 'AO-S-7-CB', 'Cesta básica (7 %) — taxa encerrada em 31/12/2023', '{}'::jsonb, 'Closed rate, kept for the documents dated 2022 and 2023', 'percent', 7, 'sale', 'domestic', date '2022-01-01', date '2023-12-31', 'Orçamento Geral do Estado para 2022 (Lei n.º 32/21) — the temporary 7 % on the goods of the basic basket (sugar, flour, beans, eggs, bread, fish, milk, cooking oil, salt, soap…), reduced from 14 %; it applied from 1 January 2022 until the rate of 5 % replaced it on 1 January 2024, so the code is closed and is kept to read documents of those two years. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'plmj-iva-7', null, null, null, null),
  ('AO', 'AO-S-7-HR', 'Hotelaria e restauração (7 %)', '{}'::jsonb, 'Reduced rate for hotel and restaurant services, in force since 1 January 2024', 'percent', 7, 'sale', 'domestic', date '2024-01-01', null, 'Código do IVA, art. 19.º, as republished by the Lei n.º 14/23 — 7 % on accommodation (hotelaria) and catering (restauração) services. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-7-SIMP', 'Regime simplificado (7 %) — taxa do contribuinte', '{}'::jsonb, 'Charged by a taxpayer of the simplified regime on all its supplies; documented as a separate code, never applied by default', 'percent', 7, 'sale', 'domestic', date '2024-01-01', null, 'Código do IVA, art. 69.º-A and art. 19.º, as republished by the Lei n.º 14/23 — a taxable person whose turnover or imports in the previous year were at least Kz 25,000,000 and under Kz 350,000,000 is in the simplified regime and charges 7 %. This is a rate of the taxpayer''s regime and not of the product: the code is never chosen by default, only by a company in that regime, and the pack does not model the regime''s 10 % input-tax allowance. The page of the Portal do Contribuinte still shows the 3 % of the earlier text; the Lei n.º 14/23 prevails. Modelo 7, quadro 9, line 1 — transactions on which the taxpayer charged tax: field 01 (taxable base) and field 02 (tax in favour of the State).', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-EX', 'Operação interna isenta, sem direito à dedução', '{}'::jsonb, 'Supplies the Código do IVA exempts, such as medicines, education, health care, letting of property and financial services', 'percent', 0, 'sale', 'exempt', date '2019-10-01', null, 'Código do IVA, art. 12.º, as republished by the Lei n.º 14/23 — domestic exemptions: books (also digital), wheelchairs for disabled people, letting of immovable property other than hotel accommodation, transfer of immovable property, collective passenger transport, education by establishments within the Lei de Bases, medical and health services other than aesthetic ones, the medical equipment of Anexo IV, medicines, financial services. Modelo 7, quadro 9, field 11 — exempt without the right to deduct (article 12 excluding its sub-paragraph a).', null, null, 90, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-EX-MOB', 'Pagamentos por plataformas móveis autorizadas, isentos', '{}'::jsonb, 'Fees of a transaction through a payment platform the central bank authorises', 'percent', 0, 'sale', 'exempt', date '2026-01-01', null, 'Lei n.º 14/25 (Orçamento Geral do Estado para 2026), art. 35.º — transactions made through mobile payment and instant transfer platforms duly authorised by the Banco Nacional de Angola are exempt from VAT and stamp duty. Reported with the other exempt supplies, Modelo 7, quadro 9, field 11; the placement in that line is this pack''s reading and is flagged for review in the README.', null, null, 100, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'oge-2026', null, null, null, null),
  ('AO', 'AO-S-EXP', 'Exportação, isenta com direito à dedução', '{}'::jsonb, 'Goods leaving Angola, with the transport evidence the customs require', 'percent', 0, 'sale', 'export', date '2019-10-01', null, 'Código do IVA, art. 15.º — supplies of goods dispatched or transported abroad by the exporter are exempt, with the right to deduct the input tax. Modelo 7, quadro 9, field 10 — transactions on which no tax was charged, exempt with the right to deduct; the specimen of the form lists exports (field 45) as a detail of that line.', null, null, 80, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null),
  ('AO', 'AO-S-NS', 'Operação não tributada (artigo 10.º)', '{}'::jsonb, 'A service rendered to a recipient abroad, outside the scope of the tax', 'percent', 0, 'sale', 'not_subject', date '2019-10-01', null, 'Código do IVA, art. 10.º — operations outside the scope of the tax, such as a service whose place of supply is outside Angola. Modelo 7, quadro 9, field 12 — non-taxed operations.', null, null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'civa-lei-14-23', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('AO-P-14-BL', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('AO-P-14-BL', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('AO-P-14-BL', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('AO-P-14-BL', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('AO-P-14-EXI', 'invoice', 'base', 100, null, '18', array['18']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-14-EXI', 'invoice', 'tax', 100, '34521', '19', array['19']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-14-EXI', 'credit_note', 'base', 100, null, '18', array['18']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-14-EXI', 'credit_note', 'tax', 100, '34521', '19', array['19']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-14-MFI', 'invoice', 'base', 100, null, '16', array['16']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-14-MFI', 'invoice', 'tax', 100, '34522', '17', array['17']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-14-MFI', 'credit_note', 'base', 100, null, '16', array['16']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-14-MFI', 'credit_note', 'tax', 100, '34522', '17', array['17']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-14-OUT', 'invoice', 'base', 100, null, '20', array['20']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-14-OUT', 'invoice', 'tax', 100, '34523', '21', array['21']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-14-OUT', 'credit_note', 'base', 100, null, '20', array['20']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-14-OUT', 'credit_note', 'tax', 100, '34523', '21', array['21']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-14-SERV', 'invoice', 'base', 100, null, '22', array['22']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-14-SERV', 'invoice', 'tax', 100, '34523', '23', array['23']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-14-SERV', 'credit_note', 'base', 100, null, '22', array['22']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-14-SERV', 'credit_note', 'tax', 100, '34523', '23', array['23']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-5-EXI', 'invoice', 'base', 100, null, '18', array['18']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-5-EXI', 'invoice', 'tax', 100, '34521', '19', array['19']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-5-EXI', 'credit_note', 'base', 100, null, '18', array['18']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-5-EXI', 'credit_note', 'tax', 100, '34521', '19', array['19']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-EX', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('AO-P-EX', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('AO-P-EXT-14', 'invoice', 'base', 100, null, '13', array['13']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-EXT-14', 'invoice', 'tax', 100, '34523', '14', array['14']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-EXT-14', 'invoice', 'tax', -100, '34531', '15', array['15']::text[], 100, 'AO-MODELO7', 30),
    ('AO-P-EXT-14', 'credit_note', 'base', 100, null, '13', array['13']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-EXT-14', 'credit_note', 'tax', 100, '34523', '14', array['14']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-EXT-14', 'credit_note', 'tax', -100, '34531', '15', array['15']::text[], -100, 'AO-MODELO7', 30),
    ('AO-P-IMP-14', 'invoice', 'base', 100, null, '24', array['24']::text[], 100, 'AO-MODELO7', 10),
    ('AO-P-IMP-14', 'invoice', 'tax', 100, '34521', '25', array['25']::text[], 100, 'AO-MODELO7', 20),
    ('AO-P-IMP-14', 'invoice', 'tax', -100, '3791', null, null, 100, null, 30),
    ('AO-P-IMP-14', 'credit_note', 'base', 100, null, '24', array['24']::text[], -100, 'AO-MODELO7', 10),
    ('AO-P-IMP-14', 'credit_note', 'tax', 100, '34521', '25', array['25']::text[], -100, 'AO-MODELO7', 20),
    ('AO-P-IMP-14', 'credit_note', 'tax', -100, '3791', null, null, 100, null, 30),
    ('AO-S-1-CAB', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-1-CAB', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-1-CAB', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-1-CAB', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-14', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-14', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-14', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-14', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-5', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-5', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-5', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-5', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-5-IND', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-5-IND', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-5-IND', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-5-IND', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-7-CB', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-7-CB', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-7-CB', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-7-CB', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-7-HR', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-7-HR', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-7-HR', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-7-HR', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-7-SIMP', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-7-SIMP', 'invoice', 'tax', 100, '34531', '2', array['2']::text[], 100, 'AO-MODELO7', 20),
    ('AO-S-7-SIMP', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-7-SIMP', 'credit_note', 'tax', 100, '34531', '2', array['2']::text[], -100, 'AO-MODELO7', 20),
    ('AO-S-EX', 'invoice', 'base', 100, null, '11', array['11']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-EX', 'credit_note', 'base', 100, null, '11', array['11']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-EX-MOB', 'invoice', 'base', 100, null, '11', array['11']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-EX-MOB', 'credit_note', 'base', 100, null, '11', array['11']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-EXP', 'invoice', 'base', 100, null, '10', array['10']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-EXP', 'credit_note', 'base', 100, null, '10', array['10']::text[], -100, 'AO-MODELO7', 10),
    ('AO-S-NS', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'AO-MODELO7', 10),
    ('AO-S-NS', 'credit_note', 'base', 100, null, '12', array['12']::text[], -100, 'AO-MODELO7', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'AO' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('AO', 'AO-MODELO7', 'Declaração Periódica do IVA (Modelo 7)', array['month']::declaration_period[], 'month'::declaration_period, date '2019-10-01', null, 'Código do IVA, art. 44.º — taxable persons submit the periodic declaration by electronic transmission of data, and the system generates the Nota de Liquidação when tax is due. The form is the Modelo 7, filed on the Portal do Contribuinte of the Administração Geral Tributária, with the annexes of suppliers (and of customers where required) and, outside the e-invoicing regime, the SAF-T (AO) files of invoicing. The pack carries the general-regime part of the form (quadro 9, fields 01 to 37); the boxes of the cash-accounting regime and of withheld tax are carried without a tax code that writes into them. Two printings of the form exist (one with fields 26 and 27 headed «regularizações do imposto cativo», one with them headed «regularizações notificadas pela AGT» and an extra field 30); this pack follows the first.', true,'last_day_of_month_after_period'::filing_deadline_rule, null, null, 'Código do IVA, art. 44.º — the declaration is submitted by the last day of the month following the one to which the operations relate, whether or not taxable operations took place; the Modelo 7 itself reads «a submeter até ao último dia de cada mês respeitante às operações realizadas do mês anterior». The tax is paid by the same date through the Nota de Liquidação; some commentaries speak of the last working day, which Ekwo''s rule (the last calendar day) does not see.', 'civa-lei-7-19', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('AO', 'AO-MODELO7', '1', 'base', 'Transmissões e prestações com liquidação de imposto — base tributável', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 01 — the taxable value of the supplies of goods and services on which tax was charged, whatever the rate (14 %, 7 %, 5 % or 1 %); the form has no line per rate.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '2', 'tax', 'Transmissões e prestações com liquidação de imposto — imposto a favor do Estado', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 02 — the tax charged on the supplies of field 01.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '3', 'base', 'Regime de IVA de caixa — base tributável', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 03 — the supplies covered by the cash-accounting regime (Código do IVA, art. 60.º). Not posted by any code of this pack.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '4', 'tax', 'Regime de IVA de caixa — imposto a favor do Estado', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 04 — the tax on the supplies of field 03. Not posted by any code of this pack.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '5', 'base', 'IVA cativo pelo declarante — base tributável', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 05 — operations in which the declarant withheld the tax (art. 21.º). Not posted by any code of this pack.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '6', 'tax', 'IVA cativo pelo declarante — imposto a favor do sujeito passivo', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 06 — the withheld tax deductible by the declarant. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '7', 'tax', 'IVA cativo pelo declarante — imposto a favor do Estado', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 07 — the withheld tax owed to the State. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '8', 'base', 'IVA cativo pelo cliente — base tributável', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 08 — operations in which the customer withheld the tax (art. 31.º). Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '9', 'tax', 'IVA cativo pelo cliente — imposto a favor do sujeito passivo', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 09 — the tax withheld by the customer, in favour of the taxpayer. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '10', 'base', 'Isentas com direito à dedução (exportações)', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 10 — supplies on which no tax was charged, exempt with the right to deduct — exports, whose detail is field 45.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '11', 'base', 'Isentas sem direito à dedução', '{}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 11 — exempt supplies without the right to deduct (art. 12.º, sub-paragraph a excluded).', 'modelo-7'),
  ('AO', 'AO-MODELO7', '12', 'base', 'Não tributadas', '{}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 12 — non-taxed operations (art. 10.º).', 'modelo-7'),
  ('AO', 'AO-MODELO7', '13', 'base', 'Serviços adquiridos a prestador não residente (art. 29.º) — base tributável', '{}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 13 — services bought from a provider with no seat, permanent establishment or domicile in Angola, the tax being charged by the declarant.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '14', 'tax', 'Serviços adquiridos a prestador não residente — imposto a favor do sujeito passivo', '{}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 14 — the self-charged tax deductible by the declarant.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '15', 'tax', 'Serviços adquiridos a prestador não residente — imposto a favor do Estado', '{}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 15 — the tax charged by the declarant on the services of field 13.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '16', 'base', 'Meios fixos e investimentos — base', '{}'::jsonb, 160, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 16 — acquisitions of fixed assets and investments, tax-exclusive.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '17', 'tax', 'Meios fixos e investimentos — imposto dedutível', '{}'::jsonb, 170, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 17 — the deductible tax on the acquisitions of field 16.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '18', 'base', 'Existências — base', '{}'::jsonb, 180, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 18 — acquisitions of inventories, tax-exclusive.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '19', 'tax', 'Existências — imposto dedutível', '{}'::jsonb, 190, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 19 — the deductible tax on the acquisitions of field 18.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '20', 'base', 'Outros bens de consumo — base', '{}'::jsonb, 200, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 20 — acquisitions of other consumable goods, tax-exclusive.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '21', 'tax', 'Outros bens de consumo — imposto dedutível', '{}'::jsonb, 210, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 21 — the deductible tax on the acquisitions of field 20.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '22', 'base', 'Serviços — base', '{}'::jsonb, 220, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 22 — acquisitions of services, tax-exclusive.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '23', 'tax', 'Serviços — imposto dedutível', '{}'::jsonb, 230, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 23 — the deductible tax on the acquisitions of field 22.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '24', 'base', 'Importações de bens — base', '{}'::jsonb, 240, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 24 — imports of goods, at customs value.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '25', 'tax', 'Importações de bens — imposto dedutível', '{}'::jsonb, 250, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 25 — the deductible tax paid on imports.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '26', 'tax', 'Regularizações do imposto cativo — a favor do sujeito passivo', '{}'::jsonb, 260, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 26 — adjustments of withheld tax in favour of the taxpayer. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '27', 'tax', 'Regularizações do imposto cativo — a favor do Estado', '{}'::jsonb, 270, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 27 — adjustments of withheld tax in favour of the State. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '28', 'tax', 'Regularizações mensais ou anuais — a favor do sujeito passivo', '{}'::jsonb, 280, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 28 — monthly or annual adjustments made by the taxpayer, in its favour. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '29', 'tax', 'Regularizações mensais ou anuais — a favor do Estado', '{}'::jsonb, 290, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 29 — monthly or annual adjustments made by the taxpayer, in favour of the State. Not posted.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '31', 'total', 'Soma das bases tributáveis', '{}'::jsonb, 300, null, array['1', '3', '5', '8', '10', '11', '12', '13', '16', '18', '20', '22', '24']::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 31 — the sum of fields 1+3+5+8+10+11+12+13+16+18+20+22+24.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '32', 'total', 'Soma do imposto a favor do sujeito passivo', '{}'::jsonb, 310, null, array['6', '9', '14', '17', '19', '21', '23', '25', '26', '28']::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 32 — the sum of fields 6+9+14+17+19+21+23+25+26+28.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '33', 'total', 'Soma do imposto a favor do Estado', '{}'::jsonb, 320, null, array['2', '4', '7', '15', '27', '29']::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 33 — the sum of fields 2+4+7+15+27+29.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '34', 'total', 'Imposto a recuperar', '{}'::jsonb, 330, null, array['32']::text[], array['33']::text[], null, null, true, false, null, 'Modelo 7, quadro 9, field 34 — field 32 minus field 33 when field 32 is the greater: the credit of the period, carried forward or claimed as a refund (art. 26.º).', 'modelo-7'),
  ('AO', 'AO-MODELO7', '35', 'total', 'Imposto a pagar do período', '{}'::jsonb, 340, null, array['33']::text[], array['32']::text[], null, null, true, false, null, 'Modelo 7, quadro 9, field 35 — field 33 minus field 32 when field 33 is the greater.', 'modelo-7'),
  ('AO', 'AO-MODELO7', '37', 'total', 'IVA a pagar ao Estado', '{}'::jsonb, 350, null, array['35']::text[], '{}'::text[], null, null, false, false, null, 'Modelo 7, quadro 9, field 37 — field 35 minus field 36, the use of credits of earlier periods. Field 36 is a taxpayer input that this pack does not carry, so field 37 equals field 35; the system issues the Nota de Liquidação (art. 44.º).', 'modelo-7')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('AO-PGC-BAL', 'AO', 'default', 'Balanço', 'balance_sheet', 'AO-PGC', date '1970-01-01', null, 'Decreto n.º 82/01 (Plano Geral de Contabilidade), Anexo — modelo de Balanço. The caption wording follows the plan''s balance sheet; the account-to-line mapping is this pack''s selection at the level of detail of the chart, not a transcription field by field of the model, and a balance sheet printed for a filing is prepared from the company''s own notes.', 'pgc-82-01'),
  ('AO-PGC-DR', 'AO', 'default', 'Demonstração de resultados por natureza', 'income_statement', 'AO-PGC', date '1970-01-01', null, 'Decreto n.º 82/01 (Plano Geral de Contabilidade), Anexo — modelo de Demonstração de Resultados por natureza. The account-to-line mapping is this pack''s selection at the level of detail of the chart.', 'pgc-82-01')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('AO-PGC-BAL', 'AI.1', 'ANC', 'Imobilizações corpóreas', '{}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AI.2', 'ANC', 'Imobilizações incorpóreas', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AI.3', 'ANC', 'Investimentos financeiros', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AI.4', 'ANC', 'Imobilizações em curso', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AI.5', 'ANC', 'Amortizações acumuladas', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'ANC', 'ATIVO', 'ACTIVO IMOBILIZADO', '{}'::jsonb, 60, 1, true, array['AI.1', 'AI.2', 'AI.3', 'AI.4', 'AI.5']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AC.1', 'AC', 'Existências', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AC.2', 'AC', 'Clientes', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AC.3', 'AC', 'Estado e outras contas a receber', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AC.4', 'AC', 'Títulos negociáveis', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AC.5', 'AC', 'Depósitos bancários e caixa', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'AC', 'ATIVO', 'ACTIVO CIRCULANTE', '{}'::jsonb, 120, 1, true, array['AC.1', 'AC.2', 'AC.3', 'AC.4', 'AC.5']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'ATIVO', null, 'TOTAL DO ACTIVO', '{}'::jsonb, 130, 1, true, array['ANC', 'AC']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CP.1', 'CP', 'Capital, acções e quotas próprias', '{}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CP.2', 'CP', 'Prémios de emissão e prestações suplementares', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CP.3', 'CP', 'Reservas', '{}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CP.4', 'CP', 'Resultados transitados', '{}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CP.5', 'CP', 'Resultado líquido do exercício', '{}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CP', 'CPP', 'CAPITAL PRÓPRIO', '{}'::jsonb, 190, 1, true, array['CP.1', 'CP.2', 'CP.3', 'CP.4', 'CP.5']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PNC.1', 'PNC', 'Provisões para outros riscos e encargos', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PNC.2', 'PNC', 'Empréstimos de médio e longo prazo', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PNC', 'PT', 'PASSIVO A MÉDIO E LONGO PRAZO', '{}'::jsonb, 220, 1, true, array['PNC.1', 'PNC.2']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PC.1', 'PCT', 'Empréstimos bancários', '{}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PC.2', 'PCT', 'Fornecedores', '{}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PC.3', 'PCT', 'Estado', '{}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PC.4', 'PCT', 'Clientes com saldo credor e outras contas a pagar', '{}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PCT', 'PT', 'PASSIVO A CURTO PRAZO', '{}'::jsonb, 270, 1, true, array['PC.1', 'PC.2', 'PC.3', 'PC.4']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'PT', 'CPP', 'TOTAL DO PASSIVO', '{}'::jsonb, 280, 1, true, array['PNC', 'PCT']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-BAL', 'CPP', null, 'TOTAL DO CAPITAL PRÓPRIO E DO PASSIVO', '{}'::jsonb, 290, 1, true, array['CP', 'PT']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '1', 'A', 'Vendas', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '2', 'A', 'Prestações de serviços', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '3', 'A', 'Outros proveitos operacionais', '{}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '4', 'A', 'Custo das existências vendidas e consumidas', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '5', 'A', 'Custos com o pessoal', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '6', 'A', 'Amortizações do exercício', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '7', 'A', 'Outros custos e perdas operacionais', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', 'A', 'C', 'Resultados operacionais', '{}'::jsonb, 80, 1, true, array['1', '2', '3']::text[], array['4', '5', '6', '7']::text[], null, null, null),
  ('AO-PGC-DR', '8', 'B', 'Proveitos e ganhos financeiros', '{}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '9', 'B', 'Custos e perdas financeiros', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', 'B', 'C', 'Resultados financeiros', '{}'::jsonb, 110, 1, true, array['8']::text[], array['9']::text[], null, null, null),
  ('AO-PGC-DR', '10', 'D', 'Proveitos e ganhos não operacionais', '{}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '11', 'D', 'Custos e perdas não operacionais', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', 'D', 'C', 'Resultados não operacionais', '{}'::jsonb, 140, 1, true, array['10']::text[], array['11']::text[], null, null, null),
  ('AO-PGC-DR', '12', 'E', 'Proveitos e ganhos extraordinários', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '13', 'E', 'Custos e perdas extraordinários', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', 'E', 'C', 'Resultados extraordinários', '{}'::jsonb, 170, 1, true, array['12']::text[], array['13']::text[], null, null, null),
  ('AO-PGC-DR', 'C', 'F', 'Resultado antes de impostos', '{}'::jsonb, 180, 1, true, array['A', 'B', 'D', 'E']::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', '14', 'F', 'Imposto sobre os lucros', '{}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('AO-PGC-DR', 'F', null, 'Resultado líquido do exercício', '{}'::jsonb, 200, 1, true, array['C']::text[], array['14']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('AO-PGC-BAL', 'AI.1', 10, 'code_range', '11', '11', null, 'any'),
    ('AO-PGC-BAL', 'AI.2', 10, 'code_range', '12', '12', null, 'any'),
    ('AO-PGC-BAL', 'AI.3', 10, 'code_range', '13', '13', null, 'any'),
    ('AO-PGC-BAL', 'AI.3', 20, 'code_range', '19', '19', null, 'any'),
    ('AO-PGC-BAL', 'AI.4', 10, 'code_range', '14', '14', null, 'any'),
    ('AO-PGC-BAL', 'AI.5', 10, 'code_range', '18', '18', null, 'any'),
    ('AO-PGC-BAL', 'AC.1', 10, 'code_range', '22', '29', null, 'any'),
    ('AO-PGC-BAL', 'AC.2', 10, 'code_range', '31', '31', null, 'debit'),
    ('AO-PGC-BAL', 'AC.2', 20, 'code_range', '38', '38', null, 'any'),
    ('AO-PGC-BAL', 'AC.3', 10, 'code_range', '32', '32', null, 'debit'),
    ('AO-PGC-BAL', 'AC.3', 20, 'code_range', '34', '34', null, 'debit'),
    ('AO-PGC-BAL', 'AC.3', 30, 'code_range', '35', '35', null, 'debit'),
    ('AO-PGC-BAL', 'AC.3', 40, 'code_range', '36', '36', null, 'debit'),
    ('AO-PGC-BAL', 'AC.3', 50, 'code_range', '37', '37', null, 'debit'),
    ('AO-PGC-BAL', 'AC.4', 10, 'code_range', '41', '41', null, 'any'),
    ('AO-PGC-BAL', 'AC.4', 20, 'code_range', '49', '49', null, 'any'),
    ('AO-PGC-BAL', 'AC.5', 10, 'code_range', '42', '48', null, 'any'),
    ('AO-PGC-BAL', 'CP.1', 10, 'code_range', '51', '52', null, 'any'),
    ('AO-PGC-BAL', 'CP.2', 10, 'code_range', '53', '54', null, 'any'),
    ('AO-PGC-BAL', 'CP.3', 10, 'code_range', '55', '58', null, 'any'),
    ('AO-PGC-BAL', 'CP.4', 10, 'code_range', '81', '81', null, 'any'),
    ('AO-PGC-BAL', 'CP.5', 10, 'code_range', '82', '89', null, 'any'),
    ('AO-PGC-BAL', 'PNC.1', 10, 'code_range', '39', '39', null, 'any'),
    ('AO-PGC-BAL', 'PNC.2', 10, 'code_range', '332', '339', null, 'any'),
    ('AO-PGC-BAL', 'PC.1', 10, 'code_range', '331', '331', null, 'any'),
    ('AO-PGC-BAL', 'PC.2', 10, 'code_range', '32', '32', null, 'credit'),
    ('AO-PGC-BAL', 'PC.3', 10, 'code_range', '34', '34', null, 'credit'),
    ('AO-PGC-BAL', 'PC.4', 10, 'code_range', '31', '31', null, 'credit'),
    ('AO-PGC-BAL', 'PC.4', 20, 'code_range', '35', '35', null, 'credit'),
    ('AO-PGC-BAL', 'PC.4', 30, 'code_range', '36', '36', null, 'credit'),
    ('AO-PGC-BAL', 'PC.4', 40, 'code_range', '37', '37', null, 'credit'),
    ('AO-PGC-DR', '1', 10, 'code_range', '61', '61', null, 'any'),
    ('AO-PGC-DR', '2', 10, 'code_range', '62', '62', null, 'any'),
    ('AO-PGC-DR', '3', 10, 'code_range', '63', '65', null, 'any'),
    ('AO-PGC-DR', '4', 10, 'code_range', '21', '21', null, 'any'),
    ('AO-PGC-DR', '4', 20, 'code_range', '71', '71', null, 'any'),
    ('AO-PGC-DR', '5', 10, 'code_range', '72', '72', null, 'any'),
    ('AO-PGC-DR', '6', 10, 'code_range', '73', '73', null, 'any'),
    ('AO-PGC-DR', '7', 10, 'code_range', '75', '75', null, 'any'),
    ('AO-PGC-DR', '8', 10, 'code_range', '66', '67', null, 'any'),
    ('AO-PGC-DR', '9', 10, 'code_range', '76', '77', null, 'any'),
    ('AO-PGC-DR', '10', 10, 'code_range', '68', '68', null, 'any'),
    ('AO-PGC-DR', '11', 10, 'code_range', '78', '78', null, 'any'),
    ('AO-PGC-DR', '12', 10, 'code_range', '69', '69', null, 'any'),
    ('AO-PGC-DR', '13', 10, 'code_range', '79', '79', null, 'any'),
    ('AO-PGC-DR', '14', 10, 'code_range', '87', '87', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('AO', 'Angola', '{}'::jsonb, array['pt']::text[], 'AOA', '311', '321', '377', '7581', '81', '613', '212', '431', '451', 'VEN', 'COM', 'DIV', 'pt', 'result_accounts', '88', '88', null, 'ABE', 'half_up', default, '662', '762', '683', '783', null, null, '34561', '34571', 'Lançamento de abertura', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Decreto Presidencial n.º 71/25, art. 10.º, n.º 1, alínea b) — an invoice carries a sequential and chronological number by type of document and economic year, in one or more identified series. The style is `sequential` and the number restarts each year, as the format carries the year.',
  numbering_source_key          = 'dp-71-25',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'delivery_date',
  tax_point_legal_reference     = 'Código do IVA (Lei n.º 7/19, as republished by the Lei n.º 14/23), art. 11.º — the tax is due and chargeable when the goods are placed at the disposal of the buyer or when the service is performed; for continuous supplies with periodic payments, at the end of each period. `delivery_date` is the closest value of Ekwo''s vocabulary; the special rules on advances, which the Modelo 7 reports in field 41, are not modelled and are recorded in the README.',
  tax_point_source_key          = 'civa-lei-7-19',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'Angola has no Peppol authority, no published structured-invoice profile and no ISO 6523 scheme a party is addressed by, so `profile`, `party_scheme` and `vat_scheme` are null and `obligation` is `none`. What Angola has instead is a clearance-style system: Decreto Presidencial n.º 71/25, art. 16.º, makes electronic invoicing mandatory for taxpayers of the general and simplified VAT regimes; art. 17.º requires invoicing software validated or provided by the Administração Geral Tributária (AGT) that transmits each invoice to it in real time; art. 37.º phases the obligation in — large taxpayers and suppliers of the State first, from 1 January 2026, then every taxpayer subject to it, from 1 January 2027 as the tax administration announced. That is a real-time reporting of each invoice to the tax administration, not a peer-to-peer exchange between businesses in the sense `einvoicing.profile` describes. Ekwo does not connect to the AGT platform; the gap is recorded in docs/international.md and in this pack''s README.',
  einvoice_source_key           = 'dp-71-25',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'AO';
