-- Ekwo OS — Estonia: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ee at version 1.9.0, do not edit.
-- Change the pack and run `ekwo pack build ee`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Käibemaksuseadus (Riigi Teataja)
--     https://www.riigiteataja.ee/akt/kms
--   Käibemaksuseadus Rahandusministeeriumi kommentaaridega, seisuga jaanuar 2026 — § 27, § 29 ja § 34 (Rahandusministeerium)
--     https://fin.ee/sites/default/files/documents/2026-01/K%C3%A4ibemaksuseaduse%20kommentaarid%20jaanuar%202026.pdf
--   Raamatupidamise seadus (Riigi Teataja)
--     https://www.riigiteataja.ee/akt/rps
--   Nõuded raamatupidamise korraldamiseks ja majandustehingute dokumenteerimiseks — algdokumendid, arved ja e-arved (Rahandusministeerium)
--     https://fin.ee/finantspoliitika-valissuhted/arvestusvaldkond/raamatupidamise-algdokumendid-arved-e-arved
--   Võlaõigusseadus (Riigi Teataja)
--     https://www.riigiteataja.ee/akt/120062026018
--   Rahandusministri 10.06.2014 määrus nr 17 „Käibedeklaratsiooni vorm“, lisa 1 (vorm KMD) ja lisa 2 (vorm KMD INF) (Riigi Teataja)
--     https://www.riigiteataja.ee/akt/130052025008
--   Raamatupidamise Toimkonna juhend RTJ 2 „Nõuded informatsiooni esitusviisile raamatupidamise aastaaruandes“, rahandusministri 22.12.2017 määruse nr 105 lisa 2 (Riigi Teataja)
--     https://www.riigiteataja.ee/akt/119022025012
--   Käibedeklaratsiooni ja aruannete esitamine — vormi KMD ja selle lisa täitmine (Maksu- ja Tolliamet)
--     https://www.emta.ee/ariklient/maksud-ja-tasumine/kaibemaks/kaibedeklaratsiooni-ja-aruannete-esitamine
--   e-MTA — keskkond, kus käibedeklaratsioon esitatakse (Maksu- ja Tolliamet)
--     https://maasikas.emta.ee/
--   EN 16931-1 — Euroopa e-arve semantiline andmemudel ja direktiivist 2014/55/EL tulenev vastavus (Euroopa Komisjon)
--     https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108950/EN+16931+compliance
--   UNCL5305 — käibemaksu kategooria koodide loend (BT-118 ja BT-151), EN 16931 jaoks avaldatud alamhulk (OpenPEPPOL — nimekirja avaldab Euroopa Komisjon)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/
--   VATEX — käibemaksuvabastuse põhjuse koodide loend (BT-121) (OpenPEPPOL — nimekirja avaldab Euroopa Komisjon)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('EE', 'Estonia', '1.9.0', date '2026-09-21', '20260921084143', 'community', null, null, 'a2d09aa1305430e523cc416edfd4a8e25f5a44087a6c69ca1f80ec1d22bdb990', '[{"key":"kms","title":"Käibemaksuseadus","publisher":"Riigi Teataja","url":"https://www.riigiteataja.ee/akt/kms","consulted_on":"2026-09-16","kind":"law"},{"key":"kms-kommentaarid","title":"Käibemaksuseadus Rahandusministeeriumi kommentaaridega, seisuga jaanuar 2026 — § 27, § 29 ja § 34","publisher":"Rahandusministeerium","url":"https://fin.ee/sites/default/files/documents/2026-01/K%C3%A4ibemaksuseaduse%20kommentaarid%20jaanuar%202026.pdf","consulted_on":"2026-09-21","kind":"guidance"},{"key":"rps","title":"Raamatupidamise seadus","publisher":"Riigi Teataja","url":"https://www.riigiteataja.ee/akt/rps","consulted_on":"2026-09-15","kind":"law"},{"key":"e-arved","title":"Nõuded raamatupidamise korraldamiseks ja majandustehingute dokumenteerimiseks — algdokumendid, arved ja e-arved","publisher":"Rahandusministeerium","url":"https://fin.ee/finantspoliitika-valissuhted/arvestusvaldkond/raamatupidamise-algdokumendid-arved-e-arved","consulted_on":"2026-09-21","kind":"guidance"},{"key":"vos","title":"Võlaõigusseadus","publisher":"Riigi Teataja","url":"https://www.riigiteataja.ee/akt/120062026018","consulted_on":"2026-09-15","kind":"law"},{"key":"kmd-vorm","title":"Rahandusministri 10.06.2014 määrus nr 17 „Käibedeklaratsiooni vorm“, lisa 1 (vorm KMD) ja lisa 2 (vorm KMD INF)","publisher":"Riigi Teataja","url":"https://www.riigiteataja.ee/akt/130052025008","consulted_on":"2026-09-15","kind":"regulation"},{"key":"rtj-2","title":"Raamatupidamise Toimkonna juhend RTJ 2 „Nõuded informatsiooni esitusviisile raamatupidamise aastaaruandes“, rahandusministri 22.12.2017 määruse nr 105 lisa 2","publisher":"Riigi Teataja","url":"https://www.riigiteataja.ee/akt/119022025012","consulted_on":"2026-09-15","kind":"guidance"},{"key":"kmd-esitamine","title":"Käibedeklaratsiooni ja aruannete esitamine — vormi KMD ja selle lisa täitmine","publisher":"Maksu- ja Tolliamet","url":"https://www.emta.ee/ariklient/maksud-ja-tasumine/kaibemaks/kaibedeklaratsiooni-ja-aruannete-esitamine","consulted_on":"2026-09-15","kind":"form"},{"key":"e-mta","title":"e-MTA — keskkond, kus käibedeklaratsioon esitatakse","publisher":"Maksu- ja Tolliamet","url":"https://maasikas.emta.ee/","consulted_on":"2026-09-15","kind":"portal"},{"key":"en-16931","title":"EN 16931-1 — Euroopa e-arve semantiline andmemudel ja direktiivist 2014/55/EL tulenev vastavus","publisher":"Euroopa Komisjon","url":"https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108950/EN+16931+compliance","consulted_on":"2026-09-15","kind":"standard"},{"key":"uncl5305","title":"UNCL5305 — käibemaksu kategooria koodide loend (BT-118 ja BT-151), EN 16931 jaoks avaldatud alamhulk","publisher":"OpenPEPPOL — nimekirja avaldab Euroopa Komisjon","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/","consulted_on":"2026-09-15","kind":"standard"},{"key":"vatex","title":"VATEX — käibemaksuvabastuse põhjuse koodide loend (BT-121)","publisher":"OpenPEPPOL — nimekirja avaldab Euroopa Komisjon","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/","consulted_on":"2026-09-15","kind":"standard"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('EE', 'default', 'Eesti väikeettevõtja kontoplaan', '{"en":"Estonian chart of accounts for small and medium-sized entities"}'::jsonb, true, 'companies', array['EE-RPS-BS', 'EE-RPS-IS1']::text[], null, 'Raamatupidamise seadus § 8 — Eestis ei ole seadusega kehtestatud kontoplaani, vaid iga raamatupidamiskohustuslane koostab oma kontoplaani. Käesolev kontoplaan on originaalne ja järgib Eesti tava nelja klassi ning neljakohaliste kontonumbritega, liigendatuna raamatupidamise seaduse lisade 1 ja 2 kirjete järgi.', 'rps')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('EE', 'default', '1000', 'Kassa', '{"en":"Cash"}'::jsonb, 'asset_cash', false, null, 10),
  ('EE', 'default', '1010', 'Arvelduskonto pangas', '{"en":"Bank current account"}'::jsonb, 'asset_cash', false, null, 20),
  ('EE', 'default', '1020', 'Arvelduskonto pangas välisvaluutas', '{"en":"Bank current account in foreign currency"}'::jsonb, 'asset_cash', false, null, 30),
  ('EE', 'default', '1080', 'Raha teel', '{"en":"Cash in transit"}'::jsonb, 'asset_cash', false, null, 40),
  ('EE', 'default', '1100', 'Lühiajalised finantsinvesteeringud', '{"en":"Short-term financial investments"}'::jsonb, 'asset_current', false, null, 50),
  ('EE', 'default', '1200', 'Nõuded ostjate vastu', '{"en":"Trade receivables"}'::jsonb, 'asset_receivable', true, null, 60),
  ('EE', 'default', '1208', 'Ebatõenäoliselt laekuvad nõuded', '{"en":"Allowance for doubtful receivables"}'::jsonb, 'asset_current', false, null, 70),
  ('EE', 'default', '1210', 'Maksude ettemaksed ja tagasinõuded', '{"en":"Prepaid and refundable taxes"}'::jsonb, 'asset_current', false, null, 80),
  ('EE', 'default', '1211', 'Käibemaksu tagasinõue — esitatud deklaratsiooni saldo', '{"en":"VAT refund claim — balance of a filed return"}'::jsonb, 'asset_current', true, null, 85),
  ('EE', 'default', '1220', 'Nõuded seotud osapoolte vastu', '{"en":"Receivables from related parties"}'::jsonb, 'asset_current', false, null, 90),
  ('EE', 'default', '1230', 'Lühiajalised laenunõuded', '{"en":"Short-term loan receivables"}'::jsonb, 'asset_current', false, null, 100),
  ('EE', 'default', '1240', 'Muud lühiajalised nõuded', '{"en":"Other short-term receivables"}'::jsonb, 'asset_current', false, null, 110),
  ('EE', 'default', '1250', 'Ettemaksed tarnijatele', '{"en":"Prepayments to suppliers"}'::jsonb, 'asset_prepayments', false, null, 120),
  ('EE', 'default', '1260', 'Tulevaste perioodide kulud', '{"en":"Deferred expenses"}'::jsonb, 'asset_prepayments', false, null, 130),
  ('EE', 'default', '1300', 'Tooraine ja materjal', '{"en":"Raw materials"}'::jsonb, 'asset_current', false, null, 140),
  ('EE', 'default', '1310', 'Lõpetamata toodang', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, null, 150),
  ('EE', 'default', '1320', 'Valmistoodang', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, null, 160),
  ('EE', 'default', '1330', 'Müügiks ostetud kaubad', '{"en":"Goods for resale"}'::jsonb, 'asset_current', false, null, 170),
  ('EE', 'default', '1340', 'Ettemaksed varude eest', '{"en":"Prepayments for inventories"}'::jsonb, 'asset_prepayments', false, null, 180),
  ('EE', 'default', '1500', 'Tütarettevõtjate aktsiad ja osad', '{"en":"Shares of subsidiaries"}'::jsonb, 'asset_non_current', false, null, 190),
  ('EE', 'default', '1510', 'Sidusettevõtjate aktsiad ja osad', '{"en":"Shares of affiliated undertakings"}'::jsonb, 'asset_non_current', false, null, 200),
  ('EE', 'default', '1600', 'Pikaajalised finantsinvesteeringud', '{"en":"Long-term financial investments"}'::jsonb, 'asset_non_current', false, null, 210),
  ('EE', 'default', '1650', 'Pikaajalised nõuded ja ettemaksed', '{"en":"Long-term receivables and prepayments"}'::jsonb, 'asset_non_current', false, null, 220),
  ('EE', 'default', '1700', 'Kinnisvarainvesteeringud', '{"en":"Investment properties"}'::jsonb, 'asset_fixed', false, null, 230),
  ('EE', 'default', '1750', 'Maa', '{"en":"Land"}'::jsonb, 'asset_fixed', false, null, 240),
  ('EE', 'default', '1760', 'Ehitised', '{"en":"Buildings"}'::jsonb, 'asset_fixed', false, null, 250),
  ('EE', 'default', '1765', 'Ehitiste akumuleeritud kulum', '{"en":"Accumulated depreciation of buildings"}'::jsonb, 'asset_fixed', false, null, 260),
  ('EE', 'default', '1770', 'Masinad ja seadmed', '{"en":"Machinery and equipment"}'::jsonb, 'asset_fixed', false, null, 270),
  ('EE', 'default', '1775', 'Masinate ja seadmete akumuleeritud kulum', '{"en":"Accumulated depreciation of machinery and equipment"}'::jsonb, 'asset_fixed', false, null, 280),
  ('EE', 'default', '1780', 'Muu materiaalne põhivara', '{"en":"Other tangible fixed assets"}'::jsonb, 'asset_fixed', false, null, 290),
  ('EE', 'default', '1785', 'Muu materiaalse põhivara akumuleeritud kulum', '{"en":"Accumulated depreciation of other tangible fixed assets"}'::jsonb, 'asset_fixed', false, null, 300),
  ('EE', 'default', '1790', 'Lõpetamata projektid ja ettemaksed põhivara eest', '{"en":"Construction in progress and prepayments for fixed assets"}'::jsonb, 'asset_fixed', false, null, 310),
  ('EE', 'default', '1900', 'Arenguväljaminekud', '{"en":"Development expenditure"}'::jsonb, 'asset_fixed', false, null, 320),
  ('EE', 'default', '1905', 'Arenguväljaminekute akumuleeritud kulum', '{"en":"Accumulated amortisation of development expenditure"}'::jsonb, 'asset_fixed', false, null, 330),
  ('EE', 'default', '1910', 'Tarkvara ja litsentsid', '{"en":"Software and licences"}'::jsonb, 'asset_fixed', false, null, 340),
  ('EE', 'default', '1915', 'Tarkvara ja litsentside akumuleeritud kulum', '{"en":"Accumulated amortisation of software and licences"}'::jsonb, 'asset_fixed', false, null, 350),
  ('EE', 'default', '1950', 'Firmaväärtus', '{"en":"Goodwill"}'::jsonb, 'asset_fixed', false, null, 360),
  ('EE', 'default', '1955', 'Firmaväärtuse akumuleeritud kulum', '{"en":"Accumulated amortisation of goodwill"}'::jsonb, 'asset_fixed', false, null, 370),
  ('EE', 'default', '2000', 'Lühiajalised laenukohustised', '{"en":"Short-term loan liabilities"}'::jsonb, 'liability_current', false, null, 380),
  ('EE', 'default', '2010', 'Pikaajaliste laenukohustiste lühiajaline osa', '{"en":"Current portion of long-term loan liabilities"}'::jsonb, 'liability_current', false, null, 390),
  ('EE', 'default', '2020', 'Kapitalirendikohustise lühiajaline osa', '{"en":"Current portion of finance lease liabilities"}'::jsonb, 'liability_current', false, null, 400),
  ('EE', 'default', '2100', 'Võlad tarnijatele', '{"en":"Trade creditors"}'::jsonb, 'liability_payable', true, null, 410),
  ('EE', 'default', '2200', 'Palgavõlg', '{"en":"Wages and salaries payable"}'::jsonb, 'liability_current', false, null, 420),
  ('EE', 'default', '2210', 'Puhkusetasu kohustis', '{"en":"Holiday pay liability"}'::jsonb, 'liability_current', false, null, 430),
  ('EE', 'default', '2310', 'Müügi käibemaks', '{"en":"Output VAT"}'::jsonb, 'liability_current', false, null, 440),
  ('EE', 'default', '2311', 'Sisendkäibemaks', '{"en":"Input VAT"}'::jsonb, 'asset_current', false, null, 450),
  ('EE', 'default', '2320', 'Sotsiaalmaksu kohustis', '{"en":"Social tax payable"}'::jsonb, 'liability_current', false, null, 460),
  ('EE', 'default', '2330', 'Kinnipeetud tulumaksu kohustis', '{"en":"Withheld income tax payable"}'::jsonb, 'liability_current', false, null, 470),
  ('EE', 'default', '2340', 'Töötuskindlustusmakse kohustis', '{"en":"Unemployment insurance premium payable"}'::jsonb, 'liability_current', false, null, 480),
  ('EE', 'default', '2350', 'Kogumispensioni makse kohustis', '{"en":"Funded pension payment payable"}'::jsonb, 'liability_current', false, null, 490),
  ('EE', 'default', '2360', 'Tulumaksukohustis', '{"en":"Income tax payable"}'::jsonb, 'liability_current', false, null, 500),
  ('EE', 'default', '2370', 'Käibemaksukohustis — esitatud deklaratsiooni saldo', '{"en":"VAT payable — balance of a filed return"}'::jsonb, 'liability_current', true, null, 505),
  ('EE', 'default', '2400', 'Muud lühiajalised võlad', '{"en":"Other current payables"}'::jsonb, 'liability_current', false, null, 510),
  ('EE', 'default', '2410', 'Võlad seotud osapooltele', '{"en":"Payables to related parties"}'::jsonb, 'liability_current', false, null, 520),
  ('EE', 'default', '2490', 'Selgitamata maksed', '{"en":"Unidentified payments"}'::jsonb, 'liability_current', false, null, 530),
  ('EE', 'default', '2500', 'Ostjate ettemaksed', '{"en":"Prepayments from customers"}'::jsonb, 'liability_current', false, null, 540),
  ('EE', 'default', '2510', 'Tulevaste perioodide tulud', '{"en":"Prepaid revenues"}'::jsonb, 'liability_current', false, null, 550),
  ('EE', 'default', '2600', 'Lühiajalised eraldised', '{"en":"Short-term provisions"}'::jsonb, 'liability_current', false, null, 560),
  ('EE', 'default', '2700', 'Lühiajaline sihtfinantseerimine', '{"en":"Short-term targeted financing"}'::jsonb, 'liability_current', false, null, 570),
  ('EE', 'default', '2750', 'Pikaajalised laenukohustised', '{"en":"Long-term loan liabilities"}'::jsonb, 'liability_non_current', false, null, 580),
  ('EE', 'default', '2760', 'Muud pikaajalised võlad', '{"en":"Other long-term payables"}'::jsonb, 'liability_non_current', false, null, 590),
  ('EE', 'default', '2770', 'Pikaajalised eraldised', '{"en":"Long-term provisions"}'::jsonb, 'liability_non_current', false, null, 600),
  ('EE', 'default', '2780', 'Pikaajaline sihtfinantseerimine', '{"en":"Long-term targeted financing"}'::jsonb, 'liability_non_current', false, null, 610),
  ('EE', 'default', '2900', 'Osakapital nimiväärtuses', '{"en":"Share capital in nominal value"}'::jsonb, 'equity', false, null, 620),
  ('EE', 'default', '2905', 'Registreerimata osakapital', '{"en":"Unregistered share capital"}'::jsonb, 'equity', false, null, 630),
  ('EE', 'default', '2910', 'Sissemaksmata osakapital', '{"en":"Unpaid share capital"}'::jsonb, 'equity', false, null, 640),
  ('EE', 'default', '2920', 'Ülekurss', '{"en":"Share premium account"}'::jsonb, 'equity', false, null, 650),
  ('EE', 'default', '2930', 'Oma aktsiad või osad', '{"en":"Own shares"}'::jsonb, 'equity', false, null, 660),
  ('EE', 'default', '2940', 'Kohustuslik reservkapital', '{"en":"Legal reserve"}'::jsonb, 'equity', false, null, 670),
  ('EE', 'default', '2950', 'Muud reservid', '{"en":"Other reserves"}'::jsonb, 'equity', false, null, 680),
  ('EE', 'default', '2960', 'Muu omakapital', '{"en":"Other owners'' equity"}'::jsonb, 'equity', false, null, 690),
  ('EE', 'default', '2970', 'Eelmiste perioodide jaotamata kasum (kahjum)', '{"en":"Retained profit (loss)"}'::jsonb, 'equity_retained', false, null, 700),
  ('EE', 'default', '2980', 'Aruandeaasta kasum (kahjum)', '{"en":"Profit (loss) for accounting year"}'::jsonb, 'equity_retained', false, null, 710),
  ('EE', 'default', '3000', 'Kauba müük Eestis', '{"en":"Sale of goods in Estonia"}'::jsonb, 'income', false, null, 720),
  ('EE', 'default', '3010', 'Teenuse müük Eestis', '{"en":"Sale of services in Estonia"}'::jsonb, 'income', false, null, 730),
  ('EE', 'default', '3020', 'Kauba müük Euroopa Liitu', '{"en":"Sale of goods to the European Union"}'::jsonb, 'income', false, null, 740),
  ('EE', 'default', '3030', 'Teenuse müük Euroopa Liitu', '{"en":"Sale of services to the European Union"}'::jsonb, 'income', false, null, 750),
  ('EE', 'default', '3040', 'Kauba eksport', '{"en":"Export of goods"}'::jsonb, 'income', false, null, 760),
  ('EE', 'default', '3050', 'Teenuse eksport', '{"en":"Export of services"}'::jsonb, 'income', false, null, 770),
  ('EE', 'default', '3060', 'Majutusteenuse müük', '{"en":"Sale of accommodation services"}'::jsonb, 'income', false, null, 780),
  ('EE', 'default', '3070', 'Maksuvaba käive', '{"en":"Supply exempt from tax"}'::jsonb, 'income', false, null, 790),
  ('EE', 'default', '3100', 'Muud äritulud', '{"en":"Other operating revenue"}'::jsonb, 'income_other', false, null, 800),
  ('EE', 'default', '3110', 'Kasum põhivara müügist', '{"en":"Gain on disposal of fixed assets"}'::jsonb, 'income_other', false, null, 810),
  ('EE', 'default', '3200', 'Valmis- ja lõpetamata toodangu varude jääkide muutus', '{"en":"Changes in inventories of finished goods and work in progress"}'::jsonb, 'income_other', false, null, 820),
  ('EE', 'default', '3250', 'Kapitaliseeritud väljaminekud oma tarbeks põhivarade valmistamisel', '{"en":"Capitalised expenditure when manufacturing fixed assets for own purposes"}'::jsonb, 'income_other', false, null, 830),
  ('EE', 'default', '3800', 'Intressitulud', '{"en":"Interest income"}'::jsonb, 'income_other', false, null, 840),
  ('EE', 'default', '3810', 'Kasum (kahjum) finantsinvesteeringutelt', '{"en":"Profit (loss) from financial investments"}'::jsonb, 'income_other', false, null, 850),
  ('EE', 'default', '3820', 'Muud finantstulud', '{"en":"Other financial income"}'::jsonb, 'income_other', false, null, 860),
  ('EE', 'default', '3830', 'Kasum (kahjum) tütarettevõtjatelt', '{"en":"Profit (loss) from subsidiaries"}'::jsonb, 'income_other', false, null, 870),
  ('EE', 'default', '3840', 'Kasum (kahjum) sidusettevõtjatelt', '{"en":"Profit (loss) from affiliated undertakings"}'::jsonb, 'income_other', false, null, 880),
  ('EE', 'default', '3850', 'Valuutakursi kasum', '{"en":"Foreign exchange gain"}'::jsonb, 'income_other', false, null, 890),
  ('EE', 'default', '4000', 'Müüdud kaupade kulu', '{"en":"Cost of goods sold"}'::jsonb, 'expense_direct_cost', false, null, 900),
  ('EE', 'default', '4010', 'Tooraine ja materjali kulu', '{"en":"Cost of raw materials"}'::jsonb, 'expense_direct_cost', false, null, 910),
  ('EE', 'default', '4020', 'Ostetud teenused', '{"en":"Purchased services"}'::jsonb, 'expense_direct_cost', false, null, 920),
  ('EE', 'default', '4100', 'Ruumide kulud', '{"en":"Premises costs"}'::jsonb, 'expense', false, null, 930),
  ('EE', 'default', '4110', 'Energia', '{"en":"Energy"}'::jsonb, 'expense', false, null, 940),
  ('EE', 'default', '4120', 'Side- ja infotehnoloogiakulud', '{"en":"Communication and information technology costs"}'::jsonb, 'expense', false, null, 950),
  ('EE', 'default', '4130', 'Sõidukikulud', '{"en":"Vehicle costs"}'::jsonb, 'expense', false, null, 960),
  ('EE', 'default', '4140', 'Lähetuskulud', '{"en":"Travel costs"}'::jsonb, 'expense', false, null, 970),
  ('EE', 'default', '4150', 'Reklaami- ja turunduskulud', '{"en":"Advertising and marketing costs"}'::jsonb, 'expense', false, null, 980),
  ('EE', 'default', '4160', 'Bürookulud', '{"en":"Office costs"}'::jsonb, 'expense', false, null, 990),
  ('EE', 'default', '4170', 'Konsultatsiooni- ja õigusabikulud', '{"en":"Consultancy and legal costs"}'::jsonb, 'expense', false, null, 1000),
  ('EE', 'default', '4180', 'Koolituskulud', '{"en":"Training costs"}'::jsonb, 'expense', false, null, 1010),
  ('EE', 'default', '4190', 'Kindlustus', '{"en":"Insurance"}'::jsonb, 'expense', false, null, 1020),
  ('EE', 'default', '4200', 'Pangateenused', '{"en":"Bank charges"}'::jsonb, 'expense', false, null, 1030),
  ('EE', 'default', '4210', 'Esinduskulud', '{"en":"Entertainment costs"}'::jsonb, 'expense', false, null, 1040),
  ('EE', 'default', '4220', 'Muud mitmesugused tegevuskulud', '{"en":"Other miscellaneous operating expenses"}'::jsonb, 'expense', false, null, 1050),
  ('EE', 'default', '4700', 'Palgakulu', '{"en":"Wages and salaries"}'::jsonb, 'expense', false, null, 1060),
  ('EE', 'default', '4710', 'Sotsiaalmaks', '{"en":"Social tax"}'::jsonb, 'expense', false, null, 1070),
  ('EE', 'default', '4720', 'Töötuskindlustusmakse (tööandja)', '{"en":"Unemployment insurance premium (employer)"}'::jsonb, 'expense', false, null, 1080),
  ('EE', 'default', '4730', 'Erisoodustused', '{"en":"Fringe benefits"}'::jsonb, 'expense', false, null, 1090),
  ('EE', 'default', '4740', 'Erisoodustuste maksud', '{"en":"Taxes on fringe benefits"}'::jsonb, 'expense', false, null, 1100),
  ('EE', 'default', '4800', 'Põhivarade kulum', '{"en":"Depreciation of fixed assets"}'::jsonb, 'expense_depreciation', false, null, 1110),
  ('EE', 'default', '4810', 'Põhivarade väärtuse langus', '{"en":"Impairment of fixed assets"}'::jsonb, 'expense_depreciation', false, null, 1120),
  ('EE', 'default', '4850', 'Olulised käibevara allahindlused', '{"en":"Significant write-downs of current assets"}'::jsonb, 'expense', false, null, 1130),
  ('EE', 'default', '4900', 'Muud ärikulud', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, null, 1140),
  ('EE', 'default', '4910', 'Kahjum põhivara müügist', '{"en":"Loss on disposal of fixed assets"}'::jsonb, 'expense', false, null, 1150),
  ('EE', 'default', '4920', 'Ümardamise vahed', '{"en":"Rounding differences"}'::jsonb, 'expense', false, null, 1160),
  ('EE', 'default', '4950', 'Intressikulud', '{"en":"Interest expenses"}'::jsonb, 'expense', false, null, 1170),
  ('EE', 'default', '4960', 'Muud finantskulud', '{"en":"Other financial expenses"}'::jsonb, 'expense', false, null, 1180),
  ('EE', 'default', '4970', 'Valuutakursi kahjum', '{"en":"Foreign exchange loss"}'::jsonb, 'expense', false, null, 1190),
  ('EE', 'default', '4990', 'Tulumaks', '{"en":"Income tax"}'::jsonb, 'expense', false, null, 1200)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('EE', 'ALG', 'Algsaldode päevik', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('EE', 'KAS', 'Kassapäevik', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('EE', 'MIS', 'Muud kanded', '{"en":"General journal"}'::jsonb, 'general', 50),
  ('EE', 'MUU', 'Müügipäevik', '{"en":"Sales journal"}'::jsonb, 'sales', 10),
  ('EE', 'OST', 'Ostupäevik', '{"en":"Purchase journal"}'::jsonb, 'purchase', 20),
  ('EE', 'PNK', 'Pangapäevik', '{"en":"Bank journal"}'::jsonb, 'bank', 30)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('EE', 'EE-P-09', 'Soetamine 9%', '{"en":"Acquisition 9%"}'::jsonb, 'Raamat, ravim, meditsiiniseade, ajakirjandusväljaanne', 'percent', 9, 'purchase', 'domestic', date '2009-01-01', null, 'KMS § 15 lg 2 ja § 29 lg 1', 'S', null, 180, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-13-MAJ', 'Majutuse soetamine 13%', '{"en":"Acquisition of accommodation 13%"}'::jsonb, 'Lähetusega seotud majutus on mahaarvatav', 'percent', 13, 'purchase', 'domestic', date '2025-01-01', null, 'KMS § 15 lg 1¹ ja § 30 lg 2 — töölähetusega seoses saadud majutusteenuse sisendkäibemaks on mahaarvatav', 'S', null, 190, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-20', 'Soetamine 20%', '{"en":"Acquisition 20%"}'::jsonb, 'Standardmäär 01.07.2009–31.12.2023', 'percent', 20, 'purchase', 'domestic', date '2009-07-01', date '2023-12-31', 'KMS § 15 lg 1, redaktsioon RT I 2009, 35, 232', 'S', null, 170, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-22', 'Soetamine 22%', '{"en":"Acquisition 22%"}'::jsonb, 'Standardmäär 01.01.2024–30.06.2025', 'percent', 22, 'purchase', 'domestic', date '2024-01-01', date '2025-06-30', 'KMS § 15 lg 1, redaktsioon RT I, 01.07.2023, 2', 'S', null, 160, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-24-K', 'Kauba soetamine 24%', '{"en":"Acquisition of goods 24%"}'::jsonb, 'Riigisisene soetamine, täielik mahaarvamine', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 15 lg 1 ja § 29 lg 1 — arvestatud käibemaksust arvatakse maha sisendkäibemaks', 'S', null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-24-P', 'Põhivara soetamine 24%', '{"en":"Acquisition of fixed assets 24%"}'::jsonb, 'Vormi KMD lahtris 5.2 eraldi näidatav sisendkäibemaks', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 15 lg 1 ja § 32 lg 4 — põhivara sisendkäibemaks, mida korrigeeritakse põhivara kasutusaja jooksul; vormil KMD lahter 5.2', 'S', null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-24-T', 'Teenuse soetamine 24%', '{"en":"Acquisition of services 24%"}'::jsonb, 'Riigisisene soetamine, täielik mahaarvamine', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 15 lg 1 ja § 29 lg 1', 'S', null, 140, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-ICG-24', 'Kauba ühendusesisene soetamine 24%', '{"en":"Intra-Community acquisition of goods 24%"}'::jsonb, 'Pöördmaksustamine, lahtrid 6.1, 4 ja 5', 'percent', 24, 'purchase', 'intracom_acquisition_goods', date '2025-07-01', null, 'KMS § 8 ja § 3 lg 4 — soetaja arvestab käibemaksu ise; § 29 lg 3 p 4 — arvestatud käibemaks on sisendkäibemaks; § 31 lg 2 — mahaarvamiseks ei ole arve nõutav', 'K', 'VATEX-EU-IC', 200, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-ICS-24', 'Teenuse saamine teise liikmesriigi maksukohustuslaselt 24%', '{"en":"Services received from a taxable person of another Member State 24%"}'::jsonb, 'Pöördmaksustamine, lahtrid 6, 4 ja 5', 'percent', 24, 'purchase', 'intracom_acquisition_services', date '2025-07-01', null, 'KMS § 10 lg 1 ja § 3 lg 4 p 2 — teenuse saaja arvestab käibemaksu; § 29 lg 3 p 3; § 31 lg 3 — mahaarvamiseks ei ole arve nõutav. KMS § 3 lg 7 — arvestamiskohustust ei teki, kui teise liikmesriigi müüja kohaldab väikeettevõtja erikorda ja tema number kannab lõppu „EX“.', 'K', 'VATEX-EU-IC', 210, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-IMP-24', 'Kauba import 24%, käibemaks deklaratsioonis', '{"en":"Import of goods 24%, VAT accounted for in the return"}'::jsonb, 'Maksuhalduri loal deklareeritakse impordi käibemaks lahtrites 4¹ ja 5.1', 'percent', 24, 'purchase', 'import', date '2025-07-01', null, 'KMS § 38 lg 2¹–2³ — maksuhalduri kirjalikul loal deklareeritakse impordilt arvestatav käibemaks käibedeklaratsioonis; § 29 lg 3 p 2 ja § 31 lg 4 ja 8. Vormil KMD ei ole impordi maksustatava väärtuse lahtrit: väärtus on tollideklaratsioonil.', null, null, 240, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-ND-24', 'Mahaarvamisõiguseta soetamine 24%', '{"en":"Acquisition with no right of deduction 24%"}'::jsonb, 'Külaliste vastuvõtu ning töötajate toitlustamise ja majutuse kulud: kogu käibemaks järgib rea kontot.', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 30 lg 1 — sisendkäibemaksu ei arvata maha külaliste vastuvõtuks ning töötajate toitlustamiseks või majutamiseks soetatud kaubalt ja teenuselt', 'S', null, 280, 'vat', false, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-PM-24', 'Erikorra alusel maksustatava kauba soetamine 24% (§ 41¹)', '{"en":"Acquisition under the special arrangements 24% (VAT Act § 41¹)"}'::jsonb, 'Kinnisasi, metallijäätmed, väärismetall ja metalltooted: lahtrid 7.1, 1, 4 ja 5', 'percent', 24, 'purchase', 'domestic_reverse_charge', date '2025-07-01', null, 'KMS § 41¹ lg 3 ja 4 — soetaja kajastab maksustatava väärtuse ja käibemaksu arve saamise maksustamisperioodil ning arvab sisendkäibemaksu maha samal perioodil', 'AE', 'VATEX-EU-AE', 230, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-SA-24-K', 'Sõiduauto tarbeks kaupade ja teenuste soetamine 24% — mahaarvamine 50%', '{"en":"Goods and services for a passenger car 24% — 50% deduction"}'::jsonb, 'Kütus, hooldus, remont, rent ja parkimine. Mahaarvamata käibemaks järgib rea kontot.', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 30 lg 3 — sama piirang sõiduauto tarbeks kaupade soetamisel ja teenuste saamisel. Vormil KMD lahter 5.4.', 'S', null, 260, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-SA-24-P', 'Sõiduauto soetamine 24% — mahaarvamine 50%', '{"en":"Acquisition of a passenger car 24% — 50% deduction"}'::jsonb, 'Osaliselt ettevõtluses kasutatav sõiduauto. Mahaarvamata käibemaks järgib rea kontot.', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 30 lg 3 — sõiduauto ettevõtluse tarbeks soetamisel arvatakse maha 50 protsenti sisendkäibemaksust; § 2 lg 12 määratleb sõiduauto; § 30 lg 4 loetleb erandid. Vormil KMD lahter 5.4.', 'S', null, 250, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-SA100-24', 'Sõiduauto 100% ettevõtluses 24%', '{"en":"Passenger car used wholly for business 24%"}'::jsonb, 'KMS § 30 lg 4 p 3–5 erand: mahaarvamine täies ulatuses, vormil KMD lahter 5.3', 'percent', 24, 'purchase', 'domestic', date '2025-07-01', null, 'KMS § 30 lg 4 p 3–5 — takso, sõiduõpe ja üksnes ettevõtluses kasutatav sõiduauto; § 30 lg 7 — kaheaastane kasutamise tingimus; § 30 lg 9 — maksukohustuslane peab tagama, et autot muul otstarbel ei kasutata. Vormil KMD lahter 5.3.', 'S', null, 270, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-VABA', 'Maksuvaba soetamine', '{"en":"Acquisition exempt from tax"}'::jsonb, 'Arve ilma käibemaksuta', 'percent', 0, 'purchase', 'exempt', date '2004-05-01', null, 'KMS § 16 — maksuvaba käive; soetaja arvel käibemaksu ei ole', 'E', 'VATEX-EU-132', 290, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-P-VS-24', 'Teenuse saamine ühendusevälise isikult 24%', '{"en":"Services received from a person outside the Union 24%"}'::jsonb, 'Pöördmaksustamine, lahtrid 7, 4 ja 5', 'percent', 24, 'purchase', 'foreign_services_received', date '2025-07-01', null, 'KMS § 3 lg 4 p 2 ja § 10 lg 1 — teenuse saamine ettevõtlusega tegelevalt välisriigi isikult, kes ei ole Eestis registreeritud; § 29 lg 3 p 3. Nõukogu direktiivi 2006/112/EÜ artiklid 44 ja 196.', null, null, 220, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-00-EXP', 'Kauba eksport', '{"en":"Export of goods"}'::jsonb, 'Maksustatav 0% määraga', 'percent', 0, 'sale', 'export', date '2004-05-01', null, 'KMS § 15 lg 3 p 1 — kauba eksport; § 37 lg 8 p 1 viimane lause vabastab ekspordiarve maksumäära aluse viitamise kohustusest', 'G', 'VATEX-EU-G', 100, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-00-ICG', 'Kauba ühendusesisene käive', '{"en":"Intra-Community supply of goods"}'::jsonb, 'Maksustatav 0% määraga', 'percent', 0, 'sale', 'intracom_goods', date '2004-05-01', null, 'KMS § 15 lg 3 p 2 ja § 7 lg 1 — kauba ühendusesisene käive; § 15 lg 3¹ seab tingimuseks soetaja kehtiva maksukohustuslasena registreerimise numbri ja ühendusesisese käibe aruandes kajastamise', 'K', 'VATEX-EU-IC', 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-00-ICS', 'Teenuse käive teise liikmesriigi maksukohustuslasele', '{"en":"Supply of services to a taxable person of another Member State"}'::jsonb, 'Pöördmaksustamine saaja poolt', 'percent', 0, 'sale', 'intracom_services', date '2010-01-01', null, 'KMS § 10 lg 4 p 9 ja § 15 lg 4 p 1 — teenus, mille käibe tekkimise koht ei ole Eesti; nõukogu direktiivi 2006/112/EÜ artiklid 44 ja 196', 'K', 'VATEX-EU-IC', 90, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-05-AJA', 'Ajakirjandusväljaanne 5%', '{"en":"Press publication 5%"}'::jsonb, 'Ajakirjandusväljaande maksumäär 01.08.2022–31.12.2024', 'percent', 5, 'sale', 'domestic', date '2022-08-01', date '2024-12-31', 'KMS § 15 lg 2¹, redaktsioon RT I, 04.06.2022, 4, kehtetu alates 01.01.2025 — ajakirjandusväljaande maksumäär 5 protsenti; vormil KMD lahter 2¹', 'S', null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-09', 'Müük 9%', '{"en":"Sale 9%"}'::jsonb, 'Raamat, õppekirjandus, ravim, meditsiiniseade ja ajakirjandusväljaanne', 'percent', 9, 'sale', 'domestic', date '2009-01-01', null, 'KMS § 15 lg 2 p 1, 2 ja 5 — raamat ja õppekirjandus, ravim ja meditsiiniseade ning alates 01.01.2025 ajakirjandusväljaanne', 'S', null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-09-MAJ', 'Majutus 9%', '{"en":"Accommodation 9%"}'::jsonb, 'Majutuse maksumäär kuni 31.12.2024', 'percent', 9, 'sale', 'domestic', date '2009-01-01', date '2024-12-31', 'KMS § 15 lg 2 p 4, kehtetu alates 01.01.2025 — majutuse maksumäär 9 protsenti kuni 31.12.2024', 'S', null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-13-MAJ', 'Majutus 13%', '{"en":"Accommodation 13%"}'::jsonb, 'Majutus või majutus koos hommikusöögiga alates 01.01.2025', 'percent', 13, 'sale', 'domestic', date '2025-01-01', null, 'KMS § 15 lg 1¹, redaktsioon RT I, 01.07.2023, 2 — majutuse või hommikusöögiga majutuse maksumäär 13 protsenti alates 01.01.2025, välja arvatud teenusega kaasnev kaup või teenus', 'S', null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-20', 'Müük 20%', '{"en":"Sale 20%"}'::jsonb, 'Standardmäär 01.07.2009–31.12.2023', 'percent', 20, 'sale', 'domestic', date '2009-07-01', date '2023-12-31', 'KMS § 15 lg 1, redaktsioon RT I 2009, 35, 232 — standardmäär 20 protsenti 01.07.2009–31.12.2023; vormil KMD lahter 1¹', 'S', null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-22', 'Müük 22%', '{"en":"Sale 22%"}'::jsonb, 'Standardmäär 01.01.2024–30.06.2025', 'percent', 22, 'sale', 'domestic', date '2024-01-01', date '2025-06-30', 'KMS § 15 lg 1, redaktsioon RT I, 01.07.2023, 2 — standardmäär 22 protsenti 01.01.2024–30.06.2025; vormil KMD lahter 1²', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-24', 'Müük 24%', '{"en":"Sale 24%"}'::jsonb, 'Standardmäär alates 01.07.2025', 'percent', 24, 'sale', 'domestic', date '2025-07-01', null, 'KMS § 15 lg 1, redaktsioon RT I, 02.01.2025, 2 — standardmäär 24 protsenti alates 01.07.2025', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-PM', 'Erikorra alusel maksustatav käive (§ 41¹)', '{"en":"Supply under the special arrangements (VAT Act § 41¹)"}'::jsonb, 'Kinnisasi, metallijäätmed, väärismetall ja metalltooted: käibemaksu arvestab soetaja', 'percent', 0, 'sale', 'domestic_reverse_charge', date '2017-01-01', null, 'KMS § 41¹ lg 1, 2 ja 5 — soetaja tasub võõrandajale käibemaksuta hinna ja arvestab arvel märgitud käibemaksu; arvele märgitakse „pöördmaksustamine“. Vormi KMD juhend: käive kajastatakse lahtris 9 ja seda lahtris 1 ei kajastata.', 'AE', 'VATEX-EU-AE', 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null),
  ('EE', 'EE-S-VABA', 'Maksuvaba käive', '{"en":"Supply exempt from tax"}'::jsonb, 'Käibemaksuga ei maksustata', 'percent', 0, 'sale', 'exempt', date '2004-05-01', null, 'KMS § 16 — maksuvaba käive', 'E', 'VATEX-EU-132', 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kms', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('EE-P-09', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 10),
    ('EE-P-09', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 10),
    ('EE-P-13-MAJ', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 10),
    ('EE-P-13-MAJ', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 10),
    ('EE-P-20', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 10),
    ('EE-P-20', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 10),
    ('EE-P-22', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 10),
    ('EE-P-22', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 10),
    ('EE-P-24-K', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 10),
    ('EE-P-24-K', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 10),
    ('EE-P-24-P', 'invoice', 'tax', 100, '2311', '5', array['5', '52']::text[], 100, 'EE-KMD', 10),
    ('EE-P-24-P', 'credit_note', 'tax', 100, '2311', '5', array['5', '52']::text[], -100, 'EE-KMD', 10),
    ('EE-P-24-T', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 10),
    ('EE-P-24-T', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 10),
    ('EE-P-ICG-24', 'invoice', 'base', 100, null, '1', array['1', '6', '61']::text[], 100, 'EE-KMD', 10),
    ('EE-P-ICG-24', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 20),
    ('EE-P-ICG-24', 'invoice', 'tax', -100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 30),
    ('EE-P-ICG-24', 'credit_note', 'base', 100, null, '1', array['1', '6', '61']::text[], -100, 'EE-KMD', 10),
    ('EE-P-ICG-24', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 20),
    ('EE-P-ICG-24', 'credit_note', 'tax', -100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 30),
    ('EE-P-ICS-24', 'invoice', 'base', 100, null, '1', array['1', '6']::text[], 100, 'EE-KMD', 10),
    ('EE-P-ICS-24', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 20),
    ('EE-P-ICS-24', 'invoice', 'tax', -100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 30),
    ('EE-P-ICS-24', 'credit_note', 'base', 100, null, '1', array['1', '6']::text[], -100, 'EE-KMD', 10),
    ('EE-P-ICS-24', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 20),
    ('EE-P-ICS-24', 'credit_note', 'tax', -100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 30),
    ('EE-P-IMP-24', 'invoice', 'tax', 100, '2311', '5', array['5', '51']::text[], 100, 'EE-KMD', 10),
    ('EE-P-IMP-24', 'invoice', 'tax', -100, '2310', '4a', array['4a']::text[], 100, 'EE-KMD', 20),
    ('EE-P-IMP-24', 'credit_note', 'tax', 100, '2311', '5', array['5', '51']::text[], -100, 'EE-KMD', 10),
    ('EE-P-IMP-24', 'credit_note', 'tax', -100, '2310', '4a', array['4a']::text[], -100, 'EE-KMD', 20),
    ('EE-P-ND-24', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 10),
    ('EE-P-ND-24', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 10),
    ('EE-P-PM-24', 'invoice', 'base', 100, null, '1', array['1', '7', '71']::text[], 100, 'EE-KMD', 10),
    ('EE-P-PM-24', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 20),
    ('EE-P-PM-24', 'invoice', 'tax', -100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 30),
    ('EE-P-PM-24', 'credit_note', 'base', 100, null, '1', array['1', '7', '71']::text[], -100, 'EE-KMD', 10),
    ('EE-P-PM-24', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 20),
    ('EE-P-PM-24', 'credit_note', 'tax', -100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 30),
    ('EE-P-SA-24-K', 'invoice', 'tax', 50, '2311', '5', array['5', '54']::text[], 50, 'EE-KMD', 20),
    ('EE-P-SA-24-K', 'invoice', 'tax_on_base', 50, null, null, null, 100, null, 30),
    ('EE-P-SA-24-K', 'credit_note', 'tax', 50, '2311', '5', array['5', '54']::text[], -50, 'EE-KMD', 20),
    ('EE-P-SA-24-K', 'credit_note', 'tax_on_base', 50, null, null, null, 100, null, 30),
    ('EE-P-SA-24-P', 'invoice', 'tax', 50, '2311', '5', array['5', '54']::text[], 50, 'EE-KMD', 20),
    ('EE-P-SA-24-P', 'invoice', 'tax_on_base', 50, null, null, null, 100, null, 30),
    ('EE-P-SA-24-P', 'credit_note', 'tax', 50, '2311', '5', array['5', '54']::text[], -50, 'EE-KMD', 20),
    ('EE-P-SA-24-P', 'credit_note', 'tax_on_base', 50, null, null, null, 100, null, 30),
    ('EE-P-SA100-24', 'invoice', 'tax', 100, '2311', '5', array['5', '53']::text[], 100, 'EE-KMD', 10),
    ('EE-P-SA100-24', 'credit_note', 'tax', 100, '2311', '5', array['5', '53']::text[], -100, 'EE-KMD', 10),
    ('EE-P-VS-24', 'invoice', 'base', 100, null, '1', array['1', '7']::text[], 100, 'EE-KMD', 10),
    ('EE-P-VS-24', 'invoice', 'tax', 100, '2311', '5', array['5']::text[], 100, 'EE-KMD', 20),
    ('EE-P-VS-24', 'invoice', 'tax', -100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 30),
    ('EE-P-VS-24', 'credit_note', 'base', 100, null, '1', array['1', '7']::text[], -100, 'EE-KMD', 10),
    ('EE-P-VS-24', 'credit_note', 'tax', 100, '2311', '5', array['5']::text[], -100, 'EE-KMD', 20),
    ('EE-P-VS-24', 'credit_note', 'tax', -100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 30),
    ('EE-S-00-EXP', 'invoice', 'base', 100, null, '3', array['3', '32']::text[], 100, 'EE-KMD', 10),
    ('EE-S-00-EXP', 'credit_note', 'base', 100, null, '3', array['3', '32']::text[], -100, 'EE-KMD', 10),
    ('EE-S-00-ICG', 'invoice', 'base', 100, null, '3', array['3', '31', '311']::text[], 100, 'EE-KMD', 10),
    ('EE-S-00-ICG', 'credit_note', 'base', 100, null, '3', array['3', '31', '311']::text[], -100, 'EE-KMD', 10),
    ('EE-S-00-ICS', 'invoice', 'base', 100, null, '3', array['3', '31']::text[], 100, 'EE-KMD', 10),
    ('EE-S-00-ICS', 'credit_note', 'base', 100, null, '3', array['3', '31']::text[], -100, 'EE-KMD', 10),
    ('EE-S-05-AJA', 'invoice', 'base', 100, null, '2a', array['2a']::text[], 100, 'EE-KMD', 10),
    ('EE-S-05-AJA', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-05-AJA', 'credit_note', 'base', 100, null, '2a', array['2a']::text[], -100, 'EE-KMD', 10),
    ('EE-S-05-AJA', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-09', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'EE-KMD', 10),
    ('EE-S-09', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-09', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'EE-KMD', 10),
    ('EE-S-09', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-09-MAJ', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'EE-KMD', 10),
    ('EE-S-09-MAJ', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-09-MAJ', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'EE-KMD', 10),
    ('EE-S-09-MAJ', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-13-MAJ', 'invoice', 'base', 100, null, '2b', array['2b']::text[], 100, 'EE-KMD', 10),
    ('EE-S-13-MAJ', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-13-MAJ', 'credit_note', 'base', 100, null, '2b', array['2b']::text[], -100, 'EE-KMD', 10),
    ('EE-S-13-MAJ', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-20', 'invoice', 'base', 100, null, '1a', array['1a']::text[], 100, 'EE-KMD', 10),
    ('EE-S-20', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-20', 'credit_note', 'base', 100, null, '1a', array['1a']::text[], -100, 'EE-KMD', 10),
    ('EE-S-20', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-22', 'invoice', 'base', 100, null, '1b', array['1b']::text[], 100, 'EE-KMD', 10),
    ('EE-S-22', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-22', 'credit_note', 'base', 100, null, '1b', array['1b']::text[], -100, 'EE-KMD', 10),
    ('EE-S-22', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-24', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'EE-KMD', 10),
    ('EE-S-24', 'invoice', 'tax', 100, '2310', '4', array['4']::text[], 100, 'EE-KMD', 20),
    ('EE-S-24', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'EE-KMD', 10),
    ('EE-S-24', 'credit_note', 'tax', 100, '2310', '4', array['4']::text[], -100, 'EE-KMD', 20),
    ('EE-S-PM', 'invoice', 'base', 100, null, '9', array['9']::text[], 100, 'EE-KMD', 10),
    ('EE-S-PM', 'credit_note', 'base', 100, null, '9', array['9']::text[], -100, 'EE-KMD', 10),
    ('EE-S-VABA', 'invoice', 'base', 100, null, '8', array['8']::text[], 100, 'EE-KMD', 10),
    ('EE-S-VABA', 'credit_note', 'base', 100, null, '8', array['8']::text[], -100, 'EE-KMD', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'EE' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('EE', 'EE-KMD', 'Käibedeklaratsioon (vorm KMD)', array['month']::declaration_period[], 'month'::declaration_period, date '2025-07-01', null, 'Käibemaksuseadus § 27 lõige 1 — maksustamisperiood on kalendrikuu ja deklaratsioon esitatakse järgneva kuu 20. kuupäevaks; vorm on rahandusministri 10.06.2014 määruse nr 17 lisa 1 rahandusministri 14.05.2025 määruse nr 20 sõnastuses, kehtiv alates 01.07.2025. Vormil on lahtrite tähiseid, mida see fail ei saa tähemärgi haaval korrata: ülaindeksiga lahtrid 1¹, 1², 2¹, 2² ja 4¹ kannavad siin tähiseid 1a, 1b, 2a, 2b ja 4a ning punktiga alamlahtrid 3.1, 3.1.1, 3.2, 3.2.1, 5.1, 5.2, 5.3, 5.4, 6.1 ja 7.1 kannavad tähiseid 31, 311, 32, 321, 51, 52, 53, 54, 61 ja 71. Iga lahtri õiguslik viide nimetab vormil trükitud tähise.', true,'day_of_month_after_period'::filing_deadline_rule, 20, null, 'Käibemaksuseadus § 27 lõige 1 — le assujetti dépose la déclaration de TVA (vorm KMD) et acquitte la taxe au plus tard le vingtième jour du mois qui suit la période d''imposition. La période d''imposition est le mois civil (§ 27 lg 1), ce qui rend la date et la cadence solidaires dans le même alinéa.', null, null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('EE', 'EE-KMD', '1', 'base', '24% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 24%"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 1 — käibemaksuseadus § 15 lõige 1. Lahter koondab 24% määraga maksustatava käibe ning maksukohustuslase enda arvestatava käibemaksu aluse: kauba ühendusesisese soetamise, teise liikmesriigi maksukohustuslaselt ja välisriigi isikult saadud teenused ning § 41¹ erikorra alusel soetatu. Iga maks nimetab selle lahtri ise — kauba ühendusesisene soetamine koos lahtritega 6 ja 6.1, erikorra alusel soetamine koos lahtritega 7 ja 7.1 —, sest üks alus võib nimetada nii mitu lahtrit, kui vorm neid trükib.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '1a', 'base', '20% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 20%"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 1¹ — käibemaksuseadus § 15 lõige 1 redaktsioonis, mis kehtis kuni 31.12.2023. Vormi juhendi järgi märgitakse siia maksustatava väärtuse muudatused, mis tulenevad kreeditarvetest ja §-st 29¹ ning puudutavad 20% määraga tehinguid.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '1b', 'base', '22% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 22%"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 1² — käibemaksuseadus § 15 lõige 1 redaktsioonis, mis kehtis 01.01.2024–30.06.2025. Vormi juhendi järgi märgitakse siia maksustatava väärtuse muudatused, mis tulenevad kreeditarvetest ja §-st 29¹ ning puudutavad 22% määraga tehinguid.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '2', 'base', '9% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 9%"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 2 — käibemaksuseadus § 15 lõige 2: raamat ja õppekirjandus (punkt 1), ravim, meditsiiniseade ja abivahend (punkt 2) ning ajakirjandusväljaanne (punkt 5, kehtiv alates 01.01.2025)', 'kmd-vorm'),
  ('EE', 'EE-KMD', '2a', 'base', '5% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 5%"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 2¹ — käibemaksuseadus § 15 lõige 2¹, mis kehtis 01.08.2022–31.12.2024 ajakirjandusväljaande kohta; kassapõhise arvestuse korral kohaldatav § 46 lõike 2⁷ alusel kuni 31.12.2026', 'kmd-vorm'),
  ('EE', 'EE-KMD', '2b', 'base', '13% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 13%"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 2² — käibemaksuseadus § 15 lõige 1¹, kehtiv alates 01.01.2025: majutus või majutus koos hommikusöögiga', 'kmd-vorm'),
  ('EE', 'EE-KMD', '3', 'base', '0% määraga maksustatavad toimingud ja tehingud', '{"en":"Acts and transactions subject to tax at a rate of 0%"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 3 — käibemaksuseadus § 15 lõiked 3 ja 4. Iga nullmääraga maks nimetab selle lahtri ise, vajaduse korral koos lahtriga 3.1, 3.1.1 või 3.2; käesolev pakk kannab nullmääraga makse üksnes kauba ühendusesisese käibe, teise liikmesriigi maksukohustuslasele osutatud teenuse ja ekspordi kohta, seega peab uue nullmääraga maksu lisaja nimetama ka selle lahtri.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '31', 'base', 'Kauba ühendusesisene käive ja teise liikmesriigi maksukohustuslasele või piiratud maksukohustuslasele osutatud teenuste käive kokku', '{"en":"Intra-Community supply of goods and services provided to a taxable person or taxable person with limited liability of another Member State, total"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 3.1 — käibemaksuseadus § 15 lõike 3 punkt 2 ja § 10 lõike 4 punkt 9. Lahtris 3 deklareeritud summas sisalduv.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '311', 'base', 'Kauba ühendusesisene käive', '{"en":"Intra-Community supply of goods"}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 3.1.1 — käibemaksuseadus § 7 lõige 1 ja § 15 lõike 3 punkt 2. Lahtris 3.1 deklareeritud summas sisalduv.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '32', 'base', 'Kauba eksport', '{"en":"Exportation of goods"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 3.2 — käibemaksuseadus § 15 lõike 3 punkt 1. Lahtris 3 deklareeritud summas sisalduv.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '321', 'base', 'Käibemaksutagastusega müük reisijale', '{"en":"Sale to passengers with return of value added tax"}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 3.2.1 — käibemaksuseadus § 5 lõiked 2 ja 4. Lahtris 3.2 deklareeritud summas sisalduv; käesolev pakk ei kanna reisijale käibemaksutagastusega müügi maksu, mistõttu lahter jääb tühjaks.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '4', 'tax', 'Käibemaks kokku', '{"en":"Total amount of value added tax"}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 4 — käibemaksuseadus § 29 lõige 2. Vormi juhend arvutab lahtri maksumääradega lahtritest 1, 1¹, 1², 2, 2¹ ja 2²; Ekwo liidab siia käibemaksu, mille dokumendid tegelikult raamatusse kirjutasid, sest pakk ei sisalda avaldiste keelt ja iga dokumendi maks on juba ümardatud.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '4a', 'tax', 'Impordilt tasumisele kuuluv käibemaks', '{"en":"Value added tax payable upon the import of the goods"}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 4¹ — käibemaksuseadus § 38 lõiked 2¹–2³: maksuhalduri kirjalikul loal deklareeritakse kauba impordilt arvestatav käibemaks käibedeklaratsioonis tollile tasumise asemel', 'kmd-vorm'),
  ('EE', 'EE-KMD', '5', 'tax', 'Kokku sisendkäibemaksu summa, mis on seadusega lubatud maha arvata', '{"en":"Total amount of input VAT subject to deduction pursuant to law"}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 5 — käibemaksuseadus §§ 29, 30 ja 31. Lahter kannab juba piirangute järgset summat; Iga mahaarvamine nimetab selle lahtri ise, vajaduse korral koos lahtriga 5.1, 5.2, 5.3 või 5.4.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '51', 'tax', 'Impordilt tasutud või tasumisele kuuluv käibemaks', '{"en":"VAT paid or payable on import"}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 5.1 — käibemaksuseadus § 29 lõike 3 punkt 2 ja § 31 lõiked 4 ja 8. Lahtri 5 summas sisalduv.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '52', 'tax', 'Põhivara soetamiselt tasutud või tasumisele kuuluv käibemaks', '{"en":"VAT paid or payable on acquisition of fixed assets"}'::jsonb, 160, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 5.2 — käibemaksuseadus § 32 lõige 4. Lahtri 5 summas sisalduv.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '53', 'tax', 'Ettevõtluses (100%) kasutatava sõiduauto soetamiselt ja selle tarbeks kaupade ja teenuste soetamiselt tasutud käibemaks', '{"en":"VAT paid or payable on acquisition of a car used wholly for business purposes and on goods and services for such a car"}'::jsonb, 170, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 5.3 — käibemaksuseadus § 30 lõike 4 punktid 3–5 ja lõige 6. Lahtri 5 summas sisalduv. Vormil on lahtri kõrval ka sõiduautode arv; Ekwo ei kanna seda, sest deklaratsiooni lahter on käesolevas mudelis rahasumma.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '54', 'tax', 'Osaliselt ettevõtluses kasutatava sõiduauto soetamiselt ja selle tarbeks kaupade ja teenuste soetamiselt tasutud käibemaks', '{"en":"VAT paid or payable on acquisition of a car used partially for business purposes and on goods and services for such a car"}'::jsonb, 180, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 5.4 — käibemaksuseadus § 30 lõige 3: maha arvatakse kuni 50 protsenti sisendkäibemaksust. Lahtri 5 summas sisalduv. Vormil on lahtri kõrval ka sõiduautode arv, mida Ekwo ei kanna.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '6', 'base', 'Kauba ühendusesisene soetamine ja teise liikmesriigi maksukohustuslaselt saadud teenused kokku', '{"en":"Intra-Community acquisitions of goods and services received from a taxable person of another Member State, total"}'::jsonb, 190, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 6 — käibemaksuseadus § 8 ja § 10 lõige 1. Vormi juhend nimetab lahtri sõnaselgelt informatiivseks: summa sisaldub juba lahtris 1 ja ei mõjuta ühtki kokkuvõtet.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '61', 'base', 'Kauba ühendusesisene soetamine', '{"en":"Intra-Community acquisitions of goods"}'::jsonb, 200, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 6.1 — käibemaksuseadus § 8. Vormi juhendi järgi informatiivne lahter.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '7', 'base', 'Muu kauba soetamine ja teenuse saamine, mida maksustatakse käibemaksuga', '{"en":"Acquisition of other goods and services subject to value added tax"}'::jsonb, 210, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 7 — käibemaksuseadus § 3 lõike 4 punktid 2 ja 5 ning § 41¹. Vormi juhendi järgi informatiivne lahter.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '71', 'base', 'Erikorra alusel maksustatava kinnisasja, metallijäätmete, väärismetalli ja metalltoodete soetamine', '{"en":"Acquisition of immovables, scrap metal, precious metal and metal products subject to value added tax under the special arrangements"}'::jsonb, 220, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 7.1 — käibemaksuseadus § 41¹ lõiked 1–4. Vormi juhendi järgi informatiivne lahter.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '8', 'base', 'Maksuvaba käive', '{"en":"Supply exempt from tax"}'::jsonb, 230, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 8 — käibemaksuseadus § 16', 'kmd-vorm'),
  ('EE', 'EE-KMD', '9', 'base', 'Erikorra alusel maksustatava kinnisasja, metallijäätmete, väärismetalli ja metalltoodete käive ning teises liikmesriigis paigaldatava või kokkupandava kauba maksustatav väärtus', '{"en":"Supply of immovables, scrap metal, precious metal and metal products under the special arrangements and taxable value of goods to be installed or assembled in another Member State"}'::jsonb, 240, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 9 — käibemaksuseadus § 41¹ lõiked 1 ja 2. Vormi juhendi järgi informatiivne lahter, ja juhend ütleb sõnaselgelt, et müüja § 41¹ käivet lahtrisse 1 ei märgita.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '10', 'tax', 'Täpsustused (+)', '{"en":"Adjustments (+)"}'::jsonb, 250, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 10 — käibemaksuseadus § 32 lõiked 1 ja 4, § 29 lõige 4 ja § 30 lõige 7: sisendkäibemaksu ümberarvestused. Käesolev pakk ei kanna ühtki maksu, mis sellesse lahtrisse kirjutaks; ümberarvestuse teeb raamatupidaja käsitsi.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '11', 'tax', 'Täpsustused (−)', '{"en":"Adjustments (−)"}'::jsonb, 260, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Vorm KMD, lahter 11 — samad alused kui lahtril 10. Vormi juhendi järgi ei täideta lahtreid 10 ja 11 üheaegselt.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '12', 'total', 'Tasumisele kuuluv käibemaks', '{"en":"Value added tax payable"}'::jsonb, 330, null, array['4', '4a', '10']::text[], array['5', '11']::text[], null, null, true, false, null, 'Vorm KMD, lahter 12 — vormi juhend: lahter 4 + lahter 4¹ − lahter 5 + lahter 10 − lahter 11. Käibemaksuseadus § 29 lõige 1 ja § 38 lõige 1.', 'kmd-vorm'),
  ('EE', 'EE-KMD', '13', 'total', 'Enammakstud käibemaks', '{"en":"Overpaid value added tax"}'::jsonb, 340, null, array['5', '11']::text[], array['4', '4a', '10']::text[], null, null, true, false, null, 'Vorm KMD, lahter 13 — sama valem kui lahtril 12, vastasmärgiga: vorm trükib lahtri 12 juurde + ja lahtri 13 juurde −, nii et täidetakse üks neist. Enammakse kantakse ettemaksukontole ja tagastatakse eraldi taotluse alusel.', 'kmd-vorm')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('EE-RPS-BS', 'EE', 'default', 'Bilanss', 'balance_sheet', 'EE-GAAP', date '2025-07-01', null, 'Raamatupidamise seadus, lisa 1 — bilansiskeem, Riigikogu 18.09.2024 seaduse sõnastuses, kehtiv alates 01.07.2025; Raamatupidamise Toimkonna juhend RTJ 2 punktid 10–20', 'rps'),
  ('EE-RPS-IS1', 'EE', 'default', 'Kasumiaruanne, skeem 1', 'income_statement', 'EE-GAAP', date '2025-07-01', null, 'Raamatupidamise seadus, lisa 2 — kasumiaruande skeem 1, kulud liigendatud kululiikide järgi; Raamatupidamise Toimkonna juhend RTJ 2 punktid 21–33. Skeem 2 liigendab ärikulud funktsiooni järgi ja seda pakk ei kanna: RTJ 2 punkt 22 ütleb, et skeemi 1 on üldjuhul lihtsam rakendada ja väiksemad ettevõtjad kasutavad seda sageli, ning punkt 24 nõuab skeemi vahetamisel võrdlusperioodi ümberarvestamist.', 'rps')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('EE-RPS-BS', '1', null, 'Kokku käibevarad', '{"en":"Total current assets"}'::jsonb, 10, 1, true, array['1.1', '1.2', '1.3', '1.4', '1.5']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.1', '1', 'Raha', '{"en":"Cash"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.2', '1', 'Finantsinvesteeringud', '{"en":"Financial investments"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3', '1', 'Nõuded ja ettemaksed', '{"en":"Receivables and prepayments"}'::jsonb, 40, 1, true, array['1.3.1', '1.3.2', '1.3.3', '1.3.4', '1.3.5', '1.3.6']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3.1', '1.3', 'Nõuded ostjate vastu', '{"en":"Trade receivables"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3.2', '1.3', 'Nõuded seotud osapoolte vastu', '{"en":"Receivables from related parties"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3.3', '1.3', 'Maksude ettemaksed ja tagasinõuded', '{"en":"Prepaid and deferred taxes"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3.4', '1.3', 'Laenunõuded', '{"en":"Loan receivables"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3.5', '1.3', 'Muud nõuded', '{"en":"Other receivables"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.3.6', '1.3', 'Ettemaksed', '{"en":"Prepayments"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.4', '1', 'Varud', '{"en":"Inventories"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '1.5', '1', 'Bioloogilised varad', '{"en":"Biological assets"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2', null, 'Kokku põhivarad', '{"en":"Total fixed assets"}'::jsonb, 130, 1, true, array['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.1', '2', 'Investeeringud tütar- ja sidusettevõtjatesse', '{"en":"Investments in subsidiaries and affiliated undertakings"}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.2', '2', 'Finantsinvesteeringud', '{"en":"Financial investments"}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.3', '2', 'Nõuded ja ettemaksed', '{"en":"Receivables and prepayments"}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.4', '2', 'Kinnisvarainvesteeringud', '{"en":"Investment properties"}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.5', '2', 'Materiaalsed põhivarad', '{"en":"Tangible assets"}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.6', '2', 'Bioloogilised varad', '{"en":"Biological assets"}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '2.7', '2', 'Immateriaalsed põhivarad', '{"en":"Intangible fixed assets"}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '3', null, 'KOKKU VARAD', '{"en":"TOTAL ASSETS"}'::jsonb, 210, 1, true, array['1', '2']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4', null, 'Kokku lühiajalised kohustised', '{"en":"Total current liabilities"}'::jsonb, 220, 1, true, array['4.1', '4.2', '4.3', '4.4']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.1', '4', 'Laenukohustised', '{"en":"Loan liabilities"}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2', '4', 'Võlad ja ettemaksed', '{"en":"Payables and prepayments"}'::jsonb, 240, 1, true, array['4.2.1', '4.2.2', '4.2.3', '4.2.4', '4.2.5', '4.2.6']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2.1', '4.2', 'Võlad tarnijatele', '{"en":"Trade creditors"}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2.2', '4.2', 'Võlad töövõtjatele', '{"en":"Employee-related liabilities"}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2.3', '4.2', 'Maksuvõlad', '{"en":"Taxes payable"}'::jsonb, 270, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2.4', '4.2', 'Muud võlad', '{"en":"Other payables"}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2.5', '4.2', 'Tulevaste perioodide tulud', '{"en":"Prepaid revenues"}'::jsonb, 290, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.2.6', '4.2', 'Muud saadud ettemaksed', '{"en":"Other received prepayments"}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.3', '4', 'Eraldised', '{"en":"Provisions"}'::jsonb, 310, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '4.4', '4', 'Sihtfinantseerimine', '{"en":"Targeted financing"}'::jsonb, 320, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '5', null, 'Kokku pikaajalised kohustised', '{"en":"Total non-current liabilities"}'::jsonb, 330, 1, true, array['5.1', '5.2', '5.3', '5.4']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '5.1', '5', 'Laenukohustised', '{"en":"Loan liabilities"}'::jsonb, 340, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '5.2', '5', 'Võlad ja ettemaksed', '{"en":"Payables and prepayments"}'::jsonb, 350, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '5.3', '5', 'Eraldised', '{"en":"Provisions"}'::jsonb, 360, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '5.4', '5', 'Sihtfinantseerimine', '{"en":"Targeted financing"}'::jsonb, 370, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '6', null, 'Kokku kohustised', '{"en":"Total liabilities"}'::jsonb, 380, 1, true, array['4', '5']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7', null, 'Kokku omakapital', '{"en":"Total owners'' equity"}'::jsonb, 390, 1, true, array['7.1', '7.2', '7.3', '7.4', '7.5', '7.6', '7.7', '7.8', '7.9', '7.10']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.1', '7', 'Aktsiakapital või osakapital nimiväärtuses', '{"en":"Share capital in nominal value"}'::jsonb, 400, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.2', '7', 'Registreerimata aktsiakapital või osakapital', '{"en":"Unregistered share capital"}'::jsonb, 410, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.3', '7', 'Sissemaksmata osakapital', '{"en":"Unpaid share capital"}'::jsonb, 420, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.4', '7', 'Ülekurss', '{"en":"Share premium account"}'::jsonb, 430, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.5', '7', 'Oma aktsiad või osad', '{"en":"Own shares"}'::jsonb, 440, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.6', '7', 'Kohustuslik reservkapital', '{"en":"Legal reserve"}'::jsonb, 450, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.7', '7', 'Muud reservid', '{"en":"Other reserves"}'::jsonb, 460, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.8', '7', 'Muu omakapital', '{"en":"Other owners'' equity"}'::jsonb, 470, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.9', '7', 'Eelmiste perioodide jaotamata kasum (kahjum)', '{"en":"Retained profit (loss)"}'::jsonb, 480, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '7.10', '7', 'Aruandeaasta kasum (kahjum)', '{"en":"Profit (loss) for accounting year"}'::jsonb, 490, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-BS', '8', null, 'KOKKU KOHUSTISED JA OMAKAPITAL', '{"en":"TOTAL LIABILITIES AND OWNERS'' EQUITY"}'::jsonb, 500, 1, true, array['6', '7']::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '1', null, 'Müügitulu', '{"en":"Sales revenue"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '2', null, 'Muud äritulud', '{"en":"Other operating revenue"}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '3', null, 'Põllumajandusliku toodangu varude jääkide muutus', '{"en":"Change in stocks of agricultural produce"}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '4', null, 'Kasum (kahjum) bioloogilistelt varadelt', '{"en":"Profit (loss) on biological assets"}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '5', null, 'Valmis- ja lõpetamata toodangu varude jääkide muutus', '{"en":"Changes in inventories of finished goods and work in progress"}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '6', null, 'Kapitaliseeritud väljaminekud oma tarbeks põhivarade valmistamisel', '{"en":"Capitalised expenditure when manufacturing fixed assets for own purposes"}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '7', null, 'Kaubad, toore, materjal ja teenused', '{"en":"Goods, raw materials and services"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '8', null, 'Mitmesugused tegevuskulud', '{"en":"Miscellaneous operating expenses"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '9', null, 'Tööjõukulud', '{"en":"Staff costs"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '10', null, 'Põhivarade kulum ja väärtuse langus', '{"en":"Depreciation and impairment of fixed assets"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '11', null, 'Olulised käibevara allahindlused', '{"en":"Significant rebates of current assets"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '12', null, 'Muud ärikulud', '{"en":"Other operating expenses"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '13', null, 'Kokku ärikasum (-kahjum)', '{"en":"Total operating profit (loss)"}'::jsonb, 130, 1, true, array['1', '2', '3', '4', '5', '6']::text[], array['7', '8', '9', '10', '11', '12']::text[], null, null, null),
  ('EE-RPS-IS1', '14', null, 'Kasum (kahjum) tütarettevõtjatelt', '{"en":"Profit (loss) from subsidiaries"}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '15', null, 'Kasum (kahjum) sidusettevõtjatelt', '{"en":"Profit (loss) from affiliated undertakings"}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '16', null, 'Kasum (kahjum) finantsinvesteeringutelt', '{"en":"Profit (loss) from financial investments"}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '17', null, 'Intressitulud', '{"en":"Interest income"}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '18', null, 'Intressikulud', '{"en":"Interest expenses"}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '19', null, 'Muud finantstulud ja -kulud', '{"en":"Other financial income and expenses"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '20', null, 'Kasum (kahjum) enne tulumaksustamist', '{"en":"Profit (loss) before income tax"}'::jsonb, 200, 1, true, array['13', '14', '15', '16', '17', '19']::text[], array['18']::text[], null, null, null),
  ('EE-RPS-IS1', '21', null, 'Tulumaks', '{"en":"Income tax expense"}'::jsonb, 210, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('EE-RPS-IS1', '22', null, 'Aruandeaasta kasum (kahjum)', '{"en":"Net profit/loss for financial year"}'::jsonb, 220, 1, true, array['20']::text[], array['21']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('EE-RPS-BS', '1.1', 10, 'code_range', '1000', '1099', null, 'any'),
    ('EE-RPS-BS', '1.2', 10, 'code_range', '1100', '1199', null, 'any'),
    ('EE-RPS-BS', '1.3.1', 10, 'code_range', '1200', '1209', null, 'any'),
    ('EE-RPS-BS', '1.3.2', 10, 'code_range', '1220', '1229', null, 'any'),
    ('EE-RPS-BS', '1.3.3', 10, 'code_range', '1210', '1219', null, 'any'),
    ('EE-RPS-BS', '1.3.3', 20, 'account_code', '2310', null, null, 'debit'),
    ('EE-RPS-BS', '1.3.3', 30, 'account_code', '2311', null, null, 'debit'),
    ('EE-RPS-BS', '1.3.4', 10, 'code_range', '1230', '1239', null, 'any'),
    ('EE-RPS-BS', '1.3.5', 10, 'code_range', '1240', '1249', null, 'any'),
    ('EE-RPS-BS', '1.3.5', 20, 'account_code', '2490', null, null, 'debit'),
    ('EE-RPS-BS', '1.3.6', 10, 'code_range', '1250', '1269', null, 'any'),
    ('EE-RPS-BS', '1.4', 10, 'code_range', '1300', '1399', null, 'any'),
    ('EE-RPS-BS', '1.5', 10, 'code_range', '1400', '1499', null, 'any'),
    ('EE-RPS-BS', '2.1', 10, 'code_range', '1500', '1549', null, 'any'),
    ('EE-RPS-BS', '2.2', 10, 'code_range', '1600', '1649', null, 'any'),
    ('EE-RPS-BS', '2.3', 10, 'code_range', '1650', '1699', null, 'any'),
    ('EE-RPS-BS', '2.4', 10, 'code_range', '1700', '1749', null, 'any'),
    ('EE-RPS-BS', '2.5', 10, 'code_range', '1750', '1899', null, 'any'),
    ('EE-RPS-BS', '2.6', 10, 'code_range', '1860', '1869', null, 'any'),
    ('EE-RPS-BS', '2.7', 10, 'code_range', '1900', '1999', null, 'any'),
    ('EE-RPS-BS', '4.1', 10, 'code_range', '2000', '2099', null, 'any'),
    ('EE-RPS-BS', '4.2.1', 10, 'code_range', '2100', '2199', null, 'any'),
    ('EE-RPS-BS', '4.2.2', 10, 'code_range', '2200', '2299', null, 'any'),
    ('EE-RPS-BS', '4.2.3', 10, 'code_range', '2320', '2399', null, 'any'),
    ('EE-RPS-BS', '4.2.3', 20, 'account_code', '2310', null, null, 'credit'),
    ('EE-RPS-BS', '4.2.3', 30, 'account_code', '2311', null, null, 'credit'),
    ('EE-RPS-BS', '4.2.4', 10, 'code_range', '2400', '2489', null, 'any'),
    ('EE-RPS-BS', '4.2.4', 20, 'account_code', '2490', null, null, 'credit'),
    ('EE-RPS-BS', '4.2.5', 10, 'code_range', '2510', '2519', null, 'any'),
    ('EE-RPS-BS', '4.2.6', 10, 'code_range', '2500', '2509', null, 'any'),
    ('EE-RPS-BS', '4.3', 10, 'code_range', '2600', '2699', null, 'any'),
    ('EE-RPS-BS', '4.4', 10, 'code_range', '2700', '2749', null, 'any'),
    ('EE-RPS-BS', '5.1', 10, 'code_range', '2750', '2759', null, 'any'),
    ('EE-RPS-BS', '5.2', 10, 'code_range', '2760', '2769', null, 'any'),
    ('EE-RPS-BS', '5.3', 10, 'code_range', '2770', '2779', null, 'any'),
    ('EE-RPS-BS', '5.4', 10, 'code_range', '2780', '2789', null, 'any'),
    ('EE-RPS-BS', '7.1', 10, 'code_range', '2900', '2904', null, 'any'),
    ('EE-RPS-BS', '7.2', 10, 'code_range', '2905', '2909', null, 'any'),
    ('EE-RPS-BS', '7.3', 10, 'code_range', '2910', '2919', null, 'any'),
    ('EE-RPS-BS', '7.4', 10, 'code_range', '2920', '2929', null, 'any'),
    ('EE-RPS-BS', '7.5', 10, 'code_range', '2930', '2939', null, 'any'),
    ('EE-RPS-BS', '7.6', 10, 'code_range', '2940', '2949', null, 'any'),
    ('EE-RPS-BS', '7.7', 10, 'code_range', '2950', '2959', null, 'any'),
    ('EE-RPS-BS', '7.8', 10, 'code_range', '2960', '2969', null, 'any'),
    ('EE-RPS-BS', '7.9', 10, 'code_range', '2970', '2979', null, 'any'),
    ('EE-RPS-BS', '7.10', 10, 'code_range', '2980', '2989', null, 'any'),
    ('EE-RPS-IS1', '1', 10, 'code_range', '3000', '3099', null, 'any'),
    ('EE-RPS-IS1', '2', 10, 'code_range', '3100', '3149', null, 'any'),
    ('EE-RPS-IS1', '3', 10, 'code_range', '3150', '3169', null, 'any'),
    ('EE-RPS-IS1', '4', 10, 'code_range', '3170', '3189', null, 'any'),
    ('EE-RPS-IS1', '5', 10, 'code_range', '3200', '3249', null, 'any'),
    ('EE-RPS-IS1', '6', 10, 'code_range', '3250', '3299', null, 'any'),
    ('EE-RPS-IS1', '7', 10, 'code_range', '4000', '4099', null, 'any'),
    ('EE-RPS-IS1', '8', 10, 'code_range', '4100', '4699', null, 'any'),
    ('EE-RPS-IS1', '9', 10, 'code_range', '4700', '4799', null, 'any'),
    ('EE-RPS-IS1', '10', 10, 'code_range', '4800', '4849', null, 'any'),
    ('EE-RPS-IS1', '11', 10, 'code_range', '4850', '4879', null, 'any'),
    ('EE-RPS-IS1', '12', 10, 'code_range', '4900', '4949', null, 'any'),
    ('EE-RPS-IS1', '14', 10, 'code_range', '3830', '3839', null, 'any'),
    ('EE-RPS-IS1', '15', 10, 'code_range', '3840', '3849', null, 'any'),
    ('EE-RPS-IS1', '16', 10, 'code_range', '3810', '3819', null, 'any'),
    ('EE-RPS-IS1', '17', 10, 'code_range', '3800', '3809', null, 'any'),
    ('EE-RPS-IS1', '18', 10, 'code_range', '4950', '4959', null, 'any'),
    ('EE-RPS-IS1', '19', 10, 'code_range', '3820', '3829', null, 'any'),
    ('EE-RPS-IS1', '19', 20, 'code_range', '3850', '3899', null, 'any'),
    ('EE-RPS-IS1', '19', 30, 'code_range', '4960', '4979', null, 'any'),
    ('EE-RPS-IS1', '21', 10, 'code_range', '4990', '4999', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('EE', 'Estonia', '{"en":"Estonia"}'::jsonb, array['et', 'en']::text[], 'EUR', '1200', '2100', '2490', '4920', '2970', '3000', '4000', '1010', '1000', 'MUU', 'OST', 'MIS', 'et', 'result_accounts', '2980', '2980', null, 'ALG', 'half_up', default, '3850', '4970', null, null, null, null, '2370', '1211', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = 30,
  late_payment_reference        = 'Võlaõigusseadus § 113 lõige 1 — viivis on § 94 alusel poolaastati avaldatav Euroopa Keskpanga põhirefinantseerimisoperatsioonide intressimäär, mida on suurendatud kaheksa protsendipunkti võrra; § 113¹ lõige 1 — sissenõudmiskulude hüvitis 40 eurot',
  numbering_legal_reference     = 'Käibemaksuseadus § 37 lõige 7 punkt 1 — arvele tuleb märkida arve järjekorranumber ja väljastamise kuupäev. Seadus nõuab järjekorranumbrit ega sea numbrile vormi. Katkematut, lünkadeta numeratsiooni käibemaksuseadus ei nõua, mistõttu numbering on siin sequential ja mitte gapless.',
  numbering_source_key          = 'kms',
  payment_terms_legal_reference = 'Võlaõigusseadus § 82¹ lõige 1 — kui vastastikuse lepingu puhul ei ole tasu maksmise tähtpäeva või tähtaega kokku lepitud, muutub tasu maksmise kohustus sissenõutavaks hiljemalt 30 päeva möödumisel arve või muu sellise makseettepaneku võlgniku kätte jõudmisest, või kauba, teenuse või muu hüve saamisest, kui arve kättesaamise aeg ei ole selge. Lõige 2 piirab lepinguga kokku lepitavat tähtaega 60 päevaga.',
  payment_terms_source_key      = 'vos',
  tax_point_rule                = 'earliest_of_delivery_or_payment',
  tax_point_legal_reference     = 'Käibemaksuseadus § 11 lõige 1 — käibe tekkimise ajaks loetakse päev, mil esimesena tehti üks lõikes nimetatud toimingutest: punkt 1 kauba ostjale lähetamine või kättesaadavaks tegemine või teenuse osutamine, punkt 2 kauba või teenuse eest osalise või täieliku makse laekumine. Käive tekib seega kahest sündmusest varasemal, ja lõige 3 piirab makse haru laekunud summaga. Arve kuupäev ei ole lõike 1 haru: arve kuulub lõikesse 2, mis on kauba ühendusesisese käibe eraldi reegel. earliest_of_delivery_or_payment kannab mõlemat haru; delivery_date, mis oli siin varem, kandis ainult punkti 1. Riigi Teataja ametlik ingliskeelne tõlge ütleb sedasama: „the date on which the first of one of the following acts is performed”.',
  tax_point_source_key          = 'kms',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = 'peppol-bis-3',
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'on_request',
  einvoice_legal_reference      = 'Raamatupidamise seadus § 7¹ lõige 7, kehtiv alates 01.07.2025 — äriregistris e-arve vastuvõtjaks märgitud raamatupidamiskohustuslane võib nõuda müüjalt e-arve esitamist, ja e-arve eeldatakse nõuetekohaseks, kui see vastab Euroopa standardile EN 16931-1; pooled võivad kokku leppida muu standardi kasutamises. Seadus ei kehtesta üldist e-arve kohustust ega ühtki tähtpäeva, mistõttu mandatory_from on tühi. Deklareeritud profiil peppol-bis-3 on EN 16931-1 kitsendus, mida Eesti operaatorid tegelikkuses vahetavad; see ei ole seadusest tulenev nõue. Riigisisene standard EVS 923 kaotas õigusliku aluse 01.07.2025, kui rahandusministri määrus „Masintöödeldava algdokumendi juhendi kehtestamine“ kehtetuks tunnistati.',
  einvoice_source_key           = 'rps',
  party_scheme                  = '0191',
  vat_scheme                    = '9931',
  bank_statement_formats        = array['camt.053', 'camt.052']::text[],
  payment_formats               = array['pain.001']::text[],
  fiscal_year_default           = 'calendar'
 where country = 'EE';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('EE', 'reverse_charge', 'reverse_charge', 'Pöördmaksustamine', '{"en":"Reverse charge"}'::jsonb, 10, date '1970-01-01', null, 'Käibemaksuseadus § 37 lõige 8 punkt 2 — märge „pöördmaksustamine“ on seaduses sätestatud sõnastuses ja seda ei saa § 37 lõike 8¹ alusel muu märkega asendada'),
  ('EE', 'intracom_goods', 'intra_eu_goods', 'Kauba ühendusesisene käive, maksustatav 0% määraga — KMS § 15 lg 3 p 2; nõukogu direktiivi 2006/112/EÜ artikkel 138.', '{"en":"Intra-Community supply of goods, taxable at 0% — VAT Act § 15 (3) 2); Council Directive 2006/112/EC, Article 138."}'::jsonb, 20, date '1970-01-01', null, 'Käibemaksuseadus § 37 lõige 8 punkt 1 — nullmääraga maksustatava käibe puhul viide § 15 lõike 3 vastavale punktile või direktiivi artiklile 138'),
  ('EE', 'intracom_services', 'intra_eu_services', 'Pöördmaksustamine — käibemaksu tasub teenuse saaja. Nõukogu direktiivi 2006/112/EÜ artiklid 44 ja 196.', '{"en":"Reverse charge — value added tax is payable by the recipient of the service. Council Directive 2006/112/EC, Articles 44 and 196."}'::jsonb, 30, date '1970-01-01', null, 'Käibemaksuseadus § 37 lõige 8 punkt 2 koostoimes § 10 lõikega 1 — teenuse käibe tekkimise koht ei ole Eesti ja maksu tasub saaja'),
  ('EE', 'exempt', 'exempt', 'Maksuvaba käive — KMS § 16.', '{"en":"Supply exempt from tax — VAT Act § 16."}'::jsonb, 40, date '1970-01-01', null, 'Käibemaksuseadus § 37 lõige 8 punkt 1 — maksuvaba käibe puhul viide § 16 vastavale lõikele ja punktile'),
  ('EE', 'small_business', 'small_business', 'Käibemaksu ei lisata — väikeettevõtja ei ole maksukohustuslasena registreeritud (KMS § 19).', '{"en":"No value added tax is added — the undertaking is not registered as a taxable person (VAT Act § 19)."}'::jsonb, 50, date '1970-01-01', null, 'Käibemaksuseadus § 19 lõige 1 — registreerimiskohustus tekib, kui maksustatav käive ületab kalendriaasta algusest arvates 40 000 eurot'),
  ('EE', 'late_payment', 'late_payment', 'Tasumisega viivitamise korral on müüjal õigus nõuda viivist võlaõigusseaduse § 113 lõikes 1 sätestatud määras ning sissenõudmiskulude hüvitist 40 eurot.', '{"en":"Where payment is late, the seller may claim penalty interest at the rate laid down in § 113 (1) of the Law of Obligations Act and compensation for collection costs of 40 euros."}'::jsonb, 60, date '1970-01-01', null, 'Võlaõigusseadus § 113 lõige 1 ja § 113¹ lõige 1')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
