-- Ekwo OS — Jersey: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/je at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build je`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Goods and Services Tax (Jersey) Law 2007 (Jersey Law (Jersey Legal Information Board))
--     https://www.jerseylaw.je/laws/current/l_27_2007
--   Submit your GST return (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/TaxesMoney/GST/Businesses/SubmittingReturn/Pages/Return.aspx
--   GST taxed on goods and services (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/TaxesMoney/GST/Businesses/Introduction/pages/whattaxed.aspx
--   GST registration thresholds (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/TaxesMoney/GST/Businesses/Registration/pages/shouldibe.aspx
--   Overseas retailers' GST guidance notes (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/TaxesMoney/GST/Businesses/Industry/pages/overseasretailersgst.aspx
--   Supplying goods and services from outside Jersey (GST) (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/TaxesMoney/GST/Businesses/Introduction/pages/placesupply.aspx
--   GST on goods and services supplied to an ISE (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/TaxesMoney/GST/InternationalServiceEntities/Pages/Supplies.aspx
--   Keeping records and accounts for GST (Government of Jersey — Revenue Jersey)
--     https://www.gov.je/taxesmoney/gst/businesses/submittingreturn/pages/keepingbooksrecords.aspx
--   Moving to Jersey: money and tax (Government of Jersey)
--     https://www.gov.je/LifeEvents/MovingToJersey/LivingInJersey/Pages/MoneyTax.aspx
--   Jersey Company Law Series: records, accounts, annual confirmation statement and audit requirements (Walkers)
--     https://www.walkersglobal.com/en/Insights/2024/10/Jersey-Company-Law-Series---records-accounts-annual-confirmation-statement-and-audit-requirements
--   FRS 102 The Financial Reporting Standard applicable in the UK and Republic of Ireland (Section 1A Small Entities) (Financial Reporting Council)
--     https://www.frc.org.uk/library/standards-codes-policy/accounting-and-reporting/uk-accounting-standards/frs-102/
--   Gov.je login services — one.gov.je and CAESAR (Government of Jersey)
--     https://www.gov.je/pages/login.aspx
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('JE', 'Jersey', '0.1.0', date '2026-10-10', '20260917170000', 'community', null, null, 'ceb54d5840381aac908ed26d7ab2646f456a9de0322a3a4c96f528cb04c7c1f0', '[{"key":"je-gst-law","title":"Goods and Services Tax (Jersey) Law 2007","publisher":"Jersey Law (Jersey Legal Information Board)","url":"https://www.jerseylaw.je/laws/current/l_27_2007","consulted_on":"2026-10-10","kind":"law"},{"key":"je-gst-return","title":"Submit your GST return","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/TaxesMoney/GST/Businesses/SubmittingReturn/Pages/Return.aspx","consulted_on":"2026-10-10","kind":"form"},{"key":"je-gst-taxed","title":"GST taxed on goods and services","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/TaxesMoney/GST/Businesses/Introduction/pages/whattaxed.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-gst-registration","title":"GST registration thresholds","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/TaxesMoney/GST/Businesses/Registration/pages/shouldibe.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-gst-overseas","title":"Overseas retailers'' GST guidance notes","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/TaxesMoney/GST/Businesses/Industry/pages/overseasretailersgst.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-gst-place-of-supply","title":"Supplying goods and services from outside Jersey (GST)","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/TaxesMoney/GST/Businesses/Introduction/pages/placesupply.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-gst-ise-supplies","title":"GST on goods and services supplied to an ISE","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/TaxesMoney/GST/InternationalServiceEntities/Pages/Supplies.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-gst-records","title":"Keeping records and accounts for GST","publisher":"Government of Jersey — Revenue Jersey","url":"https://www.gov.je/taxesmoney/gst/businesses/submittingreturn/pages/keepingbooksrecords.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-money-tax","title":"Moving to Jersey: money and tax","publisher":"Government of Jersey","url":"https://www.gov.je/LifeEvents/MovingToJersey/LivingInJersey/Pages/MoneyTax.aspx","consulted_on":"2026-10-10","kind":"guidance"},{"key":"je-companies-walkers","title":"Jersey Company Law Series: records, accounts, annual confirmation statement and audit requirements","publisher":"Walkers","url":"https://www.walkersglobal.com/en/Insights/2024/10/Jersey-Company-Law-Series---records-accounts-annual-confirmation-statement-and-audit-requirements","consulted_on":"2026-10-10","kind":"guidance"},{"key":"frs-102","title":"FRS 102 The Financial Reporting Standard applicable in the UK and Republic of Ireland (Section 1A Small Entities)","publisher":"Financial Reporting Council","url":"https://www.frc.org.uk/library/standards-codes-policy/accounting-and-reporting/uk-accounting-standards/frs-102/","consulted_on":"2026-10-10","kind":"standard"},{"key":"je-login","title":"Gov.je login services — one.gov.je and CAESAR","publisher":"Government of Jersey","url":"https://www.gov.je/pages/login.aspx","consulted_on":"2026-10-10","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('JE', 'default', 'Jersey reference chart of accounts', '{}'::jsonb, true, 'companies', array['JE-FRS102-1A-BS', 'JE-FRS102-1A-IS']::text[], null, 'There is no legal chart of accounts in Jersey. The Companies (Jersey) Law 1991 requires a company to keep accounting records sufficient to show and explain its transactions and to disclose its financial position with reasonable accuracy, to preserve them for at least ten years from the date they are made, and to have its directors prepare accounts in accordance with generally accepted accounting principles that the accounts state (Walkers, consulted 2026-10-10; the text of the Law itself was not opened, see the README). The Law prescribes no chart and no format. This chart is original and follows British bookkeeping practice, because the principles most Jersey companies declare are UK GAAP (FRS 102), with IFRS the other common choice: four digits, blocked so that each range reaches one line of the balance sheet and the profit and loss account of FRS 102 Section 1A (small entities) in the layout statements.json carries. It has no United Kingdom value added tax, PAYE or CIS account, because Jersey is outside the United Kingdom VAT system; it carries the accounts of the Jersey goods and services tax instead: input tax (1140), output tax (2210), import GST owed to Customs (2215), and the two settlement accounts a filed return clears (2230 payable, 1145 refundable), which are the only accounts besides trade debtors and creditors that can be reconciled.', 'je-companies-walkers')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('JE', 'default', '0000', 'Called up share capital not paid', '{}'::jsonb, 'asset_current', false, null, 10),
  ('JE', 'default', '0010', 'Goodwill', '{}'::jsonb, 'asset_fixed', false, null, 20),
  ('JE', 'default', '0011', 'Goodwill — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 30),
  ('JE', 'default', '0020', 'Development costs', '{}'::jsonb, 'asset_fixed', false, null, 40),
  ('JE', 'default', '0021', 'Development costs — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 50),
  ('JE', 'default', '0030', 'Patents, trade marks and licences', '{}'::jsonb, 'asset_fixed', false, null, 60),
  ('JE', 'default', '0031', 'Patents, trade marks and licences — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 70),
  ('JE', 'default', '0040', 'Other intangible assets', '{}'::jsonb, 'asset_fixed', false, null, 80),
  ('JE', 'default', '0041', 'Other intangible assets — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 90),
  ('JE', 'default', '0100', 'Freehold land and buildings', '{}'::jsonb, 'asset_fixed', false, null, 100),
  ('JE', 'default', '0101', 'Freehold land and buildings — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 110),
  ('JE', 'default', '0110', 'Leasehold property and improvements', '{}'::jsonb, 'asset_fixed', false, null, 120),
  ('JE', 'default', '0111', 'Leasehold property and improvements — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 130),
  ('JE', 'default', '0120', 'Plant and machinery', '{}'::jsonb, 'asset_fixed', false, null, 140),
  ('JE', 'default', '0121', 'Plant and machinery — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 150),
  ('JE', 'default', '0130', 'Fixtures and fittings', '{}'::jsonb, 'asset_fixed', false, null, 160),
  ('JE', 'default', '0131', 'Fixtures and fittings — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 170),
  ('JE', 'default', '0140', 'Office equipment', '{}'::jsonb, 'asset_fixed', false, null, 180),
  ('JE', 'default', '0141', 'Office equipment — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 190),
  ('JE', 'default', '0150', 'Computer equipment', '{}'::jsonb, 'asset_fixed', false, null, 200),
  ('JE', 'default', '0151', 'Computer equipment — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 210),
  ('JE', 'default', '0160', 'Motor vehicles', '{}'::jsonb, 'asset_fixed', false, null, 220),
  ('JE', 'default', '0161', 'Motor vehicles — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 230),
  ('JE', 'default', '0200', 'Shares in group undertakings and participating interests', '{}'::jsonb, 'asset_non_current', false, null, 240),
  ('JE', 'default', '0210', 'Loans to group undertakings and undertakings in which the company has a participating interest', '{}'::jsonb, 'asset_non_current', false, null, 250),
  ('JE', 'default', '0220', 'Other investments other than loans', '{}'::jsonb, 'asset_non_current', false, null, 260),
  ('JE', 'default', '0230', 'Other investments', '{}'::jsonb, 'asset_non_current', false, null, 270),
  ('JE', 'default', '1000', 'Stock — raw materials and consumables', '{}'::jsonb, 'asset_current', false, null, 280),
  ('JE', 'default', '1010', 'Stock — work in progress', '{}'::jsonb, 'asset_current', false, null, 290),
  ('JE', 'default', '1020', 'Stock — finished goods and goods for resale', '{}'::jsonb, 'asset_current', false, null, 300),
  ('JE', 'default', '1030', 'Payments on account — stocks', '{}'::jsonb, 'asset_prepayments', false, null, 310),
  ('JE', 'default', '1100', 'Trade debtors', '{}'::jsonb, 'asset_receivable', true, null, 320),
  ('JE', 'default', '1105', 'Provision for doubtful debts', '{}'::jsonb, 'asset_current', false, null, 330),
  ('JE', 'default', '1110', 'Amounts owed by group undertakings and undertakings in which the company has a participating interest', '{}'::jsonb, 'asset_current', false, null, 340),
  ('JE', 'default', '1120', 'Other debtors', '{}'::jsonb, 'asset_current', false, null, 350),
  ('JE', 'default', '1130', 'Directors'' loan account — debit', '{}'::jsonb, 'asset_current', false, null, 360),
  ('JE', 'default', '1140', 'GST input tax on purchases', '{}'::jsonb, 'asset_current', false, null, 370),
  ('JE', 'default', '1145', 'GST refundable — net of a filed return', '{}'::jsonb, 'asset_current', true, null, 380),
  ('JE', 'default', '1150', 'Income tax recoverable', '{}'::jsonb, 'asset_current', false, null, 390),
  ('JE', 'default', '1160', 'Employee advances and expense claims', '{}'::jsonb, 'asset_current', false, null, 400),
  ('JE', 'default', '1200', 'Shares in group undertakings — held as a current asset', '{}'::jsonb, 'asset_current', false, null, 410),
  ('JE', 'default', '1210', 'Other investments — held as a current asset', '{}'::jsonb, 'asset_current', false, null, 420),
  ('JE', 'default', '1300', 'Bank current account', '{}'::jsonb, 'asset_cash', false, null, 430),
  ('JE', 'default', '1310', 'Bank deposit account', '{}'::jsonb, 'asset_cash', false, null, 440),
  ('JE', 'default', '1320', 'Bank account in a foreign currency', '{}'::jsonb, 'asset_cash', false, null, 450),
  ('JE', 'default', '1330', 'Petty cash', '{}'::jsonb, 'asset_cash', false, null, 460),
  ('JE', 'default', '1340', 'Cash in transit', '{}'::jsonb, 'asset_cash', false, null, 470),
  ('JE', 'default', '1350', 'Card acquirer settlement account', '{}'::jsonb, 'asset_cash', false, null, 480),
  ('JE', 'default', '1400', 'Prepayments', '{}'::jsonb, 'asset_prepayments', false, null, 490),
  ('JE', 'default', '1410', 'Accrued income', '{}'::jsonb, 'asset_prepayments', false, null, 500),
  ('JE', 'default', '1420', 'Payments on account to suppliers', '{}'::jsonb, 'asset_prepayments', false, null, 510),
  ('JE', 'default', '2000', 'Bank loans — due within one year', '{}'::jsonb, 'liability_current', false, null, 520),
  ('JE', 'default', '2010', 'Bank overdraft', '{}'::jsonb, 'liability_current', false, null, 530),
  ('JE', 'default', '2020', 'Credit card account', '{}'::jsonb, 'liability_credit_card', false, null, 540),
  ('JE', 'default', '2100', 'Trade creditors', '{}'::jsonb, 'liability_payable', true, null, 550),
  ('JE', 'default', '2110', 'Amounts owed to group undertakings and undertakings in which the company has a participating interest', '{}'::jsonb, 'liability_current', false, null, 560),
  ('JE', 'default', '2210', 'GST output tax on sales', '{}'::jsonb, 'liability_current', false, null, 570),
  ('JE', 'default', '2215', 'GST on imports payable to Customs', '{}'::jsonb, 'liability_current', false, null, 580),
  ('JE', 'default', '2220', 'Income tax (employees) and social security contributions payable', '{}'::jsonb, 'liability_current', false, null, 590),
  ('JE', 'default', '2230', 'GST payable — net of a filed return', '{}'::jsonb, 'liability_current', true, null, 600),
  ('JE', 'default', '2240', 'Pension contributions payable', '{}'::jsonb, 'liability_current', false, null, 610),
  ('JE', 'default', '2250', 'Net wages payable', '{}'::jsonb, 'liability_current', false, null, 620),
  ('JE', 'default', '2260', 'Directors'' loan account — credit', '{}'::jsonb, 'liability_current', false, null, 630),
  ('JE', 'default', '2270', 'Dividends payable', '{}'::jsonb, 'liability_current', false, null, 640),
  ('JE', 'default', '2280', 'Income tax payable', '{}'::jsonb, 'liability_current', false, null, 650),
  ('JE', 'default', '2290', 'Other creditors', '{}'::jsonb, 'liability_current', false, null, 660),
  ('JE', 'default', '2300', 'Obligations under finance leases and hire purchase — due within one year', '{}'::jsonb, 'liability_current', false, null, 670),
  ('JE', 'default', '2400', 'Suspense account', '{}'::jsonb, 'liability_current', false, null, 680),
  ('JE', 'default', '3000', 'Bank loans — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 690),
  ('JE', 'default', '3010', 'Other loans — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 700),
  ('JE', 'default', '3020', 'Trade creditors — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 710),
  ('JE', 'default', '3030', 'Amounts owed to group undertakings and undertakings in which the company has a participating interest — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 720),
  ('JE', 'default', '3040', 'Obligations under finance leases and hire purchase — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 730),
  ('JE', 'default', '3050', 'Other creditors — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 740),
  ('JE', 'default', '3100', 'Provision for deferred taxation', '{}'::jsonb, 'liability_non_current', false, null, 750),
  ('JE', 'default', '3110', 'Other provisions for liabilities', '{}'::jsonb, 'liability_non_current', false, null, 760),
  ('JE', 'default', '3200', 'Accruals', '{}'::jsonb, 'liability_current', false, null, 770),
  ('JE', 'default', '3210', 'Deferred income', '{}'::jsonb, 'liability_current', false, null, 780),
  ('JE', 'default', '3300', 'Called up share capital', '{}'::jsonb, 'equity', false, null, 790),
  ('JE', 'default', '3310', 'Share premium account', '{}'::jsonb, 'equity', false, null, 800),
  ('JE', 'default', '3320', 'Revaluation reserve', '{}'::jsonb, 'equity', false, null, 810),
  ('JE', 'default', '3330', 'Capital redemption reserve', '{}'::jsonb, 'equity', false, null, 820),
  ('JE', 'default', '3340', 'Other reserves', '{}'::jsonb, 'equity', false, null, 830),
  ('JE', 'default', '3400', 'Profit and loss account', '{}'::jsonb, 'equity_retained', false, null, 840),
  ('JE', 'default', '3410', 'Dividends paid', '{}'::jsonb, 'equity_retained', false, null, 850),
  ('JE', 'default', '4000', 'Sales — goods', '{}'::jsonb, 'income', false, null, 860),
  ('JE', 'default', '4010', 'Sales — services', '{}'::jsonb, 'income', false, null, 870),
  ('JE', 'default', '4050', 'Sales — exports of goods', '{}'::jsonb, 'income', false, null, 880),
  ('JE', 'default', '4070', 'Retail takings', '{}'::jsonb, 'income', false, null, 890),
  ('JE', 'default', '4100', 'Sales returns and allowances', '{}'::jsonb, 'income', false, null, 900),
  ('JE', 'default', '4110', 'Discounts allowed', '{}'::jsonb, 'income', false, null, 910),
  ('JE', 'default', '4200', 'Other operating income', '{}'::jsonb, 'income_other', false, null, 920),
  ('JE', 'default', '4210', 'Rental income', '{}'::jsonb, 'income_other', false, null, 930),
  ('JE', 'default', '4220', 'Grants receivable', '{}'::jsonb, 'income_other', false, null, 940),
  ('JE', 'default', '4230', 'Profit on disposal of fixed assets', '{}'::jsonb, 'income_other', false, null, 950),
  ('JE', 'default', '4240', 'Foreign exchange gains', '{}'::jsonb, 'income_other', false, null, 960),
  ('JE', 'default', '4300', 'Income from shares in group undertakings', '{}'::jsonb, 'income_other', false, null, 970),
  ('JE', 'default', '4310', 'Income from participating interests', '{}'::jsonb, 'income_other', false, null, 980),
  ('JE', 'default', '4320', 'Income from other fixed asset investments', '{}'::jsonb, 'income_other', false, null, 990),
  ('JE', 'default', '4330', 'Other interest receivable and similar income', '{}'::jsonb, 'income_other', false, null, 1000),
  ('JE', 'default', '5000', 'Purchases — goods for resale', '{}'::jsonb, 'expense_direct_cost', false, null, 1010),
  ('JE', 'default', '5010', 'Purchases — raw materials and consumables', '{}'::jsonb, 'expense_direct_cost', false, null, 1020),
  ('JE', 'default', '5020', 'Carriage inwards', '{}'::jsonb, 'expense_direct_cost', false, null, 1030),
  ('JE', 'default', '5030', 'Import duty and freight', '{}'::jsonb, 'expense_direct_cost', false, null, 1040),
  ('JE', 'default', '5040', 'Purchase returns and allowances', '{}'::jsonb, 'expense_direct_cost', false, null, 1050),
  ('JE', 'default', '5050', 'Discounts received', '{}'::jsonb, 'expense_direct_cost', false, null, 1060),
  ('JE', 'default', '5100', 'Opening stock', '{}'::jsonb, 'expense_direct_cost', false, null, 1070),
  ('JE', 'default', '5110', 'Closing stock', '{}'::jsonb, 'expense_direct_cost', false, null, 1080),
  ('JE', 'default', '5200', 'Subcontractor costs', '{}'::jsonb, 'expense_direct_cost', false, null, 1090),
  ('JE', 'default', '5210', 'Direct labour', '{}'::jsonb, 'expense_direct_cost', false, null, 1100),
  ('JE', 'default', '5220', 'Direct expenses — plant and equipment hire', '{}'::jsonb, 'expense_direct_cost', false, null, 1110),
  ('JE', 'default', '5230', 'Direct expenses — materials', '{}'::jsonb, 'expense_direct_cost', false, null, 1120),
  ('JE', 'default', '5240', 'Direct expenses — other', '{}'::jsonb, 'expense_direct_cost', false, null, 1130),
  ('JE', 'default', '6000', 'Advertising', '{}'::jsonb, 'expense', false, null, 1140),
  ('JE', 'default', '6010', 'Marketing and promotion', '{}'::jsonb, 'expense', false, null, 1150),
  ('JE', 'default', '6020', 'Website and online advertising', '{}'::jsonb, 'expense', false, null, 1160),
  ('JE', 'default', '6100', 'Carriage outwards', '{}'::jsonb, 'expense', false, null, 1170),
  ('JE', 'default', '6110', 'Packaging', '{}'::jsonb, 'expense', false, null, 1180),
  ('JE', 'default', '6200', 'Distribution staff — wages and salaries', '{}'::jsonb, 'expense', false, null, 1190),
  ('JE', 'default', '6210', 'Distribution staff — employer''s social security contributions', '{}'::jsonb, 'expense', false, null, 1200),
  ('JE', 'default', '6220', 'Distribution staff — employer''s pension contributions', '{}'::jsonb, 'expense', false, null, 1210),
  ('JE', 'default', '6230', 'Sales commission', '{}'::jsonb, 'expense', false, null, 1220),
  ('JE', 'default', '6300', 'Delivery vehicle running costs', '{}'::jsonb, 'expense', false, null, 1230),
  ('JE', 'default', '6310', 'Travelling — distribution', '{}'::jsonb, 'expense', false, null, 1240),
  ('JE', 'default', '6400', 'Warehouse rent and property rates', '{}'::jsonb, 'expense', false, null, 1250),
  ('JE', 'default', '6410', 'Warehouse light and heat', '{}'::jsonb, 'expense', false, null, 1260),
  ('JE', 'default', '6420', 'Warehouse insurance', '{}'::jsonb, 'expense', false, null, 1270),
  ('JE', 'default', '6500', 'Depreciation — distribution assets', '{}'::jsonb, 'expense_depreciation', false, null, 1280),
  ('JE', 'default', '7000', 'Directors'' remuneration', '{}'::jsonb, 'expense', false, null, 1290),
  ('JE', 'default', '7010', 'Wages and salaries', '{}'::jsonb, 'expense', false, null, 1300),
  ('JE', 'default', '7020', 'Employer''s social security contributions', '{}'::jsonb, 'expense', false, null, 1310),
  ('JE', 'default', '7030', 'Employer''s pension contributions', '{}'::jsonb, 'expense', false, null, 1320),
  ('JE', 'default', '7040', 'Staff training', '{}'::jsonb, 'expense', false, null, 1330),
  ('JE', 'default', '7050', 'Staff welfare', '{}'::jsonb, 'expense', false, null, 1340),
  ('JE', 'default', '7060', 'Recruitment costs', '{}'::jsonb, 'expense', false, null, 1350),
  ('JE', 'default', '7070', 'Temporary and agency staff', '{}'::jsonb, 'expense', false, null, 1360),
  ('JE', 'default', '7100', 'Rent', '{}'::jsonb, 'expense', false, null, 1370),
  ('JE', 'default', '7110', 'Parish rates', '{}'::jsonb, 'expense', false, null, 1380),
  ('JE', 'default', '7120', 'Light and heat', '{}'::jsonb, 'expense', false, null, 1390),
  ('JE', 'default', '7130', 'Water rates', '{}'::jsonb, 'expense', false, null, 1400),
  ('JE', 'default', '7140', 'Insurance', '{}'::jsonb, 'expense', false, null, 1410),
  ('JE', 'default', '7150', 'Repairs and maintenance', '{}'::jsonb, 'expense', false, null, 1420),
  ('JE', 'default', '7160', 'Cleaning', '{}'::jsonb, 'expense', false, null, 1430),
  ('JE', 'default', '7170', 'Security', '{}'::jsonb, 'expense', false, null, 1440),
  ('JE', 'default', '7200', 'Telephone and internet', '{}'::jsonb, 'expense', false, null, 1450),
  ('JE', 'default', '7210', 'Postage and carriage', '{}'::jsonb, 'expense', false, null, 1460),
  ('JE', 'default', '7220', 'Printing and stationery', '{}'::jsonb, 'expense', false, null, 1470),
  ('JE', 'default', '7230', 'Software and subscriptions', '{}'::jsonb, 'expense', false, null, 1480),
  ('JE', 'default', '7240', 'Computer and IT costs', '{}'::jsonb, 'expense', false, null, 1490),
  ('JE', 'default', '7250', 'Equipment hire', '{}'::jsonb, 'expense', false, null, 1500),
  ('JE', 'default', '7260', 'Sundry expenses', '{}'::jsonb, 'expense', false, null, 1510),
  ('JE', 'default', '7300', 'Motor vehicle running costs', '{}'::jsonb, 'expense', false, null, 1520),
  ('JE', 'default', '7310', 'Motor vehicle leasing and hire', '{}'::jsonb, 'expense', false, null, 1530),
  ('JE', 'default', '7320', 'Travel and subsistence', '{}'::jsonb, 'expense', false, null, 1540),
  ('JE', 'default', '7330', 'Business entertainment', '{}'::jsonb, 'expense', false, null, 1550),
  ('JE', 'default', '7400', 'Accountancy fees', '{}'::jsonb, 'expense', false, null, 1560),
  ('JE', 'default', '7410', 'Legal and professional fees', '{}'::jsonb, 'expense', false, null, 1570),
  ('JE', 'default', '7420', 'Consultancy fees', '{}'::jsonb, 'expense', false, null, 1580),
  ('JE', 'default', '7430', 'Audit fee', '{}'::jsonb, 'expense', false, null, 1590),
  ('JE', 'default', '7440', 'Bank charges', '{}'::jsonb, 'expense', false, null, 1600),
  ('JE', 'default', '7450', 'Card processing charges', '{}'::jsonb, 'expense', false, null, 1610),
  ('JE', 'default', '7460', 'Subscriptions to professional bodies', '{}'::jsonb, 'expense', false, null, 1620),
  ('JE', 'default', '7470', 'Charitable donations', '{}'::jsonb, 'expense', false, null, 1630),
  ('JE', 'default', '7500', 'Bad debts written off', '{}'::jsonb, 'expense', false, null, 1640),
  ('JE', 'default', '7510', 'Movement in the provision for doubtful debts', '{}'::jsonb, 'expense', false, null, 1650),
  ('JE', 'default', '7600', 'Depreciation — freehold land and buildings', '{}'::jsonb, 'expense_depreciation', false, null, 1660),
  ('JE', 'default', '7610', 'Depreciation — leasehold property and improvements', '{}'::jsonb, 'expense_depreciation', false, null, 1670),
  ('JE', 'default', '7620', 'Depreciation — plant and machinery', '{}'::jsonb, 'expense_depreciation', false, null, 1680),
  ('JE', 'default', '7630', 'Depreciation — fixtures and fittings', '{}'::jsonb, 'expense_depreciation', false, null, 1690),
  ('JE', 'default', '7640', 'Depreciation — office equipment', '{}'::jsonb, 'expense_depreciation', false, null, 1700),
  ('JE', 'default', '7650', 'Depreciation — computer equipment', '{}'::jsonb, 'expense_depreciation', false, null, 1710),
  ('JE', 'default', '7660', 'Depreciation — motor vehicles', '{}'::jsonb, 'expense_depreciation', false, null, 1720),
  ('JE', 'default', '7670', 'Amortisation of goodwill', '{}'::jsonb, 'expense_depreciation', false, null, 1730),
  ('JE', 'default', '7680', 'Amortisation of other intangible assets', '{}'::jsonb, 'expense_depreciation', false, null, 1740),
  ('JE', 'default', '7690', 'Loss on disposal of fixed assets', '{}'::jsonb, 'expense', false, null, 1750),
  ('JE', 'default', '7700', 'Foreign exchange losses', '{}'::jsonb, 'expense', false, null, 1760),
  ('JE', 'default', '7710', 'Rounding differences', '{}'::jsonb, 'expense', false, null, 1770),
  ('JE', 'default', '8000', 'Bank interest payable', '{}'::jsonb, 'expense', false, null, 1780),
  ('JE', 'default', '8010', 'Loan interest payable', '{}'::jsonb, 'expense', false, null, 1790),
  ('JE', 'default', '8020', 'Finance lease and hire purchase interest', '{}'::jsonb, 'expense', false, null, 1800),
  ('JE', 'default', '8030', 'Other interest payable and similar expenses', '{}'::jsonb, 'expense', false, null, 1810),
  ('JE', 'default', '8040', 'Interest and recovery costs on late payment', '{}'::jsonb, 'expense', false, null, 1820),
  ('JE', 'default', '8100', 'Amounts written off investments', '{}'::jsonb, 'expense', false, null, 1830),
  ('JE', 'default', '8200', 'Income tax on profit or loss', '{}'::jsonb, 'expense', false, null, 1840),
  ('JE', 'default', '8210', 'Income tax — adjustment in respect of prior periods', '{}'::jsonb, 'expense', false, null, 1850),
  ('JE', 'default', '8220', 'Deferred taxation charge', '{}'::jsonb, 'expense', false, null, 1860),
  ('JE', 'default', '8300', 'Other taxes not shown under the above items', '{}'::jsonb, 'expense', false, null, 1870)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('JE', 'BNK', 'Bank', '{}'::jsonb, 'bank', 30),
  ('JE', 'CSH', 'Cash book', '{}'::jsonb, 'cash', 40),
  ('JE', 'GEN', 'General journal', '{}'::jsonb, 'general', 50),
  ('JE', 'OPN', 'Opening balances', '{}'::jsonb, 'opening', 60),
  ('JE', 'PUR', 'Purchase day book', '{}'::jsonb, 'purchase', 20),
  ('JE', 'SAL', 'Sales day book', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('JE', 'JE-P-BL', 'Purchase, GST 5 %, input tax not recoverable', '{}'::jsonb, 'A purchase whose input tax the business cannot credit, for instance because it makes exempt supplies', 'percent', 5, 'purchase', 'domestic', date '2011-06-01', null, 'Goods and Services Tax (Jersey) Law 2007, art. 33 and 34 (input tax credited against output tax) and the partial exemption rules for a business that also makes exempt supplies (Revenue Jersey, partial exemption booklet: the PDF could not be read as text, see the README). The GST lands on the cost; no box takes it. Box 4 takes the value.', null, null, 110, 'gst', false, array['supply_nature']::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-P-ES', 'Purchase, exempt', '{}'::jsonb, 'A purchase of an exempt supply', 'percent', 0, 'purchase', 'exempt', date '2008-05-06', null, 'Goods and Services Tax (Jersey) Law 2007, Schedule 5: an exempt supply carries no GST and gives no credit. Box 4 takes the value, which is a business cost from a Jersey supplier.', null, null, 130, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-P-IMP', 'Import of goods, GST 5 % paid to Customs', '{}'::jsonb, 'Goods imported into Jersey, the GST paid to Customs at the border', 'percent', 5, 'purchase', 'import', date '2011-06-01', null, 'Revenue Jersey, Supplying goods and services from outside Jersey (consulted 2026-10-10): goods imported into Jersey are subject to GST; a GST-registered importer that pays at the border recovers it as input tax. Box 5 takes the value of the imports without GST and box 7 the GST paid. The supplier is owed the value alone: the GST is owed to Customs and waits on 2215 until it is paid.', null, null, 150, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-place-of-supply', null, null, null, null),
  ('JE', 'JE-P-IMP-DEF', 'Import of goods, GST deferred by an approved customs trader', '{}'::jsonb, 'Goods imported by a GST-registered importer approved as a customs trader, GST accounted for on the return', 'percent', 5, 'purchase', 'import', date '2011-06-01', null, 'Revenue Jersey, Supplying goods and services from outside Jersey (consulted 2026-10-10): a GST-registered importer approved as a customs trader can defer payment; it excludes the GST at import and includes the goods'' value in box 5 of the return instead. The page does not say how the tax is shown in boxes 6 and 7; this code assumes the importer accounts for the GST as output tax (box 6) and claims it as input tax (box 7) in the same return, so the net is nil. A point for Revenue Jersey to confirm: see the README.', null, null, 160, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-place-of-supply', null, null, null, null),
  ('JE', 'JE-P-NR', 'Purchase with no GST — supplier not registered', '{}'::jsonb, 'A purchase from a supplier that does not charge GST', 'percent', 0, 'purchase', 'not_subject', date '2008-05-06', null, 'A business below the registration threshold of £300,000 of taxable supplies in twelve months need not register (Revenue Jersey, GST registration thresholds, consulted 2026-10-10) and charges no GST. Box 4 takes the value; there is no input tax.', null, null, 140, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-registration', null, null, null, null),
  ('JE', 'JE-P-RC', 'Service from abroad, reverse charge, GST 5 %, recoverable', '{}'::jsonb, 'A service supplied by a person belonging outside Jersey and received in Jersey', 'percent', 5, 'purchase', 'foreign_services_received', date '2008-05-06', null, 'Revenue Jersey, Supplying goods and services from outside Jersey (consulted 2026-10-10): a service can be supplied in Jersey even when supplied by someone belonging outside Jersey, and the Jersey customer receiving certain services from abroad self-assesses the GST by including the value in box 5 of the return. Same assumption on boxes 6 and 7 as JE-P-IMP-DEF.', null, null, 170, 'gst', true, array['supply_nature']::tax_condition[], null, false, false, null, 'je-gst-place-of-supply', null, null, null, null),
  ('JE', 'JE-P-TX', 'Purchase, standard-rated, GST 5 %', '{}'::jsonb, 'A purchase with GST charged by a GST-registered supplier in Jersey', 'percent', 5, 'purchase', 'domestic', date '2011-06-01', null, 'Goods and Services Tax (Jersey) Law 2007, art. 8(1): ''GST shall be charged at the rate of 5%'' (jerseylaw.je, consulted 2026-10-10). Revenue Jersey, GST taxed on goods and services: standard rate 5 %, applied to most goods and services, and no reduced rate. Input tax is the GST charged on goods and services used in the business; the law credits it against the output tax of the period and the excess is refundable as a GST credit (art. 33 and 34, as read in the part of the Law that was opened). Box 4 takes the value, box 7 the GST.', null, null, 100, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-P-ZR', 'Purchase, zero-rated', '{}'::jsonb, 'A purchase of zero-rated goods or services from a Jersey supplier', 'percent', 0, 'purchase', 'domestic', date '2008-05-06', null, 'Revenue Jersey, GST taxed on goods and services (consulted 2026-10-10): zero-rated supplies are taxed at 0 %. Box 4 takes the value.', null, null, 120, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-taxed', null, null, null, null),
  ('JE', 'JE-S-ES', 'Exempt supply', '{}'::jsonb, 'An exempt supply listed in Schedule 5: finance, insurance, postal services, medical and paramedical supplies, supplies by charities, child care, education, burial and cremation', 'percent', 0, 'sale', 'exempt', date '2008-05-06', null, 'Goods and Services Tax (Jersey) Law 2007, Schedule 5, Groups 1 to 8: finance, insurance, postal services, medical and paramedical supplies, supplies by charities, child care, education, burial and cremation (jerseylaw.je, consulted 2026-10-10; the conditions of each Group were not read in full). An exempt supply carries no GST, is not a taxable supply and is in no box of the return; the input tax on what went into it is restricted by the partial exemption rules, which the pack does not compute. No exemption reason code: the VATEX list names articles of the European Union VAT Directive, which does not bind a Jersey supplier.', 'E', null, 80, 'gst', true, array['supply_nature']::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-S-NS', 'Sale outside the scope of GST', '{}'::jsonb, 'A supply made outside Jersey by a Jersey business, or one that is not a supply for GST', 'percent', 0, 'sale', 'not_subject', date '2008-05-06', null, 'Revenue Jersey, Supplying goods and services from outside Jersey (consulted 2026-10-10) says a service can be supplied in Jersey even when the supplier belongs outside it; a supply whose place is outside Jersey is outside the scope of Jersey GST and is in no box. The United Kingdom''s VAT does not apply to a sale between Jersey and the United Kingdom, Jersey being outside the UK VAT system.', 'O', null, 90, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-place-of-supply', null, null, null, null),
  ('JE', 'JE-S-SR', 'Sale, standard-rated, GST 5 %', '{}'::jsonb, 'A taxable supply made in Jersey', 'percent', 5, 'sale', 'domestic', date '2011-06-01', null, 'Goods and Services Tax (Jersey) Law 2007, art. 8(1): ''GST shall be charged at the rate of 5%'' (jerseylaw.je, consulted 2026-10-10). Revenue Jersey, GST taxed on goods and services: standard rate 5 %, applied to most goods and services, and no reduced rate. The GST charged on the sale is output tax: box 6 of the GST return, and the value without GST is in box 1.', 'S', null, 10, 'gst', true, '{}'::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-S-SR-INC', 'Retail sale, standard-rated, GST 5 %, the price includes the GST', '{}'::jsonb, 'A taxable retail supply whose displayed price includes the GST', 'percent', 5, 'sale', 'domestic', date '2011-06-01', null, 'Goods and Services Tax (Jersey) Law 2007, art. 8(1): ''GST shall be charged at the rate of 5%'' (jerseylaw.je, consulted 2026-10-10). Revenue Jersey, GST taxed on goods and services: standard rate 5 %, applied to most goods and services, and no reduced rate. A price that includes the GST is the way a shop shows it; the engine takes the GST out of the gross. The simplified invoice Revenue Jersey allows for a retail sale up to £250 states the gross amount and the rate (Keeping records and accounts for GST, consulted 2026-10-10).', 'S', null, 20, 'gst', true, '{}'::tax_condition[], null, true, false, null, 'je-gst-records', null, null, null, null),
  ('JE', 'JE-S-ZR-DW', 'Supply of a dwelling, zero-rated', '{}'::jsonb, 'The supply of a dwelling, and the other zero-rated supplies of land', 'percent', 0, 'sale', 'domestic', date '2008-05-06', null, 'Goods and Services Tax (Jersey) Law 2007, Schedule 6 (''Supply of dwelling, and zero-rated supplies of land, services or material''; jerseylaw.je, consulted 2026-10-10) and Revenue Jersey, GST taxed on goods and services: housing is zero-rated. Which supplies of land fall in the Part is a classification the ledger cannot see; the wording of the Part was not read in full.', 'Z', null, 60, 'gst', true, array['supply_nature']::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-S-ZR-EXP', 'Export of goods, zero-rated', '{}'::jsonb, 'An export of goods from Jersey', 'percent', 0, 'sale', 'export', date '2008-05-06', null, 'Goods and Services Tax (Jersey) Law 2007, Schedule 6 (''Zero-rating of exports''; jerseylaw.je, consulted 2026-10-10), and Revenue Jersey, GST taxed on goods and services: exports of goods are zero-rated. The sale is a taxable supply at 0 %: box 1 and box 2 of the return both take its value, so that box 3 (sales subject to GST) leaves it out. The supplier must hold evidence that the goods left Jersey.', 'G', null, 30, 'gst', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-S-ZR-INTL', 'International service, zero-rated', '{}'::jsonb, 'A service supplied under a contract with a person who belongs outside Jersey and benefits a person who belongs outside Jersey', 'percent', 0, 'sale', 'export', date '2008-05-06', null, 'Goods and Services Tax (Jersey) Law 2007, Schedule 6, paragraph 5 (''Supply of international services zero-rated''; the paragraph''s wording was not read in full, see the README): services supplied to a person who belongs outside Jersey and that benefit a person who belongs outside Jersey are zero-rated, with those relating to land or goods situated in Jersey left out (Revenue Jersey, GST taxed on goods and services, consulted 2026-10-10: ''international services''). Boxes 1 and 2.', 'G', null, 40, 'gst', true, array['supply_nature', 'buyer_status']::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null),
  ('JE', 'JE-S-ZR-ISE', 'Remitted supply to an International Services Entity, zero-rated', '{}'::jsonb, 'A supply to an approved International Services Entity for the purpose of its business, on the entity''s end user relief certificate', 'percent', 0, 'sale', 'domestic', date '2008-05-06', null, 'Revenue Jersey, GST on goods and services supplied to an ISE (consulted 2026-10-10): supplies to an approved ISE for the purpose of a business carried on through it are ''remitted supplies'', treated as zero-rated for the return and shown in box 2 with the value of zero-rated supplies; the page tells the supplier to use the GST code used for zero-rated sales such as exports. A retailer may charge GST on an individual sale to an ISE under £1,000, which the ISE reclaims. The ISE regime itself (annual fee instead of GST) is not in this pack: see the README.', 'Z', null, 50, 'gst', true, array['buyer_certificate']::tax_condition[], null, false, false, null, 'je-gst-ise-supplies', null, null, null, null),
  ('JE', 'JE-S-ZR-RX', 'Medicine on prescription, zero-rated', '{}'::jsonb, 'A medicine supplied on prescription', 'percent', 0, 'sale', 'domestic', date '2008-05-06', null, 'Goods and Services Tax (Jersey) Law 2007, Schedule 6 (''Zero-rating of medicines on prescription''; jerseylaw.je, consulted 2026-10-10) and Revenue Jersey, GST taxed on goods and services: ''medical prescriptions'' are zero-rated.', 'Z', null, 70, 'gst', true, array['supply_nature']::tax_condition[], null, false, false, null, 'je-gst-law', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('JE-P-BL', 'invoice', 'base', 100, null, '4', array['4']::text[], 100, 'JE-GST', 10),
    ('JE-P-BL', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('JE-P-BL', 'credit_note', 'base', 100, null, '4', array['4']::text[], -100, 'JE-GST', 10),
    ('JE-P-BL', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 20),
    ('JE-P-ES', 'invoice', 'base', 100, null, '4', array['4']::text[], 100, 'JE-GST', 10),
    ('JE-P-ES', 'credit_note', 'base', 100, null, '4', array['4']::text[], -100, 'JE-GST', 10),
    ('JE-P-IMP', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'JE-GST', 10),
    ('JE-P-IMP', 'invoice', 'tax', 100, '1140', '7', array['7']::text[], 100, 'JE-GST', 20),
    ('JE-P-IMP', 'invoice', 'tax', -100, '2215', null, null, 100, null, 30),
    ('JE-P-IMP', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'JE-GST', 10),
    ('JE-P-IMP', 'credit_note', 'tax', 100, '1140', '7', array['7']::text[], -100, 'JE-GST', 20),
    ('JE-P-IMP', 'credit_note', 'tax', -100, '2215', null, null, 100, null, 30),
    ('JE-P-IMP-DEF', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'JE-GST', 10),
    ('JE-P-IMP-DEF', 'invoice', 'tax', 100, '1140', '7', array['7']::text[], 100, 'JE-GST', 20),
    ('JE-P-IMP-DEF', 'invoice', 'tax', -100, '2210', '6', array['6']::text[], 100, 'JE-GST', 30),
    ('JE-P-IMP-DEF', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'JE-GST', 10),
    ('JE-P-IMP-DEF', 'credit_note', 'tax', 100, '1140', '7', array['7']::text[], -100, 'JE-GST', 20),
    ('JE-P-IMP-DEF', 'credit_note', 'tax', -100, '2210', '6', array['6']::text[], -100, 'JE-GST', 30),
    ('JE-P-NR', 'invoice', 'base', 100, null, '4', array['4']::text[], 100, 'JE-GST', 10),
    ('JE-P-NR', 'credit_note', 'base', 100, null, '4', array['4']::text[], -100, 'JE-GST', 10),
    ('JE-P-RC', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'JE-GST', 10),
    ('JE-P-RC', 'invoice', 'tax', 100, '1140', '7', array['7']::text[], 100, 'JE-GST', 20),
    ('JE-P-RC', 'invoice', 'tax', -100, '2210', '6', array['6']::text[], 100, 'JE-GST', 30),
    ('JE-P-RC', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'JE-GST', 10),
    ('JE-P-RC', 'credit_note', 'tax', 100, '1140', '7', array['7']::text[], -100, 'JE-GST', 20),
    ('JE-P-RC', 'credit_note', 'tax', -100, '2210', '6', array['6']::text[], -100, 'JE-GST', 30),
    ('JE-P-TX', 'invoice', 'base', 100, null, '4', array['4']::text[], 100, 'JE-GST', 10),
    ('JE-P-TX', 'invoice', 'tax', 100, '1140', '7', array['7']::text[], 100, 'JE-GST', 20),
    ('JE-P-TX', 'credit_note', 'base', 100, null, '4', array['4']::text[], -100, 'JE-GST', 10),
    ('JE-P-TX', 'credit_note', 'tax', 100, '1140', '7', array['7']::text[], -100, 'JE-GST', 20),
    ('JE-P-ZR', 'invoice', 'base', 100, null, '4', array['4']::text[], 100, 'JE-GST', 10),
    ('JE-P-ZR', 'credit_note', 'base', 100, null, '4', array['4']::text[], -100, 'JE-GST', 10),
    ('JE-S-ES', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('JE-S-ES', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('JE-S-NS', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('JE-S-NS', 'credit_note', 'base', 100, null, null, null, 100, null, 10),
    ('JE-S-SR', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'JE-GST', 10),
    ('JE-S-SR', 'invoice', 'tax', 100, '2210', '6', array['6']::text[], 100, 'JE-GST', 20),
    ('JE-S-SR', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'JE-GST', 10),
    ('JE-S-SR', 'credit_note', 'tax', 100, '2210', '6', array['6']::text[], -100, 'JE-GST', 20),
    ('JE-S-SR-INC', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'JE-GST', 10),
    ('JE-S-SR-INC', 'invoice', 'tax', 100, '2210', '6', array['6']::text[], 100, 'JE-GST', 20),
    ('JE-S-SR-INC', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'JE-GST', 10),
    ('JE-S-SR-INC', 'credit_note', 'tax', 100, '2210', '6', array['6']::text[], -100, 'JE-GST', 20),
    ('JE-S-ZR-DW', 'invoice', 'base', 100, null, '1', array['1', '2']::text[], 100, 'JE-GST', 10),
    ('JE-S-ZR-DW', 'credit_note', 'base', 100, null, '1', array['1', '2']::text[], -100, 'JE-GST', 10),
    ('JE-S-ZR-EXP', 'invoice', 'base', 100, null, '1', array['1', '2']::text[], 100, 'JE-GST', 10),
    ('JE-S-ZR-EXP', 'credit_note', 'base', 100, null, '1', array['1', '2']::text[], -100, 'JE-GST', 10),
    ('JE-S-ZR-INTL', 'invoice', 'base', 100, null, '1', array['1', '2']::text[], 100, 'JE-GST', 10),
    ('JE-S-ZR-INTL', 'credit_note', 'base', 100, null, '1', array['1', '2']::text[], -100, 'JE-GST', 10),
    ('JE-S-ZR-ISE', 'invoice', 'base', 100, null, '1', array['1', '2']::text[], 100, 'JE-GST', 10),
    ('JE-S-ZR-ISE', 'credit_note', 'base', 100, null, '1', array['1', '2']::text[], -100, 'JE-GST', 10),
    ('JE-S-ZR-RX', 'invoice', 'base', 100, null, '1', array['1', '2']::text[], 100, 'JE-GST', 10),
    ('JE-S-ZR-RX', 'credit_note', 'base', 100, null, '1', array['1', '2']::text[], -100, 'JE-GST', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'JE' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('JE', 'JE-GST', 'GST return (Revenue Jersey)', array['quarter']::declaration_period[], 'quarter'::declaration_period, date '2008-05-06', null, 'Revenue Jersey, Submit your GST return and GST registration thresholds (consulted 2026-10-10): GST returns are quarterly (January to March, April to June, July to September, October to December) unless the registration letter says otherwise, and are completed online with the business''s Tax Identification Number and GST reference. The return has eight boxes, not the nine of the United Kingdom VAT return. Monthly returns and other cadences the registration letter may set are not declared: no page opened says so.', true,'last_day_of_month_after_period'::filing_deadline_rule, null, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10): ''Your return is due for submission no later than the last day of the month following the return period'', so 30 April for January to March; the registration page adds that payment is due within one month of quarter-end. Penalties and surcharges for late filing are not modelled.', 'je-gst-return', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('JE', 'JE-GST', '1', 'base', 'Total sales excluding GST', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 1 — the net value of all taxable sales, zero-rated sales included; exempt supplies are not taxable supplies and are left out. Credit notes reduce it.', 'je-gst-return'),
  ('JE', 'JE-GST', '2', 'base', 'Zero-rated and remitted sales', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 2 — zero-rated sales and the remitted supplies to International Services Entities, included in box 1. Exports, international services, dwellings, prescription medicines and ISE supplies.', 'je-gst-return'),
  ('JE', 'JE-GST', '3', 'total', 'Total sales subject to GST', '{}'::jsonb, 30, null, array['1']::text[], array['2']::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 3 — calculated by the form: box 1 less box 2.', 'je-gst-return'),
  ('JE', 'JE-GST', '4', 'base', 'Purchases and expenses excluding imports', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 4 — business costs from Jersey suppliers, without GST. The pack carries every purchase from a Jersey supplier here, taxed, zero-rated, exempt, with GST not recoverable or with no GST; the page does not say whether exempt or untaxed costs belong in it, which is a point to confirm (see the README).', 'je-gst-return'),
  ('JE', 'JE-GST', '5', 'base', 'Total value of imports', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 5 — all imports without GST: goods, and certain services received from outside Jersey that the customer self-assesses (Supplying goods and services from outside Jersey, consulted 2026-10-10).', 'je-gst-return'),
  ('JE', 'JE-GST', '6', 'tax', 'GST on sales', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 6 — the output tax charged to customers, net of credit notes, and the GST the pack self-assesses on deferred imports and reverse-charged services.', 'je-gst-return'),
  ('JE', 'JE-GST', '7', 'tax', 'GST on purchases', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 7 — the deductible input tax: GST on domestic purchases, GST paid to Customs on imports, and the self-assessed GST of box 6 on deferred imports and reverse-charged services, net of credit notes.', 'je-gst-return'),
  ('JE', 'JE-GST', '8', 'total', 'Amount payable or refundable', '{}'::jsonb, 80, null, array['6']::text[], array['7']::text[], null, null, false, false, null, 'Revenue Jersey, Submit your GST return (consulted 2026-10-10), box 8 — calculated by the form: box 6 less box 7; a negative amount is a refund. The GST (Jersey) Law 2007, art. 34, credits input tax against output tax and refunds the excess as a GST credit.', 'je-gst-return')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('JE-FRS102-1A-BS', 'JE', 'default', 'Balance sheet — FRS 102 Section 1A, Format 1', 'balance_sheet', 'UK-FRS102', date '1970-01-01', null, 'FRS 102 The Financial Reporting Standard applicable in the UK and Republic of Ireland, Section 1A (Small Entities), is the framework this statement follows: the Companies (Jersey) Law 1991 requires accounts that give a true and fair view where an audit is required and that state the generally accepted accounting principles adopted (Walkers, consulted 2026-10-10), and the Law does not define ''accounts'' or set their format; UK GAAP is one of the principles a Jersey company may declare. The layout is the one Section 1A shows for small entities, the Format 1 balance sheet (fixed assets, current assets, creditors due within and after one year, provisions, capital and reserves) in its summarised form. It is a layout borrowed from the United Kingdom standard, not a format Jersey law imposes, and the lines are the pack''s own groupings of its original chart. GST accounts sit in debtors (1140, 1145) and in other creditors (2210, 2215, 2230). Line K.IV carries the year''s result not yet closed to retained earnings, so that the statement ties to the cent on an open year. The text of the Law itself could not be opened; see the README.', 'frs-102'),
  ('JE-FRS102-1A-IS', 'JE', 'default', 'Profit and loss account — FRS 102 Section 1A, Format 1', 'income_statement', 'UK-FRS102', date '1970-01-01', null, 'FRS 102 Section 1A (Small Entities): the profit and loss account in the Format 1 layout (turnover, cost of sales, gross profit, distribution costs, administrative expenses, other operating income, investment income, interest, tax). Jersey law requires accounts that give a true and fair view and names no format (Companies (Jersey) Law 1991, per Walkers, consulted 2026-10-10); the layout is borrowed from the United Kingdom standard. The tax line carries Jersey income tax on the company''s profit (0 % as standard, 10 % for financial services companies, 20 % for utility companies and for Jersey property income and development, up to 20 % for large retailers, Government of Jersey, Moving to Jersey: money and tax, consulted 2026-10-10), booked by the company: nothing in this pack computes it.', 'frs-102')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('JE-FRS102-1A-BS', 'A', null, 'Called up share capital not paid', '{}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'B.I', 'B', 'Intangible assets', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'B.II', 'B', 'Tangible assets', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'B.III', 'B', 'Investments', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'B', null, 'Fixed assets', '{}'::jsonb, 50, 1, true, array['B.I', 'B.II', 'B.III']::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'C.I', 'C', 'Stocks', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'C.II', 'C', 'Debtors', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'C.III', 'C', 'Investments', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'C.IV', 'C', 'Cash at bank and in hand', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'C', null, 'Current assets', '{}'::jsonb, 100, 1, true, array['C.I', 'C.II', 'C.III', 'C.IV']::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'D', null, 'Prepayments and accrued income', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'E.1', 'E', 'Bank loans and overdrafts', '{}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'E.2', 'E', 'Trade creditors', '{}'::jsonb, 130, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'E.3', 'E', 'Amounts owed to group undertakings', '{}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'E.4', 'E', 'Other creditors including taxation and social security', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'E', null, 'Creditors: amounts falling due within one year', '{}'::jsonb, 160, 1, true, array['E.1', 'E.2', 'E.3', 'E.4']::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'J', null, 'Accruals and deferred income', '{}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'F', null, 'Net current assets (liabilities)', '{}'::jsonb, 180, 1, true, array['C', 'D']::text[], array['E', 'J']::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'G', null, 'Total assets less current liabilities', '{}'::jsonb, 190, 1, true, array['A', 'B', 'F']::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'H', null, 'Creditors: amounts falling due after more than one year', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'I', null, 'Provisions for liabilities', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'NET', null, 'Net assets (liabilities)', '{}'::jsonb, 220, 1, true, array['G']::text[], array['H', 'I']::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'K.I', 'K', 'Called up share capital', '{}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'K.II', 'K', 'Share premium account and other reserves', '{}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'K.III', 'K', 'Profit and loss account brought forward', '{}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'K.IV', 'K', 'Profit or loss for the year, not yet allocated', '{}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-BS', 'K', null, 'Capital and reserves', '{}'::jsonb, 270, 1, true, array['K.I', 'K.II', 'K.III', 'K.IV']::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '1', null, 'Turnover', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '2', null, 'Cost of sales', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '3', null, 'Gross profit or loss', '{}'::jsonb, 30, 1, true, array['1']::text[], array['2']::text[], null, null, null),
  ('JE-FRS102-1A-IS', '4', null, 'Distribution costs', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '5', null, 'Administrative expenses', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '6', null, 'Other operating income', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '7', null, 'Income from investments', '{}'::jsonb, 70, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '8', null, 'Other interest receivable and similar income', '{}'::jsonb, 80, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '9', null, 'Amounts written off investments', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '10', null, 'Interest payable and similar expenses', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '11', null, 'Tax on profit or loss', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '12', null, 'Other taxes not shown under the above items', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('JE-FRS102-1A-IS', '13', null, 'Profit or loss for the financial year', '{}'::jsonb, 130, 1, true, array['3', '6', '7', '8']::text[], array['4', '5', '9', '10', '11', '12']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('JE-FRS102-1A-BS', 'A', 10, 'account_code', '0000', null, null, 'any'),
    ('JE-FRS102-1A-BS', 'B.I', 10, 'code_range', '0010', '0041', null, 'any'),
    ('JE-FRS102-1A-BS', 'B.II', 10, 'code_range', '0100', '0161', null, 'any'),
    ('JE-FRS102-1A-BS', 'B.III', 10, 'code_range', '0200', '0230', null, 'any'),
    ('JE-FRS102-1A-BS', 'C.I', 10, 'code_range', '1000', '1030', null, 'any'),
    ('JE-FRS102-1A-BS', 'C.II', 10, 'code_range', '1100', '1160', null, 'any'),
    ('JE-FRS102-1A-BS', 'C.III', 10, 'code_range', '1200', '1210', null, 'any'),
    ('JE-FRS102-1A-BS', 'C.IV', 10, 'code_range', '1300', '1350', null, 'any'),
    ('JE-FRS102-1A-BS', 'D', 10, 'code_range', '1400', '1420', null, 'any'),
    ('JE-FRS102-1A-BS', 'E.1', 10, 'code_range', '2000', '2020', null, 'any'),
    ('JE-FRS102-1A-BS', 'E.2', 10, 'account_code', '2100', null, null, 'any'),
    ('JE-FRS102-1A-BS', 'E.3', 10, 'account_code', '2110', null, null, 'any'),
    ('JE-FRS102-1A-BS', 'E.4', 10, 'code_range', '2200', '2400', null, 'any'),
    ('JE-FRS102-1A-BS', 'J', 10, 'code_range', '3200', '3210', null, 'any'),
    ('JE-FRS102-1A-BS', 'H', 10, 'code_range', '3000', '3050', null, 'any'),
    ('JE-FRS102-1A-BS', 'I', 10, 'code_range', '3100', '3110', null, 'any'),
    ('JE-FRS102-1A-BS', 'K.I', 10, 'account_code', '3300', null, null, 'any'),
    ('JE-FRS102-1A-BS', 'K.II', 10, 'code_range', '3310', '3340', null, 'any'),
    ('JE-FRS102-1A-BS', 'K.III', 10, 'code_range', '3400', '3410', null, 'any'),
    ('JE-FRS102-1A-BS', 'K.IV', 10, 'code_range', '4000', '8399', null, 'any'),
    ('JE-FRS102-1A-IS', '1', 10, 'code_range', '4000', '4110', null, 'any'),
    ('JE-FRS102-1A-IS', '2', 10, 'code_range', '5000', '5240', null, 'any'),
    ('JE-FRS102-1A-IS', '4', 10, 'code_range', '6000', '6500', null, 'any'),
    ('JE-FRS102-1A-IS', '5', 10, 'code_range', '7000', '7710', null, 'any'),
    ('JE-FRS102-1A-IS', '6', 10, 'code_range', '4200', '4240', null, 'any'),
    ('JE-FRS102-1A-IS', '7', 10, 'code_range', '4300', '4320', null, 'any'),
    ('JE-FRS102-1A-IS', '8', 10, 'account_code', '4330', null, null, 'any'),
    ('JE-FRS102-1A-IS', '9', 10, 'account_code', '8100', null, null, 'any'),
    ('JE-FRS102-1A-IS', '10', 10, 'code_range', '8000', '8040', null, 'any'),
    ('JE-FRS102-1A-IS', '11', 10, 'code_range', '8200', '8220', null, 'any'),
    ('JE-FRS102-1A-IS', '12', 10, 'account_code', '8300', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('JE', 'Jersey', '{}'::jsonb, array['en']::text[], 'GBP', '1100', '2100', '2400', '7710', '3400', '4000', '5000', '1300', '1330', 'SAL', 'PUR', 'GEN', 'en', 'retained_earnings', null, null, null, 'OPN', 'half_up', default, '4240', '7700', '4230', '7690', null, null, '2230', '1145', null, 'quarter'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Revenue Jersey, Keeping records and accounts for GST (consulted 2026-10-10): a GST invoice carries an individual serial number. The page asks that each invoice be identified and does not say the series may have no gap, so the style is `sequential` and not a gapless one; the pattern in number_format is one a business may choose.',
  numbering_source_key          = 'je-gst-records',
  payment_terms_legal_reference = 'No Jersey statute was found that sets a payment term between two businesses in the absence of an agreement, or a rate of interest on a commercial debt paid late; the Late Payment of Commercial Debts (Interest) Act 1998 is a United Kingdom statute and no source consulted says it extends to Jersey. `legal_payment_days` and `late_payment_reference` are therefore empty. This is an absence of a source found, not a proof of absence: a Jersey lawyer should confirm it.',
  payment_terms_source_key      = 'je-gst-records',
  tax_point_rule                = 'invoice_date',
  tax_point_legal_reference     = 'The invoice carries a ''tax point date (the date on which the transaction took place)'' and a date of issue where it differs (Revenue Jersey, Keeping records and accounts for GST, consulted 2026-10-10). The rule that fixes the tax point of a supply in the Goods and Services Tax (Jersey) Law 2007 was not read in the part of the Law that was opened, so `invoice_date` is declared as the common convention and not as a rule read from the text; see the README.',
  tax_point_source_key          = 'je-gst-records',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'No Jersey statute or Revenue Jersey page was found that obliges a business to issue or accept an electronic invoice (Revenue Jersey, Keeping records and accounts for GST, consulted 2026-10-10: it asks for tax invoices and six years of records and says nothing of an electronic format), and no Peppol Authority is listed for Jersey as far as the author knows (not re-checked against the OpenPeppol list). `profile`, `party_scheme` and `vat_scheme` are null: there is no domestic profile to name, and Jersey is outside the European Union and United Kingdom VAT systems.',
  einvoice_source_key           = 'je-gst-records',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'JE';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('JE', 'tax_invoice', 'always', 'Tax invoice', '{}'::jsonb, 10, date '1970-01-01', null, 'Revenue Jersey, Keeping records and accounts for GST (consulted 2026-10-10): a GST invoice carries the words ''tax invoice'' in a prominent place, together with the supplier''s name, address and GST registration number, the tax point date, a serial number, a description, the selling price, the GST charged, the price including GST and an indication whether GST is chargeable.'),
  ('JE', 'zero_rated', 'export', 'Zero-rated supply: GST is chargeable at 0 %.', '{}'::jsonb, 20, date '1970-01-01', null, 'Revenue Jersey, Keeping records and accounts for GST (consulted 2026-10-10): the invoice indicates whether GST is chargeable on the supply; Goods and Services Tax (Jersey) Law 2007, Schedule 6, zero-rates exports of goods and international services.'),
  ('JE', 'exempt', 'exempt', 'Exempt supply: GST is not chargeable.', '{}'::jsonb, 30, date '1970-01-01', null, 'Revenue Jersey, Keeping records and accounts for GST (consulted 2026-10-10): the invoice indicates whether GST is chargeable on the supply; Goods and Services Tax (Jersey) Law 2007, Schedule 5, lists the exempt supplies.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
