-- Ekwo OS — Chile: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/cl at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build cl`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Decreto Ley N° 825, de 1974, Ley sobre Impuesto a las Ventas y Servicios — texto refundido, coordinado y sistematizado por el Decreto Ley N° 1.606, de 1976, actualizado a la Ley N° 21.462, D.O. de 26 de julio de 2022 (Ministerio de Hacienda — Servicio de Impuestos Internos)
--     https://www.sii.cl/normativa_legislacion/sobreventasyservicios.pdf
--   Ley N° 18.046, sobre Sociedades Anónimas, artículo 74 (Servicio de Impuestos Internos — copia de normativa complementaria)
--     https://www.sii.cl/pagina/jurisprudencia/legislacion/complementaria/ley_18046b.htm
--   Ley N° 20.727, que introduce modificaciones a la legislación tributaria en materia de factura electrónica y dispone otras medidas que indica (Servicio de Impuestos Internos — Factura Electrónica)
--     https://www.sii.cl/factura_electronica/ley/ley_fe_20727.htm
--   «A partir de hoy todas las empresas del país deben facturar electrónicamente» — noticia oficial del 1 de febrero de 2018, fin del calendario de obligatoriedad de la Ley N° 20.727 (Servicio de Impuestos Internos — Noticias)
--     https://www.sii.cl/noticias/2018/010218noti01er.htm
--   Ley N° 21.131, que establece pago a treinta días, que modifica diversos cuerpos legales para establecer el pago en 30 días corridos posterior a la recepción de la factura (Ministerio de Economía, Fomento y Turismo — Biblioteca del Congreso Nacional (Ley Chile))
--     https://www.bcn.cl/leychile/navegar?idNorma=1127890
--   Instrucciones para llenar el Formulario 29 (F29) de Declaración Mensual y Pago Simultáneo de Impuestos: IVA, impuestos adicionales a las ventas, retenciones de impuestos a la renta y pagos provisionales mensuales (Servicio de Impuestos Internos)
--     https://www.sii.cl/servicios_online/instrucciones_f29_20241112.pdf
--   Formulario 29 — versión Internet, con los códigos de cada línea (Servicio de Impuestos Internos)
--     https://www.sii.cl/formularios/imagen/F29.pdf
--   Plazos para presentar el Formulario 29 (Servicio de Impuestos Internos — Preguntas Frecuentes)
--     https://www.sii.cl/preguntas_frecuentes/impuestos_mensuales/001_130_1060.htm
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('CL', 'Chile', '0.1.0', date '2026-09-25', '20260921084143', 'community', null, null, '39a123d3e9d5b7d96ceb58963f458b1e193c60abc2e98e27994c366529c69ed7', '[{"key":"dl825","title":"Decreto Ley N° 825, de 1974, Ley sobre Impuesto a las Ventas y Servicios — texto refundido, coordinado y sistematizado por el Decreto Ley N° 1.606, de 1976, actualizado a la Ley N° 21.462, D.O. de 26 de julio de 2022","publisher":"Ministerio de Hacienda — Servicio de Impuestos Internos","url":"https://www.sii.cl/normativa_legislacion/sobreventasyservicios.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"ley18046","title":"Ley N° 18.046, sobre Sociedades Anónimas, artículo 74","publisher":"Servicio de Impuestos Internos — copia de normativa complementaria","url":"https://www.sii.cl/pagina/jurisprudencia/legislacion/complementaria/ley_18046b.htm","consulted_on":"2026-09-25","kind":"law"},{"key":"ley20727","title":"Ley N° 20.727, que introduce modificaciones a la legislación tributaria en materia de factura electrónica y dispone otras medidas que indica","publisher":"Servicio de Impuestos Internos — Factura Electrónica","url":"https://www.sii.cl/factura_electronica/ley/ley_fe_20727.htm","consulted_on":"2026-09-25","kind":"law"},{"key":"sii-fe-2018","title":"«A partir de hoy todas las empresas del país deben facturar electrónicamente» — noticia oficial del 1 de febrero de 2018, fin del calendario de obligatoriedad de la Ley N° 20.727","publisher":"Servicio de Impuestos Internos — Noticias","url":"https://www.sii.cl/noticias/2018/010218noti01er.htm","consulted_on":"2026-09-25","kind":"guidance"},{"key":"ley21131","title":"Ley N° 21.131, que establece pago a treinta días, que modifica diversos cuerpos legales para establecer el pago en 30 días corridos posterior a la recepción de la factura","publisher":"Ministerio de Economía, Fomento y Turismo — Biblioteca del Congreso Nacional (Ley Chile)","url":"https://www.bcn.cl/leychile/navegar?idNorma=1127890","consulted_on":"2026-09-25","kind":"law"},{"key":"f29-instrucciones","title":"Instrucciones para llenar el Formulario 29 (F29) de Declaración Mensual y Pago Simultáneo de Impuestos: IVA, impuestos adicionales a las ventas, retenciones de impuestos a la renta y pagos provisionales mensuales","publisher":"Servicio de Impuestos Internos","url":"https://www.sii.cl/servicios_online/instrucciones_f29_20241112.pdf","consulted_on":"2026-09-25","kind":"form"},{"key":"f29-formulario","title":"Formulario 29 — versión Internet, con los códigos de cada línea","publisher":"Servicio de Impuestos Internos","url":"https://www.sii.cl/formularios/imagen/F29.pdf","consulted_on":"2026-09-25","kind":"form"},{"key":"f29-plazos","title":"Plazos para presentar el Formulario 29","publisher":"Servicio de Impuestos Internos — Preguntas Frecuentes","url":"https://www.sii.cl/preguntas_frecuentes/impuestos_mensuales/001_130_1060.htm","consulted_on":"2026-09-25","kind":"guidance"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('CL', 'default', 'Plan de cuentas Ekwo para Chile (sin catálogo oficial)', '{}'::jsonb, true, 'companies', array['CL-BAL', 'CL-RES']::text[], null, 'Chile no fija por ley un plan de cuentas: el Código Tributario, art. 17, sólo exige llevar «contabilidad fidedigna» en los libros que el Servicio de Impuestos Internos autoriza, sin imponer códigos ni nombres de cuenta — a diferencia del código agrupador que el Anexo 24 de la RMF mexicana publica. Este plan es una numeración propia de Ekwo (clases 1 a 5, sin correlato oficial), pensada para que cada cuenta alcance una línea del Estado de Situación Financiera y del Estado de Resultados del artículo 74 de la Ley N° 18.046. Una empresa puede llevar cualquier otro plan de cuentas: éste es el que Ekwo instala por defecto', 'dl825')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('CL', 'default', '1101', 'Caja', '{}'::jsonb, 'asset_cash', false, null, 10),
  ('CL', 'default', '1102', 'Banco', '{}'::jsonb, 'asset_cash', false, null, 20),
  ('CL', 'default', '1103', 'Clientes', '{}'::jsonb, 'asset_receivable', true, null, 30),
  ('CL', 'default', '1104', 'Documentos por Cobrar', '{}'::jsonb, 'asset_current', false, null, 35),
  ('CL', 'default', '1105', 'IVA Crédito Fiscal', '{}'::jsonb, 'asset_current', false, null, 40),
  ('CL', 'default', '1106', 'IVA Crédito Fiscal Servicios (Devengado no Pagado)', '{}'::jsonb, 'asset_current', false, null, 50),
  ('CL', 'default', '1107', 'IVA Crédito Fiscal Remanente', '{}'::jsonb, 'asset_current', true, null, 55),
  ('CL', 'default', '1108', 'Existencias', '{}'::jsonb, 'asset_current', false, null, 60),
  ('CL', 'default', '1109', 'Gastos Pagados por Anticipado', '{}'::jsonb, 'asset_prepayments', false, null, 70),
  ('CL', 'default', '1110', 'Anticipos a Proveedores', '{}'::jsonb, 'asset_current', false, null, 81),
  ('CL', 'default', '1111', 'Otras Cuentas por Cobrar', '{}'::jsonb, 'asset_current', false, null, 82),
  ('CL', 'default', '1112', 'Cuentas por Cobrar a Empresas Relacionadas', '{}'::jsonb, 'asset_current', false, null, 83),
  ('CL', 'default', '1113', 'Préstamos al Personal', '{}'::jsonb, 'asset_current', false, null, 84),
  ('CL', 'default', '1114', 'Pagos Provisionales Mensuales por Recuperar', '{}'::jsonb, 'asset_current', false, null, 85),
  ('CL', 'default', '1115', 'Impuesto a la Renta por Recuperar', '{}'::jsonb, 'asset_current', false, null, 86),
  ('CL', 'default', '1116', 'Materias Primas', '{}'::jsonb, 'asset_current', false, null, 61),
  ('CL', 'default', '1117', 'Productos en Proceso', '{}'::jsonb, 'asset_current', false, null, 62),
  ('CL', 'default', '1118', 'Productos Terminados', '{}'::jsonb, 'asset_current', false, null, 63),
  ('CL', 'default', '1119', 'Mercaderías', '{}'::jsonb, 'asset_current', false, null, 64),
  ('CL', 'default', '1120', 'Materiales y Repuestos', '{}'::jsonb, 'asset_current', false, null, 65),
  ('CL', 'default', '1121', 'Provisión por Obsolescencia de Existencias', '{}'::jsonb, 'asset_current', false, null, 66),
  ('CL', 'default', '1122', 'Seguros Pagados por Anticipado', '{}'::jsonb, 'asset_prepayments', false, null, 71),
  ('CL', 'default', '1123', 'Arriendos Pagados por Anticipado', '{}'::jsonb, 'asset_prepayments', false, null, 72),
  ('CL', 'default', '1150', 'Partidas Pendientes de Identificación', '{}'::jsonb, 'asset_current', false, null, 80),
  ('CL', 'default', '1201', 'Terrenos', '{}'::jsonb, 'asset_fixed', false, null, 90),
  ('CL', 'default', '1202', 'Construcciones y Edificios', '{}'::jsonb, 'asset_fixed', false, null, 100),
  ('CL', 'default', '1203', 'Maquinarias y Equipos', '{}'::jsonb, 'asset_fixed', false, null, 110),
  ('CL', 'default', '1204', 'Muebles y Útiles', '{}'::jsonb, 'asset_fixed', false, null, 120),
  ('CL', 'default', '1205', 'Equipos Computacionales', '{}'::jsonb, 'asset_fixed', false, null, 130),
  ('CL', 'default', '1206', 'Vehículos', '{}'::jsonb, 'asset_fixed', false, null, 140),
  ('CL', 'default', '1207', 'Depreciación Acumulada', '{}'::jsonb, 'asset_fixed', false, null, 150),
  ('CL', 'default', '1210', 'Obras en Construcción', '{}'::jsonb, 'asset_fixed', false, null, 151),
  ('CL', 'default', '1211', 'Herramientas y Equipos Menores', '{}'::jsonb, 'asset_fixed', false, null, 152),
  ('CL', 'default', '1212', 'Instalaciones', '{}'::jsonb, 'asset_fixed', false, null, 153),
  ('CL', 'default', '1213', 'Mejoras en Bienes Arrendados', '{}'::jsonb, 'asset_fixed', false, null, 154),
  ('CL', 'default', '1214', 'Depreciación Acumulada Herramientas y Equipos Menores', '{}'::jsonb, 'asset_fixed', false, null, 155),
  ('CL', 'default', '1215', 'Depreciación Acumulada Instalaciones', '{}'::jsonb, 'asset_fixed', false, null, 156),
  ('CL', 'default', '1216', 'Depreciación Acumulada Mejoras en Bienes Arrendados', '{}'::jsonb, 'asset_fixed', false, null, 157),
  ('CL', 'default', '1301', 'Activos Intangibles', '{}'::jsonb, 'asset_non_current', false, null, 160),
  ('CL', 'default', '1310', 'Amortización Acumulada de Intangibles', '{}'::jsonb, 'asset_non_current', false, null, 161),
  ('CL', 'default', '1311', 'Inversiones en Empresas Relacionadas', '{}'::jsonb, 'asset_non_current', false, null, 162),
  ('CL', 'default', '1312', 'Depósitos en Garantía', '{}'::jsonb, 'asset_non_current', false, null, 163),
  ('CL', 'default', '2101', 'Proveedores', '{}'::jsonb, 'liability_payable', true, null, 170),
  ('CL', 'default', '2102', 'IVA Débito Fiscal', '{}'::jsonb, 'liability_current', false, null, 180),
  ('CL', 'default', '2103', 'IVA por Pagar', '{}'::jsonb, 'liability_current', true, null, 190),
  ('CL', 'default', '2104', 'IVA Débito Fiscal Servicios (Devengado no Percibido)', '{}'::jsonb, 'liability_current', false, null, 200),
  ('CL', 'default', '2105', 'Retenciones y Otros Impuestos por Pagar', '{}'::jsonb, 'liability_current', false, null, 210),
  ('CL', 'default', '2106', 'Remuneraciones por Pagar', '{}'::jsonb, 'liability_current', false, null, 220),
  ('CL', 'default', '2107', 'Provisiones', '{}'::jsonb, 'liability_current', false, null, 230),
  ('CL', 'default', '2108', 'Documentos por Pagar', '{}'::jsonb, 'liability_current', false, null, 231),
  ('CL', 'default', '2109', 'Otras Cuentas por Pagar', '{}'::jsonb, 'liability_current', false, null, 232),
  ('CL', 'default', '2110', 'Cuentas por Pagar a Empresas Relacionadas', '{}'::jsonb, 'liability_current', false, null, 233),
  ('CL', 'default', '2111', 'Dividendos por Pagar', '{}'::jsonb, 'liability_current', false, null, 234),
  ('CL', 'default', '2112', 'Impuesto a la Renta por Pagar', '{}'::jsonb, 'liability_current', false, null, 235),
  ('CL', 'default', '2113', 'AFP por Pagar', '{}'::jsonb, 'liability_current', false, null, 236),
  ('CL', 'default', '2114', 'Salud (Isapre/Fonasa) por Pagar', '{}'::jsonb, 'liability_current', false, null, 237),
  ('CL', 'default', '2115', 'Mutual de Seguridad por Pagar', '{}'::jsonb, 'liability_current', false, null, 238),
  ('CL', 'default', '2116', 'Seguro de Cesantía (AFC) por Pagar', '{}'::jsonb, 'liability_current', false, null, 239),
  ('CL', 'default', '2117', 'Impuesto Único de Segunda Categoría por Pagar', '{}'::jsonb, 'liability_current', false, null, 241),
  ('CL', 'default', '2118', 'Provisión de Vacaciones', '{}'::jsonb, 'liability_current', false, null, 242),
  ('CL', 'default', '2119', 'Provisión de Gratificaciones', '{}'::jsonb, 'liability_current', false, null, 243),
  ('CL', 'default', '2120', 'Provisión de Indemnización por Años de Servicio', '{}'::jsonb, 'liability_current', false, null, 244),
  ('CL', 'default', '2201', 'Préstamos Bancarios Largo Plazo', '{}'::jsonb, 'liability_non_current', false, null, 240),
  ('CL', 'default', '2210', 'Leasing por Pagar Largo Plazo', '{}'::jsonb, 'liability_non_current', false, null, 245),
  ('CL', 'default', '2211', 'Provisiones Largo Plazo', '{}'::jsonb, 'liability_non_current', false, null, 246),
  ('CL', 'default', '3101', 'Capital', '{}'::jsonb, 'equity', false, null, 250),
  ('CL', 'default', '3102', 'Reservas', '{}'::jsonb, 'equity', false, null, 260),
  ('CL', 'default', '3103', 'Utilidades Acumuladas', '{}'::jsonb, 'equity_retained', false, null, 270),
  ('CL', 'default', '3104', 'Pérdidas Acumuladas', '{}'::jsonb, 'equity_retained', false, null, 280),
  ('CL', 'default', '3105', 'Resultado del Ejercicio (Utilidad)', '{}'::jsonb, 'equity_retained', false, null, 290),
  ('CL', 'default', '3106', 'Resultado del Ejercicio (Pérdida)', '{}'::jsonb, 'equity_retained', false, null, 300),
  ('CL', 'default', '3107', 'Reserva Legal', '{}'::jsonb, 'equity', false, null, 301),
  ('CL', 'default', '3108', 'Otras Reservas de Capital', '{}'::jsonb, 'equity', false, null, 302),
  ('CL', 'default', '4101', 'Ventas Nacionales', '{}'::jsonb, 'income', false, null, 310),
  ('CL', 'default', '4102', 'Ventas de Exportación', '{}'::jsonb, 'income', false, null, 320),
  ('CL', 'default', '4103', 'Servicios Prestados', '{}'::jsonb, 'income', false, null, 330),
  ('CL', 'default', '4104', 'Otros Ingresos de Explotación', '{}'::jsonb, 'income_other', false, null, 340),
  ('CL', 'default', '4105', 'Ingresos Financieros', '{}'::jsonb, 'income_other', false, null, 350),
  ('CL', 'default', '4106', 'Utilidad por Diferencia de Cambio', '{}'::jsonb, 'income_other', false, null, 360),
  ('CL', 'default', '4107', 'Devoluciones y Bonificaciones sobre Ventas', '{}'::jsonb, 'income', false, null, 361),
  ('CL', 'default', '4108', 'Descuentos Obtenidos por Pronto Pago', '{}'::jsonb, 'income_other', false, null, 362),
  ('CL', 'default', '4109', 'Arriendos Ganados', '{}'::jsonb, 'income_other', false, null, 363),
  ('CL', 'default', '5101', 'Costo de Ventas', '{}'::jsonb, 'expense_direct_cost', false, null, 370),
  ('CL', 'default', '5102', 'Compras', '{}'::jsonb, 'expense_direct_cost', false, null, 380),
  ('CL', 'default', '5103', 'Gastos de Administración y Ventas', '{}'::jsonb, 'expense', false, null, 390),
  ('CL', 'default', '5104', 'Remuneraciones', '{}'::jsonb, 'expense', false, null, 400),
  ('CL', 'default', '5105', 'Depreciación del Ejercicio', '{}'::jsonb, 'expense_depreciation', false, null, 410),
  ('CL', 'default', '5106', 'Gastos Financieros', '{}'::jsonb, 'expense', false, null, 420),
  ('CL', 'default', '5107', 'Pérdida por Diferencia de Cambio', '{}'::jsonb, 'expense', false, null, 430),
  ('CL', 'default', '5108', 'Diferencias de Redondeo', '{}'::jsonb, 'expense', false, null, 440),
  ('CL', 'default', '5109', 'Impuesto a la Renta', '{}'::jsonb, 'expense', false, null, 450),
  ('CL', 'default', '5110', 'Servicios Recibidos del Exterior', '{}'::jsonb, 'expense', false, null, 460),
  ('CL', 'default', '5111', 'Sueldos y Salarios', '{}'::jsonb, 'expense', false, null, 401),
  ('CL', 'default', '5112', 'Leyes Sociales', '{}'::jsonb, 'expense', false, null, 402),
  ('CL', 'default', '5113', 'Gratificaciones', '{}'::jsonb, 'expense', false, null, 403),
  ('CL', 'default', '5114', 'Indemnización por Años de Servicio', '{}'::jsonb, 'expense', false, null, 404),
  ('CL', 'default', '5115', 'Vacaciones', '{}'::jsonb, 'expense', false, null, 405),
  ('CL', 'default', '5116', 'Honorarios Profesionales', '{}'::jsonb, 'expense', false, null, 406),
  ('CL', 'default', '5117', 'Arriendos', '{}'::jsonb, 'expense', false, null, 407),
  ('CL', 'default', '5118', 'Seguros Generales', '{}'::jsonb, 'expense', false, null, 408),
  ('CL', 'default', '5119', 'Servicios Básicos', '{}'::jsonb, 'expense', false, null, 409),
  ('CL', 'default', '5120', 'Mantención y Reparaciones', '{}'::jsonb, 'expense', false, null, 411),
  ('CL', 'default', '5121', 'Materiales de Oficina', '{}'::jsonb, 'expense', false, null, 412),
  ('CL', 'default', '5122', 'Publicidad y Marketing', '{}'::jsonb, 'expense', false, null, 413),
  ('CL', 'default', '5123', 'Gastos de Representación', '{}'::jsonb, 'expense', false, null, 414),
  ('CL', 'default', '5124', 'Viáticos y Gastos de Viaje', '{}'::jsonb, 'expense', false, null, 415),
  ('CL', 'default', '5125', 'Fletes y Transportes', '{}'::jsonb, 'expense', false, null, 416),
  ('CL', 'default', '5126', 'Comunicaciones', '{}'::jsonb, 'expense', false, null, 417),
  ('CL', 'default', '5127', 'Gastos Bancarios', '{}'::jsonb, 'expense', false, null, 431),
  ('CL', 'default', '5128', 'Amortización de Intangibles', '{}'::jsonb, 'expense_depreciation', false, null, 418),
  ('CL', 'default', '5129', 'Castigo de Cuentas Incobrables', '{}'::jsonb, 'expense', false, null, 419),
  ('CL', 'default', '5130', 'Multas e Intereses Fiscales', '{}'::jsonb, 'expense', false, null, 432),
  ('CL', 'default', '5131', 'Donaciones', '{}'::jsonb, 'expense', false, null, 421),
  ('CL', 'default', '5132', 'Patentes Municipales', '{}'::jsonb, 'expense', false, null, 422),
  ('CL', 'default', '5133', 'Capacitación del Personal', '{}'::jsonb, 'expense', false, null, 423),
  ('CL', 'default', '5134', 'Intereses por Préstamos', '{}'::jsonb, 'expense', false, null, 433),
  ('CL', 'default', '5140', 'Mano de Obra Directa', '{}'::jsonb, 'expense_direct_cost', false, null, 461),
  ('CL', 'default', '5141', 'Materiales Directos', '{}'::jsonb, 'expense_direct_cost', false, null, 462),
  ('CL', 'default', '5142', 'Gastos Indirectos de Fabricación', '{}'::jsonb, 'expense_direct_cost', false, null, 463)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('CL', 'APE', 'Asiento de Apertura', '{}'::jsonb, 'opening', 60),
  ('CL', 'BAN', 'Banco', '{}'::jsonb, 'bank', 30),
  ('CL', 'CAJ', 'Caja', '{}'::jsonb, 'cash', 40),
  ('CL', 'COM', 'Libro de Compras', '{}'::jsonb, 'purchase', 20),
  ('CL', 'DIA', 'Libro Diario', '{}'::jsonb, 'general', 50),
  ('CL', 'VEN', 'Libro de Ventas', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('CL', 'CL-P-19-BIENES', 'Compras de bienes, tasa general 19 %', '{}'::jsonb, 'Adquisición de bienes corporales muebles del giro, con derecho a crédito fiscal', 'percent', 19, 'purchase', 'domestic', date '1975-01-01', null, 'Decreto Ley N° 825, art. 14 — tasa de 19 %; art. 23 — «Los contribuyentes afectos al pago del tributo de este Título tendrán derecho a un crédito fiscal… equivalente al impuesto de este Título recargado en las facturas que acrediten sus adquisiciones». Formulario 29, línea 28 (Cód. 519/520): «Facturas recibidas del giro y Facturas de compra emitidas, con derecho a crédito fiscal»', 'S', null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'dl825', null, null, null, null),
  ('CL', 'CL-P-19-SERVICIOS', 'Compras de servicios, tasa general 19 %', '{}'::jsonb, 'Servicio recibido del giro, con derecho a crédito fiscal, acreditable al pagarse', 'percent', 19, 'purchase', 'domestic', date '1975-01-01', null, 'Decreto Ley N° 825, art. 14 y art. 23 — mismo derecho a crédito fiscal que CL-P-19-BIENES; art. 9°, letra a), y art. 55, inciso tercero — el proveedor del servicio devenga y factura su IVA al percibir o disponer de la remuneración, de modo que el crédito fiscal del comprador nace en esa misma fecha. Se declara cash_basis, sobre la cuenta de tránsito 1106, por la razón dada en CL-S-19-SERVICIOS', 'S', null, 70, 'vat', true, '{}'::tax_condition[], null, false, true, '1106', 'dl825', null, null, null, null),
  ('CL', 'CL-P-FSR-19', 'Servicio recibido de un prestador domiciliado en el extranjero', '{}'::jsonb, 'El beneficiario del servicio, contribuyente de este impuesto, es el sujeto pasivo cuando el prestador no está domiciliado ni reside en Chile', 'percent', 19, 'purchase', 'foreign_services_received', date '1975-01-01', null, 'Decreto Ley N° 825, art. 11, letra e) — son sujetos del impuesto «el beneficiario del servicio que sea contribuyente de este impuesto, siempre que la prestación sea realizada por un prestador domiciliado o residente en el extranjero»; art. 10, inciso segundo, y art. 5° — el servicio se entiende prestado en Chile cuando la actividad que lo genera se desarrolla en Chile, cualquiera sea el lugar donde se utilice, o cuando se usa en Chile aunque la remuneración se pague en el extranjero. El beneficiario se autofactura el débito y, al mismo tiempo, el crédito fiscal de la misma operación (art. 23), por lo que el efecto neto en la declaración es nulo salvo que el gasto sea sólo parcialmente afecto a IVA en manos del beneficiario. No hay categoría EN 16931 que registrar (ningún comprobante del prestador extranjero está gobernado por esa norma) ni código de exención, porque la operación no es una exención sino un traslado de la calidad de sujeto del impuesto', null, null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'dl825', null, null, null, null),
  ('CL', 'CL-S-0-EXP-BIENES', 'Exportación de bienes', '{}'::jsonb, 'Especies exportadas en su venta al exterior', 'percent', 0, 'sale', 'export', date '1975-01-01', null, 'Decreto Ley N° 825, art. 12, letra D — «Estarán exentas del impuesto establecido en este Título: … D.- Las especies exportadas en su venta al exterior». El exportador no traslada IVA en la exportación y, en cambio, tiene derecho a recuperar el impuesto soportado en sus compras e importaciones destinadas a esa actividad conforme al art. 36 — véase CL-P-19-BIENES y CL-P-19-SERVICIOS, que dan ese crédito, y la línea 37 (Cód. 593) del Formulario 29, que declara la devolución solicitada por el art. 36. La aduana certifica la salida de las especies (Documento Único de Salida)', 'G', null, 30, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'dl825', null, null, null, null),
  ('CL', 'CL-S-0-EXP-SERVICIOS', 'Exportación de servicios', '{}'::jsonb, 'Servicios prestados a personas sin domicilio ni residencia en Chile, calificados como exportación por el Servicio Nacional de Aduanas', 'percent', 0, 'sale', 'export', date '1975-01-01', null, 'Decreto Ley N° 825, art. 12, letra E, N° 16 — «Los ingresos percibidos por la prestación de servicios a personas sin domicilio ni residencia en Chile, siempre que el Servicio Nacional de Aduanas califique dichos servicios como exportación… La exención procederá respecto de aquellos servicios que sean prestados total o parcialmente en Chile para ser utilizados en el extranjero»; art. 36, inciso cuarto — los prestadores de estos servicios gozan del mismo derecho a recuperar el IVA soportado que un exportador de bienes', 'G', null, 40, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'dl825', null, null, null, null),
  ('CL', 'CL-S-19-BIENES', 'Ventas de bienes, tasa general 19 %', '{}'::jsonb, 'Venta de bienes corporales muebles gravada a la tasa general', 'percent', 19, 'sale', 'domestic', date '1975-01-01', null, 'Decreto Ley N° 825, art. 14 — «Los contribuyentes afectos a las disposiciones del presente Título pagarán el impuesto con una tasa de 19 % sobre la base imponible»; art. 8° — hecho gravado; art. 2° N° 1° — definición de «venta». El devengo sigue la regla general de tax_point (delivery_date): el art. 9°, letra a), fija el devengo en la fecha de la factura, salvo que la entrega sea anterior, y el art. 55 exige que la factura de una venta de bienes se emita «en el mismo momento» de la entrega real o simbólica de las especies, de modo que ambas fechas coinciden en el caso regular', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'dl825', null, null, null, null),
  ('CL', 'CL-S-19-SERVICIOS', 'Prestaciones de servicios, tasa general 19 %', '{}'::jsonb, 'Servicio gravado a la tasa general, devengado al percibirse o ponerse a disposición la remuneración', 'percent', 19, 'sale', 'domestic', date '1975-01-01', null, 'Decreto Ley N° 825, art. 14 — tasa de 19 %; art. 8° — hecho gravado; art. 2° N° 2° — definición de «servicio». Devengo: art. 9°, letra a) — en las prestaciones de servicios el impuesto se devenga en la fecha de emisión de la factura o boleta y, si no se hubieren emitido, «en cualquier forma, a disposición del prestador del servicio»; art. 55, inciso tercero — la factura de un servicio «deberá emitirse en el mismo periodo tributario en que la remuneración se perciba o se ponga, en cualquier forma, a disposición del prestador del servicio», de modo que el devengo de un servicio coincide con su cobro. Este paquete lo declara cash_basis, sobre la cuenta de tránsito 2104, porque el formato fija un solo tax_point por país (delivery_date, que sigue el caso general de los bienes) y reserva cash_basis para la regla distinta de un tipo de operación — el mismo mecanismo que usa el paquete de Francia para sus servicios', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, true, '2104', 'dl825', null, null, null, null),
  ('CL', 'CL-S-EXE-EDU', 'Ingresos de establecimientos de educación', '{}'::jsonb, 'Ingresos por la actividad docente propiamente tal de un establecimiento de educación', 'percent', 0, 'sale', 'exempt', date '1975-01-01', null, 'Decreto Ley N° 825, art. 13 — «Estarán liberadas del impuesto de este Título las siguientes empresas e instituciones: … 4.- Los establecimientos de educación. Esta exención se limitará a los ingresos que perciban en razón de su actividad docente propiamente tal»', 'E', null, 50, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'dl825', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('CL-P-19-BIENES', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CL-P-19-BIENES', 'invoice', 'tax', 100, '1105', '520', array['520']::text[], 100, 'CL-F29-IVA', 20),
    ('CL-P-19-BIENES', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('CL-P-19-BIENES', 'credit_note', 'tax', 100, '1105', '520', array['520']::text[], -100, 'CL-F29-IVA', 20),
    ('CL-P-19-SERVICIOS', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CL-P-19-SERVICIOS', 'invoice', 'tax', 100, '1105', '520', array['520']::text[], 100, 'CL-F29-IVA', 20),
    ('CL-P-19-SERVICIOS', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('CL-P-19-SERVICIOS', 'credit_note', 'tax', 100, '1105', '520', array['520']::text[], -100, 'CL-F29-IVA', 20),
    ('CL-P-FSR-19', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CL-P-FSR-19', 'invoice', 'tax', 100, '2102', '502', array['502']::text[], 100, 'CL-F29-IVA', 20),
    ('CL-P-FSR-19', 'invoice', 'tax', -100, '1105', '520', array['520']::text[], 100, 'CL-F29-IVA', 30),
    ('CL-P-FSR-19', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('CL-P-FSR-19', 'credit_note', 'tax', 100, '2102', '502', array['502']::text[], -100, 'CL-F29-IVA', 20),
    ('CL-P-FSR-19', 'credit_note', 'tax', -100, '1105', '520', array['520']::text[], -100, 'CL-F29-IVA', 30),
    ('CL-S-0-EXP-BIENES', 'invoice', 'base', 100, null, '20', array['20']::text[], 100, 'CL-F29-IVA', 10),
    ('CL-S-0-EXP-BIENES', 'credit_note', 'base', 100, null, '20', array['20']::text[], -100, 'CL-F29-IVA', 10),
    ('CL-S-0-EXP-SERVICIOS', 'invoice', 'base', 100, null, '20', array['20']::text[], 100, 'CL-F29-IVA', 10),
    ('CL-S-0-EXP-SERVICIOS', 'credit_note', 'base', 100, null, '20', array['20']::text[], -100, 'CL-F29-IVA', 10),
    ('CL-S-19-BIENES', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CL-S-19-BIENES', 'invoice', 'tax', 100, '2102', '502', array['502']::text[], 100, 'CL-F29-IVA', 20),
    ('CL-S-19-BIENES', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('CL-S-19-BIENES', 'credit_note', 'tax', 100, '2102', '502', array['502']::text[], -100, 'CL-F29-IVA', 20),
    ('CL-S-19-SERVICIOS', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('CL-S-19-SERVICIOS', 'invoice', 'tax', 100, '2102', '502', array['502']::text[], 100, 'CL-F29-IVA', 20),
    ('CL-S-19-SERVICIOS', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('CL-S-19-SERVICIOS', 'credit_note', 'tax', 100, '2102', '502', array['502']::text[], -100, 'CL-F29-IVA', 20),
    ('CL-S-EXE-EDU', 'invoice', 'base', 100, null, '142', array['142']::text[], 100, 'CL-F29-IVA', 10),
    ('CL-S-EXE-EDU', 'credit_note', 'base', 100, null, '142', array['142']::text[], -100, 'CL-F29-IVA', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'CL' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('CL', 'CL-F29-IVA', 'Formulario 29 — Declaración Mensual y Pago Simultáneo de Impuestos, sección Impuesto al Valor Agregado', array['month']::declaration_period[], 'month'::declaration_period, date '1975-01-01', null, 'Decreto Ley N° 825, art. 64, inciso primero — «Los contribuyentes afectos a la presente ley deberán pagar en la Tesorería Comunal respectiva, o en las oficinas bancarias autorizadas por el Servicio de Tesorerías, hasta el día 12 de cada mes, los impuestos devengados en el mes anterior… En el mismo acto deberán presentar una declaración jurada del monto total de las operaciones realizadas en el mes anterior, incluso las exentas de impuesto». Los campos son los códigos del Formulario 29, versión Internet, sección «Impuesto al Valor Agregado D.L. 825/74»; este paquete transcribe sólo los campos que el Impuesto al Valor Agregado alimenta y omite los de los demás tributos y regímenes que declara el mismo formulario (impuesto adicional a las ventas, cambio de sujeto, retenciones de la Ley de la Renta y pagos provisionales mensuales) — véase «Lo que este paquete no transcribe» en el README', true,'day_of_month_after_period'::filing_deadline_rule, 12, null, 'Decreto Ley N° 825, art. 64, inciso primero — pago hasta el día 12 del mes siguiente al de la operación. Un contribuyente que declara y paga por Internet obtiene, por resolución administrativa del Servicio de Impuestos Internos y no por esta ley, una prórroga hasta el día 20 (con pago) o el día 28 (sin pago) del mismo mes; este paquete declara el día que la ley fija a todo contribuyente, no la prórroga condicionada al canal de declaración', 'f29-plazos', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('CL', 'CL-F29-IVA', '20', 'base', 'Exportaciones (monto neto)', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 29, línea 1: «Exportaciones» — Cód. 585 (cantidad de documentos de exportación), Cód. 20 (monto neto contenido en los documentos registrados en el Cód. 585)', 'f29-formulario'),
  ('CL', 'CL-F29-IVA', '142', 'base', 'Ventas y/o servicios prestados exentos, o no gravados del giro (monto neto)', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 29, línea 2: «Ventas y/o Servicios prestados Exentos, o No Gravados del giro» — Cód. 586 (cantidad de documentos), Cód. 142 (monto neto de los documentos registrados en el Cód. 586)', 'f29-formulario'),
  ('CL', 'CL-F29-IVA', '502', 'tax', 'Débito fiscal — facturas emitidas por ventas y servicios del giro', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 29, línea 7: «Facturas emitidas por ventas y servicios del giro, o por cuenta de terceros» — Cód. 503 (cantidad de facturas emitidas durante el período), Cód. 502 (monto del impuesto recargado en las facturas registradas en el Cód. 503)', 'f29-instrucciones'),
  ('CL', 'CL-F29-IVA', '538', 'total', 'Total débitos', '{}'::jsonb, 40, null, array['502']::text[], '{}'::text[], null, null, false, false, null, 'Formulario 29, línea 23: «Registre el valor que resulte de realizar la operación aritmética de los montos de la línea 7 a 22» — este paquete suma únicamente el Cód. 502, la única línea de esa sección que sus impuestos alimentan', 'f29-instrucciones'),
  ('CL', 'CL-F29-IVA', '520', 'tax', 'Crédito fiscal — facturas recibidas del giro', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formulario 29, línea 28: «Facturas recibidas del giro y Facturas de compra emitidas» — Cód. 519 (cantidad de facturas recibidas durante el período, por adquisición de bienes o utilización de servicios que dan derecho a crédito fiscal), Cód. 520 (monto de crédito fiscal recargado en las facturas registradas en el Cód. 519)', 'f29-formulario'),
  ('CL', 'CL-F29-IVA', '537', 'total', 'Total créditos', '{}'::jsonb, 60, null, array['520']::text[], '{}'::text[], null, null, false, false, null, 'Formulario 29, línea 49: «Registre el valor que resulte de realizar la operación aritmética de los montos de la línea 28 a 48» — este paquete suma únicamente el Cód. 520, la única línea de esa sección que sus impuestos alimentan', 'f29-instrucciones'),
  ('CL', 'CL-F29-IVA', '89', 'total', 'Impuesto determinado (IVA a pagar)', '{}'::jsonb, 70, null, array['538']::text[], array['537']::text[], null, null, true, false, null, 'Formulario 29, línea 50, Cód. 89 — el resultado positivo de restar el Total de Créditos (Cód. 537) del Total de Débitos (Cód. 538) es el impuesto determinado del período', 'f29-formulario'),
  ('CL', 'CL-F29-IVA', '77', 'total', 'Remanente de crédito fiscal para el período siguiente', '{}'::jsonb, 80, null, array['537']::text[], array['538']::text[], null, null, true, false, null, 'Formulario 29, línea 50, Cód. 77 — cuando el Total de Créditos (Cód. 537) excede al Total de Débitos (Cód. 538), la diferencia es el remanente de crédito fiscal que el art. 26 del D.L. N° 825 acumula a los créditos del período tributario siguiente', 'f29-formulario')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('CL-BAL', 'CL', 'default', 'Estado de Situación Financiera', 'balance_sheet', 'CL-Ekwo', date '1970-01-01', null, 'Ley N° 18.046, sobre Sociedades Anónimas, art. 74 — el directorio presenta anualmente a la junta ordinaria de accionistas «una memoria razonada acerca de la situación de la sociedad en el último ejercicio, acompañada del balance general, del estado de ganancias y pérdidas», que «deberán reflejar con claridad la situación patrimonial de la sociedad al cierre del ejercicio y los beneficios obtenidos o las pérdidas sufridas durante el mismo». Chile no fija un plan de cuentas ni una estructura de líneas obligatoria para ese balance fuera de las sociedades que la Comisión para el Mercado Financiero fiscaliza (que reportan bajo Normas Internacionales de Información Financiera, cuyo texto no se transcribe aquí): esta es la estructura mínima que Ekwo instala por defecto, agrupada por naturaleza (activo circulante, activo fijo, pasivo circulante, pasivo no corriente, patrimonio), sobre el plan de cuentas propio del paquete', 'ley18046'),
  ('CL-RES', 'CL', 'default', 'Estado de Resultados', 'income_statement', 'CL-Ekwo', date '1970-01-01', null, 'Ley N° 18.046, sobre Sociedades Anónimas, art. 74 — el balance general se acompaña del «estado de ganancias y pérdidas» que refleja «los beneficios obtenidos o las pérdidas sufridas» del ejercicio. Estructura mínima propia de Ekwo, con los subtotales de utilidad bruta, operacional, antes de impuesto y neta', 'ley18046')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('CL-BAL', 'ACT', null, 'Total Activos', '{}'::jsonb, 10, 1, true, array['AC', 'AF', 'AO']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'AC', 'ACT', 'Activo Circulante', '{}'::jsonb, 20, 1, true, array['1101', '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1116', '1117', '1118', '1119', '1120', '1121', '1122', '1123', '1150D']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1101', 'AC', 'Caja', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1104', 'AC', 'Documentos por Cobrar', '{}'::jsonb, 35, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1102', 'AC', 'Banco', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1103', 'AC', 'Clientes', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1107', 'AC', 'IVA Crédito Fiscal Remanente', '{}'::jsonb, 55, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1105', 'AC', 'IVA Crédito Fiscal', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1116', 'AC', 'Materias Primas', '{}'::jsonb, 61, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1117', 'AC', 'Productos en Proceso', '{}'::jsonb, 62, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1118', 'AC', 'Productos Terminados', '{}'::jsonb, 63, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1119', 'AC', 'Mercaderías', '{}'::jsonb, 64, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1120', 'AC', 'Materiales y Repuestos', '{}'::jsonb, 65, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1121', 'AC', 'Provisión por Obsolescencia de Existencias', '{}'::jsonb, 66, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1106', 'AC', 'IVA Crédito Fiscal Servicios (Devengado no Pagado)', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1122', 'AC', 'Seguros Pagados por Anticipado', '{}'::jsonb, 71, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1123', 'AC', 'Arriendos Pagados por Anticipado', '{}'::jsonb, 72, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1108', 'AC', 'Existencias', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1110', 'AC', 'Anticipos a Proveedores', '{}'::jsonb, 81, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1111', 'AC', 'Otras Cuentas por Cobrar', '{}'::jsonb, 82, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1112', 'AC', 'Cuentas por Cobrar a Empresas Relacionadas', '{}'::jsonb, 83, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1113', 'AC', 'Préstamos al Personal', '{}'::jsonb, 84, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1114', 'AC', 'Pagos Provisionales Mensuales por Recuperar', '{}'::jsonb, 85, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1115', 'AC', 'Impuesto a la Renta por Recuperar', '{}'::jsonb, 86, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1109', 'AC', 'Gastos Pagados por Anticipado', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1150D', 'AC', 'Partidas Pendientes de Identificación (saldo deudor)', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, 'Sin correlato legal: cuenta de espera propia de Ekwo. Un saldo deudor es un activo y uno acreedor un pasivo — véase la línea 2107X', null),
  ('CL-BAL', 'AF', 'ACT', 'Activo Fijo', '{}'::jsonb, 110, 1, true, array['1201', '1202', '1203', '1204', '1205', '1206', '1207', '1210', '1211', '1212', '1213', '1214', '1215', '1216']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1201', 'AF', 'Terrenos', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1202', 'AF', 'Construcciones y Edificios', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1203', 'AF', 'Maquinarias y Equipos', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1204', 'AF', 'Muebles y Útiles', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1205', 'AF', 'Equipos Computacionales', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1206', 'AF', 'Vehículos', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1207', 'AF', 'Depreciación Acumulada', '{}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1210', 'AF', 'Obras en Construcción', '{}'::jsonb, 181, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1211', 'AF', 'Herramientas y Equipos Menores', '{}'::jsonb, 182, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1212', 'AF', 'Instalaciones', '{}'::jsonb, 183, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1213', 'AF', 'Mejoras en Bienes Arrendados', '{}'::jsonb, 184, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1214', 'AF', 'Depreciación Acumulada Herramientas y Equipos Menores', '{}'::jsonb, 185, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1215', 'AF', 'Depreciación Acumulada Instalaciones', '{}'::jsonb, 186, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1216', 'AF', 'Depreciación Acumulada Mejoras en Bienes Arrendados', '{}'::jsonb, 187, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'AO', 'ACT', 'Otros Activos', '{}'::jsonb, 190, 1, true, array['1301', '1310', '1311', '1312']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1301', 'AO', 'Activos Intangibles', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1310', 'AO', 'Amortización Acumulada de Intangibles', '{}'::jsonb, 201, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1311', 'AO', 'Inversiones en Empresas Relacionadas', '{}'::jsonb, 202, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1312', 'AO', 'Depósitos en Garantía', '{}'::jsonb, 203, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'PYP', null, 'Total Pasivo y Patrimonio', '{}'::jsonb, 210, 1, true, array['PAS', 'PAT']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'PAS', 'PYP', 'Total Pasivo', '{}'::jsonb, 220, 1, true, array['PC', 'PNC']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'PC', 'PAS', 'Pasivo Circulante', '{}'::jsonb, 230, 1, true, array['2101', '2102', '2103', '2104', '2105', '2106', '2107', '2108', '2109', '2110', '2111', '2112', '2113', '2114', '2115', '2116', '1150C', '2117', '2118', '2119', '2120']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2108', 'PC', 'Documentos por Pagar', '{}'::jsonb, 231, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2109', 'PC', 'Otras Cuentas por Pagar', '{}'::jsonb, 232, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2110', 'PC', 'Cuentas por Pagar a Empresas Relacionadas', '{}'::jsonb, 233, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2111', 'PC', 'Dividendos por Pagar', '{}'::jsonb, 234, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2112', 'PC', 'Impuesto a la Renta por Pagar', '{}'::jsonb, 235, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2113', 'PC', 'AFP por Pagar', '{}'::jsonb, 236, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2114', 'PC', 'Salud (Isapre/Fonasa) por Pagar', '{}'::jsonb, 237, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2115', 'PC', 'Mutual de Seguridad por Pagar', '{}'::jsonb, 238, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2116', 'PC', 'Seguro de Cesantía (AFC) por Pagar', '{}'::jsonb, 239, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2101', 'PC', 'Proveedores', '{}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2102', 'PC', 'IVA Débito Fiscal', '{}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2103', 'PC', 'IVA por Pagar', '{}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2104', 'PC', 'IVA Débito Fiscal Servicios (Devengado no Percibido)', '{}'::jsonb, 270, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2105', 'PC', 'Retenciones y Otros Impuestos por Pagar', '{}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2106', 'PC', 'Remuneraciones por Pagar', '{}'::jsonb, 290, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2107', 'PC', 'Provisiones', '{}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '1150C', 'PC', 'Partidas Pendientes de Identificación (saldo acreedor)', '{}'::jsonb, 310, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2117', 'PC', 'Impuesto Único de Segunda Categoría por Pagar', '{}'::jsonb, 311, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2118', 'PC', 'Provisión de Vacaciones', '{}'::jsonb, 312, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2119', 'PC', 'Provisión de Gratificaciones', '{}'::jsonb, 313, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2120', 'PC', 'Provisión de Indemnización por Años de Servicio', '{}'::jsonb, 314, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'PNC', 'PAS', 'Pasivo No Corriente', '{}'::jsonb, 320, 1, true, array['2201', '2210', '2211']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2201', 'PNC', 'Préstamos Bancarios Largo Plazo', '{}'::jsonb, 330, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2210', 'PNC', 'Leasing por Pagar Largo Plazo', '{}'::jsonb, 331, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '2211', 'PNC', 'Provisiones Largo Plazo', '{}'::jsonb, 332, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', 'PAT', 'PYP', 'Patrimonio', '{}'::jsonb, 340, 1, true, array['3101', '3102', '3103', '3104', '3105', '3106', '3107', '3108']::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3101', 'PAT', 'Capital', '{}'::jsonb, 350, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3102', 'PAT', 'Reservas', '{}'::jsonb, 360, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3103', 'PAT', 'Utilidades Acumuladas', '{}'::jsonb, 370, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3104', 'PAT', 'Pérdidas Acumuladas', '{}'::jsonb, 380, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3105', 'PAT', 'Resultado del Ejercicio (Utilidad)', '{}'::jsonb, 390, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3106', 'PAT', 'Resultado del Ejercicio (Pérdida)', '{}'::jsonb, 400, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3107', 'PAT', 'Reserva Legal', '{}'::jsonb, 401, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-BAL', '3108', 'PAT', 'Otras Reservas de Capital', '{}'::jsonb, 402, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', 'ING', null, 'Ingresos', '{}'::jsonb, 10, 1, true, array['4101', '4102', '4103', '4104', '4105', '4106', '4107', '4108', '4109']::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4101', 'ING', 'Ventas Nacionales', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4102', 'ING', 'Ventas de Exportación', '{}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4103', 'ING', 'Servicios Prestados', '{}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4104', 'ING', 'Otros Ingresos de Explotación', '{}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4105', 'ING', 'Ingresos Financieros', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4106', 'ING', 'Utilidad por Diferencia de Cambio', '{}'::jsonb, 70, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4107', 'ING', 'Devoluciones y Bonificaciones sobre Ventas', '{}'::jsonb, 71, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4108', 'ING', 'Descuentos Obtenidos por Pronto Pago', '{}'::jsonb, 72, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '4109', 'ING', 'Arriendos Ganados', '{}'::jsonb, 73, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', 'CV', null, 'Costo de Ventas', '{}'::jsonb, 80, 1, true, array['5101', '5102', '5140', '5141', '5142']::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5101', 'CV', 'Costo de Ventas', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5102', 'CV', 'Compras', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5140', 'CV', 'Mano de Obra Directa', '{}'::jsonb, 101, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5141', 'CV', 'Materiales Directos', '{}'::jsonb, 102, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5142', 'CV', 'Gastos Indirectos de Fabricación', '{}'::jsonb, 103, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', 'UB', null, 'Utilidad (Pérdida) Bruta', '{}'::jsonb, 110, 1, true, array['ING']::text[], array['CV']::text[], null, null, null),
  ('CL-RES', 'GO', null, 'Gastos de Operación', '{}'::jsonb, 120, 1, true, array['5103', '5104', '5105', '5110', '5111', '5112', '5113', '5114', '5115', '5116', '5117', '5118', '5119', '5120', '5121', '5122', '5123', '5124', '5125', '5126', '5128', '5129', '5131', '5132', '5133']::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5103', 'GO', 'Gastos de Administración y Ventas', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5111', 'GO', 'Sueldos y Salarios', '{}'::jsonb, 131, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5112', 'GO', 'Leyes Sociales', '{}'::jsonb, 132, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5113', 'GO', 'Gratificaciones', '{}'::jsonb, 133, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5114', 'GO', 'Indemnización por Años de Servicio', '{}'::jsonb, 134, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5115', 'GO', 'Vacaciones', '{}'::jsonb, 135, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5116', 'GO', 'Honorarios Profesionales', '{}'::jsonb, 136, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5117', 'GO', 'Arriendos', '{}'::jsonb, 137, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5118', 'GO', 'Seguros Generales', '{}'::jsonb, 138, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5119', 'GO', 'Servicios Básicos', '{}'::jsonb, 139, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5104', 'GO', 'Remuneraciones', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5120', 'GO', 'Mantención y Reparaciones', '{}'::jsonb, 141, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5121', 'GO', 'Materiales de Oficina', '{}'::jsonb, 142, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5122', 'GO', 'Publicidad y Marketing', '{}'::jsonb, 143, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5123', 'GO', 'Gastos de Representación', '{}'::jsonb, 144, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5124', 'GO', 'Viáticos y Gastos de Viaje', '{}'::jsonb, 145, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5125', 'GO', 'Fletes y Transportes', '{}'::jsonb, 146, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5126', 'GO', 'Comunicaciones', '{}'::jsonb, 147, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5128', 'GO', 'Amortización de Intangibles', '{}'::jsonb, 148, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5129', 'GO', 'Castigo de Cuentas Incobrables', '{}'::jsonb, 149, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5105', 'GO', 'Depreciación del Ejercicio', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5131', 'GO', 'Donaciones', '{}'::jsonb, 151, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5132', 'GO', 'Patentes Municipales', '{}'::jsonb, 152, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5133', 'GO', 'Capacitación del Personal', '{}'::jsonb, 153, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5110', 'GO', 'Servicios Recibidos del Exterior', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', 'UO', null, 'Utilidad (Pérdida) Operacional', '{}'::jsonb, 170, 1, true, array['UB']::text[], array['GO']::text[], null, null, null),
  ('CL-RES', 'RF', null, 'Resultado No Operacional', '{}'::jsonb, 180, 1, true, array['5106', '5107', '5108', '5127', '5130', '5134']::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5106', 'RF', 'Gastos Financieros', '{}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5107', 'RF', 'Pérdida por Diferencia de Cambio', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5108', 'RF', 'Diferencias de Redondeo', '{}'::jsonb, 205, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5127', 'RF', 'Gastos Bancarios', '{}'::jsonb, 206, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5130', 'RF', 'Multas e Intereses Fiscales', '{}'::jsonb, 207, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', '5134', 'RF', 'Intereses por Préstamos', '{}'::jsonb, 208, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', 'UAI', null, 'Utilidad (Pérdida) Antes de Impuesto', '{}'::jsonb, 210, 1, true, array['UO']::text[], array['RF']::text[], null, null, null),
  ('CL-RES', '5109', null, 'Impuesto a la Renta', '{}'::jsonb, 220, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('CL-RES', 'UN', null, 'Utilidad (Pérdida) Neta', '{}'::jsonb, 230, 1, true, array['UAI']::text[], array['5109']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('CL-BAL', '1101', 10, 'account_code', '1101', null, null, 'any'),
    ('CL-BAL', '1104', 10, 'account_code', '1104', null, null, 'any'),
    ('CL-BAL', '1102', 10, 'account_code', '1102', null, null, 'any'),
    ('CL-BAL', '1103', 10, 'account_code', '1103', null, null, 'any'),
    ('CL-BAL', '1107', 10, 'account_code', '1107', null, null, 'any'),
    ('CL-BAL', '1105', 10, 'account_code', '1105', null, null, 'any'),
    ('CL-BAL', '1116', 10, 'account_code', '1116', null, null, 'any'),
    ('CL-BAL', '1117', 10, 'account_code', '1117', null, null, 'any'),
    ('CL-BAL', '1118', 10, 'account_code', '1118', null, null, 'any'),
    ('CL-BAL', '1119', 10, 'account_code', '1119', null, null, 'any'),
    ('CL-BAL', '1120', 10, 'account_code', '1120', null, null, 'any'),
    ('CL-BAL', '1121', 10, 'account_code', '1121', null, null, 'any'),
    ('CL-BAL', '1106', 10, 'account_code', '1106', null, null, 'any'),
    ('CL-BAL', '1122', 10, 'account_code', '1122', null, null, 'any'),
    ('CL-BAL', '1123', 10, 'account_code', '1123', null, null, 'any'),
    ('CL-BAL', '1108', 10, 'account_code', '1108', null, null, 'any'),
    ('CL-BAL', '1110', 10, 'account_code', '1110', null, null, 'any'),
    ('CL-BAL', '1111', 10, 'account_code', '1111', null, null, 'any'),
    ('CL-BAL', '1112', 10, 'account_code', '1112', null, null, 'any'),
    ('CL-BAL', '1113', 10, 'account_code', '1113', null, null, 'any'),
    ('CL-BAL', '1114', 10, 'account_code', '1114', null, null, 'any'),
    ('CL-BAL', '1115', 10, 'account_code', '1115', null, null, 'any'),
    ('CL-BAL', '1109', 10, 'account_code', '1109', null, null, 'any'),
    ('CL-BAL', '1150D', 10, 'account_code', '1150', null, null, 'debit'),
    ('CL-BAL', '1201', 10, 'account_code', '1201', null, null, 'any'),
    ('CL-BAL', '1202', 10, 'account_code', '1202', null, null, 'any'),
    ('CL-BAL', '1203', 10, 'account_code', '1203', null, null, 'any'),
    ('CL-BAL', '1204', 10, 'account_code', '1204', null, null, 'any'),
    ('CL-BAL', '1205', 10, 'account_code', '1205', null, null, 'any'),
    ('CL-BAL', '1206', 10, 'account_code', '1206', null, null, 'any'),
    ('CL-BAL', '1207', 10, 'account_code', '1207', null, null, 'any'),
    ('CL-BAL', '1210', 10, 'account_code', '1210', null, null, 'any'),
    ('CL-BAL', '1211', 10, 'account_code', '1211', null, null, 'any'),
    ('CL-BAL', '1212', 10, 'account_code', '1212', null, null, 'any'),
    ('CL-BAL', '1213', 10, 'account_code', '1213', null, null, 'any'),
    ('CL-BAL', '1214', 10, 'account_code', '1214', null, null, 'any'),
    ('CL-BAL', '1215', 10, 'account_code', '1215', null, null, 'any'),
    ('CL-BAL', '1216', 10, 'account_code', '1216', null, null, 'any'),
    ('CL-BAL', '1301', 10, 'account_code', '1301', null, null, 'any'),
    ('CL-BAL', '1310', 10, 'account_code', '1310', null, null, 'any'),
    ('CL-BAL', '1311', 10, 'account_code', '1311', null, null, 'any'),
    ('CL-BAL', '1312', 10, 'account_code', '1312', null, null, 'any'),
    ('CL-BAL', '2108', 10, 'account_code', '2108', null, null, 'any'),
    ('CL-BAL', '2109', 10, 'account_code', '2109', null, null, 'any'),
    ('CL-BAL', '2110', 10, 'account_code', '2110', null, null, 'any'),
    ('CL-BAL', '2111', 10, 'account_code', '2111', null, null, 'any'),
    ('CL-BAL', '2112', 10, 'account_code', '2112', null, null, 'any'),
    ('CL-BAL', '2113', 10, 'account_code', '2113', null, null, 'any'),
    ('CL-BAL', '2114', 10, 'account_code', '2114', null, null, 'any'),
    ('CL-BAL', '2115', 10, 'account_code', '2115', null, null, 'any'),
    ('CL-BAL', '2116', 10, 'account_code', '2116', null, null, 'any'),
    ('CL-BAL', '2101', 10, 'account_code', '2101', null, null, 'any'),
    ('CL-BAL', '2102', 10, 'account_code', '2102', null, null, 'any'),
    ('CL-BAL', '2103', 10, 'account_code', '2103', null, null, 'any'),
    ('CL-BAL', '2104', 10, 'account_code', '2104', null, null, 'any'),
    ('CL-BAL', '2105', 10, 'account_code', '2105', null, null, 'any'),
    ('CL-BAL', '2106', 10, 'account_code', '2106', null, null, 'any'),
    ('CL-BAL', '2107', 10, 'account_code', '2107', null, null, 'any'),
    ('CL-BAL', '1150C', 10, 'account_code', '1150', null, null, 'credit'),
    ('CL-BAL', '2117', 10, 'account_code', '2117', null, null, 'any'),
    ('CL-BAL', '2118', 10, 'account_code', '2118', null, null, 'any'),
    ('CL-BAL', '2119', 10, 'account_code', '2119', null, null, 'any'),
    ('CL-BAL', '2120', 10, 'account_code', '2120', null, null, 'any'),
    ('CL-BAL', '2201', 10, 'account_code', '2201', null, null, 'any'),
    ('CL-BAL', '2210', 10, 'account_code', '2210', null, null, 'any'),
    ('CL-BAL', '2211', 10, 'account_code', '2211', null, null, 'any'),
    ('CL-BAL', '3101', 10, 'account_code', '3101', null, null, 'any'),
    ('CL-BAL', '3102', 10, 'account_code', '3102', null, null, 'any'),
    ('CL-BAL', '3103', 10, 'account_code', '3103', null, null, 'any'),
    ('CL-BAL', '3104', 10, 'account_code', '3104', null, null, 'any'),
    ('CL-BAL', '3105', 10, 'account_code', '3105', null, null, 'any'),
    ('CL-BAL', '3106', 10, 'account_code', '3106', null, null, 'any'),
    ('CL-BAL', '3107', 10, 'account_code', '3107', null, null, 'any'),
    ('CL-BAL', '3108', 10, 'account_code', '3108', null, null, 'any'),
    ('CL-RES', '4101', 10, 'account_code', '4101', null, null, 'any'),
    ('CL-RES', '4102', 10, 'account_code', '4102', null, null, 'any'),
    ('CL-RES', '4103', 10, 'account_code', '4103', null, null, 'any'),
    ('CL-RES', '4104', 10, 'account_code', '4104', null, null, 'any'),
    ('CL-RES', '4105', 10, 'account_code', '4105', null, null, 'any'),
    ('CL-RES', '4106', 10, 'account_code', '4106', null, null, 'any'),
    ('CL-RES', '4107', 10, 'account_code', '4107', null, null, 'any'),
    ('CL-RES', '4108', 10, 'account_code', '4108', null, null, 'any'),
    ('CL-RES', '4109', 10, 'account_code', '4109', null, null, 'any'),
    ('CL-RES', '5101', 10, 'account_code', '5101', null, null, 'any'),
    ('CL-RES', '5102', 10, 'account_code', '5102', null, null, 'any'),
    ('CL-RES', '5140', 10, 'account_code', '5140', null, null, 'any'),
    ('CL-RES', '5141', 10, 'account_code', '5141', null, null, 'any'),
    ('CL-RES', '5142', 10, 'account_code', '5142', null, null, 'any'),
    ('CL-RES', '5103', 10, 'account_code', '5103', null, null, 'any'),
    ('CL-RES', '5111', 10, 'account_code', '5111', null, null, 'any'),
    ('CL-RES', '5112', 10, 'account_code', '5112', null, null, 'any'),
    ('CL-RES', '5113', 10, 'account_code', '5113', null, null, 'any'),
    ('CL-RES', '5114', 10, 'account_code', '5114', null, null, 'any'),
    ('CL-RES', '5115', 10, 'account_code', '5115', null, null, 'any'),
    ('CL-RES', '5116', 10, 'account_code', '5116', null, null, 'any'),
    ('CL-RES', '5117', 10, 'account_code', '5117', null, null, 'any'),
    ('CL-RES', '5118', 10, 'account_code', '5118', null, null, 'any'),
    ('CL-RES', '5119', 10, 'account_code', '5119', null, null, 'any'),
    ('CL-RES', '5104', 10, 'account_code', '5104', null, null, 'any'),
    ('CL-RES', '5120', 10, 'account_code', '5120', null, null, 'any'),
    ('CL-RES', '5121', 10, 'account_code', '5121', null, null, 'any'),
    ('CL-RES', '5122', 10, 'account_code', '5122', null, null, 'any'),
    ('CL-RES', '5123', 10, 'account_code', '5123', null, null, 'any'),
    ('CL-RES', '5124', 10, 'account_code', '5124', null, null, 'any'),
    ('CL-RES', '5125', 10, 'account_code', '5125', null, null, 'any'),
    ('CL-RES', '5126', 10, 'account_code', '5126', null, null, 'any'),
    ('CL-RES', '5128', 10, 'account_code', '5128', null, null, 'any'),
    ('CL-RES', '5129', 10, 'account_code', '5129', null, null, 'any'),
    ('CL-RES', '5105', 10, 'account_code', '5105', null, null, 'any'),
    ('CL-RES', '5131', 10, 'account_code', '5131', null, null, 'any'),
    ('CL-RES', '5132', 10, 'account_code', '5132', null, null, 'any'),
    ('CL-RES', '5133', 10, 'account_code', '5133', null, null, 'any'),
    ('CL-RES', '5110', 10, 'account_code', '5110', null, null, 'any'),
    ('CL-RES', '5106', 10, 'account_code', '5106', null, null, 'any'),
    ('CL-RES', '5107', 10, 'account_code', '5107', null, null, 'any'),
    ('CL-RES', '5108', 10, 'account_code', '5108', null, null, 'any'),
    ('CL-RES', '5127', 10, 'account_code', '5127', null, null, 'any'),
    ('CL-RES', '5130', 10, 'account_code', '5130', null, null, 'any'),
    ('CL-RES', '5134', 10, 'account_code', '5134', null, null, 'any'),
    ('CL-RES', '5109', 10, 'account_code', '5109', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('CL', 'Chile', '{}'::jsonb, array['es']::text[], 'CLP', '1103', '2101', '1150', '5108', '3103', '4101', '5102', '1102', '1101', 'VEN', 'COM', 'DIA', 'es', 'result_accounts', '3105', '3106', '3104', 'APE', 'half_up', default, '4106', '5107', null, null, null, null, '2103', '1107', 'Asiento de apertura', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{NNNN}',
  legal_payment_days            = 30,
  late_payment_reference        = 'Ley N° 21.131, que establece un plazo máximo de 30 días corridos desde la recepción de la factura para su pago, salvo pacto escrito en contrario que cumpla los requisitos legales; desde el primer día de mora se aplica el interés corriente para operaciones no reajustables en moneda nacional (según el monto y plazo de la operación) más una comisión fija de recuperación de pago del 1 % del saldo insoluto (art. 2° bis de la ley, que incorpora los arts. 2 bis y siguientes a la Ley N° 19.983)',
  numbering_legal_reference     = 'Decreto Ley N° 825, art. 54 — los documentos tributarios (facturas, boletas, guías de despacho, notas de débito y de crédito) son documentos electrónicos con «folio» dentro de un «Código de Autorización de Folios» (CAF) que el Servicio de Impuestos Internos autoriza previamente por rangos, correlativo por tipo de documento y no reiniciado cada año. El folio de un CAF lo asigna y usa el propio emisor dentro del rango autorizado — no es asignado documento a documento por el Servicio, a diferencia del folio fiscal (UUID) del CFDI mexicano. El número que declara este paquete es el de la pieza contable, correlativo por diario, y no un folio de un CAF que Ekwo no solicita: véase «Ekwo no emite un DTE chileno» en el README',
  numbering_source_key          = 'dl825',
  payment_terms_legal_reference = 'Ley N° 21.131, de 2019 (D.O. 16.01.2019, vigencia 17.05.2019), que modifica la Ley N° 19.983: plazo máximo de pago de 30 días corridos desde la recepción de la factura, salvo acuerdo escrito excepcional entre las partes que cumpla los requisitos legales (identificación de las partes, giro, fecha, plazo, vigencia, inscripción en el Registro de Acuerdos de Pago del Ministerio de Economía dentro de 5 días hábiles) y no constituya una cláusula abusiva',
  payment_terms_source_key      = 'ley21131',
  tax_point_rule                = 'delivery_date',
  tax_point_legal_reference     = 'Decreto Ley N° 825, art. 9°, letra a) — «El impuesto establecido en este Título se devengará: a) En las ventas de bienes corporales muebles y prestaciones de servicios, en la fecha de emisión de la factura o boleta. En la venta de bienes corporales muebles, en caso que la entrega de las especies sea anterior a dicha fecha o bien, cuando por la naturaleza del acto que da origen a la transferencia no se emitan dichos documentos, el impuesto se devengará en la fecha de la entrega real o simbólica de las especies. En las prestaciones de servicios, si no se hubieren emitido facturas o boletas, según corresponda, o no correspondiere emitirlas, el tributo se devengará, en cualquier forma, a disposición del prestador del servicio». El art. 55 exige que, en la venta de bienes, la factura se emita «en el mismo momento» de la entrega, de modo que factura y entrega coinciden salvo mora del emisor — caso en que la entrega, más temprana, sigue fijando el devengo: por eso este paquete declara delivery_date como regla general, igual que Francia. En los servicios el art. 55 exige la factura «en el momento en que se perciba o se ponga, en cualquier forma, a disposición del prestador del servicio» la remuneración, de modo que el devengo de un servicio coincide con su cobro: los códigos de impuesto de servicios de este paquete llevan cash_basis, con la cuenta de tránsito que exige ese campo, en vez de un segundo valor de tax_point que el formato no admite',
  tax_point_source_key          = 'dl825',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Decreto Ley N° 825, arts. 21 N° 2° y 57 — un débito fiscal facturado en exceso, o una venta o servicio resciliado, anulado o devuelto, se corrige con una nota de crédito que individualiza el documento que rectifica, nunca con la modificación del documento original; el art. 29-A del Código Fiscal (por analogía con el criterio del Servicio) y el propio DTE, una vez con folio de un CAF y enviado, no admiten edición. Ekwo no emite folios de un CAF (véase el README), pero conserva la misma regla: un documento contabilizado se corrige con un comprobante de egreso (nota de crédito) que lo nombra',
  posted_edit_policy_source_key = 'dl825',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Decreto Ley N° 825, art. 54, y art. 54, incisos siguientes (según los sustituyó la Ley N° 20.727, D.O. 31.01.2014) — las facturas, facturas de compra, guías de despacho, boletas, liquidaciones-factura y notas de débito y de crédito se emiten exclusivamente como documentos tributarios electrónicos (DTE), con folio de un Código de Autorización de Folios (CAF) que el Servicio de Impuestos Internos autoriza por rangos, timbre electrónico del emisor y envío del documento al Servicio dentro del plazo que fija la resolución respectiva. La obligatoriedad se implementó de forma escalonada según tamaño de la empresa desde noviembre de 2014 y alcanzó a todas las empresas del país el 1 de febrero de 2018 («A partir de hoy todas las empresas del país deben facturar electrónicamente», noticia SII del 01.02.2018): desde esa fecha, un documento en papel «no tendrá validez legal». Es un régimen de autorización previa de folios y envío al Servicio (más próximo a un reporte continuo de operaciones que a la validación documento a documento de un tercero certificador, como el PAC mexicano) y no un intercambio entre empresas gobernado por un perfil construido sobre EN 16931. EKWO NO SOLICITA CAF, NO TIMBRA NI TRANSMITE DTE: ningún componente de packages/formats emite el XML del DTE chileno ni se comunica con el Servicio de Impuestos Internos, y un documento emitido desde Ekwo no es un comprobante tributario chileno. Por eso profile, mandatory_from y party_scheme/vat_scheme quedan vacíos aunque la obligación exista: profile nombra un perfil construido sobre EN 16931 que una pieza de packages/formats escribe, el DTE no lo es, y el formato refuse un mandatory_from sin profile. El Rol Único Tributario (RUT) identifica a emisor y receptor y no tiene código ISO 6523 de la lista que el formato usa para party_scheme y vat_scheme',
  einvoice_source_key           = 'ley20727',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = array['csv']::text[],
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'CL';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('CL', 'dte_not_issued', 'always', 'Este documento no es un Documento Tributario Electrónico (DTE) chileno: no lleva folio de un Código de Autorización de Folios (CAF) del Servicio de Impuestos Internos ni su timbre electrónico. Sólo el DTE con folio de un CAF ampara la operación para efectos tributarios en Chile.', '{}'::jsonb, 10, date '1970-01-01', null, 'Decreto Ley N° 825, art. 54, y art. 54, incisos siguientes, sobre la exigencia de que los documentos tributarios sean documentos electrónicos con folio de un CAF autorizado por el Servicio de Impuestos Internos; Ley N° 20.727. Ekwo no solicita CAF, no timbra ni transmite DTE: la frase evita que el documento que Ekwo produce se tome por el comprobante fiscal chileno'),
  ('CL', 'export', 'export', 'Exportación — venta o servicio exento del Impuesto al Valor Agregado (artículo 12, letra D, o letra E, N° 16, del D.L. N° 825, de 1974).', '{}'::jsonb, 20, date '1970-01-01', null, 'Decreto Ley N° 825, art. 12, letra D («Las especies exportadas en su venta al exterior») y letra E, N° 16 (ingresos por servicios prestados a personas sin domicilio ni residencia en Chile, calificados como exportación por el Servicio Nacional de Aduanas)'),
  ('CL', 'exempt', 'exempt', 'Operación exenta del Impuesto al Valor Agregado (artículo 12 o 13 del D.L. N° 825, de 1974, según el caso).', '{}'::jsonb, 30, date '1970-01-01', null, 'Decreto Ley N° 825, arts. 12 y 13 — ventas, servicios, empresas e instituciones exentas del impuesto de este Título'),
  ('CL', 'reverse_charge', 'reverse_charge', 'El impuesto de este servicio lo declara y entera el beneficiario del servicio, contribuyente de este impuesto (artículo 11, letra e), del D.L. N° 825, de 1974).', '{}'::jsonb, 40, date '1970-01-01', null, 'Decreto Ley N° 825, art. 11, letra e) — es sujeto del impuesto «el beneficiario del servicio que sea contribuyente de este impuesto, siempre que la prestación sea realizada por un prestador domiciliado o residente en el extranjero»')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
