-- Ekwo OS — Nigeria: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ng at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build ng`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Nigeria Tax Act, 2025 (Act No. 7 of 2025), Federal Republic of Nigeria Official Gazette No. 117, Vol. 112, 26 June 2025, pages A387–A596 — in force from 1 January 2026, repealing the Value Added Tax Act, Cap. V1, LFN 2004 (Federal Government Printer, Lagos — mirrored by the Tax Appeal Tribunal)
--     https://tat.gov.ng/Nigeria-Tax-Act-2025.pdf
--   Nigeria Tax Administration Act, 2025 (Act No. 5 of 2025), Federal Republic of Nigeria Official Gazette No. 117, Vol. 112, 26 June 2025, pages A259–A345 — in force from 1 January 2026 (Federal Government Printer, Lagos — mirrored by the Tax Appeal Tribunal)
--     https://tat.gov.ng/NIGERIA-TAX-ADMINISTRATION-ACT-2025.pdf
--   Nigeria Revenue Service (Establishment) Act, 2025 (Act No. 4 of 2025) — renames the Federal Inland Revenue Service the Nigeria Revenue Service and continues it as "the Service" of the Nigeria Tax Act and the Nigeria Tax Administration Act (Federal Government Printer, Lagos — mirrored by the Tax Appeal Tribunal)
--     https://tat.gov.ng/NIGERIA-REVENUE-SERVICE-ACT-2025.pdf
--   Value Added Tax Return, Form VAT 002, and its explanatory notes — the most recent public specimen of the paper return, printed with a worked example at the 5% rate that preceded the Finance Act 2019 (Federal Inland Revenue Service)
--     https://firs.gov.ng/wp-content/uploads/2020/10/VAT-FORM-20-02-20.pdf
--   TaxPro-Max — the e-filing portal the Service has required for VAT returns since June 2021; no manual submission is accepted for a naira-denominated return (Federal Inland Revenue Service)
--     https://taxpromax.firs.gov.ng/
--   FIRS e-Invoicing — the Merchant-Buyer Solution: live from 1 August 2025, onboarding of taxpayers with an annual turnover of at least ₦5 billion required by 1 November 2025 after a three-month extension (Federal Inland Revenue Service)
--     https://firs.gov.ng/e-invoice/
--   Companies and Allied Matters Act, 2020 (Act No. 3 of 2020), assented 7 August 2020 — Part XI (Accounts and Audit) and the First Schedule (form and content of financial statements) (Corporate Affairs Commission)
--     https://www.cac.gov.ng/wp-content/uploads/2020/12/CAMA-NOTE-BOOK-FULL-VERSION.pdf
--   Financial Reporting Council of Nigeria Act, 2011 (Act No. 6 of 2011) (Financial Reporting Council of Nigeria)
--     https://frcnigeria.gov.ng/wp-content/uploads/2024/08/The-FRC-Act_merged.pdf
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('NG', 'Nigeria', '0.1.0', date '2026-09-25', '20260917170000', 'community', null, null, '8f0ad80dfdc8e4aa8e0c8455106c1eb3e59a5ac0ffaf9cd1c91728dabc5648ec', '[{"key":"nta-2025","title":"Nigeria Tax Act, 2025 (Act No. 7 of 2025), Federal Republic of Nigeria Official Gazette No. 117, Vol. 112, 26 June 2025, pages A387–A596 — in force from 1 January 2026, repealing the Value Added Tax Act, Cap. V1, LFN 2004","publisher":"Federal Government Printer, Lagos — mirrored by the Tax Appeal Tribunal","url":"https://tat.gov.ng/Nigeria-Tax-Act-2025.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"ntaa-2025","title":"Nigeria Tax Administration Act, 2025 (Act No. 5 of 2025), Federal Republic of Nigeria Official Gazette No. 117, Vol. 112, 26 June 2025, pages A259–A345 — in force from 1 January 2026","publisher":"Federal Government Printer, Lagos — mirrored by the Tax Appeal Tribunal","url":"https://tat.gov.ng/NIGERIA-TAX-ADMINISTRATION-ACT-2025.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"nrs-act-2025","title":"Nigeria Revenue Service (Establishment) Act, 2025 (Act No. 4 of 2025) — renames the Federal Inland Revenue Service the Nigeria Revenue Service and continues it as \"the Service\" of the Nigeria Tax Act and the Nigeria Tax Administration Act","publisher":"Federal Government Printer, Lagos — mirrored by the Tax Appeal Tribunal","url":"https://tat.gov.ng/NIGERIA-REVENUE-SERVICE-ACT-2025.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"vat-form-002","title":"Value Added Tax Return, Form VAT 002, and its explanatory notes — the most recent public specimen of the paper return, printed with a worked example at the 5% rate that preceded the Finance Act 2019","publisher":"Federal Inland Revenue Service","url":"https://firs.gov.ng/wp-content/uploads/2020/10/VAT-FORM-20-02-20.pdf","consulted_on":"2026-09-25","kind":"form"},{"key":"taxpro-max","title":"TaxPro-Max — the e-filing portal the Service has required for VAT returns since June 2021; no manual submission is accepted for a naira-denominated return","publisher":"Federal Inland Revenue Service","url":"https://taxpromax.firs.gov.ng/","consulted_on":"2026-09-25","kind":"portal"},{"key":"mbs-rollout","title":"FIRS e-Invoicing — the Merchant-Buyer Solution: live from 1 August 2025, onboarding of taxpayers with an annual turnover of at least ₦5 billion required by 1 November 2025 after a three-month extension","publisher":"Federal Inland Revenue Service","url":"https://firs.gov.ng/e-invoice/","consulted_on":"2026-09-25","kind":"portal"},{"key":"cama-2020","title":"Companies and Allied Matters Act, 2020 (Act No. 3 of 2020), assented 7 August 2020 — Part XI (Accounts and Audit) and the First Schedule (form and content of financial statements)","publisher":"Corporate Affairs Commission","url":"https://www.cac.gov.ng/wp-content/uploads/2020/12/CAMA-NOTE-BOOK-FULL-VERSION.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"frc-act-2011","title":"Financial Reporting Council of Nigeria Act, 2011 (Act No. 6 of 2011)","publisher":"Financial Reporting Council of Nigeria","url":"https://frcnigeria.gov.ng/wp-content/uploads/2024/08/The-FRC-Act_merged.pdf","consulted_on":"2026-09-25","kind":"law"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('NG', 'default', 'Nigeria reference chart of accounts', '{}'::jsonb, true, 'companies', array['NG-CAMA-BS', 'NG-CAMA-IS']::text[], null, 'There is no legal chart of accounts in Nigeria. Companies and Allied Matters Act 2020, s. 378(1) requires the financial statements every company''s directors prepare under s. 377 to comply with the First Schedule to the Act "so far as applicable" for their form and content, and with the accounting standards the Financial Reporting Council of Nigeria lays down under the Financial Reporting Council of Nigeria Act 2011 — the FRC having adopted the IFRS Accounting Standards for public interest entities and the IFRS for SMEs Standard for other entities. Neither prescribes a nominal ledger, only a balance sheet and profit and loss account format (First Schedule, Section C, Format 1, the format this chart''s statements follow) and a set of recognition and measurement standards. This chart is original: four digits, blocked so that each range reaches one line of the First Schedule Format 1 balance sheet or profit and loss account, carrying the accounts a Nigerian company actually keeps — VAT recoverable and payable, the amount due to or from the Service, VAT paid to the Nigeria Customs Service on import, Pay As You Earn, Pension Reform Act and National Housing Fund contributions, the Nigeria Social Insurance Trust Fund and Industrial Training Fund levies, withholding tax credit notes and withholding tax payable, and Companies Income Tax and Development Levy apart from VAT.', 'cama-2020')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('NG', 'default', '0000', 'Called up share capital not paid', '{}'::jsonb, 'asset_current', false, null, 10),
  ('NG', 'default', '0010', 'Goodwill', '{}'::jsonb, 'asset_fixed', false, null, 20),
  ('NG', 'default', '0011', 'Goodwill — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 30),
  ('NG', 'default', '0020', 'Development costs', '{}'::jsonb, 'asset_fixed', false, null, 40),
  ('NG', 'default', '0021', 'Development costs — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 50),
  ('NG', 'default', '0030', 'Patents, trademarks and licences', '{}'::jsonb, 'asset_fixed', false, null, 60),
  ('NG', 'default', '0031', 'Patents, trademarks and licences — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 70),
  ('NG', 'default', '0040', 'Other intangible assets', '{}'::jsonb, 'asset_fixed', false, null, 80),
  ('NG', 'default', '0041', 'Other intangible assets — accumulated amortisation', '{}'::jsonb, 'asset_fixed', false, null, 90),
  ('NG', 'default', '0100', 'Freehold land and buildings', '{}'::jsonb, 'asset_fixed', false, null, 100),
  ('NG', 'default', '0101', 'Freehold land and buildings — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 110),
  ('NG', 'default', '0110', 'Leasehold property and improvements', '{}'::jsonb, 'asset_fixed', false, null, 120),
  ('NG', 'default', '0111', 'Leasehold property and improvements — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 130),
  ('NG', 'default', '0120', 'Plant and machinery', '{}'::jsonb, 'asset_fixed', false, null, 140),
  ('NG', 'default', '0121', 'Plant and machinery — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 150),
  ('NG', 'default', '0130', 'Fixtures and fittings', '{}'::jsonb, 'asset_fixed', false, null, 160),
  ('NG', 'default', '0131', 'Fixtures and fittings — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 170),
  ('NG', 'default', '0140', 'Office equipment', '{}'::jsonb, 'asset_fixed', false, null, 180),
  ('NG', 'default', '0141', 'Office equipment — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 190),
  ('NG', 'default', '0150', 'Computer equipment', '{}'::jsonb, 'asset_fixed', false, null, 200),
  ('NG', 'default', '0151', 'Computer equipment — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 210),
  ('NG', 'default', '0160', 'Motor vehicles', '{}'::jsonb, 'asset_fixed', false, null, 220),
  ('NG', 'default', '0161', 'Motor vehicles — accumulated depreciation', '{}'::jsonb, 'asset_fixed', false, null, 230),
  ('NG', 'default', '0170', 'Construction-in-progress', '{}'::jsonb, 'asset_fixed', false, null, 240),
  ('NG', 'default', '0200', 'Shares in group undertakings and participating interests', '{}'::jsonb, 'asset_non_current', false, null, 250),
  ('NG', 'default', '0210', 'Loans to group undertakings and participating interests', '{}'::jsonb, 'asset_non_current', false, null, 260),
  ('NG', 'default', '0220', 'Other investments other than loans', '{}'::jsonb, 'asset_non_current', false, null, 270),
  ('NG', 'default', '0230', 'Other long-term investments', '{}'::jsonb, 'asset_non_current', false, null, 280),
  ('NG', 'default', '1000', 'Stock — raw materials and consumables', '{}'::jsonb, 'asset_current', false, null, 290),
  ('NG', 'default', '1010', 'Stock — work in progress', '{}'::jsonb, 'asset_current', false, null, 300),
  ('NG', 'default', '1020', 'Stock — finished goods and goods for resale', '{}'::jsonb, 'asset_current', false, null, 310),
  ('NG', 'default', '1030', 'Payments on account — stocks in transit', '{}'::jsonb, 'asset_prepayments', false, null, 320),
  ('NG', 'default', '1100', 'Trade debtors', '{}'::jsonb, 'asset_receivable', true, null, 330),
  ('NG', 'default', '1105', 'Provision for doubtful debts', '{}'::jsonb, 'asset_current', false, null, 340),
  ('NG', 'default', '1110', 'Amounts owed by group and related companies', '{}'::jsonb, 'asset_current', false, null, 350),
  ('NG', 'default', '1120', 'Other debtors', '{}'::jsonb, 'asset_current', false, null, 360),
  ('NG', 'default', '1130', 'Directors'' current account — debit', '{}'::jsonb, 'asset_current', false, null, 370),
  ('NG', 'default', '1140', 'VAT recoverable — input tax', '{}'::jsonb, 'asset_current', false, null, 380),
  ('NG', 'default', '1145', 'VAT paid at Customs on imports — recoverable', '{}'::jsonb, 'asset_current', false, null, 390),
  ('NG', 'default', '1150', 'Withholding tax credit notes receivable', '{}'::jsonb, 'asset_current', false, null, 400),
  ('NG', 'default', '1155', 'VAT refundable from the Service — net credit of a filed return', '{}'::jsonb, 'asset_current', true, null, 410),
  ('NG', 'default', '1160', 'Companies Income Tax recoverable', '{}'::jsonb, 'asset_current', false, null, 420),
  ('NG', 'default', '1165', 'Development Levy recoverable', '{}'::jsonb, 'asset_current', false, null, 430),
  ('NG', 'default', '1170', 'Employee advances and expense claims', '{}'::jsonb, 'asset_current', false, null, 440),
  ('NG', 'default', '1200', 'Shares in group undertakings — held as a current asset', '{}'::jsonb, 'asset_current', false, null, 450),
  ('NG', 'default', '1210', 'Other investments — held as a current asset', '{}'::jsonb, 'asset_current', false, null, 460),
  ('NG', 'default', '1300', 'Bank current account', '{}'::jsonb, 'asset_cash', false, null, 470),
  ('NG', 'default', '1310', 'Bank deposit account', '{}'::jsonb, 'asset_cash', false, null, 480),
  ('NG', 'default', '1320', 'Bank account in a foreign currency', '{}'::jsonb, 'asset_cash', false, null, 490),
  ('NG', 'default', '1330', 'Petty cash', '{}'::jsonb, 'asset_cash', false, null, 500),
  ('NG', 'default', '1340', 'Cash in transit', '{}'::jsonb, 'asset_cash', false, null, 510),
  ('NG', 'default', '1350', 'Card and mobile-money settlement account', '{}'::jsonb, 'asset_cash', false, null, 520),
  ('NG', 'default', '1400', 'Prepayments', '{}'::jsonb, 'asset_prepayments', false, null, 530),
  ('NG', 'default', '1410', 'Accrued income', '{}'::jsonb, 'asset_prepayments', false, null, 540),
  ('NG', 'default', '1420', 'Payments on account to suppliers', '{}'::jsonb, 'asset_prepayments', false, null, 550),
  ('NG', 'default', '2000', 'Bank loans — due within one year', '{}'::jsonb, 'liability_current', false, null, 560),
  ('NG', 'default', '2010', 'Bank overdraft', '{}'::jsonb, 'liability_current', false, null, 570),
  ('NG', 'default', '2020', 'Credit card account', '{}'::jsonb, 'liability_credit_card', false, null, 580),
  ('NG', 'default', '2100', 'Trade creditors', '{}'::jsonb, 'liability_payable', true, null, 590),
  ('NG', 'default', '2110', 'Amounts owed to group and related companies', '{}'::jsonb, 'liability_current', false, null, 600),
  ('NG', 'default', '2150', 'Nigeria Customs Service — import VAT payable', '{}'::jsonb, 'liability_current', false, null, 610),
  ('NG', 'default', '2200', 'VAT payable — output tax', '{}'::jsonb, 'liability_current', false, null, 620),
  ('NG', 'default', '2210', 'VAT payable to the Service — net due on a filed return', '{}'::jsonb, 'liability_current', true, null, 630),
  ('NG', 'default', '2220', 'Pay As You Earn payable', '{}'::jsonb, 'liability_current', false, null, 640),
  ('NG', 'default', '2230', 'Pension Reform Act contributions payable', '{}'::jsonb, 'liability_current', false, null, 650),
  ('NG', 'default', '2240', 'National Housing Fund contributions payable', '{}'::jsonb, 'liability_current', false, null, 660),
  ('NG', 'default', '2250', 'Nigeria Social Insurance Trust Fund contributions payable', '{}'::jsonb, 'liability_current', false, null, 670),
  ('NG', 'default', '2260', 'Industrial Training Fund levy payable', '{}'::jsonb, 'liability_current', false, null, 680),
  ('NG', 'default', '2270', 'Withholding tax payable — deducted from suppliers and contractors', '{}'::jsonb, 'liability_current', false, null, 690),
  ('NG', 'default', '2280', 'Net wages payable', '{}'::jsonb, 'liability_current', false, null, 700),
  ('NG', 'default', '2290', 'Directors'' current account — credit', '{}'::jsonb, 'liability_current', false, null, 710),
  ('NG', 'default', '2300', 'Dividends payable', '{}'::jsonb, 'liability_current', false, null, 720),
  ('NG', 'default', '2310', 'Companies Income Tax payable', '{}'::jsonb, 'liability_current', false, null, 730),
  ('NG', 'default', '2320', 'Development Levy payable', '{}'::jsonb, 'liability_current', false, null, 740),
  ('NG', 'default', '2330', 'Fossil fuel surcharge payable', '{}'::jsonb, 'liability_current', false, null, 750),
  ('NG', 'default', '2340', 'Other creditors', '{}'::jsonb, 'liability_current', false, null, 760),
  ('NG', 'default', '2400', 'Obligations under finance leases and hire purchase — due within one year', '{}'::jsonb, 'liability_current', false, null, 770),
  ('NG', 'default', '2900', 'Suspense account', '{}'::jsonb, 'liability_current', false, null, 780),
  ('NG', 'default', '3000', 'Bank loans — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 790),
  ('NG', 'default', '3010', 'Other loans — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 800),
  ('NG', 'default', '3020', 'Trade creditors — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 810),
  ('NG', 'default', '3030', 'Amounts owed to group and related companies — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 820),
  ('NG', 'default', '3040', 'Obligations under finance leases and hire purchase — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 830),
  ('NG', 'default', '3050', 'Other creditors — due after more than one year', '{}'::jsonb, 'liability_non_current', false, null, 840),
  ('NG', 'default', '3100', 'Provision for deferred taxation', '{}'::jsonb, 'liability_non_current', false, null, 850),
  ('NG', 'default', '3110', 'Provision for end-of-service and other employee benefits', '{}'::jsonb, 'liability_non_current', false, null, 860),
  ('NG', 'default', '3120', 'Other provisions for liabilities', '{}'::jsonb, 'liability_non_current', false, null, 870),
  ('NG', 'default', '3200', 'Accruals', '{}'::jsonb, 'liability_current', false, null, 880),
  ('NG', 'default', '3210', 'Deferred income', '{}'::jsonb, 'liability_current', false, null, 890),
  ('NG', 'default', '3300', 'Called up share capital', '{}'::jsonb, 'equity', false, null, 900),
  ('NG', 'default', '3310', 'Share premium account', '{}'::jsonb, 'equity', false, null, 910),
  ('NG', 'default', '3320', 'Revaluation reserve', '{}'::jsonb, 'equity', false, null, 920),
  ('NG', 'default', '3330', 'Capital redemption reserve', '{}'::jsonb, 'equity', false, null, 930),
  ('NG', 'default', '3340', 'Statutory reserve', '{}'::jsonb, 'equity', false, null, 940),
  ('NG', 'default', '3350', 'Other reserves', '{}'::jsonb, 'equity', false, null, 950),
  ('NG', 'default', '3400', 'Retained earnings', '{}'::jsonb, 'equity_retained', false, null, 960),
  ('NG', 'default', '3410', 'Dividends paid', '{}'::jsonb, 'equity_retained', false, null, 970),
  ('NG', 'default', '4000', 'Sales — goods', '{}'::jsonb, 'income', false, null, 980),
  ('NG', 'default', '4010', 'Sales — services', '{}'::jsonb, 'income', false, null, 990),
  ('NG', 'default', '4020', 'Sales — zero-rated goods and services', '{}'::jsonb, 'income', false, null, 1000),
  ('NG', 'default', '4030', 'Sales — exempt supplies', '{}'::jsonb, 'income', false, null, 1010),
  ('NG', 'default', '4040', 'Sales — exports', '{}'::jsonb, 'income', false, null, 1020),
  ('NG', 'default', '4100', 'Sales returns and allowances', '{}'::jsonb, 'income', false, null, 1030),
  ('NG', 'default', '4110', 'Discounts allowed', '{}'::jsonb, 'income', false, null, 1040),
  ('NG', 'default', '4200', 'Other operating income', '{}'::jsonb, 'income_other', false, null, 1050),
  ('NG', 'default', '4210', 'Rental income', '{}'::jsonb, 'income_other', false, null, 1060),
  ('NG', 'default', '4220', 'Grants and donor-funded project income', '{}'::jsonb, 'income_other', false, null, 1070),
  ('NG', 'default', '4230', 'Profit on disposal of fixed assets', '{}'::jsonb, 'income_other', false, null, 1080),
  ('NG', 'default', '4240', 'Foreign exchange gains', '{}'::jsonb, 'income_other', false, null, 1090),
  ('NG', 'default', '4300', 'Income from shares in group undertakings', '{}'::jsonb, 'income_other', false, null, 1100),
  ('NG', 'default', '4310', 'Income from other fixed asset investments', '{}'::jsonb, 'income_other', false, null, 1110),
  ('NG', 'default', '4320', 'Other interest receivable and similar income', '{}'::jsonb, 'income_other', false, null, 1120),
  ('NG', 'default', '5000', 'Purchases — goods for resale', '{}'::jsonb, 'expense_direct_cost', false, null, 1130),
  ('NG', 'default', '5010', 'Purchases — raw materials and consumables', '{}'::jsonb, 'expense_direct_cost', false, null, 1140),
  ('NG', 'default', '5020', 'Carriage inwards', '{}'::jsonb, 'expense_direct_cost', false, null, 1150),
  ('NG', 'default', '5030', 'Import duty and clearing charges', '{}'::jsonb, 'expense_direct_cost', false, null, 1160),
  ('NG', 'default', '5040', 'Purchase returns and allowances', '{}'::jsonb, 'expense_direct_cost', false, null, 1170),
  ('NG', 'default', '5050', 'Discounts received', '{}'::jsonb, 'expense_direct_cost', false, null, 1180),
  ('NG', 'default', '5100', 'Opening stock', '{}'::jsonb, 'expense_direct_cost', false, null, 1190),
  ('NG', 'default', '5110', 'Closing stock', '{}'::jsonb, 'expense_direct_cost', false, null, 1200),
  ('NG', 'default', '5200', 'Subcontractor costs', '{}'::jsonb, 'expense_direct_cost', false, null, 1210),
  ('NG', 'default', '5210', 'Direct labour', '{}'::jsonb, 'expense_direct_cost', false, null, 1220),
  ('NG', 'default', '5220', 'Direct expenses — plant and equipment hire', '{}'::jsonb, 'expense_direct_cost', false, null, 1230),
  ('NG', 'default', '5230', 'Direct expenses — materials', '{}'::jsonb, 'expense_direct_cost', false, null, 1240),
  ('NG', 'default', '6000', 'Advertising and marketing', '{}'::jsonb, 'expense', false, null, 1250),
  ('NG', 'default', '6010', 'Website and online advertising', '{}'::jsonb, 'expense', false, null, 1260),
  ('NG', 'default', '6100', 'Carriage outwards', '{}'::jsonb, 'expense', false, null, 1270),
  ('NG', 'default', '6110', 'Packaging', '{}'::jsonb, 'expense', false, null, 1280),
  ('NG', 'default', '6200', 'Distribution staff — wages and salaries', '{}'::jsonb, 'expense', false, null, 1290),
  ('NG', 'default', '6210', 'Distribution staff — employer''s pension contributions', '{}'::jsonb, 'expense', false, null, 1300),
  ('NG', 'default', '6230', 'Sales commission', '{}'::jsonb, 'expense', false, null, 1310),
  ('NG', 'default', '6300', 'Delivery vehicle running costs', '{}'::jsonb, 'expense', false, null, 1320),
  ('NG', 'default', '6310', 'Travelling — distribution', '{}'::jsonb, 'expense', false, null, 1330),
  ('NG', 'default', '6400', 'Warehouse rent and rates', '{}'::jsonb, 'expense', false, null, 1340),
  ('NG', 'default', '6410', 'Warehouse light, heat and water', '{}'::jsonb, 'expense', false, null, 1350),
  ('NG', 'default', '6420', 'Warehouse insurance', '{}'::jsonb, 'expense', false, null, 1360),
  ('NG', 'default', '6500', 'Depreciation — distribution assets', '{}'::jsonb, 'expense_depreciation', false, null, 1370),
  ('NG', 'default', '7000', 'Directors'' remuneration', '{}'::jsonb, 'expense', false, null, 1380),
  ('NG', 'default', '7010', 'Wages and salaries', '{}'::jsonb, 'expense', false, null, 1390),
  ('NG', 'default', '7020', 'Employer''s pension contributions', '{}'::jsonb, 'expense', false, null, 1400),
  ('NG', 'default', '7030', 'National Housing Fund contributions', '{}'::jsonb, 'expense', false, null, 1410),
  ('NG', 'default', '7040', 'Nigeria Social Insurance Trust Fund contributions', '{}'::jsonb, 'expense', false, null, 1420),
  ('NG', 'default', '7050', 'Industrial Training Fund levy', '{}'::jsonb, 'expense', false, null, 1430),
  ('NG', 'default', '7060', 'Staff training', '{}'::jsonb, 'expense', false, null, 1440),
  ('NG', 'default', '7070', 'Staff welfare', '{}'::jsonb, 'expense', false, null, 1450),
  ('NG', 'default', '7080', 'Recruitment costs', '{}'::jsonb, 'expense', false, null, 1460),
  ('NG', 'default', '7090', 'Temporary and agency staff', '{}'::jsonb, 'expense', false, null, 1470),
  ('NG', 'default', '7100', 'Rent and rates', '{}'::jsonb, 'expense', false, null, 1480),
  ('NG', 'default', '7110', 'Light and heat', '{}'::jsonb, 'expense', false, null, 1490),
  ('NG', 'default', '7120', 'Water rates', '{}'::jsonb, 'expense', false, null, 1500),
  ('NG', 'default', '7130', 'Insurance', '{}'::jsonb, 'expense', false, null, 1510),
  ('NG', 'default', '7140', 'Repairs and maintenance', '{}'::jsonb, 'expense', false, null, 1520),
  ('NG', 'default', '7150', 'Cleaning', '{}'::jsonb, 'expense', false, null, 1530),
  ('NG', 'default', '7160', 'Security', '{}'::jsonb, 'expense', false, null, 1540),
  ('NG', 'default', '7200', 'Telephone and internet', '{}'::jsonb, 'expense', false, null, 1550),
  ('NG', 'default', '7210', 'Postage and courier', '{}'::jsonb, 'expense', false, null, 1560),
  ('NG', 'default', '7220', 'Printing and stationery', '{}'::jsonb, 'expense', false, null, 1570),
  ('NG', 'default', '7230', 'Software and subscriptions', '{}'::jsonb, 'expense', false, null, 1580),
  ('NG', 'default', '7240', 'Computer and IT costs', '{}'::jsonb, 'expense', false, null, 1590),
  ('NG', 'default', '7250', 'Equipment hire', '{}'::jsonb, 'expense', false, null, 1600),
  ('NG', 'default', '7260', 'Generator fuel and diesel', '{}'::jsonb, 'expense', false, null, 1610),
  ('NG', 'default', '7270', 'Sundry expenses', '{}'::jsonb, 'expense', false, null, 1620),
  ('NG', 'default', '7300', 'Motor vehicle running costs', '{}'::jsonb, 'expense', false, null, 1630),
  ('NG', 'default', '7310', 'Motor vehicle leasing and hire', '{}'::jsonb, 'expense', false, null, 1640),
  ('NG', 'default', '7320', 'Travel and subsistence', '{}'::jsonb, 'expense', false, null, 1650),
  ('NG', 'default', '7330', 'Business entertainment', '{}'::jsonb, 'expense', false, null, 1660),
  ('NG', 'default', '7400', 'Accountancy fees', '{}'::jsonb, 'expense', false, null, 1670),
  ('NG', 'default', '7410', 'Legal and professional fees', '{}'::jsonb, 'expense', false, null, 1680),
  ('NG', 'default', '7420', 'Consultancy fees', '{}'::jsonb, 'expense', false, null, 1690),
  ('NG', 'default', '7430', 'Audit fee', '{}'::jsonb, 'expense', false, null, 1700),
  ('NG', 'default', '7440', 'Bank charges', '{}'::jsonb, 'expense', false, null, 1710),
  ('NG', 'default', '7450', 'Card and mobile-money processing charges', '{}'::jsonb, 'expense', false, null, 1720),
  ('NG', 'default', '7460', 'Subscriptions to professional bodies', '{}'::jsonb, 'expense', false, null, 1730),
  ('NG', 'default', '7470', 'Charitable donations', '{}'::jsonb, 'expense', false, null, 1740),
  ('NG', 'default', '7500', 'Bad debts written off', '{}'::jsonb, 'expense', false, null, 1750),
  ('NG', 'default', '7510', 'Movement in the provision for doubtful debts', '{}'::jsonb, 'expense', false, null, 1760),
  ('NG', 'default', '7600', 'Depreciation — freehold land and buildings', '{}'::jsonb, 'expense_depreciation', false, null, 1770),
  ('NG', 'default', '7610', 'Depreciation — leasehold property and improvements', '{}'::jsonb, 'expense_depreciation', false, null, 1780),
  ('NG', 'default', '7620', 'Depreciation — plant and machinery', '{}'::jsonb, 'expense_depreciation', false, null, 1790),
  ('NG', 'default', '7630', 'Depreciation — fixtures and fittings', '{}'::jsonb, 'expense_depreciation', false, null, 1800),
  ('NG', 'default', '7640', 'Depreciation — office equipment', '{}'::jsonb, 'expense_depreciation', false, null, 1810),
  ('NG', 'default', '7650', 'Depreciation — computer equipment', '{}'::jsonb, 'expense_depreciation', false, null, 1820),
  ('NG', 'default', '7660', 'Depreciation — motor vehicles', '{}'::jsonb, 'expense_depreciation', false, null, 1830),
  ('NG', 'default', '7670', 'Amortisation of goodwill', '{}'::jsonb, 'expense_depreciation', false, null, 1840),
  ('NG', 'default', '7680', 'Amortisation of other intangible assets', '{}'::jsonb, 'expense_depreciation', false, null, 1850),
  ('NG', 'default', '7690', 'Loss on disposal of fixed assets', '{}'::jsonb, 'expense', false, null, 1860),
  ('NG', 'default', '7700', 'Foreign exchange losses', '{}'::jsonb, 'expense', false, null, 1870),
  ('NG', 'default', '7710', 'Rounding differences', '{}'::jsonb, 'expense', false, null, 1880),
  ('NG', 'default', '7720', 'Withholding tax suffered — irrecoverable', '{}'::jsonb, 'expense', false, null, 1890),
  ('NG', 'default', '7730', 'Fossil fuel surcharge', '{}'::jsonb, 'expense', false, null, 1900),
  ('NG', 'default', '8000', 'Bank interest payable', '{}'::jsonb, 'expense', false, null, 1910),
  ('NG', 'default', '8010', 'Loan interest payable', '{}'::jsonb, 'expense', false, null, 1920),
  ('NG', 'default', '8020', 'Finance lease and hire purchase interest', '{}'::jsonb, 'expense', false, null, 1930),
  ('NG', 'default', '8030', 'Other interest payable and similar expenses', '{}'::jsonb, 'expense', false, null, 1940),
  ('NG', 'default', '8100', 'Amounts written off investments', '{}'::jsonb, 'expense', false, null, 1950),
  ('NG', 'default', '8200', 'Companies Income Tax charge', '{}'::jsonb, 'expense', false, null, 1960),
  ('NG', 'default', '8210', 'Companies Income Tax — adjustment in respect of prior periods', '{}'::jsonb, 'expense', false, null, 1970),
  ('NG', 'default', '8220', 'Deferred taxation charge', '{}'::jsonb, 'expense', false, null, 1980),
  ('NG', 'default', '8230', 'Development Levy charge', '{}'::jsonb, 'expense', false, null, 1990),
  ('NG', 'default', '8300', 'Other taxes not shown under the above items', '{}'::jsonb, 'expense', false, null, 2000)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('NG', 'BNK', 'Bank', '{}'::jsonb, 'bank', 30),
  ('NG', 'CSH', 'Petty cash', '{}'::jsonb, 'cash', 40),
  ('NG', 'GEN', 'General journal', '{}'::jsonb, 'general', 50),
  ('NG', 'OPN', 'Opening balances', '{}'::jsonb, 'opening', 60),
  ('NG', 'PUR', 'Purchases journal', '{}'::jsonb, 'purchase', 20),
  ('NG', 'SAL', 'Sales journal', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('NG', 'NG-P-EX', 'Purchase, exempt', '{}'::jsonb, 'A purchase of a supply section 185 exempts — land, a lease of a building, money or securities, a government licence, and the other items of that section.', 'percent', 0, 'purchase', 'exempt', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 185(1). An exempt purchase carries no input tax at all.', null, null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-P-IMP', 'Purchase, import of goods, VAT paid to the Nigeria Customs Service', '{}'::jsonb, 'Goods imported into Nigeria, VAT on the import value paid to the Nigeria Customs Service before the goods are cleared, the ordinary case.', 'percent', 7.5, 'purchase', 'import', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 149: "the value of imported taxable supply […] shall be the amount which is equal to the price of the taxable supply imported plus (a) taxes, duties and other charges levied either outside or by reason of importation into Nigeria, other than VAT imposed under this Act; and (b) costs by way of commission, packing, transport and insurance up to the port or point of entry." Section 155(3): "an importer of taxable goods shall, before clearing those goods, pay to the Service the VAT on the goods." In practice the Nigeria Customs Service collects the VAT at the border on the Service''s behalf, against the same Single Goods Declaration as customs duty. The tax is owed to Customs and not to the foreign supplier, so the tax lands on 2150 — the account the payment to Customs settles — rather than being added to the amount credited to the supplier''s account, mirroring the same shape packs/sa/taxes.json uses for its own import tax.', null, null, 140, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-P-NR', 'Purchase, supplier is a small business exempt from charging VAT', '{}'::jsonb, 'A purchase from a supplier whose gross turnover does not exceed ₦100,000,000 a year and whose total fixed assets do not exceed ₦250,000,000 — a "small business", not required to register, charge VAT or file returns, unless it has opted out.', 'percent', 0, 'purchase', 'not_subject', date '2026-01-01', null, 'Nigeria Tax Administration Act 2025, s. 22(4): "the provision of subsection (1) of this section [monthly VAT returns] shall not apply to a small business"; s. 22(9) carves companies engaged in petroleum operations back out of the exemption. "Small Business" is defined in s. 202: "a business that earns gross turnover of ₦100,000,000.00 or less per annum with total fixed assets not more than ₦250,000,000.00[,] provided that any business providing professional services shall not be classified as a small business." No tax is charged because the supplier is outside the VAT system for as long as it stays under the threshold and has not opted in under s. 22(5); not reported on any box of the return.', null, null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ntaa-2025', null, null, null, null),
  ('NG', 'NG-P-SR', 'Purchase, standard-rated, input tax deductible', '{}'::jsonb, 'A standard-rated purchase of goods, services or fixed assets used for the purpose of making taxable supplies.', 'percent', 7.5, 'purchase', 'domestic', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 155(4): "Input tax incurred by a registered person on any taxable supply, including services and fixed assets made to such person, may be deducted from the tax payable by the person on its taxable supplies at the end of the tax period in which the supply occurred, but only to the extent that the input tax was incurred for the purpose of consumption, use or supply in the course of making taxable supplies." The proviso to s. 155(4)(a) restricts the deduction, where a purchase serves both taxable and non-taxable supplies, to the proportion relating to the taxable ones — **this pack applies no such apportionment**: the socle has no column for a partly-deductible tax, the gap packs/sa/tax_report.json records for Saudi Arabia''s own proportional-deduction rule. Section 155(4)(b) allows the deduction within five years of the end of the tax period the input tax was incurred in.', null, null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-P-ZR', 'Purchase, zero-rated', '{}'::jsonb, 'A purchase of a supply section 186 rates at zero percent — no tax was charged, and none is deducted because none was paid.', 'percent', 0, 'purchase', 'domestic', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 186. The supplier charges no VAT on a zero-rated supply, so a purchase of one carries no input tax to deduct; it is reported so that the VAT payable of s. 22(3) of the Nigeria Tax Administration Act — "the input tax paid, output tax collected and Value Added Tax payable in respect of all taxable supplies in the preceding month" — is stated against the whole of what was bought and not only against the taxed share of it.', null, null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-S-EX', 'Sale, exempt', '{}'::jsonb, 'A supply section 185 exempts outright — among them oil and gas exports, crude petroleum oil and feed gas, land or a building, money and securities, a government licence, baby products, locally manufactured sanitary towels, pads or tampons, and assistive devices and disability-related products.', 'percent', 0, 'sale', 'exempt', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 185(1): "the following supplies are exempt from the VAT imposed under Chapter Six of this Act — (a) oil and gas exports; (b) crude petroleum oil and feed gas for all processed gas; (c) goods purchased for use in humanitarian donor funded projects […]; (d) baby products; (e) locally manufactured sanitary towels, pads or tampons; (f) military hardware […]; (g) shared passenger road-transport service; (h) purchase, hire, rental or lease of tractors, ploughs and other equipment used for agricultural purposes[;] (i) supplies consumed by an approved entity in the export processing or free trade zones […]; (j) goods or services supplied to a diplomatic mission […]; (k) plays and performances conducted by educational institutions as part of learning; (l) land or building including interest in land or building; (m) money, stakes or securities including interest in money or securities; (n) Government licences; and (o) Assistive devices and disability-related products including hearing aids, wheelchairs, and braille materials." Note that oil and gas exports are exempt and not zero-rated — the exporter charges no VAT and deducts none of its input tax on them, unlike an ordinary export under NG-S-ZR-EXPORT.', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-S-SR', 'Sale, standard-rated, VAT 7.5%', '{}'::jsonb, 'A taxable supply of goods, services or an incorporeal deemed to take place in Nigeria under section 145 of the Nigeria Tax Act, that is neither zero-rated under section 186 nor exempt under section 185.', 'percent', 7.5, 'sale', 'domestic', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 147: "Subject to the provisions of Part IX of this Chapter, VAT shall be charged on the value of all taxable supplies at the rate of 7.5%." Section 148(1)(a) fixes the base: for a money consideration, the value of the supply is the amount which, with the VAT added, equals the consideration — the base is therefore the price net of the tax itself, as this tax''s `base` posting carries it. The rate is unchanged from the Value Added Tax Act as amended by the Finance Act 2019, which raised it from 5% to 7.5% with effect from 1 February 2020; the Nigeria Tax Act re-enacts the same figure and repeals that Act with effect from 1 January 2026 (Nigeria Tax Act 2025, s. 195, Ninth Schedule).', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-S-ZR-DOM', 'Sale, zero-rated, domestic supply of a listed essential good or service', '{}'::jsonb, 'A domestic supply of one of the goods or services section 186 rates at zero percent — basic food items, medical and pharmaceutical products, educational books and materials, fertilisers and other listed agricultural inputs, live cattle, goats, sheep and poultry, electricity generated for or transmitted on the national grid, medical services and equipment, and tuition from nursery to tertiary level.', 'percent', 0, 'sale', 'domestic', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 186(a)–(m) and (q): basic food items (defined at s. 188 as an agriculture- or aquatic-based staple food — cereals, roots, meat, fish, milk, salt and similar, raw or semi-processed), all medical and pharmaceutical products including medicinal herbal products, educational books and materials, fertilisers, locally produced agricultural chemicals, veterinary medicine and animal feeds, live cattle, goats, sheep and poultry, agricultural seeds and seedlings, electricity generated by a GENCO and supplied to the National Grid or the Nigeria Bulk Electricity Trading Company, electricity transmitted by the Transmission Company of Nigeria to a DISCO, medical services, tuition relating to nursery, primary, secondary or tertiary education, and medical equipment. Subject to Eleventh Schedule, paragraph 1 (petroleum products, renewable energy equipment, CNG, LPG and other gaseous hydrocarbons), whose charging and collection the Minister may suspend or start by an order in the Official Gazette — this pack carries no tax code for those items; see packs/ng/README.md.', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null),
  ('NG', 'NG-S-ZR-EXPORT', 'Sale, zero-rated, exported goods, services or incorporeal property', '{}'::jsonb, 'Goods exported from Nigeria (other than oil and gas), and services or incorporeal property exported to a person outside Nigeria.', 'percent', 0, 'sale', 'export', date '2026-01-01', null, 'Nigeria Tax Act 2025, s. 186: "the following taxable supplies are charged to VAT at the rate of zero percent — (n) exported goods excluding oil and gas; (o) exported services; (p) exported incorporeal property." Oil and gas exports are not zero-rated under this paragraph: section 185(1)(a) exempts them instead — see NG-S-EX. `vat_category` is left null: this pack declares no `einvoicing.profile`, so BT-151 is not a term of any invoice this pack''s companies issue, and Nigeria carries no VATEX-style register of its own reason codes this pack''s research could find (packs/packs.md § "What a tax says on the invoice").', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'nta-2025', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('NG-P-EX', 'invoice', 'base', 100, null, '7', array['7']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-P-EX', 'credit_note', 'base', 100, null, '7', array['7']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-P-IMP', 'invoice', 'base', 100, null, '8', array['8']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-P-IMP', 'invoice', 'tax', 100, '1140', '8', array['8']::text[], 100, 'NG-VAT-RETURN', 20),
    ('NG-P-IMP', 'invoice', 'tax', -100, '2150', null, null, 100, null, 30),
    ('NG-P-IMP', 'credit_note', 'base', 100, null, '8', array['8']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-P-IMP', 'credit_note', 'tax', 100, '1140', '8', array['8']::text[], -100, 'NG-VAT-RETURN', 20),
    ('NG-P-IMP', 'credit_note', 'tax', -100, '2150', null, null, 100, null, 30),
    ('NG-P-SR', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-P-SR', 'invoice', 'tax', 100, '1140', '5', array['5']::text[], 100, 'NG-VAT-RETURN', 20),
    ('NG-P-SR', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-P-SR', 'credit_note', 'tax', 100, '1140', '5', array['5']::text[], -100, 'NG-VAT-RETURN', 20),
    ('NG-P-ZR', 'invoice', 'base', 100, null, '6', array['6']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-P-ZR', 'credit_note', 'base', 100, null, '6', array['6']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-S-EX', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-S-EX', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-S-SR', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-S-SR', 'invoice', 'tax', 100, '2200', '1', array['1']::text[], 100, 'NG-VAT-RETURN', 20),
    ('NG-S-SR', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-S-SR', 'credit_note', 'tax', 100, '2200', '1', array['1']::text[], -100, 'NG-VAT-RETURN', 20),
    ('NG-S-ZR-DOM', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-S-ZR-DOM', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'NG-VAT-RETURN', 10),
    ('NG-S-ZR-EXPORT', 'invoice', 'base', 100, null, '2', array['2']::text[], 100, 'NG-VAT-RETURN', 10),
    ('NG-S-ZR-EXPORT', 'credit_note', 'base', 100, null, '2', array['2']::text[], -100, 'NG-VAT-RETURN', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'NG' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('NG', 'NG-VAT-RETURN', 'VAT return', array['month']::declaration_period[], 'month'::declaration_period, date '2026-01-01', null, 'Nigeria Tax Administration Act 2025, s. 22(1): "A taxable person shall, in respect of Value Added Tax (VAT), with or without a notice and whether or not an economic activity has taken place, submit a return to the Service in the prescribed form, on or before the 21st day of the following month"; s. 22(3): "the returns shall contain the input tax paid, output tax collected and Value Added Tax payable in respect of all taxable supplies in the preceding month." A tax period is one calendar month, and no cadence but monthly exists for it — unlike Belgium or Ireland, nothing in the Act lets a taxable person ask for a longer one. **The return is filed on the Service''s own portal, TaxPro-Max, which has accepted no manual VAT return since June 2021** (Federal Inland Revenue Service Information Circular on e-filing, June 2021); the most recent public specimen of a printed form this pack''s research could find is Form VAT 002, whose worked example still carries the 5% rate the Finance Act 2019 superseded and whose figures are stated inclusive of VAT in a way TaxPro-Max''s own sales-schedule upload (net value entered, VAT computed at 7.5%) does not appear to reproduce. Rather than transcribe a paper form''s box numbers as if they were what the portal shows today, this pack numbers its own boxes against the statutory description of s. 22(3) — output tax, input tax, VAT payable — the way packs/sa/tax_report.json numbers a return that is itself a screen and not a printed form. A reviewer who files a real return on TaxPro-Max should check the boxes against what the portal shows.', true,'day_of_month_after_period'::filing_deadline_rule, 21, null, 'Nigeria Tax Administration Act 2025, s. 22(1), quoted above. Section 49(1) sets the same day for payment: "every person shall make payment of tax due on or before the due date of filing", and s. 154(4), for VAT collected, withheld or self-accounted by a government body or an appointed collector, gives the fourteenth day instead — a different obligation on a different person, which this pack does not model (packs/ng/README.md).', 'ntaa-2025', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('NG', 'NG-VAT-RETURN', '1', 'base', 'Standard-rated sales', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 147: taxable supplies at the standard rate of 7.5%, stated net of the tax itself under s. 148(1)(a).', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '1', 'tax', 'Output VAT on standard-rated sales', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Administration Act 2025, s. 22(3): the output tax collected on taxable supplies.', 'ntaa-2025'),
  ('NG', 'NG-VAT-RETURN', '2', 'base', 'Zero-rated sales', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 186: exported goods, services and incorporeal property, and the domestic supplies the section lists — basic food, medical and pharmaceutical products, educational materials, agricultural inputs, electricity supplied to or by the national grid, medical services and equipment, and tuition.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '3', 'base', 'Exempt sales', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 185(1): oil and gas exports, crude petroleum oil and feed gas, land and buildings, money and securities, government licences, and the other items of that section.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '4', 'total', 'Total output tax', '{}'::jsonb, 50, null, array['1:tax']::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Administration Act 2025, s. 22(3), the "output tax collected" component of the return.', 'ntaa-2025'),
  ('NG', 'NG-VAT-RETURN', '5', 'base', 'Standard-rated domestic purchases', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 155(4): input tax deductible on a taxable supply, including services and fixed assets, to the extent used in making taxable supplies.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '5', 'tax', 'Deductible input VAT on standard-rated domestic purchases', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 155(4), the deductible input tax of a standard-rated domestic purchase.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '6', 'base', 'Zero-rated purchases', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'A purchase of a supply section 186 rates at zero percent, carrying no input tax to deduct.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '7', 'base', 'Exempt purchases', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'A purchase of a supply section 185 exempts, carrying no VAT at all.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '8', 'base', 'Imports of goods', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 149: the value of an imported taxable supply, plus non-VAT duties and charges and the costs of getting it to the port or point of entry.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '8', 'tax', 'VAT paid to the Nigeria Customs Service on import, deductible', '{}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 155(3): an importer pays the VAT on taxable goods to the Service, in practice through the Nigeria Customs Service, before clearing them; the tax is then deductible under s. 155(4) like any other input tax.', 'nta-2025'),
  ('NG', 'NG-VAT-RETURN', '9', 'total', 'Total input tax deductible', '{}'::jsonb, 120, null, array['5:tax', '8:tax']::text[], '{}'::text[], null, null, false, false, null, 'Nigeria Tax Administration Act 2025, s. 22(3), the "input tax paid" component of the return.', 'ntaa-2025'),
  ('NG', 'NG-VAT-RETURN', '10', 'total', 'VAT payable, or refundable', '{}'::jsonb, 130, null, array['4']::text[], array['9']::text[], null, null, false, false, null, 'Nigeria Tax Act 2025, s. 155(1): where output VAT exceeds input VAT the excess is remitted to the Service; where input VAT exceeds output VAT the taxable person carries the excess forward as a credit against subsequent months, or under s. 155(2) may request a refund. This pack applies no floor at zero: a negative figure here is the credit or the refund s. 155 describes.', 'nta-2025')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('NG-CAMA-BS', 'NG', 'default', 'Statement of financial position', 'balance_sheet', 'NG-CAMA', date '2026-01-01', null, 'Companies and Allied Matters Act 2020, s. 377(2)(b) requires "the balance sheet or balance sheet as at the last day of the year" among the financial statements the directors prepare; s. 378(1) requires it to comply with the First Schedule to the Act "so far as applicable" and with the accounting standards the Financial Reporting Council of Nigeria lays down. The lines below follow the First Schedule, Section C, Balance Sheet Formats, Format 1 — a vertical format, headed A to M — summarised to the level of this chart''s own account blocks; each heading below names the paragraph of Format 1 it carries.', 'cama-2020'),
  ('NG-CAMA-IS', 'NG', 'default', 'Statement of profit or loss', 'income_statement', 'NG-CAMA', date '2026-01-01', null, 'Companies and Allied Matters Act 2020, s. 377(2)(c) requires "a profit and loss account […] for the year" among the financial statements the directors prepare; s. 378(1) requires it to comply with the First Schedule to the Act "so far as applicable". The lines below follow the First Schedule, Section C, Profit and Loss Account Formats, Format 1 (the function-of-expense format), summarised to the level of this chart''s own account blocks.', 'cama-2020')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('NG-CAMA-BS', 'A', null, 'Called up share capital not paid', '{}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item A.', 'cama-2020'),
  ('NG-CAMA-BS', 'B.INT', null, 'Intangible fixed assets', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item D — development costs, concessions, patents, licences, trademarks and goodwill, net of accumulated amortisation.', 'cama-2020'),
  ('NG-CAMA-BS', 'B.TAN', null, 'Tangible fixed assets', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item B — land and buildings, plant and machinery, fixtures, fittings, tools and equipment, and construction-in-progress, net of accumulated depreciation.', 'cama-2020'),
  ('NG-CAMA-BS', 'C', null, 'Long-term investments', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item C.', 'cama-2020'),
  ('NG-CAMA-BS', 'FA', null, 'Fixed assets and long-term investments', '{}'::jsonb, 50, 1, true, array['B.INT', 'B.TAN', 'C']::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, items B, C and D combined.', 'cama-2020'),
  ('NG-CAMA-BS', 'E.STK', null, 'Stocks', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item E.I.', 'cama-2020'),
  ('NG-CAMA-BS', 'E.DBT', null, 'Trade and other debtors', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item E.II — trade debtors and other debtors, including amounts recoverable from the Service and from the Nigeria Customs Service.', 'cama-2020'),
  ('NG-CAMA-BS', 'E.INV', null, 'Short-term investments', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item E.III.', 'cama-2020'),
  ('NG-CAMA-BS', 'E.CSH', null, 'Cash at bank and in hand', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item E.IV.', 'cama-2020'),
  ('NG-CAMA-BS', 'F', null, 'Prepayments and accrued income', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item F.', 'cama-2020'),
  ('NG-CAMA-BS', 'CA', null, 'Current assets', '{}'::jsonb, 110, 1, true, array['E.STK', 'E.DBT', 'E.INV', 'E.CSH', 'F']::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item E plus item F.', 'cama-2020'),
  ('NG-CAMA-BS', 'G', null, 'Creditors: amounts falling due within one year', '{}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item G.', 'cama-2020'),
  ('NG-CAMA-BS', 'H', null, 'Net current assets (liabilities)', '{}'::jsonb, 130, 1, true, array['CA']::text[], array['G']::text[], null, 'First Schedule, Section C, Format 1, item H.', 'cama-2020'),
  ('NG-CAMA-BS', 'I', null, 'Total assets less current liabilities', '{}'::jsonb, 140, 1, true, array['A', 'FA', 'H']::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item I.', 'cama-2020'),
  ('NG-CAMA-BS', 'J', null, 'Creditors: amounts falling due after more than one year', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item J.', 'cama-2020'),
  ('NG-CAMA-BS', 'K', null, 'Provisions for liabilities and charges', '{}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item K.', 'cama-2020'),
  ('NG-CAMA-BS', 'L', null, 'Accruals and deferred income', '{}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item L.', 'cama-2020'),
  ('NG-CAMA-BS', 'NET', null, 'Net assets', '{}'::jsonb, 180, 1, true, array['I']::text[], array['J', 'K', 'L']::text[], null, 'First Schedule, Section C, Format 1 — item I less items J, K and L.', 'cama-2020'),
  ('NG-CAMA-BS', 'M.SC', null, 'Called up share capital', '{}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item M.1.', 'cama-2020'),
  ('NG-CAMA-BS', 'M.SP', null, 'Share premium account', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item M.2.', 'cama-2020'),
  ('NG-CAMA-BS', 'M.RV', null, 'Revaluation reserve', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item M.3.', 'cama-2020'),
  ('NG-CAMA-BS', 'M.OR', null, 'Other reserves', '{}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item M.4 — capital redemption reserve, statutory reserve and other reserves.', 'cama-2020'),
  ('NG-CAMA-BS', 'M.RE', null, 'Retained earnings', '{}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item M.V — profit and loss account balance carried from the income statement, net of dividends paid.', 'cama-2020'),
  ('NG-CAMA-BS', 'EQUITY', null, 'Capital and reserves', '{}'::jsonb, 240, 1, true, array['M.SC', 'M.SP', 'M.RV', 'M.OR', 'M.RE']::text[], '{}'::text[], null, 'First Schedule, Section C, Format 1, item M.', 'cama-2020'),
  ('NG-CAMA-IS', '1', null, 'Turnover', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 1, net of sales returns, allowances and discounts allowed.', 'cama-2020'),
  ('NG-CAMA-IS', '2', null, 'Cost of sales', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 2.', 'cama-2020'),
  ('NG-CAMA-IS', '3', null, 'Gross profit or loss', '{}'::jsonb, 30, 1, true, array['1']::text[], array['2']::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 3.', 'cama-2020'),
  ('NG-CAMA-IS', '4', null, 'Distribution expenses', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 4.', 'cama-2020'),
  ('NG-CAMA-IS', '5', null, 'Administrative expenses', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 5.', 'cama-2020'),
  ('NG-CAMA-IS', '6', null, 'Other operating income', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 6 — rental income, grants, profit on disposal of fixed assets, foreign exchange gains and income from investments.', 'cama-2020'),
  ('NG-CAMA-IS', '6B', null, 'Other operating expenses', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 11 — bad debts, depreciation and amortisation not carried in cost of sales, loss on disposal of fixed assets, foreign exchange losses, rounding, withholding tax suffered and the fossil fuel surcharge of Nigeria Tax Act 2025, Chapter Seven.', 'cama-2020'),
  ('NG-CAMA-IS', '7', null, 'Operating profit or loss', '{}'::jsonb, 80, 1, true, array['3', '6']::text[], array['4', '5', '6B']::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1 — items 3 and 6 less items 4, 5 and 11.', 'cama-2020'),
  ('NG-CAMA-IS', '12', null, 'Interest payable and similar charges', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 12.', 'cama-2020'),
  ('NG-CAMA-IS', 'PBT', null, 'Profit or loss on ordinary activities before taxation', '{}'::jsonb, 100, 1, true, array['7']::text[], array['12']::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, the figure items 13 and 14 are computed from.', 'cama-2020'),
  ('NG-CAMA-IS', '13', null, 'Tax on profit or loss on ordinary activities', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 13 — Companies Income Tax, deferred taxation and the Development Levy of Nigeria Tax Act 2025, s. 59.', 'cama-2020'),
  ('NG-CAMA-IS', '14', null, 'Profit or loss for the financial year', '{}'::jsonb, 120, 1, true, array['PBT']::text[], array['13']::text[], null, 'First Schedule, Section C, Profit and Loss Account Formats, Format 1, item 14.', 'cama-2020')
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('NG-CAMA-BS', 'A', 10, 'account_code', '0000', null, null, 'any'),
    ('NG-CAMA-BS', 'B.INT', 10, 'code_range', '0010', '0041', null, 'any'),
    ('NG-CAMA-BS', 'B.TAN', 10, 'code_range', '0100', '0170', null, 'any'),
    ('NG-CAMA-BS', 'C', 10, 'code_range', '0200', '0230', null, 'any'),
    ('NG-CAMA-BS', 'E.STK', 10, 'code_range', '1000', '1030', null, 'any'),
    ('NG-CAMA-BS', 'E.DBT', 10, 'code_range', '1100', '1170', null, 'any'),
    ('NG-CAMA-BS', 'E.INV', 10, 'code_range', '1200', '1210', null, 'any'),
    ('NG-CAMA-BS', 'E.CSH', 10, 'code_range', '1300', '1350', null, 'any'),
    ('NG-CAMA-BS', 'F', 10, 'code_range', '1400', '1420', null, 'any'),
    ('NG-CAMA-BS', 'G', 10, 'code_range', '2000', '2900', null, 'any'),
    ('NG-CAMA-BS', 'J', 10, 'code_range', '3000', '3050', null, 'any'),
    ('NG-CAMA-BS', 'K', 10, 'code_range', '3100', '3120', null, 'any'),
    ('NG-CAMA-BS', 'L', 10, 'code_range', '3200', '3210', null, 'any'),
    ('NG-CAMA-BS', 'M.SC', 10, 'account_code', '3300', null, null, 'any'),
    ('NG-CAMA-BS', 'M.SP', 10, 'account_code', '3310', null, null, 'any'),
    ('NG-CAMA-BS', 'M.RV', 10, 'account_code', '3320', null, null, 'any'),
    ('NG-CAMA-BS', 'M.OR', 10, 'code_range', '3330', '3350', null, 'any'),
    ('NG-CAMA-BS', 'M.RE', 10, 'code_range', '3400', '3410', null, 'any'),
    ('NG-CAMA-IS', '1', 10, 'code_range', '4000', '4110', null, 'any'),
    ('NG-CAMA-IS', '2', 10, 'code_range', '5000', '5230', null, 'any'),
    ('NG-CAMA-IS', '4', 10, 'code_range', '6000', '6500', null, 'any'),
    ('NG-CAMA-IS', '5', 10, 'code_range', '7000', '7470', null, 'any'),
    ('NG-CAMA-IS', '6', 10, 'code_range', '4200', '4320', null, 'any'),
    ('NG-CAMA-IS', '6B', 10, 'code_range', '7500', '7730', null, 'any'),
    ('NG-CAMA-IS', '12', 10, 'code_range', '8000', '8100', null, 'any'),
    ('NG-CAMA-IS', '13', 10, 'code_range', '8200', '8300', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('NG', 'Nigeria', '{}'::jsonb, array['en']::text[], 'NGN', '1100', '2100', '2900', '7710', '3400', '4000', '5000', '1300', '1330', 'SAL', 'PUR', 'GEN', 'en', 'retained_earnings', null, null, null, 'OPN', 'half_up', default, '4240', '7700', '4230', '7690', null, null, '2210', '1155', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Nigeria Tax Act 2025, s. 152(1): a taxable person making a taxable supply "shall maintain a sequential invoice numbering" and furnish the purchaser with a VAT invoice. The section asks the numbering to run in sequence and says nothing of a hole in it, which is why `numbering` is `sequential` and not gapless; the pattern in `number_format` is one series a business may choose and not one the Act prints.',
  numbering_source_key          = 'nta-2025',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'earliest_of_delivery_or_payment',
  tax_point_legal_reference     = 'Nigeria Tax Act 2025, s. 146(1): "a taxable supply shall be deemed to take place at the time an invoice or receipt is issued by the supplier, or where goods are delivered or made available for use, or payment is due to or received by the supplier in respect of that supply, whichever occurs first." That is a three-way earliest test — invoice, delivery, payment — and the closed vocabulary of this field has no value naming all three at once. `earliest_of_delivery_or_payment` is the nearest of the five and misses only the case where an invoice is issued ahead of both delivery and payment, which s. 146(1) would still make the tax point; docs/international.md records the same gap this pack found for Saudi Arabia and Vietnam under an equivalent three-way rule.',
  tax_point_source_key          = 'nta-2025',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Electronic invoicing exists in Nigeria and this pack still leaves all four fields above empty, for the reason packs/sa/ and packs/mx/ leave them empty: the FIRS Merchant-Buyer Solution (MBS), live since 1 August 2025, is a clearance platform a seller transmits an invoice to before it reaches the buyer, built to the Service''s own schema and exchanged over the Service''s API — not an EN 16931 profile any brick of packages/formats writes, and not a four-corner network a `party_scheme`/`vat_scheme` pair of ISO 6523 identifiers addresses (Nigeria carries no entry in the Peppol electronic address scheme list). Nigeria Tax Act 2025, s. 152(4), gives the statutory hook: "the Service may direct any taxable person who makes taxable supplies to adopt the use of electronic invoice, provided that it gives a notice of, at least 30 days". Under that hook the Service required every taxable person with an annual turnover of at least ₦5 billion to onboard to the MBS by 1 November 2025 (extended from 1 August 2025), covering business-to-business, business-to-government and business-to-consumer supplies; the pilot ran from November 2024. No instrument this pack''s research could find sets a date for taxpayers below that turnover, so `mandatory_from` would be a date nobody has fixed for most companies a reader installs this pack for. `obligation` is left out for the same reason `packs/sa/pack.json` leaves it out: the schema refuses `mandatory` without `mandatory_from`, and there is no profile to hang either on. docs/international.md carries the rest, including Nigeria Tax Act 2025, s. 157, and Nigeria Tax Administration Act 2025, s. 23, which give the Service a second and wider power to deploy an Electronic Fiscal System for recording and reporting supplies, by regulations this pack''s research found none yet published.',
  einvoice_source_key           = 'mbs-rollout',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = null
 where country = 'NG';
