-- Ekwo OS — Україна: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ua at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build ua`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Податковий кодекс України, № 2755-VI від 02.12.2010, розділ V «Податок на додану вартість» (статті 180-211), редакція станом на дату видання цього пакета (Верховна Рада України (zakon.rada.gov.ua))
--     https://zakon.rada.gov.ua/laws/show/2755-17
--   Наказ Міністерства фінансів України від 28.01.2016 № 21 «Про затвердження форм та Порядку заповнення і подання податкової звітності з податку на додану вартість», у редакції наказу Мінфіну від 09.08.2024 № 400 (Міністерство фінансів України)
--     https://zakon.rada.gov.ua/laws/show/z0159-16
--   Постанова Кабінету Міністрів України від 11.12.2019 № 1165 «Про затвердження порядків з питань зупинення реєстрації податкової накладної/розрахунку коригування в Єдиному реєстрі податкових накладних», у чинній редакції (Кабінет Міністрів України)
--     https://zakon.rada.gov.ua/laws/show/1165-2019-%D0%BF
--   Інструкція про застосування Плану рахунків бухгалтерського обліку активів, капіталу, зобов'язань і господарських операцій підприємств і організацій, затверджена наказом Міністерства фінансів України від 30.11.1999 № 291, у чинній редакції (Міністерство фінансів України)
--     https://zakon.rada.gov.ua/laws/show/z0893-99
--   Національне положення (стандарт) бухгалтерського обліку 1 «Загальні вимоги до фінансової звітності», затверджене наказом Міністерства фінансів України від 07.02.2013 № 73 (додаток 1: форми № 1 «Баланс» і № 2 «Звіт про фінансові результати») (Міністерство фінансів України)
--     https://zakon.rada.gov.ua/laws/show/z0336-13
--   Національне положення (стандарт) бухгалтерського обліку 25 «Спрощена фінансова звітність», затверджене наказом Міністерства фінансів України від 25.02.2000 № 39, у чинній редакції (Міністерство фінансів України)
--     https://zakon.rada.gov.ua/laws/show/z0161-00
--   Електронний кабінет платника податків — вхід та подання звітності з податку на додану вартість (Державна податкова служба України)
--     https://cabinet.tax.gov.ua/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('UA', 'Україна', '0.1.0', date '2026-09-25', '20260917170000', 'community', null, null, '1560b349b49ce12aa7d45a5b8208b31116cf39ae1e651f372dacb0a1b704dd37', '[{"key":"pku","title":"Податковий кодекс України, № 2755-VI від 02.12.2010, розділ V «Податок на додану вартість» (статті 180-211), редакція станом на дату видання цього пакета","publisher":"Верховна Рада України (zakon.rada.gov.ua)","url":"https://zakon.rada.gov.ua/laws/show/2755-17","consulted_on":"2026-09-25","kind":"law"},{"key":"pdv-deklaracija-nakaz-21","title":"Наказ Міністерства фінансів України від 28.01.2016 № 21 «Про затвердження форм та Порядку заповнення і подання податкової звітності з податку на додану вартість», у редакції наказу Мінфіну від 09.08.2024 № 400","publisher":"Міністерство фінансів України","url":"https://zakon.rada.gov.ua/laws/show/z0159-16","consulted_on":"2026-09-25","kind":"form"},{"key":"yerpn-postanova-1165","title":"Постанова Кабінету Міністрів України від 11.12.2019 № 1165 «Про затвердження порядків з питань зупинення реєстрації податкової накладної/розрахунку коригування в Єдиному реєстрі податкових накладних», у чинній редакції","publisher":"Кабінет Міністрів України","url":"https://zakon.rada.gov.ua/laws/show/1165-2019-%D0%BF","consulted_on":"2026-09-25","kind":"regulation"},{"key":"instr-291","title":"Інструкція про застосування Плану рахунків бухгалтерського обліку активів, капіталу, зобов''язань і господарських операцій підприємств і організацій, затверджена наказом Міністерства фінансів України від 30.11.1999 № 291, у чинній редакції","publisher":"Міністерство фінансів України","url":"https://zakon.rada.gov.ua/laws/show/z0893-99","consulted_on":"2026-09-25","kind":"regulation"},{"key":"npsbo-1","title":"Національне положення (стандарт) бухгалтерського обліку 1 «Загальні вимоги до фінансової звітності», затверджене наказом Міністерства фінансів України від 07.02.2013 № 73 (додаток 1: форми № 1 «Баланс» і № 2 «Звіт про фінансові результати»)","publisher":"Міністерство фінансів України","url":"https://zakon.rada.gov.ua/laws/show/z0336-13","consulted_on":"2026-09-25","kind":"regulation"},{"key":"npsbo-25","title":"Національне положення (стандарт) бухгалтерського обліку 25 «Спрощена фінансова звітність», затверджене наказом Міністерства фінансів України від 25.02.2000 № 39, у чинній редакції","publisher":"Міністерство фінансів України","url":"https://zakon.rada.gov.ua/laws/show/z0161-00","consulted_on":"2026-09-25","kind":"regulation"},{"key":"kabinet","title":"Електронний кабінет платника податків — вхід та подання звітності з податку на додану вартість","publisher":"Державна податкова служба України","url":"https://cabinet.tax.gov.ua/","consulted_on":"2026-09-25","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('UA', 'default', 'План рахунків бухгалтерського обліку (наказ Мінфіну № 291)', '{"en":"Chart of accounts (order of the Ministry of Finance No. 291)"}'::jsonb, true, 'companies', array['UA-NPSBO1-BS', 'UA-NPSBO1-IS']::text[], null, 'Наказ Міністерства фінансів України від 30.11.1999 № 291, який затверджує План рахунків та Інструкцію про його застосування, обов''язковий для підприємств, організацій та інших юридичних осіб (крім банків і бюджетних установ) незалежно від форм власності, організаційно-правових форм і видів діяльності. Цей пакет транскрибує рахунки та найуживаніші субрахунки першого порядку; Інструкція № 291 (вступна частина) прямо дозволяє підприємствам вводити субрахунки другого і третього порядків із збереженням кодів (номерів) субрахунків цього Плану рахунків — на цій підставі пакет додає чотиризначні субрахунки 6411-6414 (розмежування нарахованого/вхідного ПДВ і розрахунків з бюджетом) та 6851 (транзитний рахунок сум, що потребують з''ясування); див. README.md.', 'instr-291')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('UA', 'default', '10', 'Основні засоби', '{"en":"Property, plant and equipment"}'::jsonb, 'asset_fixed', false, null, 10),
  ('UA', 'default', '101', 'Земельні ділянки', '{"en":"Land"}'::jsonb, 'asset_fixed', false, '10', 20),
  ('UA', 'default', '103', 'Будинки та споруди', '{"en":"Buildings and structures"}'::jsonb, 'asset_fixed', false, '10', 30),
  ('UA', 'default', '104', 'Машини та обладнання', '{"en":"Machinery and equipment"}'::jsonb, 'asset_fixed', false, '10', 40),
  ('UA', 'default', '105', 'Транспортні засоби', '{"en":"Vehicles"}'::jsonb, 'asset_fixed', false, '10', 50),
  ('UA', 'default', '106', 'Інструменти прилади та інвентар', '{"en":"Tools, fixtures and fittings"}'::jsonb, 'asset_fixed', false, '10', 60),
  ('UA', 'default', '109', 'Інші основні засоби', '{"en":"Other property, plant and equipment"}'::jsonb, 'asset_fixed', false, '10', 70),
  ('UA', 'default', '11', 'Інші необоротні матеріальні активи', '{"en":"Other non-current tangible assets"}'::jsonb, 'asset_fixed', false, null, 80),
  ('UA', 'default', '112', 'Малоцінні необоротні матеріальні активи', '{"en":"Low-value non-current tangible assets"}'::jsonb, 'asset_fixed', false, '11', 90),
  ('UA', 'default', '117', 'Інші необоротні матеріальні активи', '{"en":"Other non-current tangible assets"}'::jsonb, 'asset_fixed', false, '11', 100),
  ('UA', 'default', '12', 'Нематеріальні активи', '{"en":"Intangible assets"}'::jsonb, 'asset_fixed', false, null, 110),
  ('UA', 'default', '121', 'Права користування природними ресурсами', '{"en":"Rights to use natural resources"}'::jsonb, 'asset_fixed', false, '12', 120),
  ('UA', 'default', '122', 'Права користування майном', '{"en":"Rights to use property"}'::jsonb, 'asset_fixed', false, '12', 130),
  ('UA', 'default', '124', 'Права на об''єкти промислової власності', '{"en":"Rights to industrial property"}'::jsonb, 'asset_fixed', false, '12', 140),
  ('UA', 'default', '125', 'Авторське право та суміжні з ним права', '{"en":"Copyright and related rights"}'::jsonb, 'asset_fixed', false, '12', 150),
  ('UA', 'default', '127', 'Інші нематеріальні активи', '{"en":"Other intangible assets"}'::jsonb, 'asset_fixed', false, '12', 160),
  ('UA', 'default', '13', 'Знос (амортизація) необоротних активів', '{"en":"Accumulated depreciation of non-current assets"}'::jsonb, 'asset_fixed', false, null, 170),
  ('UA', 'default', '131', 'Знос основних засобів', '{"en":"Accumulated depreciation of property, plant and equipment"}'::jsonb, 'asset_fixed', false, '13', 180),
  ('UA', 'default', '132', 'Знос інших необоротних матеріальних активів', '{"en":"Accumulated depreciation of other non-current tangible assets"}'::jsonb, 'asset_fixed', false, '13', 190),
  ('UA', 'default', '133', 'Накопичена амортизація нематеріальних активів', '{"en":"Accumulated amortisation of intangible assets"}'::jsonb, 'asset_fixed', false, '13', 200),
  ('UA', 'default', '14', 'Довгострокові фінансові інвестиції', '{"en":"Long-term financial investments"}'::jsonb, 'asset_non_current', false, null, 210),
  ('UA', 'default', '141', 'Інвестиції пов''язаним сторонам за методом обліку участі в капіталі', '{"en":"Investments in related parties, equity method"}'::jsonb, 'asset_non_current', false, '14', 220),
  ('UA', 'default', '143', 'Інвестиції непов''язаним сторонам', '{"en":"Investments in unrelated parties"}'::jsonb, 'asset_non_current', false, '14', 230),
  ('UA', 'default', '15', 'Капітальні інвестиції', '{"en":"Capital investments in progress"}'::jsonb, 'asset_fixed', false, null, 240),
  ('UA', 'default', '151', 'Капітальне будівництво', '{"en":"Construction in progress"}'::jsonb, 'asset_fixed', false, '15', 250),
  ('UA', 'default', '152', 'Придбання (виготовлення) основних засобів', '{"en":"Acquisition of property, plant and equipment"}'::jsonb, 'asset_fixed', false, '15', 260),
  ('UA', 'default', '154', 'Придбання (створення) нематеріальних активів', '{"en":"Acquisition (creation) of intangible assets"}'::jsonb, 'asset_fixed', false, '15', 270),
  ('UA', 'default', '17', 'Відстрочені податкові активи', '{"en":"Deferred tax assets"}'::jsonb, 'asset_non_current', false, null, 280),
  ('UA', 'default', '18', 'Довгострокова дебіторська заборгованість та інші необоротні активи', '{"en":"Long-term receivables and other non-current assets"}'::jsonb, 'asset_non_current', false, null, 290),
  ('UA', 'default', '181', 'Заборгованість за майно передане у фінансову оренду', '{"en":"Receivables on property under finance lease"}'::jsonb, 'asset_non_current', false, '18', 300),
  ('UA', 'default', '184', 'Інші необоротні активи', '{"en":"Other non-current assets"}'::jsonb, 'asset_non_current', false, '18', 310),
  ('UA', 'default', '19', 'Гудвіл', '{"en":"Goodwill"}'::jsonb, 'asset_non_current', false, null, 320),
  ('UA', 'default', '20', 'Виробничі запаси', '{"en":"Raw materials and supplies"}'::jsonb, 'asset_current', false, null, 330),
  ('UA', 'default', '201', 'Сировина й матеріали', '{"en":"Raw materials"}'::jsonb, 'asset_current', false, '20', 340),
  ('UA', 'default', '203', 'Паливо', '{"en":"Fuel"}'::jsonb, 'asset_current', false, '20', 350),
  ('UA', 'default', '207', 'Запасні частини', '{"en":"Spare parts"}'::jsonb, 'asset_current', false, '20', 360),
  ('UA', 'default', '209', 'Інші матеріали', '{"en":"Other materials"}'::jsonb, 'asset_current', false, '20', 370),
  ('UA', 'default', '22', 'Малоцінні та швидкозношувані предмети', '{"en":"Low-value and short-lived items"}'::jsonb, 'asset_current', false, null, 380),
  ('UA', 'default', '23', 'Виробництво', '{"en":"Work in progress"}'::jsonb, 'asset_current', false, null, 390),
  ('UA', 'default', '26', 'Готова продукція', '{"en":"Finished goods"}'::jsonb, 'asset_current', false, null, 400),
  ('UA', 'default', '28', 'Товари', '{"en":"Goods"}'::jsonb, 'asset_current', false, null, 410),
  ('UA', 'default', '281', 'Товари на складі', '{"en":"Goods in warehouse"}'::jsonb, 'asset_current', false, '28', 420),
  ('UA', 'default', '282', 'Товари в торгівлі', '{"en":"Goods in retail trade"}'::jsonb, 'asset_current', false, '28', 430),
  ('UA', 'default', '285', 'Торгова націнка', '{"en":"Trade margin"}'::jsonb, 'asset_current', false, '28', 440),
  ('UA', 'default', '30', 'Готівка', '{"en":"Cash on hand"}'::jsonb, 'asset_cash', false, null, 450),
  ('UA', 'default', '301', 'Готівка в національній валюті', '{"en":"Cash on hand, national currency"}'::jsonb, 'asset_cash', false, '30', 460),
  ('UA', 'default', '302', 'Готівка в іноземній валюті', '{"en":"Cash on hand, foreign currency"}'::jsonb, 'asset_cash', false, '30', 470),
  ('UA', 'default', '31', 'Рахунки в банках', '{"en":"Bank accounts"}'::jsonb, 'asset_cash', false, null, 480),
  ('UA', 'default', '311', 'Поточні рахунки в національній валюті', '{"en":"Current accounts, national currency"}'::jsonb, 'asset_cash', false, '31', 490),
  ('UA', 'default', '312', 'Поточні рахунки в іноземній валюті', '{"en":"Current accounts, foreign currency"}'::jsonb, 'asset_cash', false, '31', 500),
  ('UA', 'default', '315', 'Спеціальні рахунки в національній валюті', '{"en":"Special accounts, national currency (VAT electronic account)"}'::jsonb, 'asset_cash', false, '31', 510),
  ('UA', 'default', '33', 'Інші кошти', '{"en":"Other funds"}'::jsonb, 'asset_current', false, null, 520),
  ('UA', 'default', '331', 'Грошові документи в національній валюті', '{"en":"Cash documents, national currency"}'::jsonb, 'asset_current', false, '33', 530),
  ('UA', 'default', '34', 'Короткострокові векселі одержані', '{"en":"Short-term bills of exchange receivable"}'::jsonb, 'asset_current', false, null, 540),
  ('UA', 'default', '35', 'Поточні фінансові інвестиції', '{"en":"Current financial investments"}'::jsonb, 'asset_current', false, null, 550),
  ('UA', 'default', '36', 'Розрахунки з покупцями та замовниками', '{"en":"Receivables from customers"}'::jsonb, 'asset_receivable', true, null, 560),
  ('UA', 'default', '37', 'Розрахунки з різними дебіторами', '{"en":"Receivables from other debtors"}'::jsonb, 'asset_current', false, null, 570),
  ('UA', 'default', '371', 'Розрахунки за виданими авансами', '{"en":"Advances paid"}'::jsonb, 'asset_current', false, '37', 580),
  ('UA', 'default', '372', 'Розрахунки з підзвітними особами', '{"en":"Advances to employees (accountable persons)"}'::jsonb, 'asset_current', false, '37', 590),
  ('UA', 'default', '373', 'Розрахунки за нарахованими доходами', '{"en":"Accrued income receivable"}'::jsonb, 'asset_current', false, '37', 600),
  ('UA', 'default', '374', 'Розрахунки за претензіями', '{"en":"Claims receivable"}'::jsonb, 'asset_current', false, '37', 610),
  ('UA', 'default', '377', 'Розрахунки з іншими дебіторами', '{"en":"Receivables from other debtors"}'::jsonb, 'asset_current', false, '37', 620),
  ('UA', 'default', '38', 'Резерв сумнівних боргів', '{"en":"Allowance for doubtful debts"}'::jsonb, 'asset_current', false, null, 630),
  ('UA', 'default', '39', 'Витрати майбутніх періодів', '{"en":"Prepaid expenses"}'::jsonb, 'asset_prepayments', false, null, 640),
  ('UA', 'default', '40', 'Зареєстрований (пайовий) капітал', '{"en":"Registered (share) capital"}'::jsonb, 'equity', false, null, 650),
  ('UA', 'default', '401', 'Статутний капітал', '{"en":"Statutory capital"}'::jsonb, 'equity', false, '40', 660),
  ('UA', 'default', '41', 'Капітал у дооцінках', '{"en":"Revaluation capital"}'::jsonb, 'equity', false, null, 670),
  ('UA', 'default', '411', 'Дооцінка (уцінка) основних засобів', '{"en":"Revaluation of property, plant and equipment"}'::jsonb, 'equity', false, '41', 680),
  ('UA', 'default', '42', 'Додатковий капітал', '{"en":"Additional capital"}'::jsonb, 'equity', false, null, 690),
  ('UA', 'default', '421', 'Емісійний дохід', '{"en":"Share premium"}'::jsonb, 'equity', false, '42', 700),
  ('UA', 'default', '423', 'Накопичені курсові різниці', '{"en":"Accumulated translation differences"}'::jsonb, 'equity', false, '42', 710),
  ('UA', 'default', '43', 'Резервний капітал', '{"en":"Reserve capital"}'::jsonb, 'equity', false, null, 720),
  ('UA', 'default', '44', 'Нерозподілені прибутки (непокриті збитки)', '{"en":"Retained earnings (accumulated losses)"}'::jsonb, 'equity_retained', false, null, 730),
  ('UA', 'default', '441', 'Прибуток нерозподілений', '{"en":"Retained profit"}'::jsonb, 'equity_retained', false, '44', 740),
  ('UA', 'default', '442', 'Непокриті збитки', '{"en":"Uncovered losses"}'::jsonb, 'equity_retained', false, '44', 750),
  ('UA', 'default', '45', 'Вилучений капітал', '{"en":"Treasury (withdrawn) capital"}'::jsonb, 'equity', false, null, 760),
  ('UA', 'default', '451', 'Вилучені акції', '{"en":"Treasury shares"}'::jsonb, 'equity', false, '45', 770),
  ('UA', 'default', '46', 'Неоплачений капітал', '{"en":"Unpaid capital"}'::jsonb, 'equity', false, null, 780),
  ('UA', 'default', '47', 'Забезпечення майбутніх витрат і платежів', '{"en":"Provisions for future expenses and payments"}'::jsonb, 'liability_non_current', false, null, 790),
  ('UA', 'default', '471', 'Забезпечення виплат відпусток', '{"en":"Provision for holiday pay"}'::jsonb, 'liability_non_current', false, '47', 800),
  ('UA', 'default', '474', 'Забезпечення інших витрат і платежів', '{"en":"Other provisions"}'::jsonb, 'liability_non_current', false, '47', 810),
  ('UA', 'default', '48', 'Цільове фінансування і цільові надходження', '{"en":"Targeted financing and receipts"}'::jsonb, 'liability_non_current', false, null, 820),
  ('UA', 'default', '50', 'Довгострокові позики', '{"en":"Long-term borrowings"}'::jsonb, 'liability_non_current', false, null, 830),
  ('UA', 'default', '501', 'Довгострокові кредити банків у національній валюті', '{"en":"Long-term bank loans, national currency"}'::jsonb, 'liability_non_current', false, '50', 840),
  ('UA', 'default', '502', 'Довгострокові кредити банків в іноземній валюті', '{"en":"Long-term bank loans, foreign currency"}'::jsonb, 'liability_non_current', false, '50', 850),
  ('UA', 'default', '51', 'Довгострокові векселі видані', '{"en":"Long-term bills of exchange issued"}'::jsonb, 'liability_non_current', false, null, 860),
  ('UA', 'default', '52', 'Довгострокові зобов''язання за облігаціями', '{"en":"Long-term bond liabilities"}'::jsonb, 'liability_non_current', false, null, 870),
  ('UA', 'default', '53', 'Довгострокові зобов''язання з оренди', '{"en":"Long-term lease liabilities"}'::jsonb, 'liability_non_current', false, null, 880),
  ('UA', 'default', '54', 'Відстрочені податкові зобов''язання', '{"en":"Deferred tax liabilities"}'::jsonb, 'liability_non_current', false, null, 890),
  ('UA', 'default', '55', 'Інші довгострокові зобов''язання', '{"en":"Other long-term liabilities"}'::jsonb, 'liability_non_current', false, null, 900),
  ('UA', 'default', '60', 'Короткострокові позики', '{"en":"Short-term borrowings"}'::jsonb, 'liability_current', false, null, 910),
  ('UA', 'default', '601', 'Короткострокові кредити банків у національній валюті', '{"en":"Short-term bank loans, national currency"}'::jsonb, 'liability_current', false, '60', 920),
  ('UA', 'default', '602', 'Короткострокові кредити банків в іноземній валюті', '{"en":"Short-term bank loans, foreign currency"}'::jsonb, 'liability_current', false, '60', 930),
  ('UA', 'default', '61', 'Поточна заборгованість за довгостроковими зобов''язаннями', '{"en":"Current portion of long-term liabilities"}'::jsonb, 'liability_current', false, null, 940),
  ('UA', 'default', '62', 'Короткострокові векселі видані', '{"en":"Short-term bills of exchange issued"}'::jsonb, 'liability_current', false, null, 950),
  ('UA', 'default', '63', 'Розрахунки з постачальниками та підрядниками', '{"en":"Payables to suppliers and contractors"}'::jsonb, 'liability_payable', true, null, 960),
  ('UA', 'default', '64', 'Розрахунки за податками й платежами', '{"en":"Tax and other payments payable"}'::jsonb, 'liability_current', false, null, 970),
  ('UA', 'default', '641', 'Розрахунки за податками', '{"en":"Tax settlements"}'::jsonb, 'liability_current', false, '64', 980),
  ('UA', 'default', '6411', 'Податкові зобов''язання з ПДВ (нараховані)', '{"en":"VAT liability on sales (output VAT, posting account)"}'::jsonb, 'liability_current', false, '641', 990),
  ('UA', 'default', '6412', 'Податковий кредит з ПДВ (вхідний)', '{"en":"VAT credit on purchases (input VAT, posting account)"}'::jsonb, 'asset_current', false, '641', 1000),
  ('UA', 'default', '6413', 'Розрахунки з бюджетом за ПДВ до сплати', '{"en":"VAT settlement with the budget, payable"}'::jsonb, 'liability_current', true, '641', 1010),
  ('UA', 'default', '6414', 'Розрахунки з бюджетом за ПДВ до відшкодування', '{"en":"VAT settlement with the budget, receivable"}'::jsonb, 'asset_current', true, '641', 1020),
  ('UA', 'default', '642', 'Розрахунки за обов''язковими платежами', '{"en":"Other mandatory payments"}'::jsonb, 'liability_current', false, '64', 1030),
  ('UA', 'default', '643', 'Податкові зобов''язання (за передоплатою до першої події)', '{"en":"Tax liability (advance received, before first event)"}'::jsonb, 'liability_current', false, '64', 1040),
  ('UA', 'default', '644', 'Податковий кредит (за передоплатою до першої події)', '{"en":"Tax credit (advance paid, before first event)"}'::jsonb, 'asset_current', false, '64', 1050),
  ('UA', 'default', '65', 'Розрахунки за страхуванням', '{"en":"Payables for insurance"}'::jsonb, 'liability_current', false, null, 1060),
  ('UA', 'default', '651', 'За пенсійним забезпеченням (єдиний соціальний внесок)', '{"en":"Pension contributions (unified social contribution)"}'::jsonb, 'liability_current', false, '65', 1070),
  ('UA', 'default', '652', 'За соціальним страхуванням', '{"en":"Social insurance contributions"}'::jsonb, 'liability_current', false, '65', 1080),
  ('UA', 'default', '66', 'Розрахунки за виплатами працівникам', '{"en":"Payables to employees"}'::jsonb, 'liability_current', false, null, 1090),
  ('UA', 'default', '661', 'Розрахунки за заробітною платою', '{"en":"Payroll payable"}'::jsonb, 'liability_current', false, '66', 1100),
  ('UA', 'default', '662', 'Розрахунки з депонентами', '{"en":"Unclaimed wages (deposited)"}'::jsonb, 'liability_current', false, '66', 1110),
  ('UA', 'default', '67', 'Розрахунки з учасниками', '{"en":"Payables to participants"}'::jsonb, 'liability_current', false, null, 1120),
  ('UA', 'default', '671', 'Розрахунки за нарахованими дивідендами', '{"en":"Dividends payable"}'::jsonb, 'liability_current', false, '67', 1130),
  ('UA', 'default', '68', 'Розрахунки за іншими операціями', '{"en":"Payables for other operations"}'::jsonb, 'liability_current', false, null, 1140),
  ('UA', 'default', '681', 'Розрахунки за авансами одержаними', '{"en":"Advances received"}'::jsonb, 'liability_current', false, '68', 1150),
  ('UA', 'default', '684', 'Розрахунки за нарахованими відсотками', '{"en":"Accrued interest payable"}'::jsonb, 'liability_current', false, '68', 1160),
  ('UA', 'default', '685', 'Розрахунки з іншими кредиторами', '{"en":"Payables to other creditors"}'::jsonb, 'liability_current', false, '68', 1170),
  ('UA', 'default', '6851', 'Розрахунки за сумами що потребують з''ясування (транзитний рахунок)', '{"en":"Suspense account (amounts pending clarification)"}'::jsonb, 'liability_current', false, '685', 1180),
  ('UA', 'default', '69', 'Доходи майбутніх періодів', '{"en":"Deferred income"}'::jsonb, 'liability_current', false, null, 1190),
  ('UA', 'default', '70', 'Доходи від реалізації', '{"en":"Revenue"}'::jsonb, 'income', false, null, 1200),
  ('UA', 'default', '701', 'Дохід від реалізації готової продукції', '{"en":"Revenue from sale of finished goods"}'::jsonb, 'income', false, '70', 1210),
  ('UA', 'default', '702', 'Дохід від реалізації товарів', '{"en":"Revenue from sale of goods"}'::jsonb, 'income', false, '70', 1220),
  ('UA', 'default', '703', 'Дохід від реалізації робіт і послуг', '{"en":"Revenue from work and services"}'::jsonb, 'income', false, '70', 1230),
  ('UA', 'default', '704', 'Вирахування з доходу', '{"en":"Deductions from revenue"}'::jsonb, 'income', false, '70', 1240),
  ('UA', 'default', '71', 'Інший операційний доход', '{"en":"Other operating income"}'::jsonb, 'income_other', false, null, 1250),
  ('UA', 'default', '711', 'Дохід від реалізації іноземної валюти', '{"en":"Income from sale of foreign currency"}'::jsonb, 'income_other', false, '71', 1260),
  ('UA', 'default', '714', 'Дохід від операційної курсової різниці', '{"en":"Income from operating exchange differences"}'::jsonb, 'income_other', false, '71', 1270),
  ('UA', 'default', '715', 'Одержані штрафи пені неустойки', '{"en":"Fines, penalties and forfeits received"}'::jsonb, 'income_other', false, '71', 1280),
  ('UA', 'default', '717', 'Дохід від списання кредиторської заборгованості', '{"en":"Income from write-off of payables"}'::jsonb, 'income_other', false, '71', 1290),
  ('UA', 'default', '719', 'Інші доходи від операційної діяльності', '{"en":"Other operating income"}'::jsonb, 'income_other', false, '71', 1300),
  ('UA', 'default', '73', 'Інші фінансові доходи', '{"en":"Other financial income"}'::jsonb, 'income_other', false, null, 1310),
  ('UA', 'default', '731', 'Дивіденди одержані', '{"en":"Dividends received"}'::jsonb, 'income_other', false, '73', 1320),
  ('UA', 'default', '732', 'Відсотки одержані', '{"en":"Interest received"}'::jsonb, 'income_other', false, '73', 1330),
  ('UA', 'default', '74', 'Інші доходи', '{"en":"Other income"}'::jsonb, 'income_other', false, null, 1340),
  ('UA', 'default', '741', 'Дохід від реалізації фінансових інвестицій', '{"en":"Income from sale of financial investments"}'::jsonb, 'income_other', false, '74', 1350),
  ('UA', 'default', '90', 'Собівартість реалізації', '{"en":"Cost of sales"}'::jsonb, 'expense_direct_cost', false, null, 1400),
  ('UA', 'default', '901', 'Собівартість реалізованої готової продукції', '{"en":"Cost of finished goods sold"}'::jsonb, 'expense_direct_cost', false, '90', 1410),
  ('UA', 'default', '902', 'Собівартість реалізованих товарів', '{"en":"Cost of goods sold"}'::jsonb, 'expense_direct_cost', false, '90', 1420),
  ('UA', 'default', '903', 'Собівартість реалізованих робіт і послуг', '{"en":"Cost of work and services sold"}'::jsonb, 'expense_direct_cost', false, '90', 1430),
  ('UA', 'default', '91', 'Загальновиробничі витрати', '{"en":"Manufacturing overheads"}'::jsonb, 'expense_direct_cost', false, null, 1440),
  ('UA', 'default', '92', 'Адміністративні витрати', '{"en":"Administrative expenses"}'::jsonb, 'expense', false, null, 1450),
  ('UA', 'default', '93', 'Витрати на збут', '{"en":"Selling expenses"}'::jsonb, 'expense', false, null, 1460),
  ('UA', 'default', '94', 'Інші витрати операційної діяльності', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, null, 1470),
  ('UA', 'default', '941', 'Витрати на дослідження і розробки', '{"en":"Research and development expenses"}'::jsonb, 'expense', false, '94', 1480),
  ('UA', 'default', '944', 'Сумнівні та безнадійні борги', '{"en":"Doubtful and bad debt expense"}'::jsonb, 'expense', false, '94', 1490),
  ('UA', 'default', '945', 'Втрати від операційної курсової різниці', '{"en":"Losses on operating exchange differences"}'::jsonb, 'expense', false, '94', 1500),
  ('UA', 'default', '948', 'Визнані штрафи пені неустойки', '{"en":"Fines, penalties and forfeits recognised"}'::jsonb, 'expense', false, '94', 1510),
  ('UA', 'default', '949', 'Інші витрати операційної діяльності', '{"en":"Other operating expenses"}'::jsonb, 'expense', false, '94', 1520),
  ('UA', 'default', '95', 'Фінансові витрати', '{"en":"Financial expenses"}'::jsonb, 'expense', false, null, 1530),
  ('UA', 'default', '951', 'Відсотки за кредит', '{"en":"Interest expense"}'::jsonb, 'expense', false, '95', 1540),
  ('UA', 'default', '97', 'Інші витрати', '{"en":"Other expenses"}'::jsonb, 'expense', false, null, 1550),
  ('UA', 'default', '971', 'Собівартість реалізованих фінансових інвестицій', '{"en":"Cost of financial investments sold"}'::jsonb, 'expense', false, '97', 1560),
  ('UA', 'default', '98', 'Податок на прибуток', '{"en":"Income tax expense"}'::jsonb, 'expense', false, null, 1570)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('UA', 'BNK', 'Банківський журнал', '{"en":"Bank journal"}'::jsonb, 'bank', 30),
  ('UA', 'CSH', 'Касовий журнал', '{"en":"Cash journal"}'::jsonb, 'cash', 40),
  ('UA', 'GEN', 'Загальний журнал', '{"en":"General journal"}'::jsonb, 'general', 50),
  ('UA', 'OPN', 'Журнал відкриття', '{"en":"Opening journal"}'::jsonb, 'opening', 60),
  ('UA', 'PUR', 'Журнал придбання', '{"en":"Purchase journal"}'::jsonb, 'purchase', 20),
  ('UA', 'SAL', 'Журнал продажу', '{"en":"Sales journal"}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('UA', 'UA-P-14', 'ПДВ 14 % — окремі види сільськогосподарської продукції (купівля)', '{"en":"VAT 14% — selected agricultural products (purchase)"}'::jsonb, null, 'percent', 14, 'purchase', 'domestic', date '2022-03-01', null, 'Податковий кодекс України, підпункт «г» пункту 193.1 статті 193 та пункт 198.3 статті 198 — податковий кредит на придбання сільськогосподарської продукції за товарними позиціями 1001, 1003, 1005, 1201, 1205, 1206 00 УКТЗЕД, оподаткованої постачальником за ставкою 14 %.', null, null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-P-20', 'ПДВ 20 % — придбання на митній території (купівля)', '{"en":"VAT 20% — domestic purchase"}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2011-01-01', null, 'Податковий кодекс України, підпункт «а» пункту 193.1 статті 193 та пункт 198.3 статті 198 — податковий кредит звітного періоду складається із сум податку, нарахованих (сплачених) платником за основною ставкою в разі придбання товарів/послуг.', null, null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-P-7', 'ПДВ 7 % — ліки, вироби медичного призначення, готельні та культурні послуги (купівля)', '{"en":"VAT 7% — medicines, hotel and cultural services (purchase)"}'::jsonb, null, 'percent', 7, 'purchase', 'domestic', date '2021-01-01', null, 'Податковий кодекс України, підпункт «в» пункту 193.1 статті 193 та пункт 198.3 статті 198 — податковий кредит на придбання лікарських засобів, медичних виробів або послуг з тимчасового розміщування (готельних послуг), оподаткованих постачальником за ставкою 7 %.', null, null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-S-14', 'ПДВ 14 % — окремі види сільськогосподарської продукції (продаж)', '{"en":"VAT 14% — selected agricultural products (sale)"}'::jsonb, null, 'percent', 14, 'sale', 'domestic', date '2022-03-01', null, 'Податковий кодекс України, підпункт «г» пункту 193.1 статті 193 — ставка 14 відсотків бази оподаткування застосовується до операцій з постачання на митній території України та ввезення на митну територію України сільськогосподарської продукції за товарними позиціями 1001, 1003, 1005, 1201, 1205, 1206 00 згідно з УКТЗЕД. Перелік кодів і період їх застосування уточнювалися наступними змінами до цього підпункту (окремі маркетингові роки); поточну редакцію переліку перевірити з бухгалтером перед застосуванням до конкретної операції.', null, null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-S-20', 'ПДВ 20 % — постачання на митній території (продаж)', '{"en":"VAT 20% — domestic supply (sale)"}'::jsonb, null, 'percent', 20, 'sale', 'domestic', date '2011-01-01', null, 'Податковий кодекс України, підпункт «а» пункту 193.1 статті 193 — основна ставка податку становить 20 відсотків бази оподаткування.', null, null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-S-7', 'ПДВ 7 % — ліки, вироби медичного призначення, готельні та культурні послуги (продаж)', '{"en":"VAT 7% — medicines, hotel and cultural services (sale)"}'::jsonb, null, 'percent', 7, 'sale', 'domestic', date '2021-01-01', null, 'Податковий кодекс України, підпункт «в» пункту 193.1 статті 193 — ставка 7 відсотків застосовується до постачання зареєстрованих в Україні лікарських засобів і медичних виробів (з 1 квітня 2014 року), а з 1 січня 2021 року — до послуг з тимчасового розміщування, що надаються готелями і подібними засобами тимчасового розміщування (пункт 74 підрозділу 2 розділу XX ПКУ, надалі — на постійній основі), та до послуг у сфері культури і мистецтва за переліком, затвердженим Кабінетом Міністрів України. Цей пакет транскрибує ставку одним кодом для трьох категорій; дата, з якої кожна конкретна категорія (ліки, готелі, культура) підпадає під 7 %, різна — перевірити з бухгалтером для операції поза готельним сектором.', null, null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-S-EXEMPT-EDU', 'Звільнено від ПДВ — освітні послуги (продаж)', '{"en":"VAT exempt — education services (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2011-01-01', null, 'Податковий кодекс України, підпункт 197.1.2 пункту 197.1 статті 197 — звільняються від оподаткування операції з постачання послуг з вищої, середньої, професійно-технічної та дошкільної освіти закладами освіти, які мають ліцензію на надання таких послуг.', null, null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null),
  ('UA', 'UA-S-EXPORT', 'ПДВ 0 % — експорт товарів (продаж)', '{"en":"VAT 0% — export of goods (sale)"}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2011-01-01', null, 'Податковий кодекс України, підпункт 195.1.1 пункту 195.1 статті 195 — нульова ставка застосовується до операцій з вивезення товарів за межі митної території України у митному режимі експорту.', null, null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'pku', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('UA-P-14', 'invoice', 'base', 100, null, '103', array['103']::text[], 100, 'UA-PDV', 10),
    ('UA-P-14', 'invoice', 'tax', 100, '6412', '103', array['103']::text[], 100, 'UA-PDV', 20),
    ('UA-P-14', 'credit_note', 'base', 100, null, '103', array['103']::text[], -100, 'UA-PDV', 10),
    ('UA-P-14', 'credit_note', 'tax', 100, '6412', '103', array['103']::text[], -100, 'UA-PDV', 20),
    ('UA-P-20', 'invoice', 'base', 100, null, '101', array['101']::text[], 100, 'UA-PDV', 10),
    ('UA-P-20', 'invoice', 'tax', 100, '6412', '101', array['101']::text[], 100, 'UA-PDV', 20),
    ('UA-P-20', 'credit_note', 'base', 100, null, '101', array['101']::text[], -100, 'UA-PDV', 10),
    ('UA-P-20', 'credit_note', 'tax', 100, '6412', '101', array['101']::text[], -100, 'UA-PDV', 20),
    ('UA-P-7', 'invoice', 'base', 100, null, '102', array['102']::text[], 100, 'UA-PDV', 10),
    ('UA-P-7', 'invoice', 'tax', 100, '6412', '102', array['102']::text[], 100, 'UA-PDV', 20),
    ('UA-P-7', 'credit_note', 'base', 100, null, '102', array['102']::text[], -100, 'UA-PDV', 10),
    ('UA-P-7', 'credit_note', 'tax', 100, '6412', '102', array['102']::text[], -100, 'UA-PDV', 20),
    ('UA-S-14', 'invoice', 'base', 100, null, '13', array['13']::text[], 100, 'UA-PDV', 10),
    ('UA-S-14', 'invoice', 'tax', 100, '6411', '13', array['13']::text[], 100, 'UA-PDV', 20),
    ('UA-S-14', 'credit_note', 'base', 100, null, '13', array['13']::text[], -100, 'UA-PDV', 10),
    ('UA-S-14', 'credit_note', 'tax', 100, '6411', '13', array['13']::text[], -100, 'UA-PDV', 20),
    ('UA-S-20', 'invoice', 'base', 100, null, '11', array['11']::text[], 100, 'UA-PDV', 10),
    ('UA-S-20', 'invoice', 'tax', 100, '6411', '11', array['11']::text[], 100, 'UA-PDV', 20),
    ('UA-S-20', 'credit_note', 'base', 100, null, '11', array['11']::text[], -100, 'UA-PDV', 10),
    ('UA-S-20', 'credit_note', 'tax', 100, '6411', '11', array['11']::text[], -100, 'UA-PDV', 20),
    ('UA-S-7', 'invoice', 'base', 100, null, '12', array['12']::text[], 100, 'UA-PDV', 10),
    ('UA-S-7', 'invoice', 'tax', 100, '6411', '12', array['12']::text[], 100, 'UA-PDV', 20),
    ('UA-S-7', 'credit_note', 'base', 100, null, '12', array['12']::text[], -100, 'UA-PDV', 10),
    ('UA-S-7', 'credit_note', 'tax', 100, '6411', '12', array['12']::text[], -100, 'UA-PDV', 20),
    ('UA-S-EXEMPT-EDU', 'invoice', 'base', 100, null, '5', array['5']::text[], 100, 'UA-PDV', 10),
    ('UA-S-EXEMPT-EDU', 'credit_note', 'base', 100, null, '5', array['5']::text[], -100, 'UA-PDV', 10),
    ('UA-S-EXPORT', 'invoice', 'base', 100, null, '21', array['21']::text[], 100, 'UA-PDV', 10),
    ('UA-S-EXPORT', 'credit_note', 'base', 100, null, '21', array['21']::text[], -100, 'UA-PDV', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'UA' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format,
   rounding_unit, rounding_reference, rounding_source_key)
values
  ('UA', 'UA-PDV', 'Податкова декларація з податку на додану вартість', array['month']::declaration_period[], 'month'::declaration_period, date '2026-01-01', null, 'Наказ Міністерства фінансів України від 28.01.2016 № 21, у редакції наказу від 09.08.2024 № 400 — форма податкової декларації з податку на додану вартість та Порядок її заповнення і подання. Податковий кодекс України, пункт 202.1 статті 202 — базовий звітний (податковий) період для цієї декларації дорівнює календарному місяцю для кожного платника (квартальний період, який раніше пункт 202.2 надавав платникам єдиного податку групи 3, скасовано Законом України від 28.12.2014 № 71-VIII з 1 січня 2016 року). Цей пакет транскрибує лише рядки, які постачання його власних податків досягають: основну ставку та ставки 7 % і 14 % (рядок 1), нульову ставку на експорт (рядок 2), операції, звільнені від оподаткування та/або що не є об''єктом оподаткування (рядок 5), придбання з правом на податковий кредит за тими самими ставками (рядок 10) та підсумкові рядки 9, 17, 18, 19. Рядки коригувань (7, 8, 14, 15, 16), придбання без права на кредит або без ПДВ (10.4), імпорт (рядки 11-12), послуги від нерезидента (рядки 6, 13) та розподіл/перенесення від''ємного значення (рядки 20-21) не відтворені — див. README.md та docs/international.md, розділ «From Ukraine».', true,'day_of_month_after_period'::filing_deadline_rule, 20, null, 'Податковий кодекс України, пункт 203.1 статті 203 — податкова декларація подається за базовий звітний (податковий) період, що дорівнює календарному місяцю, протягом 20 календарних днів, що настають за останнім календарним днем звітного (податкового) місяця. Сума податкового зобов''язання, зазначена в декларації, підлягає сплаті протягом ще 10 календарних днів після цього строку (пункт 203.2) — тобто фактично до 30-го числа; це поле моделює лише строк подання декларації, а не строк сплати, який socle не розрізняє (див. README.md).', 'pku', null, 1, 'Порядок заповнення і подання податкової звітності з податку на додану вартість, затверджений наказом Мінфіну від 28.01.2016 № 21, розділ III, пункт 4 — усі показники податкової звітності з ПДВ проставляються у гривнях без копійок з відповідним округленням за загальновстановленими правилами.', 'pdv-deklaracija-nakaz-21')
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  rounding_unit       = excluded.rounding_unit,
  rounding_reference  = excluded.rounding_reference,
  rounding_source_key = excluded.rounding_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('UA', 'UA-PDV', '11', 'base', 'Операції на митній території України, що оподатковуються за основною ставкою — обсяг постачання', '{"en":"Domestic supply at the standard rate — base"}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 1.1 (колонка A).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '11', 'tax', 'Операції на митній території України, що оподатковуються за основною ставкою — сума податку', '{"en":"Domestic supply at the standard rate — tax"}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 1.1 (колонка Б).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '12', 'base', 'Операції на митній території України, що оподатковуються за ставкою 7 % — обсяг постачання', '{"en":"Domestic supply at 7% — base"}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 1.2 (колонка A).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '12', 'tax', 'Операції на митній території України, що оподатковуються за ставкою 7 % — сума податку', '{"en":"Domestic supply at 7% — tax"}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 1.2 (колонка Б).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '13', 'base', 'Операції на митній території України, що оподатковуються за ставкою 14 % — обсяг постачання', '{"en":"Domestic supply at 14% — base"}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 1.3 (колонка A).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '13', 'tax', 'Операції на митній території України, що оподатковуються за ставкою 14 % — сума податку', '{"en":"Domestic supply at 14% — tax"}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 1.3 (колонка Б).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '21', 'base', 'Операції з вивезення товарів за межі митної території України (експорт), що оподатковуються за нульовою ставкою', '{"en":"Export of goods at the zero rate"}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 2.1; Податковий кодекс України, підпункт 195.1.1 пункту 195.1 статті 195.', 'pku'),
  ('UA', 'UA-PDV', '5', 'base', 'Операції, що звільнені від оподаткування, не є об''єктом оподаткування та/або постачання яких здійснено за межами митної території України', '{"en":"Exempt, out-of-scope and outside-territory supplies"}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 5.', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '9', 'total', 'Усього податкових зобов''язань', '{"en":"Total tax liability"}'::jsonb, 90, null, array['11:tax', '12:tax', '13:tax']::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ I, рядок 9.', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '101', 'base', 'Придбання (виготовлення, будівництво) на митній території України товарів/послуг за основною ставкою, що надають право на податковий кредит — обсяг', '{"en":"Domestic purchase at the standard rate — base"}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 10.1 (колонка A).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '101', 'tax', 'Придбання на митній території України за основною ставкою, що надають право на податковий кредит — сума податку', '{"en":"Domestic purchase at the standard rate — tax"}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 10.1 (колонка Б).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '102', 'base', 'Придбання на митній території України за ставкою 7 %, що надають право на податковий кредит — обсяг', '{"en":"Domestic purchase at 7% — base"}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 10.2 (колонка A).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '102', 'tax', 'Придбання на митній території України за ставкою 7 %, що надають право на податковий кредит — сума податку', '{"en":"Domestic purchase at 7% — tax"}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 10.2 (колонка Б).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '103', 'base', 'Придбання на митній території України за ставкою 14 %, що надають право на податковий кредит — обсяг', '{"en":"Domestic purchase at 14% — base"}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 10.3 (колонка A).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '103', 'tax', 'Придбання на митній території України за ставкою 14 %, що надають право на податковий кредит — сума податку', '{"en":"Domestic purchase at 14% — tax"}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 10.3 (колонка Б).', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '17', 'total', 'Усього податкового кредиту', '{"en":"Total tax credit"}'::jsonb, 160, null, array['101:tax', '102:tax', '103:tax']::text[], '{}'::text[], null, null, false, false, null, 'Форма декларації, розділ II, рядок 17.', 'pdv-deklaracija-nakaz-21'),
  ('UA', 'UA-PDV', '18', 'total', 'Позитивне значення різниці між сумою податкового зобов''язання та сумою податкового кредиту (сума ПДВ, яка підлягає сплаті до бюджету)', '{"en":"VAT payable to the budget"}'::jsonb, 170, null, array['9']::text[], array['17']::text[], null, null, true, false, null, 'Форма декларації, розділ III, рядок 18; Податковий кодекс України, пункт 200.1 та пункт 200.2 статті 200 — позитивна різниця підлягає сплаті до бюджету у строки, встановлені статтею 203.', 'pku'),
  ('UA', 'UA-PDV', '19', 'total', 'Від''ємне значення різниці між сумою податкового зобов''язання та сумою податкового кредиту', '{"en":"Negative value of the difference"}'::jsonb, 180, null, array['17']::text[], array['9']::text[], null, null, true, false, null, 'Форма декларації, розділ III, рядок 19; Податковий кодекс України, пункт 200.4 статті 200 — від''ємне значення зменшує податковий борг, повертається платнику як бюджетне відшкодування на його заяву або враховується у складі податкового кредиту наступного звітного періоду; розподіл цього рядка за трьома напрямками (рядки 20-21 форми) не відтворений у цьому пакеті.', 'pku')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('UA-NPSBO1-BS', 'UA', 'default', 'Баланс (Звіт про фінансовий стан) — форма № 1', 'balance_sheet', 'НП(С)БО 1', date '2013-01-01', null, 'Національне положення (стандарт) бухгалтерського обліку 1 «Загальні вимоги до фінансової звітності», затверджене наказом Мінфіну від 07.02.2013 № 73, додаток 1, форма № 1. Цей пакет транскрибує підсумкові рядки форми (нетто-балансова вартість за кожною групою активів), без окремих граф «первісна вартість» / «знос», без рядків, специфічних для страхових компаній і недержавних пенсійних фондів (1060, 1065, 1650, 1670, 1800) та без рядка 1200/1700 (необоротні активи, утримувані для продажу) — жодний рахунок цього пакета їх не потребує. Див. README.md.', 'npsbo-1'),
  ('UA-NPSBO1-IS', 'UA', 'default', 'Звіт про фінансові результати (Звіт про сукупний доход) — форма № 2', 'income_statement', 'НП(С)БО 1', date '2013-01-01', null, 'Національне положення (стандарт) бухгалтерського обліку 1, додаток 1, форма № 2, розділ I «Фінансові результати». Форма розрізняє для кожного проміжного підсумку окремий рядок «прибуток» і окремий рядок «збиток» (наприклад 2090/2095, 2190/2195, 2290/2295, 2350/2355), з яких лише один заповнюється в кожному звітному періоді; цей пакет спрощує кожну таку пару в один рядок зі знаком (додатне значення — прибуток, від''ємне — збиток), а також не відтворює розділи II «Сукупний доход», III «Елементи операційних витрат» і IV «Розрахунок показників прибутковості акцій», які жодний рахунок цього пакета не потребує. Див. README.md.', 'npsbo-1')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('UA-NPSBO1-BS', '1000', null, 'Нематеріальні активи', '{"en":"Intangible assets"}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1005', null, 'Незавершені капітальні інвестиції', '{"en":"Capital investments in progress"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1010', null, 'Основні засоби', '{"en":"Property, plant and equipment"}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1030', null, 'Довгострокові фінансові інвестиції', '{"en":"Long-term financial investments"}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1045', null, 'Відстрочені податкові активи', '{"en":"Deferred tax assets"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1090', null, 'Інші необоротні активи', '{"en":"Other non-current assets"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1095', null, 'Усього за розділом I', '{"en":"Total non-current assets"}'::jsonb, 70, 1, true, array['1000', '1005', '1010', '1030', '1045', '1090']::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1100', null, 'Запаси', '{"en":"Inventories"}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1120', null, 'Векселі одержані', '{"en":"Bills receivable"}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1125', null, 'Дебіторська заборгованість за продукцію, товари, роботи, послуги', '{"en":"Trade receivables"}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1130', null, 'Дебіторська заборгованість за розрахунками — за виданими авансами', '{"en":"Receivables — advances paid"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1155', null, 'Інша поточна дебіторська заборгованість', '{"en":"Other current receivables"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1160', null, 'Поточні фінансові інвестиції', '{"en":"Current financial investments"}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1165', null, 'Гроші та їх еквіваленти', '{"en":"Cash and cash equivalents"}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1170', null, 'Витрати майбутніх періодів', '{"en":"Prepaid expenses"}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1195', null, 'Усього за розділом II', '{"en":"Total current assets"}'::jsonb, 160, 1, true, array['1100', '1120', '1125', '1130', '1155', '1160', '1165', '1170']::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1300', null, 'Баланс', '{"en":"Total assets"}'::jsonb, 170, 1, true, array['1095', '1195']::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1400', null, 'Зареєстрований (пайовий) капітал', '{"en":"Registered (share) capital"}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1405', null, 'Капітал у дооцінках', '{"en":"Revaluation capital"}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1410', null, 'Додатковий капітал', '{"en":"Additional capital"}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1415', null, 'Резервний капітал', '{"en":"Reserve capital"}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1420', null, 'Нерозподілені прибутки (непокриті збитки)', '{"en":"Retained earnings (accumulated losses)"}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1425', null, 'Неоплачений капітал', '{"en":"Unpaid capital"}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1430', null, 'Вилучений капітал', '{"en":"Treasury capital"}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1495', null, 'Усього за розділом I пасиву', '{"en":"Total equity"}'::jsonb, 250, 1, true, array['1400', '1405', '1410', '1415', '1420']::text[], array['1425', '1430']::text[], null, null, null),
  ('UA-NPSBO1-BS', '1500', null, 'Відстрочені податкові зобов''язання', '{"en":"Deferred tax liabilities"}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1510', null, 'Довгострокові кредити банків', '{"en":"Long-term bank loans"}'::jsonb, 270, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1515', null, 'Інші довгострокові зобов''язання', '{"en":"Other long-term liabilities"}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1520', null, 'Довгострокові забезпечення', '{"en":"Long-term provisions"}'::jsonb, 290, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1525', null, 'Цільове фінансування', '{"en":"Targeted financing"}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1595', null, 'Усього за розділом II пасиву', '{"en":"Total long-term liabilities"}'::jsonb, 310, 1, true, array['1500', '1510', '1515', '1520', '1525']::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1600', null, 'Короткострокові кредити банків', '{"en":"Short-term bank loans"}'::jsonb, 320, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1605', null, 'Векселі видані', '{"en":"Bills payable"}'::jsonb, 330, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1610', null, 'Поточна кредиторська заборгованість за довгостроковими зобов''язаннями', '{"en":"Current portion of long-term liabilities"}'::jsonb, 340, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1615', null, 'Поточна кредиторська заборгованість за товари, роботи, послуги', '{"en":"Trade payables"}'::jsonb, 350, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1620', null, 'Поточна кредиторська заборгованість за розрахунками з бюджетом', '{"en":"Payables to the budget"}'::jsonb, 360, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1625', null, 'Поточна кредиторська заборгованість за розрахунками зі страхування', '{"en":"Payables for insurance"}'::jsonb, 370, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1630', null, 'Поточна кредиторська заборгованість за розрахунками з оплати праці', '{"en":"Payables for payroll"}'::jsonb, 380, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1635', null, 'Поточна кредиторська заборгованість — за одержаними авансами', '{"en":"Advances received"}'::jsonb, 390, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1640', null, 'Поточна кредиторська заборгованість з учасниками', '{"en":"Payables to participants"}'::jsonb, 400, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1665', null, 'Доходи майбутніх періодів', '{"en":"Deferred income"}'::jsonb, 410, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1690', null, 'Інші поточні зобов''язання', '{"en":"Other current liabilities"}'::jsonb, 420, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1695', null, 'Усього за розділом III пасиву', '{"en":"Total current liabilities"}'::jsonb, 430, 1, true, array['1600', '1605', '1610', '1615', '1620', '1625', '1630', '1635', '1640', '1665', '1690']::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-BS', '1900', null, 'Баланс', '{"en":"Total equity and liabilities"}'::jsonb, 440, 1, true, array['1495', '1595', '1695']::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2000', null, 'Чистий доход від реалізації продукції (товарів, робіт, послуг)', '{"en":"Net revenue from sale of goods, works and services"}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2050', null, 'Собівартість реалізованої продукції (товарів, робіт, послуг)', '{"en":"Cost of goods, works and services sold"}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2090', null, 'Валовий прибуток (збиток)', '{"en":"Gross profit (loss)"}'::jsonb, 30, 1, true, array['2000']::text[], array['2050']::text[], null, null, null),
  ('UA-NPSBO1-IS', '2120', null, 'Інші операційні доходи', '{"en":"Other operating income"}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2130', null, 'Адміністративні витрати', '{"en":"Administrative expenses"}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2150', null, 'Витрати на збут', '{"en":"Selling expenses"}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2180', null, 'Інші операційні витрати', '{"en":"Other operating expenses"}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2190', null, 'Фінансовий результат від операційної діяльності (прибуток/збиток)', '{"en":"Operating profit (loss)"}'::jsonb, 80, 1, true, array['2090', '2120']::text[], array['2130', '2150', '2180']::text[], null, null, null),
  ('UA-NPSBO1-IS', '2220', null, 'Інші фінансові доходи', '{"en":"Other financial income"}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2240', null, 'Інші доходи', '{"en":"Other income"}'::jsonb, 100, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2250', null, 'Фінансові витрати', '{"en":"Financial expenses"}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2270', null, 'Інші витрати', '{"en":"Other expenses"}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2290', null, 'Фінансовий результат до оподаткування (прибуток/збиток)', '{"en":"Profit (loss) before tax"}'::jsonb, 130, 1, true, array['2190', '2220', '2240']::text[], array['2250', '2270']::text[], null, null, null),
  ('UA-NPSBO1-IS', '2300', null, 'Витрати (доход) з податку на прибуток', '{"en":"Income tax expense (income)"}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('UA-NPSBO1-IS', '2350', null, 'Чистий фінансовий результат (прибуток/збиток)', '{"en":"Net profit (loss)"}'::jsonb, 150, 1, true, array['2290']::text[], array['2300']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('UA-NPSBO1-BS', '1000', 10, 'code_range', '12', '12', null, 'any'),
    ('UA-NPSBO1-BS', '1000', 20, 'account_code', '133', null, null, 'any'),
    ('UA-NPSBO1-BS', '1005', 10, 'code_range', '15', '15', null, 'any'),
    ('UA-NPSBO1-BS', '1010', 10, 'code_range', '10', '11', null, 'any'),
    ('UA-NPSBO1-BS', '1010', 20, 'account_code', '131', null, null, 'any'),
    ('UA-NPSBO1-BS', '1010', 30, 'account_code', '132', null, null, 'any'),
    ('UA-NPSBO1-BS', '1030', 10, 'code_range', '14', '14', null, 'any'),
    ('UA-NPSBO1-BS', '1045', 10, 'account_code', '17', null, null, 'any'),
    ('UA-NPSBO1-BS', '1090', 10, 'code_range', '18', '19', null, 'any'),
    ('UA-NPSBO1-BS', '1100', 10, 'code_range', '20', '28', null, 'any'),
    ('UA-NPSBO1-BS', '1120', 10, 'account_code', '34', null, null, 'any'),
    ('UA-NPSBO1-BS', '1125', 10, 'account_code', '36', null, null, 'any'),
    ('UA-NPSBO1-BS', '1130', 10, 'account_code', '371', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 10, 'account_code', '372', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 20, 'account_code', '373', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 30, 'account_code', '374', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 40, 'account_code', '377', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 50, 'account_code', '38', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 60, 'account_code', '6412', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 70, 'account_code', '6414', null, null, 'any'),
    ('UA-NPSBO1-BS', '1155', 80, 'account_code', '644', null, null, 'any'),
    ('UA-NPSBO1-BS', '1160', 10, 'account_code', '35', null, null, 'any'),
    ('UA-NPSBO1-BS', '1165', 10, 'code_range', '30', '31', null, 'any'),
    ('UA-NPSBO1-BS', '1165', 20, 'account_code', '33', null, null, 'any'),
    ('UA-NPSBO1-BS', '1165', 30, 'account_code', '331', null, null, 'any'),
    ('UA-NPSBO1-BS', '1170', 10, 'account_code', '39', null, null, 'any'),
    ('UA-NPSBO1-BS', '1400', 10, 'code_range', '40', '40', null, 'any'),
    ('UA-NPSBO1-BS', '1405', 10, 'code_range', '41', '41', null, 'any'),
    ('UA-NPSBO1-BS', '1410', 10, 'code_range', '42', '42', null, 'any'),
    ('UA-NPSBO1-BS', '1415', 10, 'account_code', '43', null, null, 'any'),
    ('UA-NPSBO1-BS', '1420', 10, 'code_range', '44', '44', null, 'any'),
    ('UA-NPSBO1-BS', '1425', 10, 'account_code', '46', null, null, 'any'),
    ('UA-NPSBO1-BS', '1430', 10, 'code_range', '45', '45', null, 'any'),
    ('UA-NPSBO1-BS', '1500', 10, 'account_code', '54', null, null, 'any'),
    ('UA-NPSBO1-BS', '1510', 10, 'code_range', '50', '50', null, 'any'),
    ('UA-NPSBO1-BS', '1515', 10, 'code_range', '51', '53', null, 'any'),
    ('UA-NPSBO1-BS', '1515', 20, 'account_code', '55', null, null, 'any'),
    ('UA-NPSBO1-BS', '1520', 10, 'code_range', '47', '47', null, 'any'),
    ('UA-NPSBO1-BS', '1525', 10, 'account_code', '48', null, null, 'any'),
    ('UA-NPSBO1-BS', '1600', 10, 'code_range', '60', '60', null, 'any'),
    ('UA-NPSBO1-BS', '1605', 10, 'account_code', '62', null, null, 'any'),
    ('UA-NPSBO1-BS', '1610', 10, 'account_code', '61', null, null, 'any'),
    ('UA-NPSBO1-BS', '1615', 10, 'account_code', '63', null, null, 'any'),
    ('UA-NPSBO1-BS', '1620', 10, 'account_code', '6411', null, null, 'any'),
    ('UA-NPSBO1-BS', '1620', 20, 'account_code', '6413', null, null, 'any'),
    ('UA-NPSBO1-BS', '1620', 30, 'account_code', '642', null, null, 'any'),
    ('UA-NPSBO1-BS', '1620', 40, 'account_code', '643', null, null, 'any'),
    ('UA-NPSBO1-BS', '1625', 10, 'code_range', '65', '65', null, 'any'),
    ('UA-NPSBO1-BS', '1630', 10, 'code_range', '66', '66', null, 'any'),
    ('UA-NPSBO1-BS', '1635', 10, 'account_code', '681', null, null, 'any'),
    ('UA-NPSBO1-BS', '1640', 10, 'code_range', '67', '67', null, 'any'),
    ('UA-NPSBO1-BS', '1665', 10, 'account_code', '69', null, null, 'any'),
    ('UA-NPSBO1-BS', '1690', 10, 'account_code', '684', null, null, 'any'),
    ('UA-NPSBO1-BS', '1690', 20, 'code_range', '685', '685', null, 'any'),
    ('UA-NPSBO1-IS', '2000', 10, 'code_range', '70', '70', null, 'any'),
    ('UA-NPSBO1-IS', '2050', 10, 'code_range', '90', '91', null, 'any'),
    ('UA-NPSBO1-IS', '2120', 10, 'code_range', '71', '71', null, 'any'),
    ('UA-NPSBO1-IS', '2130', 10, 'account_code', '92', null, null, 'any'),
    ('UA-NPSBO1-IS', '2150', 10, 'account_code', '93', null, null, 'any'),
    ('UA-NPSBO1-IS', '2180', 10, 'code_range', '94', '94', null, 'any'),
    ('UA-NPSBO1-IS', '2220', 10, 'code_range', '73', '73', null, 'any'),
    ('UA-NPSBO1-IS', '2240', 10, 'code_range', '74', '74', null, 'any'),
    ('UA-NPSBO1-IS', '2250', 10, 'code_range', '95', '95', null, 'any'),
    ('UA-NPSBO1-IS', '2270', 10, 'code_range', '97', '97', null, 'any'),
    ('UA-NPSBO1-IS', '2300', 10, 'account_code', '98', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('UA', 'Україна', '{"en":"Ukraine"}'::jsonb, array['uk', 'en']::text[], 'UAH', '36', '63', '6851', '949', '441', '702', '902', '311', '301', 'SAL', 'PUR', 'GEN', 'uk', 'retained_earnings', null, null, null, 'OPN', 'half_up', default, '714', '945', null, null, null, null, '6413', '6414', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{NNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Закон України «Про бухгалтерський облік та фінансову звітність в Україні» від 16.07.1999 № 996-XIV, стаття 9 — первинні документи, зокрема податкові накладні та видаткові накладні, складаються під час здійснення господарської операції; форма нумерації податкової накладної визначена Порядком заповнення податкової накладної (наказ Мінфіну від 31.12.2015 № 1307) і не збігається обов''язково з номером комерційного документа. Формат тут — приклад послідовної нумерації, а не єдино нав''язана форма.',
  numbering_source_key          = 'pku',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Податковий кодекс України, пункт 187.1 статті 187 — датою виникнення податкових зобов''язань з постачання товарів/послуг вважається дата, яка припадає на податковий (звітний) період, протягом якого відбувається будь-яка з подій, що сталася раніше: або дата зарахування коштів від покупця/замовника, або дата відвантаження товарів (оформлення документа на постачання послуг) — «правило першої події». Це не є принципом, від якого дата рахунку є винятком (як у Бельгії чи Люксембурзі): жодна з двох дат не переважає іншу за умовчанням, тому системного слова цього поля («дата рахунку», «дата поставки») не існує рівно для цього правила; `invoice_if_issued` тут наближення — оплата чи відвантаження, що сталися раніше, а не виставлення рахунку, фіксують подію. Прогалину socle щодо «першої з двох дат» без прив''язки до рахунку задокументовано в README.md та в docs/international.md, розділ «From Ukraine».',
  tax_point_source_key          = 'pku',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Закон України «Про бухгалтерський облік та фінансову звітність в Україні», стаття 9, частина 5 — виправлення помилок у первинних документах здійснюється способом, який передбачає складання нового документа (зокрема, розрахунку коригування) і не допускає стирання чи виправлення без слідів; Податковий кодекс України, пункт 192.1 статті 192 — коригування податкових зобов''язань і податкового кредиту здійснюється шляхом складання розрахунку коригування до податкової накладної, зареєстрованого в ЄРПН.',
  posted_edit_policy_source_key = 'pku',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Кожна платна поставка товарів/послуг платника ПДВ супроводжується складенням податкової накладної, яка підлягає обов''язковій реєстрації в Єдиному реєстрі податкових накладних (ЄРПН) — Податковий кодекс України, статті 201.1 та 201.10, без порогу суми з часу скасування такого порогу (Закон України від 21.12.2016 № 1797-VIII, набрав чинності 01.01.2017). Реєстрація підпорядкована граничним строкам, різним залежно від половини місяця складення (стаття 201.10), і системі моніторингу критеріїв оцінки ступеня ризиків (СМКОР, постанова КМУ від 11.12.2019 № 1165), яка може зупинити реєстрацію окремої накладної до розгляду. `profile` тут залишено порожнім, а не заповнено умовною національною назвою: податкова накладна — це структурований документ, який податкова накладна складається у форматі, визначеному ДПС (наказ Мінфіну від 31.12.2015 № 1307, з подальшими змінами), і подається до ЄРПН через спеціалізоване програмне забезпечення (M.E.Doc, Вчасно тощо) або кабінет платника — вона не є жодним із профілів, побудованих на семантичній моделі EN 16931 (Peppol BIS, Factur-X, XRechnung, PINT), і не є обміном між рівними сторонами: реєстрація в ЄРПН — це умова, від якої залежить право покупця на податковий кредит (стаття 201.10), а не факт випуску самого документа продавцем, який лишається за продавцем. `party_scheme` і `vat_scheme` лишаються порожніми з тієї ж причини: в України немає учасницької схеми ISO 6523, зареєстрованої в мережі Peppol. Прогалину socle щодо реєстрації в державному реєстрі, її строків і блокування (СМКОР) задокументовано в README.md та в docs/international.md, розділ «From Ukraine».',
  einvoice_source_key           = 'yerpn-postanova-1165',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'UA';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('UA', 'reverse_charge', 'reverse_charge', 'Податок на додану вартість нараховується та сплачується отримувачем послуг самостійно відповідно до пункту 208.2 статті 208 Податкового кодексу України.', '{"en":"VAT is charged and paid by the recipient of the service, on their own account, under article 208.2 of the Tax Code of Ukraine."}'::jsonb, 10, date '1970-01-01', null, 'Податковий кодекс України, пункт 208.2 статті 208 — отримувач послуг, наданих нерезидентом, місце постачання яких розташоване на митній території України, є особою, відповідальною за нарахування та сплату податку до бюджету.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
