-- Ekwo OS — Romania: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ro at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build ro`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Legea nr. 227/2015 privind Codul fiscal, cu modificările și completările ulterioare — formă consolidată (Ministerul Justiției — Portalul Legislativ)
--     https://legislatie.just.ro/Public/DetaliiDocument/171282
--   Legea nr. 141/2025 privind unele măsuri fiscal-bugetare, în domeniul pensiilor și al gestionării eficiente a resurselor din instituțiile publice, pentru fortificarea capacității financiare — art. II pct. 42-45, care modifică art. 291 din Codul fiscal (cotele de TVA) și art. III (regim tranzitoriu locuințe) (Agenția Națională de Administrare Fiscală)
--     https://static.anaf.ro/static/10/Anaf/legislatie/L_141_2025.pdf
--   Ordinul președintelui ANAF nr. 174/2026 pentru aprobarea modelului și conținutului formularului (300) „Decont de taxă pe valoarea adăugată” (Agenția Națională de Administrare Fiscală)
--     https://static.anaf.ro/static/10/Anaf/legislatie/OPANAF_174_2026.pdf
--   Formularul (300) „Decont de taxă pe valoarea adăugată” — anexele 1-3 la Ordinul președintelui ANAF nr. 174/2026: modelul, instrucțiunile de completare și caracteristicile de editare (Agenția Națională de Administrare Fiscală)
--     https://static.anaf.ro/static/10/Anaf/formulare/D300_OPANAF_174_2026.pdf
--   Ordonanța de urgență a Guvernului nr. 120/2021 privind administrarea, funcționarea și implementarea sistemului național privind factura electronică RO e-Factura, cu modificările și completările ulterioare — formă consolidată (Ministerul Justiției — Portalul Legislativ)
--     https://legislatie.just.ro/Public/DetaliiDocument/247243
--   Ordinul ministrului finanțelor nr. 4.092/2022 pentru modificarea Ordinului nr. 1.366/2021 privind aprobarea specificațiilor tehnice ale sistemului RO e-Factura — Core Invoice Usage Specification pentru România (CIUS-RO), versiunea 1.0.1 (Ministerul Finanțelor)
--     https://legislatie.just.ro/Public/DetaliiDocument/262568
--   Ordinul președintelui ANAF nr. 1.783/2021 privind natura informațiilor pe care contribuabilul/plătitorul are obligația să le declare prin fișierul standard de control fiscal (SAF-T) și modelul de raportare, precum și calendarul de implementare — formă consolidată (Ministerul Justiției — Portalul Legislativ)
--     https://legislatie.just.ro/public/DetaliiDocument/248326
--   Legea nr. 72/2013 privind măsurile pentru combaterea întârzierii în executarea obligațiilor de plată a unor sume de bani rezultând din contracte încheiate între profesioniști și între aceștia și autorități contractante — formă consolidată (Ministerul Justiției — Portalul Legislativ)
--     https://legislatie.just.ro/Public/DetaliiDocumentAfis/174101
--   Ordinul ministrului finanțelor publice nr. 1.802/2014 pentru aprobarea Reglementărilor contabile privind situațiile financiare anuale individuale și situațiile financiare anuale consolidate — formă consolidată, inclusiv Planul de conturi general (pct. 14) și formatele bilanțului și contului de profit și pierdere (Ministerul Justiției — Portalul Legislativ)
--     https://legislatie.just.ro/Public/DetaliiDocument/164320
--   Spațiul Privat Virtual (SPV) — portalul prin care se depun declarațiile fiscale, inclusiv decontul de TVA și facturile RO e-Factura (Agenția Națională de Administrare Fiscală)
--     https://www.anaf.ro/anaf/internet/ANAF/servicii_online/serviciul_spatiul_privat_virtual/
--   EN 16931-1 — semantic data model of the core elements of an electronic invoice, required by Directive 2014/55/EU (European Commission)
--     https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108950/EN+16931+compliance
--   UNCL5305 — VAT category code list (BT-118 and BT-151), the subset published for EN 16931 (OpenPEPPOL — list published by the European Commission)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/
--   VATEX — VAT exemption reason code list (BT-121) (OpenPEPPOL — list published by the European Commission)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('RO', 'Romania', '0.1.0', date '2026-09-25', '20260921145425', 'community', null, null, '77d66c683ba88e51b6be332cc8dac6650d19f29c36b211e46ced1bd800c45382', '[{"key":"codul-fiscal","title":"Legea nr. 227/2015 privind Codul fiscal, cu modificările și completările ulterioare — formă consolidată","publisher":"Ministerul Justiției — Portalul Legislativ","url":"https://legislatie.just.ro/Public/DetaliiDocument/171282","consulted_on":"2026-09-25","kind":"law"},{"key":"legea-141-2025","title":"Legea nr. 141/2025 privind unele măsuri fiscal-bugetare, în domeniul pensiilor și al gestionării eficiente a resurselor din instituțiile publice, pentru fortificarea capacității financiare — art. II pct. 42-45, care modifică art. 291 din Codul fiscal (cotele de TVA) și art. III (regim tranzitoriu locuințe)","publisher":"Agenția Națională de Administrare Fiscală","url":"https://static.anaf.ro/static/10/Anaf/legislatie/L_141_2025.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"opanaf-174-2026","title":"Ordinul președintelui ANAF nr. 174/2026 pentru aprobarea modelului și conținutului formularului (300) „Decont de taxă pe valoarea adăugată”","publisher":"Agenția Națională de Administrare Fiscală","url":"https://static.anaf.ro/static/10/Anaf/legislatie/OPANAF_174_2026.pdf","consulted_on":"2026-09-25","kind":"regulation"},{"key":"d300-formular","title":"Formularul (300) „Decont de taxă pe valoarea adăugată” — anexele 1-3 la Ordinul președintelui ANAF nr. 174/2026: modelul, instrucțiunile de completare și caracteristicile de editare","publisher":"Agenția Națională de Administrare Fiscală","url":"https://static.anaf.ro/static/10/Anaf/formulare/D300_OPANAF_174_2026.pdf","consulted_on":"2026-09-25","kind":"form"},{"key":"oug-120-2021","title":"Ordonanța de urgență a Guvernului nr. 120/2021 privind administrarea, funcționarea și implementarea sistemului național privind factura electronică RO e-Factura, cu modificările și completările ulterioare — formă consolidată","publisher":"Ministerul Justiției — Portalul Legislativ","url":"https://legislatie.just.ro/Public/DetaliiDocument/247243","consulted_on":"2026-09-25","kind":"law"},{"key":"omf-4092-2022","title":"Ordinul ministrului finanțelor nr. 4.092/2022 pentru modificarea Ordinului nr. 1.366/2021 privind aprobarea specificațiilor tehnice ale sistemului RO e-Factura — Core Invoice Usage Specification pentru România (CIUS-RO), versiunea 1.0.1","publisher":"Ministerul Finanțelor","url":"https://legislatie.just.ro/Public/DetaliiDocument/262568","consulted_on":"2026-09-25","kind":"regulation"},{"key":"oanaf-1783-2021","title":"Ordinul președintelui ANAF nr. 1.783/2021 privind natura informațiilor pe care contribuabilul/plătitorul are obligația să le declare prin fișierul standard de control fiscal (SAF-T) și modelul de raportare, precum și calendarul de implementare — formă consolidată","publisher":"Ministerul Justiției — Portalul Legislativ","url":"https://legislatie.just.ro/public/DetaliiDocument/248326","consulted_on":"2026-09-25","kind":"regulation"},{"key":"legea-72-2013","title":"Legea nr. 72/2013 privind măsurile pentru combaterea întârzierii în executarea obligațiilor de plată a unor sume de bani rezultând din contracte încheiate între profesioniști și între aceștia și autorități contractante — formă consolidată","publisher":"Ministerul Justiției — Portalul Legislativ","url":"https://legislatie.just.ro/Public/DetaliiDocumentAfis/174101","consulted_on":"2026-09-25","kind":"law"},{"key":"omfp-1802-2014","title":"Ordinul ministrului finanțelor publice nr. 1.802/2014 pentru aprobarea Reglementărilor contabile privind situațiile financiare anuale individuale și situațiile financiare anuale consolidate — formă consolidată, inclusiv Planul de conturi general (pct. 14) și formatele bilanțului și contului de profit și pierdere","publisher":"Ministerul Justiției — Portalul Legislativ","url":"https://legislatie.just.ro/Public/DetaliiDocument/164320","consulted_on":"2026-09-25","kind":"regulation"},{"key":"spv-portal","title":"Spațiul Privat Virtual (SPV) — portalul prin care se depun declarațiile fiscale, inclusiv decontul de TVA și facturile RO e-Factura","publisher":"Agenția Națională de Administrare Fiscală","url":"https://www.anaf.ro/anaf/internet/ANAF/servicii_online/serviciul_spatiul_privat_virtual/","consulted_on":"2026-09-25","kind":"portal"},{"key":"en-16931","title":"EN 16931-1 — semantic data model of the core elements of an electronic invoice, required by Directive 2014/55/EU","publisher":"European Commission","url":"https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108950/EN+16931+compliance","consulted_on":"2026-09-25","kind":"standard"},{"key":"uncl5305","title":"UNCL5305 — VAT category code list (BT-118 and BT-151), the subset published for EN 16931","publisher":"OpenPEPPOL — list published by the European Commission","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/","consulted_on":"2026-09-25","kind":"standard"},{"key":"vatex","title":"VATEX — VAT exemption reason code list (BT-121)","publisher":"OpenPEPPOL — list published by the European Commission","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/","consulted_on":"2026-09-25","kind":"standard"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('RO', 'default', 'Planul de conturi general (clasele 1-7)', '{}'::jsonb, true, 'companies', array['RO-OMFP-BS', 'RO-OMFP-IS']::text[], null, 'Ordinul ministrului finanțelor publice nr. 1.802/2014, pct. 14 și anexă — Planul de conturi general, cu nouă clase (1-9). Acest pachet transcrie un subset funcțional al claselor 1-7 (capitaluri, imobilizări, stocuri, terți, trezorerie, cheltuieli, venituri), folosind exact codurile oficiale ale conturilor sintetice de gradul I și II; clasele 8 (conturi speciale, în afara bilanțului) și 9 (conturi de gestiune, contabilitate de gestiune internă) nu sunt reluate, fiind opționale și fără corespondent direct în formularul de TVA sau în situațiile financiare prescurtate. Câteva conturi analitice de gradul II fără o subdiviziune oficială fixă (de exemplu 6588) sunt o convenție a acestui pachet, semnalată în README', 'omfp-1802-2014')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('RO', 'default', '10', 'Capital și rezerve', '{}'::jsonb, 'equity', false, null, 10),
  ('RO', 'default', '101', 'Capital', '{}'::jsonb, 'equity', false, '10', 20),
  ('RO', 'default', '1012', 'Capital subscris vărsat', '{}'::jsonb, 'equity', false, '101', 30),
  ('RO', 'default', '104', 'Prime de capital', '{}'::jsonb, 'equity', false, '10', 40),
  ('RO', 'default', '1041', 'Prime de emisiune', '{}'::jsonb, 'equity', false, '104', 50),
  ('RO', 'default', '105', 'Rezerve din reevaluare', '{}'::jsonb, 'equity', false, '10', 60),
  ('RO', 'default', '106', 'Rezerve', '{}'::jsonb, 'equity', false, '10', 70),
  ('RO', 'default', '1061', 'Rezerve legale', '{}'::jsonb, 'equity', false, '106', 80),
  ('RO', 'default', '1068', 'Alte rezerve', '{}'::jsonb, 'equity', false, '106', 90),
  ('RO', 'default', '11', 'Rezultatul reportat', '{}'::jsonb, 'equity_retained', false, null, 100),
  ('RO', 'default', '117', 'Rezultatul reportat', '{}'::jsonb, 'equity_retained', false, '11', 110),
  ('RO', 'default', '1171', 'Rezultatul reportat reprezentând profitul nerepartizat sau pierderea neacoperită', '{}'::jsonb, 'equity_retained', false, '117', 120),
  ('RO', 'default', '12', 'Rezultatul exercițiului financiar', '{}'::jsonb, 'equity', false, null, 130),
  ('RO', 'default', '121', 'Profit sau pierdere', '{}'::jsonb, 'equity', false, '12', 140),
  ('RO', 'default', '129', 'Repartizarea profitului', '{}'::jsonb, 'equity', false, '12', 150),
  ('RO', 'default', '13', 'Subvenții pentru investiții', '{}'::jsonb, 'liability_non_current', false, null, 160),
  ('RO', 'default', '131', 'Subvenții guvernamentale pentru investiții', '{}'::jsonb, 'liability_non_current', false, '13', 170),
  ('RO', 'default', '15', 'Provizioane', '{}'::jsonb, 'liability_non_current', false, null, 180),
  ('RO', 'default', '151', 'Provizioane', '{}'::jsonb, 'liability_non_current', false, '15', 190),
  ('RO', 'default', '1511', 'Provizioane pentru litigii', '{}'::jsonb, 'liability_non_current', false, '151', 200),
  ('RO', 'default', '1512', 'Provizioane pentru garanții acordate clienților', '{}'::jsonb, 'liability_non_current', false, '151', 210),
  ('RO', 'default', '1518', 'Alte provizioane', '{}'::jsonb, 'liability_non_current', false, '151', 220),
  ('RO', 'default', '16', 'Împrumuturi și datorii asimilate', '{}'::jsonb, 'liability_non_current', false, null, 230),
  ('RO', 'default', '162', 'Credite bancare pe termen lung', '{}'::jsonb, 'liability_non_current', false, '16', 240),
  ('RO', 'default', '167', 'Alte împrumuturi și datorii asimilate', '{}'::jsonb, 'liability_non_current', false, '16', 250),
  ('RO', 'default', '168', 'Dobânzi aferente împrumuturilor și datoriilor asimilate', '{}'::jsonb, 'liability_non_current', false, '16', 260),
  ('RO', 'default', '20', 'Imobilizări necorporale', '{}'::jsonb, 'asset_fixed', false, null, 270),
  ('RO', 'default', '201', 'Cheltuieli de constituire', '{}'::jsonb, 'asset_fixed', false, '20', 280),
  ('RO', 'default', '203', 'Cheltuieli de dezvoltare', '{}'::jsonb, 'asset_fixed', false, '20', 290),
  ('RO', 'default', '205', 'Concesiuni, brevete, licențe, mărci comerciale, drepturi și active similare', '{}'::jsonb, 'asset_fixed', false, '20', 300),
  ('RO', 'default', '208', 'Alte imobilizări necorporale', '{}'::jsonb, 'asset_fixed', false, '20', 310),
  ('RO', 'default', '21', 'Imobilizări corporale', '{}'::jsonb, 'asset_fixed', false, null, 330),
  ('RO', 'default', '211', 'Terenuri și amenajări de terenuri', '{}'::jsonb, 'asset_fixed', false, '21', 340),
  ('RO', 'default', '2111', 'Terenuri', '{}'::jsonb, 'asset_fixed', false, '211', 350),
  ('RO', 'default', '212', 'Construcții', '{}'::jsonb, 'asset_fixed', false, '21', 360),
  ('RO', 'default', '213', 'Instalații tehnice și mijloace de transport', '{}'::jsonb, 'asset_fixed', false, '21', 370),
  ('RO', 'default', '2131', 'Echipamente tehnologice', '{}'::jsonb, 'asset_fixed', false, '213', 380),
  ('RO', 'default', '2133', 'Mijloace de transport', '{}'::jsonb, 'asset_fixed', false, '213', 390),
  ('RO', 'default', '214', 'Mobilier, aparatură birotică și alte active corporale', '{}'::jsonb, 'asset_fixed', false, '21', 400),
  ('RO', 'default', '231', 'Imobilizări corporale în curs de execuție', '{}'::jsonb, 'asset_fixed', false, '21', 410),
  ('RO', 'default', '233', 'Imobilizări necorporale în curs de execuție', '{}'::jsonb, 'asset_fixed', false, '20', 320),
  ('RO', 'default', '234', 'Avansuri acordate pentru imobilizări corporale', '{}'::jsonb, 'asset_fixed', false, '21', 420),
  ('RO', 'default', '26', 'Imobilizări financiare', '{}'::jsonb, 'asset_non_current', false, null, 430),
  ('RO', 'default', '261', 'Acțiuni deținute la entitățile afiliate', '{}'::jsonb, 'asset_non_current', false, '26', 440),
  ('RO', 'default', '263', 'Interese de participare', '{}'::jsonb, 'asset_non_current', false, '26', 450),
  ('RO', 'default', '267', 'Creanțe imobilizate', '{}'::jsonb, 'asset_non_current', false, '26', 460),
  ('RO', 'default', '28', 'Amortizări privind imobilizările', '{}'::jsonb, 'asset_fixed', false, null, 470),
  ('RO', 'default', '280', 'Amortizări privind imobilizările necorporale', '{}'::jsonb, 'asset_fixed', false, '28', 480),
  ('RO', 'default', '2805', 'Amortizarea concesiunilor, brevetelor, licențelor și mărcilor comerciale', '{}'::jsonb, 'asset_fixed', false, '280', 490),
  ('RO', 'default', '281', 'Amortizări privind imobilizările corporale', '{}'::jsonb, 'asset_fixed', false, '28', 500),
  ('RO', 'default', '2812', 'Amortizarea construcțiilor', '{}'::jsonb, 'asset_fixed', false, '281', 510),
  ('RO', 'default', '2813', 'Amortizarea instalațiilor tehnice și mijloacelor de transport', '{}'::jsonb, 'asset_fixed', false, '281', 520),
  ('RO', 'default', '2814', 'Amortizarea mobilierului și aparaturii birotice', '{}'::jsonb, 'asset_fixed', false, '281', 530),
  ('RO', 'default', '29', 'Ajustări pentru deprecierea imobilizărilor', '{}'::jsonb, 'asset_fixed', false, null, 540),
  ('RO', 'default', '291', 'Ajustări pentru deprecierea imobilizărilor corporale', '{}'::jsonb, 'asset_fixed', false, '29', 550),
  ('RO', 'default', '30', 'Stocuri de materii prime și materiale', '{}'::jsonb, 'asset_current', false, null, 560),
  ('RO', 'default', '301', 'Materii prime', '{}'::jsonb, 'asset_current', false, '30', 570),
  ('RO', 'default', '302', 'Materiale consumabile', '{}'::jsonb, 'asset_current', false, '30', 580),
  ('RO', 'default', '303', 'Materiale de natura obiectelor de inventar', '{}'::jsonb, 'asset_current', false, '30', 590),
  ('RO', 'default', '33', 'Producția în curs de execuție', '{}'::jsonb, 'asset_current', false, null, 600),
  ('RO', 'default', '331', 'Produse în curs de execuție', '{}'::jsonb, 'asset_current', false, '33', 610),
  ('RO', 'default', '332', 'Servicii în curs de execuție', '{}'::jsonb, 'asset_current', false, '33', 620),
  ('RO', 'default', '34', 'Produse', '{}'::jsonb, 'asset_current', false, null, 630),
  ('RO', 'default', '341', 'Semifabricate', '{}'::jsonb, 'asset_current', false, '34', 640),
  ('RO', 'default', '345', 'Produse finite', '{}'::jsonb, 'asset_current', false, '34', 650),
  ('RO', 'default', '346', 'Produse reziduale', '{}'::jsonb, 'asset_current', false, '34', 660),
  ('RO', 'default', '37', 'Mărfuri', '{}'::jsonb, 'asset_current', false, null, 670),
  ('RO', 'default', '371', 'Mărfuri', '{}'::jsonb, 'asset_current', false, '37', 680),
  ('RO', 'default', '38', 'Ambalaje', '{}'::jsonb, 'asset_current', false, null, 690),
  ('RO', 'default', '381', 'Ambalaje', '{}'::jsonb, 'asset_current', false, '38', 700),
  ('RO', 'default', '40', 'Furnizori și conturi asimilate', '{}'::jsonb, 'liability_payable', true, null, 710),
  ('RO', 'default', '401', 'Furnizori', '{}'::jsonb, 'liability_payable', true, '40', 720),
  ('RO', 'default', '403', 'Efecte de plătit', '{}'::jsonb, 'liability_payable', true, '40', 730),
  ('RO', 'default', '404', 'Furnizori de imobilizări', '{}'::jsonb, 'liability_payable', true, '40', 740),
  ('RO', 'default', '408', 'Furnizori — facturi nesosite', '{}'::jsonb, 'liability_payable', true, '40', 750),
  ('RO', 'default', '409', 'Furnizori-debitori', '{}'::jsonb, 'asset_current', false, '40', 760),
  ('RO', 'default', '41', 'Clienți și conturi asimilate', '{}'::jsonb, 'asset_receivable', true, null, 770),
  ('RO', 'default', '411', 'Clienți', '{}'::jsonb, 'asset_receivable', true, '41', 780),
  ('RO', 'default', '4111', 'Clienți', '{}'::jsonb, 'asset_receivable', true, '411', 790),
  ('RO', 'default', '4118', 'Clienți incerți sau în litigiu', '{}'::jsonb, 'asset_receivable', true, '411', 800),
  ('RO', 'default', '413', 'Efecte de primit de la clienți', '{}'::jsonb, 'asset_receivable', true, '41', 810),
  ('RO', 'default', '418', 'Clienți — facturi de întocmit', '{}'::jsonb, 'asset_receivable', true, '41', 820),
  ('RO', 'default', '419', 'Clienți-creditori', '{}'::jsonb, 'liability_current', false, '41', 830),
  ('RO', 'default', '42', 'Personal și conturi asimilate', '{}'::jsonb, 'liability_current', false, null, 840),
  ('RO', 'default', '421', 'Personal — salarii datorate', '{}'::jsonb, 'liability_current', false, '42', 850),
  ('RO', 'default', '423', 'Personal — ajutoare materiale datorate', '{}'::jsonb, 'liability_current', false, '42', 860),
  ('RO', 'default', '424', 'Prime reprezentând participarea personalului la profit', '{}'::jsonb, 'liability_current', false, '42', 870),
  ('RO', 'default', '425', 'Avansuri acordate personalului', '{}'::jsonb, 'asset_current', false, '42', 880),
  ('RO', 'default', '427', 'Rețineri din salarii datorate terților', '{}'::jsonb, 'liability_current', false, '42', 890),
  ('RO', 'default', '428', 'Alte datorii și creanțe în legătură cu personalul', '{}'::jsonb, 'liability_current', false, '42', 900),
  ('RO', 'default', '43', 'Asigurări sociale, protecția socială și conturi asimilate', '{}'::jsonb, 'liability_current', false, null, 910),
  ('RO', 'default', '431', 'Asigurări sociale', '{}'::jsonb, 'liability_current', false, '43', 920),
  ('RO', 'default', '437', 'Ajutor de șomaj', '{}'::jsonb, 'liability_current', false, '43', 930),
  ('RO', 'default', '438', 'Alte datorii și creanțe sociale', '{}'::jsonb, 'liability_current', false, '43', 940),
  ('RO', 'default', '44', 'Bugetul statului, fonduri speciale și conturi asimilate', '{}'::jsonb, 'liability_current', false, null, 950),
  ('RO', 'default', '441', 'Impozitul pe profit/venit', '{}'::jsonb, 'liability_current', false, '44', 960),
  ('RO', 'default', '442', 'Taxa pe valoarea adăugată', '{}'::jsonb, 'liability_current', false, '44', 970),
  ('RO', 'default', '4423', 'TVA de plată', '{}'::jsonb, 'liability_current', true, '442', 980),
  ('RO', 'default', '4424', 'TVA de recuperat', '{}'::jsonb, 'asset_current', true, '442', 990),
  ('RO', 'default', '4426', 'TVA deductibilă', '{}'::jsonb, 'asset_current', true, '442', 1000),
  ('RO', 'default', '4427', 'TVA colectată', '{}'::jsonb, 'liability_current', true, '442', 1010),
  ('RO', 'default', '4428', 'TVA neexigibilă', '{}'::jsonb, 'liability_current', false, '442', 1020),
  ('RO', 'default', '444', 'Impozitul pe venituri de natura salariilor', '{}'::jsonb, 'liability_current', false, '44', 1030),
  ('RO', 'default', '446', 'Alte impozite, taxe și vărsăminte asimilate', '{}'::jsonb, 'liability_current', false, '44', 1040),
  ('RO', 'default', '447', 'Fonduri speciale — taxe și vărsăminte asimilate', '{}'::jsonb, 'liability_current', false, '44', 1050),
  ('RO', 'default', '45', 'Grup și acționari/asociați', '{}'::jsonb, 'liability_current', false, null, 1060),
  ('RO', 'default', '451', 'Decontări în cadrul grupului', '{}'::jsonb, 'liability_current', true, '45', 1070),
  ('RO', 'default', '455', 'Sume datorate acționarilor/asociaților', '{}'::jsonb, 'liability_current', true, '45', 1080),
  ('RO', 'default', '456', 'Decontări cu acționarii/asociații privind capitalul', '{}'::jsonb, 'liability_current', false, '45', 1090),
  ('RO', 'default', '457', 'Dividende de plată', '{}'::jsonb, 'liability_current', false, '45', 1100),
  ('RO', 'default', '46', 'Debitori și creditori diverși', '{}'::jsonb, 'asset_current', false, null, 1110),
  ('RO', 'default', '461', 'Debitori diverși', '{}'::jsonb, 'asset_current', true, '46', 1120),
  ('RO', 'default', '462', 'Creditori diverși', '{}'::jsonb, 'liability_current', true, '46', 1130),
  ('RO', 'default', '47', 'Conturi de regularizare și asimilate', '{}'::jsonb, 'asset_prepayments', false, null, 1140),
  ('RO', 'default', '471', 'Cheltuieli înregistrate în avans', '{}'::jsonb, 'asset_prepayments', false, '47', 1150),
  ('RO', 'default', '472', 'Venituri înregistrate în avans', '{}'::jsonb, 'liability_current', false, '47', 1160),
  ('RO', 'default', '473', 'Decontări din operații în curs de clarificare', '{}'::jsonb, 'liability_current', true, '47', 1170),
  ('RO', 'default', '49', 'Ajustări pentru deprecierea creanțelor', '{}'::jsonb, 'asset_current', false, null, 1180),
  ('RO', 'default', '491', 'Ajustări pentru deprecierea creanțelor — clienți', '{}'::jsonb, 'asset_current', false, '49', 1190),
  ('RO', 'default', '50', 'Investiții pe termen scurt', '{}'::jsonb, 'asset_current', false, null, 1200),
  ('RO', 'default', '508', 'Alte investiții pe termen scurt și creanțe asimilate', '{}'::jsonb, 'asset_current', false, '50', 1210),
  ('RO', 'default', '51', 'Conturi la bănci', '{}'::jsonb, 'asset_cash', false, null, 1220),
  ('RO', 'default', '512', 'Conturi curente la bănci', '{}'::jsonb, 'asset_cash', false, '51', 1230),
  ('RO', 'default', '5121', 'Conturi la bănci în lei', '{}'::jsonb, 'asset_cash', false, '512', 1240),
  ('RO', 'default', '5124', 'Conturi la bănci în valută', '{}'::jsonb, 'asset_cash', false, '512', 1250),
  ('RO', 'default', '519', 'Credite bancare pe termen scurt', '{}'::jsonb, 'liability_current', false, '51', 1260),
  ('RO', 'default', '53', 'Casa', '{}'::jsonb, 'asset_cash', false, null, 1270),
  ('RO', 'default', '531', 'Casa', '{}'::jsonb, 'asset_cash', false, '53', 1280),
  ('RO', 'default', '5311', 'Casa în lei', '{}'::jsonb, 'asset_cash', false, '531', 1290),
  ('RO', 'default', '5314', 'Casa în valută', '{}'::jsonb, 'asset_cash', false, '531', 1300),
  ('RO', 'default', '54', 'Acreditive', '{}'::jsonb, 'asset_current', false, null, 1310),
  ('RO', 'default', '541', 'Acreditive', '{}'::jsonb, 'asset_current', false, '54', 1320),
  ('RO', 'default', '542', 'Avansuri de trezorerie', '{}'::jsonb, 'asset_current', false, '54', 1330),
  ('RO', 'default', '58', 'Viramente interne', '{}'::jsonb, 'asset_current', false, null, 1340),
  ('RO', 'default', '581', 'Viramente interne', '{}'::jsonb, 'asset_current', false, '58', 1350),
  ('RO', 'default', '60', 'Cheltuieli privind stocurile', '{}'::jsonb, 'expense_direct_cost', false, null, 1360),
  ('RO', 'default', '601', 'Cheltuieli cu materiile prime', '{}'::jsonb, 'expense_direct_cost', false, '60', 1370),
  ('RO', 'default', '602', 'Cheltuieli cu materialele consumabile', '{}'::jsonb, 'expense_direct_cost', false, '60', 1380),
  ('RO', 'default', '603', 'Cheltuieli privind materialele de natura obiectelor de inventar', '{}'::jsonb, 'expense_direct_cost', false, '60', 1390),
  ('RO', 'default', '605', 'Cheltuieli privind energia și apa', '{}'::jsonb, 'expense_direct_cost', false, '60', 1400),
  ('RO', 'default', '607', 'Cheltuieli privind mărfurile', '{}'::jsonb, 'expense_direct_cost', false, '60', 1410),
  ('RO', 'default', '608', 'Cheltuieli privind ambalajele', '{}'::jsonb, 'expense_direct_cost', false, '60', 1420),
  ('RO', 'default', '609', 'Reduceri comerciale primite', '{}'::jsonb, 'expense_direct_cost', false, '60', 1430),
  ('RO', 'default', '61', 'Cheltuieli cu lucrările și serviciile executate de terți', '{}'::jsonb, 'expense', false, null, 1440),
  ('RO', 'default', '611', 'Cheltuieli cu întreținerea și reparațiile', '{}'::jsonb, 'expense', false, '61', 1450),
  ('RO', 'default', '612', 'Cheltuieli cu redevențele, locațiile de gestiune și chiriile', '{}'::jsonb, 'expense', false, '61', 1460),
  ('RO', 'default', '613', 'Cheltuieli cu primele de asigurare', '{}'::jsonb, 'expense', false, '61', 1470),
  ('RO', 'default', '614', 'Cheltuieli cu studiile și cercetările', '{}'::jsonb, 'expense', false, '61', 1480),
  ('RO', 'default', '62', 'Cheltuieli cu alte servicii executate de terți', '{}'::jsonb, 'expense', false, null, 1490),
  ('RO', 'default', '621', 'Cheltuieli cu colaboratorii', '{}'::jsonb, 'expense', false, '62', 1500),
  ('RO', 'default', '622', 'Cheltuieli privind comisioanele și onorariile', '{}'::jsonb, 'expense', false, '62', 1510),
  ('RO', 'default', '623', 'Cheltuieli de protocol, reclamă și publicitate', '{}'::jsonb, 'expense', false, '62', 1520),
  ('RO', 'default', '624', 'Cheltuieli cu transportul de bunuri și de personal', '{}'::jsonb, 'expense', false, '62', 1530),
  ('RO', 'default', '625', 'Cheltuieli cu deplasări, detașări și transferări', '{}'::jsonb, 'expense', false, '62', 1540),
  ('RO', 'default', '626', 'Cheltuieli poștale și taxe de telecomunicații', '{}'::jsonb, 'expense', false, '62', 1550),
  ('RO', 'default', '627', 'Cheltuieli cu serviciile bancare și asimilate', '{}'::jsonb, 'expense', false, '62', 1560),
  ('RO', 'default', '628', 'Alte cheltuieli cu serviciile executate de terți', '{}'::jsonb, 'expense', false, '62', 1570),
  ('RO', 'default', '63', 'Cheltuieli cu alte impozite, taxe și vărsăminte asimilate', '{}'::jsonb, 'expense', false, null, 1580),
  ('RO', 'default', '635', 'Cheltuieli cu alte impozite, taxe și vărsăminte asimilate', '{}'::jsonb, 'expense', false, '63', 1590),
  ('RO', 'default', '64', 'Cheltuieli cu personalul', '{}'::jsonb, 'expense', false, null, 1600),
  ('RO', 'default', '641', 'Cheltuieli cu salariile personalului', '{}'::jsonb, 'expense', false, '64', 1610),
  ('RO', 'default', '645', 'Cheltuieli privind asigurările și protecția socială', '{}'::jsonb, 'expense', false, '64', 1620),
  ('RO', 'default', '646', 'Cheltuieli privind contribuția asiguratorie pentru muncă', '{}'::jsonb, 'expense', false, '64', 1630),
  ('RO', 'default', '65', 'Alte cheltuieli de exploatare', '{}'::jsonb, 'expense', false, null, 1640),
  ('RO', 'default', '654', 'Pierderi din creanțe și debitori diverși', '{}'::jsonb, 'expense', false, '65', 1650),
  ('RO', 'default', '658', 'Alte cheltuieli de exploatare', '{}'::jsonb, 'expense', false, '65', 1660),
  ('RO', 'default', '6588', 'Alte cheltuieli de exploatare diverse', '{}'::jsonb, 'expense', false, '658', 1670),
  ('RO', 'default', '66', 'Cheltuieli financiare', '{}'::jsonb, 'expense', false, null, 1680),
  ('RO', 'default', '663', 'Cheltuieli privind investițiile financiare cedate', '{}'::jsonb, 'expense', false, '66', 1690),
  ('RO', 'default', '665', 'Cheltuieli din diferențe de curs valutar', '{}'::jsonb, 'expense', false, '66', 1700),
  ('RO', 'default', '666', 'Cheltuieli privind dobânzile', '{}'::jsonb, 'expense', false, '66', 1710),
  ('RO', 'default', '667', 'Cheltuieli privind sconturile acordate', '{}'::jsonb, 'expense', false, '66', 1720),
  ('RO', 'default', '668', 'Alte cheltuieli financiare', '{}'::jsonb, 'expense', false, '66', 1730),
  ('RO', 'default', '68', 'Cheltuieli cu amortizările, provizioanele și ajustările pentru depreciere', '{}'::jsonb, 'expense_depreciation', false, null, 1740),
  ('RO', 'default', '681', 'Cheltuieli de exploatare privind amortizările, provizioanele și ajustările pentru depreciere', '{}'::jsonb, 'expense_depreciation', false, '68', 1750),
  ('RO', 'default', '686', 'Cheltuieli financiare privind ajustările pentru pierdere de valoare', '{}'::jsonb, 'expense', false, '68', 1760),
  ('RO', 'default', '69', 'Cheltuieli cu impozitul pe profit și alte impozite', '{}'::jsonb, 'expense', false, null, 1770),
  ('RO', 'default', '691', 'Cheltuieli cu impozitul pe profit', '{}'::jsonb, 'expense', false, '69', 1780),
  ('RO', 'default', '698', 'Cheltuieli cu impozitul pe venit și cu alte impozite', '{}'::jsonb, 'expense', false, '69', 1790),
  ('RO', 'default', '70', 'Cifra de afaceri netă', '{}'::jsonb, 'income', false, null, 1800),
  ('RO', 'default', '701', 'Venituri din vânzarea produselor finite', '{}'::jsonb, 'income', false, '70', 1810),
  ('RO', 'default', '704', 'Venituri din lucrări executate și servicii prestate', '{}'::jsonb, 'income', false, '70', 1820),
  ('RO', 'default', '707', 'Venituri din vânzarea mărfurilor', '{}'::jsonb, 'income', false, '70', 1830),
  ('RO', 'default', '709', 'Reduceri comerciale acordate', '{}'::jsonb, 'income', false, '70', 1840),
  ('RO', 'default', '71', 'Venituri aferente costului producției în curs de execuție', '{}'::jsonb, 'income', false, null, 1850),
  ('RO', 'default', '711', 'Venituri aferente costurilor stocurilor de produse', '{}'::jsonb, 'income', false, '71', 1860),
  ('RO', 'default', '712', 'Venituri aferente costurilor serviciilor în curs de execuție', '{}'::jsonb, 'income', false, '71', 1870),
  ('RO', 'default', '74', 'Venituri din subvenții de exploatare', '{}'::jsonb, 'income_other', false, null, 1880),
  ('RO', 'default', '741', 'Venituri din subvenții de exploatare', '{}'::jsonb, 'income_other', false, '74', 1890),
  ('RO', 'default', '75', 'Alte venituri din exploatare', '{}'::jsonb, 'income_other', false, null, 1900),
  ('RO', 'default', '758', 'Alte venituri din exploatare', '{}'::jsonb, 'income_other', false, '75', 1910),
  ('RO', 'default', '76', 'Venituri financiare', '{}'::jsonb, 'income_other', false, null, 1920),
  ('RO', 'default', '761', 'Venituri din imobilizări financiare cedate', '{}'::jsonb, 'income_other', false, '76', 1930),
  ('RO', 'default', '765', 'Venituri din diferențe de curs valutar', '{}'::jsonb, 'income_other', false, '76', 1940),
  ('RO', 'default', '766', 'Venituri din dobânzi', '{}'::jsonb, 'income_other', false, '76', 1950),
  ('RO', 'default', '767', 'Venituri din sconturi obținute', '{}'::jsonb, 'income_other', false, '76', 1960),
  ('RO', 'default', '768', 'Alte venituri financiare', '{}'::jsonb, 'income_other', false, '76', 1970),
  ('RO', 'default', '78', 'Venituri din provizioane și ajustări pentru depreciere sau pierdere de valoare', '{}'::jsonb, 'income_other', false, null, 1980),
  ('RO', 'default', '781', 'Venituri din provizioane și ajustări pentru depreciere privind exploatarea', '{}'::jsonb, 'income_other', false, '78', 1990)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('RO', 'BNC', 'Jurnal de bancă', '{}'::jsonb, 'bank', 30),
  ('RO', 'CAS', 'Jurnal de casă', '{}'::jsonb, 'cash', 40),
  ('RO', 'CMP', 'Jurnal de cumpărări', '{}'::jsonb, 'purchase', 20),
  ('RO', 'DES', 'Notă de deschidere', '{}'::jsonb, 'opening', 60),
  ('RO', 'DIV', 'Operațiuni diverse', '{}'::jsonb, 'general', 50),
  ('RO', 'VNZ', 'Jurnal de vânzări', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('RO', 'RO-P-11', 'Achiziții — cota redusă 11%', '{}'::jsonb, null, 'percent', 11, 'purchase', 'domestic', date '2025-08-01', null, 'Codul fiscal, art. 291 alin. (2), astfel cum a fost modificat de art. II pct. 42 din Legea nr. 141/2025 — cota redusă de 11%; art. 297 și art. 298 — dreptul de deducere.', null, null, 90, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'legea-141-2025', null, null, null, null),
  ('RO', 'RO-P-21', 'Achiziții — cota standard 21%', '{}'::jsonb, null, 'percent', 21, 'purchase', 'domestic', date '2025-08-01', null, 'Codul fiscal, art. 291 alin. (1), astfel cum a fost modificat de art. II pct. 42 din Legea nr. 141/2025 — cota standard de 21%; art. 297 și art. 298 — dreptul de deducere a taxei aferente achizițiilor destinate operațiunilor taxabile.', null, null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'legea-141-2025', null, null, null, null),
  ('RO', 'RO-P-EXT-21', 'Achiziție de servicii de la un prestator din afara Uniunii — taxare inversă 21%', '{}'::jsonb, null, 'percent', 21, 'purchase', 'foreign_services_received', date '2025-08-01', null, 'Codul fiscal, art. 278 alin. (2) și art. 307 alin. (2) — regula generală B2B plasează prestarea la sediul beneficiarului stabilit în România, indiferent dacă prestatorul este stabilit în Uniune sau în afara ei; beneficiarul este obligat la plata taxei prin taxare inversă. Formularul 300 nu separă cele două cazuri: rd. 7/22 le cuprinde pe amândouă, ca și rândul VJ3 al modelului italian descris în docs/packs.md.', null, null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('RO', 'RO-P-ICG-21', 'Achiziție intracomunitară de bunuri — taxare inversă 21%', '{}'::jsonb, null, 'percent', 21, 'purchase', 'intracom_acquisition_goods', date '2025-08-01', null, 'Codul fiscal, art. 273 — achiziția intracomunitară de bunuri este operațiune impozabilă; art. 308 — cumpărătorul înregistrat în scopuri de TVA colectează taxa prin taxare inversă, o înscrie atât ca taxă colectată (rd. 5 din formularul 300), cât și, în măsura dreptului de deducere, ca taxă deductibilă (rd. 20) — o singură bază, reluată în cele două rânduri, exact ca la achiziția intracomunitară estoniană din docs/packs.md.', 'K', 'VATEX-EU-IC', 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('RO', 'RO-P-ICS-21', 'Achiziție de servicii intracomunitare — taxare inversă 21%', '{}'::jsonb, null, 'percent', 21, 'purchase', 'intracom_acquisition_services', date '2025-08-01', null, 'Codul fiscal, art. 278 alin. (2) și art. 307 alin. (2) — beneficiarul stabilit în România al unui serviciu generic prestat de o persoană impozabilă stabilită în alt stat membru este obligat la plata taxei prin taxare inversă. Formularul 300 nu rezervă rd. 7/22 exclusiv serviciilor intracomunitare: același rând cuprinde și achizițiile de bunuri și servicii de la persoane neînregistrate în România, altele decât cele de la rd. 5/20 — a se vedea RO-P-EXT-21.', 'K', 'VATEX-EU-IC', 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('RO', 'RO-P-IMPORT-21', 'Import de bunuri — cota standard 21%', '{}'::jsonb, null, 'percent', 21, 'purchase', 'import', date '2025-08-01', null, 'Codul fiscal, art. 291 alin. (1); art. 326 — taxa datorată pentru importul de bunuri se stabilește prin declarația vamală. Instrucțiunile formularului 300 nu rezervă un rând distinct importurilor: rd. 24 cuprinde « baza de impozitare și taxa aferentă importurilor care nu se încadrează în prevederile art. 326 alin. (4) și (5) », alături de achizițiile interne cu cota de 21%. Regimul de amânare a plății TVA la import (art. 326 alin. (4)-(5), «taxare prin decontul de taxă», des utilizat de importatorii înregistrați) rămâne nemodelat: formularul însuși îl exclude din rd. 24/25 fără să-i rezerve un alt rând — a se vedea secțiunea «From Romania» din docs/international.md.', null, null, 100, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'd300-formular', null, null, null, null),
  ('RO', 'RO-S-11', 'Vânzări — cota redusă 11%', '{}'::jsonb, null, 'percent', 11, 'sale', 'domestic', date '2025-08-01', null, 'Codul fiscal, art. 291 alin. (2), astfel cum a fost modificat de art. II pct. 42 din Legea nr. 141/2025 — cota redusă unică de 11%, care înlocuiește de la 1 august 2025 cele două cote reduse anterioare de 9% și 5%, pentru: medicamente de uz uman; alimente și băuturi destinate consumului uman și animal (cu excepția băuturilor alcoolice, a celor de la codul NC 2202 și a produselor cu peste 10 g zahăr/100 g, altele decât laptele praf pentru nou-născuți); apă și canalizare; îngrășăminte și pesticide de uz agricol; manuale școlare, cărți, ziare și reviste; acces la castele, muzee, monumente, grădini zoologice și botanice; lemn de foc și peleți; energie termică furnizată populației și anumitor instituții în sezonul rece (1 noiembrie — 31 martie); locuințe ca parte a politicii sociale; cazare hotelieră; servicii de restaurant și catering (cu aceleași excepții privind băuturile).', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'legea-141-2025', null, null, null, null),
  ('RO', 'RO-S-21', 'Vânzări — cota standard 21%', '{}'::jsonb, null, 'percent', 21, 'sale', 'domestic', date '2025-08-01', null, 'Codul fiscal, art. 291 alin. (1), astfel cum a fost modificat de art. II pct. 42 din Legea nr. 141/2025 — cota standard de 21%, aplicabilă de la 1 august 2025 (anterior 19%, de la 1 ianuarie 2017).', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'legea-141-2025', null, null, null, null),
  ('RO', 'RO-S-EXE', 'Operațiuni financiare scutite — dobânzi pentru credite acordate', '{}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2007-01-01', null, 'Codul fiscal, art. 292 alin. (2) lit. a) pct. 1 — scutirea fără drept de deducere pentru acordarea și negocierea de credite, precum și gestiunea creditelor de către persoana care le acordă, inclusiv dobânzile aferente, transpunând art. 135 alin. (1) lit. b) din Directiva 2006/112/CE. Codul VATEX-EU-135 este un cod generic pentru articolul 135; alegerea sa aici, în locul unui cod mai specific dacă lista VATEX ar publica unul, este de reconfirmat de un contabil.', 'E', 'VATEX-EU-135', 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('RO', 'RO-S-EXPORT', 'Export de bunuri — scutit cu drept de deducere', '{}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2016-01-01', null, 'Codul fiscal, art. 294 alin. (1) lit. a) — scutire cu drept de deducere pentru livrarea de bunuri expediate sau transportate în afara Uniunii Europene de către furnizor sau de altă persoană în contul acestuia. Rândul formularului 300 nu numește explicit exportul: acest pachet îl declară la rd. 14 « Livrări de bunuri și prestări de servicii scutite cu drept de deducere, altele decât cele de la rd. 1-3 », singurul rând rămas pentru o scutire cu drept de deducere care nu este nici o livrare intracomunitară (rd. 1), nici o operațiune al cărei loc de livrare este în afara României (rd. 3) — o lectură a formularului și nu o casetă dedicată exportului, de reverificat de un contabil.', 'G', 'VATEX-EU-G', 30, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'd300-formular', null, null, null, null),
  ('RO', 'RO-S-ICG', 'Livrare intracomunitară de bunuri — scutită', '{}'::jsonb, null, 'percent', 0, 'sale', 'intracom_goods', date '2007-01-01', null, 'Codul fiscal, art. 294 alin. (2) lit. a) — scutire cu drept de deducere pentru livrarea intracomunitară de bunuri către o persoană care îi comunică furnizorului un cod valabil de înregistrare în scopuri de TVA dintr-un alt stat membru, transpunând art. 138 din Directiva 2006/112/CE.', 'K', 'VATEX-EU-IC', 40, 'vat', true, array['transport_evidence', 'buyer_status']::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('RO', 'RO-S-ICS', 'Prestare de servicii intracomunitară — neimpozabilă în România', '{}'::jsonb, null, 'percent', 0, 'sale', 'intracom_services', date '2010-01-01', null, 'Codul fiscal, art. 278 alin. (2) — locul prestării unui serviciu generic către o persoană impozabilă este locul unde beneficiarul este stabilit; taxa se datorează, prin taxare inversă, de beneficiarul stabilit în alt stat membru (art. 44 și 196 din Directiva 2006/112/CE).', 'K', 'VATEX-EU-IC', 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null),
  ('RO', 'RO-S-RC-331', 'Livrare supusă taxării inverse — măsuri de simplificare', '{}'::jsonb, null, 'percent', 0, 'sale', 'domestic_reverse_charge', date '2016-01-01', null, 'Codul fiscal, art. 331 alin. (2) — printre bunurile și serviciile supuse măsurilor de simplificare (taxare inversă) se numără cerealele și plantele tehnice, potrivit casetei « livrare de cereale și plante tehnice » a formularului 300; taxa este datorată de beneficiar, care o înregistrează în decontul propriu, iar factura se emite fără TVA, cu mențiunea « taxare inversă ».', 'AE', 'VATEX-EU-AE', 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'codul-fiscal', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('RO-P-11', 'invoice', 'base', 100, null, '25', array['25']::text[], 100, 'RO-D300', 10),
    ('RO-P-11', 'invoice', 'tax', 100, '4426', '25', array['25']::text[], 100, 'RO-D300', 20),
    ('RO-P-11', 'credit_note', 'base', 100, null, '25', array['25']::text[], -100, 'RO-D300', 10),
    ('RO-P-11', 'credit_note', 'tax', 100, '4426', '25', array['25']::text[], -100, 'RO-D300', 20),
    ('RO-P-21', 'invoice', 'base', 100, null, '24', array['24']::text[], 100, 'RO-D300', 10),
    ('RO-P-21', 'invoice', 'tax', 100, '4426', '24', array['24']::text[], 100, 'RO-D300', 20),
    ('RO-P-21', 'credit_note', 'base', 100, null, '24', array['24']::text[], -100, 'RO-D300', 10),
    ('RO-P-21', 'credit_note', 'tax', 100, '4426', '24', array['24']::text[], -100, 'RO-D300', 20),
    ('RO-P-EXT-21', 'invoice', 'base', 100, null, '7', array['7', '22']::text[], 100, 'RO-D300', 10),
    ('RO-P-EXT-21', 'invoice', 'tax', 100, '4427', '7', array['7']::text[], 100, 'RO-D300', 20),
    ('RO-P-EXT-21', 'invoice', 'tax', -100, '4426', '22', array['22']::text[], 100, 'RO-D300', 30),
    ('RO-P-EXT-21', 'credit_note', 'base', 100, null, '7', array['7', '22']::text[], -100, 'RO-D300', 10),
    ('RO-P-EXT-21', 'credit_note', 'tax', 100, '4427', '7', array['7']::text[], -100, 'RO-D300', 20),
    ('RO-P-EXT-21', 'credit_note', 'tax', -100, '4426', '22', array['22']::text[], -100, 'RO-D300', 30),
    ('RO-P-ICG-21', 'invoice', 'base', 100, null, '5', array['5', '20']::text[], 100, 'RO-D300', 10),
    ('RO-P-ICG-21', 'invoice', 'tax', 100, '4427', '5', array['5']::text[], 100, 'RO-D300', 20),
    ('RO-P-ICG-21', 'invoice', 'tax', -100, '4426', '20', array['20']::text[], 100, 'RO-D300', 30),
    ('RO-P-ICG-21', 'credit_note', 'base', 100, null, '5', array['5', '20']::text[], -100, 'RO-D300', 10),
    ('RO-P-ICG-21', 'credit_note', 'tax', 100, '4427', '5', array['5']::text[], -100, 'RO-D300', 20),
    ('RO-P-ICG-21', 'credit_note', 'tax', -100, '4426', '20', array['20']::text[], -100, 'RO-D300', 30),
    ('RO-P-ICS-21', 'invoice', 'base', 100, null, '7', array['7', '22']::text[], 100, 'RO-D300', 10),
    ('RO-P-ICS-21', 'invoice', 'tax', 100, '4427', '7', array['7']::text[], 100, 'RO-D300', 20),
    ('RO-P-ICS-21', 'invoice', 'tax', -100, '4426', '22', array['22']::text[], 100, 'RO-D300', 30),
    ('RO-P-ICS-21', 'credit_note', 'base', 100, null, '7', array['7', '22']::text[], -100, 'RO-D300', 10),
    ('RO-P-ICS-21', 'credit_note', 'tax', 100, '4427', '7', array['7']::text[], -100, 'RO-D300', 20),
    ('RO-P-ICS-21', 'credit_note', 'tax', -100, '4426', '22', array['22']::text[], -100, 'RO-D300', 30),
    ('RO-P-IMPORT-21', 'invoice', 'base', 100, null, '24', array['24']::text[], 100, 'RO-D300', 10),
    ('RO-P-IMPORT-21', 'invoice', 'tax', 100, '4426', '24', array['24']::text[], 100, 'RO-D300', 20),
    ('RO-P-IMPORT-21', 'credit_note', 'base', 100, null, '24', array['24']::text[], -100, 'RO-D300', 10),
    ('RO-P-IMPORT-21', 'credit_note', 'tax', 100, '4426', '24', array['24']::text[], -100, 'RO-D300', 20),
    ('RO-S-11', 'invoice', 'base', 100, null, '10', array['10']::text[], 100, 'RO-D300', 10),
    ('RO-S-11', 'invoice', 'tax', 100, '4427', '10', array['10']::text[], 100, 'RO-D300', 20),
    ('RO-S-11', 'credit_note', 'base', 100, null, '10', array['10']::text[], -100, 'RO-D300', 10),
    ('RO-S-11', 'credit_note', 'tax', 100, '4427', '10', array['10']::text[], -100, 'RO-D300', 20),
    ('RO-S-21', 'invoice', 'base', 100, null, '9', array['9']::text[], 100, 'RO-D300', 10),
    ('RO-S-21', 'invoice', 'tax', 100, '4427', '9', array['9']::text[], 100, 'RO-D300', 20),
    ('RO-S-21', 'credit_note', 'base', 100, null, '9', array['9']::text[], -100, 'RO-D300', 10),
    ('RO-S-21', 'credit_note', 'tax', 100, '4427', '9', array['9']::text[], -100, 'RO-D300', 20),
    ('RO-S-EXE', 'invoice', 'base', 100, null, '15', array['15']::text[], 100, 'RO-D300', 10),
    ('RO-S-EXE', 'credit_note', 'base', 100, null, '15', array['15']::text[], -100, 'RO-D300', 10),
    ('RO-S-EXPORT', 'invoice', 'base', 100, null, '14', array['14']::text[], 100, 'RO-D300', 10),
    ('RO-S-EXPORT', 'credit_note', 'base', 100, null, '14', array['14']::text[], -100, 'RO-D300', 10),
    ('RO-S-ICG', 'invoice', 'base', 100, null, '1', array['1']::text[], 100, 'RO-D300', 10),
    ('RO-S-ICG', 'credit_note', 'base', 100, null, '1', array['1']::text[], -100, 'RO-D300', 10),
    ('RO-S-ICS', 'invoice', 'base', 100, null, '3', array['3']::text[], 100, 'RO-D300', 10),
    ('RO-S-ICS', 'credit_note', 'base', 100, null, '3', array['3']::text[], -100, 'RO-D300', 10),
    ('RO-S-RC-331', 'invoice', 'base', 100, null, '13', array['13']::text[], 100, 'RO-D300', 10),
    ('RO-S-RC-331', 'credit_note', 'base', 100, null, '13', array['13']::text[], -100, 'RO-D300', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'RO' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('RO', 'RO-D300', 'Decont de taxă pe valoarea adăugată (formularul 300)', array['month', 'quarter']::declaration_period[], 'month'::declaration_period, date '2026-01-01', null, 'Ordinul președintelui ANAF nr. 174/2026, anexele 1-2 — modelul și instrucțiunile de completare ale formularului (300), aplicabile începând cu declararea obligațiilor fiscale aferente primei perioade fiscale a anului 2026. Acest pachet transcrie rândurile pe care taxele sale le declară și cele patru totaluri finale (19, 30, 31, 35, 36, 37, 44, 45); rândurile de regularizări (2, 4, 6, 8, 16, 18, 21, 23, 28, 33, 34), cele exclusiv informative (3.1, 5.1, 7.1, 12.1, 12.2, 20.1, 22.1, 26.1, 26.2, 29.1) și reportul soldurilor între perioade (rd. 38, 39, 41, 42) nu sunt reluate — a se vedea README.md și secțiunea «From Romania» din docs/international.md.', true,'day_of_month_after_period'::filing_deadline_rule, 25, null, 'Codul fiscal, art. 323 alin. (1) — decontul de taxă se depune până la data de 25 inclusiv a lunii următoare celei în care se încheie perioada fiscală.', 'codul-fiscal', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('RO', 'RO-D300', '1', 'base', 'Livrări intracomunitare de bunuri, scutite conform art. 294 alin. (2) lit. a) și d) din Codul fiscal', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 1.', 'd300-formular'),
  ('RO', 'RO-D300', '3', 'base', 'Livrări de bunuri sau prestări de servicii pentru care locul livrării/prestării este în afara României, precum și livrări intracomunitare scutite conform art. 294 alin. (2) lit. b) și c) din Codul fiscal', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 3.', 'd300-formular'),
  ('RO', 'RO-D300', '5', 'base', 'Achiziții intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă)', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 5.', 'd300-formular'),
  ('RO', 'RO-D300', '5', 'tax', 'Taxa aferentă achizițiilor intracomunitare de bunuri de la rd. 5', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 5, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '7', 'base', 'Achiziții de bunuri, altele decât cele de la rd. 5, și achiziții de servicii pentru care beneficiarul din România este obligat la plata TVA (taxare inversă)', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 7.', 'd300-formular'),
  ('RO', 'RO-D300', '7', 'tax', 'Taxa aferentă achizițiilor de la rd. 7', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 7, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '9', 'base', 'Livrări de bunuri și prestări de servicii, taxabile cu cota de 21%', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 9.', 'd300-formular'),
  ('RO', 'RO-D300', '9', 'tax', 'Taxa aferentă livrărilor de la rd. 9', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 9, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '10', 'base', 'Livrări de bunuri și prestări de servicii, taxabile cu cota de 11%', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 10.', 'd300-formular'),
  ('RO', 'RO-D300', '10', 'tax', 'Taxa aferentă livrărilor de la rd. 10', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 10, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '13', 'base', 'Livrări de bunuri și prestări de servicii supuse măsurilor de simplificare (taxare inversă)', '{}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 13 — rând informativ, fără TVA facturată.', 'd300-formular'),
  ('RO', 'RO-D300', '14', 'base', 'Livrări de bunuri și prestări de servicii scutite cu drept de deducere, altele decât cele de la rd. 1-3', '{}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 14.', 'd300-formular'),
  ('RO', 'RO-D300', '15', 'base', 'Livrări de bunuri și prestări de servicii scutite fără drept de deducere', '{}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 15.', 'd300-formular'),
  ('RO', 'RO-D300', '19', 'total', 'TOTAL TAXĂ COLECTATĂ', '{}'::jsonb, 140, null, array['5:tax', '7:tax', '9:tax', '10:tax']::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 19 — suma taxei de la rd. 1 până la rd. 18; acest pachet nu modelează regularizările (rd. 2, 4, 6, 8, 16, 18), care rămân la zero.', 'd300-formular'),
  ('RO', 'RO-D300', '20', 'base', 'Achiziții intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă) — parte deductibilă', '{}'::jsonb, 150, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 20.', 'd300-formular'),
  ('RO', 'RO-D300', '20', 'tax', 'Taxa dedusă aferentă rd. 20', '{}'::jsonb, 160, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 20, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '22', 'base', 'Achiziții de bunuri, altele decât cele de la rd. 20, și achiziții de servicii pentru care beneficiarul din România este obligat la plata TVA (taxare inversă) — parte deductibilă', '{}'::jsonb, 170, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 22.', 'd300-formular'),
  ('RO', 'RO-D300', '22', 'tax', 'Taxa dedusă aferentă rd. 22', '{}'::jsonb, 180, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 22, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '24', 'base', 'Achiziții de bunuri și servicii taxabile cu cota de 21%, altele decât cele de la rd. 27, precum și importuri care nu se încadrează în prevederile art. 326 alin. (4) și (5) din Codul fiscal', '{}'::jsonb, 190, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 24.', 'd300-formular'),
  ('RO', 'RO-D300', '24', 'tax', 'Taxa dedusă aferentă rd. 24', '{}'::jsonb, 200, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 24, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '25', 'base', 'Achiziții de bunuri și servicii, taxabile cu cota de 11%', '{}'::jsonb, 210, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 25.', 'd300-formular'),
  ('RO', 'RO-D300', '25', 'tax', 'Taxa dedusă aferentă rd. 25', '{}'::jsonb, 220, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 25, coloana taxă.', 'd300-formular'),
  ('RO', 'RO-D300', '30', 'total', 'TOTAL TAXĂ DEDUCTIBILĂ', '{}'::jsonb, 230, null, array['20:tax', '22:tax', '24:tax', '25:tax']::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 30 — suma taxei de la rd. 20 până la rd. 28; acest pachet nu modelează compensația în cotă forfetară pentru agricultori (rd. 27, 28) și lasă-le la zero.', 'd300-formular'),
  ('RO', 'RO-D300', '31', 'total', 'Sub-total taxă dedusă conform art. 297 și art. 298 sau art. 300 și art. 298 din Codul fiscal și compensație în cotă forfetară', '{}'::jsonb, 240, null, array['30']::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 31 — restrângerea prin pro rata (art. 300) nu este modelată de acest pachet, care reia integral rd. 30; a se vedea secțiunea «From Romania» din docs/international.md.', 'd300-formular'),
  ('RO', 'RO-D300', '35', 'total', 'TOTAL TAXĂ DEDUSĂ', '{}'::jsonb, 250, null, array['31']::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 35 — rd. 31 + rd. 32 + rd. 33 + rd. 34; rd. 32 (TVA restituită călătorilor străini), rd. 33 (regularizări) și rd. 34 (ajustări pro rata) nu sunt modelate și rămân la zero.', 'd300-formular'),
  ('RO', 'RO-D300', '36', 'total', 'Suma negativă a TVA în perioada de raportare', '{}'::jsonb, 260, null, array['35']::text[], array['19']::text[], null, null, true, false, null, 'Formularul 300, rd. 36 — rd. 35 minus rd. 19.', 'd300-formular'),
  ('RO', 'RO-D300', '37', 'total', 'Taxa de plată în perioada de raportare', '{}'::jsonb, 270, null, array['19']::text[], array['35']::text[], null, null, true, false, null, 'Formularul 300, rd. 37 — rd. 19 minus rd. 35.', 'd300-formular'),
  ('RO', 'RO-D300', '44', 'total', 'Sold TVA de plată la sfârșitul perioadei de raportare', '{}'::jsonb, 280, null, array['37']::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 44 — rd. 37 + rd. 38 + rd. 39, unde rd. 38 (soldul neachitat al perioadei precedente) și rd. 39 (diferențe stabilite de organele fiscale) reportează o valoare din decontul anterior sau dintr-o decizie a organului fiscal ; acest pachet nu ține un asemenea report și le lasă la zero, ca și rd. 39/rd. 62 ale declarației poloneze JPK_V7 documentate în docs/international.md.', 'd300-formular'),
  ('RO', 'RO-D300', '45', 'total', 'Soldul sumei negative de TVA la sfârșitul perioadei de raportare', '{}'::jsonb, 290, null, array['36']::text[], '{}'::text[], null, null, false, false, null, 'Formularul 300, rd. 45 — rd. 43 minus rd. 40, unde rd. 41 (soldul reportat din perioada precedentă pentru care nu s-a solicitat rambursare) și rd. 42 (diferențe negative stabilite de organele de inspecție fiscală) nu sunt modelate și rămân la zero.', 'd300-formular')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('RO-OMFP-BS', 'RO', 'default', 'Bilanț prescurtat', 'balance_sheet', 'RO-OMFP-1802', date '1970-01-01', null, 'Ordinul ministrului finanțelor publice nr. 1.802/2014, pct. 451 și anexa — formatul bilanțului prescurtat, pentru microentitățile și entitățile mici definite la pct. 9-10 din același ordin', 'omfp-1802-2014'),
  ('RO-OMFP-IS', 'RO', 'default', 'Contul de profit și pierdere', 'income_statement', 'RO-OMFP-1802', date '1970-01-01', null, 'Ordinul ministrului finanțelor publice nr. 1.802/2014, pct. 428 și anexa — formatul contului de profit și pierdere (formatul „listă”, preluat din anexa V a Directivei 2013/34/UE)', 'omfp-1802-2014')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('RO-OMFP-BS', 'A', null, 'A. Active imobilizate', '{}'::jsonb, 10, 1, true, array['A.I', 'A.II', 'A.III']::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'A.I', 'A', 'I. Imobilizări necorporale', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'A.II', 'A', 'II. Imobilizări corporale', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'A.III', 'A', 'III. Imobilizări financiare', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'B', null, 'B. Active circulante', '{}'::jsonb, 50, 1, true, array['B.I', 'B.II', 'B.III', 'B.IV']::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'B.I', 'B', 'I. Stocuri', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'B.II', 'B', 'II. Creanțe', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'B.III', 'B', 'III. Investiții pe termen scurt', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'B.IV', 'B', 'IV. Casa și conturi la bănci', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'C', null, 'C. Cheltuieli în avans', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'D', null, 'D. Datorii ce trebuie plătite într-o perioadă de un an', '{}'::jsonb, 110, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'E', null, 'E. Active circulante nete, respectiv datorii curente nete', '{}'::jsonb, 120, 1, true, array['B', 'C']::text[], array['D']::text[], null, null, null),
  ('RO-OMFP-BS', 'F', null, 'F. Total active minus datorii curente', '{}'::jsonb, 130, 1, true, array['A', 'E']::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'G', null, 'G. Datorii ce trebuie plătite într-o perioadă mai mare de un an', '{}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'H', null, 'H. Provizioane', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'I', null, 'I. Venituri în avans', '{}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J', null, 'J. Capital și rezerve', '{}'::jsonb, 170, 1, true, array['J.I', 'J.II', 'J.III', 'J.IV', 'J.V', 'J.VI']::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J.I', 'J', 'I. Capital', '{}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J.II', 'J', 'II. Prime de capital', '{}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J.III', 'J', 'III. Rezerve din reevaluare', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J.IV', 'J', 'IV. Rezerve', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J.V', 'J', 'V. Profitul sau pierderea reportat(ă)', '{}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-BS', 'J.VI', 'J', 'VI. Profitul sau pierderea exercițiului financiar', '{}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '1', null, '1. Cifra de afaceri netă', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '2', null, '2. Variația stocurilor de produse finite și a producției în curs de execuție', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '3', null, '3. Producția realizată de entitate pentru scopurile proprii și capitalizată', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '4', null, '4. Alte venituri din exploatare', '{}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '5a', null, '5.a) Cheltuieli cu materiile prime și materialele consumabile', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '5b', null, '5.b) Alte cheltuieli externe (cu energia și apa)', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '6a', null, '6.a) Cheltuieli cu salariile personalului', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '6b', null, '6.b) Cheltuieli cu asigurările sociale', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '7a', null, '7.a) Ajustări de valoare privind imobilizările corporale și necorporale', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '7b', null, '7.b) Ajustări de valoare privind activele circulante', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '8', null, '8. Alte cheltuieli de exploatare', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '9', null, '9. Venituri din interese de participare', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '10', null, '10. Venituri din alte investiții și împrumuturi care fac parte din activele imobilizate', '{}'::jsonb, 130, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '11', null, '11. Alte dobânzi de încasat și venituri similare', '{}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '12', null, '12. Ajustări de valoare privind imobilizările financiare', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '13', null, '13. Dobânzi de plătit și cheltuieli similare', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '14', null, '14. Impozitul pe profit', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '15', null, '15. Profitul sau pierderea la sfârșitul perioadei de raportare, după impozitare', '{}'::jsonb, 180, 1, true, array['1', '2', '3', '4', '9', '10', '11']::text[], array['5a', '5b', '6a', '6b', '7a', '7b', '8', '12', '13', '14']::text[], null, null, null),
  ('RO-OMFP-IS', '16', null, '16. Alte impozite neprezentate la elementele de mai sus', '{}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('RO-OMFP-IS', '17', null, '17. Profitul sau pierderea exercițiului financiar', '{}'::jsonb, 200, 1, true, array['15']::text[], array['16']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('RO-OMFP-BS', 'A.I', 10, 'code_prefix', '20', null, null, 'any'),
    ('RO-OMFP-BS', 'A.I', 20, 'account_code', '233', null, null, 'any'),
    ('RO-OMFP-BS', 'A.I', 30, 'code_prefix', '280', null, null, 'any'),
    ('RO-OMFP-BS', 'A.II', 10, 'code_prefix', '21', null, null, 'any'),
    ('RO-OMFP-BS', 'A.II', 20, 'account_code', '231', null, null, 'any'),
    ('RO-OMFP-BS', 'A.II', 30, 'account_code', '234', null, null, 'any'),
    ('RO-OMFP-BS', 'A.II', 40, 'code_prefix', '281', null, null, 'any'),
    ('RO-OMFP-BS', 'A.II', 50, 'code_prefix', '291', null, null, 'any'),
    ('RO-OMFP-BS', 'A.III', 10, 'code_prefix', '26', null, null, 'any'),
    ('RO-OMFP-BS', 'B.I', 10, 'code_prefix', '30', null, null, 'any'),
    ('RO-OMFP-BS', 'B.I', 20, 'code_prefix', '33', null, null, 'any'),
    ('RO-OMFP-BS', 'B.I', 30, 'code_prefix', '34', null, null, 'any'),
    ('RO-OMFP-BS', 'B.I', 40, 'code_prefix', '37', null, null, 'any'),
    ('RO-OMFP-BS', 'B.I', 50, 'code_prefix', '38', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 10, 'account_code', '409', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 20, 'code_prefix', '411', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 30, 'account_code', '413', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 40, 'account_code', '418', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 50, 'account_code', '425', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 60, 'account_code', '4424', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 70, 'account_code', '4426', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 80, 'account_code', '461', null, null, 'any'),
    ('RO-OMFP-BS', 'B.II', 90, 'account_code', '491', null, null, 'any'),
    ('RO-OMFP-BS', 'B.III', 10, 'account_code', '508', null, null, 'any'),
    ('RO-OMFP-BS', 'B.IV', 10, 'code_prefix', '512', null, null, 'any'),
    ('RO-OMFP-BS', 'B.IV', 20, 'code_prefix', '531', null, null, 'any'),
    ('RO-OMFP-BS', 'B.IV', 30, 'code_prefix', '54', null, null, 'any'),
    ('RO-OMFP-BS', 'B.IV', 40, 'code_prefix', '58', null, null, 'any'),
    ('RO-OMFP-BS', 'C', 10, 'account_code', '471', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 10, 'account_code', '401', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 20, 'account_code', '403', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 30, 'account_code', '404', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 40, 'account_code', '408', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 50, 'account_code', '419', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 60, 'account_code', '421', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 70, 'account_code', '423', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 80, 'account_code', '424', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 90, 'account_code', '427', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 100, 'account_code', '428', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 110, 'code_prefix', '43', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 120, 'account_code', '441', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 130, 'account_code', '4423', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 140, 'account_code', '4427', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 150, 'account_code', '4428', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 160, 'account_code', '444', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 170, 'account_code', '446', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 180, 'account_code', '447', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 190, 'code_prefix', '45', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 200, 'account_code', '462', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 210, 'account_code', '473', null, null, 'any'),
    ('RO-OMFP-BS', 'D', 220, 'account_code', '519', null, null, 'any'),
    ('RO-OMFP-BS', 'G', 10, 'code_prefix', '16', null, null, 'any'),
    ('RO-OMFP-BS', 'H', 10, 'code_prefix', '15', null, null, 'any'),
    ('RO-OMFP-BS', 'I', 10, 'account_code', '131', null, null, 'any'),
    ('RO-OMFP-BS', 'I', 20, 'account_code', '472', null, null, 'any'),
    ('RO-OMFP-BS', 'J.I', 10, 'account_code', '1012', null, null, 'any'),
    ('RO-OMFP-BS', 'J.II', 10, 'account_code', '1041', null, null, 'any'),
    ('RO-OMFP-BS', 'J.III', 10, 'account_code', '105', null, null, 'any'),
    ('RO-OMFP-BS', 'J.IV', 10, 'code_prefix', '106', null, null, 'any'),
    ('RO-OMFP-BS', 'J.V', 10, 'code_prefix', '117', null, null, 'any'),
    ('RO-OMFP-BS', 'J.VI', 10, 'account_code', '121', null, null, 'any'),
    ('RO-OMFP-BS', 'J.VI', 20, 'account_code', '129', null, null, 'any'),
    ('RO-OMFP-IS', '1', 10, 'code_prefix', '70', null, null, 'any'),
    ('RO-OMFP-IS', '2', 10, 'code_prefix', '71', null, null, 'any'),
    ('RO-OMFP-IS', '4', 10, 'code_prefix', '74', null, null, 'any'),
    ('RO-OMFP-IS', '4', 20, 'code_prefix', '75', null, null, 'any'),
    ('RO-OMFP-IS', '4', 30, 'code_prefix', '78', null, null, 'any'),
    ('RO-OMFP-IS', '5a', 10, 'code_prefix', '60', null, null, 'any'),
    ('RO-OMFP-IS', '5b', 10, 'code_prefix', '61', null, null, 'any'),
    ('RO-OMFP-IS', '5b', 20, 'code_prefix', '62', null, null, 'any'),
    ('RO-OMFP-IS', '5b', 30, 'code_prefix', '63', null, null, 'any'),
    ('RO-OMFP-IS', '6a', 10, 'account_code', '641', null, null, 'any'),
    ('RO-OMFP-IS', '6b', 10, 'account_code', '645', null, null, 'any'),
    ('RO-OMFP-IS', '6b', 20, 'account_code', '646', null, null, 'any'),
    ('RO-OMFP-IS', '7a', 10, 'account_code', '681', null, null, 'any'),
    ('RO-OMFP-IS', '7b', 10, 'account_code', '654', null, null, 'any'),
    ('RO-OMFP-IS', '8', 10, 'code_prefix', '658', null, null, 'any'),
    ('RO-OMFP-IS', '10', 10, 'account_code', '761', null, null, 'any'),
    ('RO-OMFP-IS', '11', 10, 'account_code', '765', null, null, 'any'),
    ('RO-OMFP-IS', '11', 20, 'account_code', '766', null, null, 'any'),
    ('RO-OMFP-IS', '11', 30, 'account_code', '767', null, null, 'any'),
    ('RO-OMFP-IS', '11', 40, 'account_code', '768', null, null, 'any'),
    ('RO-OMFP-IS', '12', 10, 'account_code', '686', null, null, 'any'),
    ('RO-OMFP-IS', '13', 10, 'code_prefix', '66', null, null, 'any'),
    ('RO-OMFP-IS', '14', 10, 'account_code', '691', null, null, 'any'),
    ('RO-OMFP-IS', '16', 10, 'account_code', '698', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('RO', 'Romania', '{}'::jsonb, array['ro']::text[], 'RON', '4111', '401', '473', '6588', '1171', '707', '607', '5121', '5311', 'VNZ', 'CMP', 'DIV', 'ro', 'result_accounts', '121', '121', null, 'DES', 'half_up', default, '765', '665', null, null, null, null, '4423', '4424', 'Notă contabilă de deschidere', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = 30,
  late_payment_reference        = 'Legea nr. 72/2013, art. 3 — dobânda legală penalizatoare curge de plin drept de la data scadenței, fără nicio notificare prealabilă; art. 4 — în lipsa unei dobânzi convenite, se aplică dobânda legală penalizatoare stabilită conform art. 3 din Ordonanța Guvernului nr. 13/2011, la nivelul ratei dobânzii de referință a Băncii Naționale a României în vigoare în prima zi calendaristică a semestrului, majorată cu 8 puncte procentuale.',
  numbering_legal_reference     = 'Codul fiscal, art. 319 alin. (20) lit. a) — factura cuprinde în mod obligatoriu «numărul de ordine, în baza uneia sau a mai multor serii, care identifică factura în mod unic». Legea cere doar un număr secvențial și unic, ca și la art. 106e ust. 1 pkt 2 din legea poloneză a TVA — nici continuitate fără goluri, nici o remitere la zero anuală nu sunt impuse de text; seria anuală (an în număr) este o convenție larg răspândită în practică, posibil precizată doar în Normele metodologice de aplicare (Hotărârea Guvernului nr. 1/2016), text pe care cercetarea acestui pachet nu l-a putut verifica separat.',
  numbering_source_key          = 'codul-fiscal',
  payment_terms_legal_reference = 'Legea nr. 72/2013, art. 3 alin. (1) — dobânda curge după 30 de zile calendaristice de la data primirii facturii sau, dacă data primirii facturii este incertă ori anterioară recepției bunurilor/serviciilor, de la data recepției acestora.',
  payment_terms_source_key      = 'legea-72-2013',
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Codul fiscal, art. 281 alin. (1) — faptul generator intervine la data livrării bunurilor sau la data prestării serviciilor, cu regulile speciale ale alin. (7)-(8) pentru livrări/prestări continue sau cu decontări succesive; art. 282 alin. (1) — exigibilitatea taxei intervine, ca regulă, la data faptului generator; art. 282 alin. (2) lit. a) — derogare: dacă factura este emisă înainte de data faptului generator, exigibilitatea intervine la data emiterii facturii. Nemodelat: art. 282 alin. (2) lit. b) — un avans încasat înainte de faptul generator face taxa exigibilă la data încasării, o derogare pe care acest câmp nu poate exprima decât prin cash_basis pe o taxă anume, ca și în Belgia sau Luxemburg.',
  tax_point_source_key          = 'codul-fiscal',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'Ordonanța de urgență a Guvernului nr. 120/2021, cu modificările ulterioare — sistemul național RO e-Factura este obligatoriu în relația B2B dintre persoane impozabile stabilite în România începând cu 1 iulie 2024 (perioadă de grație fără sancțiuni până la 31 decembrie 2024; sancțiuni aplicabile de la 1 iulie 2025), cu un termen de transmitere de 5 zile lucrătoare de la data emiterii facturii. Factura electronică este redactată în format UBL 2.1, potrivit specificațiilor tehnice CIUS-RO aprobate prin Ordinul ministrului finanțelor nr. 1.366/2021, modificat prin Ordinul nr. 4.092/2022 — un profil conform modelului semantic EN 16931, spre deosebire de FatturaPA (Italia) sau de schema XML națională FA(3) (Polonia). Dar RO e-Factura n-a rămas pentru asta un schimb descentralizat între parteneri: art. 4 alin. (4)-(6) din OUG 120/2021 dispune că, dacă factura respectă structura impusă, sistemul aplică «sigiliul electronic al Ministerului Finanțelor» și abia atunci o comunică destinatarului, iar «exemplarul original al facturii electronice se consideră fișierul de tip XML însoțit de sigiliul electronic al Ministerului Finanțelor» — nu fișierul emis de vânzător. Cumpărătorul primește deci o copie sigilată de stat, nu factura direct de la vânzător: o clearance de tip CTC, ca și SdI-ul italian sau KSeF-ul polonez, deși construită pe un format nominal EN 16931. Niciun brick din packages/formats/ nu scrie, validează sau transmite azi o factură conformă CIUS-RO (regulile Schematron BR-RO-* nu sunt implementate); profile și mandatory_from rămân deci vide, ca la Italia și Polonia, mai degrabă decât să afirme o interoperabilitate pe care acest depozit n-o oferă încă — a se vedea secțiunea «From Romania» din docs/international.md. vat_scheme și party_scheme rămân de asemenea vide: canalul RO e-Factura identifică părțile prin codul de identificare fiscală (CIF), nu printr-o schemă ISO 6523 verificată oficial; o eventuală schemă Peppol pentru context transfrontalier nu a putut fi confirmată dintr-o sursă oficială românească în cadrul acestei cercetări.',
  einvoice_source_key           = 'oug-120-2021',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = array['camt.053', 'mt940']::text[],
  payment_formats               = array['pain.001']::text[],
  fiscal_year_default           = 'calendar'
 where country = 'RO';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('RO', 'reverse_charge', 'reverse_charge', 'Taxare inversă', '{}'::jsonb, 10, date '1970-01-01', null, 'Codul fiscal, art. 319 alin. (20) — mențiunile obligatorii ale facturii, printre care mențiunea corespunzătoare atunci când beneficiarul este persoana obligată la plata taxei.'),
  ('RO', 'intracom_goods', 'intra_eu_goods', 'Scutit de TVA — livrare intracomunitară de bunuri, art. 294 alin. (2) lit. a) din Codul fiscal.', '{}'::jsonb, 20, date '1970-01-01', null, 'Codul fiscal, art. 319 alin. (20) — mențiunea corespunzătoare unei operațiuni scutite, cu trimitere la dispoziția legală aplicabilă; art. 294 alin. (2) lit. a) — livrarea intracomunitară de bunuri scutită, transpunând art. 138 din Directiva 2006/112/CE.'),
  ('RO', 'intracom_services', 'intra_eu_services', 'Taxare inversă — prestare de servicii intracomunitară, art. 278 alin. (2) din Codul fiscal.', '{}'::jsonb, 30, date '1970-01-01', null, 'Codul fiscal, art. 319 alin. (20); art. 278 alin. (2) — regula generală B2B, locul prestării la sediul beneficiarului, care devine persoana obligată la plata taxei (art. 44 și 196 din Directiva 2006/112/CE).'),
  ('RO', 'export', 'export', 'Scutit de TVA — export, art. 294 alin. (1) din Codul fiscal.', '{}'::jsonb, 40, date '1970-01-01', null, 'Codul fiscal, art. 319 alin. (20); art. 294 alin. (1) lit. a) — scutirea cu drept de deducere pentru bunurile expediate sau transportate în afara Uniunii Europene de către furnizor.'),
  ('RO', 'exempt', 'exempt', 'Scutit de TVA, art. 292 din Codul fiscal.', '{}'::jsonb, 50, date '1970-01-01', null, 'Codul fiscal, art. 319 alin. (20); art. 292 — scutirile fără drept de deducere pentru anumite activități de interes general și pentru alte operațiuni.'),
  ('RO', 'late_payment', 'late_payment', 'În caz de întârziere la plată, se datorează de plin drept dobânda legală penalizatoare prevăzută de Legea nr. 72/2013, precum și o indemnizație forfetară de recuperare a creanței.', '{}'::jsonb, 60, date '1970-01-01', null, 'Legea nr. 72/2013, art. 3 și art. 13 — dobânda legală penalizatoare și indemnizația forfetară de recuperare a creanței, datorate fără punere în întârziere.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
