-- Ekwo OS — Croatia: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/hr at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build hr`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Zakon o porezu na dodanu vrijednost (pročišćeni tekst, na snazi od 1. siječnja 2026.) (Zakon.hr — Poslovni info servis d.o.o., prijepis Narodnih novina)
--     https://www.zakon.hr/z/1455/zakon-o-porezu-na-dodanu-vrijednost
--   Zakon o izmjenama i dopunama Zakona o porezu na dodanu vrijednost, Narodne novine br. 151/2025 — pomiče rok predaje prijave PDV-a (čl. 4., kojim se mijenja čl. 85. st. 6. Zakona o PDV-u) s 20. dana na zadnji dan mjeseca koji slijedi po završetku obračunskog razdoblja, s primjenom od 1. siječnja 2026. (Narodne novine — službeni list Republike Hrvatske)
--     https://narodne-novine.nn.hr/clanci/sluzbeni/2025_12_151_2262.html
--   Zakon o fiskalizaciji, Narodne novine br. 89/2025 — obveza izdavanja i zaprimanja eRačuna u B2B transakcijama (čl. 33.-57., na snazi od 1. siječnja 2026.) (Narodne novine — službeni list Republike Hrvatske)
--     https://narodne-novine.nn.hr/clanci/sluzbeni/full/2025_06_89_1233.html
--   Zakon o elektroničkom izdavanju računa u javnoj nabavi, Narodne novine br. 94/18 — obveza zaprimanja eRačuna od 1. prosinca 2018. i izdavanja od 1. srpnja 2019. u javnoj nabavi (B2G), prenosi Direktivu 2014/55/EU (Narodne novine — službeni list Republike Hrvatske)
--     https://narodne-novine.nn.hr/clanci/sluzbeni/2018_10_94_1817.html
--   Zakon o rokovima ispunjenja novčanih obveza, Narodne novine br. 125/11 — rok plaćanja od 30 dana kad ugovorom nije određen, u odnosima među poduzetnicima (Narodne novine — službeni list Republike Hrvatske)
--     https://narodne-novine.nn.hr/clanci/sluzbeni/2011_11_125_2501.html
--   Zakon o obveznim odnosima (pročišćeni tekst) — čl. 29., zatezna kamata: referentna stopa uvećana za 8 postotnih poena u trgovačkim ugovorima, ažurirana polugodišnje i objavljena u Narodnim novinama (Zakon.hr — Poslovni info servis d.o.o., prijepis Narodnih novina)
--     https://www.zakon.hr/z/75/zakon-o-obveznim-odnosima
--   Obrazac PDV — Prijava poreza na dodanu vrijednost (obrazac u primjeni od veljače 2026., uključuje podatke o donacijama hrane) (Porezna uprava Republike Hrvatske)
--     https://porezna-uprava.gov.hr/UserDocsImages/Arhiva/HR_obrasci/Documents/POREZ%20NA%20DODANU%20VRIJEDNOST/PDV.pdf
--   Korisničke upute — Obrazac PDV (Porezna uprava Republike Hrvatske — ePorezna)
--     https://e-porezna.porezna-uprava.hr/Upute/G2B/Korisni%C4%8Dke%20upute%20-%20Obrazac%20PDV.pdf
--   Fiskalizacija 2.0 — pojmovnik, informacijski posrednik, pristupna točka, format eRačuna (UBL 2.1 + HR-EXT, temeljen na Peppol BIS Billing 3.0 / EN 16931) (Porezna uprava Republike Hrvatske)
--     https://fiskalizacija2.hr/rjecnik-fiskalizacije-2-0/
--   ePorezna — elektroničko podnošenje prijave PDV-a i drugih poreznih obrazaca (Porezna uprava Republike Hrvatske)
--     https://e-porezna.porezna-uprava.hr/
--   EN 16931-1 — semantic data model of the electronic invoice, conformant with Directive 2014/55/EU (European Commission)
--     https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108950/EN+16931+compliance
--   UNCL5305 — code list of VAT categories (BT-118 and BT-151), subset published for EN 16931 (OpenPEPPOL — list published by the European Commission)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/
--   VATEX — code list of VAT exemption reasons (BT-121) (OpenPEPPOL — list published by the European Commission)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/
--   Electronic Address Scheme (EAS) — ISO 6523 identifier schemes, including 9934 (Croatia VAT number) (OpenPEPPOL)
--     https://docs.peppol.eu/poacc/billing/3.0/codelist/eas/
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('HR', 'Croatia', '0.1.0', date '2026-09-25', '20260921145425', 'community', null, null, 'c910bad4c5801d38bcb0abcf511ef5d80bede36b6e9be2747ea198e5d1e95ba0', '[{"key":"zakon-pdv","title":"Zakon o porezu na dodanu vrijednost (pročišćeni tekst, na snazi od 1. siječnja 2026.)","publisher":"Zakon.hr — Poslovni info servis d.o.o., prijepis Narodnih novina","url":"https://www.zakon.hr/z/1455/zakon-o-porezu-na-dodanu-vrijednost","consulted_on":"2026-09-25","kind":"law"},{"key":"zakon-pdv-nn151-25","title":"Zakon o izmjenama i dopunama Zakona o porezu na dodanu vrijednost, Narodne novine br. 151/2025 — pomiče rok predaje prijave PDV-a (čl. 4., kojim se mijenja čl. 85. st. 6. Zakona o PDV-u) s 20. dana na zadnji dan mjeseca koji slijedi po završetku obračunskog razdoblja, s primjenom od 1. siječnja 2026.","publisher":"Narodne novine — službeni list Republike Hrvatske","url":"https://narodne-novine.nn.hr/clanci/sluzbeni/2025_12_151_2262.html","consulted_on":"2026-09-25","kind":"law"},{"key":"zakon-fiskalizacija","title":"Zakon o fiskalizaciji, Narodne novine br. 89/2025 — obveza izdavanja i zaprimanja eRačuna u B2B transakcijama (čl. 33.-57., na snazi od 1. siječnja 2026.)","publisher":"Narodne novine — službeni list Republike Hrvatske","url":"https://narodne-novine.nn.hr/clanci/sluzbeni/full/2025_06_89_1233.html","consulted_on":"2026-09-25","kind":"law"},{"key":"zakon-eracun-javna-nabava","title":"Zakon o elektroničkom izdavanju računa u javnoj nabavi, Narodne novine br. 94/18 — obveza zaprimanja eRačuna od 1. prosinca 2018. i izdavanja od 1. srpnja 2019. u javnoj nabavi (B2G), prenosi Direktivu 2014/55/EU","publisher":"Narodne novine — službeni list Republike Hrvatske","url":"https://narodne-novine.nn.hr/clanci/sluzbeni/2018_10_94_1817.html","consulted_on":"2026-09-25","kind":"law"},{"key":"zakon-rokovi-placanja","title":"Zakon o rokovima ispunjenja novčanih obveza, Narodne novine br. 125/11 — rok plaćanja od 30 dana kad ugovorom nije određen, u odnosima među poduzetnicima","publisher":"Narodne novine — službeni list Republike Hrvatske","url":"https://narodne-novine.nn.hr/clanci/sluzbeni/2011_11_125_2501.html","consulted_on":"2026-09-25","kind":"law"},{"key":"zakon-obvezni-odnosi","title":"Zakon o obveznim odnosima (pročišćeni tekst) — čl. 29., zatezna kamata: referentna stopa uvećana za 8 postotnih poena u trgovačkim ugovorima, ažurirana polugodišnje i objavljena u Narodnim novinama","publisher":"Zakon.hr — Poslovni info servis d.o.o., prijepis Narodnih novina","url":"https://www.zakon.hr/z/75/zakon-o-obveznim-odnosima","consulted_on":"2026-09-25","kind":"law"},{"key":"obrazac-pdv","title":"Obrazac PDV — Prijava poreza na dodanu vrijednost (obrazac u primjeni od veljače 2026., uključuje podatke o donacijama hrane)","publisher":"Porezna uprava Republike Hrvatske","url":"https://porezna-uprava.gov.hr/UserDocsImages/Arhiva/HR_obrasci/Documents/POREZ%20NA%20DODANU%20VRIJEDNOST/PDV.pdf","consulted_on":"2026-09-25","kind":"form"},{"key":"eporezna-uputa-pdv","title":"Korisničke upute — Obrazac PDV","publisher":"Porezna uprava Republike Hrvatske — ePorezna","url":"https://e-porezna.porezna-uprava.hr/Upute/G2B/Korisni%C4%8Dke%20upute%20-%20Obrazac%20PDV.pdf","consulted_on":"2026-09-25","kind":"guidance"},{"key":"fiskalizacija2-portal","title":"Fiskalizacija 2.0 — pojmovnik, informacijski posrednik, pristupna točka, format eRačuna (UBL 2.1 + HR-EXT, temeljen na Peppol BIS Billing 3.0 / EN 16931)","publisher":"Porezna uprava Republike Hrvatske","url":"https://fiskalizacija2.hr/rjecnik-fiskalizacije-2-0/","consulted_on":"2026-09-25","kind":"guidance"},{"key":"eporezna-portal","title":"ePorezna — elektroničko podnošenje prijave PDV-a i drugih poreznih obrazaca","publisher":"Porezna uprava Republike Hrvatske","url":"https://e-porezna.porezna-uprava.hr/","consulted_on":"2026-09-25","kind":"portal"},{"key":"en-16931","title":"EN 16931-1 — semantic data model of the electronic invoice, conformant with Directive 2014/55/EU","publisher":"European Commission","url":"https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108950/EN+16931+compliance","consulted_on":"2026-09-25","kind":"standard"},{"key":"uncl5305","title":"UNCL5305 — code list of VAT categories (BT-118 and BT-151), subset published for EN 16931","publisher":"OpenPEPPOL — list published by the European Commission","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/","consulted_on":"2026-09-25","kind":"standard"},{"key":"vatex","title":"VATEX — code list of VAT exemption reasons (BT-121)","publisher":"OpenPEPPOL — list published by the European Commission","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/","consulted_on":"2026-09-25","kind":"standard"},{"key":"peppol-eas","title":"Electronic Address Scheme (EAS) — ISO 6523 identifier schemes, including 9934 (Croatia VAT number)","publisher":"OpenPEPPOL","url":"https://docs.peppol.eu/poacc/billing/3.0/codelist/eas/","consulted_on":"2026-09-25","kind":"standard"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('HR', 'default', 'Neovisni računski plan po vrsti računa', '{}'::jsonb, true, 'companies', '{}'::text[], null, 'Zakon o računovodstvu (pročišćeni tekst) čl. 8. propisuje samo da poduzetnik vodi poslovne knjige po načelu dvojnog knjigovodstva i sastavlja financijske izvještaje prema Hrvatskim standardima financijskog izvještavanja (HSFI) ili MSFI/MSFI za MSS — ne postoji zakonom propisan računski plan. U praksi je najrašireniji "Računski plan za poduzetnike" koji svake godine objavljuje RRiF (Hrvatska zajednica računovođa i financijskih djelatnika), djelo zaštićeno autorskim pravom čije brojeve računa i nazive ovaj pack ne preuzima. Ovaj plan je samostalan: četveroznamenkasti brojevi čija prva znamenka razlikuje dugotrajnu imovinu (1xxx-0xxx po vrsti), kratkotrajnu imovinu (1xxx), kapital (4xxx), dugoročne obveze i rezerviranja (5xxx), kratkoročne obveze (6xxx), rashode (7xxx) i prihode (8xxx); potonja dva razreda dodatno prate podjelu HSFI 15/MSFI-jevog računa dobiti i gubitka na poslovne, financijske i ostale stavke. Zbog toga financijski izvještaji ovog pack-a padaju na okvir generic (packs/generic/), koji ih izvodi iz osamnaest vrsta računa; hrvatska Bilanca i RDG s AOP oznakama (Pravilnik o strukturi i sadržaju godišnjih financijskih izvještaja) nisu još preslikani red po red — vidi README.md i docs/international.md, odjeljak "From Croatia".', 'zakon-pdv')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('HR', 'default', '0100', 'Nematerijalna imovina - koncesije patenti i licencije', '{}'::jsonb, 'asset_fixed', false, null, 10),
  ('HR', 'default', '0110', 'Nematerijalna imovina - goodwill', '{}'::jsonb, 'asset_fixed', false, null, 20),
  ('HR', 'default', '0120', 'Nematerijalna imovina - softver', '{}'::jsonb, 'asset_fixed', false, null, 30),
  ('HR', 'default', '0130', 'Predujmovi za nematerijalnu imovinu', '{}'::jsonb, 'asset_fixed', false, null, 40),
  ('HR', 'default', '0190', 'Ispravak vrijednosti nematerijalne imovine', '{}'::jsonb, 'asset_fixed', false, null, 50),
  ('HR', 'default', '0200', 'Zemljišta', '{}'::jsonb, 'asset_fixed', false, null, 60),
  ('HR', 'default', '0210', 'Građevinski objekti', '{}'::jsonb, 'asset_fixed', false, null, 70),
  ('HR', 'default', '0220', 'Postrojenja i strojevi', '{}'::jsonb, 'asset_fixed', false, null, 80),
  ('HR', 'default', '0230', 'Prijevozna sredstva', '{}'::jsonb, 'asset_fixed', false, null, 90),
  ('HR', 'default', '0240', 'Uredska oprema', '{}'::jsonb, 'asset_fixed', false, null, 100),
  ('HR', 'default', '0250', 'Alati i inventar', '{}'::jsonb, 'asset_fixed', false, null, 110),
  ('HR', 'default', '0260', 'Ulaganja u tuđu nekretninu (najam)', '{}'::jsonb, 'asset_fixed', false, null, 120),
  ('HR', 'default', '0270', 'Dugotrajna imovina u pripremi', '{}'::jsonb, 'asset_fixed', false, null, 130),
  ('HR', 'default', '0280', 'Predujmovi za materijalnu imovinu', '{}'::jsonb, 'asset_fixed', false, null, 140),
  ('HR', 'default', '0291', 'Ispravak vrijednosti građevinskih objekata', '{}'::jsonb, 'asset_fixed', false, null, 150),
  ('HR', 'default', '0292', 'Ispravak vrijednosti postrojenja i strojeva', '{}'::jsonb, 'asset_fixed', false, null, 160),
  ('HR', 'default', '0293', 'Ispravak vrijednosti uredske opreme', '{}'::jsonb, 'asset_fixed', false, null, 170),
  ('HR', 'default', '0294', 'Ispravak vrijednosti prijevoznih sredstava', '{}'::jsonb, 'asset_fixed', false, null, 180),
  ('HR', 'default', '0300', 'Udjeli u povezanim poduzetnicima', '{}'::jsonb, 'asset_non_current', false, null, 190),
  ('HR', 'default', '0310', 'Dani zajmovi povezanim poduzetnicima', '{}'::jsonb, 'asset_non_current', false, null, 200),
  ('HR', 'default', '0320', 'Dugoročna ulaganja u vrijednosne papire', '{}'::jsonb, 'asset_non_current', false, null, 210),
  ('HR', 'default', '0330', 'Dugoročni depoziti', '{}'::jsonb, 'asset_non_current', false, null, 220),
  ('HR', 'default', '0340', 'Odgođena porezna imovina', '{}'::jsonb, 'asset_non_current', false, null, 230),
  ('HR', 'default', '1000', 'Banka - žiro račun EUR', '{}'::jsonb, 'asset_cash', false, null, 240),
  ('HR', 'default', '1010', 'Banka - devizni račun', '{}'::jsonb, 'asset_cash', false, null, 250),
  ('HR', 'default', '1020', 'Blagajna', '{}'::jsonb, 'asset_cash', false, null, 260),
  ('HR', 'default', '1030', 'Blagajna - devizna', '{}'::jsonb, 'asset_cash', false, null, 270),
  ('HR', 'default', '1100', 'Kratkoročni depoziti', '{}'::jsonb, 'asset_current', false, null, 280),
  ('HR', 'default', '1110', 'Kratkoročna ulaganja u vrijednosne papire', '{}'::jsonb, 'asset_current', false, null, 290),
  ('HR', 'default', '1200', 'Potraživanja od kupaca u zemlji', '{}'::jsonb, 'asset_receivable', true, null, 300),
  ('HR', 'default', '1210', 'Potraživanja od kupaca u EU', '{}'::jsonb, 'asset_receivable', true, null, 310),
  ('HR', 'default', '1220', 'Potraživanja od kupaca izvan EU', '{}'::jsonb, 'asset_receivable', true, null, 320),
  ('HR', 'default', '1230', 'Potraživanja po primljenim mjenicama', '{}'::jsonb, 'asset_current', false, null, 330),
  ('HR', 'default', '1290', 'Ispravak vrijednosti potraživanja od kupaca', '{}'::jsonb, 'asset_current', false, null, 340),
  ('HR', 'default', '1300', 'Zalihe sirovina i materijala', '{}'::jsonb, 'asset_current', false, null, 350),
  ('HR', 'default', '1310', 'Zalihe trgovačke robe', '{}'::jsonb, 'asset_current', false, null, 360),
  ('HR', 'default', '1320', 'Proizvodnja u tijeku', '{}'::jsonb, 'asset_current', false, null, 370),
  ('HR', 'default', '1330', 'Zalihe proizvoda', '{}'::jsonb, 'asset_current', false, null, 380),
  ('HR', 'default', '1340', 'Zalihe ambalaže', '{}'::jsonb, 'asset_current', false, null, 390),
  ('HR', 'default', '1350', 'Predujmovi za zalihe', '{}'::jsonb, 'asset_current', false, null, 400),
  ('HR', 'default', '1400', 'Pretporez', '{}'::jsonb, 'asset_current', true, null, 410),
  ('HR', 'default', '1410', 'Pretporez - stjecanje dobara unutar EU', '{}'::jsonb, 'asset_current', true, null, 420),
  ('HR', 'default', '1420', 'Pretporez - uvoz', '{}'::jsonb, 'asset_current', true, null, 430),
  ('HR', 'default', '1500', 'Predujmovi plaćeni dobavljačima', '{}'::jsonb, 'asset_prepayments', false, null, 440),
  ('HR', 'default', '1510', 'Unaprijed plaćeni troškovi osiguranja', '{}'::jsonb, 'asset_prepayments', false, null, 450),
  ('HR', 'default', '1520', 'Unaprijed plaćeni troškovi zakupa', '{}'::jsonb, 'asset_prepayments', false, null, 460),
  ('HR', 'default', '1530', 'Unaprijed plaćene pretplate i licencije', '{}'::jsonb, 'asset_prepayments', false, null, 470),
  ('HR', 'default', '1600', 'Potraživanja od zaposlenika', '{}'::jsonb, 'asset_current', false, null, 480),
  ('HR', 'default', '1610', 'Potraživanja od države - porez na dobit', '{}'::jsonb, 'asset_current', false, null, 490),
  ('HR', 'default', '1620', 'Potraživanja od države - ostalo', '{}'::jsonb, 'asset_current', false, null, 500),
  ('HR', 'default', '1630', 'Potraživanja od povezanih poduzetnika', '{}'::jsonb, 'asset_current', false, null, 510),
  ('HR', 'default', '1700', 'Dani kratkoročni zajmovi', '{}'::jsonb, 'asset_current', false, null, 520),
  ('HR', 'default', '1710', 'Namjenski kratkoročni depoziti', '{}'::jsonb, 'asset_current', false, null, 530),
  ('HR', 'default', '4000', 'Temeljni (upisani) kapital', '{}'::jsonb, 'equity', false, null, 540),
  ('HR', 'default', '4010', 'Vlastite dionice i udjeli', '{}'::jsonb, 'equity', false, null, 550),
  ('HR', 'default', '4100', 'Kapitalne rezerve', '{}'::jsonb, 'equity', false, null, 560),
  ('HR', 'default', '4200', 'Zakonske rezerve', '{}'::jsonb, 'equity', false, null, 570),
  ('HR', 'default', '4210', 'Statutarne rezerve', '{}'::jsonb, 'equity', false, null, 580),
  ('HR', 'default', '4220', 'Ostale rezerve', '{}'::jsonb, 'equity', false, null, 590),
  ('HR', 'default', '4300', 'Revalorizacijske rezerve', '{}'::jsonb, 'equity', false, null, 600),
  ('HR', 'default', '4500', 'Zadržana dobit', '{}'::jsonb, 'equity_retained', false, null, 610),
  ('HR', 'default', '4510', 'Preneseni gubitak', '{}'::jsonb, 'equity_retained', false, null, 620),
  ('HR', 'default', '4610', 'Dobit poslovne godine', '{}'::jsonb, 'equity', false, null, 630),
  ('HR', 'default', '4620', 'Gubitak poslovne godine', '{}'::jsonb, 'equity', false, null, 640),
  ('HR', 'default', '5000', 'Rezerviranja za otpremnine i jubilarne nagrade', '{}'::jsonb, 'liability_non_current', false, null, 650),
  ('HR', 'default', '5010', 'Rezerviranja za sudske sporove', '{}'::jsonb, 'liability_non_current', false, null, 660),
  ('HR', 'default', '5020', 'Rezerviranja za jamstva na proizvode', '{}'::jsonb, 'liability_non_current', false, null, 670),
  ('HR', 'default', '5100', 'Dugoročni krediti kod banaka', '{}'::jsonb, 'liability_non_current', false, null, 680),
  ('HR', 'default', '5110', 'Dugoročni krediti od povezanih poduzetnika', '{}'::jsonb, 'liability_non_current', false, null, 690),
  ('HR', 'default', '5120', 'Izdane dugoročne obveznice', '{}'::jsonb, 'liability_non_current', false, null, 700),
  ('HR', 'default', '5200', 'Dugoročne obveze prema dobavljačima', '{}'::jsonb, 'liability_non_current', false, null, 710),
  ('HR', 'default', '5300', 'Odgođena porezna obveza', '{}'::jsonb, 'liability_non_current', false, null, 720),
  ('HR', 'default', '5400', 'Dugoročno razgraničene državne potpore', '{}'::jsonb, 'liability_non_current', false, null, 730),
  ('HR', 'default', '6200', 'Obveze prema dobavljačima u zemlji', '{}'::jsonb, 'liability_payable', true, null, 740),
  ('HR', 'default', '6210', 'Obveze prema dobavljačima u EU', '{}'::jsonb, 'liability_payable', true, null, 750),
  ('HR', 'default', '6220', 'Obveze prema dobavljačima izvan EU', '{}'::jsonb, 'liability_payable', true, null, 760),
  ('HR', 'default', '6230', 'Obveze po primljenim predujmovima', '{}'::jsonb, 'liability_current', false, null, 770),
  ('HR', 'default', '6300', 'Obveze za plaće', '{}'::jsonb, 'liability_current', false, null, 780),
  ('HR', 'default', '6310', 'Obveze za doprinose na plaće', '{}'::jsonb, 'liability_current', false, null, 790),
  ('HR', 'default', '6320', 'Obveze za porez na dohodak iz plaća', '{}'::jsonb, 'liability_current', false, null, 800),
  ('HR', 'default', '6330', 'Obveze za prirez', '{}'::jsonb, 'liability_current', false, null, 810),
  ('HR', 'default', '6400', 'Obveza za PDV', '{}'::jsonb, 'liability_current', true, null, 820),
  ('HR', 'default', '6410', 'Obveza za porez na dobit', '{}'::jsonb, 'liability_current', false, null, 830),
  ('HR', 'default', '6420', 'Obveze za ostale poreze i doprinose', '{}'::jsonb, 'liability_current', false, null, 840),
  ('HR', 'default', '6500', 'Obveze za kamate', '{}'::jsonb, 'liability_current', false, null, 850),
  ('HR', 'default', '6510', 'Obveze za dividende', '{}'::jsonb, 'liability_current', false, null, 860),
  ('HR', 'default', '6600', 'Kratkoročni krediti kod banaka', '{}'::jsonb, 'liability_current', false, null, 870),
  ('HR', 'default', '6610', 'Kratkoročni dio dugoročnih kredita', '{}'::jsonb, 'liability_current', false, null, 880),
  ('HR', 'default', '6700', 'Kratkoročno razgraničeni prihodi', '{}'::jsonb, 'liability_current', false, null, 890),
  ('HR', 'default', '6710', 'Obračunani troškovi', '{}'::jsonb, 'liability_current', false, null, 900),
  ('HR', 'default', '6800', 'Obveze prema povezanim poduzetnicima', '{}'::jsonb, 'liability_current', false, null, 910),
  ('HR', 'default', '6900', 'Prijelazni račun', '{}'::jsonb, 'liability_current', false, null, 920),
  ('HR', 'default', '6910', 'Ostale kratkoročne obveze', '{}'::jsonb, 'liability_current', false, null, 930),
  ('HR', 'default', '7100', 'Trošak sirovina i materijala', '{}'::jsonb, 'expense_direct_cost', false, null, 940),
  ('HR', 'default', '7110', 'Trošak prodane trgovačke robe', '{}'::jsonb, 'expense_direct_cost', false, null, 950),
  ('HR', 'default', '7120', 'Trošak energije', '{}'::jsonb, 'expense', false, null, 960),
  ('HR', 'default', '7130', 'Trošak ambalaže', '{}'::jsonb, 'expense', false, null, 970),
  ('HR', 'default', '7200', 'Troškovi plaća', '{}'::jsonb, 'expense', false, null, 980),
  ('HR', 'default', '7210', 'Troškovi doprinosa na plaće', '{}'::jsonb, 'expense', false, null, 990),
  ('HR', 'default', '7220', 'Troškovi naknada radnicima (dnevnice prijevoz)', '{}'::jsonb, 'expense', false, null, 1000),
  ('HR', 'default', '7230', 'Troškovi osiguranja radnika', '{}'::jsonb, 'expense', false, null, 1010),
  ('HR', 'default', '7300', 'Troškovi usluga', '{}'::jsonb, 'expense', false, null, 1020),
  ('HR', 'default', '7310', 'Troškovi zakupa i najma', '{}'::jsonb, 'expense', false, null, 1030),
  ('HR', 'default', '7320', 'Troškovi promidžbe i reprezentacije', '{}'::jsonb, 'expense', false, null, 1040),
  ('HR', 'default', '7330', 'Troškovi intelektualnih i osobnih usluga', '{}'::jsonb, 'expense', false, null, 1050),
  ('HR', 'default', '7340', 'Troškovi telekomunikacija i poštarine', '{}'::jsonb, 'expense', false, null, 1060),
  ('HR', 'default', '7350', 'Troškovi tekućeg i investicijskog održavanja', '{}'::jsonb, 'expense', false, null, 1070),
  ('HR', 'default', '7360', 'Troškovi osiguranja imovine', '{}'::jsonb, 'expense', false, null, 1080),
  ('HR', 'default', '7370', 'Troškovi bankarskih usluga i platnog prometa', '{}'::jsonb, 'expense', false, null, 1090),
  ('HR', 'default', '7400', 'Amortizacija nematerijalne imovine', '{}'::jsonb, 'expense_depreciation', false, null, 1100),
  ('HR', 'default', '7410', 'Amortizacija materijalne imovine', '{}'::jsonb, 'expense_depreciation', false, null, 1110),
  ('HR', 'default', '7420', 'Tečajne razlike - rashodi', '{}'::jsonb, 'expense', false, null, 1120),
  ('HR', 'default', '7430', 'Kamate i ostali financijski rashodi', '{}'::jsonb, 'expense', false, null, 1130),
  ('HR', 'default', '7440', 'Vrijednosno usklađenje financijske imovine', '{}'::jsonb, 'expense', false, null, 1140),
  ('HR', 'default', '7500', 'Vrijednosno usklađenje potraživanja', '{}'::jsonb, 'expense', false, null, 1150),
  ('HR', 'default', '7510', 'Vrijednosno usklađenje zaliha', '{}'::jsonb, 'expense', false, null, 1160),
  ('HR', 'default', '7600', 'Nabavna vrijednost prodane dugotrajne imovine', '{}'::jsonb, 'expense', false, null, 1170),
  ('HR', 'default', '7610', 'Nabavna vrijednost osobnih automobila i sredstava za osobni prijevoz', '{}'::jsonb, 'expense', false, null, 1180),
  ('HR', 'default', '7700', 'Porez na dobit', '{}'::jsonb, 'expense', false, null, 1190),
  ('HR', 'default', '7900', 'Ostali (izvanredni) rashodi', '{}'::jsonb, 'expense', false, null, 1200),
  ('HR', 'default', '8100', 'Prihodi od prodaje robe u zemlji', '{}'::jsonb, 'income', false, null, 1210),
  ('HR', 'default', '8110', 'Prihodi od prodaje robe u EU', '{}'::jsonb, 'income', false, null, 1220),
  ('HR', 'default', '8120', 'Prihodi od izvoza robe', '{}'::jsonb, 'income', false, null, 1230),
  ('HR', 'default', '8130', 'Prihodi od usluga u zemlji', '{}'::jsonb, 'income', false, null, 1240),
  ('HR', 'default', '8140', 'Prihodi od usluga u EU', '{}'::jsonb, 'income', false, null, 1250),
  ('HR', 'default', '8150', 'Prihodi od izvoza usluga', '{}'::jsonb, 'income', false, null, 1260),
  ('HR', 'default', '8200', 'Prihodi od najma', '{}'::jsonb, 'income', false, null, 1270),
  ('HR', 'default', '8300', 'Prihodi od državnih potpora', '{}'::jsonb, 'income_other', false, null, 1280),
  ('HR', 'default', '8310', 'Dobit od prodaje dugotrajne imovine', '{}'::jsonb, 'income_other', false, null, 1290),
  ('HR', 'default', '8400', 'Prihodi od kamata', '{}'::jsonb, 'income_other', false, null, 1300),
  ('HR', 'default', '8410', 'Tečajne razlike - prihodi', '{}'::jsonb, 'income_other', false, null, 1310),
  ('HR', 'default', '8420', 'Prihodi od dividendi i udjela u dobiti', '{}'::jsonb, 'income_other', false, null, 1320),
  ('HR', 'default', '8900', 'Ostali (izvanredni) prihodi', '{}'::jsonb, 'income_other', false, null, 1330),
  ('HR', 'default', '8910', 'Razlike u zaokruživanju', '{}'::jsonb, 'income_other', false, null, 1340),
  ('HR', 'default', '9000', 'Tuđa dugotrajna imovina', '{}'::jsonb, 'off_balance', false, null, 1350),
  ('HR', 'default', '9010', 'Primljena osiguranja plaćanja', '{}'::jsonb, 'off_balance', false, null, 1360),
  ('HR', 'default', '9020', 'Roba na komisiji', '{}'::jsonb, 'off_balance', false, null, 1370),
  ('HR', 'default', '9030', 'Zakupljena imovina - operativni leasing', '{}'::jsonb, 'off_balance', false, null, 1380)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('HR', 'BAN', 'Banka', '{}'::jsonb, 'bank', 30),
  ('HR', 'BLG', 'Blagajna', '{}'::jsonb, 'cash', 40),
  ('HR', 'IRA', 'Knjiga izlaznih računa', '{}'::jsonb, 'sales', 10),
  ('HR', 'OTV', 'Otvaranje poslovnih knjiga', '{}'::jsonb, 'opening', 60),
  ('HR', 'TEM', 'Temeljnica', '{}'::jsonb, 'general', 50),
  ('HR', 'URA', 'Knjiga ulaznih računa', '{}'::jsonb, 'purchase', 20)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('HR', 'HR-P-13', 'PDV 13% — tuzemna nabava', '{}'::jsonb, null, 'percent', 13, 'purchase', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 3. i čl. 58.-61.', null, null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-25', 'PDV 25% — tuzemna nabava', '{}'::jsonb, null, 'percent', 25, 'purchase', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 1. i čl. 58.-61. — pravo na odbitak pretporeza po općoj stopi 25%.', null, null, 100, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-5', 'PDV 5% — tuzemna nabava', '{}'::jsonb, null, 'percent', 5, 'purchase', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 2. i čl. 58.-61.', null, null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-CAR-25', 'PDV 25% — osobni automobil, 50% neodbitno', '{}'::jsonb, null, 'percent', 25, 'purchase', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 61. st. 2. — ne može se odbiti 50% pretporeza obračunanog za nabavu osobnih automobila i drugih sredstava za osobni prijevoz te dobara i usluga u vezi s tim sredstvima.', null, null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-DOMRC', 'Građevinska usluga primljena — prijenos porezne obveze', '{}'::jsonb, null, 'percent', 25, 'purchase', 'domestic_reverse_charge', date '2026-01-01', null, 'Zakon o PDV čl. 75. st. 3. t. a) — primatelj građevinske usluge, registriran za potrebe PDV-a u RH, obračunava PDV i istovremeno ostvaruje pravo na odbitak (čl. 58.-61.).', null, null, 140, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-FOREIGN-25', 'Primljena isporuka od poreznog obveznika bez sjedišta u RH — 25%', '{}'::jsonb, null, 'percent', 25, 'purchase', 'foreign_services_received', date '2026-01-01', null, 'Zakon o PDV čl. 75. st. 2. — kad oporezivu isporuku u tuzemstvu obavlja porezni obveznik bez sjedišta, prebivališta ili uobičajenog boravišta u RH i nije registriran za potrebe PDV-a u tuzemstvu, PDV plaća primatelj, koji istovremeno odbija pretporez (čl. 58.-61.).', null, null, 170, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-ICG-25', 'Stjecanje dobara unutar EU — 25%', '{}'::jsonb, null, 'percent', 25, 'purchase', 'intracom_acquisition_goods', date '2026-01-01', null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije — primatelj obračunava PDV po stopi kojom bi dobra bila oporezovana u tuzemstvu, i istovremeno odbija pretporez (čl. 58.-61.).', null, null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-ICS-25', 'Primljena usluga iz EU — 25%', '{}'::jsonb, null, 'percent', 25, 'purchase', 'intracom_acquisition_services', date '2026-01-01', null, 'Zakon o PDV čl. 75. st. 1. t. 6. — primatelj obračunava PDV na usluge primljene od poreznog obveznika iz druge države članice, i istovremeno odbija pretporez (čl. 58.-61.).', null, null, 160, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-P-IMPORT', 'PDV pri uvozu dobara', '{}'::jsonb, null, 'percent', 25, 'purchase', 'import', date '2026-01-01', null, 'Zakon o PDV čl. 32. st. 1. — oporezivi događaj kod uvoza dobara nastaje u trenutku uvoza; PDV obračunava carinska služba na temelju uvozne deklaracije, a obveznik odbija pretporez (čl. 58.-61.).', null, null, 180, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-0', 'PDV 0% — solarne ploče na privatnim stambenim objektima', '{}'::jsonb, null, 'percent', 0, 'sale', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 6. — isporuka i ugradnja solarnih ploča na privatne stambene objekte oporezuje se po stopi 0%.', 'Z', null, 40, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-13', 'PDV 13% — tuzemna isporuka', '{}'::jsonb, null, 'percent', 13, 'sale', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 3. — snižena stopa 13% (npr. smještaj u hotelima, voda, električna energija).', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-25', 'PDV 25% — tuzemna isporuka', '{}'::jsonb, null, 'percent', 25, 'sale', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 1. — opća stopa PDV-a od 25%.', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-5', 'PDV 5% — tuzemna isporuka', '{}'::jsonb, null, 'percent', 5, 'sale', 'domestic', date '2026-01-01', null, 'Zakon o PDV čl. 38. st. 2. — snižena stopa 5% (npr. kruh, mlijeko, lijekovi, knjige).', 'S', null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-DOMRC', 'Građevinska usluga — prijenos porezne obveze na primatelja', '{}'::jsonb, null, 'percent', 0, 'sale', 'domestic_reverse_charge', date '2026-01-01', null, 'Zakon o PDV čl. 75. st. 3. t. a) — kad se obavljaju građevinske usluge poreznom obvezniku registriranom za potrebe PDV-a u RH, PDV obračunava primatelj.', 'AE', 'VATEX-EU-AE', 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-EXEMPT-RENT', 'Najam stambenih prostorija — oslobođeno bez prava na odbitak', '{}'::jsonb, null, 'percent', 0, 'sale', 'exempt', date '2026-01-01', null, 'Zakon o PDV čl. 40. st. 1. t. l) — najam stambenih prostorija za stanovanje je oslobođen PDV-a bez prava na odbitak pretporeza (transponira čl. 135. st. 1. t. l) Direktive 2006/112/EZ).', 'E', 'VATEX-EU-135-1', 90, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-EXPORT', 'Izvozna isporuka', '{}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2026-01-01', null, 'Zakon o PDV čl. 45. st. 1. t. 1. — izvozna isporuka dobara otpremljenih ili prevezenih izvan Europske unije je oslobođena PDV-a s pravom na odbitak pretporeza.', 'G', 'VATEX-EU-G', 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-ICG', 'Isporuka dobara unutar EU', '{}'::jsonb, null, 'percent', 0, 'sale', 'intracom_goods', date '2026-01-01', null, 'Zakon o PDV čl. 41. st. 1. t. a) — isporuka dobara poreznom obvezniku registriranom za potrebe PDV-a u drugoj državi članici je oslobođena PDV-a.', 'K', 'VATEX-EU-IC', 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null),
  ('HR', 'HR-S-ICS', 'Usluga oporeziva u državi sjedišta primatelja (EU)', '{}'::jsonb, null, 'percent', 0, 'sale', 'intracom_services', date '2026-01-01', null, 'Zakon o PDV čl. 17. st. 1. — mjesto obavljanja usluge poreznom obvezniku je mjesto njegova sjedišta; primatelj u drugoj državi članici obračunava PDV.', 'K', 'VATEX-EU-IC', 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'zakon-pdv', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('HR-P-13', 'invoice', 'base', 100, null, 'III2', array['III2']::text[], 100, 'HR-PDV', 10),
    ('HR-P-13', 'invoice', 'tax', 100, '1400', 'III2', array['III2']::text[], 100, 'HR-PDV', 20),
    ('HR-P-13', 'credit_note', 'base', 100, null, 'III2', array['III2']::text[], -100, 'HR-PDV', 10),
    ('HR-P-13', 'credit_note', 'tax', 100, '1400', 'III2', array['III2']::text[], -100, 'HR-PDV', 20),
    ('HR-P-25', 'invoice', 'base', 100, null, 'III3', array['III3']::text[], 100, 'HR-PDV', 10),
    ('HR-P-25', 'invoice', 'tax', 100, '1400', 'III3', array['III3']::text[], 100, 'HR-PDV', 20),
    ('HR-P-25', 'credit_note', 'base', 100, null, 'III3', array['III3']::text[], -100, 'HR-PDV', 10),
    ('HR-P-25', 'credit_note', 'tax', 100, '1400', 'III3', array['III3']::text[], -100, 'HR-PDV', 20),
    ('HR-P-5', 'invoice', 'base', 100, null, 'III1', array['III1']::text[], 100, 'HR-PDV', 10),
    ('HR-P-5', 'invoice', 'tax', 100, '1400', 'III1', array['III1']::text[], 100, 'HR-PDV', 20),
    ('HR-P-5', 'credit_note', 'base', 100, null, 'III1', array['III1']::text[], -100, 'HR-PDV', 10),
    ('HR-P-5', 'credit_note', 'tax', 100, '1400', 'III1', array['III1']::text[], -100, 'HR-PDV', 20),
    ('HR-P-CAR-25', 'invoice', 'base', 100, null, 'III3', array['III3']::text[], 100, 'HR-PDV', 10),
    ('HR-P-CAR-25', 'invoice', 'tax', 50, '1400', 'III3', array['III3']::text[], 50, 'HR-PDV', 20),
    ('HR-P-CAR-25', 'invoice', 'tax_on_base', 50, null, null, null, 100, null, 30),
    ('HR-P-CAR-25', 'credit_note', 'base', 100, null, 'III3', array['III3']::text[], -100, 'HR-PDV', 10),
    ('HR-P-CAR-25', 'credit_note', 'tax', 50, '1400', 'III3', array['III3']::text[], -50, 'HR-PDV', 20),
    ('HR-P-CAR-25', 'credit_note', 'tax_on_base', 50, null, null, null, -100, null, 30),
    ('HR-P-DOMRC', 'invoice', 'base', 100, null, 'II4', array['II4', 'III4']::text[], 100, 'HR-PDV', 10),
    ('HR-P-DOMRC', 'invoice', 'tax', 100, '6400', 'II4', array['II4']::text[], 100, 'HR-PDV', 20),
    ('HR-P-DOMRC', 'invoice', 'tax', 100, '1400', 'III4', array['III4']::text[], 100, 'HR-PDV', 30),
    ('HR-P-DOMRC', 'credit_note', 'base', 100, null, 'II4', array['II4', 'III4']::text[], -100, 'HR-PDV', 10),
    ('HR-P-DOMRC', 'credit_note', 'tax', 100, '6400', 'II4', array['II4']::text[], -100, 'HR-PDV', 20),
    ('HR-P-DOMRC', 'credit_note', 'tax', 100, '1400', 'III4', array['III4']::text[], -100, 'HR-PDV', 30),
    ('HR-P-FOREIGN-25', 'invoice', 'base', 100, null, 'II13', array['II13', 'III13']::text[], 100, 'HR-PDV', 10),
    ('HR-P-FOREIGN-25', 'invoice', 'tax', 100, '6400', 'II13', array['II13']::text[], 100, 'HR-PDV', 20),
    ('HR-P-FOREIGN-25', 'invoice', 'tax', 100, '1400', 'III13', array['III13']::text[], 100, 'HR-PDV', 30),
    ('HR-P-FOREIGN-25', 'credit_note', 'base', 100, null, 'II13', array['II13', 'III13']::text[], -100, 'HR-PDV', 10),
    ('HR-P-FOREIGN-25', 'credit_note', 'tax', 100, '6400', 'II13', array['II13']::text[], -100, 'HR-PDV', 20),
    ('HR-P-FOREIGN-25', 'credit_note', 'tax', 100, '1400', 'III13', array['III13']::text[], -100, 'HR-PDV', 30),
    ('HR-P-ICG-25', 'invoice', 'base', 100, null, 'II7', array['II7', 'III7']::text[], 100, 'HR-PDV', 10),
    ('HR-P-ICG-25', 'invoice', 'tax', 100, '6400', 'II7', array['II7']::text[], 100, 'HR-PDV', 20),
    ('HR-P-ICG-25', 'invoice', 'tax', 100, '1400', 'III7', array['III7']::text[], 100, 'HR-PDV', 30),
    ('HR-P-ICG-25', 'credit_note', 'base', 100, null, 'II7', array['II7', 'III7']::text[], -100, 'HR-PDV', 10),
    ('HR-P-ICG-25', 'credit_note', 'tax', 100, '6400', 'II7', array['II7']::text[], -100, 'HR-PDV', 20),
    ('HR-P-ICG-25', 'credit_note', 'tax', 100, '1400', 'III7', array['III7']::text[], -100, 'HR-PDV', 30),
    ('HR-P-ICS-25', 'invoice', 'base', 100, null, 'II10', array['II10', 'III10']::text[], 100, 'HR-PDV', 10),
    ('HR-P-ICS-25', 'invoice', 'tax', 100, '6400', 'II10', array['II10']::text[], 100, 'HR-PDV', 20),
    ('HR-P-ICS-25', 'invoice', 'tax', 100, '1400', 'III10', array['III10']::text[], 100, 'HR-PDV', 30),
    ('HR-P-ICS-25', 'credit_note', 'base', 100, null, 'II10', array['II10', 'III10']::text[], -100, 'HR-PDV', 10),
    ('HR-P-ICS-25', 'credit_note', 'tax', 100, '6400', 'II10', array['II10']::text[], -100, 'HR-PDV', 20),
    ('HR-P-ICS-25', 'credit_note', 'tax', 100, '1400', 'III10', array['III10']::text[], -100, 'HR-PDV', 30),
    ('HR-P-IMPORT', 'invoice', 'base', 100, null, null, null, 100, null, 10),
    ('HR-P-IMPORT', 'invoice', 'tax', 100, '6400', 'II15', array['II15']::text[], 100, 'HR-PDV', 20),
    ('HR-P-IMPORT', 'invoice', 'tax', 100, '1400', 'III14', array['III14']::text[], 100, 'HR-PDV', 30),
    ('HR-P-IMPORT', 'credit_note', 'base', 100, null, null, null, -100, null, 10),
    ('HR-P-IMPORT', 'credit_note', 'tax', 100, '6400', 'II15', array['II15']::text[], -100, 'HR-PDV', 20),
    ('HR-P-IMPORT', 'credit_note', 'tax', 100, '1400', 'III14', array['III14']::text[], -100, 'HR-PDV', 30),
    ('HR-S-0', 'invoice', 'base', 100, null, 'I11', array['I11']::text[], 100, 'HR-PDV', 10),
    ('HR-S-0', 'credit_note', 'base', 100, null, 'I11', array['I11']::text[], -100, 'HR-PDV', 10),
    ('HR-S-13', 'invoice', 'base', 100, null, 'II2', array['II2']::text[], 100, 'HR-PDV', 10),
    ('HR-S-13', 'invoice', 'tax', 100, '6400', 'II2', array['II2']::text[], 100, 'HR-PDV', 20),
    ('HR-S-13', 'credit_note', 'base', 100, null, 'II2', array['II2']::text[], -100, 'HR-PDV', 10),
    ('HR-S-13', 'credit_note', 'tax', 100, '6400', 'II2', array['II2']::text[], -100, 'HR-PDV', 20),
    ('HR-S-25', 'invoice', 'base', 100, null, 'II3', array['II3']::text[], 100, 'HR-PDV', 10),
    ('HR-S-25', 'invoice', 'tax', 100, '6400', 'II3', array['II3']::text[], 100, 'HR-PDV', 20),
    ('HR-S-25', 'credit_note', 'base', 100, null, 'II3', array['II3']::text[], -100, 'HR-PDV', 10),
    ('HR-S-25', 'credit_note', 'tax', 100, '6400', 'II3', array['II3']::text[], -100, 'HR-PDV', 20),
    ('HR-S-5', 'invoice', 'base', 100, null, 'II1', array['II1']::text[], 100, 'HR-PDV', 10),
    ('HR-S-5', 'invoice', 'tax', 100, '6400', 'II1', array['II1']::text[], 100, 'HR-PDV', 20),
    ('HR-S-5', 'credit_note', 'base', 100, null, 'II1', array['II1']::text[], -100, 'HR-PDV', 10),
    ('HR-S-5', 'credit_note', 'tax', 100, '6400', 'II1', array['II1']::text[], -100, 'HR-PDV', 20),
    ('HR-S-DOMRC', 'invoice', 'base', 100, null, 'I1', array['I1']::text[], 100, 'HR-PDV', 10),
    ('HR-S-DOMRC', 'credit_note', 'base', 100, null, 'I1', array['I1']::text[], -100, 'HR-PDV', 10),
    ('HR-S-EXEMPT-RENT', 'invoice', 'base', 100, null, 'I8', array['I8']::text[], 100, 'HR-PDV', 10),
    ('HR-S-EXEMPT-RENT', 'credit_note', 'base', 100, null, 'I8', array['I8']::text[], -100, 'HR-PDV', 10),
    ('HR-S-EXPORT', 'invoice', 'base', 100, null, 'I9', array['I9']::text[], 100, 'HR-PDV', 10),
    ('HR-S-EXPORT', 'credit_note', 'base', 100, null, 'I9', array['I9']::text[], -100, 'HR-PDV', 10),
    ('HR-S-ICG', 'invoice', 'base', 100, null, 'I3', array['I3']::text[], 100, 'HR-PDV', 10),
    ('HR-S-ICG', 'credit_note', 'base', 100, null, 'I3', array['I3']::text[], -100, 'HR-PDV', 10),
    ('HR-S-ICS', 'invoice', 'base', 100, null, 'I4', array['I4']::text[], 100, 'HR-PDV', 10),
    ('HR-S-ICS', 'credit_note', 'base', 100, null, 'I4', array['I4']::text[], -100, 'HR-PDV', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'HR' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('HR', 'HR-PDV', 'Obrazac PDV — Prijava poreza na dodanu vrijednost', array['month', 'quarter']::declaration_period[], 'month'::declaration_period, date '2026-01-01', null, 'Zakon o PDV čl. 84. st. 1. — porezno razdoblje je razdoblje od prvog do posljednjeg dana u kalendarskom mjesecu, za sve porezne obveznike kojima Zakon ne daje pravo na tromjesečno razdoblje. Obrazac je u primjeni od veljače 2026. (uključuje podatke o donacijama hrane).', true,'last_day_of_month_after_period'::filing_deadline_rule, null, null, 'Zakon o PDV čl. 85. st. 6., kako je izmijenjen čl. 4. Zakona o izmjenama i dopunama Zakona o porezu na dodanu vrijednost (NN 151/25), na snazi od 1. siječnja 2026. — prijava PDV-a podnosi se do zadnjeg dana u mjesecu koji slijedi po završetku obračunskog razdoblja (do 1. siječnja 2026. rok je bio 20. dan tog mjeseca).', 'zakon-pdv-nn151-25', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('HR', 'HR-PDV', 'I1', 'base', 'Isporuke u RH za koje PDV obračunava primatelj (tuzemni prijenos porezne obveze)', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 3. t. a) — građevinske usluge; primatelj-obveznik obračunava PDV, isporučitelj iskazuje samo osnovicu.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I2', 'base', 'Isporuke dobara obavljene u drugim državama članicama', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Uputa za popunjavanje Obrasca PDV — isporuke dobara čije je mjesto oporezivanja u drugoj državi članici (npr. isporuke s ugradnjom ili montažom, prodaja na daljinu iznad praga druge države).', 'eporezna-uputa-pdv'),
  ('HR', 'HR-PDV', 'I3', 'base', 'Isporuke dobara unutar EU', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 41. st. 1. t. a) — isporuka dobara poreznom obvezniku registriranom za potrebe PDV-a u drugoj državi članici je oslobođena PDV-a.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I4', 'base', 'Obavljene usluge unutar EU', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 17. st. 1. — mjesto obavljanja usluge poreznom obvezniku je mjesto njegova sjedišta; kad je to druga država članica, primatelj obračunava PDV (čl. 75. st. 1. t. 6.).', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I5', 'base', 'Obavljene isporuke osobama bez sjedišta u RH', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Uputa za popunjavanje Obrasca PDV — isporuke dobara i usluga čije je mjesto oporezivanja izvan RH, obavljene osobama bez sjedišta, prebivališta ili uobičajenog boravišta u RH.', 'eporezna-uputa-pdv'),
  ('HR', 'HR-PDV', 'I6', 'base', 'Sastavljanje i postavljanje dobara u drugoj državi članici EU', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Uputa za popunjavanje Obrasca PDV — isporuka dobara s ugradnjom ili montažom u drugoj državi članici, koja se tamo smatra mjestom oporezivanja.', 'eporezna-uputa-pdv'),
  ('HR', 'HR-PDV', 'I7', 'base', 'Isporuke novih prijevoznih sredstava u EU', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 41. st. 1. t. b) — isporuka novog prijevoznog sredstva otpremljenog ili prevezenog u drugu državu članicu je oslobođena PDV-a, i to osobi koja nije registrirana za potrebe PDV-a.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I8', 'base', 'Tuzemne isporuke (oslobođene bez prava na odbitak pretporeza)', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 40. — tuzemne isporuke oslobođene PDV-a bez prava na odbitak pretporeza (npr. najam stambenih prostorija, čl. 40. st. 1. t. l).', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I9', 'base', 'Izvozne isporuke', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 45. st. 1. t. 1. — izvozna isporuka dobara otpremljenih ili prevezenih izvan Europske unije je oslobođena PDV-a s pravom na odbitak pretporeza.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I10', 'base', 'Ostala oslobođenja', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 39. — oslobođenja u javnom interesu i druga oslobođenja s pravom na odbitak pretporeza koja ne pripadaju drugom redku ovog obrasca.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I11', 'base', 'Isporuke po stopi 0%', '{}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 6. — isporuka i ugradnja solarnih ploča na privatne stambene objekte i javne te druge zgrade koje se koriste za djelatnosti od javnog interesa, i na građevine u njihovoj blizini, oporezuje se po stopi 0%.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'I', 'total', 'I. Transakcije koje ne podliježu oporezivanju, oslobođene i oporezive po stopi 0% — ukupno', '{}'::jsonb, 120, null, array['I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'I10', 'I11']::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PDV, redak I. — zbroj redaka 1. do 11.', 'obrazac-pdv'),
  ('HR', 'HR-PDV', 'II1', 'base', 'Isporuke dobara i usluga u RH po stopi 5% — osnovica', '{}'::jsonb, 200, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II1', 'tax', 'Isporuke dobara i usluga u RH po stopi 5% — PDV', '{}'::jsonb, 201, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II2', 'base', 'Isporuke dobara i usluga u RH po stopi 13% — osnovica', '{}'::jsonb, 210, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 3.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II2', 'tax', 'Isporuke dobara i usluga u RH po stopi 13% — PDV', '{}'::jsonb, 211, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 3.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II3', 'base', 'Isporuke dobara i usluga u RH po stopi 25% — osnovica', '{}'::jsonb, 220, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 1.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II3', 'tax', 'Isporuke dobara i usluga u RH po stopi 25% — PDV', '{}'::jsonb, 221, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 38. st. 1.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II4', 'base', 'Primljene isporuke u RH za koje PDV obračunava primatelj — osnovica', '{}'::jsonb, 230, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 3. t. a).', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II4', 'tax', 'Primljene isporuke u RH za koje PDV obračunava primatelj — PDV', '{}'::jsonb, 231, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 3. t. a).', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II5', 'base', 'Stjecanje dobara unutar EU po stopi 5% — osnovica', '{}'::jsonb, 240, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije; primatelj je obveznik plaćanja PDV-a.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II5', 'tax', 'Stjecanje dobara unutar EU po stopi 5% — PDV', '{}'::jsonb, 241, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II6', 'base', 'Stjecanje dobara unutar EU po stopi 13% — osnovica', '{}'::jsonb, 250, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II6', 'tax', 'Stjecanje dobara unutar EU po stopi 13% — PDV', '{}'::jsonb, 251, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II7', 'base', 'Stjecanje dobara unutar EU po stopi 25% — osnovica', '{}'::jsonb, 260, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II7', 'tax', 'Stjecanje dobara unutar EU po stopi 25% — PDV', '{}'::jsonb, 261, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV, oporezivanje stjecanja dobara unutar Europske unije.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II8', 'base', 'Primljene usluge iz EU po stopi 5% — osnovica', '{}'::jsonb, 270, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II8', 'tax', 'Primljene usluge iz EU po stopi 5% — PDV', '{}'::jsonb, 271, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II9', 'base', 'Primljene usluge iz EU po stopi 13% — osnovica', '{}'::jsonb, 280, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II9', 'tax', 'Primljene usluge iz EU po stopi 13% — PDV', '{}'::jsonb, 281, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II10', 'base', 'Primljene usluge iz EU po stopi 25% — osnovica', '{}'::jsonb, 290, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II10', 'tax', 'Primljene usluge iz EU po stopi 25% — PDV', '{}'::jsonb, 291, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II11', 'base', 'Primljene isporuke dobara i usluga od poreznih obveznika bez sjedišta u RH po stopi 0% i 5% — osnovica', '{}'::jsonb, 300, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II11', 'tax', 'Primljene isporuke dobara i usluga od poreznih obveznika bez sjedišta u RH po stopi 0% i 5% — PDV', '{}'::jsonb, 301, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II12', 'base', 'Primljene isporuke dobara i usluga od poreznih obveznika bez sjedišta u RH po stopi 13% — osnovica', '{}'::jsonb, 310, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II12', 'tax', 'Primljene isporuke dobara i usluga od poreznih obveznika bez sjedišta u RH po stopi 13% — PDV', '{}'::jsonb, 311, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II13', 'base', 'Primljene isporuke dobara i usluga od poreznih obveznika bez sjedišta u RH po stopi 25% — osnovica', '{}'::jsonb, 320, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II13', 'tax', 'Primljene isporuke dobara i usluga od poreznih obveznika bez sjedišta u RH po stopi 25% — PDV', '{}'::jsonb, 321, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II14', 'tax', 'Naknadno oslobođenje izvoza u okviru osobnog putničkog prometa', '{}'::jsonb, 330, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Uputa za popunjavanje Obrasca PDV — naknadno umanjenje obveze PDV-a kad putnik iz treće zemlje ostvari povrat poreza na robu iznesenu u osobnoj prtljazi.', 'eporezna-uputa-pdv'),
  ('HR', 'HR-PDV', 'II15', 'tax', 'Obračunani PDV pri uvozu', '{}'::jsonb, 340, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 32. st. 1. — oporezivi događaj kod uvoza dobara nastaje u trenutku uvoza; PDV obračunava i naplaćuje nadležno tijelo carinske službe.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'II', 'total', 'II. Oporezive transakcije — ukupno (PDV)', '{}'::jsonb, 350, null, array['II1:tax', 'II2:tax', 'II3:tax', 'II4:tax', 'II5:tax', 'II6:tax', 'II7:tax', 'II8:tax', 'II9:tax', 'II10:tax', 'II11:tax', 'II12:tax', 'II13:tax', 'II14', 'II15']::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PDV, redak II. — zbroj stupca PDV-a redaka 1. do 15.', 'obrazac-pdv'),
  ('HR', 'HR-PDV', 'III1', 'base', 'Pretporez od primljenih isporuka u tuzemstvu po stopi 5% — osnovica', '{}'::jsonb, 400, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61. — pravo na odbitak pretporeza.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III1', 'tax', 'Pretporez od primljenih isporuka u tuzemstvu po stopi 5% — pretporez', '{}'::jsonb, 401, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III2', 'base', 'Pretporez od primljenih isporuka u tuzemstvu po stopi 13% — osnovica', '{}'::jsonb, 410, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III2', 'tax', 'Pretporez od primljenih isporuka u tuzemstvu po stopi 13% — pretporez', '{}'::jsonb, 411, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III3', 'base', 'Pretporez od primljenih isporuka u tuzemstvu po stopi 25% — osnovica', '{}'::jsonb, 420, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III3', 'tax', 'Pretporez od primljenih isporuka u tuzemstvu po stopi 25% — pretporez', '{}'::jsonb, 421, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61., uz ograničenje odbitka iz čl. 61. st. 2. za osobne automobile i druga sredstva za osobni prijevoz.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III4', 'base', 'Pretporez od primljenih isporuka u RH za koje PDV obračunava primatelj — osnovica', '{}'::jsonb, 430, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 3. t. a) i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III4', 'tax', 'Pretporez od primljenih isporuka u RH za koje PDV obračunava primatelj — pretporez', '{}'::jsonb, 431, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 3. t. a) i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III5', 'base', 'Pretporez od stjecanja dobara unutar EU po stopi 5% — osnovica', '{}'::jsonb, 440, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III5', 'tax', 'Pretporez od stjecanja dobara unutar EU po stopi 5% — pretporez', '{}'::jsonb, 441, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III6', 'base', 'Pretporez od stjecanja dobara unutar EU po stopi 13% — osnovica', '{}'::jsonb, 450, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III6', 'tax', 'Pretporez od stjecanja dobara unutar EU po stopi 13% — pretporez', '{}'::jsonb, 451, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III7', 'base', 'Pretporez od stjecanja dobara unutar EU po stopi 25% — osnovica', '{}'::jsonb, 460, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III7', 'tax', 'Pretporez od stjecanja dobara unutar EU po stopi 25% — pretporez', '{}'::jsonb, 461, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III8', 'base', 'Pretporez od primljenih usluga iz EU po stopi 5% — osnovica', '{}'::jsonb, 470, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III8', 'tax', 'Pretporez od primljenih usluga iz EU po stopi 5% — pretporez', '{}'::jsonb, 471, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III9', 'base', 'Pretporez od primljenih usluga iz EU po stopi 13% — osnovica', '{}'::jsonb, 480, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III9', 'tax', 'Pretporez od primljenih usluga iz EU po stopi 13% — pretporez', '{}'::jsonb, 481, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III10', 'base', 'Pretporez od primljenih usluga iz EU po stopi 25% — osnovica', '{}'::jsonb, 490, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III10', 'tax', 'Pretporez od primljenih usluga iz EU po stopi 25% — pretporez', '{}'::jsonb, 491, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 1. t. 6. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III11', 'base', 'Pretporez od primljenih isporuka od poreznih obveznika bez sjedišta u RH po stopi 5% — osnovica', '{}'::jsonb, 500, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III11', 'tax', 'Pretporez od primljenih isporuka od poreznih obveznika bez sjedišta u RH po stopi 5% — pretporez', '{}'::jsonb, 501, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III12', 'base', 'Pretporez od primljenih isporuka od poreznih obveznika bez sjedišta u RH po stopi 13% — osnovica', '{}'::jsonb, 510, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III12', 'tax', 'Pretporez od primljenih isporuka od poreznih obveznika bez sjedišta u RH po stopi 13% — pretporez', '{}'::jsonb, 511, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III13', 'base', 'Pretporez od primljenih isporuka od poreznih obveznika bez sjedišta u RH po stopi 25% — osnovica', '{}'::jsonb, 520, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III13', 'tax', 'Pretporez od primljenih isporuka od poreznih obveznika bez sjedišta u RH po stopi 25% — pretporez', '{}'::jsonb, 521, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 75. st. 2. i čl. 58.-61.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III14', 'tax', 'Pretporez pri uvozu', '{}'::jsonb, 530, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 32. i čl. 58.-61. — pretporez na uvoz dobara odbija se na temelju uvozne carinske deklaracije.', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III15', 'tax', 'Ispravci pretporeza', '{}'::jsonb, 540, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Zakon o PDV čl. 63.-65. — ispravak odbitka pretporeza (promjena namjene, dugotrajna imovina).', 'zakon-pdv'),
  ('HR', 'HR-PDV', 'III', 'total', 'III. Obračunani pretporez — ukupno', '{}'::jsonb, 550, null, array['III1:tax', 'III2:tax', 'III3:tax', 'III4:tax', 'III5:tax', 'III6:tax', 'III7:tax', 'III8:tax', 'III9:tax', 'III10:tax', 'III11:tax', 'III12:tax', 'III13:tax', 'III14', 'III15']::text[], '{}'::text[], null, null, false, false, null, 'Obrazac PDV, redak III. — zbroj stupca pretporeza redaka 1. do 15.', 'obrazac-pdv'),
  ('HR', 'HR-PDV', 'IV', 'total', 'IV. Obveza PDV-a u obračunskom razdoblju: za uplatu (II. − III.) ili za povrat (III. − II.)', '{}'::jsonb, 600, null, array['II']::text[], array['III']::text[], null, null, false, false, null, 'Obrazac PDV, redak IV. — razlika obračunanog PDV-a (redak II.) i obračunanog pretporeza (redak III.); pozitivna razlika je obveza za uplatu, negativna je pravo na povrat.', 'obrazac-pdv')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('HR', 'Croatia', '{}'::jsonb, array['hr']::text[], 'EUR', '1200', '6200', '6900', '8910', '4500', '8100', '7300', '1000', '1020', 'IRA', 'URA', 'TEM', 'hr', 'result_accounts', '4610', '4620', '4510', 'OTV', 'half_up', default, '8410', '7420', null, null, null, null, '6400', '1400', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}-{YYYY}-{NNNN}',
  legal_payment_days            = 30,
  late_payment_reference        = 'Zakon o obveznim odnosima čl. 29. — zatezna kamata u trgovačkim ugovorima: referentna stopa uvećana za 8 postotnih poena, ažurirana polugodišnje (1. siječnja i 1. srpnja) i objavljena u Narodnim novinama.',
  numbering_legal_reference     = 'Zakon o PDV čl. 79. st. 1. t. 3. — račun sadrži broj računa koji ga jednoznačno identificira; obveznici fiskalizacije iskazuju broj u tri dijela (redni broj, oznaka poslovnog prostora, oznaka naplatnog uređaja). Zakon traži jednoznačnost, a ne neprekinutu godišnju numeraciju, otuda sequential i ne gapless_per_year.',
  numbering_source_key          = 'zakon-pdv',
  payment_terms_legal_reference = 'Zakon o rokovima ispunjenja novčanih obveza čl. 4. — kad ugovorom između poduzetnika nije određen rok ispunjenja novčane obveze, dužnik je obvezan ispuniti novčanu obvezu u roku od 30 dana.',
  payment_terms_source_key      = 'zakon-rokovi-placanja',
  tax_point_rule                = 'delivery_date',
  tax_point_legal_reference     = 'Zakon o PDV čl. 30. st. 1. — obveza obračuna PDV-a nastaje u trenutku kada su dobra isporučena ili usluge obavljene. St. 5. — kod predujma, obveza nastaje u trenutku primitka predujma, do visine primljenog iznosa. Ovaj pack ne modelira izdavanje računa kao zamjenu za trenutak isporuke, jer za to u Zakonu o PDV-u — za razliku od Austrije ili Luksemburga — nije pronađena opća odredba.',
  tax_point_source_key          = 'zakon-pdv',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = 'Zakon o računovodstvu čl. 9. st. 4. — poslovni događaj se u poslovnim knjigama iskazuje na temelju vjerodostojne knjigovodstvene isprave; ispravak pogrešno unesenog podatka obavlja se na način da se može utvrditi izvorni sadržaj, pa se knjižena isporuka ispravlja knjigovodstvenom ispravkom (storno knjiženjem ili odobrenjem/terećenjem), a ne izmjenom izvornog zapisa.',
  posted_edit_policy_source_key = 'zakon-pdv',
  einvoice_profile              = 'peppol-bis-3',
  einvoice_mandatory_from       = date '2026-01-01',
  einvoice_obligation           = 'mandatory',
  einvoice_legal_reference      = 'Zakon o fiskalizaciji (NN 89/25) čl. 33.-57., na snazi od 1. siječnja 2026. — svaki obveznik fiskalizacije s poslovnim nastanom u Republici Hrvatskoj mora od tog dana izdavati i zaprimati eRačune u transakcijama s drugim obveznicima fiskalizacije (B2B); tuzemni eRačun se razmjenjuje preko ovlaštenog informacijskog posrednika ili pristupne točke, u formatu UBL 2.1 s hrvatskim CIUS proširenjem HR-EXT nad Peppol BIS Billing 3.0, koji je semantički model EN 16931. mandatory_from nosi datum koji obvezuje sve odjednom — obveza zaprimanja vrijedi od 1. siječnja 2026. i za obveznike PDV-a i za one koji nisu, dok obveza izdavanja za neobveznike PDV-a počinje tek 1. siječnja 2027. i nije ovdje posebno modelirana. Prema Zakonu o elektroničkom izdavanju računa u javnoj nabavi (NN 94/18), obveza zaprimanja eRačuna u javnoj nabavi (B2G) postoji već od 1. prosinca 2018., a obveza izdavanja od 1. srpnja 2019., preko središnje platforme FINA-e; ta starija obveza ne mijenja gornju riječ jer B2B obveza od 2026. postoji za sve. profile imenuje temeljni europski format; hrvatsko CIUS proširenje HR-EXT i sama razmjena preko informacijskog posrednika/FINA-e nisu ovim pack-om modelirani — vidi docs/international.md, odjeljak "From Croatia".',
  einvoice_source_key           = 'zakon-fiskalizacija',
  party_scheme                  = null,
  vat_scheme                    = '9934',
  bank_statement_formats        = array['camt.053']::text[],
  payment_formats               = array['pain.001']::text[],
  fiscal_year_default           = 'calendar'
 where country = 'HR';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('HR', 'reverse_charge', 'reverse_charge', 'Prijenos porezne obveze', '{}'::jsonb, 10, date '1970-01-01', null, 'Zakon o PDV čl. 78. st. 1. — kad je za obračun PDV-a obvezan primatelj dobara ili usluga, umjesto iznosa PDV-a na računu se navodi napomena o prijenosu porezne obveze na primatelja.'),
  ('HR', 'intracom_goods', 'intra_eu_goods', 'Oslobođeno PDV-a — isporuka dobara unutar Europske unije (čl. 41. Zakona o PDV-u)', '{}'::jsonb, 20, date '1970-01-01', null, 'Zakon o PDV čl. 78. st. 1. t. 2. i čl. 41. st. 1. t. a) — isporuka dobara poreznom obvezniku registriranom za potrebe PDV-a u drugoj državi članici je oslobođena, a račun mora sadržavati upućivanje na odredbu na temelju koje je isporuka oslobođena.'),
  ('HR', 'intracom_services', 'intra_eu_services', 'Prijenos porezne obveze — usluga oporeziva u državi sjedišta primatelja (čl. 17. st. 1. Zakona o PDV-u)', '{}'::jsonb, 30, date '1970-01-01', null, 'Zakon o PDV čl. 78. st. 1. t. 2. i čl. 17. st. 1. — mjesto obavljanja usluge poreznom obvezniku je mjesto njegova sjedišta; kad je to druga država članica, primatelj obračunava PDV, a račun upućuje na odredbu na temelju koje se isporuka smatra oslobođenom u tuzemstvu.'),
  ('HR', 'export', 'export', 'Izvozna isporuka oslobođena PDV-a (čl. 45. Zakona o PDV-u)', '{}'::jsonb, 40, date '1970-01-01', null, 'Zakon o PDV čl. 78. st. 1. t. 2. i čl. 45. st. 1. t. 1. — izvozna isporuka dobara je oslobođena PDV-a; račun upućuje na tu odredbu.'),
  ('HR', 'exempt', 'exempt', 'Oslobođeno PDV-a bez prava na odbitak pretporeza', '{}'::jsonb, 50, date '1970-01-01', null, 'Zakon o PDV čl. 78. st. 1. t. 2. — za oslobođenu isporuku račun upućuje na odredbu Zakona o PDV-u, propisa donesenog na temelju njega ili Direktive 2006/112/EZ na temelju koje je isporuka oslobođena.'),
  ('HR', 'small_business', 'small_business', 'Oslobođeno PDV-a — mali poduzetnik (čl. 90. Zakona o PDV-u)', '{}'::jsonb, 60, date '1970-01-01', null, 'Zakon o PDV čl. 90. st. 1. — porezni obveznik s sjedištem u tuzemstvu čija vrijednost isporuka u prethodnoj kalendarskoj godini nije prešla 60.000,00 eura je oslobođen plaćanja PDV-a bez prava na odbitak pretporeza. Ni jedan stupac u jezgri ne pamti taj status poduzeća u cjelini; redak postoji za renderer koji bi ga poznavao odande.'),
  ('HR', 'late_payment', 'late_payment', 'U slučaju zakašnjenja plaćanja obračunava se zatezna kamata po stopi iz članka 29. Zakona o obveznim odnosima.', '{}'::jsonb, 70, date '1970-01-01', null, 'Zakon o obveznim odnosima čl. 29. — vidjeti documents.late_payment_reference.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
