-- Ekwo OS — Türkiye: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/tr at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build tr`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   3065 sayılı Katma Değer Vergisi Kanunu, 25/10/1984 tarihli ve 18563 sayılı Resmî Gazete'de yayımlanmış, güncel konsolide metin (Cumhurbaşkanlığı Mevzuat Bilgi Sistemi (mevzuat.gov.tr))
--     https://www.mevzuat.gov.tr/mevzuatmetin/1.5.3065.pdf
--   213 sayılı Vergi Usul Kanunu, 4/1/1961, güncel konsolide metin (Cumhurbaşkanlığı Mevzuat Bilgi Sistemi (mevzuat.gov.tr))
--     https://www.mevzuat.gov.tr/mevzuatmetin/1.4.213.pdf
--   Mal ve Hizmetlere Uygulanacak Katma Değer Vergisi Oranlarının Tespitine İlişkin Kararda Değişiklik Yapılmasına Dair Karar (Karar Sayısı: 7346), 6 Temmuz 2023 — 7/7/2023 tarihli ve 32241 sayılı Resmî Gazete, genel oranı %18'den %20'ye ve (II) sayılı listedeki oranı %8'den %10'a yükselten karar; 2007/13033 sayılı Bakanlar Kurulu Kararının (24/12/2007, 30/12/2007 tarihli ve 26742 sayılı Resmî Gazete) değişikliği (Cumhurbaşkanlığı — Resmî Gazete)
--     https://www.resmigazete.gov.tr/eskiler/2023/07/20230707-11.pdf
--   Katma Değer Vergisi Genel Uygulama Tebliği, 26/4/2014 tarihli ve 28983 sayılı Resmî Gazete, sonraki seri no'lu tebliğlerle değişik güncel metin (Hazine ve Maliye Bakanlığı — Gelir İdaresi Başkanlığı)
--     https://cdn.gib.gov.tr/api/gibportal-file/file/getFile?objectKey=MEVZUAT_TEBLIGLER%2FUNIVERSAL%2F2026%2Fkdv_genteb.pdf
--   149 Sıra No'lu Vergi Usul Kanunu Sirküleri — Katma Değer Vergisi Beyannamelerinin Verilme ve Ödeme Sürelerinin Uzatılması (1 Aralık 2022'den itibaren verilecek KDV beyannameleri için verilme ve ödeme süresi izleyen ayın 28. günü sonuna uzatılmıştır) (Gelir İdaresi Başkanlığı)
--     https://www.gib.gov.tr/149-nolu-vergi-usul-kanunu-sirkuleri-ile-katma-deger-vergisi-beyannamelerinin-verilme-ve-odeme
--   e-Fatura, e-Arşiv Fatura ve e-Defter uygulamaları — 509 Sıra No'lu Vergi Usul Kanunu Genel Tebliği ve sonraki değişiklikleri (535, 550, 573, 589 sıra no'lu tebliğler dahil) (Gelir İdaresi Başkanlığı)
--     https://ebelge.gib.gov.tr/efaturamevzuat.html
--   1 Sıra No'lu Muhasebe Sistemi Uygulama Genel Tebliği — Tekdüzen Hesap Çerçevesi, Hesap Planı ve İşleyişi, 26/12/1992 tarihli ve 21447 sayılı Resmî Gazete (Maliye ve Gümrük Bakanlığı)
--     https://www.resmigazete.gov.tr/arsiv/21447_1.pdf
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('TR', 'Türkiye', '0.1.0', date '2026-09-25', '20260917170000', 'community', null, null, '3774ee7cbc4e04f042a8957ff8746487ebc897434ee75fabb70a6a0f1146bbec', '[{"key":"kdv-kanunu","title":"3065 sayılı Katma Değer Vergisi Kanunu, 25/10/1984 tarihli ve 18563 sayılı Resmî Gazete''de yayımlanmış, güncel konsolide metin","publisher":"Cumhurbaşkanlığı Mevzuat Bilgi Sistemi (mevzuat.gov.tr)","url":"https://www.mevzuat.gov.tr/mevzuatmetin/1.5.3065.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"vuk","title":"213 sayılı Vergi Usul Kanunu, 4/1/1961, güncel konsolide metin","publisher":"Cumhurbaşkanlığı Mevzuat Bilgi Sistemi (mevzuat.gov.tr)","url":"https://www.mevzuat.gov.tr/mevzuatmetin/1.4.213.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"kdv-oran-karari","title":"Mal ve Hizmetlere Uygulanacak Katma Değer Vergisi Oranlarının Tespitine İlişkin Kararda Değişiklik Yapılmasına Dair Karar (Karar Sayısı: 7346), 6 Temmuz 2023 — 7/7/2023 tarihli ve 32241 sayılı Resmî Gazete, genel oranı %18''den %20''ye ve (II) sayılı listedeki oranı %8''den %10''a yükselten karar; 2007/13033 sayılı Bakanlar Kurulu Kararının (24/12/2007, 30/12/2007 tarihli ve 26742 sayılı Resmî Gazete) değişikliği","publisher":"Cumhurbaşkanlığı — Resmî Gazete","url":"https://www.resmigazete.gov.tr/eskiler/2023/07/20230707-11.pdf","consulted_on":"2026-09-25","kind":"regulation"},{"key":"kdv-genel-uygulama-tebligi","title":"Katma Değer Vergisi Genel Uygulama Tebliği, 26/4/2014 tarihli ve 28983 sayılı Resmî Gazete, sonraki seri no''lu tebliğlerle değişik güncel metin","publisher":"Hazine ve Maliye Bakanlığı — Gelir İdaresi Başkanlığı","url":"https://cdn.gib.gov.tr/api/gibportal-file/file/getFile?objectKey=MEVZUAT_TEBLIGLER%2FUNIVERSAL%2F2026%2Fkdv_genteb.pdf","consulted_on":"2026-09-25","kind":"regulation"},{"key":"gib-beyan-uzatma","title":"149 Sıra No''lu Vergi Usul Kanunu Sirküleri — Katma Değer Vergisi Beyannamelerinin Verilme ve Ödeme Sürelerinin Uzatılması (1 Aralık 2022''den itibaren verilecek KDV beyannameleri için verilme ve ödeme süresi izleyen ayın 28. günü sonuna uzatılmıştır)","publisher":"Gelir İdaresi Başkanlığı","url":"https://www.gib.gov.tr/149-nolu-vergi-usul-kanunu-sirkuleri-ile-katma-deger-vergisi-beyannamelerinin-verilme-ve-odeme","consulted_on":"2026-09-25","kind":"guidance"},{"key":"gib-efatura","title":"e-Fatura, e-Arşiv Fatura ve e-Defter uygulamaları — 509 Sıra No''lu Vergi Usul Kanunu Genel Tebliği ve sonraki değişiklikleri (535, 550, 573, 589 sıra no''lu tebliğler dahil)","publisher":"Gelir İdaresi Başkanlığı","url":"https://ebelge.gib.gov.tr/efaturamevzuat.html","consulted_on":"2026-09-25","kind":"portal"},{"key":"muhasebe-tebligi-1","title":"1 Sıra No''lu Muhasebe Sistemi Uygulama Genel Tebliği — Tekdüzen Hesap Çerçevesi, Hesap Planı ve İşleyişi, 26/12/1992 tarihli ve 21447 sayılı Resmî Gazete","publisher":"Maliye ve Gümrük Bakanlığı","url":"https://www.resmigazete.gov.tr/arsiv/21447_1.pdf","consulted_on":"2026-09-25","kind":"regulation"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('TR', 'default', 'Tekdüzen Hesap Planı', '{}'::jsonb, true, 'companies', array['TR-TDHP-BILANCO', 'TR-TDHP-GELIR']::text[], null, '1 Sıra No''lu Muhasebe Sistemi Uygulama Genel Tebliği, bilânço esasına göre defter tutan gerçek ve tüzel kişilerin Tekdüzen Hesap Çerçevesi''ni, Hesap Planı''nı ve işleyiş kurallarını 1/1/1994 tarihinden itibaren uygulamalarını zorunlu kılar. Bu pack yalnızca üç haneli ana hesapları (Tebliğ''in kendisinin belirlediği, değiştirilemez) ve KDV ile tahsilat/ödeme işleyişi için gerekli birkaç dört haneli alt hesabı taşır; bir işletmenin tuttuğu tüm alt hesaplar burada sayılmamıştır.', 'muhasebe-tebligi-1')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('TR', 'default', '100', 'Kasa', '{}'::jsonb, 'asset_cash', false, null, 10),
  ('TR', 'default', '101', 'Alınan Çekler', '{}'::jsonb, 'asset_cash', false, null, 15),
  ('TR', 'default', '102', 'Bankalar', '{}'::jsonb, 'asset_cash', false, null, 20),
  ('TR', 'default', '103', 'Verilen Çekler ve Ödeme Emirleri (-)', '{}'::jsonb, 'asset_cash', false, null, 25),
  ('TR', 'default', '108', 'Diğer Hazır Değerler', '{}'::jsonb, 'asset_cash', false, null, 28),
  ('TR', 'default', '110', 'Hisse Senetleri', '{}'::jsonb, 'asset_current', false, null, 30),
  ('TR', 'default', '111', 'Özel Kesim Tahvil Senet ve Bonoları', '{}'::jsonb, 'asset_current', false, null, 31),
  ('TR', 'default', '112', 'Kamu Kesimi Tahvil Senet ve Bonoları', '{}'::jsonb, 'asset_current', false, null, 32),
  ('TR', 'default', '118', 'Diğer Menkul Kıymetler', '{}'::jsonb, 'asset_current', false, null, 33),
  ('TR', 'default', '119', 'Menkul Değerler Değer Düşüklüğü Karşılığı (-)', '{}'::jsonb, 'asset_current', false, null, 34),
  ('TR', 'default', '120', 'Alıcılar', '{}'::jsonb, 'asset_receivable', true, null, 40),
  ('TR', 'default', '121', 'Alacak Senetleri', '{}'::jsonb, 'asset_current', false, null, 41),
  ('TR', 'default', '122', 'Alacak Senetleri Reeskontu (-)', '{}'::jsonb, 'asset_current', false, null, 42),
  ('TR', 'default', '126', 'Verilen Depozito ve Teminatlar', '{}'::jsonb, 'asset_current', false, null, 43),
  ('TR', 'default', '127', 'Diğer Ticari Alacaklar', '{}'::jsonb, 'asset_current', false, null, 44),
  ('TR', 'default', '128', 'Şüpheli Ticari Alacaklar', '{}'::jsonb, 'asset_current', false, null, 45),
  ('TR', 'default', '129', 'Şüpheli Alacaklar Karşılığı (-)', '{}'::jsonb, 'asset_current', false, null, 46),
  ('TR', 'default', '131', 'Ortaklardan Alacaklar', '{}'::jsonb, 'asset_current', false, null, 50),
  ('TR', 'default', '132', 'İştiraklerden Alacaklar', '{}'::jsonb, 'asset_current', false, null, 51),
  ('TR', 'default', '133', 'Bağlı Ortaklıklardan Alacaklar', '{}'::jsonb, 'asset_current', false, null, 52),
  ('TR', 'default', '135', 'Personelden Alacaklar', '{}'::jsonb, 'asset_current', false, null, 53),
  ('TR', 'default', '136', 'Diğer Çeşitli Alacaklar', '{}'::jsonb, 'asset_current', false, null, 54),
  ('TR', 'default', '1369', 'Geçici Hesap (Askıda Tutulan İşlemler)', '{}'::jsonb, 'asset_current', false, '136', 55),
  ('TR', 'default', '137', 'Diğer Alacak Senetleri Reeskontu (-)', '{}'::jsonb, 'asset_current', false, null, 56),
  ('TR', 'default', '138', 'Şüpheli Diğer Alacaklar', '{}'::jsonb, 'asset_current', false, null, 57),
  ('TR', 'default', '139', 'Şüpheli Diğer Alacaklar Karşılığı (-)', '{}'::jsonb, 'asset_current', false, null, 58),
  ('TR', 'default', '151', 'Yarı Mamuller — Üretim', '{}'::jsonb, 'asset_current', false, null, 60),
  ('TR', 'default', '152', 'Mamuller', '{}'::jsonb, 'asset_current', false, null, 61),
  ('TR', 'default', '153', 'Ticari Mallar', '{}'::jsonb, 'asset_current', false, null, 62),
  ('TR', 'default', '157', 'Diğer Stoklar', '{}'::jsonb, 'asset_current', false, null, 63),
  ('TR', 'default', '158', 'Stok Değer Düşüklüğü Karşılığı (-)', '{}'::jsonb, 'asset_current', false, null, 64),
  ('TR', 'default', '159', 'Verilen Sipariş Avansları', '{}'::jsonb, 'asset_current', false, null, 65),
  ('TR', 'default', '180', 'Gelecek Aylara Ait Giderler', '{}'::jsonb, 'asset_prepayments', false, null, 70),
  ('TR', 'default', '181', 'Gelir Tahakkukları', '{}'::jsonb, 'asset_prepayments', false, null, 71),
  ('TR', 'default', '190', 'Devreden Katma Değer Vergisi', '{}'::jsonb, 'asset_current', false, null, 80),
  ('TR', 'default', '191', 'İndirilecek KDV', '{}'::jsonb, 'asset_current', false, null, 81),
  ('TR', 'default', '192', 'Diğer Katma Değer Vergisi', '{}'::jsonb, 'asset_current', true, null, 82),
  ('TR', 'default', '193', 'Peşin Ödenen Vergiler ve Fonlar', '{}'::jsonb, 'asset_prepayments', false, null, 83),
  ('TR', 'default', '195', 'İş Avansları', '{}'::jsonb, 'asset_current', false, null, 84),
  ('TR', 'default', '196', 'Personel Avansları', '{}'::jsonb, 'asset_current', false, null, 85),
  ('TR', 'default', '197', 'Sayım ve Tesellüm Noksanları', '{}'::jsonb, 'asset_current', false, null, 86),
  ('TR', 'default', '198', 'Diğer Çeşitli Dönen Varlıklar', '{}'::jsonb, 'asset_current', false, null, 87),
  ('TR', 'default', '199', 'Diğer Dönen Varlıklar Karşılığı (-)', '{}'::jsonb, 'asset_current', false, null, 88),
  ('TR', 'default', '220', 'Alıcılar (Uzun Vadeli)', '{}'::jsonb, 'asset_non_current', false, null, 100),
  ('TR', 'default', '226', 'Verilen Depozito ve Teminatlar', '{}'::jsonb, 'asset_non_current', false, null, 101),
  ('TR', 'default', '229', 'Şüpheli Alacaklar Karşılığı (-)', '{}'::jsonb, 'asset_non_current', false, null, 102),
  ('TR', 'default', '240', 'Bağlı Menkul Kıymetler', '{}'::jsonb, 'asset_non_current', false, null, 110),
  ('TR', 'default', '242', 'İştirakler', '{}'::jsonb, 'asset_non_current', false, null, 111),
  ('TR', 'default', '245', 'Bağlı Ortaklıklar', '{}'::jsonb, 'asset_non_current', false, null, 112),
  ('TR', 'default', '248', 'Diğer Mali Duran Varlıklar', '{}'::jsonb, 'asset_non_current', false, null, 113),
  ('TR', 'default', '251', 'Yeraltı ve Yerüstü Düzenleri', '{}'::jsonb, 'asset_fixed', false, null, 120),
  ('TR', 'default', '252', 'Binalar', '{}'::jsonb, 'asset_fixed', false, null, 121),
  ('TR', 'default', '253', 'Tesis Makine ve Cihazlar', '{}'::jsonb, 'asset_fixed', false, null, 122),
  ('TR', 'default', '254', 'Taşıtlar', '{}'::jsonb, 'asset_fixed', false, null, 123),
  ('TR', 'default', '255', 'Demirbaşlar', '{}'::jsonb, 'asset_fixed', false, null, 124),
  ('TR', 'default', '256', 'Diğer Maddi Duran Varlıklar', '{}'::jsonb, 'asset_fixed', false, null, 125),
  ('TR', 'default', '257', 'Birikmiş Amortismanlar (-)', '{}'::jsonb, 'asset_fixed', false, null, 126),
  ('TR', 'default', '258', 'Yapılmakta Olan Yatırımlar', '{}'::jsonb, 'asset_fixed', false, null, 127),
  ('TR', 'default', '259', 'Verilen Avanslar', '{}'::jsonb, 'asset_fixed', false, null, 128),
  ('TR', 'default', '260', 'Haklar', '{}'::jsonb, 'asset_non_current', false, null, 130),
  ('TR', 'default', '261', 'Şerefiye', '{}'::jsonb, 'asset_non_current', false, null, 131),
  ('TR', 'default', '262', 'Kuruluş ve Örgütlenme Giderleri', '{}'::jsonb, 'asset_non_current', false, null, 132),
  ('TR', 'default', '263', 'Araştırma ve Geliştirme Giderleri', '{}'::jsonb, 'asset_non_current', false, null, 133),
  ('TR', 'default', '264', 'Özel Maliyetler', '{}'::jsonb, 'asset_non_current', false, null, 134),
  ('TR', 'default', '267', 'Diğer Maddi Olmayan Duran Varlıklar', '{}'::jsonb, 'asset_non_current', false, null, 135),
  ('TR', 'default', '268', 'Birikmiş Amortismanlar (-) (İtfa Payları)', '{}'::jsonb, 'asset_non_current', false, null, 136),
  ('TR', 'default', '269', 'Verilen Avanslar', '{}'::jsonb, 'asset_non_current', false, null, 137),
  ('TR', 'default', '280', 'Gelecek Yıllara Ait Giderler', '{}'::jsonb, 'asset_prepayments', false, null, 140),
  ('TR', 'default', '281', 'Gelir Tahakkukları', '{}'::jsonb, 'asset_prepayments', false, null, 141),
  ('TR', 'default', '291', 'Gelecek Yıllarda İndirilecek KDV', '{}'::jsonb, 'asset_non_current', false, null, 150),
  ('TR', 'default', '292', 'Diğer KDV', '{}'::jsonb, 'asset_non_current', false, null, 151),
  ('TR', 'default', '293', 'Gelecek Yıllar İhtiyacı Stoklar', '{}'::jsonb, 'asset_non_current', false, null, 152),
  ('TR', 'default', '294', 'Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar', '{}'::jsonb, 'asset_non_current', false, null, 153),
  ('TR', 'default', '297', 'Diğer Çeşitli Duran Varlıklar', '{}'::jsonb, 'asset_non_current', false, null, 154),
  ('TR', 'default', '298', 'Stok Değer Düşüklüğü Karşılığı (-)', '{}'::jsonb, 'asset_non_current', false, null, 155),
  ('TR', 'default', '299', 'Birikmiş Amortismanlar (-)', '{}'::jsonb, 'asset_non_current', false, null, 156),
  ('TR', 'default', '300', 'Banka Kredileri (Kısa Vadeli)', '{}'::jsonb, 'liability_current', false, null, 170),
  ('TR', 'default', '303', 'Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri', '{}'::jsonb, 'liability_current', false, null, 171),
  ('TR', 'default', '309', 'Diğer Mali Borçlar', '{}'::jsonb, 'liability_current', false, null, 172),
  ('TR', 'default', '320', 'Satıcılar', '{}'::jsonb, 'liability_payable', true, null, 180),
  ('TR', 'default', '321', 'Borç Senetleri', '{}'::jsonb, 'liability_current', false, null, 181),
  ('TR', 'default', '322', 'Borç Senetleri Reeskontu (-)', '{}'::jsonb, 'liability_current', false, null, 182),
  ('TR', 'default', '326', 'Alınan Depozito ve Teminatlar', '{}'::jsonb, 'liability_current', false, null, 183),
  ('TR', 'default', '329', 'Diğer Ticari Borçlar', '{}'::jsonb, 'liability_current', false, null, 184),
  ('TR', 'default', '331', 'Ortaklara Borçlar', '{}'::jsonb, 'liability_current', false, null, 190),
  ('TR', 'default', '332', 'İştiraklere Borçlar', '{}'::jsonb, 'liability_current', false, null, 191),
  ('TR', 'default', '333', 'Bağlı Ortaklıklara Borçlar', '{}'::jsonb, 'liability_current', false, null, 192),
  ('TR', 'default', '334', 'Üyelere Borçlar', '{}'::jsonb, 'liability_current', false, null, 193),
  ('TR', 'default', '335', 'Personele Borçlar', '{}'::jsonb, 'liability_current', false, null, 194),
  ('TR', 'default', '336', 'Diğer Çeşitli Borçlar', '{}'::jsonb, 'liability_current', false, null, 195),
  ('TR', 'default', '337', 'Diğer Borç Senetleri Reeskontu (-)', '{}'::jsonb, 'liability_current', false, null, 196),
  ('TR', 'default', '340', 'Alınan Sipariş Avansları', '{}'::jsonb, 'liability_current', false, null, 200),
  ('TR', 'default', '349', 'Alınan Diğer Avanslar', '{}'::jsonb, 'liability_current', false, null, 201),
  ('TR', 'default', '360', 'Ödenecek Vergi ve Fonlar', '{}'::jsonb, 'liability_current', false, null, 220),
  ('TR', 'default', '3600', 'Ödenecek Katma Değer Vergisi', '{}'::jsonb, 'liability_current', true, '360', 221),
  ('TR', 'default', '361', 'Ödenecek Sosyal Güvenlik Kesintileri', '{}'::jsonb, 'liability_current', false, null, 222),
  ('TR', 'default', '368', 'Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler', '{}'::jsonb, 'liability_current', false, null, 223),
  ('TR', 'default', '369', 'Ödenecek Diğer Yükümlülükler', '{}'::jsonb, 'liability_current', false, null, 224),
  ('TR', 'default', '370', 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları', '{}'::jsonb, 'liability_current', false, null, 230),
  ('TR', 'default', '371', 'Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)', '{}'::jsonb, 'liability_current', false, null, 231),
  ('TR', 'default', '372', 'Kıdem Tazminatı Karşılığı (Kısa Vadeli)', '{}'::jsonb, 'liability_current', false, null, 232),
  ('TR', 'default', '373', 'Maliyet Giderleri Karşılığı', '{}'::jsonb, 'liability_current', false, null, 233),
  ('TR', 'default', '379', 'Diğer Borç ve Gider Karşılıkları', '{}'::jsonb, 'liability_current', false, null, 234),
  ('TR', 'default', '380', 'Gelecek Aylara Ait Gelirler', '{}'::jsonb, 'liability_current', false, null, 240),
  ('TR', 'default', '381', 'Gider Tahakkukları', '{}'::jsonb, 'liability_current', false, null, 241),
  ('TR', 'default', '391', 'Hesaplanan KDV', '{}'::jsonb, 'liability_current', false, null, 250),
  ('TR', 'default', '392', 'Diğer KDV (Sorumlu Sıfatıyla Beyan Edilecek)', '{}'::jsonb, 'liability_current', false, null, 251),
  ('TR', 'default', '393', 'Merkez ve Şubeler Cari Hesabı', '{}'::jsonb, 'liability_current', false, null, 252),
  ('TR', 'default', '397', 'Sayım ve Tesellüm Fazlaları', '{}'::jsonb, 'liability_current', false, null, 253),
  ('TR', 'default', '399', 'Diğer Çeşitli Kısa Vadeli Yabancı Kaynaklar', '{}'::jsonb, 'liability_current', false, null, 254),
  ('TR', 'default', '400', 'Banka Kredileri (Uzun Vadeli)', '{}'::jsonb, 'liability_non_current', false, null, 270),
  ('TR', 'default', '409', 'Diğer Mali Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 271),
  ('TR', 'default', '421', 'Borç Senetleri', '{}'::jsonb, 'liability_non_current', false, null, 280),
  ('TR', 'default', '422', 'Borç Senetleri Reeskontu (-)', '{}'::jsonb, 'liability_non_current', false, null, 281),
  ('TR', 'default', '426', 'Alınan Depozito ve Teminatlar', '{}'::jsonb, 'liability_non_current', false, null, 282),
  ('TR', 'default', '429', 'Diğer Ticari Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 283),
  ('TR', 'default', '431', 'Ortaklara Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 290),
  ('TR', 'default', '432', 'İştiraklere Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 291),
  ('TR', 'default', '433', 'Bağlı Ortaklıklara Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 292),
  ('TR', 'default', '434', 'Üyelere Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 293),
  ('TR', 'default', '436', 'Diğer Çeşitli Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 294),
  ('TR', 'default', '437', 'Diğer Borç Senetleri Reeskontu (-)', '{}'::jsonb, 'liability_non_current', false, null, 295),
  ('TR', 'default', '438', 'Kamuya Olan Ertelenmiş veya Taksitlendirilmiş Borçlar', '{}'::jsonb, 'liability_non_current', false, null, 296),
  ('TR', 'default', '440', 'Alınan Sipariş Avansları', '{}'::jsonb, 'liability_non_current', false, null, 300),
  ('TR', 'default', '449', 'Alınan Diğer Avanslar', '{}'::jsonb, 'liability_non_current', false, null, 301),
  ('TR', 'default', '472', 'Kıdem Tazminatı Karşılığı (Uzun Vadeli)', '{}'::jsonb, 'liability_non_current', false, null, 310),
  ('TR', 'default', '479', 'Diğer Borç ve Gider Karşılıkları', '{}'::jsonb, 'liability_non_current', false, null, 311),
  ('TR', 'default', '480', 'Gelecek Yıllara Ait Gelirler', '{}'::jsonb, 'liability_non_current', false, null, 320),
  ('TR', 'default', '481', 'Gider Tahakkukları', '{}'::jsonb, 'liability_non_current', false, null, 321),
  ('TR', 'default', '492', 'Gelecek Yıllara Ertelenen veya Terkin Edilecek KDV', '{}'::jsonb, 'liability_non_current', false, null, 330),
  ('TR', 'default', '493', 'Tesise Katılma Payları', '{}'::jsonb, 'liability_non_current', false, null, 331),
  ('TR', 'default', '499', 'Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar', '{}'::jsonb, 'liability_non_current', false, null, 332),
  ('TR', 'default', '500', 'Sermaye', '{}'::jsonb, 'equity', false, null, 350),
  ('TR', 'default', '501', 'Ödenmiş Sermaye (-)', '{}'::jsonb, 'equity', false, null, 351),
  ('TR', 'default', '522', 'Maddi Duran Varlık Yeniden Değerleme Artışları', '{}'::jsonb, 'equity', false, null, 360),
  ('TR', 'default', '523', 'İştirakler Yeniden Değerleme Artışları', '{}'::jsonb, 'equity', false, null, 361),
  ('TR', 'default', '529', 'Diğer Sermaye Yedekleri', '{}'::jsonb, 'equity', false, null, 362),
  ('TR', 'default', '540', 'Yasal Yedekler', '{}'::jsonb, 'equity', false, null, 370),
  ('TR', 'default', '541', 'Statü Yedekleri', '{}'::jsonb, 'equity', false, null, 371),
  ('TR', 'default', '542', 'Olağanüstü Yedekler', '{}'::jsonb, 'equity', false, null, 372),
  ('TR', 'default', '548', 'Diğer Kâr Yedekleri', '{}'::jsonb, 'equity', false, null, 373),
  ('TR', 'default', '549', 'Özel Fonlar', '{}'::jsonb, 'equity', false, null, 374),
  ('TR', 'default', '570', 'Geçmiş Yıllar Karları', '{}'::jsonb, 'equity_retained', false, null, 380),
  ('TR', 'default', '580', 'Geçmiş Yıllar Zararları (-)', '{}'::jsonb, 'equity_retained', false, null, 390),
  ('TR', 'default', '590', 'Dönem Net Karı', '{}'::jsonb, 'equity_retained', false, null, 400),
  ('TR', 'default', '591', 'Dönem Net Zararı (-)', '{}'::jsonb, 'equity_retained', false, null, 401),
  ('TR', 'default', '600', 'Yurtiçi Satışlar', '{}'::jsonb, 'income', false, null, 410),
  ('TR', 'default', '601', 'Yurtdışı Satışlar', '{}'::jsonb, 'income', false, null, 411),
  ('TR', 'default', '602', 'Diğer Gelirler', '{}'::jsonb, 'income_other', false, null, 412),
  ('TR', 'default', '603', 'Bağış ve Yardımlar', '{}'::jsonb, 'income_other', false, null, 413),
  ('TR', 'default', '604', 'Prim ve Aidatlar', '{}'::jsonb, 'income_other', false, null, 414),
  ('TR', 'default', '610', 'Satıştan İadeler (-)', '{}'::jsonb, 'income', false, null, 420),
  ('TR', 'default', '611', 'Satış İskontoları (-)', '{}'::jsonb, 'income', false, null, 421),
  ('TR', 'default', '620', 'Satılan Mamuller Maliyeti (-)', '{}'::jsonb, 'expense_direct_cost', false, null, 430),
  ('TR', 'default', '621', 'Satılan Ticari Mallar Maliyeti (-)', '{}'::jsonb, 'expense_direct_cost', false, null, 431),
  ('TR', 'default', '622', 'Satılan Hizmet Maliyeti (-)', '{}'::jsonb, 'expense_direct_cost', false, null, 432),
  ('TR', 'default', '630', 'Araştırma ve Geliştirme Giderleri (-)', '{}'::jsonb, 'expense', false, null, 440),
  ('TR', 'default', '631', 'Pazarlama Satış ve Dağıtım Giderleri (-)', '{}'::jsonb, 'expense', false, null, 441),
  ('TR', 'default', '632', 'Genel Yönetim Giderleri (-)', '{}'::jsonb, 'expense', false, null, 442),
  ('TR', 'default', '640', 'İştiraklerden Temettü Gelirleri', '{}'::jsonb, 'income_other', false, null, 450),
  ('TR', 'default', '641', 'Bağlı Ortaklıklardan Temettü Gelirleri', '{}'::jsonb, 'income_other', false, null, 451),
  ('TR', 'default', '642', 'Faiz Gelirleri', '{}'::jsonb, 'income_other', false, null, 452),
  ('TR', 'default', '644', 'Konusu Kalmayan Karşılıklar', '{}'::jsonb, 'income_other', false, null, 453),
  ('TR', 'default', '645', 'Menkul Kıymet Satış Karları', '{}'::jsonb, 'income_other', false, null, 454),
  ('TR', 'default', '646', 'Kambiyo Karları', '{}'::jsonb, 'income_other', false, null, 455),
  ('TR', 'default', '647', 'Reeskont Faiz Gelirleri', '{}'::jsonb, 'income_other', false, null, 456),
  ('TR', 'default', '648', 'İktisadi İşletme Gelirleri', '{}'::jsonb, 'income_other', false, null, 457),
  ('TR', 'default', '649', 'Diğer Olağan Gelir ve Karlar', '{}'::jsonb, 'income_other', false, null, 458),
  ('TR', 'default', '653', 'Komisyon Giderleri (-)', '{}'::jsonb, 'expense', false, null, 460),
  ('TR', 'default', '654', 'Karşılık Giderleri (-)', '{}'::jsonb, 'expense', false, null, 461),
  ('TR', 'default', '655', 'Menkul Kıymet Satış Zararları (-)', '{}'::jsonb, 'expense', false, null, 462),
  ('TR', 'default', '656', 'Kambiyo Zararları (-)', '{}'::jsonb, 'expense', false, null, 463),
  ('TR', 'default', '657', 'Reeskont Faiz Giderleri (-)', '{}'::jsonb, 'expense', false, null, 464),
  ('TR', 'default', '659', 'Diğer Gider ve Zararlar (-)', '{}'::jsonb, 'expense', false, null, 465),
  ('TR', 'default', '660', 'Kısa Vadeli Borçlanma Giderleri (-)', '{}'::jsonb, 'expense', false, null, 470),
  ('TR', 'default', '671', 'Önceki Dönem Gelir ve Karları', '{}'::jsonb, 'income_other', false, null, 480),
  ('TR', 'default', '679', 'Diğer Olağandışı Gelir ve Karlar', '{}'::jsonb, 'income_other', false, null, 481),
  ('TR', 'default', '680', 'Çalışmayan Kısım Gider ve Zararları (-)', '{}'::jsonb, 'expense', false, null, 490),
  ('TR', 'default', '681', 'Önceki Dönem Gider ve Zararları (-)', '{}'::jsonb, 'expense', false, null, 491),
  ('TR', 'default', '689', 'Diğer Olağandışı Gider ve Zararlar (-)', '{}'::jsonb, 'expense', false, null, 492)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('TR', 'BNK', 'Banka', '{}'::jsonb, 'bank', 30),
  ('TR', 'CSH', 'Kasa', '{}'::jsonb, 'cash', 40),
  ('TR', 'GEN', 'Genel Yevmiye', '{}'::jsonb, 'general', 50),
  ('TR', 'OPN', 'Açılış Kayıtları', '{}'::jsonb, 'opening', 60),
  ('TR', 'PUR', 'Alış Yevmiyesi', '{}'::jsonb, 'purchase', 20),
  ('TR', 'SAL', 'Satış Yevmiyesi', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('TR', 'TR-P-EX', 'Alış, istisna kapsamındaki mal veya hizmet', '{}'::jsonb, 'BSMV kapsamındaki bir sigorta ya da finansal işlem gibi, üzerinde hiç KDV hesaplanmamış bir alış.', 'percent', 0, 'purchase', 'exempt', date '1985-01-01', null, '3065 sayılı Kanun, madde 17/4-e — satıcı BSMV kapsamında işlem yaptığından faturada KDV hesaplanmaz, dolayısıyla indirilecek bir tutar da doğmaz.', 'E', null, 90, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null),
  ('TR', 'TR-P-IMP', 'Alış, mal ithalatı, gümrükte ödenen ve indirilebilir KDV', '{}'::jsonb, 'Yurt dışından satın alınan ve Türkiye gümrük bölgesine giren bir malın ithalinde gümrük idaresine, gümrük vergisi ile birlikte ve aynı anda ödenen KDV.', 'percent', 20, 'purchase', 'import', date '2023-07-10', null, '3065 sayılı Kanun, madde 1/2 (her türlü mal ithalatı verginin konusuna girer); madde 21 (ithalatta matrah, malın gümrük vergisi tarhına esas kıymeti — bulunmadığı hâllerde CİF değeri — artı ithalat sırasında ödenen her türlü vergi, resim, harç ve paylardır); madde 46/2 (ithalde alınan KDV, gümrük vergisi ile birlikte ve aynı zamanda ödenir); madde 29 (bu KDV, ödendiği dönemde indirim konusu yapılır). Türkiye Avrupa Birliği gümrük birliği dışında kaldığından mal ithalatında bir topluluk içi alım (intracom_acquisition_goods) değil, doğrudan bir ithalat söz konusudur ve bu KDV — Körfez ülkeleri paketlerinin (AE, SA) aksine — dönem beyannamesinde bir sorumluluk (reverse charge) olarak değil, gümrükte fiilen ödenmiş ve sonradan indirilen bir tutar olarak izlenir.', null, null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null),
  ('TR', 'TR-P-NR', 'Alış, KDV mükellefi olmayan satıcıdan', '{}'::jsonb, 'Esnaf muaflığından yararlanan ya da KDV mükellefiyeti bulunmayan bir satıcıdan yapılan, üzerinde KDV hesaplanmamış alış.', 'percent', 0, 'purchase', 'not_subject', date '1985-01-01', null, 'Satıcı 3065 sayılı Kanun''un mükellefi olmadığından (madde 1 ve madde 8) fatura üzerinde hesaplanmış bir KDV yoktur.', 'O', null, 100, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null),
  ('TR', 'TR-P-RC-SVC', 'Alış, yurt dışından hizmet ithali, sorumlu sıfatıyla KDV', '{}'::jsonb, 'Türkiye''de ikametgâhı, işyeri, kanuni merkezi ve iş merkezi bulunmayan bir satıcıdan alınan ve Türkiye''de faydalanılan bir hizmet — hizmeti alan, KDV''yi kendisi hesaplayıp sorumlu sıfatıyla beyan eder.', 'percent', 20, 'purchase', 'foreign_services_received', date '2023-07-10', null, '3065 sayılı Kanun, madde 1 (hizmetten Türkiye''de faydalanılması verginin konusuna sokar) ve madde 9/1 (Maliye Bakanlığı, Türkiye''de ikametgâhı, işyeri, kanuni ve iş merkezi bulunmayanlar tarafından yapılan işlemlerde, işleme taraf olanı verginin ödenmesinden sorumlu tutabilir; Katma Değer Vergisi Genel Uygulama Tebliği I/C-2.1.2.1 bu sorumluluğu tam tevkifat olarak düzenler). Bu KDV, 2 No''lu KDV Beyannamesi ile ayrı olarak beyan edilip ödenir — bu pack''in tax_report.json''ı yalnızca 1 No''lu KDV Beyannamesini modeller, bu yüzden bu tutarın kendisi hiçbir kutuya yazılmaz; madde 29 uyarınca aynı dönemde 1 No''lu beyannamede indirim konusu yapılabilen payı ise İndirilecek KDV tablosunda izlenir.', null, null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-genel-uygulama-tebligi', null, null, null, null),
  ('TR', 'TR-P-RR10', 'Alış, indirimli oran, KDV %10, indirilebilir', '{}'::jsonb, '(II) sayılı listede sayılan bir alış.', 'percent', 10, 'purchase', 'domestic', date '2023-07-10', null, '3065 sayılı Kanun, madde 28 ve madde 29; 2007/13033 sayılı Bakanlar Kurulu Kararı eki (II) sayılı liste.', 'S', null, 80, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-oran-karari', null, null, null, null),
  ('TR', 'TR-P-SR', 'Alış, genel oran, KDV %20, indirilebilir', '{}'::jsonb, 'Genel orana tabi ve indirim hakkı doğuran alış.', 'percent', 20, 'purchase', 'domestic', date '2023-07-10', null, '3065 sayılı Kanun, madde 28 (oran) ve madde 29 (mükellefler, faaliyetlerine ilişkin olarak kendilerine yapılan teslim ve hizmetler dolayısıyla hesaplanan KDV''yi, faaliyetlerine ait vergiye tabi işlemler üzerinden hesaplanan KDV''den indirebilirler).', 'S', null, 70, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null),
  ('TR', 'TR-S-EX-FIN', 'Satış, BSMV kapsamındaki işlemler istisnası', '{}'::jsonb, 'Banka ve Sigorta Muameleleri Vergisi kapsamına giren işlemler ile sigorta acente ve prodüktörlerinin sigorta muamelelerine ilişkin işlemleri.', 'percent', 0, 'sale', 'exempt', date '1985-01-01', null, '3065 sayılı Kanun, madde 17/4-e — Banka ve Sigorta Muameleleri Vergisi Kanunu kapsamına giren işlemler ile sigorta acente ve prodüktörlerinin sigorta muamelelerine ilişkin işlemleri vergiden müstesnadır. 6802 sayılı Gider Vergileri Kanunu madde 28 vd., sigorta şirketlerinin lehlerine aldıkları paraları BSMV''ye tabi tutar; madde 30 mükellefiyeti sigorta şirketlerine yükler, acente ve prodüktörlerin komisyonları da bu kapsamdadır. Türkiye Avrupa Birliği ortak KDV sistemi dışında olduğundan bu satırda bir VATEX kodu yerine yalnızca madde ataması yapılmıştır.', 'E', null, 50, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null),
  ('TR', 'TR-S-OS', 'Satış, verginin konusuna girmeyen işlem', '{}'::jsonb, 'Türkiye''de yapılmayan, dolayısıyla 3065 sayılı Kanun''un konusuna hiç girmeyen teslim ve hizmetler.', 'percent', 0, 'sale', 'not_subject', date '1985-01-01', null, '3065 sayılı Kanun, madde 1 — Türkiye''de yapılan ticari, sınai, zirai faaliyet ve serbest meslek faaliyeti çerçevesindeki teslim ve hizmetler ile her türlü mal ve hizmet ithalatı verginin konusunu oluşturur; işlemin Türkiye dışında gerçekleşmesi hâlinde Kanunun konusuna girmez ve hiçbir kutuya yansımaz.', 'O', null, 60, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null),
  ('TR', 'TR-S-RR1', 'Satış, indirimli oran, KDV %1', '{}'::jsonb, '2007/13033 sayılı Kararın eki (I) sayılı listede sayılan teslim ve hizmetler (temel gıda maddelerinin bir kısmı, gazete ve dergi, nakdi ve gayrinakdi kredi teminatı ücretleri gibi).', 'percent', 1, 'sale', 'domestic', date '2007-12-31', null, '3065 sayılı Kanun, madde 28; 2007/13033 sayılı Bakanlar Kurulu Kararı eki (I) sayılı liste — oran %1''dir ve 7346 sayılı Cumhurbaşkanı Kararı bu oranda değişiklik yapmamıştır. Bu pack (I) sayılı listenin tamamını madde madde taşımaz.', 'S', null, 30, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-oran-karari', null, null, null, null),
  ('TR', 'TR-S-RR10', 'Satış, indirimli oran, KDV %10', '{}'::jsonb, '2007/13033 sayılı Kararın eki (II) sayılı listede sayılan teslim ve hizmetler (ör. gıda hizmeti/lokanta, konaklama, tekstil ürünlerinin bir kısmı, kitap ve süreli yayınlar).', 'percent', 10, 'sale', 'domestic', date '2023-07-10', null, '3065 sayılı Kanun, madde 28; 2007/13033 sayılı Bakanlar Kurulu Kararı eki (II) sayılı liste. 7346 sayılı Cumhurbaşkanı Kararı ile 10 Temmuz 2023''ten itibaren bu listedeki oran %8''den %10''a yükseltilmiştir. Bu pack (II) sayılı listenin tamamını madde madde taşımaz — hangi kalemlerin listede olduğu 2007/13033 sayılı Kararın ekinde okunmalıdır; bu, bir sonraki sürümde eklenecek bir eksikliktir.', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-oran-karari', null, null, null, null),
  ('TR', 'TR-S-SR', 'Satış, genel oran, KDV %20', '{}'::jsonb, '(I) ve (II) sayılı listelerde sayılmayan her türlü teslim ve hizmet.', 'percent', 20, 'sale', 'domestic', date '2023-07-10', null, '3065 sayılı Kanun, madde 28 — katma değer vergisi oranı, vergiye tabi her bir işlem için %10''dur; Cumhurbaşkanı bu oranı dört katına kadar artırmaya, %1''e kadar indirmeye yetkilidir. Bu yetkiye dayanılarak yürürlükte olan 2007/13033 sayılı Bakanlar Kurulu Kararı, (I) ve (II) sayılı listelerde sayılmayan işlemler için oranı %18 olarak belirlemişti; 7346 sayılı Cumhurbaşkanı Kararı ile 10 Temmuz 2023''ten itibaren bu oran %20''ye yükseltilmiştir.', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-oran-karari', null, null, null, null),
  ('TR', 'TR-S-ZR-EXP', 'Satış, ihracat istisnası (tam istisna)', '{}'::jsonb, 'İhracat teslimleri ve bu teslimlere ilişkin hizmetler.', 'percent', 0, 'sale', 'export', date '1985-01-01', null, '3065 sayılı Kanun, madde 11/1-a — ihracat teslimleri ve bu teslimlere ilişkin hizmetler vergiden müstesnadır; madde 12 bu istisnanın şartlarını (malın yurt dışındaki bir müşteriye veya yetkili gümrük antreposu işleticisine teslimi ve Türkiye Cumhuriyeti gümrük bölgesinden çıkışı) düzenler. Madde 32 uyarınca bu tam istisna kapsamındaki işlem nedeniyle yüklenilen ve indirim yoluyla giderilemeyen KDV, ihracatçıya iade olunur.', 'G', null, 40, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'kdv-kanunu', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('TR-P-IMP', 'invoice', 'base', 100, null, 'iith', array['iith']::text[], 100, 'TR-KDV1', 10),
    ('TR-P-IMP', 'invoice', 'tax', 100, '191', 'tith', array['tith']::text[], 100, 'TR-KDV1', 20),
    ('TR-P-IMP', 'credit_note', 'base', 100, null, 'iith', array['iith']::text[], -100, 'TR-KDV1', 10),
    ('TR-P-IMP', 'credit_note', 'tax', 100, '191', 'tith', array['tith']::text[], -100, 'TR-KDV1', 20),
    ('TR-P-RC-SVC', 'invoice', 'tax', 100, '191', 'trc', array['trc']::text[], 100, 'TR-KDV1', 10),
    ('TR-P-RC-SVC', 'invoice', 'tax', -100, '392', null, null, 100, null, 20),
    ('TR-P-RC-SVC', 'credit_note', 'tax', 100, '191', 'trc', array['trc']::text[], -100, 'TR-KDV1', 10),
    ('TR-P-RC-SVC', 'credit_note', 'tax', -100, '392', null, null, -100, null, 20),
    ('TR-P-RR10', 'invoice', 'base', 100, null, 'iyi', array['iyi']::text[], 100, 'TR-KDV1', 10),
    ('TR-P-RR10', 'invoice', 'tax', 100, '191', 'tyi', array['tyi']::text[], 100, 'TR-KDV1', 20),
    ('TR-P-RR10', 'credit_note', 'base', 100, null, 'iyi', array['iyi']::text[], -100, 'TR-KDV1', 10),
    ('TR-P-RR10', 'credit_note', 'tax', 100, '191', 'tyi', array['tyi']::text[], -100, 'TR-KDV1', 20),
    ('TR-P-SR', 'invoice', 'base', 100, null, 'iyi', array['iyi']::text[], 100, 'TR-KDV1', 10),
    ('TR-P-SR', 'invoice', 'tax', 100, '191', 'tyi', array['tyi']::text[], 100, 'TR-KDV1', 20),
    ('TR-P-SR', 'credit_note', 'base', 100, null, 'iyi', array['iyi']::text[], -100, 'TR-KDV1', 10),
    ('TR-P-SR', 'credit_note', 'tax', 100, '191', 'tyi', array['tyi']::text[], -100, 'TR-KDV1', 20),
    ('TR-S-EX-FIN', 'invoice', 'base', 100, null, 'mist', array['mist']::text[], 100, 'TR-KDV1', 10),
    ('TR-S-EX-FIN', 'credit_note', 'base', 100, null, 'mist', array['mist']::text[], -100, 'TR-KDV1', 10),
    ('TR-S-RR1', 'invoice', 'base', 100, null, 'm1', array['m1']::text[], 100, 'TR-KDV1', 10),
    ('TR-S-RR1', 'invoice', 'tax', 100, '391', 't1', array['t1']::text[], 100, 'TR-KDV1', 20),
    ('TR-S-RR1', 'credit_note', 'base', 100, null, 'm1', array['m1']::text[], -100, 'TR-KDV1', 10),
    ('TR-S-RR1', 'credit_note', 'tax', 100, '391', 't1', array['t1']::text[], -100, 'TR-KDV1', 20),
    ('TR-S-RR10', 'invoice', 'base', 100, null, 'm10', array['m10']::text[], 100, 'TR-KDV1', 10),
    ('TR-S-RR10', 'invoice', 'tax', 100, '391', 't10', array['t10']::text[], 100, 'TR-KDV1', 20),
    ('TR-S-RR10', 'credit_note', 'base', 100, null, 'm10', array['m10']::text[], -100, 'TR-KDV1', 10),
    ('TR-S-RR10', 'credit_note', 'tax', 100, '391', 't10', array['t10']::text[], -100, 'TR-KDV1', 20),
    ('TR-S-SR', 'invoice', 'base', 100, null, 'm20', array['m20']::text[], 100, 'TR-KDV1', 10),
    ('TR-S-SR', 'invoice', 'tax', 100, '391', 't20', array['t20']::text[], 100, 'TR-KDV1', 20),
    ('TR-S-SR', 'credit_note', 'base', 100, null, 'm20', array['m20']::text[], -100, 'TR-KDV1', 10),
    ('TR-S-SR', 'credit_note', 'tax', 100, '391', 't20', array['t20']::text[], -100, 'TR-KDV1', 20),
    ('TR-S-ZR-EXP', 'invoice', 'base', 100, null, 'mihr', array['mihr']::text[], 100, 'TR-KDV1', 10),
    ('TR-S-ZR-EXP', 'credit_note', 'base', 100, null, 'mihr', array['mihr']::text[], -100, 'TR-KDV1', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'TR' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('TR', 'TR-KDV1', '1 No''lu Katma Değer Vergisi Beyannamesi', array['month']::declaration_period[], 'month'::declaration_period, date '2023-07-10', null, '3065 sayılı Kanun, madde 39 — katma değer vergisinde vergilendirme dönemi, faaliyette bulunulan takvim yılının birer aylık dönemleridir. Madde 42, beyannamenin şekil ve muhtevasının Hazine ve Maliye Bakanlığınca belirleneceğini söyler; bu belirleme Katma Değer Vergisi Genel Uygulama Tebliği ve GİB''in e-Beyanname sisteminin 1 No''lu KDV Beyannamesi ekranıdır. Bu pack, GİB''in canlı e-Beyanname ekranındaki kutu numaralarını (bu araştırma sırasında doğrulanabilir, tek başına erişilebilir bir metin olarak bulunamadı) değil, kanunun ve tebliğin sözünü ettiği içeriği — oran bazında matrah ve hesaplanan KDV, indirilecek KDV''nin kaynakları, ödenecek/devreden KDV — kendi kutu adlarıyla taşır. Bir GİB e-Beyanname ekranını bilen bir kişi bunu ilk kontrol etmelidir.', true,'day_of_month_after_period'::filing_deadline_rule, 28, null, '3065 sayılı Kanun, madde 41/1 — mükellefler KDV beyannamelerini vergilendirme dönemini takip eden ayın yirmidördüncü günü akşamına kadar vermekle yükümlüdür; madde 46/1 aynı günün akşamına kadar ödenmesini ister. 149 Sıra No''lu Vergi Usul Kanunu Sirküleri, 213 sayılı Kanunun mükerrer 28''inci maddesindeki yetkiye dayanarak, 1 Aralık 2022''den itibaren verilmesi gereken KDV beyannamelerinin verilme ve bu beyannameler üzerine tahakkuk eden verginin ödeme süresini, yeni bir belirleme yapılıncaya kadar, izleyen ayın 28''inci günü sonuna uzatmıştır — bu pack idari olarak fiilen uygulanan günü (28) taşır ve kanuni günü (24) burada kaydeder.', 'gib-beyan-uzatma', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('TR', 'TR-KDV1', 'm20', 'base', 'Genel orana (%20) tabi işlemlerin matrahı', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 42; Katma Değer Vergisi Genel Uygulama Tebliği''nin matrah tablosu, oran bazında ayrı satırlar ister.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 't20', 'tax', 'Genel orana (%20) tabi işlemler üzerinden hesaplanan KDV', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 34 ve madde 42.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'm10', 'base', 'İndirimli orana (%10) tabi işlemlerin matrahı', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 42; 2007/13033 sayılı Karar eki (II) sayılı liste.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 't10', 'tax', 'İndirimli orana (%10) tabi işlemler üzerinden hesaplanan KDV', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 34 ve madde 42.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'm1', 'base', 'İndirimli orana (%1) tabi işlemlerin matrahı', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 42; 2007/13033 sayılı Karar eki (I) sayılı liste.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 't1', 'tax', 'İndirimli orana (%1) tabi işlemler üzerinden hesaplanan KDV', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 34 ve madde 42.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'htop', 'total', 'Hesaplanan KDV toplamı', '{}'::jsonb, 70, null, array['t20', 't10', 't1']::text[], '{}'::text[], null, null, false, false, null, 'Katma Değer Vergisi Genel Uygulama Tebliği''nin matrah tablosunun sonuç satırı; her oranın hesaplanan KDV''sinin toplamıdır.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'mihr', 'base', 'İhracat istisnası kapsamındaki teslim ve hizmetlerin bedeli', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 11/1-a ve madde 32; beyannamenin istisnalar tablosu.', 'kdv-kanunu'),
  ('TR', 'TR-KDV1', 'mist', 'base', 'Kısmi istisna kapsamındaki (BSMV dâhil) teslim ve hizmetlerin bedeli', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 17; beyannamenin istisnalar tablosu.', 'kdv-kanunu'),
  ('TR', 'TR-KDV1', 'iyi', 'base', 'Yurtiçi alışlara ait bu döneme ait indirilecek KDV''nin matrahı', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 29; beyannamenin indirimler tablosu.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'tyi', 'tax', 'Yurtiçi alışlara ait bu döneme ait indirilecek KDV', '{}'::jsonb, 110, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 29.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'iith', 'base', 'İthalatta ödenen ve indirilecek KDV''nin matrahı', '{}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 21 (ithalatta matrah) ve madde 46/2 (ithalde alınan KDV''nin gümrük vergisiyle birlikte ödenmesi).', 'kdv-kanunu'),
  ('TR', 'TR-KDV1', 'tith', 'tax', 'İthalatta ödenen ve bu dönemde indirilen KDV', '{}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 29 ve madde 46/2.', 'kdv-kanunu'),
  ('TR', 'TR-KDV1', 'trc', 'tax', 'Sorumlu sıfatıyla (2 No''lu KDV) beyan edilip bu dönemde indirilen KDV', '{}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, '3065 sayılı Kanun, madde 9 ve madde 29; Katma Değer Vergisi Genel Uygulama Tebliği I/C-2.1.1.2 — sorumlu sıfatıyla beyan edilen KDV, beyan edildiği dönemde 1 No''lu KDV Beyannamesinde indirim konusu yapılabilir. 2 No''lu KDV Beyannamesinin kendisi bu formun dışındadır.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'tind', 'total', 'İndirilecek KDV toplamı', '{}'::jsonb, 150, null, array['tyi', 'tith', 'trc']::text[], '{}'::text[], null, null, false, false, null, 'Katma Değer Vergisi Genel Uygulama Tebliği''nin indirimler tablosunun sonuç satırı.', 'kdv-genel-uygulama-tebligi'),
  ('TR', 'TR-KDV1', 'odn', 'total', 'Ödenecek KDV', '{}'::jsonb, 160, null, array['htop']::text[], array['tind']::text[], null, null, true, false, null, '3065 sayılı Kanun, madde 29/1 — hesaplanan KDV''nin indirilecek KDV''yi aşan kısmı, o dönem için ödenecek KDV''dir.', 'kdv-kanunu'),
  ('TR', 'TR-KDV1', 'dev', 'total', 'Sonraki döneme devreden KDV', '{}'::jsonb, 170, null, array['tind']::text[], array['htop']::text[], null, null, true, false, null, '3065 sayılı Kanun, madde 29/2 — indirilecek KDV toplamının hesaplanan KDV''yi aştığı hâllerde aradaki fark, iade edilmeyip sonraki döneme devrolunur.', 'kdv-kanunu')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('TR-TDHP-BILANCO', 'TR', 'default', 'Bilânço — Tekdüzen Hesap Planı', 'balance_sheet', 'TR-TDHP', date '1970-01-01', null, '1 Sıra No''lu Muhasebe Sistemi Uygulama Genel Tebliği, ekindeki bilânço şeması: Aktif I. Dönen Varlıklar, II. Duran Varlıklar; Pasif III. Kısa Vadeli Yabancı Kaynaklar, IV. Uzun Vadeli Yabancı Kaynaklar, V. Özkaynaklar. Bu pack, Tebliğ''in ayrıntılı alt gruplarından yalnızca bu chart''ın taşıdığı hesapların düştüğü satırları içerir; yıllara yaygın inşaat hakedişleri ve özel tükenmeye tabi varlıklar gibi bu golden''ın hiç ihtiyaç duymadığı, sektöre özgü gruplar bu ilk sürümde yer almaz.', 'muhasebe-tebligi-1'),
  ('TR-TDHP-GELIR', 'TR', 'default', 'Gelir Tablosu — Tekdüzen Hesap Planı', 'income_statement', 'TR-TDHP', date '1970-01-01', null, '1 Sıra No''lu Muhasebe Sistemi Uygulama Genel Tebliği, ekindeki gelir tablosu şeması: A. Brüt Satışlar''dan J. Olağandışı Gider ve Zararlar''a kadar harf sırasıyla giden, çeşit esasına göre (nature) düzenlenmiş tek biçim. Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları hesabı (370) bu pack''te hiçbir vergi kodu tarafından beslenmez; bir şirketin kurumlar vergisi karşılığını elle kaydetmesi için var olan bir hesaptır.', 'muhasebe-tebligi-1')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('TR-TDHP-BILANCO', 'AKT', null, 'AKTİF (VARLIKLAR) TOPLAMI', '{}'::jsonb, 10, 1, true, array['DV', 'DUV']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV', 'AKT', 'I. Dönen Varlıklar', '{}'::jsonb, 20, 1, true, array['DV.1', 'DV.1b', 'DV.2', 'DV.3', 'DV.4', 'DV.5', 'DV.6']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.1', 'DV', 'A. Hazır Değerler', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.1b', 'DV', 'B. Menkul Kıymetler', '{}'::jsonb, 35, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.2', 'DV', 'C. Ticari Alacaklar', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.3', 'DV', 'D. Diğer Alacaklar', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.4', 'DV', 'E. Stoklar', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.5', 'DV', 'G. Gelecek Aylara Ait Giderler ve Gelir Tahakkukları', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DV.6', 'DV', 'H. Diğer Dönen Varlıklar', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV', 'AKT', 'II. Duran Varlıklar', '{}'::jsonb, 90, 1, true, array['DUV.A', 'DUV.C', 'DUV.1', 'DUV.E', 'DUV.G', 'DUV.H']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV.A', 'DUV', 'A. Ticari Alacaklar', '{}'::jsonb, 95, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV.C', 'DUV', 'C. Mali Duran Varlıklar', '{}'::jsonb, 97, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV.1', 'DUV', 'D. Maddi Duran Varlıklar', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV.E', 'DUV', 'E. Maddi Olmayan Duran Varlıklar', '{}'::jsonb, 103, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV.G', 'DUV', 'G. Gelecek Yıllara Ait Giderler ve Gelir Tahakkukları', '{}'::jsonb, 106, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'DUV.H', 'DUV', 'H. Diğer Duran Varlıklar', '{}'::jsonb, 109, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'PAS', null, 'PASİF (KAYNAKLAR) TOPLAMI', '{}'::jsonb, 110, 1, true, array['KVYK', 'UVYK', 'OZK']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK', 'PAS', 'III. Kısa Vadeli Yabancı Kaynaklar', '{}'::jsonb, 120, 1, true, array['KVYK.1', 'KVYK.2', 'KVYK.3', 'KVYK.D', 'KVYK.4', 'KVYK.5', 'KVYK.H', 'KVYK.6']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.1', 'KVYK', 'A. Mali Borçlar', '{}'::jsonb, 130, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.2', 'KVYK', 'B. Ticari Borçlar', '{}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.3', 'KVYK', 'C. Diğer Borçlar', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.D', 'KVYK', 'D. Alınan Avanslar', '{}'::jsonb, 155, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.4', 'KVYK', 'F. Ödenecek Vergi ve Diğer Yükümlülükler', '{}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.5', 'KVYK', 'G. Borç ve Gider Karşılıkları', '{}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.H', 'KVYK', 'H. Gelecek Aylara Ait Gelirler ve Gider Tahakkukları', '{}'::jsonb, 175, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'KVYK.6', 'KVYK', 'I. Diğer Kısa Vadeli Yabancı Kaynaklar', '{}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK', 'PAS', 'IV. Uzun Vadeli Yabancı Kaynaklar', '{}'::jsonb, 190, 1, true, array['UVYK.1', 'UVYK.B', 'UVYK.C', 'UVYK.D', 'UVYK.2', 'UVYK.G', 'UVYK.H']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.1', 'UVYK', 'A. Mali Borçlar', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.B', 'UVYK', 'B. Ticari Borçlar', '{}'::jsonb, 203, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.C', 'UVYK', 'C. Diğer Borçlar', '{}'::jsonb, 206, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.D', 'UVYK', 'D. Alınan Avanslar', '{}'::jsonb, 208, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.2', 'UVYK', 'G. Borç ve Gider Karşılıkları', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.G', 'UVYK', 'H. Gelecek Yıllara Ait Gelirler ve Gider Tahakkukları', '{}'::jsonb, 213, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'UVYK.H', 'UVYK', 'I. Diğer Uzun Vadeli Yabancı Kaynaklar', '{}'::jsonb, 216, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK', 'PAS', 'V. Özkaynaklar', '{}'::jsonb, 220, 1, true, array['OZK.1', 'OZK.B', 'OZK.2', 'OZK.3', 'OZK.4', 'OZK.5', 'OZK.6']::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.1', 'OZK', 'A. Ödenmiş Sermaye', '{}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.B', 'OZK', 'B. Sermaye Yedekleri', '{}'::jsonb, 235, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.2', 'OZK', 'C. Kâr Yedekleri', '{}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.3', 'OZK', 'D. Geçmiş Yıllar Karları', '{}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.4', 'OZK', 'E. Geçmiş Yıllar Zararları (-)', '{}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.5', 'OZK', 'F. Dönem Net Karı', '{}'::jsonb, 270, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-BILANCO', 'OZK.6', 'OZK', 'F. Dönem Net Zararı (-)', '{}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.A', null, 'A. Brüt Satışlar', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.B', null, 'B. Satış İndirimleri (-)', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.C', null, 'C. Net Satışlar', '{}'::jsonb, 30, 1, true, array['GT.A']::text[], array['GT.B']::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.D', null, 'D. Satışların Maliyeti (-)', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.BSKZ', null, 'Brüt Satış Karı veya Zararı', '{}'::jsonb, 50, 1, true, array['GT.C']::text[], array['GT.D']::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.E', null, 'E. Faaliyet Giderleri (-)', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.FKZ', null, 'Faaliyet Karı veya Zararı', '{}'::jsonb, 70, 1, true, array['GT.BSKZ']::text[], array['GT.E']::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.F', null, 'F. Diğer Faaliyetlerden Olağan Gelir ve Kârlar', '{}'::jsonb, 80, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.G', null, 'G. Diğer Faaliyetlerden Olağan Gider ve Zararlar (-)', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.H', null, 'H. Finansman Giderleri (-)', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.OKZ', null, 'Olağan Kar veya Zarar', '{}'::jsonb, 110, 1, true, array['GT.FKZ', 'GT.F']::text[], array['GT.G', 'GT.H']::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.I', null, 'I. Olağandışı Gelir ve Kârlar', '{}'::jsonb, 120, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.J', null, 'J. Olağandışı Gider ve Zararlar (-)', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.DKZ', null, 'Dönem Karı veya Zararı', '{}'::jsonb, 140, 1, true, array['GT.OKZ', 'GT.I']::text[], array['GT.J']::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.VK', null, 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, null, null),
  ('TR-TDHP-GELIR', 'GT.NKZ', null, 'Dönem Net Karı veya Zararı', '{}'::jsonb, 160, 1, true, array['GT.DKZ']::text[], array['GT.VK']::text[], null, null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('TR-TDHP-BILANCO', 'DV.1', 10, 'code_range', '100', '109', null, 'any'),
    ('TR-TDHP-BILANCO', 'DV.1b', 10, 'code_range', '110', '119', null, 'any'),
    ('TR-TDHP-BILANCO', 'DV.2', 10, 'code_range', '120', '129', null, 'any'),
    ('TR-TDHP-BILANCO', 'DV.3', 10, 'code_range', '130', '139', null, 'any'),
    ('TR-TDHP-BILANCO', 'DV.4', 10, 'code_range', '150', '159', null, 'any'),
    ('TR-TDHP-BILANCO', 'DV.5', 10, 'code_range', '180', '189', null, 'any'),
    ('TR-TDHP-BILANCO', 'DV.6', 10, 'code_range', '190', '199', null, 'any'),
    ('TR-TDHP-BILANCO', 'DUV.A', 10, 'code_range', '220', '229', null, 'any'),
    ('TR-TDHP-BILANCO', 'DUV.C', 10, 'code_range', '240', '249', null, 'any'),
    ('TR-TDHP-BILANCO', 'DUV.1', 10, 'code_range', '250', '259', null, 'any'),
    ('TR-TDHP-BILANCO', 'DUV.E', 10, 'code_range', '260', '269', null, 'any'),
    ('TR-TDHP-BILANCO', 'DUV.G', 10, 'code_range', '280', '289', null, 'any'),
    ('TR-TDHP-BILANCO', 'DUV.H', 10, 'code_range', '290', '299', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.1', 10, 'code_range', '300', '309', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.2', 10, 'code_range', '320', '329', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.3', 10, 'code_range', '330', '339', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.D', 10, 'code_range', '340', '349', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.4', 10, 'code_range', '360', '369', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.5', 10, 'code_range', '370', '379', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.H', 10, 'code_range', '380', '389', null, 'any'),
    ('TR-TDHP-BILANCO', 'KVYK.6', 10, 'code_range', '390', '399', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.1', 10, 'code_range', '400', '409', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.B', 10, 'code_range', '420', '429', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.C', 10, 'code_range', '430', '439', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.D', 10, 'code_range', '440', '449', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.2', 10, 'code_range', '470', '479', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.G', 10, 'code_range', '480', '489', null, 'any'),
    ('TR-TDHP-BILANCO', 'UVYK.H', 10, 'code_range', '490', '499', null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.1', 10, 'code_range', '500', '509', null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.B', 10, 'code_range', '520', '529', null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.2', 10, 'code_range', '540', '549', null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.3', 10, 'account_code', '570', null, null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.4', 10, 'account_code', '580', null, null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.5', 10, 'account_code', '590', null, null, 'any'),
    ('TR-TDHP-BILANCO', 'OZK.6', 10, 'account_code', '591', null, null, 'any'),
    ('TR-TDHP-GELIR', 'GT.A', 10, 'code_range', '600', '604', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.B', 10, 'code_range', '610', '619', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.D', 10, 'code_range', '620', '629', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.E', 10, 'code_range', '630', '639', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.F', 10, 'code_range', '640', '649', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.G', 10, 'code_range', '650', '659', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.H', 10, 'code_range', '660', '669', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.I', 10, 'code_range', '670', '679', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.J', 10, 'code_range', '680', '689', null, 'any'),
    ('TR-TDHP-GELIR', 'GT.VK', 10, 'account_code', '370', null, null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('TR', 'Türkiye', '{}'::jsonb, array['tr']::text[], 'TRY', '120', '320', '1369', '659', '570', '600', '632', '102', '100', 'SAL', 'PUR', 'GEN', 'tr', 'result_accounts', '590', '591', '580', 'OPN', 'half_up', default, '646', '656', '679', '689', null, null, '3600', '192', null, 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = true,
  number_format                 = '{CODE}{YYYY}{NNNNNNNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = '213 sayılı Vergi Usul Kanunu, madde 230/1-2 — faturada düzenlenme tarihi ile fatura seri ve sıra numarasının bulunması zorunludur; madde 231/1 — faturalar sıra numarası dahilinde teselsül ettirilir. Elektronik fatura (e-Fatura) ve e-Arşiv Fatura uygulamasında bu numara, Gelir İdaresi Başkanlığı''nın teknik kılavuzlarının belirlediği üç karakterlik seri kodu, dört haneli yıl ve dokuz haneli müteselsil sayaçtan oluşan on altı karakterlik biçimde üretilir; format burada bir işletmenin seçebileceği bir örnektir, dayatılan tek biçim değildir.',
  numbering_source_key          = 'vuk',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = '3065 sayılı Kanun, madde 10 — vergiyi doğuran olay kural olarak (a) bendi uyarınca malın tesliminde veya hizmetin ifasında meydana gelir; (b) bendi bunu, teslim veya ifadan önce fatura ya da benzeri belge düzenlenmesi hâlinde, bu belgede gösterilen miktarla sınırlı olmak üzere belgenin düzenlenmesi anına ileri çeker — teslim/ifa kural, önceden kesilen fatura istisnadır, tıpkı Belçika''nın madde 16/22 - 17/22bis''i ve Lüksemburg''un madde 21 - 24, par. 1''i gibi. İthalatta vergiyi doğuran olay ayrıca (ı) bendinde düzenlenmiştir: gümrük vergisine tabi işlemlerde gümrük vergisi ödeme mükellefiyetinin başlaması, tabi olmayanlarda gümrük beyannamesinin tescili.',
  tax_point_source_key          = 'kdv-kanunu',
  posted_edit_policy            = 'reversal_only',
  posted_edit_policy_legal_reference = '6102 sayılı Türk Ticaret Kanunu, madde 64/3 — tacirin tuttuğu ticari defterlere yapılan kayıtların, izleyen bir düzeltme kaydı düşülmeden değiştirilmesi, okunamaz hâle getirilmesi ya da kayıt sürecinin izlenmesini engelleyecek şekilde ortadan kaldırılması yasaktır; 213 sayılı Vergi Usul Kanunu, madde 231/1 faturaların sıra numarası dahilinde teselsül ettirilmesini ister. Bir işlenmiş faturanın taslağa dönmesi bu iki kuralı birlikte ihlal eder — numarası boşta kalır ve kaydı sanki hiç yapılmamış gibi geri almak, izleyen bir düzeltme kaydı düşmeden değişiklik yapmak demektir. Düzeltme, 3065 sayılı Kanun''un fatura ve benzeri belgeler için tanıdığı alacak dekontu (iade faturası) iledir.',
  posted_edit_policy_source_key = 'vuk',
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_legal_reference      = 'e-Fatura ve e-Arşiv Fatura, Gelir İdaresi Başkanlığı''nın (GİB) kendi platformu veya GİB onaylı özel entegratörler üzerinden, ciro eşiğini aşan mükellefler için 213 sayılı Vergi Usul Kanunu''nun mükerrer 257''nci maddesindeki yetkiye dayanan 509 Sıra No''lu Vergi Usul Kanunu Genel Tebliği (ve 535, 550, 573, 589 sıra no''lu değişiklik tebliğleri) ile zorunlu kılınmıştır — bu pack''in araştırmasının ulaştığı en güncel eşik, bir önceki yıl brüt satış hasılatı 3.000.000 TL ve üzerinde olan mükellefler için genel olarak, e-ticaret/gayrimenkul ve motorlu taşıt ticareti yapanlar için 500.000 TL olarak, izleyen yılın 1 Temmuz''undan itibaren geçerlidir; 1 Ocak 2026''dan itibaren bilanço esasına göre defter tutan hiçbir mükellef artık kâğıt fatura düzenleyemez, tutarı ne olursa olsun e-Fatura veya e-Arşiv Fatura düzenlemek zorundadır. `profile` bu yüzden boş bırakılmıştır: e-Fatura ve e-Arşiv Fatura, UBL-TR (UBL 2.1''in GİB tarafından yerelleştirilmiş bir alt kümesi) biçiminde yazılır ve GİB''in kendi platformu ya da bir özel entegratör üzerinden GİB''e iletilir — iki taraf arasında doğrudan bir EN 16931 profili (Peppol BIS, Factur-X, XRechnung, bir PINT) değişimi değil, idarenin kendisinin arada durduğu bir teyit (clearance benzeri) modelidir; packages/formats''ın hiçbir bileşeni bu XML''i yazmaz, imzalamaz ya da GİB''e iletmez. `party_scheme` ve `vat_scheme` de bu yüzden boştur: Türkiye''nin ISO 6523 kayıtlı bir katılımcı kimlik şeması yoktur (Peppol katılımcı kimlik şeması listesi v9.7''de TR yer almaz); bir e-Fatura mükellefi GİB tarafından atanan bir Posta Kutusu Etiketi (PK etiketi, ör. urn:mail:defaultpk@... biçiminde) ile adreslenir, VKN/TCKN ise ayrı bir alanda taşınır.',
  einvoice_source_key           = 'gib-efatura',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'TR';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('TR', 'reverse_charge', 'reverse_charge', 'KDV, alıcı tarafından sorumlu sıfatıyla 3065 sayılı Kanun''un 9''uncu maddesi uyarınca 2 No''lu KDV Beyannamesi ile beyan edilip ödenecektir.', '{}'::jsonb, 10, date '1970-01-01', null, '3065 sayılı Kanun, madde 9 — Maliye Bakanlığı (Hazine ve Maliye Bakanlığı), vergi alacağının emniyet altına alınması amacıyla, vergiye tabi işlemlere taraf olanları verginin ödenmesinden sorumlu tutabilir; Katma Değer Vergisi Genel Uygulama Tebliği I/C-2 bölümü bu sorumluluğun beyanının 2 No''lu KDV Beyannamesi ile yapılacağını düzenler. Faturaya basılacak cümlenin metni bu Kanunda yer almadığından pack''in kendi ifadesidir.')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
