-- Ekwo OS — Maroc: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/ma at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build ma`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Code général des impôts, édition 2026 (Direction générale des Impôts — Ministère de l'Économie et des Finances)
--     https://www.finances.gov.ma/Publication/dgi/2025/CGI-2026-FR.pdf
--   Guide de la Télé déclaration TVA (SIMPL-TVA) (Direction générale des Impôts)
--     https://portail.tax.gov.ma/wps/wcm/connect/647d98f0-d163-4b78-b351-aef38e1f8f7a/NOUVEAU+GUIDE+DE+LA+TVA.pdf?MOD=AJPERES
--   Note synthétique des mesures fiscales de la loi de finances n° 50-25 pour l'année budgétaire 2026 (Direction générale des Impôts)
--     https://www.finances.gov.ma/Publication/dgi/2025/note-synthetique-mesures-fiscalesLF20265.pdf
--   Dahir n° 1-92-138 du 30 joumada II 1413 (25 décembre 1992) portant promulgation de la loi n° 9-88 relative aux obligations comptables des commerçants, rendant obligatoire le Code général de normalisation comptable (Secrétariat général du Gouvernement — Bulletin officiel du Royaume du Maroc)
--     https://www.finances.gov.ma/fr/Nos-metiers/Pages/normalisation-comptable.aspx
--   Code général de normalisation comptable (C.G.N.C.) — norme générale comptable et plan comptable général des entreprises (Conseil national de la comptabilité)
--     https://www.befec.ma/documentation/comptabilite/Plan_comptable/CGNC/cgnc.pdf
--   SIMPL — téléservices de la Direction générale des Impôts (espace professionnel, SIMPL-TVA) (Direction générale des Impôts)
--     https://www.tax.gov.ma
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('MA', 'Maroc', '0.1.0', date '2026-09-25', '20260923110000', 'community', null, null, 'e512496883199c20189ed138dbb3af3d48abdc356a9f74a8cad0e7c2ccab3ed6', '[{"key":"cgi2026","title":"Code général des impôts, édition 2026","publisher":"Direction générale des Impôts — Ministère de l''Économie et des Finances","url":"https://www.finances.gov.ma/Publication/dgi/2025/CGI-2026-FR.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"simpl-guide","title":"Guide de la Télé déclaration TVA (SIMPL-TVA)","publisher":"Direction générale des Impôts","url":"https://portail.tax.gov.ma/wps/wcm/connect/647d98f0-d163-4b78-b351-aef38e1f8f7a/NOUVEAU+GUIDE+DE+LA+TVA.pdf?MOD=AJPERES","consulted_on":"2026-09-25","kind":"guidance"},{"key":"lf2026-note","title":"Note synthétique des mesures fiscales de la loi de finances n° 50-25 pour l''année budgétaire 2026","publisher":"Direction générale des Impôts","url":"https://www.finances.gov.ma/Publication/dgi/2025/note-synthetique-mesures-fiscalesLF20265.pdf","consulted_on":"2026-09-25","kind":"guidance"},{"key":"loi9-88","title":"Dahir n° 1-92-138 du 30 joumada II 1413 (25 décembre 1992) portant promulgation de la loi n° 9-88 relative aux obligations comptables des commerçants, rendant obligatoire le Code général de normalisation comptable","publisher":"Secrétariat général du Gouvernement — Bulletin officiel du Royaume du Maroc","url":"https://www.finances.gov.ma/fr/Nos-metiers/Pages/normalisation-comptable.aspx","consulted_on":"2026-09-25","kind":"law"},{"key":"cgnc","title":"Code général de normalisation comptable (C.G.N.C.) — norme générale comptable et plan comptable général des entreprises","publisher":"Conseil national de la comptabilité","url":"https://www.befec.ma/documentation/comptabilite/Plan_comptable/CGNC/cgnc.pdf","consulted_on":"2026-09-25","kind":"standard"},{"key":"simpl-portal","title":"SIMPL — téléservices de la Direction générale des Impôts (espace professionnel, SIMPL-TVA)","publisher":"Direction générale des Impôts","url":"https://www.tax.gov.ma","consulted_on":"2026-09-25","kind":"portal"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('MA', 'default', 'PCGE — Plan comptable général des entreprises (modèle normal)', '{}'::jsonb, true, 'companies', array['MA-CGNC-BL', 'MA-CGNC-CPC']::text[], null, 'Dahir n° 1-92-138 du 25 décembre 1992 portant loi n° 9-88 relative aux obligations comptables des commerçants, art. 1er — tenue de la comptabilité selon la loi et ses textes d''application ; Code général de normalisation comptable, deuxième partie, Titre III — plan de comptes du modèle normal, classes 1 à 8. Le pack reprend les rubriques (postes) du cadre comptable et une sélection de comptes divisionnaires suffisante pour tenir des livres et tirer les états de synthèse ; une entreprise ouvre les comptes supplémentaires dont elle a besoin, dans le respect de la nomenclature du CGNC.', 'cgnc')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('MA', 'default', '1', 'FINANCEMENT PERMANENT', '{}'::jsonb, 'equity', false, null, 10),
  ('MA', 'default', '11', 'CAPITAUX PROPRES', '{}'::jsonb, 'equity', false, '1', 20),
  ('MA', 'default', '111', 'Capital social', '{}'::jsonb, 'equity', false, '11', 30),
  ('MA', 'default', '1111', 'Capital social', '{}'::jsonb, 'equity', false, '111', 40),
  ('MA', 'default', '112', 'Primes d''émission, de fusion et d''apport', '{}'::jsonb, 'equity', false, '11', 50),
  ('MA', 'default', '114', 'Réserve légale', '{}'::jsonb, 'equity_retained', false, '11', 60),
  ('MA', 'default', '115', 'Autres réserves', '{}'::jsonb, 'equity_retained', false, '11', 70),
  ('MA', 'default', '116', 'Report à nouveau', '{}'::jsonb, 'equity_retained', false, '11', 80),
  ('MA', 'default', '1161', 'Report à nouveau', '{}'::jsonb, 'equity_retained', false, '116', 90),
  ('MA', 'default', '118', 'Résultats nets en instance d''affectation', '{}'::jsonb, 'equity', false, '11', 100),
  ('MA', 'default', '119', 'Résultat net de l''exercice', '{}'::jsonb, 'equity', false, '11', 110),
  ('MA', 'default', '1191', 'Résultat net de l''exercice', '{}'::jsonb, 'equity', false, '119', 120),
  ('MA', 'default', '13', 'CAPITAUX PROPRES ASSIMILÉS', '{}'::jsonb, 'liability_non_current', false, '1', 130),
  ('MA', 'default', '131', 'Subventions d''investissement', '{}'::jsonb, 'liability_non_current', false, '13', 140),
  ('MA', 'default', '135', 'Provisions réglementées', '{}'::jsonb, 'liability_non_current', false, '13', 150),
  ('MA', 'default', '14', 'DETTES DE FINANCEMENT', '{}'::jsonb, 'liability_non_current', false, '1', 160),
  ('MA', 'default', '141', 'Emprunts obligataires', '{}'::jsonb, 'liability_non_current', false, '14', 170),
  ('MA', 'default', '148', 'Autres dettes de financement', '{}'::jsonb, 'liability_non_current', false, '14', 180),
  ('MA', 'default', '15', 'PROVISIONS DURABLES POUR RISQUES ET CHARGES', '{}'::jsonb, 'liability_non_current', false, '1', 190),
  ('MA', 'default', '151', 'Provisions pour risques', '{}'::jsonb, 'liability_non_current', false, '15', 200),
  ('MA', 'default', '155', 'Provisions pour charges', '{}'::jsonb, 'liability_non_current', false, '15', 210),
  ('MA', 'default', '17', 'ÉCARTS DE CONVERSION - PASSIF (éléments durables)', '{}'::jsonb, 'liability_non_current', false, '1', 220),
  ('MA', 'default', '1710', 'Augmentation des créances immobilisées', '{}'::jsonb, 'liability_non_current', false, '17', 230),
  ('MA', 'default', '1720', 'Diminution des dettes de financement', '{}'::jsonb, 'liability_non_current', false, '17', 240),
  ('MA', 'default', '2', 'ACTIF IMMOBILISÉ', '{}'::jsonb, 'asset_fixed', false, null, 250),
  ('MA', 'default', '21', 'IMMOBILISATIONS EN NON-VALEURS', '{}'::jsonb, 'asset_fixed', false, '2', 260),
  ('MA', 'default', '211', 'Frais préliminaires', '{}'::jsonb, 'asset_fixed', false, '21', 270),
  ('MA', 'default', '212', 'Charges à répartir sur plusieurs exercices', '{}'::jsonb, 'asset_fixed', false, '21', 280),
  ('MA', 'default', '213', 'Primes de remboursement des obligations', '{}'::jsonb, 'asset_fixed', false, '21', 290),
  ('MA', 'default', '22', 'IMMOBILISATIONS INCORPORELLES', '{}'::jsonb, 'asset_fixed', false, '2', 300),
  ('MA', 'default', '221', 'Immobilisations en recherche et développement', '{}'::jsonb, 'asset_fixed', false, '22', 310),
  ('MA', 'default', '222', 'Brevets, marques, droits et valeurs similaires', '{}'::jsonb, 'asset_fixed', false, '22', 320),
  ('MA', 'default', '223', 'Fonds commercial', '{}'::jsonb, 'asset_fixed', false, '22', 330),
  ('MA', 'default', '228', 'Autres immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '22', 340),
  ('MA', 'default', '23', 'IMMOBILISATIONS CORPORELLES', '{}'::jsonb, 'asset_fixed', false, '2', 350),
  ('MA', 'default', '231', 'Terrains', '{}'::jsonb, 'asset_fixed', false, '23', 360),
  ('MA', 'default', '232', 'Constructions', '{}'::jsonb, 'asset_fixed', false, '23', 370),
  ('MA', 'default', '233', 'Installations techniques, matériel et outillage', '{}'::jsonb, 'asset_fixed', false, '23', 380),
  ('MA', 'default', '234', 'Matériel de transport', '{}'::jsonb, 'asset_fixed', false, '23', 390),
  ('MA', 'default', '235', 'Mobilier, matériel de bureau et aménagements divers', '{}'::jsonb, 'asset_fixed', false, '23', 400),
  ('MA', 'default', '238', 'Autres immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '23', 410),
  ('MA', 'default', '239', 'Immobilisations corporelles en cours', '{}'::jsonb, 'asset_fixed', false, '23', 420),
  ('MA', 'default', '24', 'IMMOBILISATIONS FINANCIÈRES', '{}'::jsonb, 'asset_non_current', false, '2', 430),
  ('MA', 'default', '2411', 'Prêts immobilisés', '{}'::jsonb, 'asset_non_current', false, '24', 440),
  ('MA', 'default', '2415', 'Titres de participation', '{}'::jsonb, 'asset_non_current', false, '24', 450),
  ('MA', 'default', '2488', 'Autres créances financières', '{}'::jsonb, 'asset_non_current', false, '24', 460),
  ('MA', 'default', '27', 'ÉCARTS DE CONVERSION - ACTIF (éléments durables)', '{}'::jsonb, 'asset_fixed', false, '2', 470),
  ('MA', 'default', '2710', 'Diminution des créances immobilisées', '{}'::jsonb, 'asset_fixed', false, '27', 480),
  ('MA', 'default', '2720', 'Augmentation des dettes de financement', '{}'::jsonb, 'asset_fixed', false, '27', 490),
  ('MA', 'default', '28', 'AMORTISSEMENTS DES IMMOBILISATIONS', '{}'::jsonb, 'asset_fixed', false, '2', 500),
  ('MA', 'default', '2821', 'Amortissements des immobilisations en non-valeurs', '{}'::jsonb, 'asset_fixed', false, '28', 510),
  ('MA', 'default', '2822', 'Amortissements des immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '28', 520),
  ('MA', 'default', '2823', 'Amortissements des immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '28', 530),
  ('MA', 'default', '28233', 'Amortissements des installations techniques, matériel et outillage', '{}'::jsonb, 'asset_fixed', false, '2823', 540),
  ('MA', 'default', '28234', 'Amortissements du matériel de transport', '{}'::jsonb, 'asset_fixed', false, '2823', 550),
  ('MA', 'default', '28235', 'Amortissements du mobilier et du matériel de bureau', '{}'::jsonb, 'asset_fixed', false, '2823', 560),
  ('MA', 'default', '29', 'PROVISIONS POUR DÉPRÉCIATION DES IMMOBILISATIONS', '{}'::jsonb, 'asset_non_current', false, '2', 570),
  ('MA', 'default', '292', 'Provisions pour dépréciation des immobilisations incorporelles', '{}'::jsonb, 'asset_non_current', false, '29', 580),
  ('MA', 'default', '293', 'Provisions pour dépréciation des immobilisations corporelles', '{}'::jsonb, 'asset_non_current', false, '29', 590),
  ('MA', 'default', '294', 'Provisions pour dépréciation des immobilisations financières', '{}'::jsonb, 'asset_non_current', false, '29', 600),
  ('MA', 'default', '3', 'ACTIF CIRCULANT (HORS TRÉSORERIE)', '{}'::jsonb, 'asset_current', false, null, 610),
  ('MA', 'default', '31', 'STOCKS', '{}'::jsonb, 'asset_current', false, '3', 620),
  ('MA', 'default', '311', 'Marchandises', '{}'::jsonb, 'asset_current', false, '31', 630),
  ('MA', 'default', '312', 'Matières et fournitures consommables', '{}'::jsonb, 'asset_current', false, '31', 640),
  ('MA', 'default', '313', 'Produits en cours', '{}'::jsonb, 'asset_current', false, '31', 650),
  ('MA', 'default', '315', 'Produits finis', '{}'::jsonb, 'asset_current', false, '31', 660),
  ('MA', 'default', '34', 'CRÉANCES DE L''ACTIF CIRCULANT', '{}'::jsonb, 'asset_current', false, '3', 670),
  ('MA', 'default', '341', 'Fournisseurs débiteurs, avances et acomptes', '{}'::jsonb, 'asset_current', false, '34', 680),
  ('MA', 'default', '342', 'Clients et comptes rattachés', '{}'::jsonb, 'asset_receivable', true, '34', 690),
  ('MA', 'default', '3421', 'Clients', '{}'::jsonb, 'asset_receivable', true, '342', 700),
  ('MA', 'default', '3425', 'Clients douteux ou litigieux', '{}'::jsonb, 'asset_receivable', true, '342', 710),
  ('MA', 'default', '3427', 'Clients - retenues de garantie', '{}'::jsonb, 'asset_receivable', true, '342', 720),
  ('MA', 'default', '345', 'ÉTAT - DÉBITEUR', '{}'::jsonb, 'asset_current', false, '34', 730),
  ('MA', 'default', '3455', 'État - TVA récupérable', '{}'::jsonb, 'asset_current', false, '345', 740),
  ('MA', 'default', '34551', 'État - TVA récupérable sur immobilisations', '{}'::jsonb, 'asset_current', false, '3455', 750),
  ('MA', 'default', '34552', 'État - TVA récupérable sur charges', '{}'::jsonb, 'asset_current', false, '3455', 760),
  ('MA', 'default', '3456', 'État - crédit de TVA', '{}'::jsonb, 'asset_current', true, '345', 770),
  ('MA', 'default', '3458', 'Autres comptes débiteurs de l''État', '{}'::jsonb, 'asset_current', false, '345', 780),
  ('MA', 'default', '346', 'Comptes d''associés débiteurs', '{}'::jsonb, 'asset_current', false, '34', 790),
  ('MA', 'default', '348', 'Autres débiteurs', '{}'::jsonb, 'asset_current', false, '34', 800),
  ('MA', 'default', '349', 'Comptes de régularisation - actif', '{}'::jsonb, 'asset_prepayments', false, '34', 810),
  ('MA', 'default', '35', 'TITRES ET VALEURS DE PLACEMENT', '{}'::jsonb, 'asset_current', false, '3', 820),
  ('MA', 'default', '350', 'Titres et valeurs de placement', '{}'::jsonb, 'asset_current', false, '35', 830),
  ('MA', 'default', '37', 'ÉCARTS DE CONVERSION - ACTIF (éléments circulants)', '{}'::jsonb, 'asset_current', false, '3', 840),
  ('MA', 'default', '3701', 'Diminution des créances circulantes', '{}'::jsonb, 'asset_current', false, '37', 850),
  ('MA', 'default', '3702', 'Augmentation des dettes circulantes', '{}'::jsonb, 'asset_current', false, '37', 860),
  ('MA', 'default', '39', 'PROVISIONS POUR DÉPRÉCIATION DES COMPTES DE L''ACTIF CIRCULANT', '{}'::jsonb, 'asset_current', false, '3', 870),
  ('MA', 'default', '391', 'Provisions pour dépréciation des stocks', '{}'::jsonb, 'asset_current', false, '39', 880),
  ('MA', 'default', '394', 'Provisions pour dépréciation des créances de l''actif circulant', '{}'::jsonb, 'asset_current', false, '39', 890),
  ('MA', 'default', '4', 'PASSIF CIRCULANT (HORS TRÉSORERIE)', '{}'::jsonb, 'liability_current', false, null, 900),
  ('MA', 'default', '44', 'DETTES DU PASSIF CIRCULANT', '{}'::jsonb, 'liability_current', false, '4', 910),
  ('MA', 'default', '441', 'Fournisseurs et comptes rattachés', '{}'::jsonb, 'liability_payable', true, '44', 920),
  ('MA', 'default', '4411', 'Fournisseurs', '{}'::jsonb, 'liability_payable', true, '441', 930),
  ('MA', 'default', '4415', 'Fournisseurs - effets à payer', '{}'::jsonb, 'liability_payable', true, '441', 940),
  ('MA', 'default', '4417', 'Fournisseurs - retenues de garantie', '{}'::jsonb, 'liability_payable', true, '441', 950),
  ('MA', 'default', '442', 'Clients créditeurs, avances et acomptes', '{}'::jsonb, 'liability_current', false, '44', 960),
  ('MA', 'default', '443', 'Personnel - créditeur', '{}'::jsonb, 'liability_current', false, '44', 970),
  ('MA', 'default', '4432', 'Rémunérations dues au personnel', '{}'::jsonb, 'liability_current', false, '443', 980),
  ('MA', 'default', '444', 'Organismes sociaux', '{}'::jsonb, 'liability_current', false, '44', 990),
  ('MA', 'default', '445', 'État - créditeur', '{}'::jsonb, 'liability_current', false, '44', 1000),
  ('MA', 'default', '4452', 'État - Impôts et taxes assimilées', '{}'::jsonb, 'liability_current', false, '445', 1010),
  ('MA', 'default', '4453', 'État - Impôt sur les résultats', '{}'::jsonb, 'liability_current', false, '445', 1020),
  ('MA', 'default', '4455', 'État - TVA facturée', '{}'::jsonb, 'liability_current', false, '445', 1030),
  ('MA', 'default', '4456', 'État - TVA due', '{}'::jsonb, 'liability_current', true, '445', 1040),
  ('MA', 'default', '4458', 'Autres comptes créditeurs de l''État', '{}'::jsonb, 'liability_current', false, '445', 1050),
  ('MA', 'default', '446', 'Comptes d''associés créditeurs', '{}'::jsonb, 'liability_current', false, '44', 1060),
  ('MA', 'default', '448', 'Autres créanciers', '{}'::jsonb, 'liability_current', false, '44', 1070),
  ('MA', 'default', '449', 'Comptes de régularisation - passif', '{}'::jsonb, 'liability_current', false, '44', 1080),
  ('MA', 'default', '45', 'AUTRES PROVISIONS POUR RISQUES ET CHARGES', '{}'::jsonb, 'liability_current', false, '4', 1090),
  ('MA', 'default', '450', 'Autres provisions pour risques et charges', '{}'::jsonb, 'liability_current', false, '45', 1100),
  ('MA', 'default', '47', 'ÉCARTS DE CONVERSION - PASSIF (éléments circulants)', '{}'::jsonb, 'liability_current', false, '4', 1110),
  ('MA', 'default', '4701', 'Augmentation des créances circulantes', '{}'::jsonb, 'liability_current', false, '47', 1120),
  ('MA', 'default', '4702', 'Diminution des dettes circulantes', '{}'::jsonb, 'liability_current', false, '47', 1130),
  ('MA', 'default', '5', 'TRÉSORERIE', '{}'::jsonb, 'asset_cash', false, null, 1140),
  ('MA', 'default', '51', 'TRÉSORERIE - ACTIF', '{}'::jsonb, 'asset_cash', false, '5', 1150),
  ('MA', 'default', '511', 'Chèques et valeurs à encaisser', '{}'::jsonb, 'asset_cash', false, '51', 1160),
  ('MA', 'default', '514', 'Banques, Trésorerie Générale et chèques postaux débiteurs', '{}'::jsonb, 'asset_cash', false, '51', 1170),
  ('MA', 'default', '5141', 'Banques (soldes débiteurs)', '{}'::jsonb, 'asset_cash', false, '514', 1180),
  ('MA', 'default', '516', 'Caisses, régies d''avances et accréditifs', '{}'::jsonb, 'asset_cash', false, '51', 1190),
  ('MA', 'default', '5161', 'Caisses', '{}'::jsonb, 'asset_cash', false, '516', 1200),
  ('MA', 'default', '55', 'TRÉSORERIE - PASSIF', '{}'::jsonb, 'liability_current', false, '5', 1210),
  ('MA', 'default', '552', 'Crédits d''escompte', '{}'::jsonb, 'liability_current', false, '55', 1220),
  ('MA', 'default', '553', 'Crédits de trésorerie', '{}'::jsonb, 'liability_current', false, '55', 1230),
  ('MA', 'default', '554', 'Banques (soldes créditeurs)', '{}'::jsonb, 'liability_current', false, '55', 1240),
  ('MA', 'default', '59', 'PROVISIONS POUR DÉPRÉCIATION DES COMPTES DE TRÉSORERIE', '{}'::jsonb, 'asset_cash', false, '5', 1250),
  ('MA', 'default', '590', 'Provisions pour dépréciation des comptes de trésorerie', '{}'::jsonb, 'asset_cash', false, '59', 1260),
  ('MA', 'default', '6', 'CHARGES', '{}'::jsonb, 'expense', false, null, 1270),
  ('MA', 'default', '61', 'CHARGES D''EXPLOITATION', '{}'::jsonb, 'expense', false, '6', 1280),
  ('MA', 'default', '611', 'Achats revendus de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '61', 1290),
  ('MA', 'default', '6111', 'Achats de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '611', 1300),
  ('MA', 'default', '6114', 'Variation des stocks de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '611', 1310),
  ('MA', 'default', '612', 'Achats consommés de matières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '61', 1320),
  ('MA', 'default', '6121', 'Achats de matières premières', '{}'::jsonb, 'expense_direct_cost', false, '612', 1330),
  ('MA', 'default', '6125', 'Achats non stockés de matières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '612', 1340),
  ('MA', 'default', '613', 'Autres charges externes', '{}'::jsonb, 'expense', false, '61', 1360),
  ('MA', 'default', '6131', 'Locations et charges locatives', '{}'::jsonb, 'expense', false, '613', 1370),
  ('MA', 'default', '6133', 'Entretien et réparations', '{}'::jsonb, 'expense', false, '613', 1380),
  ('MA', 'default', '6134', 'Variation des stocks de matières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '612', 1350),
  ('MA', 'default', '6136', 'Rémunérations d''intermédiaires et honoraires', '{}'::jsonb, 'expense', false, '613', 1390),
  ('MA', 'default', '6141', 'Transports', '{}'::jsonb, 'expense', false, '613', 1400),
  ('MA', 'default', '6145', 'Frais postaux et frais de télécommunications', '{}'::jsonb, 'expense', false, '613', 1410),
  ('MA', 'default', '6147', 'Services bancaires', '{}'::jsonb, 'expense', false, '613', 1420),
  ('MA', 'default', '616', 'IMPÔTS ET TAXES', '{}'::jsonb, 'expense', false, '61', 1430),
  ('MA', 'default', '6161', 'Impôts et taxes directs', '{}'::jsonb, 'expense', false, '616', 1440),
  ('MA', 'default', '6165', 'Taxes non récupérables', '{}'::jsonb, 'expense', false, '616', 1450),
  ('MA', 'default', '617', 'CHARGES DE PERSONNEL', '{}'::jsonb, 'expense', false, '61', 1460),
  ('MA', 'default', '6171', 'Rémunérations du personnel', '{}'::jsonb, 'expense', false, '617', 1470),
  ('MA', 'default', '6174', 'Charges sociales', '{}'::jsonb, 'expense', false, '617', 1480),
  ('MA', 'default', '618', 'AUTRES CHARGES D''EXPLOITATION', '{}'::jsonb, 'expense', false, '61', 1490),
  ('MA', 'default', '6181', 'Jetons de présence', '{}'::jsonb, 'expense', false, '618', 1500),
  ('MA', 'default', '6188', 'Autres charges d''exploitation diverses', '{}'::jsonb, 'expense', false, '618', 1510),
  ('MA', 'default', '619', 'DOTATIONS D''EXPLOITATION', '{}'::jsonb, 'expense_depreciation', false, '61', 1520),
  ('MA', 'default', '6191', 'Dotations d''exploitation aux amortissements de l''immobilisation en non-valeurs', '{}'::jsonb, 'expense_depreciation', false, '619', 1530),
  ('MA', 'default', '6193', 'Dotations d''exploitation aux amortissements des immobilisations corporelles', '{}'::jsonb, 'expense_depreciation', false, '619', 1540),
  ('MA', 'default', '6194', 'Dotations d''exploitation aux provisions pour dépréciation des immobilisations', '{}'::jsonb, 'expense', false, '619', 1550),
  ('MA', 'default', '6196', 'Dotations d''exploitation aux provisions pour risques et charges', '{}'::jsonb, 'expense', false, '619', 1560),
  ('MA', 'default', '63', 'CHARGES FINANCIÈRES', '{}'::jsonb, 'expense', false, '6', 1570),
  ('MA', 'default', '631', 'Charges d''intérêts', '{}'::jsonb, 'expense', false, '63', 1580),
  ('MA', 'default', '6311', 'Intérêts des emprunts et dettes', '{}'::jsonb, 'expense', false, '631', 1590),
  ('MA', 'default', '633', 'Pertes de change', '{}'::jsonb, 'expense', false, '63', 1600),
  ('MA', 'default', '638', 'Autres charges financières', '{}'::jsonb, 'expense', false, '63', 1610),
  ('MA', 'default', '639', 'Dotations financières', '{}'::jsonb, 'expense', false, '63', 1620),
  ('MA', 'default', '65', 'CHARGES NON COURANTES', '{}'::jsonb, 'expense', false, '6', 1630),
  ('MA', 'default', '651', 'Valeurs nettes d''amortissements des immobilisations cédées', '{}'::jsonb, 'expense', false, '65', 1640),
  ('MA', 'default', '656', 'Subventions accordées', '{}'::jsonb, 'expense', false, '65', 1650),
  ('MA', 'default', '658', 'Autres charges non courantes', '{}'::jsonb, 'expense', false, '65', 1660),
  ('MA', 'default', '6583', 'Pénalités et amendes fiscales ou pénales', '{}'::jsonb, 'expense', false, '658', 1670),
  ('MA', 'default', '659', 'Dotations non courantes', '{}'::jsonb, 'expense', false, '65', 1680),
  ('MA', 'default', '67', 'IMPÔTS SUR LES RÉSULTATS', '{}'::jsonb, 'expense', false, '6', 1690),
  ('MA', 'default', '670', 'Impôts sur les bénéfices', '{}'::jsonb, 'expense', false, '67', 1700),
  ('MA', 'default', '6701', 'Impôt sur les résultats', '{}'::jsonb, 'expense', false, '670', 1710),
  ('MA', 'default', '7', 'PRODUITS', '{}'::jsonb, 'income', false, null, 1720),
  ('MA', 'default', '71', 'PRODUITS D''EXPLOITATION', '{}'::jsonb, 'income', false, '7', 1730),
  ('MA', 'default', '711', 'Ventes de marchandises', '{}'::jsonb, 'income', false, '71', 1740),
  ('MA', 'default', '7111', 'Ventes de marchandises au Maroc', '{}'::jsonb, 'income', false, '711', 1750),
  ('MA', 'default', '7113', 'Ventes de marchandises à l''étranger', '{}'::jsonb, 'income', false, '711', 1760),
  ('MA', 'default', '712', 'Ventes de biens et services produits', '{}'::jsonb, 'income', false, '71', 1770),
  ('MA', 'default', '7121', 'Ventes de biens produits au Maroc', '{}'::jsonb, 'income', false, '712', 1780),
  ('MA', 'default', '7124', 'Ventes de services produits au Maroc', '{}'::jsonb, 'income', false, '712', 1790),
  ('MA', 'default', '7126', 'Ventes de biens et services produits à l''étranger', '{}'::jsonb, 'income', false, '712', 1800),
  ('MA', 'default', '713', 'Variation des stocks de produits', '{}'::jsonb, 'income', false, '71', 1810),
  ('MA', 'default', '714', 'Immobilisations produites par l''entreprise pour elle-même', '{}'::jsonb, 'income', false, '71', 1820),
  ('MA', 'default', '716', 'Subventions d''exploitation', '{}'::jsonb, 'income', false, '71', 1830),
  ('MA', 'default', '718', 'Autres produits d''exploitation', '{}'::jsonb, 'income', false, '71', 1840),
  ('MA', 'default', '719', 'Reprises d''exploitation; transferts de charges', '{}'::jsonb, 'income_other', false, '71', 1850),
  ('MA', 'default', '73', 'PRODUITS FINANCIERS', '{}'::jsonb, 'income', false, '7', 1860),
  ('MA', 'default', '732', 'Produits des titres de participation et autres titres immobilisés', '{}'::jsonb, 'income', false, '73', 1870),
  ('MA', 'default', '733', 'Gains de change', '{}'::jsonb, 'income', false, '73', 1880),
  ('MA', 'default', '738', 'Intérêts et autres produits financiers', '{}'::jsonb, 'income', false, '73', 1890),
  ('MA', 'default', '739', 'Reprises financières; transferts de charges', '{}'::jsonb, 'income_other', false, '73', 1900),
  ('MA', 'default', '75', 'PRODUITS NON COURANTS', '{}'::jsonb, 'income_other', false, '7', 1910),
  ('MA', 'default', '751', 'Produits des cessions d''immobilisations', '{}'::jsonb, 'income_other', false, '75', 1920),
  ('MA', 'default', '756', 'Subventions d''équilibre', '{}'::jsonb, 'income_other', false, '75', 1930),
  ('MA', 'default', '757', 'Reprises sur subventions d''investissement', '{}'::jsonb, 'income_other', false, '75', 1940),
  ('MA', 'default', '758', 'Autres produits non courants', '{}'::jsonb, 'income_other', false, '75', 1950),
  ('MA', 'default', '759', 'Reprises non courantes; transferts de charges', '{}'::jsonb, 'income_other', false, '75', 1960)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('MA', 'AC', 'Journal des achats', '{}'::jsonb, 'purchase', 20),
  ('MA', 'AN', 'Journal des à-nouveaux', '{}'::jsonb, 'opening', 60),
  ('MA', 'BQ', 'Journal de banque', '{}'::jsonb, 'bank', 30),
  ('MA', 'CA', 'Journal de caisse', '{}'::jsonb, 'cash', 40),
  ('MA', 'OD', 'Journal des opérations diverses', '{}'::jsonb, 'general', 50),
  ('MA', 'VT', 'Journal des ventes', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('MA', 'MA-P-10', 'Achats de biens et services 10 % (déductible)', '{}'::jsonb, null, 'percent', 10, 'purchase', 'domestic', date '2026-01-01', null, 'Code général des impôts, art. 101 pour le droit à déduction ; art. 99-B-1° pour le taux réduit de 10 % avec droit à déduction.', 'S', null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-P-20', 'Achats de biens et services 20 % (déductible)', '{}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2026-01-01', null, 'Code général des impôts, art. 101 — la taxe dont les redevables peuvent opérer la déduction est celle qui a grevé les éléments du prix d''une opération imposable, figurant sur des factures répondant aux conditions de l''article 146 ; art. 99-A pour le taux.', 'S', null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-P-20-IMMO', 'Achats d''immobilisations 20 % (déductible)', '{}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2026-01-01', null, 'Code général des impôts, art. 101 — déduction de la taxe ayant grevé les biens constituant des immobilisations ; art. 104 — la déduction est calculée dès le mois de l''acquisition, sous réserve des régularisations qu''entraîne une cession ou un changement d''affectation ; art. 99-A pour le taux.', 'S', null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-P-20-ND', 'Achat de véhicule de tourisme 20 % (non déductible, art. 106)', '{}'::jsonb, null, 'percent', 20, 'purchase', 'domestic', date '2026-01-01', null, 'Code général des impôts, art. 106-II — n''ouvre pas droit à déduction la taxe ayant grevé les véhicules de transport de personnes, à l''exclusion de ceux utilisés pour le transport public, le transport collectif du personnel des entreprises ou constituant l''outil principal d''exploitation d''une entreprise de location de voitures. La taxe non déductible fait partie du coût du véhicule.', 'S', null, 140, 'vat', false, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-P-NR-20', 'Prestation d''un prestataire étranger non établi, sans représentant fiscal (art. 115)', '{}'::jsonb, null, 'percent', 20, 'purchase', 'foreign_services_received', date '2026-01-01', null, 'Code général des impôts, art. 115 — toute personne n''ayant pas au Maroc d''établissement stable et y effectuant des opérations imposables est tenue de faire accréditer auprès de l''administration fiscale un représentant domicilié au Maroc ; à défaut, la taxe due, ainsi que la pénalité et les majorations y afférentes, sont dues par la partie versante pour le compte de la personne non-résidente. Lorsque le client marocain est lui-même redevable de la taxe, il déclare le montant hors taxe de l''opération, calcule la taxe exigible et procède simultanément à sa déduction (autoliquidation) ; art. 96 pour l''assujettissement des prestations de services utilisées ou exploitées au Maroc.', null, null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-S-10-ADD', 'Ventes taux réduit 10 % (avec droit à déduction)', '{}'::jsonb, 'Opérations de restauration et autres opérations visées à l''article 99-B taxées à 10 % avec droit à déduction', 'percent', 10, 'sale', 'domestic', date '2026-01-01', null, 'Code général des impôts, art. 99-B-1° — taux réduit de 10 % avec droit à déduction, notamment pour les opérations de restauration. La loi de finances pour 2026 (loi n° 50-25) achève la convergence de plusieurs opérations auparavant taxées à 14 % ou à 7 % (transport, eau, sucre raffiné) vers ce taux de 10 % ; seules les catégories que le pack a pu vérifier par recoupement de plusieurs commentaires professionnels concordants sont reprises ici, faute d''avoir pu extraire le texte intégral de l''article 99 — voir la section « From Morocco » de docs/international.md.', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-S-20', 'Ventes taux normal 20 %', '{}'::jsonb, 'Ventes et prestations de services imposables au taux normal', 'percent', 20, 'sale', 'domestic', date '2026-01-01', null, 'Code général des impôts, art. 99-A — taux normal de 20 %, taux applicable à toutes les opérations imposables que la loi ne soumet pas expressément à un autre taux. Ancien taux réduit de 14 %, encore en vigueur en 2023 sur certaines opérations, entièrement convergé vers 20 % ou 10 % par le calendrier de convergence de la loi de finances pour 2024 (loi n° 55-23), poursuivi par la loi de finances pour 2025 (loi n° 60-24) et achevé par la loi de finances pour 2026 (loi n° 50-25) : à la date de ce pack, l''article 99 ne connaît plus que le taux normal de 20 % (A) et le taux réduit de 10 % (B).', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-S-EXO', 'Opération exonérée sans droit à déduction (art. 91)', '{}'::jsonb, 'Vente de pain, exonérée sans droit à déduction', 'percent', 0, 'sale', 'exempt', date '2026-01-01', null, 'Code général des impôts, art. 91-I — sont exonérées de la taxe sur la valeur ajoutée sans droit à déduction les ventes autrement qu''à consommer sur place portant sur le pain, ainsi que la farine et les céréales servant à sa fabrication.', 'E', null, 40, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null),
  ('MA', 'MA-S-EXP', 'Exportation exonérée (avec droit à déduction)', '{}'::jsonb, null, 'percent', 0, 'sale', 'export', date '2026-01-01', null, 'Code général des impôts, art. 92-I-1° — sont exonérées de la taxe sur la valeur ajoutée avec bénéfice du droit à déduction les produits livrés et les prestations de services rendues à l''exportation par les assujettis ; l''exonération s''applique à la dernière vente effectuée et à la dernière prestation de service rendue sur le territoire marocain ayant pour effet direct et immédiat de réaliser l''exportation, sur justification par l''exportateur des titres de transport, des documents douaniers ou de tout document en tenant lieu.', 'G', null, 30, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'cgi2026', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('MA-P-10', 'invoice', 'tax', 100, '34552', 'DEDCH', array['DEDCH']::text[], 100, 'MA-TVA', 10),
    ('MA-P-10', 'credit_note', 'tax', 100, '34552', 'DEDCH', array['DEDCH']::text[], -100, 'MA-TVA', 10),
    ('MA-P-20', 'invoice', 'tax', 100, '34552', 'DEDCH', array['DEDCH']::text[], 100, 'MA-TVA', 10),
    ('MA-P-20', 'credit_note', 'tax', 100, '34552', 'DEDCH', array['DEDCH']::text[], -100, 'MA-TVA', 10),
    ('MA-P-20-IMMO', 'invoice', 'tax', 100, '34551', 'DEDIMMO', array['DEDIMMO']::text[], 100, 'MA-TVA', 10),
    ('MA-P-20-IMMO', 'credit_note', 'tax', 100, '34551', 'DEDIMMO', array['DEDIMMO']::text[], -100, 'MA-TVA', 10),
    ('MA-P-20-ND', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 10),
    ('MA-P-20-ND', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 10),
    ('MA-P-NR-20', 'invoice', 'base', 100, null, 'CANR', array['CANR']::text[], 100, 'MA-TVA', 10),
    ('MA-P-NR-20', 'invoice', 'tax', 100, '34552', 'DEDNR', array['DEDNR']::text[], 100, 'MA-TVA', 20),
    ('MA-P-NR-20', 'invoice', 'tax', -100, '4455', 'TVANR', array['TVANR']::text[], 100, 'MA-TVA', 30),
    ('MA-P-NR-20', 'credit_note', 'base', 100, null, 'CANR', array['CANR']::text[], -100, 'MA-TVA', 10),
    ('MA-P-NR-20', 'credit_note', 'tax', 100, '34552', 'DEDNR', array['DEDNR']::text[], -100, 'MA-TVA', 20),
    ('MA-P-NR-20', 'credit_note', 'tax', -100, '4455', 'TVANR', array['TVANR']::text[], -100, 'MA-TVA', 30),
    ('MA-S-10-ADD', 'invoice', 'base', 100, null, 'CA10', array['CA10']::text[], 100, 'MA-TVA', 10),
    ('MA-S-10-ADD', 'invoice', 'tax', 100, '4455', 'TVA10', array['TVA10']::text[], 100, 'MA-TVA', 20),
    ('MA-S-10-ADD', 'credit_note', 'base', 100, null, 'CA10', array['CA10']::text[], -100, 'MA-TVA', 10),
    ('MA-S-10-ADD', 'credit_note', 'tax', 100, '4455', 'TVA10', array['TVA10']::text[], -100, 'MA-TVA', 20),
    ('MA-S-20', 'invoice', 'base', 100, null, 'CA20', array['CA20']::text[], 100, 'MA-TVA', 10),
    ('MA-S-20', 'invoice', 'tax', 100, '4455', 'TVA20', array['TVA20']::text[], 100, 'MA-TVA', 20),
    ('MA-S-20', 'credit_note', 'base', 100, null, 'CA20', array['CA20']::text[], -100, 'MA-TVA', 10),
    ('MA-S-20', 'credit_note', 'tax', 100, '4455', 'TVA20', array['TVA20']::text[], -100, 'MA-TVA', 20),
    ('MA-S-EXO', 'invoice', 'base', 100, null, 'EXO', array['EXO']::text[], 100, 'MA-TVA', 10),
    ('MA-S-EXO', 'credit_note', 'base', 100, null, 'EXO', array['EXO']::text[], -100, 'MA-TVA', 10),
    ('MA-S-EXP', 'invoice', 'base', 100, null, 'EXP', array['EXP']::text[], 100, 'MA-TVA', 10),
    ('MA-S-EXP', 'credit_note', 'base', 100, null, 'EXP', array['EXP']::text[], -100, 'MA-TVA', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'MA' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('MA', 'MA-TVA', 'Déclaration du chiffre d''affaires — taxe sur la valeur ajoutée', array['month', 'quarter']::declaration_period[], null, date '2026-01-01', null, 'Code général des impôts, art. 108 — la déclaration est mensuelle pour les redevables dont le chiffre d''affaires taxable réalisé au cours de l''année écoulée atteint ou dépasse 1 000 000 de dirhams, ainsi que pour toute personne n''ayant pas d''établissement au Maroc et y effectuant des opérations imposables ; elle est trimestrielle pour les autres redevables, sur option possible pour le régime mensuel avant le 31 janvier. La cadence dépend donc du chiffre d''affaires de l''entreprise : le pack n''en propose aucune par défaut. La déclaration est servie en ligne sur le télé-service SIMPL-TVA (tax.gov.ma), en six rubriques A à F : CA total, CA imposable, opérations réalisées avec des contribuables non-résidents (art. 115), calcul de la taxe exigible, déductions, paiement de la taxe. L''imprimé n''étant pas publié sous une forme numérotée consultée pour ce pack, les codes de case ci-dessous sont ceux de ces six rubriques et non ceux, s''ils existent, d''un bordereau-avis papier.', true,'last_day_of_month_after_period'::filing_deadline_rule, null, null, 'Code général des impôts, art. 108 et 110 — la déclaration du chiffre d''affaires, mensuelle ou trimestrielle, est déposée et la taxe correspondante versée avant l''expiration du mois qui suit la période. Le numéro exact de l''article fixant ce délai n''a pas pu être vérifié sur le texte intégral du Code à la date de ce pack — voir la section « From Morocco » de docs/international.md — et mérite une relecture par un professionnel local avant mise en production.', 'cgi2026', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('MA', 'MA-TVA', 'CA20', 'base', 'Chiffre d''affaires taxable au taux normal de 20 %', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 96 — opérations imposables ; art. 99-A pour le taux. Rubrique B, « CA imposable », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'CA10', 'base', 'Chiffre d''affaires taxable au taux réduit de 10 %', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 99-B. Rubrique B, « CA imposable », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'CAI', 'total', 'Total du chiffre d''affaires imposable', '{}'::jsonb, 30, null, array['CA20', 'CA10']::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 96 et 99. Rubrique B, « CA imposable », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'EXP', 'base', 'Exportations exonérées avec droit à déduction', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 92-I-1°. Rubrique A, « CA total », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'EXO', 'base', 'Opérations exonérées sans droit à déduction', '{}'::jsonb, 50, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 91. Rubrique A, « CA total », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'CAT', 'total', 'Chiffre d''affaires total', '{}'::jsonb, 60, null, array['CAI', 'EXP', 'EXO']::text[], '{}'::text[], null, null, false, false, null, 'Rubrique A, « CA total », du formulaire SIMPL-TVA.', 'simpl-guide'),
  ('MA', 'MA-TVA', 'CANR', 'base', 'Opérations réalisées avec des contribuables non-résidents (art. 115)', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 115. Rubrique C du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'TVA20', 'tax', 'Taxe exigible au taux de 20 %', '{}'::jsonb, 80, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 95 pour le fait générateur ; art. 99-A pour le taux. Rubrique D, « Calcul de la TVA exigible », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'TVA10', 'tax', 'Taxe exigible au taux de 10 %', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 99-B. Rubrique D, « Calcul de la TVA exigible », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'TVANR', 'tax', 'Taxe exigible sur les opérations avec des non-résidents (autoliquidation, art. 115)', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 115. Rubrique C du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'TVAB', 'total', 'Total de la taxe exigible', '{}'::jsonb, 110, null, array['TVA20', 'TVA10', 'TVANR']::text[], '{}'::text[], null, null, false, false, null, 'Rubrique D, « Calcul de la TVA exigible », du formulaire SIMPL-TVA.', 'simpl-guide'),
  ('MA', 'MA-TVA', 'DEDIMMO', 'tax', 'TVA déductible sur immobilisations', '{}'::jsonb, 120, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 101 et 104. Rubrique E, « Les déductions », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'DEDCH', 'tax', 'TVA déductible sur charges', '{}'::jsonb, 130, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 101. Rubrique E, « Les déductions », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'DEDNR', 'tax', 'TVA déduite sur les opérations avec des non-résidents (art. 115)', '{}'::jsonb, 140, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code général des impôts, art. 115. Rubrique E, « Les déductions », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'DEDT', 'total', 'Total des déductions', '{}'::jsonb, 150, null, array['DEDIMMO', 'DEDCH', 'DEDNR']::text[], '{}'::text[], null, null, false, false, null, 'Rubrique E, « Les déductions », du formulaire SIMPL-TVA.', 'simpl-guide'),
  ('MA', 'MA-TVA', 'NET', 'total', 'TVA due', '{}'::jsonb, 160, null, array['TVAB']::text[], array['DEDT']::text[], null, null, true, false, null, 'Code général des impôts, art. 101 — la taxe due au titre d''un mois ou d''un trimestre est établie après déduction de la taxe déductible. Rubrique F, « Paiement de la TVA », du formulaire SIMPL-TVA.', 'cgi2026'),
  ('MA', 'MA-TVA', 'CRED', 'total', 'Crédit de TVA à reporter', '{}'::jsonb, 170, null, array['DEDT']::text[], array['TVAB']::text[], null, null, true, false, null, 'Code général des impôts, art. 103 — lorsque la déduction ne peut s''opérer en totalité, l''excédent est reporté sur la taxe due au titre du ou des mois ou trimestres qui suivent, sans limitation de délai ; art. 103 bis pour le remboursement du crédit de taxe cumulé.', 'cgi2026')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('MA-CGNC-BL', 'MA', 'default', 'Bilan (BL) — modèle normal, masses et postes', 'balance_sheet', 'CGNC', date '1994-01-01', null, 'Code général de normalisation comptable, deuxième partie, Titre I — modèle du bilan du modèle normal. Les postes du bilan retenus ici regroupent, pour un pack de statut community, les comptes divisionnaires d''un même poste du cadre comptable en une seule ligne — le modèle normal officiel détaille davantage le passif circulant (fournisseurs, personnel, organismes sociaux, État, associés, autres créanciers et régularisation en postes distincts) ; voir la section « From Morocco » de docs/international.md.', 'cgnc'),
  ('MA-CGNC-CPC', 'MA', 'default', 'Compte de produits et charges (CPC) — modèle normal, en liste', 'income_statement', 'CGNC', date '1994-01-01', null, 'Code général de normalisation comptable, deuxième partie, Titre I — modèle du compte de produits et charges du modèle normal, présenté en liste avec dégagement du résultat d''exploitation, du résultat financier, du résultat courant, du résultat non courant et du résultat net de l''exercice.', 'cgnc')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('MA-CGNC-BL', 'AA', 'AZ', 'Immobilisations en non-valeurs', '{}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif immobilisé, poste « Immobilisations en non-valeurs ».', 'cgnc'),
  ('MA-CGNC-BL', 'AB', 'AZ', 'Immobilisations incorporelles', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif immobilisé, poste « Immobilisations incorporelles ».', 'cgnc'),
  ('MA-CGNC-BL', 'AC', 'AZ', 'Immobilisations corporelles', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif immobilisé, poste « Immobilisations corporelles ».', 'cgnc'),
  ('MA-CGNC-BL', 'AD', 'AZ', 'Immobilisations financières', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif immobilisé, poste « Immobilisations financières ».', 'cgnc'),
  ('MA-CGNC-BL', 'AE', 'AZ', 'Écarts de conversion - actif (éléments durables)', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif immobilisé, poste « Écarts de conversion - actif ».', 'cgnc'),
  ('MA-CGNC-BL', 'AZ', 'ZZ', 'TOTAL ACTIF IMMOBILISÉ', '{}'::jsonb, 60, 1, true, array['AA', 'AB', 'AC', 'AD', 'AE']::text[], '{}'::text[], null, 'CGNC, bilan, masse « Actif immobilisé ».', 'cgnc'),
  ('MA-CGNC-BL', 'BA', 'BZ', 'Stocks', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif circulant (hors trésorerie), poste « Stocks ».', 'cgnc'),
  ('MA-CGNC-BL', 'BB', 'BZ', 'Créances de l''actif circulant', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif circulant (hors trésorerie), poste « Créances de l''actif circulant ».', 'cgnc'),
  ('MA-CGNC-BL', 'BC', 'BZ', 'Titres et valeurs de placement', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif circulant (hors trésorerie), poste « Titres et valeurs de placement ».', 'cgnc'),
  ('MA-CGNC-BL', 'BD', 'BZ', 'Écarts de conversion - actif (éléments circulants)', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, actif circulant (hors trésorerie), poste « Écarts de conversion - actif ».', 'cgnc'),
  ('MA-CGNC-BL', 'BZ', 'ZZ', 'TOTAL ACTIF CIRCULANT (HORS TRÉSORERIE)', '{}'::jsonb, 110, 1, true, array['BA', 'BB', 'BC', 'BD']::text[], '{}'::text[], null, 'CGNC, bilan, masse « Actif circulant (hors trésorerie) ».', 'cgnc'),
  ('MA-CGNC-BL', 'CA', 'ZZ', 'Trésorerie - Actif', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, masse « Trésorerie - Actif ».', 'cgnc'),
  ('MA-CGNC-BL', 'ZZ', null, 'TOTAL GÉNÉRAL ACTIF', '{}'::jsonb, 130, 1, true, array['AZ', 'BZ', 'CA']::text[], '{}'::text[], null, 'CGNC, bilan, total général de l''actif.', 'cgnc'),
  ('MA-CGNC-BL', 'DA', 'DZ', 'Capitaux propres', '{}'::jsonb, 140, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, financement permanent, poste « Capitaux propres ».', 'cgnc'),
  ('MA-CGNC-BL', 'DB', 'DZ', 'Capitaux propres assimilés', '{}'::jsonb, 150, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, financement permanent, poste « Capitaux propres assimilés ».', 'cgnc'),
  ('MA-CGNC-BL', 'DC', 'DZ', 'Dettes de financement', '{}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, financement permanent, poste « Dettes de financement ».', 'cgnc'),
  ('MA-CGNC-BL', 'DD', 'DZ', 'Provisions durables pour risques et charges', '{}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, financement permanent, poste « Provisions durables pour risques et charges ».', 'cgnc'),
  ('MA-CGNC-BL', 'DE', 'DZ', 'Écarts de conversion - passif (éléments durables)', '{}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, financement permanent, poste « Écarts de conversion - passif ».', 'cgnc'),
  ('MA-CGNC-BL', 'DZ', 'YY', 'TOTAL FINANCEMENT PERMANENT', '{}'::jsonb, 190, 1, true, array['DA', 'DB', 'DC', 'DD', 'DE']::text[], '{}'::text[], null, 'CGNC, bilan, masse « Financement permanent ».', 'cgnc'),
  ('MA-CGNC-BL', 'EA', 'EZ', 'Dettes du passif circulant', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, passif circulant (hors trésorerie), poste « Dettes du passif circulant » — regroupe ici, pour ce pack community, les comptes 441 à 449 du cadre comptable (fournisseurs, clients créditeurs, personnel, organismes sociaux, État, associés, autres créanciers, régularisation), que le modèle normal officiel détaille poste par poste.', 'cgnc'),
  ('MA-CGNC-BL', 'EB', 'EZ', 'Autres provisions pour risques et charges', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, passif circulant (hors trésorerie), poste « Autres provisions pour risques et charges ».', 'cgnc'),
  ('MA-CGNC-BL', 'EC', 'EZ', 'Écarts de conversion - passif (éléments circulants)', '{}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, passif circulant (hors trésorerie), poste « Écarts de conversion - passif ».', 'cgnc'),
  ('MA-CGNC-BL', 'EZ', 'YY', 'TOTAL PASSIF CIRCULANT (HORS TRÉSORERIE)', '{}'::jsonb, 230, 1, true, array['EA', 'EB', 'EC']::text[], '{}'::text[], null, 'CGNC, bilan, masse « Passif circulant (hors trésorerie) ».', 'cgnc'),
  ('MA-CGNC-BL', 'FA', 'YY', 'Trésorerie - Passif', '{}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, bilan, masse « Trésorerie - Passif ».', 'cgnc'),
  ('MA-CGNC-BL', 'YY', null, 'TOTAL GÉNÉRAL PASSIF', '{}'::jsonb, 250, 1, true, array['DZ', 'EZ', 'FA']::text[], '{}'::text[], null, 'CGNC, bilan, total général du passif.', 'cgnc'),
  ('MA-CGNC-CPC', 'PA', 'PZ', 'Ventes de marchandises', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Ventes de marchandises ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PB', 'PZ', 'Ventes de biens et services produits', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Ventes de biens et services produits ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PC', 'PZ', 'Variation de stocks de produits', '{}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Variation de stocks de produits ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PD', 'PZ', 'Immobilisations produites par l''entreprise pour elle-même', '{}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Immobilisations produites par l''entreprise pour elle-même ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PE', 'PZ', 'Subventions d''exploitation', '{}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Subventions d''exploitation ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PF', 'PZ', 'Autres produits d''exploitation', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Autres produits d''exploitation ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PG', 'PZ', 'Reprises d''exploitation ; transferts de charges', '{}'::jsonb, 70, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, produits d''exploitation, poste « Reprises d''exploitation ; transferts de charges ».', 'cgnc'),
  ('MA-CGNC-CPC', 'PZ', 'RA', 'TOTAL DES PRODUITS D''EXPLOITATION', '{}'::jsonb, 80, 1, true, array['PA', 'PB', 'PC', 'PD', 'PE', 'PF', 'PG']::text[], '{}'::text[], null, 'CGNC, CPC, total I des produits d''exploitation.', 'cgnc'),
  ('MA-CGNC-CPC', 'QA', 'QZ', 'Achats revendus de marchandises', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Achats revendus de marchandises ».', 'cgnc'),
  ('MA-CGNC-CPC', 'QB', 'QZ', 'Achats consommés de matières et fournitures', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Achats consommés de matières et fournitures ».', 'cgnc'),
  ('MA-CGNC-CPC', 'QC', 'QZ', 'Autres charges externes', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Autres charges externes » — le cadre comptable poursuit la nomenclature des comptes divisionnaires de ce poste sur le compte 614 faute de place sur le compte 613 (dix comptes divisionnaires seulement) ; les deux comptes de rubrique forment un seul poste du CPC.', 'cgnc'),
  ('MA-CGNC-CPC', 'QD', 'QZ', 'Impôts et taxes', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Impôts et taxes ».', 'cgnc'),
  ('MA-CGNC-CPC', 'QE', 'QZ', 'Charges de personnel', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Charges de personnel ».', 'cgnc'),
  ('MA-CGNC-CPC', 'QF', 'QZ', 'Autres charges d''exploitation', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Autres charges d''exploitation ».', 'cgnc'),
  ('MA-CGNC-CPC', 'QG', 'QZ', 'Dotations d''exploitation', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, charges d''exploitation, poste « Dotations d''exploitation ».', 'cgnc'),
  ('MA-CGNC-CPC', 'QZ', 'RA', 'TOTAL DES CHARGES D''EXPLOITATION', '{}'::jsonb, 160, 1, true, array['QA', 'QB', 'QC', 'QD', 'QE', 'QF', 'QG']::text[], '{}'::text[], null, 'CGNC, CPC, total II des charges d''exploitation.', 'cgnc'),
  ('MA-CGNC-CPC', 'RA', 'TA', 'RÉSULTAT D''EXPLOITATION', '{}'::jsonb, 170, 1, true, array['PZ']::text[], array['QZ']::text[], null, 'CGNC, CPC, rubrique III, résultat d''exploitation (I - II).', 'cgnc'),
  ('MA-CGNC-CPC', 'SA', 'SC', 'Produits financiers', '{}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, rubrique IV, produits financiers.', 'cgnc'),
  ('MA-CGNC-CPC', 'SB', 'SC', 'Charges financières', '{}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, rubrique V, charges financières.', 'cgnc'),
  ('MA-CGNC-CPC', 'SC', 'TA', 'RÉSULTAT FINANCIER', '{}'::jsonb, 200, 1, true, array['SA']::text[], array['SB']::text[], null, 'CGNC, CPC, rubrique VI, résultat financier (IV - V).', 'cgnc'),
  ('MA-CGNC-CPC', 'TA', 'VA', 'RÉSULTAT COURANT', '{}'::jsonb, 210, 1, true, array['RA', 'SC']::text[], '{}'::text[], null, 'CGNC, CPC, rubrique VII, résultat courant (III + VI).', 'cgnc'),
  ('MA-CGNC-CPC', 'UA', 'UC', 'Produits non courants', '{}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, rubrique VIII, produits non courants.', 'cgnc'),
  ('MA-CGNC-CPC', 'UB', 'UC', 'Charges non courantes', '{}'::jsonb, 230, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, rubrique IX, charges non courantes.', 'cgnc'),
  ('MA-CGNC-CPC', 'UC', 'VA', 'RÉSULTAT NON COURANT', '{}'::jsonb, 240, 1, true, array['UA']::text[], array['UB']::text[], null, 'CGNC, CPC, rubrique X, résultat non courant (VIII - IX).', 'cgnc'),
  ('MA-CGNC-CPC', 'VA', 'XA', 'RÉSULTAT AVANT IMPÔTS', '{}'::jsonb, 250, 1, true, array['TA', 'UC']::text[], '{}'::text[], null, 'CGNC, CPC, rubrique XI, résultat avant impôts (VII + X).', 'cgnc'),
  ('MA-CGNC-CPC', 'WA', 'XA', 'Impôts sur les résultats', '{}'::jsonb, 260, 1, false, '{}'::text[], '{}'::text[], null, 'CGNC, CPC, rubrique XII, impôts sur les résultats.', 'cgnc'),
  ('MA-CGNC-CPC', 'XA', null, 'RÉSULTAT NET DE L''EXERCICE', '{}'::jsonb, 270, 1, true, array['VA']::text[], array['WA']::text[], null, 'CGNC, CPC, rubrique XIII, résultat net de l''exercice (XI - XII).', 'cgnc')
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('MA-CGNC-BL', 'AA', 10, 'code_range', '21', '21', null, 'any'),
    ('MA-CGNC-BL', 'AA', 20, 'code_range', '2821', '2821', null, 'any'),
    ('MA-CGNC-BL', 'AB', 10, 'code_range', '22', '22', null, 'any'),
    ('MA-CGNC-BL', 'AB', 20, 'code_range', '2822', '2822', null, 'any'),
    ('MA-CGNC-BL', 'AB', 30, 'account_code', '292', null, null, 'any'),
    ('MA-CGNC-BL', 'AC', 10, 'code_range', '23', '23', null, 'any'),
    ('MA-CGNC-BL', 'AC', 20, 'code_range', '2823', '2823', null, 'any'),
    ('MA-CGNC-BL', 'AC', 30, 'account_code', '293', null, null, 'any'),
    ('MA-CGNC-BL', 'AD', 10, 'code_range', '24', '24', null, 'any'),
    ('MA-CGNC-BL', 'AD', 20, 'account_code', '294', null, null, 'any'),
    ('MA-CGNC-BL', 'AE', 10, 'code_range', '27', '27', null, 'any'),
    ('MA-CGNC-BL', 'BA', 10, 'code_range', '31', '31', null, 'any'),
    ('MA-CGNC-BL', 'BA', 20, 'account_code', '391', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 10, 'account_code', '341', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 20, 'code_range', '342', '342', null, 'any'),
    ('MA-CGNC-BL', 'BB', 30, 'code_range', '3455', '3455', null, 'any'),
    ('MA-CGNC-BL', 'BB', 40, 'account_code', '3456', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 50, 'account_code', '3458', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 60, 'account_code', '346', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 70, 'account_code', '348', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 80, 'account_code', '349', null, null, 'any'),
    ('MA-CGNC-BL', 'BB', 90, 'account_code', '394', null, null, 'any'),
    ('MA-CGNC-BL', 'BC', 10, 'code_range', '35', '35', null, 'any'),
    ('MA-CGNC-BL', 'BD', 10, 'code_range', '37', '37', null, 'any'),
    ('MA-CGNC-BL', 'CA', 10, 'code_range', '51', '51', null, 'any'),
    ('MA-CGNC-BL', 'CA', 20, 'account_code', '590', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 10, 'account_code', '1111', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 20, 'account_code', '112', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 30, 'account_code', '114', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 40, 'account_code', '115', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 50, 'account_code', '1161', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 60, 'account_code', '118', null, null, 'any'),
    ('MA-CGNC-BL', 'DA', 70, 'account_code', '1191', null, null, 'any'),
    ('MA-CGNC-BL', 'DB', 10, 'code_range', '13', '13', null, 'any'),
    ('MA-CGNC-BL', 'DC', 10, 'code_range', '14', '14', null, 'any'),
    ('MA-CGNC-BL', 'DD', 10, 'code_range', '15', '15', null, 'any'),
    ('MA-CGNC-BL', 'DE', 10, 'code_range', '17', '17', null, 'any'),
    ('MA-CGNC-BL', 'EA', 10, 'code_range', '44', '44', null, 'any'),
    ('MA-CGNC-BL', 'EB', 10, 'code_range', '45', '45', null, 'any'),
    ('MA-CGNC-BL', 'EC', 10, 'code_range', '47', '47', null, 'any'),
    ('MA-CGNC-BL', 'FA', 10, 'code_range', '55', '55', null, 'any'),
    ('MA-CGNC-CPC', 'PA', 10, 'code_range', '711', '711', null, 'any'),
    ('MA-CGNC-CPC', 'PB', 10, 'code_range', '712', '712', null, 'any'),
    ('MA-CGNC-CPC', 'PC', 10, 'account_code', '713', null, null, 'any'),
    ('MA-CGNC-CPC', 'PD', 10, 'account_code', '714', null, null, 'any'),
    ('MA-CGNC-CPC', 'PE', 10, 'account_code', '716', null, null, 'any'),
    ('MA-CGNC-CPC', 'PF', 10, 'account_code', '718', null, null, 'any'),
    ('MA-CGNC-CPC', 'PG', 10, 'account_code', '719', null, null, 'any'),
    ('MA-CGNC-CPC', 'QA', 10, 'code_range', '611', '611', null, 'any'),
    ('MA-CGNC-CPC', 'QB', 10, 'code_range', '612', '612', null, 'any'),
    ('MA-CGNC-CPC', 'QC', 10, 'code_range', '613', '613', null, 'any'),
    ('MA-CGNC-CPC', 'QC', 20, 'code_range', '614', '614', null, 'any'),
    ('MA-CGNC-CPC', 'QD', 10, 'code_range', '616', '616', null, 'any'),
    ('MA-CGNC-CPC', 'QE', 10, 'code_range', '617', '617', null, 'any'),
    ('MA-CGNC-CPC', 'QF', 10, 'code_range', '618', '618', null, 'any'),
    ('MA-CGNC-CPC', 'QG', 10, 'code_range', '619', '619', null, 'any'),
    ('MA-CGNC-CPC', 'SA', 10, 'code_range', '73', '73', null, 'any'),
    ('MA-CGNC-CPC', 'SB', 10, 'code_range', '63', '63', null, 'any'),
    ('MA-CGNC-CPC', 'UA', 10, 'code_range', '75', '75', null, 'any'),
    ('MA-CGNC-CPC', 'UB', 10, 'code_range', '65', '65', null, 'any'),
    ('MA-CGNC-CPC', 'WA', 10, 'code_range', '67', '67', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('MA', 'Maroc', '{}'::jsonb, array['fr']::text[], 'MAD', '3421', '4411', null, null, '1161', '7111', '6111', '5141', '5161', 'VT', 'AC', 'OD', 'fr', 'result_accounts', '1191', '1191', null, 'AN', 'half_up', default, '733', '633', null, null, null, null, '4456', '3456', null, null)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = false,
  number_format                 = '{CODE}/{YYYY}/{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Code général des impôts, art. 145-III — tout achat de biens ou de services effectué par un contribuable auprès d''un fournisseur soumis à la taxe professionnelle doit être appuyé d''une facture régulière comportant, entre autres mentions, un numéro pris dans une série continue et ininterrompue. Le paragraphe n''impose ni forme ni remise à zéro annuelle, que le format proposé ici (`{CODE}/{YYYY}/{NNNN}`) permet sans l''exiger. Le libellé exact du paragraphe III n''a pas pu être extrait du PDF officiel pour ce pack et a été recoupé sur plusieurs commentaires professionnels concordants — voir la section « From Morocco » de docs/international.md.',
  numbering_source_key          = 'cgi2026',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'invoice_if_issued',
  tax_point_legal_reference     = 'Code général des impôts, art. 95 — le fait générateur de la taxe est constitué par l''encaissement total ou partiel du prix des marchandises, des travaux ou des services (régime de l''encaissement, applicable de plein droit) ; les redevables qui en font la déclaration avant le 1er janvier, ou dans les trente jours de leur début d''activité, sont autorisés à acquitter la taxe d''après le régime des débits, la facturation valant alors fait générateur. invoice_if_issued dit le régime des débits sur option, qui devance l''encaissement de droit commun dès qu''il est retenu ; le pack ne code pas l''option elle-même, qui est un choix de l''entreprise et non une règle du texte.',
  tax_point_source_key          = 'cgi2026',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'Le principe d''une obligation de facturation électronique existe dans la loi, à l''art. 145-IX du Code général des impôts (introduit par la loi de finances pour 2018 et dont l''entrée en application a été accélérée par la loi de finances pour 2024) : le contribuable doit se doter d''un système informatique de facturation répondant à des critères techniques fixés par l''administration, selon des modalités renvoyées à un décret d''application. Aucun décret d''application n''était publié au Bulletin officiel à la date de ce pack — la presse professionnelle rapportait, en avril 2026, un avant-projet transmis au secrétariat général du gouvernement et un déploiement par vagues annoncé par la Direction générale des Impôts en commençant par les grandes entreprises en B2B, sans date ni seuil de chiffre d''affaires officialisés, ni format technique arrêté par un texte publié. Le pack laisse donc `obligation` à `none` et le reste du bloc vide plutôt que d''anticiper un décret non publié : voir la section « From Morocco » de docs/international.md.',
  einvoice_source_key           = null,
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'MA';
