-- Ekwo OS — Algérie: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/dz at version 0.1.0, do not edit.
-- Change the pack and run `ekwo pack build dz`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Community pack — not reviewed.
-- Written from:
--   Code des taxes sur le chiffre d'affaires (CTCA) (Direction générale des impôts — texte mis à disposition par la Direction générale des douanes)
--     https://www.douane.gov.dz/IMG/pdf/code_des_taxes_sur_le_chiffre_d_affaire.pdf
--   La taxe sur la valeur ajoutée (TVA) (Direction générale des impôts (DGI))
--     https://www.mfdgi.gov.dz/fr/professionnels/services-pro/regime-reel/la-taxe-sur-la-valeur-ajoutee
--   Paiement mensuel de la taxe sur le chiffre d'affaires, TVA, TIC et TPP (Direction générale des impôts (DGI))
--     https://www.mfdgi.gov.dz/fr/professionnels/calandrier-fiscal-pro/593-regime-reel/18-paiement-mensuel-de-la-taxe-sur-le-chiffre-d-affaires-tva-tic-et-tpp
--   Décret exécutif n° 05-468 du 8 Dhou El Kaada 1426 correspondant au 10 décembre 2005 fixant les conditions et les modalités d'établissement de la facture, du bon de livraison, du bon de transfert et de la facture récapitulative (Ministère du Commerce)
--     https://www.commerce.gov.dz/fr/reglementation/decret-executif-n05-468
--   Jibaya'tic — télédéclaration et télépaiement des impôts et taxes (Direction générale des impôts (DGI))
--     https://jibayatic.mf.gov.dz
--   Loi n° 07-11 du 25 novembre 2007 portant système comptable financier, et arrêté du 23 Rajab 1429 correspondant au 26 juillet 2008 fixant les règles d'évaluation et de comptabilisation, le contenu et la présentation des états financiers ainsi que la nomenclature et les règles de fonctionnement des comptes (Ministère des Finances)
--     https://www.mf.gov.dz/pdf/Le_Systeme_comptable_Financier.pdf
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum, sources)
values
  ('DZ', 'Algérie', '0.1.0', date '2026-09-25', '20260923110000', 'community', null, null, '09d0ef13134c8b703450d4e5eb3f787db82febadcba59d4f000fc5cd6e220552', '[{"key":"ctca","title":"Code des taxes sur le chiffre d''affaires (CTCA)","publisher":"Direction générale des impôts — texte mis à disposition par la Direction générale des douanes","url":"https://www.douane.gov.dz/IMG/pdf/code_des_taxes_sur_le_chiffre_d_affaire.pdf","consulted_on":"2026-09-25","kind":"law"},{"key":"mfdgi-tva","title":"La taxe sur la valeur ajoutée (TVA)","publisher":"Direction générale des impôts (DGI)","url":"https://www.mfdgi.gov.dz/fr/professionnels/services-pro/regime-reel/la-taxe-sur-la-valeur-ajoutee","consulted_on":"2026-09-25","kind":"guidance"},{"key":"mfdgi-calendrier","title":"Paiement mensuel de la taxe sur le chiffre d''affaires, TVA, TIC et TPP","publisher":"Direction générale des impôts (DGI)","url":"https://www.mfdgi.gov.dz/fr/professionnels/calandrier-fiscal-pro/593-regime-reel/18-paiement-mensuel-de-la-taxe-sur-le-chiffre-d-affaires-tva-tic-et-tpp","consulted_on":"2026-09-25","kind":"guidance"},{"key":"decret-05-468","title":"Décret exécutif n° 05-468 du 8 Dhou El Kaada 1426 correspondant au 10 décembre 2005 fixant les conditions et les modalités d''établissement de la facture, du bon de livraison, du bon de transfert et de la facture récapitulative","publisher":"Ministère du Commerce","url":"https://www.commerce.gov.dz/fr/reglementation/decret-executif-n05-468","consulted_on":"2026-09-25","kind":"regulation"},{"key":"jibayatic","title":"Jibaya''tic — télédéclaration et télépaiement des impôts et taxes","publisher":"Direction générale des impôts (DGI)","url":"https://jibayatic.mf.gov.dz","consulted_on":"2026-09-25","kind":"portal"},{"key":"scf","title":"Loi n° 07-11 du 25 novembre 2007 portant système comptable financier, et arrêté du 23 Rajab 1429 correspondant au 26 juillet 2008 fixant les règles d''évaluation et de comptabilisation, le contenu et la présentation des états financiers ainsi que la nomenclature et les règles de fonctionnement des comptes","publisher":"Ministère des Finances","url":"https://www.mf.gov.dz/pdf/Le_Systeme_comptable_Financier.pdf","consulted_on":"2026-09-25","kind":"law"}]'::jsonb)
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum,
  sources              = excluded.sources;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference, source_key)
values
  ('DZ', 'default', 'SCF — nomenclature générale des comptes', '{}'::jsonb, true, 'companies', array['DZ-SCF-BS', 'DZ-SCF-IS']::text[], null, 'Loi n° 07-11 du 25 novembre 2007 portant système comptable financier, art. 17 — recours à une nomenclature des comptes fixée par voie réglementaire ; arrêté du 26 juillet 2008, titre III — nomenclature et règles de fonctionnement des comptes, classes 1 à 7. La classe 8 (engagements hors bilan) n''est pas reprise : elle ne porte pas de comptes numérotés destinés à recevoir une écriture de l''exploitant.', 'scf')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference,
  source_key           = excluded.source_key;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('DZ', 'default', '10', 'Capital, réserves et assimilés', '{}'::jsonb, 'equity', false, null, 10),
  ('DZ', 'default', '101', 'Capital émis', '{}'::jsonb, 'equity', false, '10', 20),
  ('DZ', 'default', '103', 'Primes liées au capital social', '{}'::jsonb, 'equity', false, '10', 30),
  ('DZ', 'default', '105', 'Écarts de réévaluation', '{}'::jsonb, 'equity', false, '10', 40),
  ('DZ', 'default', '106', 'Réserves (légale, statutaires, réglementées)', '{}'::jsonb, 'equity', false, '10', 50),
  ('DZ', 'default', '108', 'Compte de l''exploitant', '{}'::jsonb, 'equity', false, '10', 60),
  ('DZ', 'default', '109', 'Capital souscrit, non appelé', '{}'::jsonb, 'equity', false, '10', 70),
  ('DZ', 'default', '11', 'Report à nouveau', '{}'::jsonb, 'equity_retained', false, null, 80),
  ('DZ', 'default', '110', 'Report à nouveau — solde créditeur', '{}'::jsonb, 'equity_retained', false, '11', 90),
  ('DZ', 'default', '119', 'Report à nouveau — solde débiteur', '{}'::jsonb, 'equity_retained', false, '11', 100),
  ('DZ', 'default', '12', 'Résultat de l''exercice', '{}'::jsonb, 'equity', false, null, 110),
  ('DZ', 'default', '120', 'Résultat net de l''exercice — bénéfice', '{}'::jsonb, 'equity', false, '12', 120),
  ('DZ', 'default', '129', 'Résultat net de l''exercice — perte', '{}'::jsonb, 'equity', false, '12', 130),
  ('DZ', 'default', '13', 'Produits et charges différés', '{}'::jsonb, 'liability_non_current', false, null, 140),
  ('DZ', 'default', '131', 'Subventions d''équipement', '{}'::jsonb, 'liability_non_current', false, '13', 150),
  ('DZ', 'default', '132', 'Autres subventions d''investissement', '{}'::jsonb, 'liability_non_current', false, '13', 160),
  ('DZ', 'default', '133', 'Impôts différés actif', '{}'::jsonb, 'asset_non_current', false, '13', 170),
  ('DZ', 'default', '134', 'Impôts différés passif', '{}'::jsonb, 'liability_non_current', false, '13', 180),
  ('DZ', 'default', '138', 'Autres produits et charges différés', '{}'::jsonb, 'liability_non_current', false, '13', 190),
  ('DZ', 'default', '15', 'Provisions pour charges — passifs non courants', '{}'::jsonb, 'liability_non_current', false, null, 200),
  ('DZ', 'default', '153', 'Provisions pour pensions et obligations similaires', '{}'::jsonb, 'liability_non_current', false, '15', 210),
  ('DZ', 'default', '155', 'Provisions pour impôts', '{}'::jsonb, 'liability_non_current', false, '15', 220),
  ('DZ', 'default', '158', 'Autres provisions pour charges', '{}'::jsonb, 'liability_non_current', false, '15', 230),
  ('DZ', 'default', '16', 'Emprunts et dettes assimilées', '{}'::jsonb, 'liability_non_current', false, null, 240),
  ('DZ', 'default', '164', 'Emprunts auprès des établissements de crédit', '{}'::jsonb, 'liability_non_current', false, '16', 250),
  ('DZ', 'default', '165', 'Dépôts et cautionnements reçus', '{}'::jsonb, 'liability_non_current', false, '16', 260),
  ('DZ', 'default', '168', 'Autres emprunts et dettes assimilées', '{}'::jsonb, 'liability_non_current', false, '16', 270),
  ('DZ', 'default', '17', 'Dettes rattachées à des participations', '{}'::jsonb, 'liability_non_current', false, null, 280),
  ('DZ', 'default', '18', 'Comptes de liaison des établissements et sociétés en participation', '{}'::jsonb, 'liability_non_current', false, null, 290),
  ('DZ', 'default', '20', 'Immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, null, 300),
  ('DZ', 'default', '203', 'Frais de développement et de prospection', '{}'::jsonb, 'asset_fixed', false, '20', 310),
  ('DZ', 'default', '204', 'Logiciels informatiques et assimilés', '{}'::jsonb, 'asset_fixed', false, '20', 320),
  ('DZ', 'default', '205', 'Concessions, brevets, licences, marques et droits similaires', '{}'::jsonb, 'asset_fixed', false, '20', 330),
  ('DZ', 'default', '207', 'Écart d''acquisition (goodwill)', '{}'::jsonb, 'asset_fixed', false, '20', 340),
  ('DZ', 'default', '208', 'Autres immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '20', 350),
  ('DZ', 'default', '21', 'Immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, null, 360),
  ('DZ', 'default', '211', 'Terrains', '{}'::jsonb, 'asset_fixed', false, '21', 370),
  ('DZ', 'default', '213', 'Constructions', '{}'::jsonb, 'asset_fixed', false, '21', 380),
  ('DZ', 'default', '215', 'Installations techniques, matériel et outillages industriels', '{}'::jsonb, 'asset_fixed', false, '21', 390),
  ('DZ', 'default', '218', 'Autres immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '21', 400),
  ('DZ', 'default', '2182', 'Matériel de transport', '{}'::jsonb, 'asset_fixed', false, '218', 410),
  ('DZ', 'default', '2183', 'Matériel de bureau et informatique', '{}'::jsonb, 'asset_fixed', false, '218', 420),
  ('DZ', 'default', '2184', 'Mobilier', '{}'::jsonb, 'asset_fixed', false, '218', 430),
  ('DZ', 'default', '22', 'Immobilisations en concession', '{}'::jsonb, 'asset_fixed', false, null, 440),
  ('DZ', 'default', '23', 'Immobilisations en cours', '{}'::jsonb, 'asset_fixed', false, null, 450),
  ('DZ', 'default', '232', 'Immobilisations corporelles en cours', '{}'::jsonb, 'asset_fixed', false, '23', 460),
  ('DZ', 'default', '237', 'Avances et acomptes versés sur immobilisations', '{}'::jsonb, 'asset_fixed', false, '23', 470),
  ('DZ', 'default', '26', 'Participations et créances rattachées à des participations', '{}'::jsonb, 'asset_non_current', false, null, 480),
  ('DZ', 'default', '261', 'Titres de participation', '{}'::jsonb, 'asset_non_current', false, '26', 490),
  ('DZ', 'default', '267', 'Créances rattachées à des participations', '{}'::jsonb, 'asset_non_current', false, '26', 500),
  ('DZ', 'default', '27', 'Autres immobilisations financières', '{}'::jsonb, 'asset_non_current', false, null, 510),
  ('DZ', 'default', '274', 'Prêts', '{}'::jsonb, 'asset_non_current', false, '27', 520),
  ('DZ', 'default', '275', 'Dépôts et cautionnements versés', '{}'::jsonb, 'asset_non_current', false, '27', 530),
  ('DZ', 'default', '276', 'Autres créances immobilisées', '{}'::jsonb, 'asset_non_current', false, '27', 540),
  ('DZ', 'default', '28', 'Amortissements des immobilisations', '{}'::jsonb, 'asset_fixed', false, null, 550),
  ('DZ', 'default', '280', 'Amortissements des immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '28', 560),
  ('DZ', 'default', '281', 'Amortissements des immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '28', 570),
  ('DZ', 'default', '2813', 'Amortissements des constructions', '{}'::jsonb, 'asset_fixed', false, '281', 580),
  ('DZ', 'default', '2815', 'Amortissements des installations techniques et du matériel', '{}'::jsonb, 'asset_fixed', false, '281', 590),
  ('DZ', 'default', '2818', 'Amortissements des autres immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '281', 600),
  ('DZ', 'default', '29', 'Pertes de valeur sur immobilisations', '{}'::jsonb, 'asset_fixed', false, null, 610),
  ('DZ', 'default', '30', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, null, 620),
  ('DZ', 'default', '31', 'Matières premières et fournitures', '{}'::jsonb, 'asset_current', false, null, 630),
  ('DZ', 'default', '35', 'Stocks de produits', '{}'::jsonb, 'asset_current', false, null, 640),
  ('DZ', 'default', '39', 'Pertes de valeur sur stocks', '{}'::jsonb, 'asset_current', false, null, 650),
  ('DZ', 'default', '40', 'Fournisseurs et comptes rattachés', '{}'::jsonb, 'liability_payable', true, null, 660),
  ('DZ', 'default', '401', 'Fournisseurs', '{}'::jsonb, 'liability_payable', true, '40', 670),
  ('DZ', 'default', '403', 'Fournisseurs — effets à payer', '{}'::jsonb, 'liability_current', false, '40', 680),
  ('DZ', 'default', '404', 'Fournisseurs d''immobilisations', '{}'::jsonb, 'liability_current', false, '40', 690),
  ('DZ', 'default', '408', 'Fournisseurs — factures non parvenues', '{}'::jsonb, 'liability_current', false, '40', 700),
  ('DZ', 'default', '409', 'Fournisseurs débiteurs — avances et acomptes versés', '{}'::jsonb, 'asset_current', false, '40', 710),
  ('DZ', 'default', '41', 'Clients et comptes rattachés', '{}'::jsonb, 'asset_receivable', true, null, 720),
  ('DZ', 'default', '411', 'Clients', '{}'::jsonb, 'asset_receivable', true, '41', 730),
  ('DZ', 'default', '413', 'Clients — effets à recevoir', '{}'::jsonb, 'asset_current', false, '41', 740),
  ('DZ', 'default', '416', 'Clients douteux ou litigieux', '{}'::jsonb, 'asset_current', false, '41', 750),
  ('DZ', 'default', '418', 'Clients — produits non encore facturés', '{}'::jsonb, 'asset_current', false, '41', 760),
  ('DZ', 'default', '419', 'Clients créditeurs — avances et acomptes reçus', '{}'::jsonb, 'liability_current', false, '41', 770),
  ('DZ', 'default', '42', 'Personnel et comptes rattachés', '{}'::jsonb, 'liability_current', false, null, 780),
  ('DZ', 'default', '421', 'Personnel — rémunérations dues', '{}'::jsonb, 'liability_current', false, '42', 790),
  ('DZ', 'default', '425', 'Personnel — avances et acomptes', '{}'::jsonb, 'asset_current', false, '42', 800),
  ('DZ', 'default', '428', 'Personnel — charges à payer', '{}'::jsonb, 'liability_current', false, '42', 810),
  ('DZ', 'default', '43', 'Organismes sociaux', '{}'::jsonb, 'liability_current', false, null, 820),
  ('DZ', 'default', '431', 'Sécurité sociale', '{}'::jsonb, 'liability_current', false, '43', 830),
  ('DZ', 'default', '438', 'Organismes sociaux — charges à payer', '{}'::jsonb, 'liability_current', false, '43', 840),
  ('DZ', 'default', '44', 'État et collectivités publiques', '{}'::jsonb, 'liability_current', false, null, 850),
  ('DZ', 'default', '441', 'État — subventions à recevoir', '{}'::jsonb, 'asset_current', false, '44', 860),
  ('DZ', 'default', '444', 'État — impôts sur les résultats', '{}'::jsonb, 'liability_current', false, '44', 870),
  ('DZ', 'default', '445', 'État — taxes sur le chiffre d''affaires', '{}'::jsonb, 'liability_current', false, '44', 880),
  ('DZ', 'default', '44551', 'TVA à décaisser', '{}'::jsonb, 'liability_current', true, '445', 890),
  ('DZ', 'default', '44562', 'TVA récupérable sur immobilisations', '{}'::jsonb, 'asset_current', false, '445', 900),
  ('DZ', 'default', '44566', 'TVA récupérable sur achats de biens et services', '{}'::jsonb, 'asset_current', false, '445', 910),
  ('DZ', 'default', '44567', 'Crédit de TVA à reporter', '{}'::jsonb, 'asset_current', true, '445', 920),
  ('DZ', 'default', '44571', 'TVA collectée sur ventes', '{}'::jsonb, 'liability_current', false, '445', 930),
  ('DZ', 'default', '44572', 'TVA collectée sur les encaissements — prestations de services en attente', '{}'::jsonb, 'liability_current', false, '445', 935),
  ('DZ', 'default', '447', 'Autres impôts, taxes et versements assimilés', '{}'::jsonb, 'liability_current', false, '44', 940),
  ('DZ', 'default', '448', 'État — charges à payer', '{}'::jsonb, 'liability_current', false, '44', 950),
  ('DZ', 'default', '45', 'Groupe et associés', '{}'::jsonb, 'liability_current', false, null, 960),
  ('DZ', 'default', '455', 'Associés — comptes courants', '{}'::jsonb, 'liability_current', false, '45', 970),
  ('DZ', 'default', '457', 'Associés — dividendes à payer', '{}'::jsonb, 'liability_current', false, '45', 980),
  ('DZ', 'default', '46', 'Débiteurs et créditeurs divers', '{}'::jsonb, 'liability_current', false, null, 990),
  ('DZ', 'default', '462', 'Créances sur cessions d''immobilisations', '{}'::jsonb, 'asset_current', false, '46', 1000),
  ('DZ', 'default', '467', 'Autres comptes débiteurs ou créditeurs', '{}'::jsonb, 'liability_current', false, '46', 1010),
  ('DZ', 'default', '47', 'Comptes transitoires ou d''attente', '{}'::jsonb, 'liability_current', false, null, 1020),
  ('DZ', 'default', '471', 'Compte d''attente', '{}'::jsonb, 'liability_current', false, '47', 1030),
  ('DZ', 'default', '48', 'Comptes de régularisation', '{}'::jsonb, 'liability_current', false, null, 1040),
  ('DZ', 'default', '486', 'Charges constatées d''avance', '{}'::jsonb, 'asset_prepayments', false, '48', 1050),
  ('DZ', 'default', '487', 'Produits constatés d''avance', '{}'::jsonb, 'liability_current', false, '48', 1060),
  ('DZ', 'default', '49', 'Pertes de valeur sur comptes de tiers', '{}'::jsonb, 'asset_current', false, null, 1070),
  ('DZ', 'default', '50', 'Valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, null, 1080),
  ('DZ', 'default', '51', 'Banques, établissements financiers et assimilés', '{}'::jsonb, 'asset_cash', false, null, 1090),
  ('DZ', 'default', '511', 'Valeurs à l''encaissement', '{}'::jsonb, 'asset_current', false, '51', 1100),
  ('DZ', 'default', '512', 'Banque', '{}'::jsonb, 'asset_cash', false, '51', 1110),
  ('DZ', 'default', '53', 'Caisse', '{}'::jsonb, 'asset_cash', false, null, 1120),
  ('DZ', 'default', '530', 'Caisse', '{}'::jsonb, 'asset_cash', false, '53', 1130),
  ('DZ', 'default', '54', 'Régies d''avances et accréditifs', '{}'::jsonb, 'asset_current', false, null, 1140),
  ('DZ', 'default', '58', 'Virements internes', '{}'::jsonb, 'asset_current', false, null, 1150),
  ('DZ', 'default', '59', 'Pertes de valeur sur comptes financiers', '{}'::jsonb, 'asset_current', false, null, 1160),
  ('DZ', 'default', '60', 'Achats consommés', '{}'::jsonb, 'expense_direct_cost', false, null, 1170),
  ('DZ', 'default', '601', 'Achats de matières premières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '60', 1180),
  ('DZ', 'default', '602', 'Achats d''autres approvisionnements', '{}'::jsonb, 'expense_direct_cost', false, '60', 1190),
  ('DZ', 'default', '603', 'Variation des stocks', '{}'::jsonb, 'expense_direct_cost', false, '60', 1200),
  ('DZ', 'default', '607', 'Achats de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '60', 1210),
  ('DZ', 'default', '609', 'Rabais, remises et ristournes obtenus sur achats', '{}'::jsonb, 'expense_direct_cost', false, '60', 1220),
  ('DZ', 'default', '61', 'Services extérieurs', '{}'::jsonb, 'expense', false, null, 1230),
  ('DZ', 'default', '611', 'Sous-traitance générale', '{}'::jsonb, 'expense', false, '61', 1240),
  ('DZ', 'default', '613', 'Locations', '{}'::jsonb, 'expense', false, '61', 1250),
  ('DZ', 'default', '615', 'Entretien et réparations', '{}'::jsonb, 'expense', false, '61', 1260),
  ('DZ', 'default', '616', 'Primes d''assurances', '{}'::jsonb, 'expense', false, '61', 1270),
  ('DZ', 'default', '62', 'Autres services extérieurs', '{}'::jsonb, 'expense', false, null, 1280),
  ('DZ', 'default', '621', 'Personnel extérieur à l''entreprise', '{}'::jsonb, 'expense', false, '62', 1290),
  ('DZ', 'default', '622', 'Rémunérations d''intermédiaires et honoraires', '{}'::jsonb, 'expense', false, '62', 1300),
  ('DZ', 'default', '623', 'Publicité, publications et relations publiques', '{}'::jsonb, 'expense', false, '62', 1310),
  ('DZ', 'default', '624', 'Transports', '{}'::jsonb, 'expense', false, '62', 1320),
  ('DZ', 'default', '625', 'Déplacements, missions et réceptions', '{}'::jsonb, 'expense', false, '62', 1330),
  ('DZ', 'default', '626', 'Frais postaux et de télécommunications', '{}'::jsonb, 'expense', false, '62', 1340),
  ('DZ', 'default', '627', 'Services bancaires et assimilés', '{}'::jsonb, 'expense', false, '62', 1350),
  ('DZ', 'default', '628', 'Divers', '{}'::jsonb, 'expense', false, '62', 1360),
  ('DZ', 'default', '63', 'Charges de personnel', '{}'::jsonb, 'expense', false, null, 1370),
  ('DZ', 'default', '631', 'Rémunérations du personnel', '{}'::jsonb, 'expense', false, '63', 1380),
  ('DZ', 'default', '635', 'Cotisations aux organismes sociaux', '{}'::jsonb, 'expense', false, '63', 1390),
  ('DZ', 'default', '638', 'Autres charges sociales', '{}'::jsonb, 'expense', false, '63', 1400),
  ('DZ', 'default', '64', 'Impôts, taxes et versements assimilés (hors impôts sur les résultats)', '{}'::jsonb, 'expense', false, null, 1410),
  ('DZ', 'default', '641', 'Impôts, taxes et versements assimilés', '{}'::jsonb, 'expense', false, '64', 1420),
  ('DZ', 'default', '65', 'Autres charges opérationnelles', '{}'::jsonb, 'expense', false, null, 1430),
  ('DZ', 'default', '651', 'Redevances pour concessions, brevets, licences et marques', '{}'::jsonb, 'expense', false, '65', 1440),
  ('DZ', 'default', '654', 'Pertes sur créances irrécouvrables', '{}'::jsonb, 'expense', false, '65', 1450),
  ('DZ', 'default', '658', 'Charges diverses de gestion courante', '{}'::jsonb, 'expense', false, '65', 1460),
  ('DZ', 'default', '66', 'Charges financières', '{}'::jsonb, 'expense', false, null, 1470),
  ('DZ', 'default', '661', 'Charges d''intérêts', '{}'::jsonb, 'expense', false, '66', 1480),
  ('DZ', 'default', '666', 'Pertes de change', '{}'::jsonb, 'expense', false, '66', 1490),
  ('DZ', 'default', '668', 'Autres charges financières', '{}'::jsonb, 'expense', false, '66', 1500),
  ('DZ', 'default', '67', 'Éléments extraordinaires — charges', '{}'::jsonb, 'expense', false, null, 1510),
  ('DZ', 'default', '68', 'Dotations aux amortissements, provisions et pertes de valeur', '{}'::jsonb, 'expense_depreciation', false, null, 1520),
  ('DZ', 'default', '681', 'Dotations aux amortissements — charges d''exploitation', '{}'::jsonb, 'expense_depreciation', false, '68', 1530),
  ('DZ', 'default', '685', 'Dotations aux provisions — charges financières', '{}'::jsonb, 'expense_depreciation', false, '68', 1540),
  ('DZ', 'default', '69', 'Impôts sur les résultats et assimilés', '{}'::jsonb, 'expense', false, null, 1550),
  ('DZ', 'default', '695', 'Impôts sur les bénéfices (IBS)', '{}'::jsonb, 'expense', false, '69', 1560),
  ('DZ', 'default', '698', 'Autres impôts sur les résultats', '{}'::jsonb, 'expense', false, '69', 1570),
  ('DZ', 'default', '70', 'Ventes de marchandises, de produits fabriqués et prestations de services', '{}'::jsonb, 'income', false, null, 1580),
  ('DZ', 'default', '700', 'Ventes de marchandises', '{}'::jsonb, 'income', false, '70', 1590),
  ('DZ', 'default', '701', 'Ventes de produits finis', '{}'::jsonb, 'income', false, '70', 1600),
  ('DZ', 'default', '706', 'Prestations de services', '{}'::jsonb, 'income', false, '70', 1610),
  ('DZ', 'default', '709', 'Rabais, remises et ristournes accordés', '{}'::jsonb, 'income', false, '70', 1620),
  ('DZ', 'default', '72', 'Production stockée (ou déstockage)', '{}'::jsonb, 'income_other', false, null, 1630),
  ('DZ', 'default', '73', 'Production immobilisée', '{}'::jsonb, 'income_other', false, null, 1640),
  ('DZ', 'default', '74', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, null, 1650),
  ('DZ', 'default', '75', 'Autres produits opérationnels', '{}'::jsonb, 'income_other', false, null, 1660),
  ('DZ', 'default', '758', 'Produits divers de gestion courante', '{}'::jsonb, 'income_other', false, '75', 1670),
  ('DZ', 'default', '76', 'Produits financiers', '{}'::jsonb, 'income_other', false, null, 1680),
  ('DZ', 'default', '766', 'Gains de change', '{}'::jsonb, 'income_other', false, '76', 1690),
  ('DZ', 'default', '768', 'Autres produits financiers', '{}'::jsonb, 'income_other', false, '76', 1700),
  ('DZ', 'default', '77', 'Éléments extraordinaires — produits', '{}'::jsonb, 'income_other', false, null, 1710),
  ('DZ', 'default', '78', 'Reprises sur pertes de valeur et provisions', '{}'::jsonb, 'income_other', false, null, 1720)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, name_i18n, journal_type, sequence) values
  ('DZ', 'AC', 'Journal des achats', '{}'::jsonb, 'purchase', 20),
  ('DZ', 'AN', 'Journal des à-nouveaux', '{}'::jsonb, 'opening', 60),
  ('DZ', 'BQ', 'Journal de banque', '{}'::jsonb, 'bank', 30),
  ('DZ', 'CA', 'Journal de caisse', '{}'::jsonb, 'cash', 40),
  ('DZ', 'OD', 'Opérations diverses', '{}'::jsonb, 'general', 50),
  ('DZ', 'VT', 'Journal des ventes', '{}'::jsonb, 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, name_i18n, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, conditions, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code, source_key,
   applies_seller_territory, applies_buyer_territory, applies_supply_territory,
   applies_supply_vs_seller)
values
  ('DZ', 'DZ-P-19', 'Achat 19 % déductible', '{}'::jsonb, 'Achats de biens et services au taux normal, déductibles', 'percent', 19, 'purchase', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires — la taxe ayant grevé les biens et services acquis pour les besoins de l''exploitation et non exclus du droit à déduction (art. 41) est déductible de la taxe due par l''assujetti ; art. 21 pour le taux', 'S', null, 110, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-P-19-IMMO', 'Achat d''immobilisations 19 % déductible', '{}'::jsonb, 'Acquisitions d''immobilisations au taux normal, déductibles', 'percent', 19, 'purchase', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires — la taxe ayant grevé les biens constituant des immobilisations est déductible dans les mêmes conditions que celle grevant les biens et services, sous réserve des exclusions de l''art. 41 ; art. 21 pour le taux', 'S', null, 120, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-P-19-ND', 'Achat 19 % non déductible (art. 41)', '{}'::jsonb, 'Biens et services exclus du droit à déduction : notamment les véhicules de tourisme ne constituant pas l''outil indispensable de l''activité, et les biens ou services non liés à l''exploitation', 'percent', 19, 'purchase', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 41 — exclusions du droit à déduction, notamment les véhicules de tourisme qui ne constituent pas l''outil indispensable à l''exercice de l''activité ; la taxe non déductible est un élément du coût du bien ou du service acquis', 'S', null, 140, 'vat', false, '{}'::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-P-9', 'Achat 9 % déductible', '{}'::jsonb, 'Achats de biens et services relevant du taux réduit de l''article 23, déductibles', 'percent', 9, 'purchase', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 23 pour le taux ; la taxe est déductible dans les mêmes conditions que celle du taux normal', 'S', null, 130, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-P-IMP-19', 'Importation 19 % (TVA acquittée en douane)', '{}'::jsonb, 'TVA liquidée et perçue par les services des douanes lors du dédouanement', 'percent', 19, 'purchase', 'import', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires — la taxe sur la valeur ajoutée à l''importation est liquidée et perçue par les services des douanes sur une base incluant la valeur en douane et les droits et taxes d''entrée, à l''exclusion de la taxe elle-même ; le document douanier justifie la déduction. Le numéro d''article exact de l''assiette à l''importation, dans la numérotation en vigueur, n''a pas pu être vérifié dans une édition consolidée officielle cette session : à faire relire', null, null, 150, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-S-19', 'Vente 19 %', '{}'::jsonb, 'Livraisons de biens et prestations de services au taux normal', 'percent', 19, 'sale', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 21 — « la taxe sur la valeur ajoutée est perçue au taux normal de 19 % », taux résiduel applicable à toute opération taxable qui ne relève ni du taux réduit de l''art. 23 ni d''une exonération ; art. 14 — pour une vente de biens, le fait générateur est constitué par la livraison juridique ou matérielle du bien', 'S', null, 10, 'vat', true, '{}'::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-S-19-SRV', 'Prestation de services 19 % — TVA sur les encaissements', '{}'::jsonb, 'Prestations de services au taux normal : le fait générateur est l''encaissement, total ou partiel, du prix', 'percent', 19, 'sale', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 14 — « pour les prestations de services, le fait générateur est constitué par l''encaissement partiel ou total du prix » ; à défaut d''encaissement, la taxe devient exigible à l''expiration d''un délai d''un an à compter de la livraison juridique ou matérielle, régularisation que ce pack ne modélise pas ; art. 21 pour le taux', 'S', null, 20, 'vat', true, '{}'::tax_condition[], null, false, true, '44572', 'ctca', null, null, null, null),
  ('DZ', 'DZ-S-9', 'Vente 9 %', '{}'::jsonb, 'Produits, biens, travaux, opérations et services énumérés à l''article 23 du CTCA (produits alimentaires de base, produits pharmaceutiques, livres, transport ferroviaire de voyageurs, actes médicaux, notamment)', 'percent', 9, 'sale', 'domestic', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 23 — « le taux réduit de la taxe sur la valeur ajoutée est fixé à 9 %. Il s''applique aux produits, biens, travaux, opérations et services ci-après : ... » ; un bien ou un service qui n''y figure pas relève du taux normal de l''art. 21', 'S', null, 30, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-S-EXO', 'Opération exonérée (art. 8 à 12)', '{}'::jsonb, 'Opérations exonérées énumérées aux articles 8 à 12 du CTCA (notamment les produits et services de première nécessité, les opérations bancaires réservées aux établissements financiers, les biens acquis dans le cadre d''un régime privilégié)', 'percent', 0, 'sale', 'exempt', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 8, 9, 10, 11 et 12 — opérations exonérées de la taxe sur la valeur ajoutée. Le pack ne reprend pas la liste, longue et modifiée à chaque loi de finances ; le code exact de l''exonération applicable à une opération donnée se lit dans l''article visé sur la facture', 'E', null, 50, 'vat', true, array['supply_nature']::tax_condition[], null, false, false, null, 'ctca', null, null, null, null),
  ('DZ', 'DZ-S-EXP', 'Exportation exonérée', '{}'::jsonb, 'Vente de marchandises exportées, exonérée avec maintien du droit à déduction', 'percent', 0, 'sale', 'export', date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 13, section I — « les affaires de vente et de façon qui portent sur les marchandises exportées » sont exonérées, sous réserve de la justification de l''exportation par les documents douaniers ; section III — les antiquités, œuvres d''art et métaux précieux restent exclus de l''exonération ; l''exportation ouvre droit à déduction de la taxe ayant grevé les éléments du prix de l''opération exonérée', 'G', null, 40, 'vat', true, array['transport_evidence']::tax_condition[], null, false, false, null, 'ctca', null, null, null, null)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  conditions      = excluded.conditions,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code,
  source_key      = excluded.source_key,
  applies_seller_territory = excluded.applies_seller_territory,
  applies_buyer_territory  = excluded.applies_buyer_territory,
  applies_supply_territory = excluded.applies_supply_territory,
  applies_supply_vs_seller = excluded.applies_supply_vs_seller;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.declaration_boxes::text[],
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('DZ-P-19', 'invoice', 'tax', 100, '44566', 'DEDBS', array['DEDBS']::text[], 100, 'DZ-G50', 10),
    ('DZ-P-19', 'credit_note', 'tax', 100, '44566', 'DEDBS', array['DEDBS']::text[], -100, 'DZ-G50', 10),
    ('DZ-P-19-IMMO', 'invoice', 'tax', 100, '44562', 'DEDIMMO', array['DEDIMMO']::text[], 100, 'DZ-G50', 10),
    ('DZ-P-19-IMMO', 'credit_note', 'tax', 100, '44562', 'DEDIMMO', array['DEDIMMO']::text[], -100, 'DZ-G50', 10),
    ('DZ-P-19-ND', 'invoice', 'tax_on_base', 100, null, null, null, 100, null, 10),
    ('DZ-P-19-ND', 'credit_note', 'tax_on_base', 100, null, null, null, 100, null, 10),
    ('DZ-P-9', 'invoice', 'tax', 100, '44566', 'DEDBS', array['DEDBS']::text[], 100, 'DZ-G50', 10),
    ('DZ-P-9', 'credit_note', 'tax', 100, '44566', 'DEDBS', array['DEDBS']::text[], -100, 'DZ-G50', 10),
    ('DZ-P-IMP-19', 'invoice', 'tax', 100, '44566', 'DEDBS', array['DEDBS']::text[], 100, 'DZ-G50', 10),
    ('DZ-P-IMP-19', 'credit_note', 'tax', 100, '44566', 'DEDBS', array['DEDBS']::text[], -100, 'DZ-G50', 10),
    ('DZ-S-19', 'invoice', 'base', 100, null, 'CA19', array['CA19']::text[], 100, 'DZ-G50', 10),
    ('DZ-S-19', 'invoice', 'tax', 100, '44571', 'TVA19', array['TVA19']::text[], 100, 'DZ-G50', 20),
    ('DZ-S-19', 'credit_note', 'base', 100, null, 'CA19', array['CA19']::text[], -100, 'DZ-G50', 10),
    ('DZ-S-19', 'credit_note', 'tax', 100, '44571', 'TVA19', array['TVA19']::text[], -100, 'DZ-G50', 20),
    ('DZ-S-19-SRV', 'invoice', 'base', 100, null, 'CA19', array['CA19']::text[], 100, 'DZ-G50', 10),
    ('DZ-S-19-SRV', 'invoice', 'tax', 100, '44571', 'TVA19', array['TVA19']::text[], 100, 'DZ-G50', 20),
    ('DZ-S-19-SRV', 'credit_note', 'base', 100, null, 'CA19', array['CA19']::text[], -100, 'DZ-G50', 10),
    ('DZ-S-19-SRV', 'credit_note', 'tax', 100, '44571', 'TVA19', array['TVA19']::text[], -100, 'DZ-G50', 20),
    ('DZ-S-9', 'invoice', 'base', 100, null, 'CA9', array['CA9']::text[], 100, 'DZ-G50', 10),
    ('DZ-S-9', 'invoice', 'tax', 100, '44571', 'TVA9', array['TVA9']::text[], 100, 'DZ-G50', 20),
    ('DZ-S-9', 'credit_note', 'base', 100, null, 'CA9', array['CA9']::text[], -100, 'DZ-G50', 10),
    ('DZ-S-9', 'credit_note', 'tax', 100, '44571', 'TVA9', array['TVA9']::text[], -100, 'DZ-G50', 20),
    ('DZ-S-EXO', 'invoice', 'base', 100, null, 'EXO', array['EXO']::text[], 100, 'DZ-G50', 10),
    ('DZ-S-EXO', 'credit_note', 'base', 100, null, 'EXO', array['EXO']::text[], -100, 'DZ-G50', 10),
    ('DZ-S-EXP', 'invoice', 'base', 100, null, 'EXP', array['EXP']::text[], 100, 'DZ-G50', 10),
    ('DZ-S-EXP', 'credit_note', 'base', 100, null, 'EXP', array['EXP']::text[], -100, 'DZ-G50', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, declaration_boxes, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'DZ' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  declaration_boxes  = excluded.declaration_boxes,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, periods, period_default, valid_from, valid_to, legal_reference,
   is_periodic_return, deadline_rule, deadline_day, deadline_plus_days,
   deadline_reference, deadline_source_key, file_format)
values
  ('DZ', 'DZ-G50', 'Déclaration mensuelle — série G n° 50', array['month']::declaration_period[], 'month'::declaration_period, date '2017-01-01', null, 'Code des taxes sur le chiffre d''affaires, art. 28 — les redevables souscrivent, avant le vingtième jour de chaque mois, une déclaration mensuelle des opérations réalisées au titre du mois précédent, y compris en l''absence d''opérations taxables (« déclaration Néant ») ; art. 76-1 — paiement mensuel de la taxe sur le chiffre d''affaires réalisé, au titre du mois précédent, par les contribuables soumis au régime du réel, entre le 1er et le 20 du mois. Le modèle officiel de l''imprimé série G n° 50 n''a pas été retrouvé publié en texte consolidé cette session : les cases de ce formulaire suivent le contenu que l''article 28 impose (opérations taxables et exonérées, taxe exigible, déductions), et non la numérotation de l''imprimé lui-même.', true,'day_of_month_after_period'::filing_deadline_rule, 20, null, 'Code des taxes sur le chiffre d''affaires, art. 76-1, tel que retranscrit par le calendrier fiscal de la Direction générale des impôts : dépôt et paiement entre le 1er et le 20 du mois qui suit celui des opérations, reporté au premier jour ouvrable suivant lorsque le 20 tombe un jour férié ou chômé', 'mfdgi-calendrier', null)
on conflict (country, code) do update set
  name                = excluded.name,
  periods             = excluded.periods,
  period_default      = excluded.period_default,
  valid_from          = excluded.valid_from,
  valid_to            = excluded.valid_to,
  legal_reference     = excluded.legal_reference,
  is_periodic_return  = excluded.is_periodic_return,
  deadline_rule       = excluded.deadline_rule,
  deadline_day        = excluded.deadline_day,
  deadline_plus_days  = excluded.deadline_plus_days,
  deadline_reference  = excluded.deadline_reference,
  deadline_source_key = excluded.deadline_source_key,
  file_format         = excluded.file_format;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence, print_sequence,
   plus_boxes, minus_boxes, rate, rate_of_box, floor_zero, hidden, xml_element,
   legal_reference, source_key)
values
  ('DZ', 'DZ-G50', 'CA19', 'base', 'Opérations taxables au taux normal de 19 %', '{}'::jsonb, 10, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — la déclaration porte le montant des opérations taxables ; art. 21 pour le taux', 'ctca'),
  ('DZ', 'DZ-G50', 'CA9', 'base', 'Opérations taxables au taux réduit de 9 %', '{}'::jsonb, 20, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 et art. 23 pour le taux', 'ctca'),
  ('DZ', 'DZ-G50', 'EXP', 'base', 'Exportations exonérées ouvrant droit à déduction', '{}'::jsonb, 30, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — montant des opérations exonérées ; art. 13 pour l''exonération des exportations', 'ctca'),
  ('DZ', 'DZ-G50', 'EXO', 'base', 'Autres opérations exonérées (art. 8 à 12)', '{}'::jsonb, 40, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — montant des opérations exonérées ; art. 8 à 12 pour la liste', 'ctca'),
  ('DZ', 'DZ-G50', 'CAT', 'total', 'Chiffre d''affaires total du mois', '{}'::jsonb, 50, null, array['CA19', 'CA9', 'EXP', 'EXO']::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — montant des opérations taxables et exonérées', 'ctca'),
  ('DZ', 'DZ-G50', 'TVA19', 'tax', 'Taxe exigible au taux de 19 %', '{}'::jsonb, 60, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — taxe exigible ; art. 14 pour le fait générateur et l''exigibilité', 'ctca'),
  ('DZ', 'DZ-G50', 'TVA9', 'tax', 'Taxe exigible au taux de 9 %', '{}'::jsonb, 70, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 et art. 23', 'ctca'),
  ('DZ', 'DZ-G50', 'TVAB', 'total', 'Total de la taxe exigible', '{}'::jsonb, 80, null, array['TVA19', 'TVA9']::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28', 'ctca'),
  ('DZ', 'DZ-G50', 'DEDIMMO', 'tax', 'TVA déductible sur immobilisations', '{}'::jsonb, 90, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — déductions ; les conditions et exclusions du droit à déduction sont à l''art. 41', 'ctca'),
  ('DZ', 'DZ-G50', 'DEDBS', 'tax', 'TVA déductible sur biens et services (y compris importations)', '{}'::jsonb, 100, null, '{}'::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28 — déductions ; art. 41 pour les conditions et exclusions', 'ctca'),
  ('DZ', 'DZ-G50', 'DEDT', 'total', 'Total des déductions', '{}'::jsonb, 110, null, array['DEDIMMO', 'DEDBS']::text[], '{}'::text[], null, null, false, false, null, 'Code des taxes sur le chiffre d''affaires, art. 28', 'ctca'),
  ('DZ', 'DZ-G50', 'NET', 'total', 'TVA nette à décaisser', '{}'::jsonb, 120, null, array['TVAB']::text[], array['DEDT']::text[], null, null, true, false, null, 'Code des taxes sur le chiffre d''affaires, art. 76-1 — la déclaration vaut titre de paiement de la taxe exigible diminuée des déductions', 'mfdgi-calendrier'),
  ('DZ', 'DZ-G50', 'CRED', 'total', 'Crédit de TVA à reporter', '{}'::jsonb, 130, null, array['DEDT']::text[], array['TVAB']::text[], null, null, true, false, null, 'Code des taxes sur le chiffre d''affaires — l''excédent de taxe déductible non imputé est reporté sur les déclarations suivantes jusqu''à son absorption, ou remboursé dans les conditions que le code fixe pour les crédits nés notamment de l''exportation ou d''un taux de taxe d''amont supérieur au taux de taxe d''aval. Le numéro d''article exact du report et du remboursement n''a pas pu être vérifié dans une édition consolidée officielle cette session : à faire relire', 'ctca')
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  print_sequence  = excluded.print_sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  rate            = excluded.rate,
  rate_of_box     = excluded.rate_of_box,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference,
   source_key)
values
  ('DZ-SCF-BS', 'DZ', 'default', 'Bilan', 'balance_sheet', 'SCF', date '2010-01-01', null, 'Loi n° 07-11 du 25 novembre 2007 portant système comptable financier, art. 25 et 26 ; arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan. En vigueur pour les exercices ouverts à compter du 1er janvier 2010.', 'scf'),
  ('DZ-SCF-IS', 'DZ', 'default', 'Compte de résultat (par nature)', 'income_statement', 'SCF', date '2010-01-01', null, 'Loi n° 07-11 du 25 novembre 2007 portant système comptable financier, art. 25 et 26 ; arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat, présentation par nature. En vigueur pour les exercices ouverts à compter du 1er janvier 2010. Les charges sont lues ici en positif et retranchées par les soldes intermédiaires, là où le modèle les imprime affectées du signe « - ».', 'scf')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference, source_key)
values
  ('DZ-SCF-BS', 'ANC-GW', 'ANC-TOT', 'Écart d''acquisition (goodwill)', '{}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ANC-INC', 'ANC-TOT', 'Immobilisations incorporelles', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif, présenté net des amortissements', 'scf'),
  ('DZ-SCF-BS', 'ANC-TER', 'ANC-TOT', 'Terrains', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ANC-CON', 'ANC-TOT', 'Constructions', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif, présenté net des amortissements', 'scf'),
  ('DZ-SCF-BS', 'ANC-AUT', 'ANC-TOT', 'Autres immobilisations corporelles', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif, présenté net des amortissements et des pertes de valeur', 'scf'),
  ('DZ-SCF-BS', 'ANC-CCN', 'ANC-TOT', 'Immobilisations en concession', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ANC-ENC', 'ANC-TOT', 'Immobilisations en cours', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ANC-FIN', 'ANC-TOT', 'Immobilisations financières', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ANC-IDA', 'ANC-TOT', 'Impôts différés actif', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ANC-TOT', 'ACTIF-TOT', 'TOTAL ACTIF NON COURANT', '{}'::jsonb, 100, 1, true, array['ANC-GW', 'ANC-INC', 'ANC-TER', 'ANC-CON', 'ANC-AUT', 'ANC-CCN', 'ANC-ENC', 'ANC-FIN', 'ANC-IDA']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'AC-STK', 'AC-TOT', 'Stocks et en cours', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif, présenté net des pertes de valeur', 'scf'),
  ('DZ-SCF-BS', 'AC-CLI', 'AC-TOT', 'Clients', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif, présenté net des pertes de valeur sur créances', 'scf'),
  ('DZ-SCF-BS', 'AC-AUT', 'AC-TOT', 'Autres créances et emplois assimilés', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'AC-DISP', 'AC-TOT', 'Disponibilités et assimilés', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'AC-TOT', 'ACTIF-TOT', 'TOTAL ACTIF COURANT', '{}'::jsonb, 150, 1, true, array['AC-STK', 'AC-CLI', 'AC-AUT', 'AC-DISP']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, actif', 'scf'),
  ('DZ-SCF-BS', 'ACTIF-TOT', null, 'TOTAL GENERAL ACTIF', '{}'::jsonb, 160, 1, true, array['ANC-TOT', 'AC-TOT']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan', 'scf'),
  ('DZ-SCF-BS', 'CP-CAP', 'CP-TOT', 'Capital émis', '{}'::jsonb, 170, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — capitaux propres', 'scf'),
  ('DZ-SCF-BS', 'CP-REE', 'CP-TOT', 'Écarts de réévaluation', '{}'::jsonb, 180, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — capitaux propres', 'scf'),
  ('DZ-SCF-BS', 'CP-RES', 'CP-TOT', 'Réserves', '{}'::jsonb, 190, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — capitaux propres', 'scf'),
  ('DZ-SCF-BS', 'CP-RNE', 'CP-TOT', 'Résultat net de l''exercice', '{}'::jsonb, 200, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — capitaux propres', 'scf'),
  ('DZ-SCF-BS', 'CP-RAN', 'CP-TOT', 'Autres capitaux propres — report à nouveau', '{}'::jsonb, 210, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — capitaux propres', 'scf'),
  ('DZ-SCF-BS', 'CP-TOT', 'PASSIF-TOT', 'TOTAL I — CAPITAUX PROPRES', '{}'::jsonb, 220, 1, true, array['CP-CAP', 'CP-REE', 'CP-RES', 'CP-RNE', 'CP-RAN']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif', 'scf'),
  ('DZ-SCF-BS', 'PNC-EMP', 'PNC-TOT', 'Emprunts et dettes financières', '{}'::jsonb, 230, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs non courants', 'scf'),
  ('DZ-SCF-BS', 'PNC-IMP', 'PNC-TOT', 'Impôts (différés et provisionnés)', '{}'::jsonb, 240, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs non courants', 'scf'),
  ('DZ-SCF-BS', 'PNC-AUT', 'PNC-TOT', 'Autres dettes non courantes', '{}'::jsonb, 250, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs non courants', 'scf'),
  ('DZ-SCF-BS', 'PNC-PROV', 'PNC-TOT', 'Provisions et produits comptabilisés d''avance', '{}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs non courants', 'scf'),
  ('DZ-SCF-BS', 'PNC-TOT', 'PASSIF-TOT', 'TOTAL II — PASSIFS NON COURANTS', '{}'::jsonb, 270, 1, true, array['PNC-EMP', 'PNC-IMP', 'PNC-AUT', 'PNC-PROV']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif', 'scf'),
  ('DZ-SCF-BS', 'PC-FOU', 'PC-TOT', 'Fournisseurs et comptes rattachés', '{}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs courants', 'scf'),
  ('DZ-SCF-BS', 'PC-IMP', 'PC-TOT', 'Impôts', '{}'::jsonb, 290, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs courants', 'scf'),
  ('DZ-SCF-BS', 'PC-AUT', 'PC-TOT', 'Autres dettes', '{}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs courants', 'scf'),
  ('DZ-SCF-BS', 'PC-REG', 'PC-TOT', 'Comptes de régularisation et transitoires', '{}'::jsonb, 310, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif — passifs courants', 'scf'),
  ('DZ-SCF-BS', 'PC-TOT', 'PASSIF-TOT', 'TOTAL III — PASSIFS COURANTS', '{}'::jsonb, 320, 1, true, array['PC-FOU', 'PC-IMP', 'PC-AUT', 'PC-REG']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan, passif', 'scf'),
  ('DZ-SCF-BS', 'PASSIF-TOT', null, 'TOTAL GENERAL PASSIF', '{}'::jsonb, 330, 1, true, array['CP-TOT', 'PNC-TOT', 'PC-TOT']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 2 — modèle de bilan', 'scf'),
  ('DZ-SCF-IS', 'IS-CA', 'IS-TPO', 'Chiffre d''affaires', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-PS', 'IS-TPO', 'Production stockée (ou déstockage)', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-PI', 'IS-TPO', 'Production immobilisée', '{}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-SUB', 'IS-TPO', 'Subventions d''exploitation', '{}'::jsonb, 40, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-APO', 'IS-TPO', 'Autres produits opérationnels', '{}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-REP', 'IS-TPO', 'Reprises sur pertes de valeur et provisions', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-TPO', 'IS-ROP', 'TOTAL DES PRODUITS OPERATIONNELS', '{}'::jsonb, 70, 1, true, array['IS-CA', 'IS-PS', 'IS-PI', 'IS-SUB', 'IS-APO', 'IS-REP']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-ACH', 'IS-TCO', 'Achats consommés', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-SE', 'IS-TCO', 'Services extérieurs et autres consommations', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-PER', 'IS-TCO', 'Charges de personnel', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-TAX', 'IS-TCO', 'Impôts, taxes et versements assimilés', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-ACO', 'IS-TCO', 'Autres charges opérationnelles', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-DOT', 'IS-TCO', 'Dotations aux amortissements et aux provisions', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-TCO', 'IS-ROP', 'TOTAL DES CHARGES OPERATIONNELLES', '{}'::jsonb, 140, 1, true, array['IS-ACH', 'IS-SE', 'IS-PER', 'IS-TAX', 'IS-ACO', 'IS-DOT']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-ROP', 'IS-ROA', 'RESULTAT OPERATIONNEL', '{}'::jsonb, 150, 1, true, array['IS-TPO']::text[], array['IS-TCO']::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-PF', 'IS-RF', 'Produits financiers', '{}'::jsonb, 160, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-CF', 'IS-RF', 'Charges financières', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-RF', 'IS-ROA', 'RESULTAT FINANCIER', '{}'::jsonb, 180, 1, true, array['IS-PF']::text[], array['IS-CF']::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-ROA', 'IS-RAO', 'RESULTAT ORDINAIRE AVANT IMPOTS', '{}'::jsonb, 190, 1, true, array['IS-ROP', 'IS-RF']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-IMP', 'IS-RAO', 'Impôts exigibles sur résultats ordinaires', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-RAO', 'IS-RES', 'RESULTAT NET DES ACTIVITES ORDINAIRES', '{}'::jsonb, 210, 1, true, array['IS-ROA']::text[], array['IS-IMP']::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-PEX', 'IS-REX', 'Produits extraordinaires', '{}'::jsonb, 220, -1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-CEX', 'IS-REX', 'Charges extraordinaires', '{}'::jsonb, 230, 1, false, '{}'::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-REX', 'IS-RES', 'RESULTAT EXTRAORDINAIRE', '{}'::jsonb, 240, 1, true, array['IS-PEX']::text[], array['IS-CEX']::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf'),
  ('DZ-SCF-IS', 'IS-RES', null, 'RESULTAT NET DE L''EXERCICE', '{}'::jsonb, 250, 1, true, array['IS-RAO', 'IS-REX']::text[], '{}'::text[], null, 'Arrêté du 26 juillet 2008, titre II, chapitre 3 — modèle de compte de résultat', 'scf')
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference,
  source_key      = excluded.source_key;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('DZ-SCF-BS', 'ANC-GW', 10, 'code_range', '207', '207', null, 'any'),
    ('DZ-SCF-BS', 'ANC-INC', 10, 'code_range', '203', '205', null, 'any'),
    ('DZ-SCF-BS', 'ANC-INC', 20, 'code_range', '208', '208', null, 'any'),
    ('DZ-SCF-BS', 'ANC-INC', 30, 'code_range', '280', '280', null, 'any'),
    ('DZ-SCF-BS', 'ANC-TER', 10, 'code_range', '211', '211', null, 'any'),
    ('DZ-SCF-BS', 'ANC-CON', 10, 'code_range', '213', '213', null, 'any'),
    ('DZ-SCF-BS', 'ANC-CON', 20, 'code_range', '2813', '2813', null, 'any'),
    ('DZ-SCF-BS', 'ANC-AUT', 10, 'code_range', '215', '215', null, 'any'),
    ('DZ-SCF-BS', 'ANC-AUT', 20, 'code_range', '2182', '2184', null, 'any'),
    ('DZ-SCF-BS', 'ANC-AUT', 30, 'code_range', '2815', '2815', null, 'any'),
    ('DZ-SCF-BS', 'ANC-AUT', 40, 'code_range', '2818', '2818', null, 'any'),
    ('DZ-SCF-BS', 'ANC-AUT', 50, 'code_range', '29', '29', null, 'any'),
    ('DZ-SCF-BS', 'ANC-CCN', 10, 'code_range', '22', '22', null, 'any'),
    ('DZ-SCF-BS', 'ANC-ENC', 10, 'code_range', '232', '232', null, 'any'),
    ('DZ-SCF-BS', 'ANC-ENC', 20, 'code_range', '237', '237', null, 'any'),
    ('DZ-SCF-BS', 'ANC-FIN', 10, 'code_range', '261', '261', null, 'any'),
    ('DZ-SCF-BS', 'ANC-FIN', 20, 'code_range', '267', '267', null, 'any'),
    ('DZ-SCF-BS', 'ANC-FIN', 30, 'code_range', '274', '276', null, 'any'),
    ('DZ-SCF-BS', 'ANC-IDA', 10, 'code_range', '133', '133', null, 'any'),
    ('DZ-SCF-BS', 'AC-STK', 10, 'code_range', '30', '31', null, 'any'),
    ('DZ-SCF-BS', 'AC-STK', 20, 'code_range', '35', '35', null, 'any'),
    ('DZ-SCF-BS', 'AC-STK', 30, 'code_range', '39', '39', null, 'any'),
    ('DZ-SCF-BS', 'AC-CLI', 10, 'code_range', '411', '411', null, 'any'),
    ('DZ-SCF-BS', 'AC-CLI', 20, 'code_range', '413', '413', null, 'any'),
    ('DZ-SCF-BS', 'AC-CLI', 30, 'code_range', '416', '416', null, 'any'),
    ('DZ-SCF-BS', 'AC-CLI', 40, 'code_range', '418', '418', null, 'any'),
    ('DZ-SCF-BS', 'AC-CLI', 50, 'code_range', '49', '49', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 10, 'code_range', '409', '409', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 20, 'code_range', '425', '425', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 30, 'code_range', '441', '441', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 40, 'code_range', '44562', '44562', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 50, 'code_range', '44566', '44566', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 60, 'code_range', '44567', '44567', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 70, 'code_range', '462', '462', null, 'any'),
    ('DZ-SCF-BS', 'AC-AUT', 80, 'code_range', '486', '486', null, 'any'),
    ('DZ-SCF-BS', 'AC-DISP', 10, 'code_range', '50', '50', null, 'any'),
    ('DZ-SCF-BS', 'AC-DISP', 20, 'code_range', '511', '512', null, 'any'),
    ('DZ-SCF-BS', 'AC-DISP', 30, 'code_range', '530', '530', null, 'any'),
    ('DZ-SCF-BS', 'AC-DISP', 40, 'code_range', '54', '54', null, 'any'),
    ('DZ-SCF-BS', 'AC-DISP', 50, 'code_range', '58', '58', null, 'any'),
    ('DZ-SCF-BS', 'AC-DISP', 60, 'code_range', '59', '59', null, 'any'),
    ('DZ-SCF-BS', 'CP-CAP', 10, 'code_range', '101', '101', null, 'any'),
    ('DZ-SCF-BS', 'CP-CAP', 20, 'code_range', '103', '103', null, 'any'),
    ('DZ-SCF-BS', 'CP-CAP', 30, 'code_range', '108', '109', null, 'any'),
    ('DZ-SCF-BS', 'CP-REE', 10, 'code_range', '105', '105', null, 'any'),
    ('DZ-SCF-BS', 'CP-RES', 10, 'code_range', '106', '106', null, 'any'),
    ('DZ-SCF-BS', 'CP-RNE', 10, 'code_range', '120', '120', null, 'any'),
    ('DZ-SCF-BS', 'CP-RNE', 20, 'code_range', '129', '129', null, 'any'),
    ('DZ-SCF-BS', 'CP-RAN', 10, 'code_range', '110', '110', null, 'any'),
    ('DZ-SCF-BS', 'CP-RAN', 20, 'code_range', '119', '119', null, 'any'),
    ('DZ-SCF-BS', 'PNC-EMP', 10, 'code_range', '164', '165', null, 'any'),
    ('DZ-SCF-BS', 'PNC-EMP', 20, 'code_range', '168', '168', null, 'any'),
    ('DZ-SCF-BS', 'PNC-EMP', 30, 'code_range', '17', '17', null, 'any'),
    ('DZ-SCF-BS', 'PNC-IMP', 10, 'code_range', '134', '134', null, 'any'),
    ('DZ-SCF-BS', 'PNC-IMP', 20, 'code_range', '155', '155', null, 'any'),
    ('DZ-SCF-BS', 'PNC-AUT', 10, 'code_range', '18', '18', null, 'any'),
    ('DZ-SCF-BS', 'PNC-PROV', 10, 'code_range', '131', '132', null, 'any'),
    ('DZ-SCF-BS', 'PNC-PROV', 20, 'code_range', '138', '138', null, 'any'),
    ('DZ-SCF-BS', 'PNC-PROV', 30, 'code_range', '153', '153', null, 'any'),
    ('DZ-SCF-BS', 'PNC-PROV', 40, 'code_range', '158', '158', null, 'any'),
    ('DZ-SCF-BS', 'PC-FOU', 10, 'code_range', '401', '401', null, 'any'),
    ('DZ-SCF-BS', 'PC-FOU', 20, 'code_range', '403', '404', null, 'any'),
    ('DZ-SCF-BS', 'PC-FOU', 30, 'code_range', '408', '408', null, 'any'),
    ('DZ-SCF-BS', 'PC-IMP', 10, 'code_range', '444', '444', null, 'any'),
    ('DZ-SCF-BS', 'PC-IMP', 20, 'code_range', '44551', '44551', null, 'any'),
    ('DZ-SCF-BS', 'PC-IMP', 30, 'code_range', '44571', '44572', null, 'any'),
    ('DZ-SCF-BS', 'PC-IMP', 40, 'code_range', '447', '448', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 10, 'code_range', '419', '419', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 20, 'code_range', '421', '421', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 30, 'code_range', '428', '428', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 40, 'code_range', '431', '431', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 50, 'code_range', '438', '438', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 60, 'code_range', '455', '455', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 70, 'code_range', '457', '457', null, 'any'),
    ('DZ-SCF-BS', 'PC-AUT', 80, 'code_range', '467', '467', null, 'any'),
    ('DZ-SCF-BS', 'PC-REG', 10, 'code_range', '471', '471', null, 'any'),
    ('DZ-SCF-BS', 'PC-REG', 20, 'code_range', '487', '487', null, 'any'),
    ('DZ-SCF-IS', 'IS-CA', 10, 'code_range', '700', '701', null, 'any'),
    ('DZ-SCF-IS', 'IS-CA', 20, 'code_range', '706', '706', null, 'any'),
    ('DZ-SCF-IS', 'IS-CA', 30, 'code_range', '709', '709', null, 'any'),
    ('DZ-SCF-IS', 'IS-PS', 10, 'code_range', '72', '72', null, 'any'),
    ('DZ-SCF-IS', 'IS-PI', 10, 'code_range', '73', '73', null, 'any'),
    ('DZ-SCF-IS', 'IS-SUB', 10, 'code_range', '74', '74', null, 'any'),
    ('DZ-SCF-IS', 'IS-APO', 10, 'code_range', '758', '758', null, 'any'),
    ('DZ-SCF-IS', 'IS-REP', 10, 'code_range', '78', '78', null, 'any'),
    ('DZ-SCF-IS', 'IS-ACH', 10, 'code_range', '601', '603', null, 'any'),
    ('DZ-SCF-IS', 'IS-ACH', 20, 'code_range', '607', '607', null, 'any'),
    ('DZ-SCF-IS', 'IS-ACH', 30, 'code_range', '609', '609', null, 'any'),
    ('DZ-SCF-IS', 'IS-SE', 10, 'code_range', '611', '611', null, 'any'),
    ('DZ-SCF-IS', 'IS-SE', 20, 'code_range', '613', '613', null, 'any'),
    ('DZ-SCF-IS', 'IS-SE', 30, 'code_range', '615', '616', null, 'any'),
    ('DZ-SCF-IS', 'IS-SE', 40, 'code_range', '621', '628', null, 'any'),
    ('DZ-SCF-IS', 'IS-PER', 10, 'code_range', '631', '631', null, 'any'),
    ('DZ-SCF-IS', 'IS-PER', 20, 'code_range', '635', '635', null, 'any'),
    ('DZ-SCF-IS', 'IS-PER', 30, 'code_range', '638', '638', null, 'any'),
    ('DZ-SCF-IS', 'IS-TAX', 10, 'code_range', '641', '641', null, 'any'),
    ('DZ-SCF-IS', 'IS-ACO', 10, 'code_range', '651', '651', null, 'any'),
    ('DZ-SCF-IS', 'IS-ACO', 20, 'code_range', '654', '654', null, 'any'),
    ('DZ-SCF-IS', 'IS-ACO', 30, 'code_range', '658', '658', null, 'any'),
    ('DZ-SCF-IS', 'IS-DOT', 10, 'code_range', '681', '681', null, 'any'),
    ('DZ-SCF-IS', 'IS-DOT', 20, 'code_range', '685', '685', null, 'any'),
    ('DZ-SCF-IS', 'IS-PF', 10, 'code_range', '766', '768', null, 'any'),
    ('DZ-SCF-IS', 'IS-CF', 10, 'code_range', '661', '661', null, 'any'),
    ('DZ-SCF-IS', 'IS-CF', 20, 'code_range', '666', '666', null, 'any'),
    ('DZ-SCF-IS', 'IS-CF', 30, 'code_range', '668', '668', null, 'any'),
    ('DZ-SCF-IS', 'IS-IMP', 10, 'code_range', '695', '698', null, 'any'),
    ('DZ-SCF-IS', 'IS-PEX', 10, 'code_range', '77', '77', null, 'any'),
    ('DZ-SCF-IS', 'IS-CEX', 10, 'code_range', '67', '67', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, name_i18n, languages, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit, fx_gain_code, fx_loss_code,
   asset_disposal_gain_code, asset_disposal_loss_code,
   asset_disposal_proceeds_code, asset_disposal_value_code,
   tax_payable_code, tax_receivable_code, opening_entry_label,
   vat_period_default)
values
  ('DZ', 'Algérie', '{}'::jsonb, array['fr']::text[], 'DZD', '411', '401', '471', '658', '110', '700', '607', '512', '530', 'VT', 'AC', 'OD', 'fr', 'result_accounts', '120', '129', '119', 'AN', 'half_up', default, '766', '666', null, null, null, null, '44551', '44567', 'À-nouveaux', 'month'::declaration_period)
on conflict (country) do update set
  name                   = excluded.name,
  name_i18n              = excluded.name_i18n,
  languages              = excluded.languages,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit,
  fx_gain_code           = excluded.fx_gain_code,
  fx_loss_code           = excluded.fx_loss_code,
  asset_disposal_gain_code        = excluded.asset_disposal_gain_code,
  asset_disposal_loss_code        = excluded.asset_disposal_loss_code,
  asset_disposal_proceeds_code    = excluded.asset_disposal_proceeds_code,
  asset_disposal_value_code       = excluded.asset_disposal_value_code,
  tax_payable_code                = excluded.tax_payable_code,
  tax_receivable_code             = excluded.tax_receivable_code,
  opening_entry_label             = excluded.opening_entry_label,
  vat_period_default              = excluded.vat_period_default;

update country_defaults set
  numbering_gapless             = true,
  number_format                 = '{CODE}-{NNNN}',
  legal_payment_days            = null,
  late_payment_reference        = null,
  numbering_legal_reference     = 'Décret exécutif n° 05-468 du 10 décembre 2005 ; décret exécutif n° 16-66 du 16 février 2016, art. 5, qui reprend la même règle pour les documents équivalents des secteurs agricole, de la pêche et de l''artisanat — les factures et documents en tenant lieu sont extraits d''un carnet à souches, ou d''une suite logicielle, à « numération de série ininterrompue et chronologique ». Le texte impose la continuité de la séquence, jamais une remise à zéro annuelle ni une forme particulière du numéro.',
  numbering_source_key          = 'decret-05-468',
  payment_terms_legal_reference = null,
  payment_terms_source_key      = null,
  tax_point_rule                = 'delivery_date',
  tax_point_legal_reference     = 'Code des taxes sur le chiffre d''affaires, art. 14 — pour une vente, le fait générateur est la livraison juridique ou matérielle du bien ; pour une prestation de services, il est constitué par l''encaissement partiel ou total du prix, avec exigibilité au plus tard un an après la livraison à défaut d''encaissement — régularisation que ce pack ne modélise pas. delivery_date dit le principe des ventes de biens ; la branche des prestations de services est portée par les taxes de service en cash_basis, et non par une seconde règle du pays.',
  tax_point_source_key          = 'ctca',
  posted_edit_policy            = null,
  posted_edit_policy_legal_reference = null,
  posted_edit_policy_source_key = null,
  einvoice_profile              = null,
  einvoice_mandatory_from       = null,
  einvoice_obligation           = 'none',
  einvoice_legal_reference      = 'À la date de ce pack, aucun texte de portée générale n''oblige les entreprises algériennes à échanger des factures électroniques entre elles : le Code des taxes sur le chiffre d''affaires et le décret exécutif n° 05-468 du 10 décembre 2005 organisent la facture sur support ordinaire, et la Direction générale des impôts déploie des téléservices de déclaration et de paiement (Jibaya''tic) sans qu''un format ni une obligation de facturation électronique interentreprises n''aient été publiés et vérifiés cette session. Une facturation numérique existe déjà pour certains grands comptes et fournisseurs de l''État, sous des dispositifs particuliers que ce pack ne modélise pas faute de texte consolidé retrouvé.',
  einvoice_source_key           = 'mfdgi-tva',
  party_scheme                  = null,
  vat_scheme                    = null,
  bank_statement_formats        = null,
  payment_formats               = null,
  fiscal_year_default           = 'calendar'
 where country = 'DZ';
