-- Ekwo OS — España: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/es/fixed_assets.json at version 0.5.0, do not edit.
-- Change the pack and run `ekwo pack build es`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the fixed assets module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into fixed_assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('ES', 'days', 'days', 'actual', null, true, 'net_result', 'Plan General de Contabilidad (Real Decreto 1514/2007), norma de registro y valoración 2.ª, apartado 2.1 — las amortizaciones se establecen de manera sistemática y racional en función de la vida útil y del valor residual del bien. Ni el Plan ni la Ley 27/2014 (art. 12) fijan cómo se prorratea el primer ejercicio: contar los días reales desde la puesta en funcionamiento hasta el cierre es la práctica corriente y no una regla de texto, tanto en lineal como en porcentaje constante. Ley 27/2014, art. 12.1.b — el porcentaje constante se aplica sobre el valor pendiente de amortización, ponderando el coeficiente lineal por 1,5, 2 o 2,5 según el período, con un mínimo del 11 %; la ley no fija un tope sobre el valor de adquisición (por eso no hay tope) ni prevé el paso al lineal, que el módulo aplica para que el plan termine.')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into fixed_assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::fixed_assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::fixed_assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('ES', 'goodwill', 'Fondo de comercio', '{"en":"Goodwill"}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 10, 'Plan General de Contabilidad (Real Decreto 1514/2007), norma de registro y valoración 6.ª, c) — el fondo de comercio se amortiza durante su vida útil y se presume, salvo prueba en contrario, que es de diez años y que su recuperación es lineal. Fiscalmente, Ley 27/2014, art. 12.2, la amortización del fondo de comercio es deducible con el límite anual máximo de la veinteava parte de su importe: el exceso sobre ese límite es un ajuste fiscal que esta sección no expresa.'),
    ('ES', 'development', 'Gastos de desarrollo activados', '{"en":"Capitalised development costs"}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 20, 'Plan General de Contabilidad, norma de registro y valoración 6.ª, a) — los gastos de desarrollo activados se amortizan durante su vida útil, que se presume, salvo prueba en contrario, que no es superior a cinco años (los de investigación, dentro del plazo de cinco años). Cinco años es el tope de la presunción, no una duración obligatoria.'),
    ('ES', 'software', 'Aplicaciones informáticas', '{"en":"Software"}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 30, 'Plan General de Contabilidad, norma de registro y valoración 6.ª, e) — los programas de ordenador siguen los mismos criterios de amortización que los gastos de desarrollo: vida útil presumida no superior a cinco años. Ley 27/2014, art. 12.1.a, «Sistemas y programas informáticos»: coeficiente lineal máximo 33 %, período máximo 6 años; cinco años (20 % anual) queda dentro de la tabla.'),
    ('ES', 'intangible-other', 'Otro inmovilizado intangible (vida útil no estimable)', '{"en":"Other intangible assets (useful life not reliably estimable)"}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 40, 'Plan General de Contabilidad, norma de registro y valoración 5.ª, apartado 2 — cuando la vida útil de un inmovilizado intangible no pueda estimarse de manera fiable, se amortiza en un plazo de diez años, sin perjuicio de los plazos de las normas particulares (6.ª). Una concesión o una licencia con plazo propio usa ese plazo en su lugar. Ley 27/2014, art. 12.2: sin vida útil fiable, la amortización fiscal tiene el límite anual de la veinteava parte.'),
    ('ES', 'building-commercial', 'Edificios comerciales, administrativos, de servicios y viviendas', '{"en":"Commercial, administrative and service buildings and dwellings"}'::jsonb, 'straight_line', 600, null, null, 'asset_fixed', 50, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Edificios comerciales, administrativos, de servicios y viviendas», coeficiente lineal máximo 2 %, período máximo 100 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'building-industrial', 'Edificios industriales', '{"en":"Industrial buildings"}'::jsonb, 'straight_line', 400, null, null, 'asset_fixed', 60, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Edificios industriales», coeficiente lineal máximo 3 %, período máximo 68 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'fixtures', 'Instalaciones (resto de instalaciones)', '{"en":"Installations (other installations)"}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 70, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Resto instalaciones», coeficiente lineal máximo 10 %, período máximo 20 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'machinery', 'Maquinaria', '{"en":"Machinery"}'::jsonb, 'straight_line', 100, null, null, 'asset_fixed', 80, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Maquinaria», coeficiente lineal máximo 12 %, período máximo 18 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'machinery-declining', 'Maquinaria — porcentaje constante', '{"en":"Machinery — constant percentage"}'::jsonb, 'declining_balance', 216, 2.5, null, 'asset_fixed', 90, 'Ley 27/2014, art. 12.1.b — porcentaje constante sobre el valor pendiente de amortización: el coeficiente lineal obtenido del período de la tabla del art. 12.1.a («Maquinaria», 18 años, máximo 12 %) se pondera por 2,5, según que el período sea inferior a 5 años (1,5), de 5 a menos de 8 años (2) o de 8 años o más (2,5); el porcentaje constante no puede ser inferior al 11 %. La duración es el período máximo de la tabla. Los edificios, el mobiliario y los enseres no pueden acogerse a este método. El texto no prevé el paso al lineal: el que aplica el módulo es su mecanismo para que el plan termine.'),
    ('ES', 'medical-equipment', 'Equipos médicos y asimilados', '{"en":"Medical and similar equipment"}'::jsonb, 'straight_line', 80, null, null, 'asset_fixed', 100, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Equipos médicos y asimilados», coeficiente lineal máximo 15 %, período máximo 14 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'vehicle', 'Elementos de transporte externo', '{"en":"External transport equipment"}'::jsonb, 'straight_line', 75, null, null, 'asset_fixed', 110, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Elementos de transporte externo», coeficiente lineal máximo 16 %, período máximo 14 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'truck', 'Autocamiones', '{"en":"Lorries"}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 120, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Autocamiones», coeficiente lineal máximo 20 %, período máximo 10 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'truck-declining', 'Autocamiones — porcentaje constante', '{"en":"Lorries — constant percentage"}'::jsonb, 'declining_balance', 120, 2.5, null, 'asset_fixed', 130, 'Ley 27/2014, art. 12.1.b — porcentaje constante sobre el valor pendiente de amortización: el coeficiente lineal obtenido del período de la tabla del art. 12.1.a («Autocamiones», 10 años, máximo 20 %) se pondera por 2,5, según que el período sea inferior a 5 años (1,5), de 5 a menos de 8 años (2) o de 8 años o más (2,5); el porcentaje constante no puede ser inferior al 11 %. La duración es el período máximo de la tabla. Los edificios, el mobiliario y los enseres no pueden acogerse a este método. El texto no prevé el paso al lineal: el que aplica el módulo es su mecanismo para que el plan termine.'),
    ('ES', 'furniture', 'Mobiliario', '{"en":"Furniture"}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 140, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Mobiliario», coeficiente lineal máximo 10 %, período máximo 20 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'tools', 'Útiles y herramientas', '{"en":"Tools and implements"}'::jsonb, 'straight_line', 48, null, null, 'asset_fixed', 150, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Útiles y herramientas», coeficiente lineal máximo 25 %, período máximo 8 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'electronic-equipment', 'Equipos electrónicos', '{"en":"Electronic equipment"}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 160, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Equipos electrónicos», coeficiente lineal máximo 20 %, período máximo 10 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'it-equipment', 'Equipos para procesos de información', '{"en":"Information-processing equipment"}'::jsonb, 'straight_line', 48, null, null, 'asset_fixed', 170, 'Ley 27/2014 del Impuesto sobre Sociedades, art. 12.1.a — tabla de coeficientes de amortización lineal: «Equipos para procesos de información», coeficiente lineal máximo 25 %, período máximo 8 años. La duración propuesta es la más corta cuyo porcentaje anual no supera el coeficiente lineal máximo de la tabla (12 × 100 / coeficiente, en meses); el período máximo de la tabla es un tope de años, no una vida útil. La vida útil real la estima la empresa (PGC, norma de registro y valoración 2.ª, apartado 2.1) y la categoría solo propone.'),
    ('ES', 'it-equipment-declining', 'Equipos para procesos de información — porcentaje constante', '{"en":"Information-processing equipment — constant percentage"}'::jsonb, 'declining_balance', 96, 2.5, null, 'asset_fixed', 180, 'Ley 27/2014, art. 12.1.b — porcentaje constante sobre el valor pendiente de amortización: el coeficiente lineal obtenido del período de la tabla del art. 12.1.a («Equipos para procesos de información», 8 años, máximo 25 %) se pondera por 2,5, según que el período sea inferior a 5 años (1,5), de 5 a menos de 8 años (2) o de 8 años o más (2,5); el porcentaje constante no puede ser inferior al 11 %. La duración es el período máximo de la tabla. Los edificios, el mobiliario y los enseres no pueden acogerse a este método. El texto no prevé el paso al lineal: el que aplica el módulo es su mecanismo para que el plan termine.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

