-- Ekwo OS — Australia: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/au/fixed_assets.json at version 0.4.0, do not edit.
-- Change the pack and run `ekwo pack build au`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the fixed assets module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into fixed_assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('AU', 'days', 'days', 'actual', null, true, 'net_result', 'AASB 116, paragraph 55 — depreciation begins when the asset is available for use, so the first period carries only the part of the year the asset was held. Paragraph 62 prescribes no method and names the straight line, the diminishing balance and the units of production among those an entity may select, so no cap on a declining annuity is declared. The proration is in days because that is the Australian convention in the one place it is written down: Income Tax Assessment Act 1997, section 40-75(1) (prime cost) multiplies by days held over 365, and sections 40-70(1) and 40-72(1) (diminishing value, 150% before and 200% after 9 May 2006) do the same, counting days from the day the asset is first used or installed ready for use. The module counts the days of the real calendar, so a year of 366 days divides by 366 where the Act divides by 365, and the day of entry into service is counted. Division 40 is a tax computation and AASB 116 does not oblige the books to follow it; the module carries one schedule, so a company whose tax depreciation differs from its accounting depreciation keeps the difference outside. The module switches the diminishing value to the straight line over the remaining periods once that is larger, which Division 40 does not do (its balance never reaches zero) and which a schedule needs in order to end.')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into fixed_assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::fixed_assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::fixed_assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('AU', 'buildings', 'Buildings (capital works)', '{}'::jsonb, 'straight_line', 480, null, null, 'asset_fixed', 10, 'Income Tax Assessment Act 1997, section 43-25(1) — the deduction for capital works begun after 26 February 1992 is 2.5% of the construction expenditure a year for most non-residential buildings, which is forty years on the straight line (4% for parts used in the manner of Table 43-145, not carried here). Division 43 is a tax deduction and not a depreciation of the accounts, and land is not depreciated, so a property is split before this category reaches the building. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the rate of the capital works deduction, a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'in-house-software', 'Software developed for own use', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 20, 'Income Tax Assessment Act 1997, section 40-95(7), item 8 — the effective life of in-house software is 5 years, fixed by the Act and not by the Commissioner. Software bought off the shelf is not in-house software and is not carried here. AASB 138 on intangible assets was not read for this pack, so the accounting treatment of the cost (capitalise or expense) is the accountant''s to decide. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the life the Act gives for income tax; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'standard-patents', 'Standard patents', '{}'::jsonb, 'straight_line', 240, null, null, 'asset_fixed', 30, 'Income Tax Assessment Act 1997, section 40-95(7), item 1 — the effective life of a standard patent is 20 years, fixed by the Act. Other intellectual property carries other statutory lives (registered designs 15 years, copyright the shorter of 25 years and its term, a licence its term) and is not carried here. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the life the Act gives for income tax; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'office-furniture', 'Office furniture, freestanding', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 40, 'Table B of the 2025 determination, Office furniture, freestanding: chairs 10 years, general tables 10 years and reception assets 10 years. Desks, workstations, screens and boardroom tables are 20 years and metal cabinets 20 years, so ten years is the life of the seating and tables and a company with mostly desks sets a longer one. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the effective life the Commissioner of Taxation determines for income tax under section 40-100 of the Income Tax Assessment Act 1997, which a business may use or replace with its own estimate under section 40-95; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'desktop-computers', 'Desktop computers, monitors and servers', '{}'::jsonb, 'straight_line', 48, null, null, 'asset_fixed', 50, 'Table B of the 2025 determination, Computers and computer equipment: desktop computers (including personal computers) 4 years, computer monitors 4 years, servers 4 years, and 4 years for computer equipment not specified elsewhere. Network equipment is 5 years and mainframes 5 years, not carried here. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the effective life the Commissioner of Taxation determines for income tax under section 40-100 of the Income Tax Assessment Act 1997, which a business may use or replace with its own estimate under section 40-95; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'portable-computers', 'Laptops and tablets', '{}'::jsonb, 'straight_line', 24, null, null, 'asset_fixed', 60, 'Table B of the 2025 determination, Computers and computer equipment: mobile/portable computers (including laptops, tablets) 2 years. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the effective life the Commissioner of Taxation determines for income tax under section 40-100 of the Income Tax Assessment Act 1997, which a business may use or replace with its own estimate under section 40-95; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'cars', 'Cars, straight line', '{}'::jsonb, 'straight_line', 96, null, null, 'asset_fixed', 70, 'Table B of the 2025 determination, Motor vehicles and trailers: cars, designed to carry a load of less than one tonne and fewer than 9 passengers, generally, 8 years. Hire cars, rental cars and taxis have shorter lives and are not carried here; section 40-102 of the Income Tax Assessment Act 1997 may cap the life of a car for tax and the cap was not read. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the effective life the Commissioner of Taxation determines for income tax under section 40-100 of the Income Tax Assessment Act 1997, which a business may use or replace with its own estimate under section 40-95; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'cars-diminishing', 'Cars, diminishing value at 200%', '{}'::jsonb, 'declining_balance', 96, 2, null, 'asset_fixed', 80, 'Income Tax Assessment Act 1997, section 40-72(1) — for an asset first held on or after 10 May 2006 the diminishing value method takes the base value times days held over 365 times 200% over the effective life, which is twice the straight-line rate: coefficient 2 on the 8 years of Table B of the 2025 determination for a car. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the effective life the Commissioner of Taxation determines for income tax under section 40-100 of the Income Tax Assessment Act 1997, which a business may use or replace with its own estimate under section 40-95; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.'),
    ('AU', 'light-commercial-vehicles', 'Light commercial vehicles', '{}'::jsonb, 'straight_line', 144, null, null, 'asset_fixed', 90, 'Table B of the 2025 determination, Motor vehicles and trailers: light commercial vehicles designed to carry a load of one tonne or greater and having a gross vehicle mass of 3.5 tonnes or less, 12 years. There is no accounting table of useful lives in Australia: AASB 116, paragraphs 50 and 51, make the entity allocate the depreciable amount over the useful life it estimates and review it at least at each year end. The duration below is the effective life the Commissioner of Taxation determines for income tax under section 40-100 of the Income Tax Assessment Act 1997, which a business may use or replace with its own estimate under section 40-95; it is a tax figure that Australian practice often adopts for the books and not an accounting rule, and an asset that depreciates differently says so in its own columns.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

