-- Ekwo OS — Nigeria: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/ng/fixed_assets.json at version 0.3.0, do not edit.
-- Change the pack and run `ekwo pack build ng`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the fixed assets module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into fixed_assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('NG', 'days', 'days', 'actual', null, true, 'net_result', 'IFRS for SMEs, Section 17, paragraph 17.20 — depreciation of an asset begins when it is available for use, that is when it is in the location and condition necessary for it to be capable of operating in the manner intended by management, and ceases when the asset is derecognised; paragraph 17.22 names the straight-line method and the diminishing balance method among those an entity may select. The Standard does not say how a first period is cut; this pack counts the real days from the day the asset is available for use, and a company that counts whole months sets prorata = ''months'' on the asset. Nothing in the Standard or in the Nigerian texts read caps an annuity, which is why no cap is declared. The Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria).')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into fixed_assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::fixed_assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::fixed_assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('NG', 'goodwill', 'Goodwill', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 10, 'IFRS for SMEs, paragraph 19.34 — goodwill is measured at cost less accumulated amortisation and impairment, amortised under paragraphs 18.19 to 18.24, and where its useful life cannot be reliably established the best estimate of it shall not exceed ten years. Ten years is therefore the ceiling this category starts from and not a life anybody estimated. The Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria).'),
    ('NG', 'intangibles', 'Other intangible assets, patents and licences', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 20, 'IFRS for SMEs, Section 18, paragraphs 18.19 to 18.22 — every intangible asset has a finite useful life, never longer than the period of the contractual or legal rights it arises from; where the life cannot be established reliably it is management''s best estimate and does not exceed ten years; amortisation begins when the asset is available for use and uses the straight line where the pattern cannot be determined reliably. Five years is common practice and not a rule read in a Nigerian text: a licence or a patent takes the term of its own right instead. The Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria).'),
    ('NG', 'freehold-buildings', 'Freehold buildings', '{}'::jsonb, 'straight_line', 600, null, null, 'asset_fixed', 30, 'Land is not depreciated (paragraph 17.16) and the building on it is, so a freehold property is split before this category is applied to the part that has a life. There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.'),
    ('NG', 'leasehold-improvements', 'Leasehold property and improvements', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 40, 'Common practice depreciates a leasehold improvement over the shorter of its own life and the remaining term of the lease (paragraph 17.21(d), legal limits such as the expiry of a lease), which is a fact about the lease and not about the category. There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.'),
    ('NG', 'plant-and-machinery', 'Plant and machinery', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 50, 'There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.'),
    ('NG', 'fixtures-and-fittings', 'Fixtures and fittings', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 60, 'There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.'),
    ('NG', 'office-equipment', 'Office equipment', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 70, 'There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.'),
    ('NG', 'computer-equipment', 'Computer equipment', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 80, 'There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.'),
    ('NG', 'motor-vehicles', 'Motor vehicles', '{}'::jsonb, 'straight_line', 48, null, null, 'asset_fixed', 90, 'There is no legal or fiscal table of useful lives in Nigeria for the accounting charge. IFRS for SMEs, Section 17, paragraphs 17.16 to 17.22, require an entity to allocate the depreciable amount of an item of property, plant and equipment on a systematic basis over its useful life, which the entity estimates and reviews for itself, and to select the method that reflects the pattern in which it expects to consume the asset''s benefits; the Financial Reporting Council of Nigeria has adopted that Standard for small and medium-sized entities (IFRS Foundation jurisdictional profile for Nigeria). Capital allowances under the Nigeria Tax Act 2025 are a tax computation and are never the accounting charge. The duration below is therefore common practice, not a rule read in a Nigerian text, and an asset that depreciates differently says so in its own columns.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

