-- Ekwo OS — Singapore: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/sg/fixed_assets.json at version 0.3.0, do not edit.
-- Change the pack and run `ekwo pack build sg`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the fixed assets module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into fixed_assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('SG', 'months', 'months', 'actual', null, true, 'net_result', 'Singapore law prescribes no method, no prorata and no cap for the depreciation of the financial statements: the Companies Act 1967, s. 201, only requires statements that comply with the accounting standards, and the text of SFRS for Small Entities could not be opened from here, so what it says about when depreciation begins is not quoted. A charge from the month the asset is brought into use, rather than for the whole of the first year, is the common practice and the declared rule; the straight line and the reducing balance are both in use and no ceiling on an annuity is known. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A are a tax computation (IRAS, Explanatory Notes to Form C for YA 2026, and its audit write-up, which says the depreciation of the financial statements is added back) and never the accounting charge.')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into fixed_assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::fixed_assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::fixed_assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('SG', 'goodwill', 'Goodwill', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 10, 'Goodwill and acquired intangibles are amortised over their useful life; ten years is a common practice and not a life anybody estimated for the company. Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'intangibles', 'Other intangible assets, software and licences', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 20, 'Software, licences and similar rights are amortised over their useful life, usually the term of the licence where there is one. Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'leasehold-property', 'Leasehold property', '{}'::jsonb, 'straight_line', 360, null, null, 'asset_fixed', 30, 'A leasehold is depreciated over the shorter of its life and the remaining term of the lease, which is a fact about the lease and not about the category; thirty years is a placeholder to be replaced by the lease term. Land held freehold is not depreciated. Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'renovation', 'Renovation and refurbishment', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 40, 'Renovation works are depreciated over their useful life, capped in practice by the lease term. The tax deduction for renovation under s. 14N is a separate tax computation. Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'plant-and-machinery', 'Plant and machinery', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 50, 'Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'office-equipment', 'Office equipment', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 60, 'Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'computers', 'Computers and IT equipment', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 70, 'Computers are written off in one year for capital allowances under s. 19A(2), which is a tax computation and not the three years used here. Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'furniture-and-fittings', 'Furniture and fittings', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 80, 'Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('SG', 'motor-vehicles', 'Motor vehicles', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 90, 'Singapore sets no legal or fiscal table of accounting useful lives. The Companies Act 1967, s. 201, requires financial statements that comply with the accounting standards, and ACRA names SFRS for Small Entities among them; the text of that standard could not be opened from here (it is served to Singapore addresses only), so no wording of its Sections 17 to 19 is quoted. Capital allowances under the Income Tax Act 1947, ss. 19 and 19A (one year for computers, prescribed automation equipment and items of no more than $5,000 each, three years for other plant and machinery, or the prescribed tax useful life under s. 19) are a tax computation, and IRAS tells companies to add back the depreciation of the financial statements as non-deductible; they are never the accounting charge. The duration below is therefore common Singapore practice and not a rule, and an asset that depreciates differently says so in its own columns.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

