-- Ekwo OS — United Arab Emirates: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/ae/fixed_assets.json at version 0.4.0, do not edit.
-- Change the pack and run `ekwo pack build ae`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the fixed assets module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into fixed_assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('AE', 'days', 'days', 'actual', null, true, 'net_result', 'IFRS for SMEs, Section 17, paragraph 17.20 — depreciation of an asset begins when it is available for use and ceases when it is derecognised; paragraph 17.18 asks for a systematic allocation over the useful life and paragraph 17.22 names the straight-line and the diminishing balance methods among those an entity may select, the one that reflects the pattern in which it expects to consume the asset''s benefits. The standard does not say how a first period is counted: a charge from the day of availability, in real days, is the reading that follows 17.20 most closely, and a company that counts whole months sets prorata = ''months'' on the asset. Neither the standard nor the Corporate Tax Decree-Law caps a declining-balance annuity, which is why no cap is declared.')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into fixed_assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::fixed_assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::fixed_assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('AE', 'goodwill', 'Goodwill', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_non_current', 10, 'IFRS for SMEs, paragraph 19.23 — goodwill is amortised over its useful life, and where that cannot be established reliably the life is management''s best estimate and shall not exceed ten years. Ten years is therefore the ceiling this category starts from and not a life anybody estimated. There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'intangibles', 'Other intangible assets, software and licences', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_non_current', 20, 'IFRS for SMEs, paragraphs 18.19 and 18.20 — an intangible asset has a finite useful life, amortised from the day it is available for use (18.22), and where the life cannot be established reliably it is management''s best estimate and shall not exceed ten years. Five years is practice for software and licences. There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'buildings', 'Buildings', '{}'::jsonb, 'straight_line', 300, null, null, 'asset_fixed', 30, 'Land is not depreciated and the building on it is, so a property is split before this category is applied to the part that has a life. There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'leasehold-improvements', 'Leasehold improvements', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 40, 'IFRS for SMEs, paragraph 17.21(d) names legal limits on the use of the asset, such as the expiry of a lease, among the factors of a useful life: the life is the shorter of the improvement''s own and the remaining term of the lease, which is a fact about the lease and not about the category. There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'plant-and-machinery', 'Plant and machinery', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 50, 'There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'furniture-and-fixtures', 'Furniture and fixtures', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 60, 'There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'office-equipment', 'Office equipment', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 70, 'There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'computer-equipment', 'Computer equipment', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 80, 'There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('AE', 'motor-vehicles', 'Motor vehicles', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 90, 'There is no legal or fiscal table of useful lives in the United Arab Emirates. IFRS for SMEs, Section 17, paragraphs 17.18 and 17.21 (read from the IFRS Foundation''s module 17) require the depreciable amount to be allocated on a systematic basis over a useful life the entity estimates from its own expected usage, wear and tear, obsolescence and legal limits; Federal Decree-Law No. 47 of 2022, Article 20(1) and (2), starts the Taxable Income from the Accounting Income of financial statements prepared under the accounting standards accepted in the State, and the Decree-Law read here sets no depreciation table. The duration below is therefore common practice and not a rule, and an asset that depreciates differently says so in its own columns.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

