-- Ekwo OS — South Africa: how this country depreciates and derecognises a fixed asset.
--
-- Generated from packs/za/fixed_assets.json at version 0.3.0, do not edit.
-- Change the pack and run `ekwo pack build za`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Applied by the module migration runner — `ekwo migrate`, or `ekwo module
-- migrate` — and never by the socle seed step: these tables exist only on an
-- installation that carries the fixed assets module.
--
-- The accounts a disposal lands on are not here. They are roles of the chart,
-- in `country_defaults`, written by the pack seed beside every other role.

insert into fixed_assets.country_rules
  (country, prorata_straight_line, prorata_declining, day_count,
   declining_cap_percent, declining_switch_to_linear, disposal_style, legal_reference)
values
  ('ZA', 'months', 'months', 'actual', null, true, 'net_result', 'IFRS for SMEs, paragraph 17.20 — depreciation of an asset begins when it is available for use, ie when it is in the location and condition necessary for it to be capable of operating in the manner intended by management, so the charge runs from the month the asset is brought into use and not for the whole of the first year; paragraph 17.22 prescribes no method and names the straight-line method, the diminishing balance method and a method based on usage among those an entity may select. The standard does not say how to cut the first period, so counting whole months is practice and not text. Nothing in South African company law caps an annuity, which is why no cap is declared. What this section is **not** is the wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962: Interpretation Note 47 (Issue 5) apportions that allowance for an asset not used throughout the year of assessment and offers the diminishing-value and the straight-line methods, which is a tax computation and never the books.')
on conflict (country) do update set
  prorata_straight_line      = excluded.prorata_straight_line,
  prorata_declining          = excluded.prorata_declining,
  day_count                  = excluded.day_count,
  declining_cap_percent      = excluded.declining_cap_percent,
  declining_switch_to_linear = excluded.declining_switch_to_linear,
  disposal_style             = excluded.disposal_style,
  legal_reference            = excluded.legal_reference;

insert into fixed_assets.category_templates
  (country, code, name, name_i18n, method, duration_months, coefficient,
   prorata, account_type, sequence, legal_reference)
select v.country::char(2), v.code, v.name, v.name_i18n::jsonb,
       v.method::fixed_assets.depreciation_method, v.duration_months::integer,
       v.coefficient::numeric, v.prorata::fixed_assets.prorata_rule,
       v.account_type::account_type, v.sequence::integer, v.legal_reference
  from (values
    ('ZA', 'goodwill', 'Goodwill', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 10, 'IFRS for SMEs, paragraph 19.23 — goodwill is amortised under the principles of paragraphs 18.19 to 18.24, and where its useful life cannot be established reliably the life is management''s best estimate and shall not exceed ten years. Ten years is therefore the ceiling this category starts from and not a life anybody estimated. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'software', 'Computer software', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 20, 'The Annexure to Interpretation Note 47 lists purchased main-frame software at three years, self-developed main-frame software at five years and personal-computer software at two years for the tax allowance; three years is the practice this category starts from, and the Annexure figures are not applied here. IFRS for SMEs, paragraphs 18.19 to 18.23, amortise a finite-life intangible asset over its useful life with a residual value of zero unless the paragraph says otherwise. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'patents-and-licences', 'Patents, trade marks and licences', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 30, 'IFRS for SMEs, paragraph 18.19 — the useful life of an intangible asset that arises from contractual or other legal rights shall not exceed the period of those rights; paragraph 18.20 caps at ten years the life of one whose life cannot be established reliably. The right''s own term is a fact about the contract and not about the category. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'buildings', 'Buildings', '{}'::jsonb, 'straight_line', 600, null, null, 'asset_fixed', 40, 'Land is not depreciated and the building on it is, so a property is split before this category is applied to the part that has a life. Fifty years is a common practice figure; no official table of building lives was read for this pack, and the Annexure to Interpretation Note 47 lists no building. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'leasehold-improvements', 'Leasehold improvements', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 50, 'Practice depreciates an improvement over the shorter of its own life and the remaining term of the lease, which is a fact about the lease and not about the category. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'plant-and-machinery', 'Plant and machinery', '{}'::jsonb, 'straight_line', 120, null, null, 'asset_fixed', 60, 'The Annexure to Interpretation Note 47 lists specific machines at periods from four to twenty years and no general category, so ten years is the practice this category starts from and not a figure of any official text. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'furniture-and-fittings', 'Furniture and fittings', '{}'::jsonb, 'straight_line', 72, null, null, 'asset_fixed', 70, 'The Annexure to Interpretation Note 47 lists furniture and fittings at six years for the tax allowance, and practice commonly takes the same figure for the books; the two agree by habit and not by rule. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'computer-equipment', 'Computer equipment', '{}'::jsonb, 'straight_line', 36, null, null, 'asset_fixed', 80, 'The Annexure to Interpretation Note 47 lists personal computers at three years and main-frames and servers at five for the tax allowance; three years is the practice figure for a personal computer. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'passenger-cars', 'Motor vehicles, passenger cars', '{}'::jsonb, 'straight_line', 60, null, null, 'asset_fixed', 90, 'The Annexure to Interpretation Note 47 lists passenger cars at five years for the tax allowance, and practice commonly takes the same figure for the books; the two agree by habit and not by rule. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.'),
    ('ZA', 'delivery-vehicles', 'Motor vehicles, delivery vehicles', '{}'::jsonb, 'straight_line', 48, null, null, 'asset_fixed', 100, 'The Annexure to Interpretation Note 47 lists delivery vehicles at four years for the tax allowance, and practice commonly takes the same figure for the books; the two agree by habit and not by rule. There is no legal table of useful lives in South Africa for the books: IFRS for SMEs, Section 17, paragraphs 17.18 to 17.22, requires the depreciable amount of an item of property, plant and equipment to be allocated on a systematic basis over its useful life, which the entity estimates and reviews itself. The wear-and-tear allowance of section 11(e) of the Income Tax Act 58 of 1962 and the write-off periods in the Annexure to SARS Interpretation Note 47 (Issue 5, 9 February 2021) are a tax computation and are never the accounting charge. The duration below is therefore common South African practice and not a rule, and an asset that depreciates differently says so in its own columns.')
  ) as v (country, code, name, name_i18n, method, duration_months, coefficient,
          prorata, account_type, sequence, legal_reference)
on conflict (country, code) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  method          = excluded.method,
  duration_months = excluded.duration_months,
  coefficient     = excluded.coefficient,
  prorata         = excluded.prorata,
  account_type    = excluded.account_type,
  sequence        = excluded.sequence,
  legal_reference = excluded.legal_reference;

