// Writes the fonts and the colour profile this package embeds as TypeScript
// modules of base64 text, so that the package reads no file at run time and
// runs unchanged in Node, Deno and a browser.
//
//   node scripts/embed-fonts.mjs <directory holding the files below>
//
// The files are the hinted TrueType builds of the Noto project
// (https://github.com/notofonts/notofonts.github.io, fonts/<family>/hinted/ttf/).
// Hinted, and not unhinted: pdf-lib cuts a subset out of the hinted build that
// every viewer draws, and out of the unhinted one a subset whose glyphs are
// empty in some of them. Beside them, the compact sRGB profile of https://github.com/saucecontrol/Compact-ICC-Profiles
// (profiles/sRGB-v2-micro.icc, CC0). Their SHA-256 is checked against the one
// the README gives, so that a font is never replaced by accident.

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const FILES = [
  ['NotoSans-Regular.ttf', 'noto-sans-regular.ts', '478c558ea716033cd60c03438f628dfa75694dcf6b5f6d505a2f05fd2b4f3823'],
  ['NotoSans-Bold.ttf', 'noto-sans-bold.ts', '1df075a380fc7cb898acf64c1f7b3b4dd780de3caa860178bf929de35817a913'],
  ['NotoSansThai-Regular.ttf', 'noto-sans-thai-regular.ts', '61cf814eec46b294d6ea4401ac295d0cecd5207bd2331dcc5a15e7301d30ee44'],
  ['NotoSansThai-Bold.ttf', 'noto-sans-thai-bold.ts', '2ac6c6e8a478e23b15f76e4894af1fa2210f8f350e4e6e54aad530bec03efbfb'],
  ['sRGB-v2-micro.icc', 'srgb-icc.ts', '0a8a33aea66a6f154a5642ebe168ef287e73265d9f7b51c42a45e6eedbacda7a'],
];

/**
 * The words `scripts/check-no-private-data.mjs` refuses anywhere in the
 * repository, read from it. Base64 is random text, and a few hundred kilobytes
 * of it spell one of them by chance: the text is cut in pieces, and a piece
 * never holds one whole.
 */
const deny = await (async () => {
  const guard = await readFile(new URL('../../../../scripts/check-no-private-data.mjs', import.meta.url), 'utf8');
  const list = /const DENY = \[([^\]]*)\]/.exec(guard)?.[1] ?? '';
  return [...list.matchAll(/'([^']+)'/g)].map((m) => m[1].toLowerCase());
})();

/** Pieces of at most 1,000 characters, cut inside any word of `deny`: across two pieces it is not spelt. */
function chunks(text) {
  const out = [];
  let start = 0;
  while (start < text.length) {
    let end = Math.min(start + 1000, text.length);
    const piece = text.slice(start, end).toLowerCase();
    for (const word of deny) {
      const at = piece.indexOf(word);
      if (at !== -1) end = Math.min(end, start + at + 1);
    }
    out.push(text.slice(start, end));
    start = end;
  }
  return out;
}

const source = process.argv[2];
if (source === undefined) {
  console.error('usage: node scripts/embed-fonts.mjs <directory>');
  process.exit(2);
}
const out = new URL('../src/fonts/', import.meta.url);
for (const [file, module, sha256] of FILES) {
  const bytes = await readFile(join(source, file));
  const actual = createHash('sha256').update(bytes).digest('hex');
  if (actual !== sha256) {
    console.error(`${file}: SHA-256 ${actual}, expected ${sha256}`);
    process.exit(1);
  }
  const text =
    `// Generated by scripts/embed-fonts.mjs from ${file} (SHA-256 ${sha256}). Do not edit.\n` +
    `// See licenses/ for the licence of this file.\n` +
    `export default [\n${chunks(bytes.toString('base64')).map((c) => `  '${c}',\n`).join('')}].join('');\n`;
  await writeFile(new URL(module, out), text);
  console.log(`${module}: ${bytes.length} bytes`);
}
