/**
 * The privileges the schema declares, and how a live database is compared to
 * them.
 *
 * Since `20260914151207` every table, view and function of Ekwo names the
 * roles that may reach it, in the migration that creates it. Before that the
 * privileges came from a Supabase project's default privileges on `public`,
 * which gave `anon` — the role behind the publishable key — `all` on every
 * table of the ledger, and which vanish the day somebody recreates the schema.
 *
 * The declaration travels in `packages/cli/assets/expected-objects.json`,
 * under `grants` in each schema's section: the same inventory that carries the
 * tables, the policies and the triggers a release defines, generated by
 * `scripts/generate-expected-objects.mjs` from a freshly migrated database and
 * committed. One file, because the privileges of an object and the object are
 * the same release. This module reads the same catalogue out of a live
 * installation and says where the two differ:
 *
 *   - a **missing** grant is a problem. It is the failure PostgREST reports as
 *     "permission denied for table companies" to the first user, and it passes
 *     every other check there is.
 *   - an **extra** grant to `anon` is a problem. The anonymous role reaches
 *     the policy helpers and nothing else; anything more is a surface somebody
 *     opened by hand or a default privilege that was never taken away.
 *   - an **extra** grant to `authenticated` or `service_role` is a warning. It
 *     is usually a local customisation and it is never nothing: row level
 *     security is then the only thing refusing a verb the schema meant to
 *     withhold.
 *
 * The SQL that describes a schema lives here rather than in the generator, so
 * that the file and the check can never read the catalogue two different ways.
 * `inventory.ts` calls `describeGrants` to fill the section, and `doctor.ts`
 * calls it again on the live database and hands both to `compareSection`.
 */

/** The three roles a Supabase project exposes to a client. */
export const GRANT_ROLES = ['anon', 'authenticated', 'service_role'] as const;
export type GrantRole = (typeof GRANT_ROLES)[number];

/** Privileges held on one object, by role. Lower case, sorted. */
export type HeldBy = Record<GrantRole, string[]>;

export interface GrantedObject extends HeldBy {
  name: string;
  /** Functions only: the identity arguments that tell an overload apart. */
  arguments?: string;
  /** Functions only, and true when the function returns `trigger`. */
  trigger?: boolean;
}

export interface GrantsSection extends Record<string, unknown> {
  schema: string;
  /** `usage` on the schema itself, which is what makes the rest reachable. */
  usage: HeldBy;
  tables: GrantedObject[];
  views: GrantedObject[];
  sequences: GrantedObject[];
  functions: GrantedObject[];
  /**
   * Default privileges still standing on the schema, as
   * `owner:objtype:role:privilege`. Empty is the point: a privilege that comes
   * from here comes from something no migration wrote.
   */
  defaultPrivileges: string[];
}

/** Rows from one parameterised query. Both PGlite and the CLI client fit. */
export type QueryRows = <T>(sql: string, params: unknown[]) => Promise<T[]>;

const KINDS = `'r', 'p', 'v', 'm', 'S'`;

/**
 * Every privilege one schema hands to the three roles, object by object.
 *
 * `aclexplode` turns an `aclitem[]` into one row per grantee and privilege,
 * which is the only shape worth comparing: the text form of an ACL depends on
 * the owner's name and on the order the privileges happen to sit in. The
 * owner's own grants are dropped — they are not a declaration, they are what
 * owning a table means.
 */
export async function describeGrants(rows: QueryRows, schema: string): Promise<GrantsSection> {
  const q = <T>(sql: string) => rows<T>(sql, [schema]);

  const relations = await q<{ key: string; grantee: string; privilege: string }>(
    `select c.relname as key,
            pg_get_userbyid((aclexplode(c.relacl)).grantee) as grantee,
            lower((aclexplode(c.relacl)).privilege_type) as privilege
       from pg_class c
       join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = $1 and c.relkind in (${KINDS})`,
  );

  const names = await q<{ name: string; kind: string }>(
    `select c.relname as name, c.relkind as kind
       from pg_class c
       join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = $1 and c.relkind in (${KINDS})
      order by c.relname`,
  );

  const functions = await q<{ name: string; arguments: string; is_trigger: boolean }>(
    `select p.proname as name,
            pg_get_function_identity_arguments(p.oid) as arguments,
            p.prorettype::regtype::text = 'trigger' as is_trigger
       from pg_proc p
       join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = $1
      order by p.proname, pg_get_function_identity_arguments(p.oid)`,
  );

  const functionAcl = await q<{ key: string; grantee: string; privilege: string }>(
    `select p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' as key,
            pg_get_userbyid((aclexplode(p.proacl)).grantee) as grantee,
            lower((aclexplode(p.proacl)).privilege_type) as privilege
       from pg_proc p
       join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = $1`,
  );

  // `create` on the schema is not a client privilege and is not Ekwo's to
  // declare: a Supabase project gives it to `postgres` and `service_role`, and
  // a self-hosted one may give it to whoever runs the migrations.
  const schemaAcl = (
    await q<{ key: string; grantee: string; privilege: string }>(
      `select n.nspname as key,
              pg_get_userbyid((aclexplode(n.nspacl)).grantee) as grantee,
              lower((aclexplode(n.nspacl)).privilege_type) as privilege
         from pg_namespace n
        where n.nspname = $1`,
    )
  ).filter((r) => r.privilege !== 'create');

  const defaults = (
    await q<{ owner: string; object: string; grantee: string; privilege: string }>(
      `select pg_get_userbyid(d.defaclrole) as owner,
              d.defaclobjtype as object,
              pg_get_userbyid((aclexplode(d.defaclacl)).grantee) as grantee,
              lower((aclexplode(d.defaclacl)).privilege_type) as privilege
         from pg_default_acl d
         join pg_namespace n on n.oid = d.defaclnamespace
        where n.nspname = $1`,
    )
  )
    .filter((r) => (GRANT_ROLES as readonly string[]).includes(r.grantee))
    .map((r) => `${r.owner}:${r.object}:${r.grantee}:${r.privilege}`)
    .sort();

  const held = (acl: { key: string; grantee: string; privilege: string }[], key: string): HeldBy => {
    const out = {} as HeldBy;
    for (const role of GRANT_ROLES) {
      out[role] = acl
        .filter((r) => r.grantee === role && r.key === key)
        .map((r) => r.privilege)
        .sort();
    }
    return out;
  };

  const section = (kinds: string[]): GrantedObject[] =>
    names
      .filter((n) => kinds.includes(n.kind))
      .map((n) => ({ name: n.name, ...held(relations, n.name) }));

  return {
    schema,
    usage: held(schemaAcl, schema),
    tables: section(['r', 'p']),
    views: section(['v', 'm']),
    sequences: section(['S']),
    functions: functions.map((f) => ({
      name: f.name,
      arguments: f.arguments,
      ...(f.is_trigger ? { trigger: true } : {}),
      ...held(functionAcl, `${f.name}(${f.arguments})`),
    })),
    defaultPrivileges: defaults,
  };
}

export type Difference = 'missing' | 'extra';

export interface GrantFinding {
  schema: string;
  /** `table entries`, `function post_entry(p_entry_id uuid)`. */
  object: string;
  role: GrantRole;
  difference: Difference;
  /** The privileges that are missing, or the ones that are too many. */
  privileges: string[];
}

/** One object, expected against actual, for the three roles. */
function compareObject(
  schema: string,
  label: string,
  expected: HeldBy | undefined,
  actual: HeldBy | undefined,
  found: GrantFinding[],
): void {
  for (const role of GRANT_ROLES) {
    const want = new Set(expected?.[role] ?? []);
    const have = new Set(actual?.[role] ?? []);
    const missing = [...want].filter((p) => !have.has(p)).sort();
    const extra = [...have].filter((p) => !want.has(p)).sort();
    if (missing.length > 0) {
      found.push({ schema, object: label, role, difference: 'missing', privileges: missing });
    }
    if (extra.length > 0) {
      found.push({ schema, object: label, role, difference: 'extra', privileges: extra });
    }
  }
}

const label = (o: GrantedObject, kind: string): string =>
  kind === 'function' ? `function ${o.name}(${o.arguments ?? ''})` : `${kind} ${o.name}`;

/** Every difference between what a schema declares and what it holds. */
export function compareSection(expected: GrantsSection, actual: GrantsSection): GrantFinding[] {
  const found: GrantFinding[] = [];
  compareObject(expected.schema, `schema ${expected.schema}`, expected.usage, actual.usage, found);

  for (const [kind, key] of [
    ['table', 'tables'],
    ['view', 'views'],
    ['sequence', 'sequences'],
    ['function', 'functions'],
  ] as const) {
    const wanted = expected[key];
    const held = actual[key];
    const byKey = new Map(held.map((o) => [label(o, kind), o]));
    for (const object of wanted) {
      const name = label(object, kind);
      // An object that is not there at all is the inventory of objects'
      // business — `ekwo doctor` reports a pending migration for that. Here it
      // would only produce a second, noisier way of saying the same thing.
      const counterpart = byKey.get(name);
      if (counterpart === undefined) continue;
      compareObject(expected.schema, name, object, counterpart, found);
      byKey.delete(name);
    }
    // What is left is an object this release never declared. Its grants are
    // still worth reporting when they reach `anon`: a table somebody added by
    // hand, readable without signing in, is the shape of the hole this whole
    // change is about.
    for (const [name, object] of byKey) {
      compareObject(expected.schema, name, undefined, object, found);
    }
  }
  return found;
}

/** A finding as one line of the doctor's output. */
export function describeFinding(finding: GrantFinding): string {
  const verb = finding.difference === 'missing' ? 'is missing' : 'holds an extra';
  return `${finding.schema}.${finding.object}: ${finding.role} ${verb} ${finding.privileges.join(', ')}`;
}
